### ISSUE TITLE
ERL-291: https, message digests, file signing for the downloads

### ISSUE THREAD

**Issue by OTP-Maintainer** [erlang/otp#3216]
Original reporter: `bugreport`
Affected version: `Not Specified`
Component: `Not Specified`
Migrated from: https://bugs.erlang.org/browse/ERL-291

---

```
make it possible to download from http://erlang.org/download with https

redirect http to https

create a 4096-bit RSA keypair with gnupg to make detached signatures for the files with it

never use md5 and/or sha1, use sha512
```

**Comment by proxyles** [comment]
We have made some improvements in this area, and will look into changing the hash algorithm in the future,
