### ISSUE TITLE
ERL-235: Make ssh_sftp: list_dir return more information

### ISSUE THREAD

**Issue by OTP-Maintainer** [erlang/otp#3352]
Original reporter: `verma`
Affected version: `Not Specified`
Component: `ssh`
Migrated from: https://bugs.erlang.org/browse/ERL-235

---

```
{{ssh_sftp:list_dir}} returns the remote listing at a given path. The listing is a list of names of type {{string()}}.  Apart from listing what's in a remote directory, this function seems to have a very limited use.

It would be nice if it could return some more information about each item, e.g. whether its a file or a directory, its size, ctime, atime etc.  There is a {{readdir}} function which can be used for this purpose but list_dir seems to be doing all of the accumulator loop stuff already.  Another option is to call read_file_info on each item.

This sort of functionality would be handy if provided by the stdlib.

May be we can get another function {{list_dir_details}} or something similar that gives us more information about the listing? May be {{Name, Info}} tuples?  I would think {{ssh_xfer_attr}} record would need to be exposed as well and put in an {{include}} directory may be.

I can work on a PR if it seems something like this would be useful.

Thanks!

Edit: Couple of format edits.
```

**Comment by arjan** [comment]
Has anyone every worked on this? I'm bumping into this now while using the sftpd application on a Nerves-powered music radio; uploading files is pretty annoying if you can't change directories easily; the directory bit is missing from file listings so user interfaces present directories as files.

**Comment by arjan** [comment]
Oh, I actually found the culprit, it is a bug in the client, not the server:
https://trac.filezilla-project.org/ticket/11779: "Filezilla SFTP Client see folders as regular files"

**Comment by KennethL** [comment]
I think we can close this since it seemed to be a problem with the client.
