### ISSUE TITLE
ERL-1230: BLAKE3 support

### ISSUE THREAD

**Issue by OTP-Maintainer** [erlang/otp#3430]
Original reporter: `JIRAUSER14705`
Affected version: `Not Specified`
Component: `crypto`
Migrated from: https://bugs.erlang.org/browse/ERL-1230

---

```
Can you add BLAKE3 support?
- [https://github.com/BLAKE3-team]
- [https://github.com/BLAKE3-team/BLAKE3]
- [https://github.com/BLAKE3-team/BLAKE3-specs]

Thanks in advance.
```

**Comment by gmile** [comment]
If understand correctly, Erlang will not adopt Blake 3, since it's not part of OpenSSL. So, FWIW there's an ongoing discussion about including Blake3 into OpenSSL, just liking it here for future reference: https://github.com/openssl/openssl/issues/11613
