### ISSUE TITLE
ERL-1439: Common Test: config leaks between groups

### ISSUE THREAD

**Issue by OTP-Maintainer** [erlang/otp#3480]
Original reporter: `roadrunnr71`
Affected version: `OTP-23`
Component: `common_test`
Migrated from: https://bugs.erlang.org/browse/ERL-1439

---

```
The attached minimal sample uses a nested group structure. The problem occurs only when the last group in the nested group is skipped.

The config option set in init_per_group for the top level group is leaking into the next top level group.

 
```

**Comment by u3s** [comment]
I can't reproduce the leakage in the next SUITE variant. Can more details be provided on how to reproduce leakage between suites?
