### ISSUE TITLE
ERL-311: Support for RFC5077 in erlang ssl module

### ISSUE THREAD

**Issue by OTP-Maintainer** [erlang/otp#3619]
Original reporter: `silviu`
Affected version: `Not Specified`
Component: `ssl`
Migrated from: https://bugs.erlang.org/browse/ERL-311

---

```
Resuming ssl sessions using tickets is not possible because RFC5077 is not supported.

```

**Comment by IngelaAndin** [comment]
We do not plan to support this, we recommend TLS-1.3 instead
