### ISSUE TITLE
ERL-771: CAA record support

### ISSUE THREAD

**Issue by OTP-Maintainer** [erlang/otp#3984]
Original reporter: `fleximus`
Affected version: `OTP-21.1.1`
Component: `kernel`
Migrated from: https://bugs.erlang.org/browse/ERL-771

---

```
Please add [CAA|https://en.wikipedia.org/wiki/DNS_Certification_Authority_Authorization] ([RFC 6844|https://tools.ietf.org/html/rfc6844]) lookup support to inet_res.
```

**Comment by RaimoNiskanen** [comment]
Sorry for missing this issue, partially thanks to transfer of issue between issue systems, but CAA support was added by #2827 and released in OTP-24.0 on May 5, 2021.
