### ISSUE TITLE
ERL-1480: Add `no_underspecs` to `-dialyzer(_).`

### ISSUE THREAD

**Issue by OTP-Maintainer** [erlang/otp#4033]
Original reporter: `paulo.ferraz.oliveira@gmail.com`
Affected version: `Not Specified`
Component: `Not Specified`
Migrated from: https://bugs.erlang.org/browse/ERL-1480

---

```
I'd like it to be possible to suppress `underspecs` in a single function, while having it enabled for all the others.

I ran into an issue (reported here: [https://github.com/tomas-abrahamsson/gpb/issues/196)] whose solution might be this "option".

I see that something similar's been discussed in ERL-1379, already, but it appears it was abandoned.

This is especially useful when (like with `gpb`) our code includes generated code, whose analysis we can't suppress.
```

**Comment by uabboli** [comment]
As per your suggestion I've added no_underspecs in GH-4517. Considered adding more options, but this is the only one that really adds something, I think.

**Comment by paulo-ferraz-oliveira** [comment]
Great, thanks. I think we can close this one.

**Note**: I find developers of code generators will like it :-) since it'll allow to be as detailed as possible, in some cases, while maintaining a more default strictness, on others.

**Comment by paulo-ferraz-oliveira** [comment]
Worked flawlessly (tested in a very small code base).
