### ISSUE TITLE
ERL-1101: An application crashes with bad_return error when top-level supervisor returns 'ignore' atom

### ISSUE THREAD

**Issue by OTP-Maintainer** [erlang/otp#4048]
Original reporter: `JIRAUSER12801`
Affected version: `OTP-22.1`
Component: `Not Specified`
Migrated from: https://bugs.erlang.org/browse/ERL-1101

---

According to the docs, supervisor, when starting, can either return a `{ok, {SupFlags, [ChildSpec]}}` tuple or an atom 'ignore' ([doc](https://www.erlang.org/doc/man/supervisor.html#Module:init-1)). And this works perfect for any standalone supervisors started by hand or by other supervisor.

Problems start when you try to use `ignore` keyword for a top-level supervisor of an application. Like in any usual configuration, which has been generated from the template:

```
-module(app_app).
-behaviour(application).
-export([start/2, stop/1]).

start(_StartType, _StartArgs) ->
    app_sup:start_link().

stop(_State) ->
    ok.
```
Plus custom supervisor:

```
-module(app_sup).
-behaviour(supervisor).
-export([start_link/0]).
-export([init/1]).
-define(SERVER, ?MODULE).

start_link() ->
    supervisor:start_link({local, ?SERVER}, ?MODULE, []).

init([]) ->
    ignore.
```
 
Launching such degenerate application explodes with `bad_return` error and scary crash report logs:

```
=CRASH REPORT==== 25-Nov-2019::09:01:57.339059 ===
  crasher:
    initial call: application_master:init/4
    pid: <0.129.0>
    registered_name: []
    exception exit: {bad_return,{{app_app,start,[normal,[]]},ignore}}
      in function  application_master:init/4 (application_master.erl, line 138)
    ancestors: [<0.128.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.130.0>,normal}]
    links: [<0.128.0>,<0.43.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 207
  neighbours:===> Failed to boot app for reason {bad_return,
                                               {{app_app,start,[normal,[]]},
                                                ignore}}
=INFO REPORT==== 25-Nov-2019::09:01:57.342105 ===
    application: app
    exited: {bad_return,{{app_app,start,[normal,[]]},ignore}}
    type: temporary
```

And yes, this is not entirely a bug, rather a certain inconsistency in OTP.  An application without a top-level supervisor should not be started regardless, but the returned error, for sure could be handled in a better way.

**Comment by sverker** [comment]
I'm closing this. I don't consider this a bug. Atom `ignore` is not a documented accepted return value from application `start` callback. And the error report says just that; `bad_return`.
