### ISSUE TITLE
ERL-1251: ftp:nlist returns ok

### ISSUE THREAD

**Issue by OTP-Maintainer** [erlang/otp#4177]
Original reporter: `JIRAUSER15005`
Affected versions: `OTP-23.0`, `OTP-22.3.1`
Fixed in versions: `OTP-22.3.4.2`, `OTP-23.1`
Component: `Not Specified`
Migrated from: https://bugs.erlang.org/browse/ERL-1251

---

```
Frequently, when calling {{ftp:nlist/2}} a bare {{ok}} atom is returned, as opposed to a list result or error.

I've only observed this behavior since upgrading from OTP 21.0.7 to OTP 22.3.2.  I was also able to reproduce with OTP 23.0

I can reliably reproduce if additional debug/trace is required
```

**Comment by vermaxik** [comment]
>Frequently, when calling {{ftp:nlist/2}} a bare {{ok}} atom is returned, as opposed to a list result or error.

I encounter this issue in `24.2`, going to create an issue.
