### ISSUE TITLE
ERL-1224: Erlang OTP64 EXE Missing Properties

### ISSUE THREAD

**Issue by OTP-Maintainer** [erlang/otp#4232]
Original reporter: `JIRAUSER14701`
Affected version: `Not Specified`
Component: `otp`
Migrated from: https://bugs.erlang.org/browse/ERL-1224

---

```
The OTP64 Windows EXE binary is missing values for "File version" and "Product version", which when coupled with Chocolatey doesn't allow for dynamic discovery of the binary version and needs to be hardcoded or cross-referenced.

I would like to request for all future OTP64 and OTP32 Windows EXE binaries to include valid file properties in the Windows EXE to include:
 * File version (should match version of binary, e.g. 22.3.0.0)
 * Product version (should match version of binary, e.g. 22.3.0.0)
 * Product name (e.g. OTP64)
```

**Comment by dgud** [comment]
Closed by #5319

**Comment by inikulshin** [comment]
@dgud I think, this bug is different and can't be closed by #5319.

This bug is about VERSIONINFO resource of **Windows installers** (e. g. `otp_win64_*.exe`), not `erl.exe`.

**Comment by inikulshin** [comment]
@dgud I also suggest to change

For `erl.exe`
- `LegalCopyright` to `Copyright Ericsson AB 2010-2021. All Rights Reserved.`. like here https://github.com/erlang/otp#license)
- `FileDescription` to `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator` or `Erlang emulator`, like `erl.exe -version` outputs
- `CompanyName` to `Ericsson AB`, like in `LegalCopyright`
- `ProductName` - probably to `Erlang OTP`, like in registry key `HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Erlang OTP 24 (12.1.5)`

For `otp_win*.exe` same VERRSIONINFO, like for `erl.exe`, except
`FileDescription` which should be `%ProductName% installer` or `%ProductName% setup`

**Comment by inikulshin** [comment]
@garazdawi FYI

**Comment by lukebakken** [comment]
I checked erl.exe and it has correct file information. The installer doesn't but I don't really think anyone cares. The RabbitMQ team is going to take over the Erlang Chocolatey package, so if it matters there I'll open a new issue and will link to this.

**Comment by inikulshin** [comment]
@lukebakken our QA cares :)
We install Erlang and RabbitMQ on customer's machines and QA don't like our package contains 3rd party binaries without details (VERSIONINFO). The Erlang installer is signed by Ericsson AB certificate, but that's not perfect.

Also, it could be great to be able to get both OTP version (e.g. 25.2) and erts version (e.g. 13.1.3) from the installer.

**Comment by lukebakken** [comment]
@inikulshin please check out the "Windows Installer" artifact here: https://github.com/erlang/otp/pull/6587

The PR appears to address this issue (#4232)
