### ISSUE TITLE
ERL-128: Close stdin of a port

### ISSUE THREAD

**Issue by OTP-Maintainer** [erlang/otp#4326]
Original reporter: `fnanninga`
Affected version: `Not Specified`
Component: `erts`
Migrated from: https://bugs.erlang.org/browse/ERL-128

---

```
There is no way to close the stdin of a port (send EOF). This is necessary for piping data to programs which usually read from a file but can read from stdin.

It's possible to work around this by creating a wrapper executable and communicating with that wrapper through some frame format; but the effort seems out of proportion with the effort needed to add this feature to Erlang.

Using named pipes instead seems not to be an option as as far as I know Erlang does not support those.

*EDIT:* I still want to be able to receive future data from the program, so erlang:close_port/1 is too much.
```

**Comment by bezborodow** [comment]
I have also implemented a patch on https://github.com/erlang/otp/compare/master...bezborodow:otp:port_eof and am currently working on a test case.

I have just noticed https://github.com/rinpatch/otp/commit/ce8d0750b7e441a66be065fb272727825f3bb4a9 and will look to it for further inspiration.

**Comment by bezborodow** [comment]
I have also implemented a test case, but would need feedback and review.

**Comment by adkron** [comment]
I need this. I must send something on STDIN, and the output returns on STDOUT. The issue is that STDOUT closes when I try to get an EOF to STDIN.

**Comment by ivanov** [comment]
I am not sure if this issue was closed as "won't fix" or just accidentally closed at the same time that it was marked as a low priority feature. 

I also came across this issue today, and found some of the resources linked from @bezborodow's #6824 summary description useful to peruse for possible workarounds, along with [the comparisons in `Rambo` README](https://github.com/jayjun/rambo#comparisons). Hope that helps you figure out some paths forward.

**Comment by adamwight** [comment]
I ran into the same need, when interfacing with the `bzip2` binary, which won't send the last packet of data until it knows its input is fully consumed.

It would be nice if the port call looked something like this, and the implementation between port and the spawn driver can be opaque.
```erlang
erlang:port_command(Port, eof)
```

**Comment by Nicd** [comment]
This has been closed as "completed", though it seems it has not been completed. Can we reopen this or mark it as "won't fix" if that is the resolution?

**Comment by adamwight** [comment]
There seemed to be interest from the core team in PR #9453, which is a slightly different approach to a related problem: the child process of a forker port will receive a SIGTERM when the port is closed or when the BEAM exits.  I got bogged down in the Windows implementation but the basic idea feels consistent with the OTP paradigm generally.

**Comment by mjsir911** [comment]
btw multiiple libraries are around *just* to solve this problem:

- https://github.com/shortishly/grimsby
- https://github.com/saleyn/erlexec
