### ISSUE TITLE
ERL-1420: Stuck in ssl:send when internal_active_n != 1

### ISSUE THREAD

**Issue by OTP-Maintainer** [erlang/otp#4349]
Original reporter: `essen`
Affected version: `Not Specified`
Component: `ssl`
Migrated from: https://bugs.erlang.org/browse/ERL-1420

---

```
This issue only occurs on *Windows*. Tested on Windows 10.

This is a followup to https://bugs.erlang.org/browse/ERL-960 where the attached test case now works reliably, but the more general problem seems to remain.

I have test cases that heavily send data via ssl:send. When a single test is run, there is typically no problem. When multiple tests run at the same time and internal_active_n=1 there is no problem. When multiple tests run at the same time and internal_active_n=$DEFAULT then the ssl:send gets stuck.

I do not have an easy to use test case to reproduce this issue. On the other hand it should be reproducible by cloning Ranch and running a specific test suite. I can reproduce this with all versions of OTP >= 22.0 at least.

{{git clone [https://github.com/ninenines/ranch]}}

{{cd ranch}}

{{git checkout windows-ssl-active-n}}

{{make ct-sendfile t=ssl}}

You should have timeouts and timetrap timeouts. If I remove the timetrap timeout then the tests simply never finish.

I'd appreciate help in solving this issue.
```

**Comment by max-au** [comment]
@essen  this bug actually reminds me very much of a tricky corruption I fixed in https://github.com/erlang/otp/pull/2701 - could you test/see if this is actually fixed with the PR?

**Comment by essen** [comment]
Based on the PR merge and release dates I believe your fix is part of 23.1, with which I could observe this issue.

**Comment by max-au** [comment]
Very true, it is in OTP 21.1. It also seems to be Windows-specific, which I must admit I haven't tested.
Does setting internal_active_n to 2 work? If not, it means that only {active, once} works on Windows.

**Comment by essen** [comment]
I do not remember. I'll try and get back to you on that when I can.

**Comment by essen** [comment]
Sorry it took so long to come back to you.

Unfortunately it's harder to tell what's happening now because I'm getting `timetrap_timeout` even when internal_active_n is set to 1. It happens with 23.2 as well as older versions.

I suspect it is more a combination of VirtualBox+Windows+OTP than it is a plain OTP issue.

I'm happy to just close this as I'm unlikely to have time debugging this in the near future.
