### ISSUE TITLE
ERL-1469: Add `shortest` to float_to_list/2 and float_to_binary/2 options, using Ryu

### ISSUE THREAD

**Issue by OTP-Maintainer** [erlang/otp#4492]
Original reporter: `JIRAUSER17203`
Affected version: `Not Specified`
Component: `kernel`
Migrated from: https://bugs.erlang.org/browse/ERL-1469

---

```
Right now, there is 2 different ways to get a float into a string in OTP. All the others boil down to these two.
 * float_to_list/2 and float_to_binary/2
 * io_lib_format:fwrite_g/1

The first is a BIF that call to various libc sprintf and in certain case an optimised case written directly in kernel and support the classic %e and %f. The second is a pure erlang implementation of a shortest round_trip printing procedure (with a few added rules).

There has been interesting work in the past few years to get an order of magnitude faster algorithms for shortest round trip float to string conversion in C in relatively simple ways. What we offer here is to use the Ryu https://github.com/ulfjack/ryu algorithm to add a `shortest` option to the BIFs. And then `io_lib_format:fwrite_g/1` can delegate to the BIFs. We hope that this would yield a faster algorithm and make it easier to follow what is happening upstream.

On top of that, while `io_lib_format:fwrite_g/1` is technically a private and undocumented function, but is is used in the wild, in particular in the json library Jason. There is ground to make it public in a BIF, to allow better support.

We offer to use Microsoft STL test suite for charconv, which is implemented with Ryu, to test this new implementation https://github.com/microsoft/STL/tree/master/tests/std/tests/P0067R5_charconv

Left for latter is the possibility to make this `shortest` the default option in `float_to_list/1` which right now use {scientific,20} as the default.

This would stay in line with being compatible with `list_to_float`  and would not lose any capability as both the BIFs and `io_lib_format:fwrite_g/1` ignore locales already.
```

**Comment by OTP-Maintainer** [comment]
`JIRAUSER17203` said:

The EEF has shown interest in possibly financing me to do this work if the OTP team would be interested in this.

I think the main possible problem is to make public something that was private and the possibly maintainability cost for a code that has been heavily stable.

I think these are acceptable in this case.

**Comment by DianaOlympos** [comment]
So i am beginning work on this, as the EEF approved the funding. 

on the other issue #4452 , you mentionned vendoring like `pcre` @garazdawi and then wrapping the call in a bif. I am not sure it is what we want here. Couple of reasons.

- Ryu in the upstream version has a lot of different functionalities we do not need or want. We could probably only vendor some files though. That could be done like `pcre` by just dropping it
- Ryu in the upstream version only output in the shortest scientific format. If we want to follow what `fwrite_g/1` does in the stdlib, we need to do our own "printing to string" version, with quite a bunch of edge cases. We could patch that in our version too ofc but that become more brittle
- Finally Ryu depends on a lot of intrinsics https://github.com/ulfjack/ryu/blob/master/ryu/d2s_intrinsics.h and https://github.com/ulfjack/ryu/blob/master/ryu/common.h that i do not know how we want to vendor.

My current idea is to vendor like `pcre`, drop the "to_string" part in the file, write the to_string in the BIF and wrap the calls to Ryu in the BIFs. With the intrinsics and the lookup table living in the Ryu folder.

I _think_ we do not have to wrap it to make it resumable as it is already fast, in the 50ns range. I will check that once i get some code running with that strategy defined above. I will try to build a makefile for it anyway. What do you think ?

**Comment by DianaOlympos** [comment]
Also of note, i think the name of the option should be `pretty_print`, as we will need to keep the large int rule that was introduced in otp24, which means it will not be "shortest" all the time,

**Comment by josevalim** [comment]
What do you think about reusing the option `compact`? Today it only makes sense with `decimals`, so we could add a meaning if `compact` is used without `decimals`.

**Comment by DianaOlympos** [comment]
I personally am against because it would be overloading that options with two different meaning.

I think it would make more sense to add an option than overload an existing one. This case is still under control in term of options, it is far easier to document one more option and i am not sure options are really expensive here to deal with.

Do you see advantages on overloading `compact` ?

**Comment by josevalim** [comment]
I don't see it as overloading but rather making an option that already exists more useful after you said `shortest` is not optimal and given there is no ambiguity here. But I am fine with whatever option, it is not the most relevant aspect of the work. :)

**Comment by garazdawi** [comment]
The goal with change this from our point of view is to decrease the maintenance burden by including the Ryu codebase as is. We do not want to have to maintain our own version of Ryu in C. I'm not familiar enough with the Ryu library to say how it would be possible to include as much as we need but as little as possible while also allowing us to easily take patches in the future.

> My current idea is to vendor like pcre, drop the "to_string" part in the file, write the to_string in the BIF and wrap the calls to Ryu in the BIFs. With the intrinsics and the lookup table living in the Ryu folder.

Without having looked deeper into how the Ryu lib is structured this seems like a reasonable approach.

> I think we do not have to wrap it to make it resumable as it is already fast, in the 50ns range.

Agreed.

**Comment by garazdawi** [comment]
Also, just to make it clear. This change will not be part of OTP-24.0.

**Comment by kjellwinblad** [comment]
Added label "in progress" as this is being implemented in PR-4719

**Comment by kjellwinblad** [comment]
Closing this as https://github.com/erlang/otp/pull/4719 that implements this has been merged.
