### ISSUE TITLE
TLS Hostname Check Should NOT be Case Sensitive

### ISSUE THREAD

**Issue by andrewcln** [erlang/otp#4500]
**Description**
When making a TLS connection with the `verify` option set to `verify_peer` and the `customize_hostname_check` option set to `[{match_fun, public_key:pkix_verify_hostname_match_fun(https)}]`, the check applied when comparing the server name with the subject alt name in the certificate is case-sensitive and will return a `hostname_check_failed` error.

**To Reproduce**
This can be easily reproduce with a site that uses an upper-case hostname in its certificate:

```
O1 = [
    {server_name_indication, "www.dvtaonlineni.gov.uk"},
    {verify, verify_peer}, 
    {cacertfile,CA-CERT-FILE},
    {customize_hostname_check, [{match_fun, public_key:pkix_verify_hostname_match_fun(https)}]}
],
ssl:connect("194.73.120.150", 443, O1).

O2 = [
    {server_name_indication, "WWW.DVTAONLINENI.GOV.UK"},
    {verify, verify_peer}, 
    {cacertfile,CA-CERT-FILE},
    {customize_hostname_check, [{match_fun, public_key:pkix_verify_hostname_match_fun(https)}]}
],
ssl:connect("194.73.120.150", 443, O2).
```

**Expected behavior**
The first connection in the example above should have returned an OK response with a connected TLS socket.

**Affected versions**
Found in OTP 23.1

**Comment by IngelaAndin** [comment]
Seems to be an oversight in the public_key:pkix_verify_hostname_match_fun/1 function. We will fix it.

**Comment by andrewcln** [comment]
Thanks Ingela!

**Comment by dgud** [comment]
Merged to maint
