### ISSUE TITLE
Dialyzer --check_plt should not crash on unfound beam files.

### ISSUE THREAD

**Issue by acw224** [erlang/otp#4501]
**Bug description**

If a beam file is indexed in a plt file,  and dialyzer is not unable to find this one at runtime when ran with --check_plt option, it will crash with the following message:

Checking whether the PLT _localPlt is up-to-date...{"init terminating in do_boot",{{case_clause,{{nocatch,{dialyzer_error,[70,105,108,101,32,110,111,116,32,102,111,117,110,100,58,32,"/home/thomasdavid/otp/Test/boolean.beam",10]}},[{dialyzer_plt,compute_md5_from_file,1,[{file,"dialyzer_plt.erl"},{line,543}]},{dialyzer_plt,compute_new_md5_1,3,[{file,"dialyzer_plt.erl"},{line,509}]},{dialyzer_plt,check_plt1,3,[{file,"dialyzer_plt.erl"},{line,479}]},{dialyzer_plt,'-subproc/1-fun-0-',1,[{file,"dialyzer_plt.erl"},{line,603}]}]}},[{dialyzer_cl,check_plt,3,[{file,"dialyzer_cl.erl"},{line,250}]},{dialyzer_cl,plt_common,3,[{file,"dialyzer_cl.erl"},{line,183}]},{dialyzer,'-cl_check_init/1-fun-0-',1,[{file,"dialyzer.erl"},{line,94}]},{dialyzer,doit,1,[{file,"dialyzer.erl"},{line,236}]},{dialyzer,plain_cl,0,[{file,"dialyzer.erl"},{line,56}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}

It should instead consider them as being removed, warn the user, and update the plt accordingly instead of throwing errors.

**Steps To Reproduce:**

given an erl file file.erl.
erlc +debug_info file.erl
touch _localPlt
dialyzer --build_plt file.beam --plt _localPlt
rm file.beam
dialyzer --check_plt --plt _localPlt

-> crashes as specified above.

**Expected Behaviour:**
"Warning: file.beam not present -- updating the plt).
done"

**Affected versions**
Tested with r23

**Comment by uabboli** [comment]
Merged commit 6f1e0189be893db6bc78db15e039c597a90dbb43 to erlang:maint. Missing files still need to be removed from the PLT with option --remove_from_plt.
