### ISSUE TITLE
Scheduler module: Ignoring online schedulers

### ISSUE THREAD

**Issue by tak30** [erlang/otp#4502]
**Describe the bug**
When running inside docker with the flag --cpus the online schedulers are properly configured but the module scheduler reports all possible schedules utilization and not only the online.  

**To Reproduce**

1. Run otp 23 inside a docker container with cpus flag: 
```
   docker run --cpus 2 -it erlang:23.2.4 /bin/bash 
   erl
```
2. Check online schedulers: ```erlang:system_info(schedulers_online).```
3. Check scheduler utilization: ```scheduler:utilization(scheduler:sample()).```

You will see that the scheduler utlization reports more schedulers than the N that schedulers_online reported.

**Expected behavior**
Calls to the module scheduler should report only utilization of the online schedulers.

**Affected versions**

 OTP 23.*

Note: I didn't put prior versions to otp 23 as affected by this issue as prior to otp 23 there was no support for cpu limits inside containers.

**Additional context**

**Comment by sverker** [comment]
I'm not sure this is worth "fixing". Keeping it as is

- does not risk any backward compatibility problems.
- may give you a couple of extra inactive offline schedulers in the list that can be ignored.
- do result in a different 'total' value. But the 'total' value is dubious anyway as it contains all dirty-cpu schedulers that may very well all be inactive.
- does not affect the 'weighted' value.

**Comment by tak30** [comment]
Hi, thanks a lot for taking a look at the issue.

Which seems strange to me is that all schedulers report utilization, I would expect that those schedulers "not online" should report an utilization of 0%. Also we have seen that most of the time one scheduler is almost 100%. Example of a 12 core host with 2 cores available:

```
2> io:format("~p", [scheduler:utilization(scheduler:sample())]).
[{total,0.06198379665575581,"6.2%"},
 {weighted,0.12396759331151162,"12.4%"},
 {normal,1,1.0,"100.0%"},
 {normal,2,0.0643971273935827,"6.4%"},
 {normal,3,0.061633875799530405,"6.2%"},
 {normal,4,0.050678467996485635,"5.1%"},
 {normal,5,0.06317929065710347,"6.3%"},
 {normal,6,0.04405369144916358,"4.4%"},
 {normal,7,0.030897090040044255,"3.1%"},
 {normal,8,0.05600799519336589,"5.6%"},
 {normal,9,0.02001999093434373,"2.0%"},
 {normal,10,0.026704984358213196,"2.7%"},
 {normal,11,0.02766046111605335,"2.8%"},
 {normal,12,0.037758994287351584,"3.8%"},
 {cpu,13,0.0,"0.0%"},
 {cpu,14,0.0,"0.0%"},
 {cpu,15,0.0,"0.0%"},
 {cpu,16,0.0,"0.0%"},
 {cpu,17,0.0,"0.0%"},
 {cpu,18,0.0,"0.0%"},
 {cpu,19,0.0,"0.0%"},
 {cpu,20,0.0,"0.0%"},
 {cpu,21,0.0,"0.0%"},
 {cpu,22,0.0,"0.0%"},
 {cpu,23,0.0,"0.0%"},
 {cpu,24,0.0,"0.0%"}]
```

On the other hand, if this is not worth fixing it and I would like to check the utilization of my online schedulers. How should I do it? Is there other way?

Thanks!!

**Comment by sverker** [comment]
Don't do `scheduler:utilization(scheduler:sample())`. This is the same as
```
S1 = scheduler:sample(),
S2 = scheduler:sample(),
scheduler:utilization(S1,S2).
```
It's like measuring the position of a moving car two times as fast as you can and then calculate the speed from that. You need to let some time pass, at least one second to get some reasonable averaged values. For example: `scheduler:utilization(1)`.

Offline schedulers are mostly inactive but not entirely. They might have to do some work like reporting their scheduler utilization. The 2-6% utilization you see is most likely the distributed work of `scheduler:sample()` itself on each scheduler.

Online schedulers are always the ones with lowest numbers, 1 and 2 in your case I assume.

Maybe what's needed here is some clarification in the documentation.

**Comment by tak30** [comment]
Got it! Now it makes total sense. 
Knowing this I agree with you, a fix is not needed. 

Let me know if I should close the issue.
Thanks a lot for the help and have a nice day.

**Comment by sverker** [comment]
Good. I think I will write some additional notes in the `scheduler` documentation and maybe you could review that before we close this.

**Comment by tak30** [comment]
That's perfect, if I can help somehow let me know
