### ISSUE TITLE
Mnesia BackendMod:init_backend() only called when re-registering a backend type (and mnesia startup)

### ISSUE THREAD

**Issue by uwiger** [erlang/otp#4525]
**Describe the bug**
In the mnesia backend type behavior, the `init_backend()` behavior callback is supposed to be called when starting mnesia, and when adding a backend module for the first time.

Unfortunately, the boolean test is reversed, and `Mod:init_backend()` is only called if `Mod` has _already_ been registered.

**To Reproduce**
Shell interaction:
```erlang
(<0.188.0>) call mnesia_rocksdb:register()
(<0.246.0>) call mnesia_rocksdb:module_info(exports)
(<0.188.0>) call mnesia_rocksdb:add_aliases([rocksdb_copies])   %% init_backend() should have been called first
...
9> mnesia:stop().
...
stopped
10> mnesia:start().                                    
(<0.271.0>) call mnesia_rocksdb:init_backend()                       %% here, init_backend() IS called
(<0.271.0>) call mnesia_rocksdb:add_aliases([rocksdb_copies])
...
11> mnesia_schema:add_backend_type(rocksdb_copies2, mnesia_rocksdb).
(<0.308.0>) call mnesia_rocksdb:module_info(exports)
(<0.188.0>) call mnesia_rocksdb:init_backend()                       %% here, init_backend() IS called
(<0.188.0>) call mnesia_rocksdb:add_aliases([rocksdb_copies2])
```

**Expected behavior**
The `Mod:init_backend()` callback should be called every time the backend module is prepared for use for the first time.

**Affected versions**
OTP 19.0 and later.

**Additional context**

Related code:
https://github.com/erlang/otp/blob/master/lib/mnesia/src/mnesia_schema.erl#L1357-L1388

**Comment by uwiger** [comment]
I only now noticed the "help wanted" label.
Specifically what help is needed? Writing test cases for it? The actual bug is, as described above, that the boolean test is reversed: `ModuleRegistered` is interpreted as `NeedsInit`, when it should be the other way around.

**Comment by dgud** [comment]
A pull-request with a fix and test cases would be great.

**Comment by dgud** [comment]
Thanks for the bug-report and PR.
