### ISSUE TITLE
Observer cuts off last character in overview fields

### ISSUE THREAD

**Issue by lhoguin** [erlang/otp#4533]
**Describe the bug**
Observer cuts off the last character in overview fields as shown in the following screenshot:

<img width="804" alt="Screenshot 2021-02-18 at 16 30 13" src="https://user-images.githubusercontent.com/79089961/108380690-60d76b00-7207-11eb-935b-7389ad5ad07d.png">

As you can see this doesn't happen in all fields.

**To Reproduce**
Not sure! New laptop running macOS Catalina with a newly built Erlang/OTP. Wx version is:

```
% brew info wxmac
wxmac: stable 3.0.5.1 (bottled), HEAD
Cross-platform C++ GUI toolkit (wxWidgets for macOS)
https://www.wxwidgets.org
/usr/local/Cellar/wxmac/3.0.5.1_1 (810 files, 23.0MB) *
  Poured from bottle on 2021-02-15 at 16:33:24
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/wxmac.rb
License: wxWindows
==> Dependencies
Required: jpeg ✔, libpng ✔, libtiff ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 13,005 (30 days), 39,686 (90 days), 214,437 (365 days)
install-on-request: 1,865 (30 days), 5,594 (90 days), 24,191 (365 days)
build-error: 0 (30 days)
```

**Expected behavior**
No cut off.

**Affected versions**
Current maint and 23.1.x versions at least.

**Additional context**
The data is correct, I have confirmed by printing the result of `wxStaticText:getLabel/1`. It is only the visuals that are wrong.

With the following patch things seem to work fine. This is obviously not the right patch but it hints as to where the problem could be:

``` patch
diff --git a/lib/observer/src/observer_lib.erl b/lib/observer/src/observer_lib.erl
index 7d115306bd..901e350ce1 100644
--- a/lib/observer/src/observer_lib.erl
+++ b/lib/observer/src/observer_lib.erl
@@ -221,10 +221,10 @@ update_info2([Scroll = {_, _, _}|Fs], [{_, NewInfo}|Rest]) ->
     update_scroll_boxes(Scroll, NewInfo),
     update_info2(Fs, Rest);
 update_info2([Field|Fs], [{_Str, {click, Value}}|Rest]) ->
-    wxStaticText:setLabel(Field, to_str(Value)),
+    wxStaticText:setLabel(Field, to_str(Value) ++ " "),
     update_info2(Fs, Rest);
 update_info2([Field|Fs], [{_Str, Value}|Rest]) ->
-    wxStaticText:setLabel(Field, to_str(Value)),
+    wxStaticText:setLabel(Field, to_str(Value) ++ " "),
     update_info2(Fs, Rest);
 update_info2([Field|Fs], [undefined|Rest]) ->
     wxStaticText:setLabel(Field, ""),
```

Screenshot with this patch:

<img width="807" alt="Screenshot 2021-02-18 at 16 28 10" src="https://user-images.githubusercontent.com/79089961/108380636-54531280-7207-11eb-95ee-045208c01255.png">

I'm happy to look further but am not sure where I should look at.

**Comment by lhoguin** [comment]
It's in the process overview as well (see `error_handle` missing final `r` for example):

<img width="704" alt="Screenshot 2021-02-19 at 09 42 56" src="https://user-images.githubusercontent.com/79089961/108480228-f968fc00-7296-11eb-9978-e4ebedf67de8.png">

**Comment by dgud** [comment]
Can you test with a later wxWidgets, 3.1.4 for example, wxWidgets don't propagate patches to their stable branch,
they mostly just fix stuff on their master branch and especially for mac.

**Comment by lhoguin** [comment]
No problem with wxWidgets 3.1.5 and OTP-23.2.5. Sucks about the Homebrew install but oh well. Closing, thanks!
