### ISSUE TITLE
file:send_file leaks file descriptors

### ISSUE THREAD

**Issue by bmteller** [erlang/otp#4540]
**Describe the bug**
If send_file doesn't send all the bytes it leaks the file descriptor it duplicates. see: erts/emulator/drivers/common/inet_drv.c

```
        int dup_file_fd;        /* The file handle to send from; this is
                                 * duplicated when sendfile is issued to
                                 * reduce (but not eliminate) the impact of a
                                 * nasty race, so we have to remember to close
                                 * it. */
```

**To Reproduce**

```
defmodule Leak do

  def leak() do
    File.write!("/tmp/bigfile.txt", String.duplicate("A", 1_000_000))
    port = server()
    client(port)
    client(port)
    pid = :os.getpid()
    {out, _} = System.cmd("lsof", ["-p", to_string(pid)])
    IO.puts(out)
    IO.puts("SLEEPING")
    Process.sleep(300_000)
  end

  def server() do
    {:ok, server} = :gen_tcp.listen(0, [])
    Task.async(fn() -> server_loop(server) end)
    {:ok, {_ip, port}} = :inet.sockname(server)
    port
  end

  def client(port) do
    {:ok, socket} = :gen_tcp.connect('localhost', port, [:binary, {:active, false}])
    {:ok, data} = :gen_tcp.recv(socket, 100)
    IO.puts("RECEIVED_DATA: #{data}")
    :gen_tcp.close(socket)
    IO.puts("LEAKED FD")
  end

  def server_loop(socket) do
    {:ok, client} = :gen_tcp.accept(socket)
    task = Task.async(fn() -> handle_client() end)
    :ok = :gen_tcp.controlling_process(client, task.pid)
    send(task.pid, {:socket, client})
    server_loop(socket)
  end

  def handle_client() do
    client = receive do
      {:socket, client} -> client
    end

    try do
      {:ok, fd} = File.open("/tmp/bigfile.txt", [:binary, :raw, :read])
      try do
        :file.sendfile(fd, client, 0, 1_000_000, [])
      after
        :file.close(fd)
        IO.puts("closed_file")
      end
    after
      :gen_tcp.close(client)
      IO.puts("closed_client")
    end
  end
end
```

**Expected behavior**

file:send_file should ensure it closes the file descriptor it duplicates

**Affected versions**

I've tested it on 23.2.5 but I think it affects a lot of versions.

**Comment by kjnilsson** [comment]
We (RabbitMQ) are currently working on a new feature which uses file:sendfile heavily for replication. Some early tests indicated there was a handle leak but we assumed we had a bug somewhere in our code but this suggest perhaps we didn't. The way we use sendfile is very likely to frequently send fewer bytes than requested. We'd be happy to help in any way possible.

**Comment by garazdawi** [comment]
Thanks for the report. I have a solution that I think should work in #4543. Please test it and see if it works for you. I still need to add some tests that verify that the fix works.

**Comment by bmteller** [comment]
I think there is some weird behaviour around calling file:sendfile() against the same socket concurrently. I haven't tested against your version but I assume it would leak. this is kind of malicious use of the API so maybe can be ignored.
