### ISSUE TITLE
In OTP-22, modules exporting a function named "clauses" cannot be cover-compiled

### ISSUE THREAD

**Issue by jesperes** [erlang/otp#4549]
**Describe the bug**
Modules containing an **exported** function called `clauses` cannot be cover compiled.

**To Reproduce**
Take a module with an exported function called `clauses`:
```erlang
-module(foo).
-export([clauses/1]).
clauses(_X) ->
    ok.
```
When cover-compiling this with e.g. `cover:compile/1`, it crashes with a `function_clause` error:
```
Erlang/OTP 22 [erts-10.7.2.7] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Eshell V10.7.2.7  (abort with ^G)
1> cover:compile("/home/jesperes/foo.erl").
=ERROR REPORT==== 25-Feb-2021::14:18:52.054661 ===
Error in process <0.87.0> with exit value:
{function_clause,[{cover,'-patch_code1/2-lc$^0/1-1-',
                         [1],
                         [{file,"cover.erl"},{line,2181}]},
                  {cover,patch_code1,2,[{file,"cover.erl"},{line,2181}]},
                  {cover,'-patch_code1/2-lc$^1/1-0-',2,
                         [{file,"cover.erl"},{line,2183}]},
                  {cover,patch_code_tuple,5,[{file,"cover.erl"},{line,2191}]},
                  {cover,'-patch_code1/2-lc$^1/1-0-',2,
                         [{file,"cover.erl"},{line,2183}]},
                  {cover,'-patch_code1/2-lc$^1/1-0-',2,
                         [{file,"cover.erl"},{line,2183}]},
                  {cover,transform,4,[{file,"cover.erl"},{line,1649}]},
                  {cover,do_compile_beam2,6,
                         [{file,"cover.erl"},{line,1591}]}]}
```

**Expected behavior**
The `cover:compile/1` function should return `{ok, <modulename>}`.

**Affected versions**
* 22.3.4.15
* 23.2.4

**Not affected versions**
* 21.3.8.20 

**Additional context**
The bug is caused by `cover:patch_code1/2` having a clause which looks like this:
```erlang
patch_code1({clauses,Cs}, Key) ->
    {clauses,[patch_code1(El, Key) || El <- Cs]};
```
This not only matches `{clauses, _}`-tuples in the abstract code itself, but also exported functions named `clauses`. Such functions appear as `-export` attributes like this in the abstract code:
```erlang
 {attribute,2,export,[{clauses,1}]},
```

**Comment by bjorng** [comment]
The bug fix will be included in the next patch for OTP 22 and in OTP 23.3.
