### ISSUE TITLE
SIGUSR1 kills beam immediately under +B i/d

### ISSUE THREAD

**Issue by jktomer** [erlang/otp#4552]
**Describe the bug**
The OTP [documentation](https://erlang.org/doc/man/kernel_app.html) states that SIGUSR1 is normally handled by causing a crash dump and halt Erlang. However, when the emulator flags `+B i` or `+B d` are passed, the system call to handle SIGUSR1 is not invoked, so SIGUSR1 will actually cause BEAM to die immediately.

**To Reproduce**
1. start Erlang with `+B i` or `+B d`.
2. send SIGUSR1 to the BEAM process.

**Expected behavior**
Erlang exits producing a crash dump with the slogan "Received SIGUSR1"

**Actual behavior**
Erlang exits immediately; no crash dump is produced (nor does any other cleanup happen).

**Affected versions**
Apparently since at least R13B03.

**Additional context**
See the pull request accompanying this issue.

**Comment by garazdawi** [comment]
I have a vague recollection that we did not change this behaviour when implementing the signal server was because of backward compatibility concerns. Maybe it is time to revisit those concerns and see if they still are valid.
