### ISSUE TITLE
Can't build OTP 24.0-rc1 with webview on macOS

### ISSUE THREAD

**Issue by DOBRO** [erlang/otp#4556]
**Describe the bug**
Trying to build OTP 24.0-rc1 on macOS Big Sur. This warning appears:
```wxWidgets was not compiled with --enable-webview or wxWebView developer package is not installed, wxWebView will NOT be available```

wxWidgets installed and compiled with ```--enable-webview``` flag

**To Reproduce**
```kerl build 24.0-rc1```

**Comment by josevalim** [comment]
@DOBRO I ran into a similar issue which was caused by using an older installation of `wxmac`. Once I updated homebrew and wxmac, it worked. Did you try that?

**Comment by dgud** [comment]
On Big Sur we really need wxWidgets-3.1.5 (not yet released) to make it work ok,
The master branch of wxWidgets should work.

**Comment by DOBRO** [comment]
@josevalim , yes I tried the latest wxmac version:
```bash
$ brew update
$ brew upgrade
$ brew install wxmac
Warning: wxmac 3.0.5.1_1 is already installed and up-to-date.
```
and after `kerl build 24.0-rc1` I got the same issue.

So, looking forward to wxWidgets-3.1.5
