### ISSUE TITLE
Cannot run debugger (erlang 22.3.4.9)

### ISSUE THREAD

**Issue by menih** [erlang/otp#4558]
Trying to invoke debugger:start(), but it does not exist. Same works fine on OTP 23.

**Comment by paulo-ferraz-oliveira** [comment]
Are you compiling from source? Or are you using something pre-built like `kerl` or `asdf`?

**Comment by garazdawi** [comment]
Hello!

We need more information in order to solve this. Can you please attach the build logs for when you built Erlang/OTP?
