### ISSUE TITLE
The OTP-24.0-rc1 man archive is broken

### ISSUE THREAD

**Issue by filmor** [erlang/otp#4559]
**Describe the bug**
The file at http://erlang.org/download/otp_doc_man_24.0-rc1.tar.gz is not gzipped.

**To Reproduce**
Download the file and unpack using `tar -xvzf ...`, fails with `not in gzip format`. Unpacking with `tar -xvf` works.

**Expected behavior**
Unpacks.

**Affected versions**
24.0-rc1.

**Comment by garazdawi** [comment]
Thanks for letting us know. I recently changed some thing in the script that creates the man archive and apparently I missed to add the `z` to the tar command. I've fixed the problem in our scripts and will upload a gzipped version to erlang.org soon.

**Comment by proxyles** [comment]
The new http://erlang.org/download/otp_doc_man_24.0-rc1.tar.gz is now in place.
