### ISSUE TITLE
Not able to build otp from git source ld: framework not found QuickTime

### ISSUE THREAD

**Issue by jainygaurav** [erlang/otp#4560]
MacOS: 10.15.7 (19H15)
Xcode: Version 12.4 (12D4e)
git clone https://github.com/erlang/otp.git
cd otp
./otp_build autoconf
./configure
make

Error Output:

LD	../priv/x86_64-apple-darwin19.6.0/wxe_driver.so
ld: framework not found QuickTime
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [../priv/x86_64-apple-darwin19.6.0/wxe_driver.so] Error 1
make[2]: *** [opt] Error 2
make[1]: *** [opt] Error 2
make: *** [libs] Error 2

**Comment by dgud** [comment]
Looks like you have an old version of wxWidgets?
Or a incomplete wxWidgets installation.

**Comment by paulo-ferraz-oliveira** [comment]
@jainygaurav, might your issue be related to #4556?

**Comment by jainygaurav** [comment]
Not sure if it was the right thing to do but I built otp by removing QuickTime framework from Makefile.
