### ISSUE TITLE
Is OTP 19 backward compatible with OTP 18

### ISSUE THREAD

**Issue by jainygaurav** [erlang/otp#4562]
* I have a OTP 18 server with ejabberd-16.03 and some other modules running. I can not upgrade non-OTP modules.

* Is OTP 19 backward compatible with OTP 18?

I mean will my current modules working on OTP 18 work with OTP 19?

**Comment by michaelklishin** [comment]
As with any major OTP release, the answer is "yes, mostly, but there can be exceptions" such as certain libraries or functions in OTP being deprecated or removed.

Note that OTP 19 has been effectively out of support for a while now.
