### ISSUE TITLE
spec description error

### ISSUE THREAD

**Issue by dong50252409** [erlang/otp#4569]
https://github.com/erlang/otp/blob/4cdd991df2885398a7c00c85b4340c34197b92d3/lib/mnesia/src/mnesia.erl#L145

**Comment by paulo-ferraz-oliveira** [comment]
Nice catch. You should pull request. 😄

**Comment by dong50252409** [comment]
#4572

**Comment by paulo-ferraz-oliveira** [comment]
A nifty GitHub trick: if, in a pull request, you write text "Closes #4572." (for example) the elements get linked (Check "Linked pull requests" to the right) and then your Issue gets closed when the pull request does too.

**Comment by josevalim** [comment]
I believe this can be closed now. :)
