### ISSUE TITLE
Breaking Change in Version 23.2.7 SSL Connect Options

### ISSUE THREAD

**Issue by maennchen** [erlang/otp#4586]
**Describe the bug**

If a tcp socket is opened using `gen_tcp:connect/4` with mode `binary` supplied and the connection is later upgraded to tls using `ssl:connect/3` with mode `list`, the SSL socket will be in list mode in `23.2.7` and in `binary` mode in `23.2.6`.

**To Reproduce**

This script passes in `23.2.6`, but not in `23.2.7`:

```erlang
#!/usr/bin/env escript

main(_ArgV) ->
  application:ensure_all_started(ssl),
  
  {ok, TcpSocket} = gen_tcp:connect("aspmx.l.google.com", 25, [binary, {active, false}, {packet, line}]),
  {ok, <<"220 mx.google.com", _/binary>>} = gen_tcp:recv(TcpSocket, 0),

  ok = gen_tcp:send(TcpSocket, "EHLO smtp.example.com\r\n"),
  {ok, <<"250-mx.google.com at your service", _/binary>>} = gen_tcp:recv(TcpSocket, 0),
  {ok, <<"250-SIZE", _/binary>>} = gen_tcp:recv(TcpSocket, 0),
  {ok, <<"250-8BITMIME", _/binary>>} = gen_tcp:recv(TcpSocket, 0),
  {ok, <<"250-STARTTLS", _/binary>>} = gen_tcp:recv(TcpSocket, 0),
  {ok, <<"250-ENHANCEDSTATUSCODES", _/binary>>} = gen_tcp:recv(TcpSocket, 0),
  {ok, <<"250-PIPELINING", _/binary>>} = gen_tcp:recv(TcpSocket, 0),
  {ok, <<"250-CHUNKING", _/binary>>} = gen_tcp:recv(TcpSocket, 0),
  {ok, <<"250 SMTPUTF8", _/binary>>} = gen_tcp:recv(TcpSocket, 0),

  ok = gen_tcp:send(TcpSocket, ["STARTTLS\r\n"]),
  {ok, <<"220 2.0.0 Ready to start TLS", _/binary>>} = gen_tcp:recv(TcpSocket, 0),

  {ok, SslSocket} = ssl:connect(TcpSocket, [list, {active, false}, {packet, line}, {versions, ['tlsv1', 'tlsv1.1', 'tlsv1.2']}]),

  ok = ssl:send(SslSocket, ["EHLO smtp.example.com\r\n"]),
  {ok, <<"250-mx.google.com at your service", _/binary>>} = ssl:recv(SslSocket, 0).
```

**Expected behavior**

I'm not sure since this is technically what the user asked for.

**Affected versions**

* `23.2.7`

**Additional context**

This change produces bugs in [`gen_smtp`](https://github.com/gen-smtp/gen_smtp/issues/250).

I have not verified this by myself but it also produces bugs in `ranch`.

**Comment by maennchen** [comment]
@kleinernik has produced a more concise way to reproduce the issue in elixir: https://github.com/gen-smtp/gen_smtp/issues/250#issuecomment-791577491

**Comment by arjan** [comment]
Seems like you both added an issue around the same time.. this one is a duplicate of #4585. I think we should close this one in favor of the other because the other is a bit more clear (it shows where this bug got introduced)

**Comment by maennchen** [comment]
@arjan oops, closing

**Comment by lhoguin** [comment]
Could you provide details about the issue in Ranch? Would like to understand the issue in case we run into it. Here or in a Ranch ticket is fine. Thanks!
