### ISSUE TITLE
Support Windows on ARM

### ISSUE THREAD

**Issue by rubin55** [erlang/otp#4594]
**Is your feature request related to a problem? Please describe.**

Currently Erlang is available on quite a few platforms. Recently, there's been an uptake in ARM-based platforms, most notably Apple's M1, but also Microsoft Surface Pro X with its Windows on ARM platform. It would be most excellent if Erlang would provide Erlang binaries for Windows on ARM.

**Describe the solution you'd like**
Have Erlang provide Windows on ARM binaries, available for download at erlang.org/downloads

**Describe alternatives you've considered**
N/A.

**Additional context**
N/A.

**Comment by KennethL** [comment]
We have currently no plans to build and test Erlang/OTP for Windows on ARM.
A contribution of code, makefiles, and description on how to build Erlang for Windows on ARM would be a first good step.

**Comment by Scotty-Hudson** [comment]
With Snapdragon X Elite about to come out, will priorities change on this?

**Comment by garazdawi** [comment]
It is nothing that we are planning to do anytime soon, though if it becomes popular enough we will of course have a look and see what can be done. It should not be too hard to port the interpreter, so if anyone wants to contribute patches for that we would still be happy to accept those.

**Comment by garazdawi** [comment]
Just remembered that #8142 tries to fix the Windows ARM support. So maybe support will be there sooner than I originally thought.
