### ISSUE TITLE
Is there a maps_compat library to make OTP < 21 work for libs that depend on OTP > 21

### ISSUE THREAD

**Issue by jainygaurav** [erlang/otp#4595]
Example compat library that I am using: https://github.com/benoitc/unicode_util_compat to get past `string:lowercase` issues.

I am reposting what I posted on SO. Please help.

https://stackoverflow.com/questions/66535862/stacktrace-erlang-nif-error-undefined

**Comment by okeuday** [comment]
@jainygaurav If you needed a `dict` API using an Erlang map, that compatibility code is at https://github.com/okeuday/mapsd .  For `maps:iterator` and `maps:next` it is best to use a more recent version of Erlang/OTP (your nif error makes it look like the functionality is missing in your version).

**Comment by sverker** [comment]
What about something simple like this:
```
maps_iterator(Map) ->
    maps:to_list(Map).

maps_next([{K,V} | T]) ->
    {K, V, T};
maps_next([]) ->
    none.
```

**Comment by jainygaurav** [comment]
@sverker I try and update this post.

**Comment by jainygaurav** [comment]
@sverker after implementing your suggestion, I don't get the error in this bug. I might hit other issues but I close this.

Thank you so much. I don't know a better way of thanking you!
