### ISSUE TITLE
When sys.config refers to another file, and the second points to third file, merge_env will crash

### ISSUE THREAD

**Issue by whtevrdude** [erlang/otp#4599]
**Describe the bug**
When sys.config in a release refers to another config file, e.g. file1.config, and file1.config points to another config file, e.g. file2.config, starting the app will fail due to application_controller:merge_env crash.

**To Reproduce**
Place a sys.config at the release folder with content:
```["file1.config",{app, [{key1, val1}]}]```
Place file1.config on the same folder, with content:
```["file2.config",{app, [{key2, val2}]}]```
Place file2.config on the same folder, with content:
```[{app, [{key3, val3}]}]```
**Expected behavior**
Get env with ```{app => [{key1, val1}, {key2, val2}, {key3, val3}]}```.

**Affected versions**
OTP 22 (the only one I checked).

**Additional context**, but , the bug label might be wrong: 
According to [config doc](https://erlang.org/doc/man/config.html#sys.config):
> When traversing the contents of sys.config and a filename is encountered, its contents are read and merged with the result so far. When an application configuration tuple {Application, Env} is found, it is merged with the result so far.

As I see it, the documentation should state clearly the current limitations (the bug is the Doc, but I guess this is my intrepretation).
If possible, a feature request should allow merge_env handle referrals with any depth, not just 1.
Thanks.

**Comment by garazdawi** [comment]
As the docs state, the `sys.config` file is allowed to include other files. No other config files are allowed to include files. You get a similar result if you try to do `erl -config file1`.

A patch to [the documentation](https://github.com/erlang/otp/blob/master/lib/kernel/doc/src/config.xml#L131) to make this clearer would be much appreciated.

I wasn't present when the decision to make it behave this way was done, but I think it is to make it easier to figure out exactly what config is loaded. Also, it avoids aging to check for any loops which makes the code simpler.

**Comment by lrascao** [comment]
fortunately you can override previous config values when including multiple `.config` files:

`sys.config`
`[{app, [{key1, val1}]}, "file1.config", "file2.config"]`

`file1.config`
`[{app, [{key1, val2}]}]`

`file2.config`
`[{app, [{key1, val3}]}]`

**Comment by whtevrdude** [comment]
Yes, I should have put it as a feature request.
Currently the solution I used is similar to @lrascao 's suggestion, but it requires using a sed command in the Makefile rebar3 runs to remove the referral from file1 to file2. I still think a better solution should be considered when using various apps which may have their own configs.
