### ISSUE TITLE
OTP-24.0-rc1 removed edoc's NO_APP macro

### ISSUE THREAD

**Issue by mikpe** [erlang/otp#4603]
**Describe the bug**
The documentation for edoc_doclet (https://erlang.org/doc/man/edoc_doclet.html) states that edoc_doclet.hrl provides the NO_APP macro. OTP-24.0-rc1 removed this macro without prior deprecation via https://github.com/erlang/otp/pull/2914. As a consequence, existing code using the currently documented way to get this value fails to compile. One such example is Ulf Wiger's edown.

**To Reproduce**
```
> cat bug.erl
-module(bug).
-export([foo/0]).
-include_lib("edoc/include/edoc_doclet.hrl").
foo() -> io:format("~p\n", [?NO_APP]).
> erlc bug.erl
bug.erl:4:30: undefined macro 'NO_APP'
%    4| foo() -> io:format("~p\n", [?NO_APP]).
%     |                              ^

bug.erl:2:2: function foo/0 undefined
%    2| -export([foo/0]).
%     |  ^
```

**Expected behavior**
With OTP-23:
```
> erlc bug.erl && erl -noshell -noinput -s bug foo -s erlang halt
[]
```

**Affected versions**
OTP-24.0-rc1

**Additional context**
I would have expected the macro to (1) receive a new value, (2) be marked as deprecated with a clear replacement in the documentation, and (3) be removed in a later release (i.e. in OTP-25 at the earliest).

**Comment by garazdawi** [comment]
Thanks for letting us know that you depended on this. I opened #4713 in order to do the deprecation properly. There is also a PR open to fix edown, https://github.com/uwiger/edown/pull/21.
