### ISSUE TITLE
No obvious/appropriate replacement for `http_uri:decode/1` or `http_uri:encode/1` in `uri_string`

### ISSUE THREAD

**Issue by distortedsignal** [erlang/otp#4607]
**Is your feature request related to a problem? Please describe.**
There isn't an obvious replacement for either `http_uri:decode/1` or `http_uri:encode/1` exported from `uri_string`. If `http_uri` is going to be deprecated in OTP 25, these functions should be replicated/replaced.

**Describe the solution you'd like**
Looking through the source, it seems like there is a `decode/1` function already [in the `uri_string` module](https://github.com/erlang/otp/blob/205606a0bbae0d4484224a87d074d7eeb9e401df/lib/stdlib/src/uri_string.erl#L1478-L1480). It might be enough to export that function so that users can use it. The currently exported function (`uri_string:percent_decode/1`) seems like it could be a replacement, but I'm curious why it was decided that `Mod1:decode/1` should become `Mod2:percent_decode/1`.

It looks like `encode` might be a little harder. There is an `encode/2` function [in the `uri_string` module](https://github.com/erlang/otp/blob/205606a0bbae0d4484224a87d074d7eeb9e401df/lib/stdlib/src/uri_string.erl#L1575-L1580), but the user would have to pass in a `fun` of unspecified arguments - which seems distinctly un-fun to me. It seems to me (in my layman's lack-of-encoding-understanding) that this `fun` should be fully defined by the IETF RFC for URLs, and should be relatively static in terms of how the encoding should work. It _seems_ like this should be a fine thing to ship in the URI library. But again, I'm a layman in these things.

**Describe alternatives you've considered**
I could continue to use the `http_uri` module, but that seems like something that won't continue to work past OTP 25, as my compiler keeps telling me.

I could publish my own library with these functions, but that seems like it would be counterintuitive - taking a function from something shipped to the standard library to a third-party dependency. That strikes me as regressive.

We could get this from a third party language, but that seems _really bad_.

**Additional context**
I'll try to take a crack at this when I get the chance. I'm guessing the longest part is going to be the `fun` that turns characters into their percent-encoded counterparts.

**Comment by lhoguin** [comment]
There is no encode function because the module already automatically encodes when you give it appropriate components.

Some background is here: https://github.com/erlang/otp/pull/2492 - the `percent_decode` function was added because the `uri_string` parser does not decode reserved characters in components. The decoding has to be done independently by the application afterwards, if desired. The same is not true for encoding.

What do you use the `encode` function for?

**Comment by distortedsignal** [comment]
Oh, there are some examples in the README of that library that should explain what I'm trying to do as well. Check them out here:

https://github.com/distortedsignal/erlidata_lib/pull/1/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R57-R66

**Comment by lhoguin** [comment]
Accepting both encoded and non-encoded in the same function is just looking for trouble. In your case I would parse the URI (without the query), add the query to the map, and recompose the URI. No need to encode manually.

Note that there's different ways to percent encode, even in just RFC 3986. In a URI for example, each component is percent-encoded slightly differently. The query string itself is encoded very differently compared to the rest of the URI, using the algorithm from `application/x-www-form-urlencoded` instead. So when you say there should be a function to encode, it's a little more complex than just adding the one function.

Cheers.

**Comment by distortedsignal** [comment]
Yeah, I get where you're coming from. That makes sense.

**Comment by luos** [comment]
Hi,

I don't think there is a replacement for this: 

For example let's say I have a parameter with value `This is/a test`, now this is not part of the query string but the path, for example I would like to query: 

`http://localhost:234/This%20is%2f%a%test` 

And now if `http_uri:encode` is removed, there is no (built in) way to do this. Am I incorrect?

Thanks

**Comment by samwar** [comment]
@luos I can't find a way to use the `uri_string` functions to be able to encode like you're suggesting. My API is constantly dealing with path items (like switch interface names) that need to be percent-encoded, and we heavily rely on the `http_uri:encode/1` function.

**Comment by lhoguin** [comment]
Please open a separate ticket so your issue can be seen by the OTP team. So far the `uri_string:allowed_characters/0` function was added that could help in building all kinds of encode functions. A way to split/zip path segments was discussed but not added yet so you need to make a strong case in the ticket, with as many details as you can.

**Comment by samwar** [comment]
@luos if you're still interested in seeing a resolution to the problem around the removal of the function, I've opened issue https://github.com/erlang/otp/issues/5368.
