### ISSUE TITLE
Docs for OTP 24-rc1

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlang/otp#4612]
Are the expected release notes and doc.s found anywhere online? Should they?

In the process of migrating to OTP 24 **while the final version is still not out**, this would help, among other things, to:
* understand how to fix something that broke due to interface changes (`socket`, I'm looking at you),
* iron out any doc.-related elements that aren't clear (or perhaps even missing).

**Comment by garazdawi** [comment]
A link can be found in the new item: https://www.erlang.org/news/144 and also on the github release https://github.com/erlang/otp/releases/tag/OTP-24.0-rc1

The link are: http://erlang.org/documentation/doc-12.0-rc1/doc/ and https://erlang.org/download/OTP-24.0-rc1.README

**Comment by paulo-ferraz-oliveira** [comment]
:) thanks, @garazdawi. I got the news from GitHub, I guess. Closing.
