### ISSUE TITLE
Notice for "experimental" in `socket`

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlang/otp#4614]
https://erlang.org/download/OTP-24.0-rc1.README mentions `socket` is experimental.

http://erlang.org/documentation/doc-12.0-rc1/lib/kernel-8.0/doc/html/socket.html#sockname-1, however, does not, even though it states

```
There is currently no support for Windows.

Support for IPv6 has been implemented but not tested.

SCTP has only been partly implemented (and not tested).
```

Should a note be added to that text box, stating that the API is indeed subject to breakage, or that it is experimental? (I think it's somewhat noticeable, afterward, in each function signature, what belongs to each OTP version)

**Comment by RaimoNiskanen** [comment]
We intend to remove the Experimental status for socket for OTP-24.0.

The Tickets in the README that mention "experimental ... socket" were written while socket clearly was experimental and had no thought about what state it would be when the fix eventually was released.

By "removing the Experimental status" we mean to freeze the API, and in the future only make backwards compatible changes.  The notes in the function signatures states when a clause was introduced, which mostly are backwards compatible additions.

So we aim to fix up Windows, IPv6 and SCTP, without making backwards incompatible changes.
Hence the socket API can be regarded as not experimental but still incomplete in some regards, from OTP-24.0,
but I agree that if IPv6 and SCTP is broken it would be hard to recommend the `socket` module for all applications
even though the API may be declared as not experimental...

**Comment by paulo-ferraz-oliveira** [comment]
I'm OK with "incomplete but stable". Thanks.
