### ISSUE TITLE
OTP 24-rc1: prim_socket,nif_cancel badarg after socket:send (no wait) with a sndbuf of 1

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlang/otp#4618]
**Describe the bug**

Cancelling an open `socket` for a sender that has a send buffer of `1` which has already "overflown", causes a `badarg` at the `prim_socket,nif_cancel` level.

**To Reproduce**

Here's some code:
```erlang
-module(gen_tcp_test).

-compile([export_all, nowarn_export_all]).

test() ->
    {ok, ListenSocket} = socket:open(inet, stream, tcp),
    _ = socket:bind(ListenSocket, #{ family => inet, port => 0, addr => any }),
    {ok, #{ port := ListenPort }} = socket:sockname(ListenSocket),
    ok = socket:listen(ListenSocket, 1024),
    _ = spawn(fun () -> accept(ListenSocket) end),

    {ok, ClientSocket} = gen_tcp:connect({127, 0, 0, 1}, ListenPort, []),
    inet:setopts(ClientSocket, [{recbuf, 1}]).

accept(ListenSocket) ->
    {ok, ServerSocket} = socket:accept(ListenSocket),
    socket:setopt(ServerSocket, socket, sndbuf, 1),
    ok = socket:send(ServerSocket, [0], nowait),
    {select, SelectInfo} = socket:send(ServerSocket, [0], nowait),
    socket:cancel(ServerSocket, SelectInfo).
```

**Expected behavior**

No crash, as per e.g. OTP 23.2.

**Affected versions**

24.0-rc1 (haven't tested `master`), with the result being like
```erlang
=ERROR REPORT==== 11-Mar-2021::19:07:16.226814 ===
Error in process <0.89.0> with exit value:
{badarg,[{prim_socket,nif_cancel,
                      [#Ref<0.1584005092.2933522433.14725>,
                       {send,0},
                       #Ref<0.1584005092.2933391361.14728>],
                      []},
         {socket,cancel,3,[{file,"socket.erl"},{line,3319}]}]}
```

**Comment by paulo-ferraz-oliveira** [comment]
cc: @g-andrade

**Comment by RaimoNiskanen** [comment]
I tried to reproduce, but get `badmatch` for `ok` on the second send operation.  I suspect it is because I run on Linux while you maybe not, since Linux is known to set larger buffer sizes than you request.

Nevertheless, this patch would most probably fix the issue:
``` Erlang
diff --git a/lib/kernel/src/socket.erl b/lib/kernel/src/socket.erl
index 489b1578cd..8c011c650d 100644
--- a/lib/kernel/src/socket.erl
+++ b/lib/kernel/src/socket.erl
@@ -3307,9 +3307,9 @@ cancel(?socket(SockRef), ?SELECT_INFO(Tag, Ref))
   when is_reference(SockRef) ->
     case Tag of
         {OpName, _} when is_atom(OpName) ->
-            cancel(SockRef, Tag, Ref);
+            cancel(SockRef, OpName, Ref);
         OpName when is_atom(OpName) ->
-            cancel(SockRef, Tag, Ref)
+            cancel(SockRef, OpName, Ref)
     end;
 cancel(Socket, SelectInfo) ->
     erlang:error(badarg, [Socket, SelectInfo]).
```

**Comment by paulo-ferraz-oliveira** [comment]
Hey, @RaimoNiskanen, thanks for looking at this. Yeah, I'm on Mac OS X (can't remember if the same problem existed with Linux), but, as stated, stuff works for OTP 23, not OTP 24. I'll try your patch out. Want me to pull request later, if is eventually works? (or will you?)

**Comment by RaimoNiskanen** [comment]
I already have a work branch for socket stuff, so I will just throw it in there

**Comment by paulo-ferraz-oliveira** [comment]
I'm getting `{error, einval}`, now.

**Comment by paulo-ferraz-oliveira** [comment]
I get `ok` now. Will try to test what was failing using this minor change. Thanks.

**Comment by paulo-ferraz-oliveira** [comment]
@RaimoNiskanen, as per your latest comment, can we expect to see this in rc3? Thanks.

**Comment by paulo-ferraz-oliveira** [comment]
@RaimoNiskanen, did this one make it to rc3? 👀

**Comment by RaimoNiskanen** [comment]
Nope.  That would be PR #4748 commit c071fbe.

**Comment by paulo-ferraz-oliveira** [comment]
No biggie. It should make it to 24.0, at least, right?

**Comment by RaimoNiskanen** [comment]
Yes it will.
