### ISSUE TITLE
Many error checks in erlexec.c are ineffective since OTP 22.1

### ISSUE THREAD

**Issue by JeromeDeBretagne** [erlang/otp#4624]
**Describe the bug**
Looking at the source code from [erlexec.c](https://github.com/erlang/otp/blob/master/erts/etc/common/erlexec.c), some user input mistakes should be detected and should raise an error message, but currently they are not working as intended.

For instance here is the error check for the "-name" option (but there are many other similar ones) :
https://github.com/erlang/otp/blob/master/erts/etc/common/erlexec.c#L733-L735
```
		    if (strcmp(argv[i], "-name") == 0) { /* -name NAME */
			if (i+1 >= argc) <====================== This check is broken
			    usage("-name");
```

**To Reproduce**
$ erl -name
Erlang/OTP [...]

Eshell Vx.y.z  (abort with ^G)
1> 

**Expected behavior**
$ erl -name
Missing argument(s) for '-name'.
Usage: erl ...

**Affected versions**
@garazdawi my guess is that a regression was introduced by this commit https://github.com/erlang/otp/commit/889cc75f40c74ee574b0943524df4f786371efaf from June 2019 as it introduced an extra "--" separator thus incrementing argc, so I would say since OTP 22.1

**Additional context**
I've indeed found that there is an extra "--" argument by adding some debug code.

EDIT: The issue actually happens when an ERL_*FLAGS environment variable is set, cf. https://github.com/erlang/otp/issues/4624#issuecomment-801135677

**Comment by garazdawi** [comment]
This was partly fixed in OTP-23 through 9c113f4deeb7dc1ee02cd58003782e1d70edad56. However, you can still make it happen if you have an ERL_*FLAGS environment variable set. I've opened up #4639 to solve this, just need to think of a way to test this....

**Comment by JeromeDeBretagne** [comment]
> However, you can still make it happen if you have an ERL_*FLAGS environment variable set

Good catch, I have indeed ERL_AFLAGS defined in my setup to enable the Erlang shell history.

> I've opened up #4639 to solve this, just need to think of a way to test this....

I have applied it locally, I can confirm that #4639 is properly fixing the issue, thanks.

Will you apply the fix only on master or do you also plan to backport it to other releases later on? I'm asking to know if I'll have to target master for #2945.

**Comment by JeromeDeBretagne** [comment]
About `erl` argument checks, I've also detected that the following command:

```
erl -name node_name an_unexpected_argument

1> node().
nonode@nohost
```

doesn't start the intended distributed node and doesn't raise any error message either with Erlang/OTP 23.

Do you want me to open another issue for this different case?

**Comment by garazdawi** [comment]
> Do you want me to open another issue for this different case?

I've amended the PR with a check that prints an error when this happens.

**Comment by JeromeDeBretagne** [comment]
> I've amended the PR with a check that prints an error when this happens.

I've finally been able to build OTP 24.0 RC3, this is indeed detected with a clear error message, thank you once again.

Here is an example for reference:
```
$ erl -name node_name an_unexpected_argument
Erlang/OTP 24 [RELEASE CANDIDATE 3] [erts-12.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]

=ERROR REPORT==== 27-Apr-2021::22:57:17.030537 ===
Invalid -name given to erl, node_name an_unexpected_argument
=ERROR REPORT==== 27-Apr-2021::22:57:17.030537 ===
Invalid -name given to erl, node_name an_unexpected_argument
Eshell V12.0  (abort with ^G)
1>
```

P.S. I'm wondering if the 2 duplicated lines are expected, it is a nitpick as this is purely cosmetic, but this was surprising at first sight

**Comment by garazdawi** [comment]
> I'm wondering if the 2 duplicated lines are expected, it is a nitpick as this is purely cosmetic, but this was surprising at first sight

I noticed the same, and yes it is the expected behaviour. Whether it is the correct behaviour is another matter...

Basically what happens is that the log event is done very very early during startup, which means that the logging subsystem is not really up and running so a very simple logger is running that prints things to stdout. When the real logger comes online, any log events recorded by the simple logger are replayed into the final logger. In the default case that is the stdout logger, which makes the events show up twice. If you were to configure a file logger as the default logger (or syslog for that matter), then the extra events would be replayed into the file, which is what you want.

Maybe a special filter should be added to the default stdout logger that ignored any replayed log messages... or something similar.
