### ISSUE TITLE
erlang:system_info(system_architecture) returns "arm" instead of "arm64"

### ISSUE THREAD

**Issue by wojtekmach** [erlang/otp#4626]
**Describe the bug**

I'm on a M1 MacBook Air:

```
$ uname -a
Darwin m1.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64
```

and noticed:

```
1> erlang:system_info(system_architecture).
"arm-apple-darwin20.3.0"
```

**Expected behavior**

I'd expect: `"arm64-apple-darwin20.3.0"`, similar to output of `uname -srm` on my machine:

```
$ uname -srm
Darwin 20.3.0 arm64
```

**Affected versions**
all

**Additional context**

I noticed the system architecture contains the kernel version (20.3.0 on my machine) on Darwin but not on Linux (which in turns contains the libc variant)

```
~% docker run --rm -it erlang:latest erl -noshell -eval 'erlang:display(erlang:system_info(system_architecture)), halt()'
"aarch64-unknown-linux-gnu"

~% docker run --rm -it erlang:alpine erl -noshell -eval 'erlang:display(erlang:system_info(system_architecture)), halt()'
"aarch64-unknown-linux-musl"
```

If it's any help, I also noticed this for Python:

```
$ python3 -c "import platform; print({'system':platform.system(), 'machine':platform.machine(), 'processor':platform.processor()})"
{'system': 'Darwin', 'machine': 'arm64', 'processor': 'arm'}

$ docker run --rm -it python python -c "import platform; print({'system':platform.system(), 'machine':platform.machine(), 'processor':platform.processor()})"
{'system': 'Linux', 'machine': 'aarch64', 'processor': ''}
```

**Comment by rickard-green** [comment]
This information is taken from `config.guess` which is part of `autoconf`. We had a very old `config.guess` checked in which only recognized Apple's M1 as arm. I've update `config.guess` (from `autoconf` version 2.70 released last autumn) in  PR #4627. This update recognize Apple's M1 as `aarch64`. This update will not make it in to OTP 23, but will (assuming testing goes well) make it into OTP 24.

**Comment by wojtekmach** [comment]
I just tested it and it works well. I'm happy to see it reports `aarch64` over `arm64` too.

**Comment by rickard-green** [comment]
Regarding the difference in the target triplet (cpu-vendor-os) between MacOS and Linux. Since we just use what is reported by `config.guess` that difference will remain. My x86_64 Linux changed from `x86_64-unknown-linux-gnu` to `x86_64-pc-linux-gnu`.

**Comment by rickard-green** [comment]
Just force pushed an even newer update from (`autoconf` 2.71). The result regarding apple M1 is the same though.

**Comment by wojtekmach** [comment]
Thank you!

**Comment by al2o3cr** [comment]
@rickard-green FWIW, the change from `x86_64-unknown-linux-gnu` to `x86_64-pc-linux-gnu` broke this buildpack that assumes the target name when copying files. https://github.com/elixir-buildpack/heroku-otp/issues/2#issuecomment-843676086

Is there a reliable way to correctly reference the output directory (versus [hard-coding](https://github.com/elixir-buildpack/heroku-otp/blob/43dc62d762fbabfbfea9b1017b1c1cc3871de91d/.github/workflows/build-new-release.yml#L131) it) independent of the OTP version, since 24.0+ produce artifacts in a different place?

**Comment by garazdawi** [comment]
Way down in the bottom of the [Installation Guide](http://erlang.org/doc/installation_guide/INSTALL.html#advanced-configuration-and-build-of-erlang-otp) it is described that you can use the environment variable `RELEASE_ROOT` when doing `make release` to direct the release to someplace else than the default directory.

You can call `erts/autoconf/config.guess` to get the triplet of the current system, so if you do not want to use RELEASE_ROOT you can call that script.

Or just do `*` and `sh` will most likely do the right thing.
