### ISSUE TITLE
compiler: Question about scope of `(no)warn_export_all`

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlang/otp#4628]
I have a module I'm compiling using `rebar3` with `rebar.config` containing `{erl_opts, [warn_export_all]}`.

In that module I have directive `-compile([export_all, nowarn_export_all]).` The compiler complains that all functions are being exported, even though I explicitly tell it to not care about that in that specific module.

Now... (and this is probably just my expectation, not really justified), is this correct? Should a "lower-level" option not override a "higher-level" one? My expectation is that no, but I'd like to understand if this might:
1. be a bug, and should be fixed,
2. be a feature, and should be documented.

**Comment by bjorng** [comment]
For options handled by `erl_lint`, it is intentional that options on the command line overrides options in module:

https://github.com/erlang/otp/blob/c38f2d8e2a2d5522970f6f439cc4b169be49471d/lib/stdlib/src/erl_lint.erl#L568-L573

This comment was added in R10 and it seems that the before that options in the module would take precedence over options on the command line. I might have done that change myself and probably had a good reason for the change, but I can't remember the reason.

So I think that the current behavior should be documented.

**Comment by paulo-ferraz-oliveira** [comment]
> For options handled by erl_lint, it is intentional that options on the command line overrides options in module:

I was hoping for the expectation to be otherwise 😢 but I guess if there's history... (also, I'm not sure about how much breakage a change for this would introduce).

What this makes difficult is module-level control, since it's not possible from the CLI, per-module. Let me explain...

Let's say you have 200 test SUITES (which is the place where I use `export_all` the most), if you want to ignore `export_all` in only one (which is what I believe is the norm - use a module-level option for the least-occurring case) you'll have, at the CLI-level to use `nowarn_export_all` and then where you want the warning to use `warn_export_all` (e.g. in 198 modules) - and even then I'm not sure it wouldn't be overridden also, since they seem tightly coupled. This'd be odd.

Also, you talk about R10, but `warn_export_all` became a default more recently, right, like in R17 or so... was that previous consideration re-considered then?

Would a new option (I'm not saying this is MY preferred route, it's just a possibility) allow controlling this, something that would override the current implementation to give the consumer choice?

Thanks for taking the time to look at this, @bjorng.

**Comment by bjorng** [comment]
> I was hoping for the expectation to be otherwise 😢 but I guess if there's history... (also, I'm not sure about how much breakage a change for this would introduce).

I am also not sure how much breakage it would introduce, so I don't think we will dare to change it.

> Also, you talk about R10, but warn_export_all became a default more recently, right, like in R17 or so... was that previous consideration re-considered then?

No, I don't think we thought about that.

> Would a new option (I'm not saying this is MY preferred route, it's just a possibility) allow controlling this, something that would override the current implementation to give the consumer choice?

Yes, that would be possible. Another way would be to introduce a new attribute, for example `compile_a_options`, whose options would take precedence over those on the command line. For anything to happen, I think that the community will have to come up with a suggestion for a solution and write an EEP.

**Comment by bjorng** [comment]
I have been thinking a little bit more about your use cases.

> I have a module I'm compiling using `rebar3` with `rebar.config` containing `{erl_opts, [warn_export_all]}`.

Since it was quite a long time ago that `warn_export_all` became default, why not just remove the option from `rebar.config`?

> Let's say you have 200 test SUITES...

If I understood you correctly, you want the warnings for all modules except one. Why would you want to give the `warn_export_all` option on on the command line since it is default?

**Comment by paulo-ferraz-oliveira** [comment]
> why not just remove the option from rebar.config?

Sure, but would that mean that the module-level option would take precedence? I'm not sure why/if we've not removed it.

> If I understood you correctly, you want the warnings for all modules except one.

That's right!

> Why would you want to give the warn_export_all option on on the command line since it is default?

I don't, but I was pretty sure it's applied by default (sure) and the override doesn't work. Let me check it.

**Comment by paulo-ferraz-oliveira** [comment]
Hm... the lib-level option (e.g. CLI) seems to only take precedence over the module-level one **IF** it's explicitly set in `rebar.config`. Closing, since the default is reasonable for my expectations, and your suggestion is too.

Thanks again, @bjorng.
