### ISSUE TITLE
inet_db terminated in 24.0-rc1

### ISSUE THREAD

**Issue by sneako** [erlang/otp#4631]
**Describe the bug**
We have been running the release candidate in production for a few days now and everything was looking great until we had a node crash, with the following log (Elixir):
```
14:01:55.259 [error] GenServer :inet_db terminating
** (ArgumentError) argument error
    (stdlib 3.15) :ets.next(:inet_cache, {'somedomain.com', :in, :cname})
    (kernel 8.0) inet_db.erl:1733: :inet_db.do_refresh_cache/4
    (kernel 8.0) inet_db.erl:1198: :inet_db.handle_info/2
    (stdlib 3.15) gen_server.erl:699: :gen_server.try_dispatch/4
    (stdlib 3.15) gen_server.erl:775: :gen_server.handle_msg/6
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :refresh_timeout
{"Kernel pid terminated",application_controller,"{application_terminated,kernel,shutdown}"}
Kernel pid terminated (application_controller) ({application_terminated,kernel,shutdown})

Crash dump is being written to: /app/tmp/erl_crash.dump...done
``` 

**To Reproduce**
With a system configured to use `inet_res` perform many concurrent DNS resolutions for an extended period of time (long enough for the cache to expire). The node on which we experienced this had been running for ~23 hours, and had cache_refresh and timeout lower than the defaults:
```
{cache_refresh, 300000}.
{timeout, 300}.
```

**Expected behavior**
No crash 🙂 

**Affected versions**
24.0-rc1

**Additional context**
CC: @josevalim as I believe this is related to some of the recent `inet_res` changes he worked on recently.

I am happy to provide any additional information that I can, and test out future patches.

**Comment by josevalim** [comment]
@sneako I have sent a PR but I haven't tested the fix extensively yet. I am rebuilding OTP and I will let you know soon.

**Comment by sneako** [comment]
I'll test out the PR and report back, thank you!
