### ISSUE TITLE
Support ED25519 key for TLS

### ISSUE THREAD

**Issue by Sgiath** [erlang/otp#4637]
**Is your feature request related to a problem? Please describe.**
NSA designed ECs are considered [potential security risk](https://en.wikipedia.org/wiki/Dual_EC_DRBG#Weakness:_a_potential_backdoor) so I would like to use ED25519 TLS certificate for my server. Erlang currently has some support for ED25519 but not for `ssl:listen/2`.

**Describe the solution you'd like**
Add support for TLS certificates signed with ED25519 key.

**Describe alternatives you've considered**
Alternative is using supported ECs e.g. `prime256v1` but I would rather use more secure variant.

**Additional context**
For the reference I am using this commands to generate my keys:
```
openssl genpkey -algorithm ED25519 -out key.pem
openssl req -new -x509 -days 1825 -key key.pem -out cert.pem
```

And this is the stacktrace I get when trying to use such key:
```
{
  :function_clause,
  [
    {:pubkey_cert_records, :supportedPublicKeyAlgorithms, [{1, 3, 101, 112}], [file: 'pubkey_cert_records.erl', line: 109]}, 
    {:pubkey_cert_records, :decode_supportedPublicKey, 1, [file: 'pubkey_cert_records.erl', line: 228]}, 
    {:pubkey_cert_records, :decode_tbs, 1, [file: 'pubkey_cert_records.erl', line: 325]}, 
    {:pubkey_cert_records, :decode_cert, 1, [file: 'pubkey_cert_records.erl', line: 42]}, 
    {:public_key, :pkix_decode_cert, 2, [file: 'public_key.erl', line: 380]}, 
    {:ssl_handshake, :get_cert_params, 1, [file: 'ssl_handshake.erl', line: 1613]}, 
    {:tls_handshake_1_3, :get_certificate_params, 1, [file: 'tls_handshake_1_3.erl', line: 2245]}, 
    {:tls_handshake_1_3, :do_start, 2, [file: 'tls_handshake_1_3.erl', line: 638]}
  ]
}
```

**Comment by IngelaAndin** [comment]
It is in the plan for OTP-24 and in our current sprint. However, we have not had time to start it yet. I do not think that there are only small parts missing, and probably the most time will go to writing test cases.

**Comment by Sgiath** [comment]
@IngelaAndin thanks for quick answer! I am glad to hear that :)
