### ISSUE TITLE
Bad type :public_key.issuer_name()

### ISSUE THREAD

**Issue by Sgiath** [erlang/otp#4650]
**Describe the bug**
I am using different methods from `:public_key` module in my application and I am getting warnings about bad arguments because of the wrong type. I narrowed it down to bad RDN sequence type:

`:public_key.issuer_name()` is defined as `{rdnSequence,[#'AttributeTypeAndValue'{}]}` but actually every function which returns this type is returning `{rdnSequence,[[#'AttributeTypeAndValue'{}]]}` (notice double array). Affected functions that I found out: `:public_key.pkix_subject_id/1`, `:public_key.pkix_issuer_id/2`, `:public_key.pkix_decode_cert/2`

The type definition: https://github.com/erlang/otp/blob/master/lib/public_key/src/public_key.erl#L131
Type documentation: https://erlang.org/doc/man/public_key.html#type-issuer_name

**To Reproduce**
1. Generate some certificate with `CN`:
`openssl req -new -subj "/CN=test" -x509 -newkey EC -pkeyopt=ec_paramgen_curve:prime256v1 -pkeyopt=ec_param_enc:named_curve -days 1825 -out cert.pem -keyout key.pem`
2. Load key as DER-encoded binary (I am doing that with `:ssl.peercert(socket)`)
3. Extract subject RDN sequence `:public_key.pkix_subject_id(cert)`
4. Inspect result

I am getting:
```elixir
{_subject_serial_number,
 {:rdnSequence,
  [[{:AttributeTypeAndValue, {2, 5, 4, 3}, {:utf8String, "test"}}]]}}
```

**Expected behavior**
The return type should reflect actual value that is returned.

**Affected versions**
I am trying it with OTP 23.2.7

**Comment by IngelaAndin** [comment]
The type depends on the ASN-1 spec so the documentation is incorrect and should be changed.
