### ISSUE TITLE
ssl:connect/3 function_clause crash in OTP-23.2.3

### ISSUE THREAD

**Issue by achan1989** [erlang/otp#4658]
OTP 23.2.3 on Ubuntu 20.04 crashes in a call to ssl:connect/3.  But I don't know enough Erlang or TLS to know whether this is an invalid usage on my part, a server bug, or an Erlang bug.  A minimal example to run in `erl`:

```
application:start(crypto).
application:start(asn1).
application:start(public_key).
application:start(ssl).

Host = 'irc.chat.twitch.tv'.
Port = 6697.
Suites = [#{
  cipher => aes_128_gcm,
  key_exchange => ecdhe_rsa,
  mac => aead,
  prf => sha256}].
Options = [
  {versions, ['tlsv1.3']},
  {verify, verify_peer},
  {cacertfile, "/etc/ssl/certs/ca-certificates.crt"},
  {ciphers, Suites},
  {crl_check, true}].
ssl:connect(Host, Port, Options).
```

Which crashes with a function clause error (full log in [crash.txt](https://github.com/erlang/otp/files/6185590/crash.txt)):

```
{function_clause,
                [{tls_handshake_1_3,get_key_shares,
                     [undefined],
                     [{file,"tls_handshake_1_3.erl"},{line,2288}]}, ...
```

I am requesting tlsv1.3 only, and if ssllabs is correct the server doesn't support it.  But in that case I would expect a more graceful error.

**Comment by IngelaAndin** [comment]
If you try using a TLS-1.3 cipher suite (TLS-1.2 and TLS-1.3 do not have any overlapping cipher suites, ssl:cipher_suites(exclusive, 'tlsv1.3')).  You will get the result {error, closed}.  I would have expected the server to send a protocol_version alert however that has nothing to do with erlang in this case. On the other hand, I agree that your options should have generated an error message and not even tried to connect with those options. We will enhance the error handling.

**Comment by achan1989** [comment]
Thanks.

Just to be clear: is it valid to use the cipher suite I specified with TLS v1.3, and invalid to use it with TLS v1.2?

**Comment by IngelaAndin** [comment]
The cipher suite you specified is a TLS-1.2 cipher suite and can not be used with TLS-1.3.
```
ssl:cipher_suites(exclusive, 'tlsv1.3'). 
[#{cipher => aes_256_gcm,key_exchange => any,mac => aead,
   prf => sha384},
 #{cipher => aes_128_gcm,key_exchange => any,mac => aead,
   prf => sha256},
 #{cipher => chacha20_poly1305,key_exchange => any,mac => aead,
   prf => sha256},
 #{cipher => aes_128_ccm,key_exchange => any,mac => aead,
   prf => sha256},
 #{cipher => aes_128_ccm_8,key_exchange => any,mac => aead,
   prf => sha256}]

```

**Comment by IngelaAndin** [comment]
After #4983 this will no longer result in a function_clause but rather in an {error, closed} which is as good as it gets with that server. The server could have been more graceful in its handling sending a version alert but that is someone else's problem.
