### ISSUE TITLE
a crashing gen_server should be able to control last message formatting

### ISSUE THREAD

**Issue by mikpe** [erlang/otp#4673]
**Describe the bug**
When a gen_server crashes, a crash report is output which combines the last message received ("Last message in was") with the server's state. The latter is passed through the server's optional `format_status/2` callback, which allows it to limit the amount of detail logged. Unfortunately, the server's callback module has no say in how to format the last message. The only control I've found is the `kernel` application's `error_logger_format_depth` variable, but that applies to much more than just the last message. The end result is that if gen_servers crash while receiving large messages (and the crashes may be due to unrelated issues such as destinations being down), considerable resources may be spent formatting and enqueuing crash reports, ultimately causing nodes to run out of memory.

**To Reproduce**
Send a large message to a gen_server that crashes. Observe the message being included in the crash report.

**Expected behavior**
A gen_server should be able to control, via a callback, how the last message is formatted in crash reports.

**Affected versions**
n/a

**Additional context**
We may end up using `error_logger_format_depth`, but it's a blunt instrument.

**Comment by iilyak** [comment]
Just wanted to chime in and mention that we at CouchDB also have this issue and ended up writing a hack on a custom logging backend to extract it (see here https://github.com/apache/couchdb/commit/e1b4259a9e0714fb78f740ee763dd12f84bbca1a). Which is unfortunate and sub-optimal. 

The problem affects : 
- gen_fsm 
- gen_event
- gen_server

**Comment by mikpe** [comment]
> Just wanted to chime in and mention that we at CouchDB also have this issue and ended up writing a hack on a custom logging backend to extract it (see here [apache/couchdb@e1b4259](https://github.com/apache/couchdb/commit/e1b4259a9e0714fb78f740ee763dd12f84bbca1a)). Which is unfortunate and sub-optimal.

Thanks for the pointer. I've done some experiments with `error_logger_format_depth`. Although it limits the initial "Generic server <Pid> terminating" message, it does not affect the subsequent `crash_report` message. Looks like doing this in the logging backend (we have our own) is the only solution for now.

**Comment by garazdawi** [comment]
I've added a proposed solution to include a message in the format_status call in #4952, any comments on the API would be most welcome.
