### ISSUE TITLE
Function zip:create add directories with wrong permissions making unpacked archive inaccessible by default

### ISSUE THREAD

**Issue by sigsergv** [erlang/otp#4687]
**Describe the bug**

When you create archive using `zip:create()` and specify directory in second argument, that directory is added into the archive with "file" permissions 0644 instead of 0755. So resulting archive content is inaccessible after using `unzip` command on linux and you need to change directory mode to access it.

**To Reproduce**

~~~~
% mkdir -p /tmp/test-zip/dir-1
% cd /tmp/test-zip
% echo "Sample data." > dir-1/file.txt
% erl
1> zip:create("test.zip", ["dir-1"]).
^C^C
% zipinfo test.zip
Archive:  test.zip
Zip file size: 227 bytes, number of entries: 2
?rw-r--r--  2.0 unx        0 b- stor 21-Mar-29 04:25 dir-1/
?rw-r--r--  2.0 unx       11 b- defN 21-Mar-29 04:26 dir-1/file.txt
2 files, 11 bytes uncompressed, 13 bytes compressed:  -18.2%
~~~~

**Expected behavior**

Unpacked directories must have correct permissions.

**Affected versions**

Erlang/OTP 23

**Additional context**

Source file permissions are fine:

~~~~
% ls -l
drwxrwxr-x 2 user user 4096 Mar 29 04:25 dir-1
-rw-rw-r-- 1 user user  227 Mar 29 04:35 test.zip
~~~~

**Comment by kjellwinblad** [comment]
I have made a fix for this here https://github.com/kjellwinblad/otp/tree/kjell/stdlib/zip_exec_access_dirs/OTP-17295/GH-4687. I will make a pull request once the fix has gone through our nightly tests.

It is not obvious what "correct permissions" are. In the commit mentioned above, all directories get permission 744, making them accessible for the owner.
