### ISSUE TITLE
uri_string:parse/1 doesn't parsing ip:port pair

### ISSUE THREAD

**Issue by NoobsEnslaver** [erlang/otp#4692]
**Describe the bug**
uri_string:parse/1 doesn't parsing ip:port pair.

**To Reproduce**
```
> uri_string:parse("127.0.0.1:8080").
{error,invalid_uri,":"}
```

**Expected behavior**
```
> uri_string:parse("127.0.0.1:8080").
#{host => "127.0.0.1", port => 8080}
```

**Affected versions**
23.3

**Additional context**
I see in source of uri_string that this case is foreseen - `parse_host`-> `try parse_ipv4_bin` -> `parse_port`, but looks like `parse_scheme` is too greedy and eat all symbols before  : .

**Comment by lhoguin** [comment]
This is not a proper URI nor a URI reference. You need to at least put `//` in the front:

``` erlang
2> uri_string:parse("//127.0.0.1:8080").
#{host => "127.0.0.1",path => [],port => 8080}
```

The code cannot guess whether this is a scheme, a host/port pair or a path segment with a colon.

**Comment by NoobsEnslaver** [comment]
Code can everything you want, just don't drop second colon blindly and if there is no second colon for separate scheme from host just backtrack and try to parse this part as host.

**Comment by NoobsEnslaver** [comment]
Also, complexity of parsing it is not a users problem - if `parse("127.0.0.1")` returns `#{path => "127.0.0.1"}` user expect that `parse("127.0.0.1:80")` returns atleast `#{path => "127.0.0.1", port => 80}`. Every lib or tool also works with this kind of uri - 'gen_tcp`, `httpc`, etc, so there is expects the same.

**Comment by RoadRunnr** [comment]
The documentation of uri_string is stating clearly that it works on RFC3986 URIs only:

> A URI is an identifier consisting of a sequence of characters matching the syntax rule named URI in RFC 3986.

[RFC3986](https://tools.ietf.org/html/rfc3986#section-3) is quite explicit on the structure of URIs:

> URI         = scheme ":" hier-part [ "?" query ] [ "#" fragment ]

so, everything before the first colon is the scheme. According to that `127.0.0.1:8080` would have a scheme of `127.0.0.1` and hier-part of `8080`.

The string you are trying to parse is simply not a valid URI.

**Comment by lhoguin** [comment]
> returns atleast `#{path => "127.0.0.1", port => 80}`

The port cannot be after the path.

The rules are that it's a scheme before the colon: `scheme:hier-part` as mentioned. If given a URI reference and it's to a host/port, then it has to be `//host:port`; otherwise if it's a path, then it has to be given with a leading dot `./path:more`. That's just how the algorithm works.

@RoadRunnr The module doesn't only work with RFC3986 URIs, it also works with URI references.

**Comment by RoadRunnr** [comment]
> @RoadRunnr The module doesn't only work with RFC3986 URIs, it also works with URI references.

Not the parse function:

> Parses an RFC 3986 compliant uri_string() into a uri_map(), that holds the parsed components of the URI. If parsing fails, an error tuple is returned.

**Comment by lhoguin** [comment]
The documentation is wrong and/or misleading.

**Comment by lhoguin** [comment]
Just prepend `"//"`.

``` erlang
uri_string:parse(["//", IPPort])
```
