### ISSUE TITLE
Dialyzer gets the wrong type for socket:send/3

### ISSUE THREAD

**Issue by pergu** [erlang/otp#4693]
**Describe the bug**
Dialyzer gives a bogus warning when using socket:send/3 correctly. This is caused by a type being wrong in the socket module. 
-opaque select_tag() :: atom()
should really be:
-opaque select_tag :: atom() | {atom(), integer()}.
**To Reproduce**
run dialyzer on a file:
-module(bug).
-export([send/2]).
send(Socket, Data) ->
  case socket:send(Socket,Data,nowait) of
    {select, _SelectInfo} -> great;
    _ -> not_great
  end.

This finds a dialyzer error, (that the select branch can not be matched)

**Expected behavior**
There should not be an error.

**Affected versions**
OTP 24 at least maybe 23 as well

**Additional context**
It is obvious from inspection that the type is wrong as well see for example line 1477 in socket.erl which through the use of ?SELECT_INFO(Tag, Ref) matches the tag to a 2-tuple.

To be clear, the bug is not in dialyzer but in the types for socket.erl

**Comment by RaimoNiskanen** [comment]
Yes, stumbeled on that and corrected it on my current working branch for sendfile, to be merged in to 'master', upcoming 24.

**Comment by pergu** [comment]
Awesome! Thank you!

**Comment by paulo-ferraz-oliveira** [comment]
@RaimoNiskanen, as per your latest common, can we expect to see this in rc3? Thanks.

**Comment by RaimoNiskanen** [comment]
Hopefully...

**Comment by RaimoNiskanen** [comment]
Nope.  Sorry.  I failed the deadline

**Comment by RaimoNiskanen** [comment]
I have created PR #4748 with the sendfile implementation.  The third commit: 74e37ef, is the fix for this issue.

**Comment by paulo-ferraz-oliveira** [comment]
No biggie. It should make it to 24.0, at least, right?

**Comment by RaimoNiskanen** [comment]
Yes, absolutely!
