### ISSUE TITLE
file:read_file/2 max_size option

### ISSUE THREAD

**Issue by okeuday** [erlang/otp#4694]
**Is your feature request related to a problem? Please describe.**
There currently is no safe way to prevent a large file from being read into memory.  It currently is possible to use `file:read_file_info` before calling `file:read_file/1` though the size would never be checked in a safe way (the file could easily increase in size inbetween the two function calls.

**Describe the solution you'd like**
If the C source code used `fstat` to check the file size of the open file descriptor, based on a `max_size` option provided in a list, that would be a safe solution.  An example could be `file:read_file("data.bin", [{max_size, 16384}])` with 16384 as the max file size in bytes.  If the file was too large, `{error, efbig}` could be returned.

**Describe alternatives you've considered**
Not aware of an alternative

**Additional context**
This matters when attempting to manage the amount of memory an Erlang process may consume when reading files in that are randomly changing.

**Comment by jhogberg** [comment]
1. You ought to know what you're opening. If you're using unknown paths from untrusted sources then that's a problem in and of itself.
1. There is nothing magical about C that prevents race conditions, the file can still grow after doing `fstat`. 
1. This is trivial to implement yourself:

```erlang
bounded_read_file(Path, MaxSize) ->
    case file:open(Path, [raw, binary]) of
        {ok, Fd} ->
            Result = case file:read_file_info(Fd, []) of
                         {ok, #file_info{size=Sz}} when Sz < MaxSize ->
                             file:read(Fd, Sz);
                         {ok, #file_info{}} ->
                             {error, too_big};
                         Error ->
                             Error
                     end,
            file:close(Fd),
            Result;
        Error ->
            Error
    end.

```
