### ISSUE TITLE
[Question] Erlang OTP Compatibility with Ubuntu Bionic

### ISSUE THREAD

**Issue by AnirKulk** [erlang/otp#4697]
Hello,

Where can I find Erlang otp compatibility matrix with Ubuntu? Specifically I want to know if the package erlang/OTP-20.3.4.tar.gz can be installed on Ubuntu Bionic?

**Comment by garazdawi** [comment]
Erlang/OTP 20 is out of support (we only support the three latest major versions, that is OTP-21, OTP-22 and OTP-23). So I would recommend that you update to a release that still receives security patches.

We run our tests on many different OSs of which Ubuntu Bionic is one of them. The tests are however not run on OTP-20 as that is out of support, so while it should work, we do not regularly check that it does.

**Comment by paulo-ferraz-oliveira** [comment]
@AnirKulk, Erlang/OTP 20-23 should work OK with Ubuntu Bionic. I've used it with no problems.
