### ISSUE TITLE
zlib:inflate fails on valid input

### ISSUE THREAD

**Issue by ananthakumaran** [erlang/otp#4710]
**Describe the bug**
`zlib:inflate` fails to inflate valid data under certain conditions. @magnetised came up with the [zip file](https://github.com/ananthakumaran/zstream/pull/9) that triggers the bug. I am attaching the specific zlib encoded file that triggers the bug [zlib-bug.log](https://github.com/erlang/otp/files/6252480/zlib-bug.log) (.log extension is used to overcome github attachment validation). The size of each chunk seems to play an important part in triggering the bug.

**To Reproduce**
```erlang
main(_) ->
    io:format('OTP: ~p ERTS: ~p ~n', [erlang:system_info(otp_release), erlang:system_info(version)]),

    {ok, Binary} = file:read_file('./zlib-bug.log'),

    %% inflate in one shot
    %% works
    Z1 = zlib:open(),
    ok = zlib:inflateInit(Z1, -15),
    _ = zlib:inflate(Z1, Binary),
    ok = zlib:inflateEnd(Z1),
    ok = zlib:close(Z1),

    %% inflate in chunks
    %% works
    Z2 = zlib:open(),
    ok = zlib:inflateInit(Z2, -15),
    <<C21:100000/binary, C22:100000/binary, C23:100000/binary, C24:100000/binary, C25:100000/binary, C26/binary>> = Binary,
    _ = zlib:inflate(Z2, C21),
    _ = zlib:inflate(Z2, C22),
    _ = zlib:inflate(Z2, C23),
    _ = zlib:inflate(Z2, C24),
    _ = zlib:inflate(Z2, C25),
    _ = zlib:inflate(Z2, C26),
    ok = zlib:inflateEnd(Z2),
    ok = zlib:close(Z2),

    %% inflate in chunks with specific size
    %% fails
    Z3 = zlib:open(),
    ok = zlib:inflateInit(Z3, -15),
    <<C31:83187/binary, C32:94617/binary, C33:94617/binary, C34:94617/binary, C35:94617/binary, C36:94617/binary, C37/binary>> = Binary,
    _ = zlib:inflate(Z3, C31),
    _ = zlib:inflate(Z3, C32),
    _ = zlib:inflate(Z3, C33),
    _ = zlib:inflate(Z3, C34),
    _ = zlib:inflate(Z3, C35),
    _ = zlib:inflate(Z3, C36),
    _ = zlib:inflate(Z3, C37),
    ok = zlib:inflateEnd(Z3),
    ok = zlib:close(Z3).
```

**Expected behavior**
```
OTP: "23" ERTS: "11.1"
escript: exception error: data_error
  in function  zlib:inflateEnd_nif/1
     called as zlib:inflateEnd_nif(#Ref<0.3493035981.480641034.6240>)
  in call from erl_eval:do_apply/6 (erl_eval.erl, line 680)
  in call from erl_eval:expr/5 (erl_eval.erl, line 449)
  in call from escript:eval_exprs/5 (escript.erl, line 872)
  in call from erl_eval:local_func/6 (erl_eval.erl, line 567)
  in call from escript:interpret/4 (escript.erl, line 788)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1
```
Should inflate the data without the above error

**Affected versions**
21, 22, 23 (not sure about versions prior to 21)

**Comment by jhogberg** [comment]
Thanks for your report, I've fixed this in https://github.com/erlang/otp/pull/4714 and will release a patch shortly.

**Comment by ananthakumaran** [comment]
@jhogberg thanks for the confirmation. Does this bug also affect `zlib:safeInflate` method? I am thinking of switching to that method if this bug only affects `zlib:inflate`, so we can avoid the OTP upgrade.

**Comment by jhogberg** [comment]
Unfortunately there's no workaround for this. It affects just about all functions in the `zlib` module, including `deflate/2`, so you'll need to upgrade once the patch is released.
