### ISSUE TITLE
Yum installation of erlang-23.2.3-1.el8.x86_64.rpm  failing when gpg validation is turned on.Can we get the signed rpm?

### ISSUE THREAD

**Issue by itssiri** [erlang/otp#4717]
**Describe the bug**
Unable to yum install erlang-23.2.3-1.el8.x86_64.rpm on rhel8 and centos8 with the GPG check turned on.

**To Reproduce**
Steps to reproduce the behavior.
When installing erlang-23.2.3-1.el8.x86_64.rpm  on rhel8 /centos8 , we are getting the below error:

**Expected behavior**

**Affected versions**
The OTP versions that are affected by this bug.

**Additional context**
Add any other context about the problem here. If you wish to attach Erlang code you can either write it directly in the post using [code tags](https://guides.github.com/features/mastering-markdown/), create a [gist](https://gist.github.com), or attach it as a zip file to this post.

**Comment by itssiri** [comment]
Error: Failed to validate GPG signature for erlang-22.3.4-1.el8.x86_64.

**Comment by garazdawi** [comment]
Hello!

All Erlang OS packages are provided by third parties, so you will have to contact whoever it is that has built this package to find out how to fix it.
