### ISSUE TITLE
start_ret() type definition does not take into account start_monitor

### ISSUE THREAD

**Issue by sebasb21** [erlang/otp#4725]
I think 

`-type start_ret()  :: {'ok', pid()} | 'ignore' | {'error', term()}.`

should be replaced by 

`-type start_ret()  :: {'ok', pid()} | {'ok', {pid(), reference()}} | 'ignore' | {'error', term()}.` 

in gen.erl, so dialyzer don't complain on start_monitor

Sebastian

**Comment by paulo-ferraz-oliveira** [comment]
This is the line the issue refers to: https://github.com/erlang/otp/blob/master/lib/stdlib/src/gen.erl#L150.
