### ISSUE TITLE
Retrieving "keylog" TLS connection information fails for TLS 1.3

### ISSUE THREAD

**Issue by lukebakken** [erlang/otp#4738]
The ability to retrieve NSS-style key log information was introduced in https://github.com/erlang/otp/pull/2823

**Describe the bug**

Calling `ssl:connection_information(Sock, [keylog])` returns an empty list when TLS 1.3 is used.

**To Reproduce**

* Build Erlang/OTP from a branch that includes some debugging output - 
https://github.com/lukebakken/otp/blob/lrb-add-keylog-debugging/lib/ssl/src/ssl_gen_statem.erl#L2007-L2038
* Run the following commands:
```
git clone https://github.com/lukebakken/erlang-tls-misc.git
cd erlang-tls-misc
git submodule update --init
cd tls-gen/basic
make
cd ../..
```
* Run the `run-tls-server.sh` script. Ensure that the custom OTP build from above is being used. It will output debug info starting with `@@@@@@@@`
* In another window, run `run-tls-client.sh`
* In the first window, you will see the `badmatch` error due to missing information that is expected by `maybe_add_keylog/

**Expected behavior**

You should be able to retrieve the NSS-style key log information, and be able to write it to a file as described here in "Exporting the Secrets":

https://erlang.org/doc/apps/ssl/using_ssl.html

**Affected versions**

I tested with the current `master` as well as OTP `23.3.1`

**Additional context**

Output of `run-tls-server.sh` on my machine. You can see the missing information in the connection info that causes `lists:keyfind` to return `false`, which results in the `badmatch` error:
[tls-server.log.txt](https://github.com/erlang/otp/files/6314368/tls-server.log.txt)

As you'll see in the stack trace, this line fails to find the required information:

```
{client_traffic_secret_0, ClientTrafficSecret0Bin} = lists:keyfind(client_traffic_secret_0, 1, Info),
```

**Comment by lukebakken** [comment]
Of course, after filing this "bug", I find `keep_secrets` in the code as well as the docs 🤦‍♂️ 

https://erlang.org/doc/man/ssl.html#type-keep_secrets

**Comment by garazdawi** [comment]
If you have any suggestions to make the docs clearer a pr would be most welcome!

**Comment by lukebakken** [comment]
@garazdawi will do.

**Comment by lukebakken** [comment]
https://github.com/erlang/otp/pull/4743
