### ISSUE TITLE
Undefine tv:start().

### ISSUE THREAD

**Issue by juancar0505** [erlang/otp#4740]
I have the ejabberd docker image installed on my pc and I have set up a Mnesia database
I am trying to see the contents of the database. Is there a function defined for this? How can I inspect ejabberd's Mnesia tables?
I cant use tv:start() because is not define

**Comment by dgud** [comment]
This is not a bug, only bugs should be added here, use erlang-questions for questions, or slack.

And you didn't use the template, if you did, you would have provided useful information such which release you are running on,
but if you had I would have answered that should use 'observer:start()' instead.

**Comment by juancar0505** [comment]
Sorry im using this version:
Elang/OTP 22 [erts-10.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [asyc-threads:1]
Eshell V10.5 

I have already tried also with the  'observer:start()' command and it doesn't work either.
