### ISSUE TITLE
when i start erlang, process hangs.

### ISSUE THREAD

**Issue by njuyang14** [erlang/otp#4744]
**Describe the bug**
  
when i start erlang vm like this, the process hangs.   
Maybe in infinity loop, memory and cpu is increasing fast.   
  
![image](https://user-images.githubusercontent.com/22637345/115015746-bae26d00-9ee6-11eb-8e82-44dfdcf9cd44.png)
![image](https://user-images.githubusercontent.com/22637345/115015215-e7e25000-9ee5-11eb-93c4-ae3e8b610bd2.png)

**To Reproduce**
Steps to reproduce the behavior.
```
$ erl
```

**Expected behavior**
i hope to run erlang vm

**Affected versions**
The OTP versions that are affected by this bug.
i just try 21.3.8.21, 22.3.4.16, 23.3.1, but these are all  affected by this bug.

**Additional context**
my OS is MAC OS 11.2.3, and firstly i run them in less than 11.2.3 (forgot the version i firstly use)  
i searched annother issue erlang/otp#2968,   
and use the otp 22.3.4.16 more than 22.3.4.14 ,   
but it also hangs.

**Comment by garazdawi** [comment]
Can you attach with `lldb` to the process and print what the different threads are doing?

**Comment by njuyang14** [comment]
i try to search erl_crash.dump and find a function is in infinity loop.   
```erlang
group_history:read_full_log
```
in the group_history module, i find some file and directory named 'erlang-history', 'erlang-shell-log', so i try to delete them.
and then it's all ok;
```
$ cd ./Library/Caches/erlang-history
$ ls -alht
-rw-r--r--   1     26B  4 16 19:58 erlang-shell-log.idx
drwxr-xr-x   7    224B  4 16 19:58 .
-rw-r--r--   1     51K  4 16 19:58 erlang-shell-log.2
-rw-r--r--   1     13B  4 16 19:58 erlang-shell-log.siz
drwx------+ 85    2.7K  4 16 19:44 ..
-rw-r--r--   1    1.0K  4 14 12:15 erlang-shell-log.3
-rw-r--r--   1    51K  3 11 14:50 erlang-shell-log.1
$ 
```

when i scan the funtion and add some logs, i got the log results.   
i think the error is the {NextCont, Logs} just match the {badarg,continuation}. hahaha 
```erlang
-spec read_full_log(term()) -> [string()].
read_full_log(Name) ->
    case disk_log:chunk(Name, start) of
        {error, no_such_log} ->
            show_unexpected_close_warning(),
            [];
        eof ->
            [];
        {Cont, Logs} ->
            io:format("Cont ~p Logs ~p~n", [Cont, Logs]),
            lists:reverse(maybe_drop_header(Logs) ++ read_full_log(Name, Cont))
    end.
read_full_log(Name, Cont) ->
    case disk_log:chunk(Name, Cont) of
        {error, no_such_log} ->
            show_unexpected_close_warning(),
            [];
        eof ->
            [];
        {NextCont, Logs} ->
            io:format("Cont ~p Logs ~p~n", [NextCont, Logs]),
            maybe_drop_header(Logs) ++ read_full_log(Name, NextCont)
    end.
```
output:
```
Cont error Logs {corrupt_log_file,"~/Library/Caches/erlang-history/erlang-shell-log.3"}
Cont error Logs {badarg,continuation}
Cont error Logs {badarg,continuation}
Cont error Logs {badarg,continuation}
Cont error Logs {badarg,continuation}
...(infinity loop)
```

**Comment by garazdawi** [comment]
I think this is fixed here: https://github.com/erlang/otp/pull/4581 which will be part of OTP-24.
