### ISSUE TITLE
dialyzer "pattern never match the type" false negative

### ISSUE THREAD

**Issue by okeuday** [erlang/otp#4745]
**Describe the bug**
Dialyzer fails to see a possible match, possibly due to a call-path memory limitation.  I noticed this problem when changing unrelated source code that is provided to the dialyzer command-line.

**To Reproduce**
```
git clone https://github.com/CloudI/CloudI
cd CloudI/src
git checkout cbd8d32f3a48934c768a54fc8838d30989e2877e
# to avoid creating a plt you can do:
# ln -s ~/.dialyzer_plt dialyzer.plt
./autogen.sh && ./configure --disable-java-support --disable-javascript-support --disable-perl-support --disable-php-support --disable-python-support --disable-python-c-support --disable-ruby-support && make dialyze
```
provides the error:
```
cloudi_core_i_logger.erl:1092: The pattern 
         <{'error', Reason},
          State> can never match the type 
         <'ok',
          #state{}>
```
However, that error shouldn't occur because it isn't valid based on the source code.

**Expected behavior**
The "pattern never match the type" error should not occur based on the source code.

**Affected versions**
I have replicated it with both Erlang/OTP 23.3 and 24.0-rc2.

**Additional context**
If you used the separate `cloudi_core` repository (internal services only) you wouldn't see the error with the same `syslog_socket` source code (`{error, Reason}` is a return value from the syslog_socket module):
```
git clone https://github.com/CloudI/cloudi_core
cd cloudi_core
git checkout b09a5d0f872925b7d931e3aa941ac170cabc5870
rebar get-deps compile
dialyzer --verbose -I include ebin deps/*/ebin
```

**Comment by jhogberg** [comment]
The function in question (`log_init/2`) is only ever called with the return value of `syslog_open/2`, so let's have a look at that:

```erlang
syslog_open(undefined, _, State) ->
    {ok, State#state{syslog = undefined,
                     syslog_level = undefined}};
syslog_open(_Omitted_for_brevity, LogError, State) ->
    %% ... snip ...
    case cloudi_x_syslog_socket:start_monitor(Options) of
        {ok, Syslog} ->
            {ok, State#state{syslog = Syslog,
                             syslog_level = SyslogLevel}};
        {error, Reason} = Error ->
            if
                LogError =:= true ->
                    ?LOG_T0_ERROR("syslog error: ~tp", [Reason],
                                  State#state{syslog = undefined,
                                              syslog_level = undefined});
                LogError =:= false ->
                    {Error, State}
            end
    end.
```

`cloudi_x_syslog_socket` doesn't exist and the call will crash at runtime, so the only possible return value is that of the first clause: `{ok, #state{}}`. This means that the second clause of `log_init/2` will never match.

If you change it to call `syslog_socket` instead, like you do in `cloudi_core`, it works just fine.

> Dialyzer fails to see a possible match, possibly due to a call-path memory limitation.

Remember that `dialyzer` is never wrong. It's error messages might give C++ a run for its money but they are always right when you dig deeper.

This is not because `dialyzer` is somehow infallible but because it never emits errors it cannot prove. `dialyzer` has its limitations but  _they reduce the accuracy of the analysis_ (and therefore the amount errors it can prove), which ironically means that fixing or just shuffling your code around may cause it to report errors in other parts. Errors that were always there but could not be proven.

Put another way, `dialyzer` couldn't see that `syslog_open/2` only returned `{ok, #state{}}` prior to your latest commit and assumed that both clauses of `log_init/2` were reachable. Now that it knows for certain that the second clause can't be reached, it reports the error.

**Comment by okeuday** [comment]
@jhogberg If you would have ran the commands to reproduce, you would see the module has a name change to make the function call valid.  The prefix is added to provide the equivalent of a namespace in Erlang, due to the lack of such a concept in the language.  I hope you are able to look at this again with more attention, whether in this issue or a future issue.

**Comment by aronisstav** [comment]
I'm taking a look into this too (currently installing boost).

**Comment by aronisstav** [comment]
When running the suggested command, I got an error about including assert.hpp in two different files, which I am currently solving by hand.

**Comment by okeuday** [comment]
@aronisstav http://cloudi.org/faq.html#3_Overview has a list of packages for different OS installations.  The list is hard to keep up-to-date, but shows that you should only need C/C++ and the boost header/library files with the configure flags provided.  The boost header files missing may be the assert.hpp error you saw.

**Comment by aronisstav** [comment]
My solution of commenting out the include does not work, but I am not competent in c++. 

Error before:
```
./assert.hpp:31:2: error: cassert or assert.h should not be included
```

Error after commenting out:
```
cloudi.cpp:603:5: error: use of undeclared identifier 'assert_initialize'
```

**Comment by aronisstav** [comment]
I see! I will add boost ahead of everything else then.

**Comment by aronisstav** [comment]
@okeuday In the meantime, would you be willing to give a few more details on how you reason that the clause can be reached?

**Comment by okeuday** [comment]
@aronisstav Sure, more info below:
```erlang
start_monitor(Options) ->
    case start(Options) of
        {ok, Pid} = Success ->
            _ = erlang:monitor(process, Pid),
            Success;
        {error, _} = Error ->
            Error
    end.
```
Shows the `{error, _}` tuple from the `cloudi_x_syslog_socket:start_monitor/1`  function call.  In the `syslog_socket` module (modified to be `cloudi_x_syslog_socket`) the `start_monitor/1` is calling `start/1` which is getting the `{error, _}` tuple from `gen_server:start/3`.  `gen_server:start/3` can definitely provide a `{error, _}` tuple.

From what I have seen, some unrelated source code appears to make dialyzer produce this error.  I am not sure which source code, but it should be something in the external directory.

**Comment by okeuday** [comment]
@aronisstav To simplify the situation I locally modified the Makefile.am to remove dialyzer file paths, making the execution match what was ran with the separate `cloudi_core` repository (modifying the `dialyze-internal` Makefile target).  That makes the execution like:
```
dialyzer --verbose --plt ./dialyzer.plt \
              -I lib/cloudi_core/include \
              lib/cloudi_core/ebin \
              lib/cpg/ebin \
              lib/erlang_term/ebin \
              lib/key2value/ebin \
              lib/keys1value/ebin \
              lib/pqueue/ebin \
              lib/quickrand/ebin \
              lib/reltool_util/ebin \
              lib/supool/ebin \
              lib/syslog_socket/ebin \
              lib/trie/ebin \
              lib/uuid/ebin \
              lib/varpool/ebin
```
That still provides the error, which is strange because its view of the source code is much more limited (it won't see the various applications in the external directory because those are mainly related to the `cloudi_service_`... Erlang applications).  I still don't see a good reason for that error to occur and it just started happening recently.

**Comment by jhogberg** [comment]
> @jhogberg If you would have ran the commands to reproduce, you would see the module has a name change to make the function call valid. The prefix is added to provide the equivalent of a namespace in Erlang, due to the lack of such a concept in the language. I hope you are able to look at this again with more attention, whether in this issue or a future issue.

That was rather confusing, but I think I've found it. `cloudi_x_syslog_socket:start_monitor/1` accepts the following options:

```erlang
-type options() :: list({transport, transport()} |
                        {transport_options, list()} |
                        {cloudi_x_protocol, cloudi_x_protocol()} |
                        {utf8, boolean()} |
                        {facility, facility()} |
                        {app_name, app_name()} |
                        {path, nonempty_string()} |
                        {host, inet:ip_address() | inet:hostname()} |
                        {port, undefined | inet:port_number()} |
                        {timeout, timeout_milliseconds()}).
```

While you're passing:

``` erlang
    Options = [{app_name, SyslogIdentity},
               {facility, SyslogFacility},
               {transport, SyslogTransport},
               {transport_options, SyslogTransportOptions},
               {protocol, SyslogProtocol}, %% Name doesn't match `cloudi_x_protocol` in the spec
               {utf8, true},
               {path, SyslogPath},
               {host, SyslogHost},
               {port, SyslogPort},
               {timeout, 5000}],
```

Since `protocol` is not an accepted option, `dialyzer` assumes that the call will crash, and therefore the only possible return value for `syslog_open/2` is the `{ok, #state{}}` of the first clause.

Fixing the option name makes everything pass.

**Comment by jhogberg** [comment]
The original source of `syslog_socket` has the following spec, so it looks like a problem with your namespacing script:

```erlang
-type options() :: list({transport, transport()} |
                        {transport_options, list()} |
                        {protocol, protocol()} | %% Gets replaced with `cloudi_x_protocol`
                        {utf8, boolean()} |
                        {facility, facility()} |
                        {app_name, app_name()} |
                        {path, nonempty_string()} |
                        {host, inet:ip_address() | inet:hostname()} |
                        {port, undefined | inet:port_number()} |
                        {timeout, timeout_milliseconds()}).
```

**Comment by okeuday** [comment]
@jhogberg Yes, that is it.  So, it isn't a dialyzer problem.  It is related to some separate source code I updated and how that impacts the `cloudi_x_` prefix addition.  Thank you for pointing it out and sorry for the noise.
