### ISSUE TITLE
Fix spec for os:getenv

### ISSUE THREAD

**Issue by tothlac** [erlang/otp#4753]
Spec for `os:getenv/1` :
```
-spec getenv(VarName) -> Value | false when
      VarName :: env_var_name(),
      Value :: env_var_value().
```

, where

```
-type env_var_value() :: string().
```
This is false spec. Even the documentation says:
```
getenv(VarName) -> Value | false   
```
getenv/2 can return anything depending on the default value passed to the function in the 2nd arg.

Because of this I got following dialyzer error:

```
1869: The pattern 'false' can never match the type string()
```

**Comment by galdor** [comment]
In `os:getenv/2`, the default value is defined as an `env_var_value()`, i.e. as a `string()`, so the return value can only be `false` or an `env_var_value()`.

**Comment by tothlac** [comment]
Yes, but the spec says it always returns string(), which is not true since it can return false as well. Because of this wrong specification, I got the dialyzer warning mentioned above.

**Comment by galdor** [comment]
`os:get_env/2` cannot return `false` since it returns the default value if the variable is missing. Which code is causing this Dialyzer warning ?

**Comment by tothlac** [comment]
For instance this will cause dialyzer problem, and dialyzer is right about that. 

```
deduce_prev_rel_path(_RelName, _RelVersion, _Profile, upgrade_checks = _Type) ->
    case get_previous_rel_path_from_env() of
        false ->
            {error, var_not_defined};
        Value ->
            Value
    end.

-spec get_prev_rel_path_from_env() -> Res when
      Res :: undefined | string().
get_prev_rel_path_from_env() ->
    os:getenv("PREV_REL_PATH", []).
```
Dialyzer says:
```
1869: The pattern 'false' can never match the type string()
```
and this is right because the specification of getenv/1 says it will always return string(), but actually, it can return false as well.

**Comment by garazdawi** [comment]
It is the spec of `get_prev_rel_path_from_env` that is incorrect. If you remove it, or fix it to be:

```erlang
-spec get_prev_rel_path_from_env() -> Res when
      Res :: false | string().
```

dialyzer is happy.

**Comment by tothlac** [comment]
You are right, that fixed the issue. I was wrong with my spec.  Not sure about this, but should not the spec for getenv/1 look like :

```
-spec getenv(VarName) -> Value | false when
      VarName :: env_var_name(),
      Value :: false | env_var_value().
```
Anyways, thanks for the help. The ticket can be closed.

**Comment by garazdawi** [comment]
The `false` is already included in the return in the function, that is `Value | false`. So there is no need to list it as part of the `Value`.
