### ISSUE TITLE
Clarification on licensing

### ISSUE THREAD

**Issue by f-camera** [erlang/otp#4754]
Hi All,
could you please help me clarify under which license are some specific files released?
I'm interested in *.xpm files under lib/wx/examples (e.g. [https://github.com/erlang/otp/blob/master/lib/wx/examples/simple/sample.xpm](https://github.com/erlang/otp/blob/master/lib/wx/examples/simple/sample.xpm) ).

In particular, should they they be considered under main otp license (Apache 2.0) or under [https://github.com/wxWidgets/wxWidgets/blob/master/docs/licence.txt](https://github.com/wxWidgets/wxWidgets/blob/master/docs/licence.txt)?

Thanks in advance.

**Comment by dgud** [comment]
The sample icon is copied from wxWidgets so it's wxWidgets licence, we should probably replace that with an
erlang icon.

Thanks for pointing that out.
