### ISSUE TITLE
warn_missing_spec doesn't warn when export_all flag enabled

### ISSUE THREAD

**Issue by mheiber** [erlang/otp#4772]
**Describe the bug**

When An Erlang file with a missing top-level spec is compiled with the combination of `export_all` and `warn_missing_spec` there is no warning for missing specs.

**To Reproduce**

```erl
-module(missing).

-compile(warn_missing_spec).
-compile([export_all, nowarn_export_all]).

main(_) -> ok.
```

**Expected behavior**

warning for a missing spec: `missing.erl:6: Warning: missing specification for function main/1`

**Affected versions**

Tested on OTP 24

**Comment by mheiber** [comment]
I'm happy to PR a fix if it helps.

**Comment by paulo-ferraz-oliveira** [comment]
Not exactly sure it's linked, but I reported a similar (scope) issue here: https://github.com/erlang/otp/issues/4628.

**Comment by mheiber** [comment]
🎉 thank you
