### ISSUE TITLE
Unused type that "depends" on itself not flagged as unused

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlang/otp#4784]
**Describe the bug**
Declaring an unused type as `-type t() :: [t()].` "tricks" the compiler into thinking the type is used.

**To Reproduce**
Declare the type and compile the module.

**Expected behavior**
A warning like ": Warning: type t() is unused".

**Affected versions**
24.0, at least, but potentially more.

**Additional context**
I'm not sure if there's a special reason for this to happen, but I can imagine there's a missing validation somewhere. At the same time, I had this in a module that had an unused type that depended on 10 other types. As I removed that one, the compiler allowed me to reduce my LOC by a bit, which is always good in my book.

**Comment by uabboli** [comment]
Indeed, the linter should warn about this. Too late for 24.0, but I'll create a ticket.

**Comment by uabboli** [comment]
The branch is based on master because the fix is minor and we don't
take any risks when it comes to breaking builds due to the
`warnings_as_errors` compiler option.
