### ISSUE TITLE
Error in case matching in OTP 24

### ISSUE THREAD

**Issue by nickva** [erlang/otp#4788]
**Describe the bug**

The snippet below called as `test(1)` throws instead of returning `ok`.

```erlang
-module(failcase24).

-export([test/1]).

test(N) ->
    case {N >= 0, N == undefined} of
        {true, _} -> ok;
        {_, true} -> ok;
        _ -> throw(lt_0_or_undefined)
    end,
    ok.
```

**To Reproduce**

Compile the above snippet and run as:
```
1> failcase24:test(1).
** exception throw: lt_0_or_undefined
     in function  failcase24:test/1 (failcase24.erl, line 9)
```

**Expected behavior**

The expectation is for `test(1)` to return `ok`. It returns `ok` on `23.3.1`

**Affected versions**

`24-rc3`

**Additional context**

* The snippet above is a condensed version of a validation function from CouchDB code which was failing during a test run with the new Erlang `24` https://github.com/apache/couchdb/blob/main/src/couch_views/src/couch_views_validate.erl#L88-L92

* Compiling the code on `23.3.1` and loading the module on `24-rc3` doesn't show the error. Compiling on `24-rc3` and running on `23.3.1` did show the error. So it's seems like a `24-rc3` compiler issue. 

* Compiling to core erlang didn't show any differences but compiling to assembly showed differences in emitted code:

Working version (23.3.1)
```
{module, failcase24}.  %% version = 0

{exports, [{module_info,0},{module_info,1},{test,1}]}.

{attributes, []}.

{labels, 9}.

{function, test, 1, 2}.
  {label,1}.
    {line,[{location,"failcase24.erl",5}]}.
    {func_info,{atom,failcase24},{atom,test},1}.
  {label,2}.
    {bif,'>=',{f,0},[{x,0},{integer,0}],{x,1}}.
    {bif,'=:=',{f,0},[{x,0},{atom,undefined}],{x,0}}.
    {test,is_ne_exact,{f,3},[{x,1},{atom,true}]}.
    {test,is_eq_exact,{f,4},[{x,0},{atom,true}]}.
  {label,3}.
    {move,{atom,ok},{x,0}}.
    return.
  {label,4}.
    {move,{atom,lt_0_or_undefined},{x,0}}.
    {line,[{location,"failcase24.erl",9}]}.
    {call_ext_only,1,{extfunc,erlang,throw,1}}.
```

Not working (24-rc3)
```
{module, failcase24}.  %% version = 0

{exports, [{module_info,0},{module_info,1},{test,1}]}.

{attributes, []}.

{labels, 8}.

{function, test, 1, 2}.
  {label,1}.
    {line,[{location,"failcase24.erl",5}]}.
    {func_info,{atom,failcase24},{atom,test},1}.
  {label,2}.
    {test,is_eq_exact,{f,3},[{x,0},{atom,undefined}]}.
    {move,{atom,ok},{x,0}}.
    return.
  {label,3}.
    {move,{atom,lt_0_or_undefined},{x,0}}.
    {line,[{location,"failcase24.erl",9}]}.
    {call_ext_only,1,{extfunc,erlang,throw,1}}.
```

**Comment by frej** [comment]
Having seen something like this in my development compiler (using experimental passes) which disappeared when I tried to troubleshoot it, I ran a bisect on @nickva's example.

Bisection points to 81bc659e4cf0f4842f28c1042a21122c0ff6a57b
