### ISSUE TITLE
Compile error in `erl_proc_sig_queue.c`

### ISSUE THREAD

**Issue by itssundeep** [erlang/otp#4790]
**Describe the bug**
Compile error in `erl_proc_sig_queue.c` when compiled with USE_VM_PROBES flag enabled.

**To Reproduce**
- Run configure with `--with-dynamic-trace=systemtap`
- make

Error:
beam/erl_proc_sig_queue.c:6734:43: error: ‘mp’ undeclared (first use in this function); did you mean ‘hp’?
 6734 |      if (is_not_immed(ERL_MESSAGE_DT_UTAG(mp)))
 
 

**Expected behavior**
No build failures.

**Affected versions**
This bug is introduced with this change. 
https://github.com/erlang/otp/commit/0ab8930521a1404f26ea677eadd5694caf5e0d38

**Additional context**
Potential fix is to change `mp` to `msg`

**Comment by garazdawi** [comment]
fixed with #4795
