### ISSUE TITLE
[ssl] document what algorithms are supported for peercert

### ISSUE THREAD

**Issue by Sgiath** [erlang/otp#4800]
**Describe the bug**
There is no documentation on what algorithms are supported for peer certificates. Also error code from the running application isn't helpful. If the algorithm is not supported it just returns `{error, no_peercert}` which is not very helpful for debugging.

**To Reproduce**
Go to https://erlang.org/doc/man/ssl.html#peercert-1 and see that there is no mention on what algorithms are supported.

Generate new self-signed certificate with unsupported algorithm:
```
openssl genpkey -algorithm ED25519 -out key.pem
openssl req -new -x509 -days 365 -key key.pem -out cert.pem
```
and use that certificate to connect to `ssl:listen/2` server. Call `ssl:peercert/1` and inspect the result.

**Expected behavior**
There is documentation on what algorithms are supported for peer certificates and error code is better describing what is happening. E.g.: `{error, algorithm_not_supported}`

**Affected versions**
OTP 23

**Additional context**
Also it would be great if more types of algorithms were supported but this was maybe addressed by #4756 PR?

**Comment by IngelaAndin** [comment]
I guess you did not use any verification ` {verify, verify_peer} ` option on your connection?! As then you would not have got a connection with an unsupported algorithm. Then you would have got a TLS, INSUFFICIENT_SECURITY,  ALERT with the log information no_suitable_signature_algorithm.   The signature algorithms are documented in the data type section of the man page.  

OTP-23:
```
signature_algs() = [{hash(), sign_algo()}]
sign_algo() = rsa | dsa | ecdsa

sign_scheme() =
    rsa_pkcs1_sha256 | rsa_pkcs1_sha384 | rsa_pkcs1_sha512 |
    ecdsa_secp256r1_sha256 | ecdsa_secp384r1_sha384 |
    ecdsa_secp521r1_sha512 | rsa_pss_rsae_sha256 |
    rsa_pss_rsae_sha384 | rsa_pss_rsae_sha512 |
    rsa_pss_pss_sha256 | rsa_pss_pss_sha384 | rsa_pss_pss_sha512 |
    rsa_pkcs1_sha1 | ecdsa_sha1
```

OTP-24:
```
signature_algs() = [{hash(), sign_algo()}]
sign_algo() = rsa | dsa | ecdsa | eddsa
 
sign_scheme() =
    eddsa_ed25519 | eddsa_ed448 | ecdsa_secp256r1_sha256 |
    ecdsa_secp384r1_sha384 | ecdsa_secp521r1_sha512 |
    rsa_pss_rsae_sha256 | rsa_pss_rsae_sha384 |
    rsa_pss_rsae_sha512 | rsa_pss_pss_sha256 |
    rsa_pss_pss_sha384 | rsa_pss_pss_sha512 | rsa_pkcs1_sha256 |
    rsa_pkcs1_sha384 | rsa_pkcs1_sha512 | rsa_pkcs1_sha1 |
    ecdsa_sha1

```

**Comment by Sgiath** [comment]
You are right, I have this in my configuration (calling it from Elixir):

```elixir
[
  {:verify, :verify_peer},
  {:verify_fun,
    {fn cert, event, _init_state ->
      IO.inspect(cert, label: "certificate")
      IO.inspect(event, label: "event")

      {:valid, :unknown_user}
    end, []}}
]
```

but my custom `:verify_fun` isn't even called when I connect with bad certificate and there are no logs about `INSUFFICIENT_SECURITY`. It just silently returns `{:error, :no_peercert}`.

With supported algorithm my `:verify_fun` is called and event is `{:bad_cert, :selfsigned_peer}`.

BTW it is desired behavior for my use-case to not verify certificates - I am working on non-HTTP protocol which expects self-signed certificates.

And thanks for pointing me to the documentation but I still think that there should be at least some note and link at `ssl:peercert/1` function pointing to this types since it is not at all obvious where to look for this information if you are not reading documentation from first page to the last but just looking up specification for functions you are interested in.

**Comment by IngelaAndin** [comment]
Humm ... I am not sure I follow your use case completely.  ssl:peercert/1 is a utility function that the user can call after the connection has been established and is not used during certificate path validation. Looking at the documentation I can see that we can make a small improvement in the type spec of this function. Perhaps we will add some links to the Users Guide of ssl and public_key applications for further reading but the description of supported algorithms details should not go here.  

Also, your verify_fun does not implement all the required clauses. Should look like:

```
fun(_,{bad_cert, _} = Reason, _) ->
	 {fail, Reason};
    (_,{extension, _}, UserState) ->
	 {unknown, UserState};
    (_, valid, UserState) ->
	 {valid, UserState};
    (_, valid_peer, UserState) ->
         {valid, UserState}
 end
```
Self-signed certificate chains are pretty useless from a security point as they provide no authenticity.

**Comment by Sgiath** [comment]
I am implementing a protocol where peer certificates are used as replacement for username/password. So user is expected to generate self-signed certificate and use it as client certificate. There is also option to not provide any certificate than the connection is treated as anonymous/unauthenticated.

So what I want to do is to accept any connection with or without peer certificate and if the certificate is present do not validate it at all just hand it to the application code which will probably compare it's fingerprint against it's user database or something like that.

So your `verify_fun` wouldn't work for me since I do get `bad_cert` when the certificate is self-signed. My actual function looks like this because I basically don't want to do anything with the certificate (present or not, valid or not) on protocol level and leave that to the application code:
```elixir
[
  {:verify, :verify_peer},
  {:verify_fun, {fn _cert, _event, _init_state -> {:valid, :unknown_user} end, []}}
]
```

**Comment by IngelaAndin** [comment]
No, it was not my suggestion that you use exactly that fun, it is the default verify_fun for {verify, verify_peer}.  I am just saying that you are not handling all the cases.  For instance, if your fun is called with an extension it should either validate it or say that it is unknown. And if you want to accept the self-signed cert chains you should catch that explicitly in your fun and not accept all errors.  Also, you do get the whole certificate in the 
valid_peer clause and here you can let the application fail the connection if their fingerprint check fails so that you do not get a connection at all if it is not desired!
