### ISSUE TITLE
crypto:crypto_dyn_iv_init core dump

### ISSUE THREAD

**Issue by tonyrog** [erlang/otp#4810]
**Describe the bug**
Core dump

**To Reproduce**
Steps to reproduce the behavior.

crypto:crypto_dyn_iv_init(des_ede3_cbc, <<>>, []).

**Expected behavior**
not core dump

**Affected versions**
The OTP versions that are affected by this bug.

Erlang/OTP 23 [erts-11.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

**Additional context**
Add any other context about the problem here. If you wish to attach Erlang code you can either write it directly in the post using [code tags](https://guides.github.com/features/mastering-markdown/), create a [gist](https://gist.github.com), or attach it as a zip file to this post.

**Comment by HansN** [comment]
Hej Tony :)
A fix is released in 

- OTP 24.0.1
- OTP 23.3.4.1 
- OTP 22.3.4.19

Thanks for the report!
