### ISSUE TITLE
empd implicitly binds to `::1` despite no IPv6 loopback device present

### ISSUE THREAD

**Issue by paulmenzel** [erlang/otp#4820]
**Describe the bug**

[From eturnal commit 3a65d408](https://github.com/processone/eturnal/commit/3a65d40818058137ee95e5af07a7701669e691f3)

> Binding epmd to a specific IP address lets it implicitly bind to ::1 as well, which can go wrong on IPv4-only systems.  See, for example, the following thread:
> 
> https://erlang.org/pipermail/erlang-questions/2016-March/thread.html#88408

**To Reproduce**

    # disable IPv6 support on the loopback device
    $ sudo sysctl net.ipv6.conf.lo.disable_ipv6=1
    $ ERL_EPMD_ADDRESS="127.0.0.1" ERL_EPMD_PORT=5678 epmd
    epmd: Sat Mar 19 22:40:09 2016: failed to bind socket: Cannot assign requested address

**Expected behavior**
On a system with IPv6 disabled, that means no IPv6 loopback present, epmd shouldn’t bind to `::1`.

In the thread, the claim below is made:

> A system with a working IPv6 implementation must have an IPv6 loopback.

As an alternative, to explicitly disable IPv6 support in epmd, would also work.

**Affected versions**
According to [the list thread](https://erlang.org/pipermail/erlang-questions/2016-March/thread.html#88408) since 18.3.

/cc @weiss

**Comment by polaris-alioth** [comment]
I have the same problem. Maybe provide a new environment is a alternative solution
#5394

**Comment by weiss** [comment]
I guess this issue is fixed by e8c9e121c1b286ecddd572190c2a1fe72adc97bb and can therefore be closed?
