### ISSUE TITLE
Cannot compile from a root directory

### ISSUE THREAD

**Issue by ericmj** [erlang/otp#4823]
**Describe the bug**
When compiling inside a root directory such as `/OTP` compilation fails, but compilation succeeds inside `/OTP/subdir`.

**To Reproduce**

```
mkdir -p /OTP
wget -nv "https://github.com/erlang/otp/archive/OTP-24.0.tar.gz"
tar -zxf "OTP-24.0.tar.gz" -C /OTP --strip-components=1
cd /OTP
./otp_build autoconf
./configure
make

[...]

=== Entering application ssl
make[3]: Entering directory '/OTP/lib/ssl/src'
SED x86_64-pc-linux-gnu /OTP
 GEN    /OTP/lib/ssl/src/deps/ssl.d
make[3]: *** No rule to make target '../../../bootstrap/lib/public_key/includ../../..-PUB-KEY.hrl', needed by '../ebin/ssl_crl_cache_api.beam'.  Stop.
make[3]: Leaving directory '/OTP/lib/ssl/src'
make[2]: Leaving directory '/OTP/lib/ssl'
make[2]: *** [/OTP/make/otp_subdir.mk:29: opt] Error 2
make[1]: Leaving directory '/OTP/lib'
make[1]: *** [/OTP/make/otp_subdir.mk:29: opt] Error 2
make: *** [Makefile:498: libs] Error 2
```

**Expected behavior**
Compilation should work regardless of working directory.

**Affected versions**
OTP-24.0

**Additional context**
Add any other context about the problem here. If you wish to attach Erlang code you can either write it directly in the post using [code tags](https://guides.github.com/features/mastering-markdown/), create a [gist](https://gist.github.com), or attach it as a zip file to this post.

**Comment by garazdawi** [comment]
Hello!

The problem is not that you run it in a subdirectory, it is that you run it in a subdirectory named `/OTP`. There is a sed script that looks for the root dir and replaces it in the dependency files, so in your cane anything named `/OTP` will be removed :)

I'll see what I can do about fixing the sed script to only match what it is supposed to match.

**Comment by garazdawi** [comment]
The unlucky sed script is this: https://github.com/erlang/otp/blob/master/lib/ssl/src/Makefile#L177-L186

Though I'm sure there may be other places that would also not be happy if you try to build from `/` (the root folder).
