### ISSUE TITLE
io_lib:format/3 with specific chars_limit falls into a loop

### ISSUE THREAD

**Issue by hareen-kancharla** [erlang/otp#4824]
**Describe the bug**
For specific nested terms and chars_limit, like the one mentioned below io_lib:format/3 falls into a loop. 
**To Reproduce**
```
1> f(F), F = fun R(I) -> case I =:= 0 of true -> 0; false -> [I, R(I-1)] end end.
#Fun<erl_eval.31.126501267>
2> io_lib:format("~p", [F(1000)], [{chars_limit, 1000}]). 
```
Similar bugs exists for nested tuples and nested maps. 
```
f(F), F = fun R(I) -> case I =:= 0 of true -> 0; false -> {I, R(I-1)} end end.
f(F), F = fun R(I) -> case I =:= 0 of true -> 0; false -> #{I => R(I-1)} end end.
```
**Expected behavior**
The list should be trimmed, to print the term until the soft limit of chars_limit is printed.
**Affected versions**
Tested in on the following version - Erlang/OTP 22 [erts-10.7.2.7] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
**Additional context**

I think the bug is in the function io_lib_pretty:print_length_list1, where the length needed to print a comma as a delimiter between elements in a list is counted twice. T is decremented twice at line 698 (tsub(T,1))and line 699 (tsub(T,Len+1)). But the length calculation done via list_length does it correctly by accounting it for only once.

Edit 1: More accurately the bug is this I think - when you have a tail-nested term like, {1,{2,{3 ...}}}} we reserve space for a comma even for the tail element (in line 698) which will never be used. I think there should be stronger checks to check if E is a tail element or not and only then decrement T by 1 and not decrement T at all in line 699.

And therefore in the function clause:
`print_length_list1(Term, D, T, RF, Enc, Str) when D =:= 1; T =:= 0
` when T =:= 0 and the walk terminates, the Length accumulated in Len via list_length (in print_length_list) is less than chars_limit.

Now, In find_upper (on finding Len < T) we exponentially keep increasing the depth and end up looping.

Find outputs from examples runs here - https://gist.github.com/hareen-kancharla/43480e5070a2a8c7498be69e18cfe644

I wish to make a pull request for this with the following change and understand if replacing tsub(T,1) wouldn't regress other cases. Let me know. 
```
--- a/lib/stdlib/src/io_lib_pretty.erl
+++ b/lib/stdlib/src/io_lib_pretty.erl
@@ -695,7 +695,7 @@ print_length_list1(Term, D, T, RF, Enc, Str) when D =:= 1; T =:= 0->
     More = fun(T1, Dd) -> ?FUNCTION_NAME(Term, D+Dd, T1, RF, Enc, Str) end,
     {dots, 3, 3, More};
 print_length_list1([E | Es], D, T, RF, Enc, Str) ->
-    {_, Len1, _, _} = Elem1 = print_length(E, D - 1, tsub(T, 1), RF, Enc, Str),
+    {_, Len1, _, _} = Elem1 = print_length(E, D - 1, T, RF, Enc, Str),
     [Elem1 | print_length_list1(Es, D - 1, tsub(T, Len1 + 1), RF, Enc, Str)];
 print_length_list1(E, D, T, RF, Enc, Str) ->
     print_length(E, D - 1, T, RF, Enc, Str).
```
```
Edit 1: 
print_length_list1([E | Es], D, T, RF, Enc, Str) ->
    %% If E is the last element in list, don't account length for a comma.
    T1 = case Es =:= [] of
             false -> T+1;
             true -> T
         end,
    {_, Len1, _, _} = Elem1 = print_length(E, D - 1, T1, RF, Enc, Str),
    [Elem1 | print_length_list1(Es, D - 1, tsub(T1, Len1), RF, Enc, Str)];
```

**Comment by uabboli** [comment]
Thanks a lot for pinpointing this bug. I've extended your fix a little
and added tests. Patches are planned for 22, 23 and 24.

**Comment by uabboli** [comment]
Thanks again for the fix.
