### ISSUE TITLE
Travis builds not getting triggered

### ISSUE THREAD

**Issue by nirmannarang** [erlang/otp#4825]
I can see the .travis.yml file, though the builds are not getting triggered. 
https://travis-ci.org/github/erlang/otp
Has the Travis CI been completely removed now?

**Comment by michaelklishin** [comment]
OTP has adopted [GitHub Actions](https://github.com/erlang/otp/actions) and GItHub packaging features months ago.

**Comment by nirmannarang** [comment]
@michaelklishin Yes GA has been there already, but some functionality had been still kept in Travis as I recall reading in an issue. Just wanted to confirm if Travis has been completely removed now.

**Comment by garazdawi** [comment]
I've been planning to remove those files for a while but not gotten around to it yet.
