### ISSUE TITLE
Specs for application:start/2 callback, supervisor:start_link/1 and supervisor:start_link/2 and documentation are inconsistent.

### ISSUE THREAD

**Issue by ilya-klyuchnikov** [erlang/otp#4836]
**Describe the bug**
Running dialyzer (with the options to check consistency of specs) on code written according to documentation about application callback modules (https://erlang.org/doc/design_principles/applications.html#application-callback-module) reveals mismatches between specs.

**To Reproduce**
The simplest (dummy) application with a supervisor:

```erlang
-module(my_sup).

-behavior(supervisor).
-export([init/1, start_link/0]).

-spec init(Args :: term()) ->
    {ok, {supervisor:sup_flags(), [supervisor:child_spec()]}}.
init(_) ->
    {ok, {#{}, []}}.

-spec start_link() -> 
    supervisor:startlink_ret().
start_link() ->
    supervisor:start_link(?MODULE, []).
```

```erlang
-module(my_app).
-behavior(application).
-export([start/2, stop/1]).

% copy of application:start/2 callback spec
-spec start(application:start_type(), term()) ->
    {ok, pid()} | {ok, pid(), term()} | {error, term()}.
start(_StartType, _StartArgs) ->
    my_sup:start_link().

-spec stop(term()) -> ok.
stop(_State) ->
    ok.
```

Running `dialyzer -Wspecdiffs my_app.erl my_sup.erl` discovers the mismatches:

```
my_app.erl:5: The success typing for my_app:start/2 implies that the function might also return 
          'ignore' but the specification return is 
          {'error', _} | {'ok', pid()} | {'ok', pid(), _}
my_app.erl:5: The specification for my_app:start/2 states that the function might also return 
          {'ok', pid(), _} but the inferred return is 
          'ignore' | {'error', _} | {'ok', pid()}
```

While there are few discrepancies, the most problematic one is that `supervisor:start_link/1` may return `ignore`, which is not in the return type of the callback `application:start/2`. Meaning, that the application callback `start/2` SHOULD somehow handle the possibility of getting `ignore` from `supervisor:start_link/1`.

**Expected behavior**

Documentation and specs together are consistent and clear about how to write correct code (wrt to callback specs).

**Affected versions**
OTP 23 and 24 exhibit the described issue. 

**Additional context**

**Comment by garazdawi** [comment]
If the supervisor may return `ignore`, you need to handle that in the application start code. I don't think it is worth expanding the example in the Design Principles as it is very rare to have a supervisor that returns `ignore`, and I think keeping the example simple trumps explaining all scenarios.

If you don't want `dialyzer -Wspecdiffs` to complain, you also need to take that into consideration when coding your application. The Erlang/OTP code makes no attempts at being free of `-Wspecdiffs` errors.
