### ISSUE TITLE
Misleading dialyzer error

### ISSUE THREAD

**Issue by nathanl** [erlang/otp#4848]
**Describe the bug**
Dialyzer gives a misleading error.

**To Reproduce**
Run dialyzer on this Elixir module (from [this minimal reproduction repo](https://github.com/nathanl/confusing_dialyzer_error_example)).

The error seems to indicate that `get_greeting/1` always returns `nil`, which is not true.

```elixir
defmodule Foo do
  @moduledoc """
  Documentation for `Foo`.
  """

  @type a_greeting :: %{greeting: String.t()}

  @spec foo(term()) :: String.t()
  def foo(val) do
    case get_greeting(val) do
      # The dialyzer error says:
      #
      # lib/foo.ex:27:pattern_match
      # The pattern can never match the type.
      #
      # Pattern:
      # %{:greeting => _greeting}
      #
      # Type:
      # nil
      #
      # Dialyzer seems to be saying that `get_greeting/1` will always return
      # `nil`, but that's not true. The other type of value that it can return
      # is not mentioned in this error message.
      # The spec for `get_greeting/1` says it can return `a_greeting()`, which
      # would match here. But its spec is wrong, which is the real problem.
      %{greeting: greeting} ->
        greeting
      nil ->
        "FOOOOOOO"
    end
  end

  # This spec is wrong because the non-nil return value doesn't actually match
  # the `a_greeting()` type, since it isn't a map.
  # But dialyzer doesn't identify this spec as the problem.
  @spec get_greeting(term()) :: a_greeting() | nil
  def get_greeting(val) do
    case val do
      :a ->
        # Whoops, this isn't a map, it's a list of tuples (a "keyword list")
        Enum.map(["hi"], fn word -> {:greeting, word} end)
      _ ->
        nil
    end
  end

end
```

**Expected behavior**
Dialyzer should say that the spec for `get_greeting/1` is incorrect because the non-nil return value is not a map.

**Affected versions**
Tested with Erlang 24.0

**Comment by uabboli** [comment]
It's hard for Dialyzer to suggest where the error actually resides. It
generally trusts the user, that is, that the specs are correct.

Dialyzer does not say that get_greeting/1 will always return 'nil',
but it shows the part of the success typing which is also part of the
contract.

As long as the contract and the success typing have something in
common, no contract warning is output by default. If the Dialyzer
option '-Wunderspecs' is added--which is not generally recommended as
it returns many false positives--the success typing is shown in a
warning:

  The specification for conf:get_greeting/1 states that the function
  might also return
          #{'greeting' := string()} but the inferred return is 
          'nil' | [{'greeting', 'word'}, ...]
