### ISSUE TITLE
Inconsistent dialyzer underspec warning

### ISSUE THREAD

**Issue by paulozulato** [erlang/otp#4851]
**Describe the bug**
Dialyzer is running fine when function spec states the return is a proplist, but it complains (underspec warning) when spec states the return is a proplist emulation.

**To Reproduce**
Follow used rebar.config and two versions of same module which differ only on spec.  
rebar.config:
```
    {erl_opts, [debug_info]}.
    {deps, []}.
    {dialyzer, [
       {get_warnings, true},
       {warnings, [error_handling, underspecs, unknown, unmatched_returns]}
    ]}.
```

Source with proplist emulation:
```
    -module(test).

    -export([test/0]).

    %% From <https://erlang.org/doc/man/proplists.html>
    -type property() :: atom() | tuple().
    -type proplist() :: [property()].
    -spec test() -> proplist().
    test() ->
       [
           {one_test, [a,b,c]},
           {another_test, [d,e,f]}
       ].
```

Dialyzer result:
```
    ===> Verifying dependencies...
    ===> Analyzing applications...
    ===> Compiling test
    ===> Dialyzer starting, this may take a while...
    ===> Updating plt...
    ===> Resolving files...
    ===> Updating base plt...
    ===> Resolving files...
    ===> Checking 204 files in ../../home/pzulato/.cache/rebar3/rebar3_24.0_plt...
    ===> Copying ../../home/pzulato/.cache/rebar3/rebar3_24.0_plt to _build/default/rebar3_24.0_plt...
    ===> Checking 204 files in _build/default/rebar3_24.0_plt...
    ===> Doing success typing analysis...
    ===> Resolving files...
    ===> Analyzing 1 files with _build/default/rebar3_24.0_plt...

    src/test.erl
    Line 8 Column 2: Type specification test:test() -> proplist() is a supertype of the success typing: test:test() -> [{'another_test',['d' | 'e' | 'f',...]} | {'one_test',['a' | 'b' | 'c',...]},...]
    ===> Warnings written to _build/default/24.0.dialyzer_warnings
    ===> Warnings occurred running dialyzer: 1
```

Source with real proplist:
```
    -module(test).

    -export([test/0]).

    -spec test() -> proplists:proplist().
    test() ->
       [
           {one_test, [a,b,c]},
           {another_test, [d,e,f]}
       ].
```

Dialyzer result:
```
    ===> Verifying dependencies...
    ===> Analyzing applications...
    ===> Compiling test
    ===> Dialyzer starting, this may take a while...
    ===> Updating plt...
    ===> Resolving files...
    ===> Checking 204 files in _build/default/rebar3_24.0_plt...
    ===> Doing success typing analysis...
    ===> Resolving files...
    ===> Analyzing 1 files with _build/default/rebar3_24.0_plt...
```

**Expected behavior**
Dialyzer seems to be handling external types in a different way that it handles internal types once the dialyzer runs on above examples should return the same results. As discussed on [mailing list](http://erlang.org/pipermail/erlang-questions/2021-May/101065.html), it should return the underspec warning for both cases.

**Affected versions**
I have tested it on OTP 23.2.6 and OTP 24 with same result.

**Comment by paulo-ferraz-oliveira** [comment]
22.3.4.18 too.

**Comment by uabboli** [comment]
This is a known issue and we have an (old) ticket regarding this matter, but is has not been prioritized. I've asked Kostis and Stavros for advice on how to go forward.

**Comment by aronisstav** [comment]
Hi @uabboli and @paulozulato! (allso ccing @kostis )

@uabboli has narrowed down this inconsistency in a [commit](804df7a5) of mine from 2011, which makes Dialyzer suppress underspec warnings when they involve remote types.

My subjective line of thinking about this was something like the following: if the kind of value you want to express is matching some remote type (especially if it's a well known type, like `proplist()` here), and you still want to use `-Wunderspecs`, it would be annoying for Dialyzer to complain that your values are actually a subset of the remote type.

I see now that this leads to other unexpected results and I am not sure what's the best way forward. "underspecs" are a pain, overall, and that's why they are off by default.

**Comment by uabboli** [comment]
This issue is now referred to in our internal ticket OTP-12160. The issue will be resolved when and if we find a way to proceed.
