### ISSUE TITLE
Race condition in proc_lib:stop/3

### ISSUE THREAD

**Issue by Maria-12648430** [erlang/otp#4853]
**Describe the bug**
`proc_lib:stop/3` works like this:
* spawn and monitor a process that sends a `terminate` system message to the process to stop via `gen:call`
* wait for a `DOWN` message from the spawned process, or kill it after the timeout given to `proc_lib:stop/3` and raise an `exit(timeout)` exception

If the timeout given to `proc_lib:stop/3` is very small (like, `0`), the spawned process is likely to be killed before it has sent the `terminate` message to the process to be stopped, so when the `timeout` exception is raised, it may be that the process to be stopped may be stopped later (`terminate` message was sent before the kill) or that it won't be stopped at all (the kill happened before the `timeout` message was sent).

The documentation for [`proc_lib:stop/3`](http://erlang.org/doc/man/proc_lib.html#stop-3) states:
```text
Orders the process to exit with the specified Reason and waits for it to terminate.
Returns ok if the process exits with the specified Reason within Timeout milliseconds.
If the call times out, a timeout exception is raised.
...
```
This suggests that the process is _always_ ordered to terminate.

Similarly, the documentation for [`gen_server:stop/3`](http://erlang.org/doc/man/gen_server.html#stop-3) (and analogous, [`gen_statem:stop/3`](http://erlang.org/doc/man/gen_statem.html#stop-3)), which ultimately uses `proc_lib:stop/3` and is thus subject to the same problem, states:
```text
Orders a generic server to exit with the specified Reason and waits for it to terminate.
...
If the server has not terminated within the specified time, a timeout exception is raised.
...
```

**To Reproduce**
Example `gen_server`:
```erlang
-module(test).
-behavior(gen_server).

-export([start_link/0, init/1, handle_call/3, handle_cast/2, terminate/2]).

start_link() ->
        gen_server:start_link(?MODULE, [], []).

init([]) ->
        process_flag(trap_exit, true),
        {ok, undefined}.

handle_call(_, _, State) ->
        {noreply, State}.

handle_cast(_, State) ->
        {noreply, State}.

terminate(_, _) ->
        % artificial delay
        receive after 1000 -> ok end.
```

Example session:
```
1> process_flag(trap_exit, true).
false
2> {ok, P}=test:start_link().
{ok,<0.83.0>}
3> catch gen_server:stop(P, normal, 0).
{'EXIT',timeout}
4> % wait a bit
4> flush().
ok
5> catch gen_server:stop(P, normal, 100).
{'EXIT',timeout}
6> % wait a bit
6> flush().
Shell got {'EXIT',<0.83.0>,normal}
ok
```

The example server delays its termination for a second.
In the example session, we use a zero-timeout stop at `3>` and a 100ms-timeout at `5>`. In both cases we get the expected `timeout` exception (the example server did not terminate in the given timeout), but after the 100ms-timeout stop, the example server eventually terminates after the artificial 1s delay, while after the zero-timeout stop it keeps running forever.

**Expected behavior**
Even with a zero-timeout stop, the intended process (example server) should be eventually stopped.

**Affected versions**
Probably all OTP >= 18.0, at least the documentation says that this is the version when `proc_lib:stop` appeared.

**Additional context**
The intention behind using a zero timeout in a catch+stop was (for me at least) something along the lines of "just tell it to stop and keep going, I don't care _when_ it really stops". I don't know if that is encouraged, but that is besides the point, the behavior should be consistent (timeout-independent) and according to what the documentation suggests.

**Comment by Maria-12648430** [comment]
Oh, I get it, nvm 😅

**Comment by garazdawi** [comment]
Agreed that the way it works today is a bug and the fix seems simple enough by just adding a synchronization in between the caller and the spawned process.

**Comment by Maria-12648430** [comment]
Yes... I'm just unsure about purpose of the `infinity` timeout in the `sys:terminate/3` call on line 1089:
https://github.com/erlang/otp/blob/b9b5d751c86fd862bbdf0421c72005844e043edf/lib/stdlib/src/proc_lib.erl#L1086-L1094
This is the line after which a sync message should be sent to the caller process.

Now, if the process to terminate is responding to the system message, this should be over quickly, all right, and we send the sync message. But if it doesn't answer, the call will hang infinitely, until the receive timeout in the caller process kicks in. But if the caller is waiting for a sync message from the spawned process before it enters the receive, and the spawned process is (infinitely) waiting for `sys:terminate/3` to return, the whole thing deadlocks.

I guess my question now is, would it be safe to use `0` instead of `infinity` there? I followed the calls around a bit: `sys:terminate` calls `sys:send_system_msg`, which in turn calls `gen:call`. `gen:call` sends the message to the given process (if it exists), and _then_ waits for a response, or for the given timeout to expire. If that timeout is `0`, it will immediately throw an exit exception, but the message will have been sent. Is that correct?

**Comment by garazdawi** [comment]
> the whole thing deadlocks.

Ah, of course. I did not realize this when looking at the code before...

Maybe the best solution is to use `sys:terminate/3` with the timeout as an argument and just skip the proxy process?

I assume that the proxy process was added in order to consume any late replies from the shutting down the process, but now that we have process aliases used in `gen:call` we do not get any late messages so we should be able to just make `proc_lib:stop` call `sys:terminate` directly and then map the error reasons to the correct values.

**Comment by Maria-12648430** [comment]
Hm. `sys:terminate` returning doesn't mean the process has terminated, it just means the system message has been sent and was "acked" by the target process (in my example in the initial post, the example gen_server will still linger for another second before it really terminates). That means that we would have to recalculate the timeout, ie take a timestamp before the `sys:terminate/3` call with the given timeout, and if it responds in time, take another timestamp, calculate the time spent in the call, subtract it from the given timeout, and use that in the receive.

Instead (assuming it really _is_ safe), we could call `sys:terminate/3` with a timeout of `0`, and then use the full timeout in the receive?

And yes, the proxy process is obsolete I guess :)

**Comment by juhlig** [comment]
I'm making up a draft, let's see how it works :)

**Comment by garazdawi** [comment]
> Hm. sys:terminate returning doesn't mean the process has terminated, it just means the system message has been sent and was "acked" by the target process (in my example in the initial post, the example gen_server will still linger for another second before it really terminates).

So easy to get turned around in the code...

**Comment by Maria-12648430** [comment]
Now imagine me reading it on my tiny mobile in a swaying train... 😅

@juhlig great, thanks :) How's it going, any results yet?

**Comment by juhlig** [comment]
Hm, not as straight-forward as I thought it would be. There is a nasty thing that makes things complicated and defeats your `sys:terminate/3` with zero timeout scheme.

You do something like `catch proc_lib:stop(Pid, Reason, 1000)`. If the process acks the system message and then exits with the same `Reason`, you get `ok`. If it exits with a different `Reason`, you get `{'EXIT', OtherReason}`. Good. But if the process exits with whatever reason (`SomeReason`) _without_ answering the terminate system message, what you get is `{'EXIT', {SomeReason, {sys, terminate, [...]}}}`. In a way, this is accurate as the exit was raised by `sys:terminate` (actually, `sys:send_system_msg`), but on the other hand, this is just the exit of the process, enriched with some more info.

With the zero timeout approach, you will always get the first scenario. To me, this seems good enough, and more useful on the outside, but... @garazdawi, what do you think?

**Comment by juhlig** [comment]
For reference, this would be `proc_lib:stop` with the zero timeout approach:
```erlang
stop(Process, Reason, Timeout) ->
    Mref = erlang:monitor(process, Process),
    catch sys:terminate(Process, Reason, 0),
    receive
        {'DOWN', Mref, _, _, Reason} ->
            ok;
        {'DOWN', Mref, _, _, {noproc, {sys, terminate, _}}} ->
            exit(noproc);
        {'DOWN', Mref, _, _, CrashReason} ->
            exit(CrashReason)
    after Timeout ->
        demonitor(Mref, [flush]),
        exit(timeout)
    end.
```

This is roughly what is necessary to keep the old behavior:
```erlang
stop(Process, Reason, Timeout) ->
    Mref = erlang:monitor(process, Process),
    T0 = erlang:monotonic_time(millisecond),
    case catch sys:terminate(Process, Reason, Timeout) of
        ok ->
            ok;
        {'EXIT', Reason1} ->
            demonitor(Mref, [flush]),
            exit(Reason1)
    end,
    T1 = ceil(erlang:monotonic_time(microsecond)),
    Timeout1 = Timeout - (T1 - T0),
    receive
        {'DOWN', Mref, _, _, Reason} ->
            ok;
        {'DOWN', Mref, _, _, {noproc, {sys, terminate, _}}} ->
            exit(noproc);
        {'DOWN', Mref, _, _, Reason2} ->
            exit(Reason2)
    after Timeout1 ->
        demonitor(Mref, [flush]),
        exit(timeout)
    end.
```

**Comment by Maria-12648430** [comment]
I... see... 😦
