### ISSUE TITLE
Fix dir listing HTML generated by httpd

### ISSUE THREAD

**Issue by u3s** [erlang/otp#4855]
**Describe the bug**
Dir listing HTML page generated by httpd does not look good.

- The columns are not aligned properly
- The icons does not work - image references point to non-existing files

![dir_listing_issue](https://user-images.githubusercontent.com/4620572/118940900-7b79c700-b951-11eb-8990-9ab3b9649fd9.png)

**To Reproduce**
1. Start the server
```
inets:start().
{ok, Pid} = inets:start(httpd, [{port, 8080},
                                {server_name,"httpd_server"},
                                {server_root,"/some/folder/with/various/files_and_dirs"},
                                {document_root,"/some/folder/with/various/files_and_dirs"},
                                {bind_address, "localhost"}]).

```
2. Navigate to http://localhost:8080

3. Verify alignment and icons

**Expected behavior**
Dir listing HTML renders as aligned view with visible icons:
 - columns should be nicely aligned no matter on how long the item name is
 - icons are displayed for various file and dir types
 - behavior is _reasonably_ consistent among most popular browsers
 - icon image alt text still presented for non graphical browsers

**Additional context**
This tickets content is based on #4677

**Comment by zuiderkwast** [comment]
I'll give it a shot.
