### ISSUE TITLE
Add support for SHAKE128 and SHAKE256

### ISSUE THREAD

**Issue by dannote** [erlang/otp#4871]
### Rationale

SHAKE128 and SHAKE256 are part of the SHA-3 hash family (are also based on Keccak-f[1600] permutations), and while they are not as commonly used as SHA3-*, there are notorious projects, such as Tor, which [use them](https://github.com/torproject/torspec/blob/baf7bc9cf7d474e77daa9922471c2b090d90053d/rend-spec-v3.txt#L214) as key derivation functions. OpenSSL 1.1.1 [supports](https://www.openssl.org/docs/man1.1.1/man3/EVP_shake256.html) both.

### Purposed changes

As those functions are XOFs (Extendable Output Functions), supporting them might require some tweaks to existing APIs for providing variable output length. I think the cleanest way would be to pass tuples with algorithm name and size of output needed in bits:

```erlang
crypto:hash({shake256, 32}, Msg)

State = crypto:hash_init({shake128, 256})
State2 = crypto:hash_update(State, Msg)
crypto:hash_final(State2)
```

**Comment by HansN** [comment]
We don't plan for this, but it seems as a good medium-level PR project!  Volunteers?

**Comment by marcellanz** [comment]
I'm still working on this one; having the implemenation and tests ready and now make sure it's properly documented too. I expect to have a PR for review ready before the end of the year.

**Comment by marcellanz** [comment]
I'm preparing a PR for this issue updated to the latest OTP release.
