### ISSUE TITLE
ssl: doc `honor_cipher_order` mentioned twice in the same options list

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlang/otp#4873]
Here: https://erlang.org/doc/man/ssl.html#type-server_option.

As both `boolean()` and `honor_cipher_order()` (which is `boolean()`).

**Comment by IngelaAndin** [comment]
Thank you for the report.  For now, I have removed the duplicate without the meta-type. The meta-type was created to be able to get a link to the description of the option, and probably we missed removing the old definition of this type. However, we are currently evaluating documentation principles together with types to try to make things more consistent throughout the whole of OTP. That is why I stalled this at first, but I decided to make it consistent for the application for now as it probably will take some time before we come to a conclusion and updated document format.

**Comment by paulo-ferraz-oliveira** [comment]
Thank you, @IngelaAndin.
