### ISSUE TITLE
Debugger support (CLI and IDE) 

### ISSUE THREAD

**Issue by menih** [erlang/otp#4874]
Need to be able to debug quickly and efficiently, without GUI. In many situations, GUI is not installed on server hosts. I've tried using int module and it is very hard to use, not to mention documentation is very lacking. Looking for dbg like experience, where one can really be productive in troubleshooting issues.

The second level to that is a way to attack to a running node with popular IDEs (IntelliJ, Eclipse, VSCode) to a running system. This will greatly increase the chance of Erlang adaptation.

I think the language is quite different than other more main steam languages. But in my opinion, it is the tooling that makes more developers adopt a languages, specifically IDEs, Debuggers, Profiling.

**Comment by KennethL** [comment]
Erlang is actually quite famous for the support of trouble shooting live systems. It is the support for tracing that is unique. You can trace on function calls and message passing and there is sequential tracing. The tracing can be done without having a specially prepared system it is just to activate. You need contact with the E-node to trace either by Erlang distribution or if you have an Erlang shell on the node where you can activate and and examine the trace output.

The tools and APIs for tracing are dbg (in runtime_tools), observer.
You find documentation here: https://erlang.org/doc/apps/observer/introduction_ug.html and here: https://erlang.org/doc/man/dbg.html

Note that the tracing I am referring to i built in to the Erlang runtime and is not dependent on or related to LTTNG, DTRACE or SystemTap. The latter are only interesting if you want to build a system with trace support for both Erlang and C/C++ code and want the output merged in the same logs or if you want to add trace points into the Erlang runtime (written in C).

I don't claim that the debugger is super good but it is actually possible to run the GUI on another host than the system you want do debug. In general I recommend tracing as much more useful than running a debugger (a stepping and stopping one) when trouble shooting a live system. A debugger will stop processes which will most likely result in timeouts which would be very disturbing to the live system and eventually make it crash.

So yes Erlang is very different compared with other languages with its powerful support for tracing.

When it comes to IDE and Debugging there is ongoing work in the erlang_ls project with support for DAP (Debug Adapter Protocol). It demo was made during the Code Beam conference where a Vscode session using erlang_ls and DAP was connected to the Erlang debugger showing a very nice user interface. I think this is the way forward when improving the support for debugging. The tracing should also be possible to activate with use of the DAP protocol but that is not implemented yet AFAIK.

**Comment by menih** [comment]
@KennethL - indeed, Erlang tracing facility is very impressive. But what I am interested in is debugging. The ability to control where program stops, evaluate variables, control the timing on when and what to do next is a very important development tool, troubleshooting and most essential to learning new code base. Ask any developer "What is the best way you for you to learn new code base (after reading the code of course)" - I'll bet >90% will tell you "placing a breakpoint and track execution". And, it would be awesome if this capability is well integrated with today's popular IDEs, with an ability to remote attach to any running VM. That's just a common expectation from a robust language.

**Comment by victorolinasc** [comment]
IMHO debugging is already present at the language level and the way to extend it forward is through standard debugging protocols like [DAP](https://microsoft.github.io/debug-adapter-protocol/) in external tools as said @KennethL. [erlang-ls](https://github.com/erlang-ls/erlang_ls) and [elixir-ls](https://github.com/elixir-lsp/elixir-ls) are both providing this (or in the way to provide this) so that IDEs can use it.

I think, though, that what you want is not what will be present. Debugging on the BEAM is different than on, say, Java. When you stop at a breakpoint on the JVM, you actually stop the running thread and all of its state there. On the BEAM, everything is in a concurrent process so you would only debug "procedural erlang". Most libraries and architectures make use of the true concurrent nature of the BEAM and that would affect the ability to "(...) control the timing on when and what to do next" considerably.

I truly believe that the BEAM has not many equivalents in the programming world and so in my opinion it is hard to compare experiences here.

**Comment by menih** [comment]
I get Erlang processes are not OS threads. And I get the fact other processes will be still running. Erlang is actually not unique in offering lightweight green threads. Golang, Crystal, Huskell supports it and Java will be introducing them soon (loom). Still, they are all offering ability to interactively debug concurrent written code. The honest of course still lays on the developer on where to place their breakpoints, the conditions to be break and when to resume. Debugging a concurrent/multithreaded/parallelized is actually not a new concept and has been supported for a while by maybe IDEs and languages. In fact, Erlang has a standalone debugger. Its not up to par with other tools and suffers stability issues.

**Comment by dgud** [comment]
Most people don't use the debugger in erlang, so it gets a low priority.  But we are not aware of any bugs in it.

While the debugger behaves differently on erlang compared to Java/C  it have some positive that the other don't,
it uses erlang distribution, so you can do debugging on multiple nodes simultaneously.  Which when debugging something
like mnesia is hard to beat, when you can arbitrary paus remote processes to introduce timing issues.
So as long as you don't have timeouts in your system it works very well.

But as I said above it gets its priority based on usage and usage is low, but if you have any improvements you are very welcome 
to send in PR's..

**Comment by KennethL** [comment]
Closing this one since this is more a discussion than a concrete bug report or feature request. Welcome to report specific issues for example the stability issues you are mentioning. As @dgud mentioned you are very welcome with PRs as well.

**Comment by menih** [comment]
So here is a bug report - I've tried erlang debugger, following steps. Connected to remote node, with proper cookie, verified connectivity (net_adm:ping) and confirmed connectivity (erlang:nodes()), loaded interpretable module, set break point, checked break on First call and On break and invoked logic. Breakpoint is not triggered.

If I am doing something wrong, or missing a step, it would be missing from the docs. But I don't think this is the case, because following these steps on just simple shell works. But our app is obviously not as simple.

**Comment by KennethL** [comment]
Please create a new Github issue with your bug report (since this issue is closed) and provide some more information about how to recreate the problem. If it works with a trivial example please try to narrow down what is different in your case when it does not work. And the best would of course be if you could provide instructions for how to recreate the non working case.
