### ISSUE TITLE
TLS handshake issues once DST Root CA X3 expires

### ISSUE THREAD

**Issue by voltone** [erlang/otp#4877]
**Describe the bug**

Let's Encrypt, probably the most popular certificate authority these days, is now issuing certificates with a chain that includes a cross-signed certificate (details further below). Once the *DST Root CA X3* root certificate expires on September 30th, TLS clients using `ssl` will fail to connect to servers with such certificates. 

If users are caught unaware of this issue, I expect a lot of production environments are going to break on September 30th due to the widespread use of Let's Encrypt certificates. The only two options available as it stands are:

* Configure the server to not send the cross-signed CA certificate; this does not work for servers that are not under one's control
* Remove the *DST Root CA X3* certificate from the trust store prior to September 30th; this will work with clients that use `partial_chain` functions to handle alternate chains, but requires editing/forking the CA trust store

**To Reproduce**

The [future.voltone.net](future.voltone.net) server simulates the situation after the *DST Root CA X3* root certificate expires, using Let's Encypt staging certificates. The CA certificates and trust store for this environment can be found [here](https://gist.github.com/voltone/b0ff56227f342833900765e99dbee1a0).

```erlang
ssl:start().

ssl:connect("future.voltone.net", 443, [
  {verify, verify_peer},
  %% Trust store with both root CA certificates:
  {cacertfile, "trust_store.pem"},
  {depth, 3}
]).
%% --> {error,{tls_alert,{certificate_expired, ...}}}

ssl:connect("future.voltone.net", 443, [
  {verify, verify_peer},
  %% Only the new (short chain) root CA:
  {cacertfile, "new_root_ca.pem"},
  {depth, 3}
]).
%% --> {error,{tls_alert,{unknown_ca, ...}}}
```

**Expected behavior**

Ideally `ssl` would itself look for alternate ways of completing the chain using one of the certificates in its trust store, which would allow both scenarios above to pass without a `partial_chain` option. That would match how modern browsers and TLS implementations in other languages handle cross-signed certificates.

Alternatively, it should be possible for clients to opt-in to alternate-chain handling, using a `partial_chain` callback. Many clients already to this (e.g. [Hackney](https://github.com/benoitc/hackney/blob/master/src/hackney_ssl.erl#L49), [Mint](https://github.com/elixir-mint/mint/blob/main/lib/mint/core/transport/ssl.ex#L590)), but this hook will be ineffective once *DST Root CA X3* expires, since the handshake is aborted before it is called. It should be possible for `partial_chain` to nominate an alternate chain regardless of why `ssl` could not build the 'long' chain (missing from trust store, expired, revoked, ...).

**Affected versions**

OTP 23.3 and later. Prior versions ignored the expiry date on certificates in the CA trust store.

**Additional context**

Servers that use a Let's Encrypt certificate will be presenting [a certificate chain with a cross-signed certificate](https://community.letsencrypt.org/t/production-chain-changes/150739) for up to 3 years. The chain can be completed (trusted) in one of two ways:

* Clients with a recent CA trust store will ignore the cross-signed (3rd) certificate sent by the server, and instead complete the chain with the *ISRG Root X1* certificate from their trust store
* Older clients that do not have *ISRG Root X1* in their trust store, in particular older Android devices, complete the chain with the (expired) *DST Root CA X3* root certificate; Android disregards the expiry date on certificates in its CA trust store (as Erlang/OTP did prior to 23.3)

Several Erlang/Elixir TLS clients, such as Hackney and Mint, use an `partial_chain` handler to try and select an alternate (shorter) chain when `ssl` cannot complete the chain using its CA trust store. This enables (some) support for cross-signed certificates. However, OTP since v23.3 will fail the TLS handshake immediately if the longer chain is rooted in a CA certificate that is present in its trust store and that has expired. This means client do not have a chance to select the alternate chain rooted in the (valid) *ISRG Root X1* CA certificate.

More details in [this blog post](https://blog.voltone.net/post/29).

**Comment by IngelaAndin** [comment]
The reason for adding the check of the validity period for the trusted anchor certificates is that path validation time is the logical moment to check this even if it is not included in the path validation algorithm. OpenSSL does this too. And we think it adds to the security, as this probably will not be checked by the user, and if it has expired it should strictly not be trusted anymore. However, I can see that OpenSSL behaves differently with your example so we will look into changing our behavior.

**Comment by voltone** [comment]
> I can see that OpenSSL behaves differently with your example

That's presumably because OpenSSL selects the shorter chain when the ISRG root certificate is present in the trust store, ignoring the cross-signed certificate sent by the server.

> if it has expired it should strictly not be trusted anymore

Sure, and presumably the trust store (whether provided by the OS or a Hex package) will remove the expired CA in the next update. In the meantime I believe OTP should handle an expired CA as if it was already removed from the trust store: fail to complete the chain and call `partial_chain`, as that's what will happen once the true store has been updated.

That's the smallest possible fix here, and it will prevent issues for users of Hackney/Mint/etc. (But it won't work for clients that don't provide a `partial_chain` function: those would fail to connect to a server with the longer Let's Encrypt chain even if they have ISRG in their trust store.)

> we will look into changing our behavior.

Thanks. Please let me know if you need any further input or test scenarios.

**Comment by IngelaAndin** [comment]
@voltone patches are out now!   OTP 23.3.4.5 and  OTP 24.0.4 so there should be some time to adopt them in time for the expiration date at end of September.

**Comment by voltone** [comment]
Yes, I saw. That's excellent new, thanks a lot for all the work!

I will write another blog post to explain exactly what people can do to be ready for September 30th, depending on which release they are on and how they use 'ssl' (directly or through something like Hackney).
