### ISSUE TITLE
dialyzer reports overlapping domains for disjoint types

### ISSUE THREAD

**Issue by ilya-klyuchnikov** [erlang/otp#4882]
**Describe the bug**
dialyzer reports overlapping domains for disjoint types

**To Reproduce**

```erlang
-module(overlap).

-export([core/1]).

-type at() :: a | {at()}.
-type bt() :: b | {bt()}.

-spec core
    (at()) -> a;
    (bt()) -> b.
core(a) -> a;
core(b) -> b;
core({I}) -> core(I).
```

```
overlap.erl:8:2: Overloaded contract for overlap:core/1 has overlapping domains...
```

**Expected behavior**

There is no reason to reject this example.

`at()` and `bt()` do not overlap. Enumerating all the elements of `at()` and `bt()` explicitly, - clearly they are disjoint.
```
at() = a | {a} | {{a}} | {{{a}}} | ...
bt() = b | {b} | {{b}} | {{{b}}} | ...
```

**Affected versions**
OTP 24

**Additional context**

**Comment by kostis** [comment]
This is an interesting example and you are correct in what you are pointing out.
However,
1. The current type representation employs a depth limit abstraction, and thus loses the information that these two types are indeed disjoint, and
2. The presence of the third clause actually requires a quite complex analysis to figure out that the function will indeed return `a` for all `a()` terms and `b` for all `b()`s.

But feel free to provide a PR that fixes this.

**Comment by ilya-klyuchnikov** [comment]
> The current type representation employs a depth limit abstraction, and thus loses the information that these two types are indeed disjoint,

> But feel free to provide a PR that fixes this.

Thanks. 

What would you say about "explicitly giving up" when the depth limit is reached? Exposed in UI in a way like "Overloaded contract is too complex to analyze.."

**Comment by kostis** [comment]
> What would you say about "explicitly giving up" when the depth limit is reached? Exposed in UI in a way like "Overloaded contract is too complex to analyze.."

The suggested message is (of course) better for these cases, but I as far as I recall Dialyzer has (long ago) already lost the information that its representation of types is approximate, so I am not sure distinguishing between the types of "problems in overloaded contracts" is indeed possible.

But do not let me stop you.  Suggest/sketch such a PR, and we can comment on it.
