### ISSUE TITLE
No - otp_win32_xxx.exe in latest release

### ISSUE THREAD

**Issue by SebastianJust** [erlang/otp#4887]
Hello, 
There's no otp_win32_xx.exe file in the latest release: https://github.com/erlang/otp/releases/tag/OTP-22.3.4.19. 
Is it on purpose? :)

**Comment by garazdawi** [comment]
Only Erlang/OTP 23 and later are built with windows installers for patches.

In Erlang/OTP 23 we redid the windows build infrastructure to use WSL which allows us to also release patches. However, in releases before then, we cannot (or rather, we have not spent the time to setup a toolchain for it).

So if you need windows installers for patches before Erlang/OTP 23 you need to build them yourself.

**Comment by SebastianJust** [comment]
Hi,
Thank you for you answer.
Sorry to interrupt, but 22.3.4.19 is marked as latest release: https://github.com/erlang/otp/releases

**Comment by garazdawi** [comment]
The github UI is not really adapted for multiple release tracks, so it displays the latest release in time as the latest release, which in this case is a patch on an old release.

**Comment by SebastianJust** [comment]
Okay - thank you very much :)
