### ISSUE TITLE
Debugger breakpoint not triggered

### ISSUE THREAD

**Issue by menih** [erlang/otp#4904]
**Description** 
So here is a bug report - I've tried erlang debugger, following steps. Connected to remote node, with proper cookie, verified connectivity (net_adm:ping) and confirmed connectivity (erlang:nodes()), loaded interpretable module, set break point, checked break on First call and On break and invoked logic. Breakpoint is not triggered.

If I am doing something wrong, or missing a step, it would be missing from the docs. But I don't think this is the case, because following these steps on just simple shell works. But our app is obviously not as simple.

**To Reproduce**
I have no idea how to repro. Would appreciate if someone can tell me what logs/debugging info to collect which may indicate any failures, or steps to examine varies aspects of the debugger to ensure it is properly configured. For example: the mechanism that cause the breakpoint - is it properly installed? Are we missing any debug info? Were there any "hidden errors" during instrumentation?

**Affected versions**
OTP 22.3

**Comment by dgud** [comment]
Start node that should be debugged.

erl -sname unix
Erlang/OTP 24 [erts-12.0] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]

Eshell V12.0  (abort with ^G)
(unix@Dan)1> 


Start "debugger" node
werl.exe -sname win32
(win@Dan)1> net_adm:ping('unix@Dan').
pong
(win@Dan)2> debugger:start().
{ok,<0.98.0>}
(win@Dan)3> 

Interpret modules from the gui or use ` ini:ni(FIle)` from the command line.
set up break point ib(mnesia,start,0)  or from the gui.

On target
(unix@Dan)1> mnesia:start().

And breakpoint breaks for me.

The debugger window that pops up needs to be resized for me which is irritating, but otherwise it works.

**Comment by dgud** [comment]
The interpreter must be able to change the module to the interpreted one,
 i.e. the code must not be running already or the code must do external calls to it self so the code can be swapped to the interpreted code. Otherwise it will be running non-interpreted code and it can not be debugged.

**Comment by menih** [comment]
Oh... that would clearly be the main difference between a trivial case and
my case where the app is already running and modules are all loaded. I'd
think this would be a very important thing to know and document...

In my specific use case, I cannot control the bootstrapping of our
application. So I need to be able to attach a debugger at any point on a
running process.

1) Is there a way to know if there was a failure or inability to make the
swap?
2)  Is there an erlang VM startup option that can load all modules as
interpretable?
3) Are there future plans to overcome this? Are there any workarounds?
4) Strongly suggest we add this very important limitation to docs.

**Comment by dgud** [comment]
> 1) Is there a way to know if there was a failure or inability to make the swap?

No, This loads a second version of the code as done in erlang code-loading, new extranal calls
to the module will use the new code.

> 2)  Is there an erlang VM startup option that can load all modules as
interpretable?

Not that I know of

> 3) Are there future plans to overcome this? Are there any workarounds?

No this is how the interpreter/debugger works,  as we have said there are 
other ways to debug a live system, tracing is what most people are using.

There are to my knowledge not any plans to write a "real" debugger.

> 4) Strongly suggest we add this very important limitation to docs.

Please do a PR.
