### ISSUE TITLE
Building erlang with wx fail to start debugger

### ISSUE THREAD

**Issue by menih** [erlang/otp#4907]
**Describe the bug**
Followed build instructions to build including wx. OS - macos bigsur.

**To Reproduce**
Building Erlang/OTP 22.3.4.15 (22.3.4.15), please wait...
APPLICATIONS DISABLED (See: /Users/menihillel/.kerl/builds/22.3.4.15/otp_build_22.3.4.15.log)
 * odbc           : ODBC library - link check failed

DOCUMENTATION INFORMATION (See: /Users/menihillel/.kerl/builds/22.3.4.15/otp_build_22.3.4.15.log)
 * documentation  :
 *                  fop is missing.
 *                  Using fakefop to generate placeholder PDF files.

Erlang/OTP 22.3.4.15 (22.3.4.15) has been successfully built

menihillel@Menis-MacBook-Pro:~/kerl$ kerl install 22.3.4.15 ~/kerl/22.3.4.15
Installing Erlang/OTP 22.3.4.15 (22.3.4.15) in /Users/menihillel/kerl/22.3.4.15...
You can activate this installation running the following command:
. /Users/menihillel/kerl/22.3.4.15/activate
Later on, you can leave the installation typing:
kerl_deactivate
menihillel@Menis-MacBook-Pro:~/kerl$ . 22.3.4.15/activate
menihillel@Menis-MacBook-Pro:~/kerl$ erl -version
Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.7.2.7

menihillel@Menis-MacBook-Pro:~/kerl$ erl -s debugger start
Erlang/OTP 22 [erts-10.7.2.7] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Eshell V10.7.2.7  (abort with ^G)
=ERROR REPORT==== 27-May-2021::23:09:49.130522 ===
WX Failed loading "wxe_driver"@"/Users/menihillel/kerl/22.3.4.15/lib/wx-1.9/priv"

1> =CRASH REPORT==== 27-May-2021::23:09:49.150482 ===
  crasher:
    initial call: wxe_master:init/1
    pid: <0.85.0>
    registered_name: []
    exception error: {load_driver,"dlopen(/Users/menihillel/kerl/22.3.4.15/lib/wx-1.9/priv/wxe_driver.so, 2): Symbol not found: __ZN10wxBoxSizer11RecalcSizesEv\n  Referenced from: /Users/menihillel/kerl/22.3.4.15/lib/wx-1.9/priv/wxe_driver.so\n  Expected in: flat namespace\n in /Users/menihillel/kerl/22.3.4.15/lib/wx-1.9/priv/wxe_driver.so"}
      in function  wxe_master:init/1 (wxe_master.erl, line 132)
      in call from gen_server:init_it/2 (gen_server.erl, line 374)
      in call from gen_server:init_it/6 (gen_server.erl, line 342)
    ancestors: [<0.84.0>,dbg_wx_mon]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 2959
  neighbours:

=CRASH REPORT==== 27-May-2021::23:09:49.150685 ===
  crasher:
    initial call: wxe_server:init/1
    pid: <0.84.0>
    registered_name: []
    exception error: {load_driver,"dlopen(/Users/menihillel/kerl/22.3.4.15/lib/wx-1.9/priv/wxe_driver.so, 2): Symbol not found: __ZN10wxBoxSizer11RecalcSizesEv\n  Referenced from: /Users/menihillel/kerl/22.3.4.15/lib/wx-1.9/priv/wxe_driver.so\n  Expected in: flat namespace\n in /Users/menihillel/kerl/22.3.4.15/lib/wx-1.9/priv/wxe_driver.so"}
      in function  wxe_master:init/1 (wxe_master.erl, line 132)
      in call from gen_server:init_it/2 (gen_server.erl, line 374)
      in call from gen_server:init_it/6 (gen_server.erl, line 342)
    ancestors: [dbg_wx_mon]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 248
  neighbours:

**Comment by dgud** [comment]
Something is broken in your build, it is really hard for me to help with that.

Did you use the same compiler when compiling wxWidgets and erlang?

Anyway you will need wxWidgets-3.1.5 and latest OTP-23.3 or OTP-24  for wx apps to work ok on BigSur.

**Comment by menih** [comment]
Yes. Same tool chain.

I've also tried it with the latest from wxWidgets, which is 3.1.6 and it
still fails with a similar error - some missing exported symbols.

**Comment by menih** [comment]
Any update? I also tried the following https://dev.to/hugomatinho/setting-up-elixir-for-mac-with-erlang-observer-working-17pg which interestingly produced the same results.

**Comment by dgud** [comment]
No, and I don't work on Sundays :-)
But can't really help you here, something is broken in your setup or your procedure, you will have to figure that out.

It should be as simple as:
   cd wxWidgets &&  ./configure WITH_DOCUMENTED_OPTIONS && make && sudo make install

   Ensure that you have the correct (new) installed wxWidgets in your path with for example:  wx-config --include
   
   cd otp && ./otp_build setup -a

**Comment by menih** [comment]
~/wxWidgets$  ./configure WITH_DOCUMENTED_OPTIONS && make && sudo make
install
configure: WARNING: you should use --build, --host, --target
checking build system type... Invalid configuration
`WITH_DOCUMENTED_OPTIONS': machine `WITH_DOCUMENTED_OPTIONS-unknown' not
recognized
configure: error: /bin/sh ./config.sub WITH_DOCUMENTED_OPTIONS failed

Can you please provide the wxWidget branch you are using and version of the
toolchains that participate in building?

The error I am getting seems to suggest a missing function that is being
used by Erlang, but does not exist in wxWidgets. Either I am using the
wrong erlang branch, which I've already confirmed is the latest, or I am
using the wrong wxWidget version.

Are you sure there aren't any other config/define/env needs to be set?

**Comment by menih** [comment]
I think I figured out the issue and indeed it is a build issue with wxWidget.
