### ISSUE TITLE
DualMapping allocation adds 100 ms to JIT startup time on Mac OS

### ISSUE THREAD

**Issue by richcarl** [erlang/otp#4911]
https://github.com/erlang/otp/blob/f07e4dc692b367e68435a05b021da72ef434ae24/erts/emulator/beam/jit/beam_jit_main.cpp#L172

Investigating why the startup times increased by over 100ms between OTP 23 and OTP 24 on an Intel i5 Mac OS Catalina, it was found that the call to create_allocator(&dual_params) is responsible for most of the added time.

**Comment by garazdawi** [comment]
I've tracked it down to this syscall: https://github.com/erlang/otp/blob/f07e4dc/erts/emulator/asmjit/core/virtmem.cpp#L648

What to do about it is another question...

**Comment by jhogberg** [comment]
Fixed in #7018
