### ISSUE TITLE
Start Erlang VM with "debugger" enabled

### ISSUE THREAD

**Issue by menih** [erlang/otp#4924]
This feature request is based on reported issue https://github.com/erlang/otp/issues/4904#issuecomment-852117643.

Enhancement request:
- Start Erlang VM in debugger mode where each module is loaded as interpretable.
- Need a way to know the status of a module interpretability as well as the error reason if failed.
- A console mode debugger without needing GUI.

I'd rather module interpretability will not fail so I can start debugging at any point. It is not clear why it fails, nor it is documented anywhere that it may fail, and why. If I knew why it may fail, I may had a way to correct it.

**Comment by KennethL** [comment]
It is not in our current plans to add the suggested functionality. If there is something wrong with the current implementation as it is documented or if the documentation is wrong please report such issues. 
A module is interpretable if it contains debuginfo (the abstract code chunk) in the .beam file
