### ISSUE TITLE
[Dialyzer] Different diagnostic when function is inlined.

### ISSUE THREAD

**Issue by slaykachu** [erlang/otp#4935]
**To Reproduce**
I'm currently trying to reproduce with a minimal/self-contained example.
In the meantime, here is how my code looks like:
```erlang
f() ->
  Param = g(),
  Result = h(Param),
  case Result of
       {_, _, {ok, _, _}} ->
           erlang:display(ok);
        X ->
           erlang:display(X)
    end,
    Result.

h(X) ->
  Result = DoStuff(X),  % Actually several lines of code
   case Result of       % Exact same sanity check than in the caller f().
       {_, _, {ok, _, _}} ->
           erlang:display(ok);
        X ->
           erlang:display(X)
    end,
    Result. 
```

**Describe the bug**
An error is reported in `f()`:
```shell
Line 4 Column 8: The pattern {_, _, {'ok', _, _}} can never match the type 
                               {_, _, {'error', {atom() | binary() | [atom() | [any()] | char()],non_neg_integer() | {non_neg_integer(),pos_integer()},atom(),_}}}
```

Fair, there might be a real problem. The error message itself is a bit misleading, because unit testing shows that the type actually include the `ok` alternative. But that's not my issue here!

My first surprise is that the same error isn't reported in h(). Sure, it depends on context (passed X parameter). But in my case h() isn't exported, and is only called once, by f(). So I expected the analysis in h() to use the exact restricted context that triggers the error in f().

Now, the behaviour that is really baffling me: **When I inline h() in f(), the error disappears**. 

**Expected behavior**
* Same diagnostic for semantically equivalent constructs.

**Affected versions**
Erlang/OTP 24

**Additional context**
I know that when Dialyzer complains, it oftens pinpoint a real problem in the code. 
The bug might be between the chair and the keyboard, in which case I will look stupid. That's ok, I like to look stupid, part of my 'challenging the comfort zone' exercices. Also, the insights from this issue might help me and others anyway.
The only result I got by searching the internet was "Diagnosis, Treatment, and Prevention of Hemodialysis".

**Comment by aronisstav** [comment]
Hi @slaykachu ! It is very hard to debug this without a broken example, but as a start are the "tail parts" of `h()`'s and `f()`'s code truthful, or are there some other relevant things there? I am wondering whether `g()` or `f()` do more things with `Result` after the sanity check that make Dialyzer further constrain its type.

**Comment by kostis** [comment]
> Now, the behaviour that is really baffling me: When I inline h() in f(), the error disappears.

Just out of curiosity: do you have any idea what function inlining does?

In particular, do you enable it just for the fun of playing with options, or to allow the compiler to do something (hopefully clever) with your code?

**Comment by bjorng** [comment]
I am closing this because you have not provided us with a code example that can be compiled.
