### ISSUE TITLE
Update to asmjit/asmjit@78de7d9 to fix the Android cross-compilation

### ISSUE THREAD

**Issue by JeromeDeBretagne** [erlang/otp#4950]
**Describe the bug**
Cross compiling OTP 24.x for Android (x86_64 / ARM / ARM64) fails with:
```
 CXX	obj/aarch64-unknown-linux-android/opt/jit/asmjit/core/virtmem.o
asmjit/core/virtmem.cpp:372:17: error: no member named 'shm_open' in the global namespace
        _fd = ::shm_open(_tmpName.data(), O_RDWR | O_CREAT | O_EXCL, S_IRUSR | S_IWUSR);
              ~~^
asmjit/core/virtmem.cpp:393:9: error: no member named 'shm_unlink' in the global namespace
      ::shm_unlink(_tmpName.data());
      ~~^
 CXX	obj/aarch64-unknown-linux-android/opt/jit/asmjit/core/zonehash.o
2 errors generated.
```

**To Reproduce**
$ /otp_build configure --xcomp-conf=xcomp/erl-xcomp-x86_64-android.conf  --with-ssl=/path/to/src/openssl-android-x86_64 --disable-dynamic-ssl-lib

$ make -j4

**Expected behavior**
The build should pass.

**Affected versions**
OTP 24.0 / 24.0.1 / 24.0.2 / 24.0.3 / 24.0.4 / 24.0.5 / 24.1.x / 24.2

**Additional context**
This was discussed in https://github.com/erlang/otp/pull/4833 with @jhogberg :

> Thanks for your report! This has been fixed upstream in asmjit/asmjit@8ee4c76, and I'd prefer to update to that version rather than disabling the JIT and risk forgetting about it later on. We'll try to do that before 24.1 at the latest.

After further testing and some more discussions in asmjit/asmjit@8ee4c76, a second fix was applied in asmjit/asmjit@78de7d9 this time fully fixing the compilation. 

I'm creating this issue so that it doesn't get lost, as this was captured in discussions and in a now-closed PR. Thanks

(EDIT: Update the affected versions up to OTP 24.2)

**Comment by JeromeDeBretagne** [comment]
I've seen that a tentative [OTP-24.1 milestone](https://github.com/erlang/otp/milestone/153) is planned for September 22, 2021. @bjorng, @jhogberg, could this issue be added to this milestone too? Thanks

**Comment by JeromeDeBretagne** [comment]
It seems that AsmJit is not updated from upstream so regularly (which is fine) so I've proposed these 2 dedicated PRs to fix cross compiling for Android : #5569 for the maint branch and #5570 for master branch.

@jhogberg I let you see if this is OK or if this is going to make your life more difficult when updating AsmJit later on.

**Comment by jhogberg** [comment]
Thanks, but we're waiting for `asmjit` to merge the `aarch64` branch to reduce merge conflicts when merging patches forward from `maint-24` to `maint` and `master` in the future (there's massive changes to `x64` as well). It's going to happen pretty soon from the sound of it.

If I understood things correctly, it's also going to move on to having versioned releases with a stable API soon after that, so we'll be able to keep it as a separate dependency rather than putting it in our source tree.

**Comment by JeromeDeBretagne** [comment]
No worries and thanks for the update about the `AsmJit` plans. The 2 closed PR are available in the meantime if anyone else faces the same build issue.

**Comment by JeromeDeBretagne** [comment]
The merges from earlier today are looking good to fix this issue, for both the maint and master branches, thanks @jhogberg !
