### ISSUE TITLE
Add the ability to change states to leex.

### ISSUE THREAD

**Issue by skynet1** [erlang/otp#4951]
**Is your feature request related to a problem? Please describe.**
I'm trying to write a javascript parser using leex and yecc, and it would be much easier to do if leex supported changing states like lex does and also allowed me to add my own variable to keep track of how many parantheses there are in a regular expression literal.
**Describe the solution you'd like**
Parsing regular expression literals would be easier if leex allowed me to change state so as to use a different set of regular expressions with a different set of rules when one of the rules decides to change states. Also the ability to add my own variables to the function that leex generates so that I can count how many parantheses there are in the regex would make it easier to turn the entire regex into one token.

**Describe alternatives you've considered**
One possible way to solve this would be to try and pass the characters in the regex to yecc and have yecc put together the regex, but that would be much more difficult to figure out. Another possibility is to write a custom lexer, or find a parser library but writing a custom parser might take more time, and many of the parsing libraries for javascript either don't work, or they don't handle ```document.write()``` the way I'd like.

**Additional context**
Regex literals in javascript start with a forward slash and end with a forward slash, and a forward slash can exist unescaped in a character class or in paranthesis. Since regexes make it possible to have nested paranthesis that are any number of layers deep, it's impossible to match a javascript regex literal with an ordinary regex.

The only practical answer I can think of is to have it switch states when it comes across a token that might come before a regex literal, and then have it build up the regex one character at a time storing the characters in a variable, counting the number of begin and end paranthesis so it knows whether or not a forward slash character is the end of the regex or part of it, and then return the regex as one token.

**Comment by bjorng** [comment]
We think that Leex should remain simple and we don't plan to extend it. When Leex is not sufficient, we think that the best solution is to handwrite a tokenizer in Erlang.
