### ISSUE TITLE
TLS 1.3: Server sends incorrect CertificateVerify for ECDSA certificates

### ISSUE THREAD

**Issue by anhuang** [erlang/otp#4958]
**Describe the bug**
When the Erlang/OTP server authenticates with an ECDSA certificate, it will populate its CertificateVerify message with the first EDCSA signature algorithm in the intersection of client and server supported signature algorithms, without considering the curve of the certificate's public key algorithm.

This is strongly suspected to be due to how [select_sign_algo](https://github.com/erlang/otp/blob/master/lib/ssl/src/tls_handshake_1_3.erl#L2329) is defined. When `PublicKeyAlgo` is `ecdsa`, It returns the first algorithm in `PeerSignAlgs` whose scheme is `ecdsa`, since `validate_key_compatbility` doesn't perform any validation for non-RSA algorithms. 

Based on the code, this issue likely extends to EDDSA certificates as well, though I haven't tested this. 

**To Reproduce**
*Setup*
Run an Erlang/OTP server with an ECDSA certificate. I discovered this issue on a server with an ECDSA certificate with an `secp256r1` curve.

*Scenario 1*
Client sends ClientHello with the following in the ~~signature_algorithms_cert/~~ signature_algorithms extension: `ecdsa_secp521r1_sha512, ecdsa_secp384r1_sha384, ecdsa_secp256r1_sha256`.
Server sends CertificateVerify with `ecdsa_secp521r1_sha512` as the algorithm. 

*Scenario 2*
Client sends ClientHello with the following in the ~~signature_algorithms_cert/~~ signature_algorithms extension: `ecdsa_secp384r1_sha384, ecdsa_secp256r1_sha256, ecdsa_secp521r1_sha512`.
Server sends CertificateVerify with `ecdsa_secp384r1_sha384` as the algorithm. 

*Scenario 3*
Client sends ClientHello with the following in the ~~signature_algorithms_cert/~~ signature_algorithms extension: `ecdsa_secp256r1_sha256, ecdsa_secp521r1_sha512, ecdsa_secp384r1_sha384`.
Server sends CertificateVerify with `ecdsa_secp256r1_sha256` as the algorithm. 

**Expected behavior**
~~Server should send CertificateVerify with the `ecdsa_secp256r1_sha256` algorithm in all three scenarios, corresponding to the certificate.~~
Server should send CertificateVerify with an `algorithm` value that corresponds to the actual signature algorithm used for the `signature` in CertificateVerify. In the scenarios above, because the server signs with the `ecdsa_secp256r1_sha256` algorithm, `algorithm` should be `ecdsa_secp256r1_sha256`. 

**Affected versions**
This issue was discovered and reproduced on 23.1.1, but the code that would cause this is present in the current master branch. 

Edit: Remove mistaken inclusion of `signature_algorithms_cert` extension. Clarify expected behavior.

**Comment by anhuang** [comment]
I believe I was somewhat unclear and inaccurate in my report. The bug is solely with regards to the mismatch between the `algorithm` value in CertificateVerify and the actual signature algorithm used for the `signature` in CertificateVerify. The signature algorithm that the certificate is signed with is not within the scope of this bug. My mistaken inclusion of `signature_algorithms_cert` likely fueled this confusion, and I'll edit the original report appropriately. This bug was discovered and reproduced through reordering the signature algorithms in the `signature_algorithms` extension.

**Comment by peterdmv** [comment]
Thank you for the clarification! I have reproduced it and I can confirm that this is a bug.

**Comment by IngelaAndin** [comment]
Will be part of upcoming patches for OTP-23 and OTP-24 that are currently being prepared
