### ISSUE TITLE
ssl psk ciphers options break between ssl 9.2 and 10.1

### ISSUE THREAD

**Issue by danj3** [erlang/otp#4978]
# Use of tls1.2 psk cipher does not work (or work the same) in ssl 10.1

Use of unchanged psk options for ssl:connect are not respected in upgrade from 9.2 to 10.1 and unable to find a hint on how the options need to change or if there is a bug.

This code reproduces against a public https server, wireshark shows cipher suites offered in Client Hello.

```
%% connect to any ssl server
%% Using:
%% 12> erlang:system_info(otp_release).
%% "22"
%% 13> erlang:system_info(version).
%% "10.7.2.12"
%% 14> ssl:versions().
%% [{ssl_app,"9.2"},
%%  {supported,['tlsv1.2']},
%%  {supported_dtls,['dtlsv1.2']},
%%  {available,['tlsv1.3','tlsv1.2','tlsv1.1',tlsv1,sslv3]},
%%  {available_dtls,['dtlsv1.2',dtlsv1]}]
%%
%% only the PSK is correctly sent
%% This will fail against a regular https server since it's only offering
%% a PSK cipher, but that is success in this case

%% Using:
%% 4> erlang:system_info(otp_release).
%% "23"
%% 5> erlang:system_info(version).
%% "11.1.3"
%% 6> ssl:versions().
%% [{ssl_app,"10.1"},
%%  {supported,['tlsv1.3','tlsv1.2']},
%%  {supported_dtls,['dtlsv1.2']},
%%  {available,['tlsv1.3','tlsv1.2','tlsv1.1',tlsv1]},
%%  {available_dtls,['dtlsv1.2',dtlsv1]},
%%  {implemented,['tlsv1.3','tlsv1.2','tlsv1.1',tlsv1]},
%%  {implemented_dtls,['dtlsv1.2',dtlsv1]}]
%%
%% no PSK is sent and a regular SSL suite is
%% This call will succeed against a regular https server, for instance
%% but that success is a PSK failure.

%% Use wireshark to see the Client Hello packet, but a correct one
%% Has this:
%%
%% Cipher Suites (2 suites)
%% Cipher Suite: TLS_EMPTY_RENEGOTIATION_INFO_SCSV (0x00ff)
%% Cipher Suite: TLS_PSK_WITH_AES_128_CBC_SHA (0x008c)

%% An incorrect will have:

%% Cipher Suites (45 suites)
%% Cipher Suite: TLS_EMPTY_RENEGOTIATION_INFO_SCSV (0x00ff)
%% Cipher Suite: TLS_AES_256_GCM_SHA384 (0x1302)
%% .. etc
%% But no PSK

-module(wrong_suites).
-export([connect/2]).

psk_lookup( psk, _, _Any ) ->
    [ 1,2,3 ].

connect(Host,Port) ->
    ssl:start(),
    SslOptions = [
                  { verify, verify_none },
                  { psk_identity, "TESTID" },
                  { user_lookup_fun, { fun psk_lookup/3, nil } },
                  { ciphers, [
                              #{
                                cipher => aes_128_cbc,
                                key_exchange => psk,
                                mac => sha,
                                prf => default_prf
                               }
                             ]
                  }
                 ],
    { ok, Tcp } = gen_tcp:connect(Host,Port, [ { active, false } ]),
    { ok, _Ssl } = ssl:connect( Tcp, SslOptions ),
    gen_tcp:close( Tcp ).
```

## An expected result looks like:

erl> wrong_suites:connect('www.erlang.org',443).
=NOTICE REPORT==== 17-Jun-2021::17:18:44.862089 ===
TLS client: In state hello received SERVER ALERT: Fatal - Handshake Failure

** exception error: no match of right hand side value {error,
                                                       {tls_alert,
                                                        {handshake_failure,
                                                         "TLS client: In state hello received SERVER ALERT: Fatal - Handshake Failure\n"}}}
     in function  wrong_suites:connect/2 (wrong_suites.erl, line 24)

## An incorrect result looks like:

8> wrong_suites:connect('www.erlang.org',443).
ok

**Comment by IngelaAndin** [comment]
Your configuration above is not really a working one (in the second scenario) as you have not included any TLS-1.3 cipher suites but use the default versions that include TLS-1.3.  TLS-1.3 does not share any cipher suites with previous versions. If you include a TLS-1.3 cipher suite and try to connect towards a TLS-1.2 server with only the PSK cipher suite for TLS-1.2 you should get the same behavior for that cipher suite as before.  

It seems like in the second scenario the cipher suite configuration is being ignored and the default configuration is used instead which feels odd. I will look into that. Also, have you tried the latest version of the ssl application to rule out that is something that might have been fixed?

**Comment by danj3** [comment]
I used the latest version available as a docker container. I just freshly pulled to make sure and got

{ssl_app,"10.4.1"},

I also added protocol_versions
```
{ protocol_versions, 'tlsv1.2' }
```

wireshark shows:

Version: TLS 1.2 (0x0303)

No change in the Client Hello otherwise. Is there some other configuration part that's needed?

**Comment by IngelaAndin** [comment]
The option is `{versions, ['tlsv1.2']}`

**Comment by IngelaAndin** [comment]
However I believe there is a bug in handling the cipher suites when supporting both TLS-1.3 and TLS-1.2 with a list of ciphers suites including ciphers from both and that contains TLS-1.2 PSK cipher suites .  And I believe #4983  will fix it

**Comment by danj3** [comment]
There seems to be a larger problem with option handling. After changing the options to look like this:
```
    SslOptions = [
                  { verify, verify_none },
                  { psk_identity, "TESTID" },
                  { versions, [ 'tlsv1.2' ] },
                  { user_lookup_fun, { fun psk_lookup/3, nil } },
                  { ciphers, [
                              #{
                                cipher => aes_128_cbc,
                                key_exchange => psk,
                                mac => sha,
                                prf => default_prf
                               }
                             ]
                  }
                 ],
```
I run the same test using a docker container based on alpine, which does not include and ca-certificates by default and the error produced was:
```
=WARNING REPORT==== 18-Jun-2021::19:32:38.925569 ===
Description: "Authenticity is not established by certificate path validation"
     Reason: "Option {verify, verify_peer} and cacertfile/cacerts is missing"
```
But {verify, verify_none} is set. Using versions [ 'tlsv1.2' ] did not alter the outcome.

**Comment by IngelaAndin** [comment]
The warning will not make it fail. The warning is primarily  for not making the user have  a false sense of security especially when using an empty options list that will default to verify_none as there are then no know certs to use for validation.  When you tried it did you use my patch or not? My patch ought to have made sure that the psk suite would be part of the client hello, if it can be negotiated or not is a different question.

**Comment by IngelaAndin** [comment]
@danj3 did you try my patch or not? Could you perhaps make a test case for your scenario so that I could reproduce your issue?

**Comment by IngelaAndin** [comment]
I merged my PR, which I think is an improvement related to the reported issue. If you still experience some problem after this feel free to open a new issue, preferably with a reliable way to reproduce the problem.
