### ISSUE TITLE
OTP 23  beam can‘t auto gc on a CentOS 7 server

### ISSUE THREAD

**Issue by TangYunTao** [erlang/otp#4984]
**Describe the bug**
OTP 23  beam can‘t auto gc on a CentOS 7 server，and call 'erlang:garbage_collect'  effectively frees the process's memory;
and  It works on mac

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
after the client establishes a connection to the server, the process takes 40K bytes and does not release it

**Affected versions**
otp 23

**Additional context**
[gc.md](https://github.com/erlang/otp/files/6677305/gc.md)

**Comment by rickard-green** [comment]
This is not a bug. A process is not garbage collected unless it reach certain limits, for example it needs to allocate heap data and there is no free heap available. If a process stops executing, it does not matter how long time passes, it wont automatically garbage collect by itself unless it reaches one of these limits.

**Comment by TangYunTao** [comment]
thanks !

**Comment by TangYunTao** [comment]
Thanks

**Comment by rickard-green** [comment]
> Thanks
> but why does not the automatic garbage collec when `total_heap_size` is greater than `min_bin_vheap_size` and `fullsweep_after = 0 `?
> 

These values are not related to each other like that.

* `total_heap_size` is the total amount of heap memory allocated, including free heap memory.
* `min_bin_vheap_size` is minimum virtual heap size for off heap binaries.
* `fullsweep_after = 0 ` is number of generational garbage collections allowed before a fullsweep garbage collection is forced.

> because Is `heap_size `less than `total_heap_size` ?

These values are also not related to each other like that.

`heap_size` is the size of the continues memory block used for the youngest generation heap or only generation heap in case of `fullsweep_after = 0`. It is very frequently less than `total_heap_size` also when using `fullsweep_after = 0`.
