### ISSUE TITLE
ssl:close fails with nif sockets

### ISSUE THREAD

**Issue by petrkozorezov** [erlang/otp#4993]
**Describe the bug**

`ssl:close` fails with `function_clause` error when using nif sockets api

**To reproduce**

1. Start erlang with `erl -kernel inet_backend socket`.
2. Type

```
application:ensure_all_started(ssl).
{ok,S}=ssl:connect("erlang.com", 443, [], 5000).
ssl:close(S).
```

**Full log**

https://gist.github.com/petrkozorezov/d2376e15fac0687bf0ee5e22be3ae809

**Comment by IngelaAndin** [comment]
#4996 merged for OTP-24.1
