### ISSUE TITLE
A process is not dead when it has executed it's last instruction...

### ISSUE THREAD

**Issue by gnaeser** [erlang/otp#5001]
**Describe the bug**
The observable life of a process that send a message as is last instruction depends on the size of the message

**To Reproduce**
Compile the following function
```
test(N) ->
    S = spawn(
          fun() ->
                  receive
                      {get, From} ->
                          From ! {data, lists:seq(1, N)}
                  end
          end),
    S ! {get, self()},
    receive
        {data, D} -> D
    end,
    is_process_alive(S).
```
The function will (on my system) return `false` for values of `N` up to and including 80961, and 'true' for larger values.
 
**Expected behavior**
I would expect the return value of the function above to be the same regardless of 'N'.

I would personally prefer a behaviour like the one observed for small messages, where the process is _dead_ once it has executed its final instruction.

**Affected versions**
OTP24, OTP23, OTP22 (at least)

**Additional context**
If the spawned process replies with `{data, length(lists:seq(1, N))}` the process is always observed as dead (resulting in `false`).

**Comment by avtobiff** [comment]
This behaviour is observed on my machine on master HEAD
(97d6c162922adbfc4cc9ced20976b80ad70020fe) as well.

The above test function returns `false` for `N` up to and
including 101597, and `true` for larger values.

**Comment by sverker** [comment]
There is no defined expected behavior here. 

A process can be preempted at any time both by the schedulers of the Erlang VM and by the OS.

Use a link or monitor to get a message when a process has terminated.
