### ISSUE TITLE
Mac brew install erlang failed

### ISSUE THREAD

**Issue by apprentice1988** [erlang/otp#5003]
**Describe the bug**
![4EF62F6F-80C2-4189-BF14-66F68D9A2E6F](https://user-images.githubusercontent.com/3086940/123349765-2fdbbe00-d58c-11eb-927c-4124704de237.png)

**To Reproduce**
I use M1 Mac Mini to install erlang

**Comment by josevalim** [comment]
You should most likely report it to the Homebrew team. I _think_ the formulas are maintained by the Homebrew community. :)
