### ISSUE TITLE
error in socket open with provided fd

### ISSUE THREAD

**Issue by leasg** [erlang/otp#5004]
**Describe the bug**
gen_udp fail open from fd without passing address to options

**To Reproduce**
4> gen_udp:open(0, [{fd, 20}]).      
{20,undefined,0,[{active,true},{recbuf,8192}],udp,inet,dgram,inet_udp}
DoNotBind: true
Error {error,einval}
{error,einval}

5> gen_udp:open(0, [{fd, 20}, {ifaddr, {0,0,0,0}}]).
{20,{0,0,0,0},0,[{active,true},{recbuf,8192}],udp,inet,dgram,inet_udp}
DoNotBind: false
{ok,#Port<0.9>}

**Expected behavior**
gen_udp:open(0, [{fd, 20}]). 
should return {ok, #Port<0.9>} like it was before 24.x

**Affected versions**
otp 24.0.2

**Additional context**

**Comment by RaimoNiskanen** [comment]
I tried to get that change in 24.0 because it had to affect somebody out there ;-) but failed.
Sorry about that!

**Comment by RaimoNiskanen** [comment]
So, according to me this is not a bug.
