### ISSUE TITLE
inet module: send_timeout_close option does not close socket on peer side.

### ISSUE THREAD

**Issue by ygb8745** [erlang/otp#5006]
**Describe the bug**
When set send_timeout and send_timeout_close  option to a socket, and the packet send timeout due to buffer full on peer side, OTP close socket on local side quietly without info peer side.

**To Reproduce**
On server side:
```
{ok, ListenSocket} = gen_tcp:listen(10086, [{active, false},binary,{buffer, 32}, {recbuf, 64},{sndbuf, 256}]),
{ok, DataSocket} = gen_tcp:accept(ListenSocket),
io:format("~p~n",[{'ListenSocket',ListenSocket,'DataSocket', DataSocket}]).
```
On client side:
```
{ok, Socket} = gen_tcp:connect("127.0.0.88", 10086,[binary,{buffer, 512}, {recbuf, 1024},{sndbuf, 2048}
    ,{send_timeout, 30*1000},{send_timeout_close, true} ]),
SendFun = fun Fun(Count)->
    Res = gen_tcp:send(Socket, "x"),
    io:format("~p~n", [{Count, Res}]),
    case Res of
        ok ->
            Fun(Count + 1);
        _ ->
            do_nothing
    end
end,
SendFun (1).
```

**Expected behavior**
Client send until packet send timeout.
Client close socket(Socket go to FIN_WAIT1; but no FIN packet send out.)
After a while, the client clean up socket on local side, but the socket on server side is still in ESTABLISHED state.

**Affected versions**
All.

**Additional context**
The client should send reset packet to server when send_timeout to info the server to close the socket.

**Comment by RaimoNiskanen** [comment]
`gen_tcp` does what it is supposed to do.

When the send times out (option `send_timeout`, corresponding to, in C, to use a time-out value to poll()/select()), `gen_tcp` closes (option `send_timeout_close`) the socket by calling close(2) on the socket descriptor.  Then the system cleans up as it sees fit.  Erlang/OTP has no part in what happens on the wire nor in which states the socket may be according to the system network stack.

The normal behaviour when closing a socket for most system network stacks is to try to send the lingering data for quite a while.  This is what you see.  `gen_tcp` has no part in this.

Fortunately, most (all I know of) system network stacks support the socket option `{linger,{true,0}}` which tells the system how to deal with lingering data when a socket is closed.  `{true,0}` means wait for zero time and waste the lingering data.  On all systems I have heard of it is also implemented so the closed socket sends (TCP) RST to the remote end.

I tried your example, adding `{linger,{true,0}}` to the client options, and then the socket disappears seemingly immediately after client time-out from the output of "netstat -4 | grep 10086".

This sounds like what you request.  It is a socket option as old as sockets, fundamental to network programming, and a behaviour of the socket itself.

`gen_tcp` is just a layer on top of the system network stack, and what you report is a well known property of TCP sockets implemented by the system network stack.
(Except for possibly the `send_timeout` and `send_timeout_close` options that does what I described).
