### ISSUE TITLE
Compiler emits invalid code when using a guard with not (X =:= true)

### ISSUE THREAD

**Issue by josevalim** [erlang/otp#5007]
**To Reproduce**

Take this code:

```erl
-module(foo).
-export([bar/1]).

bar(X) when not (X =:= true) -> ok;
bar(_) -> error.
```

Then the following session:

```
$ erl
Erlang/OTP 24 [erts-12.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Eshell V12.0  (abort with ^G)
1> foo:bar(true).
error
2> foo:bar(foo).
error
```

The last call should have returned `ok` instead.

**Expected behavior**

```
1> foo:bar(true).
error
2> foo:bar(foo).
ok
```

**Affected versions**

I have verified it on Erlang/OTP 24, compiler-8.0. I will be glad to check other versions if necessary.

**Comment by ranjanified** [comment]
This is whoa....

I tried with an Anonymous function, but it behaved how it should have...

Eshell V11.1.7  (abort with ^G)
1> Bar = fun (X) when not (X =:= true) -> ok; (_) -> error end.
#Fun<erl_eval.44.128886729>
2> Bar(true).
error
3> Bar(true1).
ok
4>

**Comment by ranjanified** [comment]
Wait... May be, my source isn't latest master...

it's at...
commit cd074622c9ed4c93d4f12ded40f2a36f91a26bc0 (HEAD -> master, upstream/master)

**Comment by mikpe** [comment]
> This is whoa....
> 
> I tried with an Anonymous function, but it behaved how it should have...
> 
> Eshell V11.1.7 (abort with ^G)
> 1> Bar = fun (X) when not (X =:= true) -> ok; (_) -> error end.
> #Fun<erl_eval.44.128886729>
> 2> Bar(true).
> error
> 3> Bar(true1).
> ok
> 4>

That's in the shell, which is a different, interpreted, implementation.

I see the error (with the compiler) at least as far back as OTP-20. (I don't have older versions built ATM.)

**Comment by ranjanified** [comment]
> > This is whoa....
> > I tried with an Anonymous function, but it behaved how it should have...
> > Eshell V11.1.7 (abort with ^G)
> > 1> Bar = fun (X) when not (X =:= true) -> ok; (_) -> error end.
> > #Fun<erl_eval.44.128886729>
> > 2> Bar(true).
> > error
> > 3> Bar(true1).
> > ok
> > 4>
> 
> That's in the shell, which is a different, interpreted, implementation.
> 
> I see the error (with the compiler) at least as far back as OTP-20. (I don't have older versions built ATM.)

May be I would have tried the shell after looking at @josevalim's snapshot of the session(in the description. :smile:) 

Oh Yes, indeed. I tried compiling, and yes it is **not correct**. Since OTP-20, that is something to ponder....

```
Erlang/OTP 24 [DEVELOPMENT] [erts-11.1.7] [source-f60c6c8c48] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]

Eshell V11.1.7  (abort with ^G)
1> foo:bar(true).
foo:bar(true).
error
2> foo:bar(true1).
foo:bar(true1).
error
3> 
```

**Comment by josevalim** [comment]
To be fair, this is a very unlikely code to write. One would either pattern match or use `X =/= true`. The only reason it showed up was because it was generated code from an Elixir macro.

**Comment by ityonemo** [comment]
and even that was a corner case in an autogenerated test suite from: 

https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/master/tests/draft2020-12/enum.json#L158-L176 

Elixir JsonSchema macros have uncovered errors in erlang compiler before!

**Comment by bjorng** [comment]
We don't plan to release emergency patches for older releases, because (theoretically) the change in the code emitted from `v3_core` could expose latent bugs in one of the optimization passes.
