### ISSUE TITLE
Error downgrading TLS/DTLS just after connection

### ISSUE THREAD

**Issue by garthk** [erlang/otp#5009]
Using `ssl:close/2` to hand over to a new controller process just after `ssl:connect/3` fails with `{error, closed}`.

**To Reproduce**
With Erlang/OTP 24.0.2:

```erlang
#!/usr/bin/env escript
%% -*- erlang -*-
% @format({formatter, default_formatter}, #{paper => 98}).

main([]) ->
    application:ensure_all_started(ssl),
    % The apparent need to call  ssl:close/2 to renegotiate is in jamdb_oracle_conn
    % but I can reproduce the unexpected {error, _} response using erlang.org:
    TcpHost = "www.erlang.org",
    TcpPort = 443,
    Ciphers =
        ssl:filter_cipher_suites(
            ssl:cipher_suites(all, 'tlsv1.3'), []),
    SslOptions =
        [{cacertfile, "_build/dev/lib/castore/priv/cacerts.pem"},
         {certfile, "wallet/clcerts.pem"},
         {ciphers, Ciphers},
         {keyfile, "wallet/priv.pem"},
         {server_name_indication, TcpHost},
         {verify, verify_peer}],
    {ok, Port} =
        gen_tcp:connect(TcpHost,
                        TcpPort,
                        [binary,
                         {active, false},
                         {packet, raw},
                         {nodelay, true},
                         {keepalive, true}],
                        15000),
    {ok, {sslsocket, {gen_tcp, Port, tls_connection, undefined}, [_, _]} = Socket} =
        ssl:connect(Port, SslOptions, 1000),
    % Insert delay to prevent the failure:
    % timer:sleep(1000),
    {ok, Port} = ssl:close(Socket, {self(), 15000}),
    gen_tcp:close(Port).
```

**Expected behavior**
This line to successfully match, even if there's been no delay:
```erlang
    {ok, Port} = ssl:close(Socket, {self(), 15000}),
```

**Affected versions**
Erlang/OTP 24.0.2 on macOS 11.4 (20F71) installed with `asdf` and compiled with:
```bash
KERL_BUILD_DOCS="yes"
KERL_CONFIGURE_OPTIONS="--without-javac --with-ssl=/usr/local/opt/openssl@1.1"
```

**Additional context**
I'm having trouble making connections to Oracle Cloud's databases using `jamdb_oracle`; see erlangbureau/jamdb_oracle#98. The package calls `gen_tcp:connect/4` and `ssl:connect/3` as above, then `ssl:send/2` to send a login packet. On getting a particular reply from `ssl:recv/2`, it then attempts to downgrade with `ssl:close/2` as above. It fails, preventing it from trying `ssl:connect/3` again.

 @vstavskyi reports success only with this patch to OTP24:

```diff
--- ssl_gen_statem.erl.orig
+++ ssl_gen_statem.erl
@@ -596,7 +596,7 @@
 		    [{reply, From, {ok, SelectedProtocol}}]);
 connection({call, From},
            {close, {Pid, _Timeout}},
-           #state{connection_env = #connection_env{terminated = closed} = CEnv,
+           #state{connection_env = #connection_env{terminated = false} = CEnv,
                  protocol_specific = PS} = State) ->
     {next_state, downgrade, State#state{connection_env =
```

If this is an OTP bug, it strikes me y'all should know about it. If not, I'd much appreciate correction on how to successfully negotiate this connection.

**Comment by garthk** [comment]
More context: I think I should have called out this info log from https://github.com/erlangbureau/jamdb_oracle/issues/98:
> [info] TLS :client: In state :connection at ssl_record.erl:450 generated CLIENT ALERT: Fatal - Bad Record MAC - :decryption_failed

If I change `jamdb_oracle_conn:handle_login/1` so it resends without renegotiation, the driver process crashes with that error prominently:
> [error] Jamdb.Oracle (#PID<0.544.0>) failed to connect: ** (DBConnection.ConnectionError) {:socket, {:tls_alert, {:bad_record_mac, 'TLS client: In state connection at ssl_record.erl:450 generated CLIENT ALERT: Fatal - Bad Record MAC\n decryption_failed'}}}

`:dbg` shows that part of the message came from the `ssl:recv/3` return value: 
```erlang
{error,
  {tls_alert,
  {bad_record_mac,
    "TLS client: In state connection at ssl_record.erl:450 generated CLIENT ALERT: Fatal - Bad Record MAC\n decryption_failed"}}},
```
Perhaps related:
* [ERL-538](https://bugs.erlang.org/browse/ERL-538), though this happens even if I filter out the `chacha20_poly1305` cipher
* [ERL-1136](https://bugs.erlang.org/browse/ERL-1136)
* [ERL-1331](https://bugs.erlang.org/browse/ERL-1331), though this happens even if I restrict the ciphers to `ssl:filter_cipher_suites(ssl:cipher_suites(all, 'tlsv1.2'), [])`

… but I'm out of my depth, and should perhaps quit while I'm behind. :)

**Comment by garthk** [comment]
@vstavskyi provided more context (thanks!): see also #1458 “Fix SSL connection downgrade ” which got closed before merge because, if I'm reading it right, it mixed concerns.

**Comment by vstavskyi** [comment]
I couldn't find how init value **false**  in #connection_env{terminated = false} became **closed** in  #connection_env{terminated = closed} .

**Comment by garthk** [comment]
I can't find any assignment to `closed` either: it seems `terminated` always starts `false` and is only ever set `true`, though my Erlang is poor and I might be missing some assignment. You refactored this ~7mo ago, @IngelaAndin; any clues?

<details><summary>Rudimentary search in OTP 24.0.3 (0a887ba0):</summary>

```plain
~/src/open/otp$ rg -n 'terminated = \S+' | cat
lib/ssl/src/tls_gen_connection.erl:770:    {next_state, StateName, State#state{connection_env = CEnv#connection_env{terminated = true}}};
lib/ssl/src/ssl_connection.hrl:96:                          terminated = false                          ::boolean() | closed,  
lib/ssl/src/ssl_gen_statem.erl:599:           #state{connection_env = #connection_env{terminated = closed} = CEnv,
lib/ssl/src/ssl_gen_statem.erl:602:                                            CEnv#connection_env{terminated = true,
lib/ssl/src/ssl_gen_statem.erl:626:                                                                        terminated = true},
lib/ssl/src/ssl_gen_statem.erl:700:     {reply, From, Result}, State#state{connection_env = CEnv#connection_env{terminated = true}}};
lib/ssl/src/ssl_gen_statem.erl:711:                                                            CEnv#connection_env{terminated = true}},
lib/ssl/src/ssl_gen_statem.erl:715:                     State#state{connection_env = CEnv#connection_env{terminated = true}}}
lib/ssl/src/ssl_gen_statem.erl:1078:terminate(_, _, #state{connection_env = #connection_env{terminated = true}}) ->
lib/ssl/src/ssl_gen_statem.erl:1299:                                                                  connection_env = #connection_env{terminated = true},
```
</details>

Strikes me if that's right, then the test coverage will show a gap for this entire clause of `connection/3`:

https://github.com/erlang/otp/blob/0a887ba078f6faadea128b51a98e928dcb0e79a4/lib/ssl/src/ssl_gen_statem.erl#L597-L607

It'd also explain the `function_clause` errors I'd seen but not isolated; I'll see if I can reproduce them again now I've got `:dbg` strapped on.

**Comment by IngelaAndin** [comment]
I will check it when I get back from vacation.

**Comment by IngelaAndin** [comment]
Humm ... I think we have ended up with some inconsistent code here.  I think both the above clause and the next one needs some rewriting. I will make a PR.

**Comment by IngelaAndin** [comment]
I believe that my PR should solve your problem, it would be great if you could try it. It will make your recreation example behave differently. Although now it will also get a TCP closed as erlang.org will not want to downgrade!

**Comment by vstavskyi** [comment]
Now function connection/3 without send_alert(?ALERT_REC(?WARNING, ?CLOSE_NOTIFY)... is missing.

Parameter for not sending CLOSE_NOTIFY during downgrade is needed.
Or this patch is needed.

```
--- ssl_gen_statem.erl.orig
+++ ssl_gen_statem.erl
@@ -595,6 +595,17 @@
                                                  negotiated_protocol = undefined}} = State) ->
     hibernate_after(?FUNCTION_NAME, State,
 		    [{reply, From, {ok, SelectedProtocol}}]);
+connection({call, From},
+           {close,{NewController, _Timeout}},
+           #state{protocol_specific = PS,
+                  connection_env = #connection_env{socket_tls_closed = false, socket_terminated = false} = CEnv
+                 } = State) ->
+    {next_state, downgrade, State#state{connection_env =
+                                        CEnv#connection_env{downgrade = {NewController, From}},
+                                        protocol_specific = PS#{active_n_toggle => true,
+                                        active_n => 1}
+                                        },
+     [{next_event, internal, ?ALERT_REC(?WARNING, ?CLOSE_NOTIFY)}]};
 connection({call, From}, 
            {close,{NewController, Timeout}},
            #state{connection_states = ConnectionStates,

```

**Comment by IngelaAndin** [comment]
I do not think that I agree. A downgrade without sending the close notify alert will never succeed.  Before the connection can be allowed to be successfully downgraded a close notify alert must have been received from the peer.  Also, both sides need to be in agreement that a downgrade is what is wanted so that the connection is kept alive and can be used after TLS has been terminated.

**Comment by garthk** [comment]
If I can successfully build this PR I'll be able to test against the Oracle database which prompted the bug: erlang.org was just to show reproduction. I trust the database is ready for renegotiation.

**Comment by IngelaAndin** [comment]
I see no reason why you should not be able to build OTP with my PR. I suspect that it is rather the action of replaying the received close alert from the peer in the "downgrad" state that is important to your use case and this will still happen when needed. Also, I added handling of possible cookie messages in TLS-1.3 which would cause problems for the erlang.org case, which may or may not have been a problem in your database case.
