### ISSUE TITLE
UDS in windows

### ISSUE THREAD

**Issue by menih** [erlang/otp#5024]
I am trying to use Named Pipes in windows, which seems to work just fine if I compile things with C. using open_port(), just like I would successfully would have done in Linux. It returns einval error. Is there anything I have to do special ?

I also tried UDS (Unix Domain Sockets which also works ok in C program, but is not successful with Erlang on Windows.

What I really want is an IPC that does not require external TCP/UDP port to be exposed by the external process and it is already running by the time I need to connect to it. So no, I cannot start it and use stdin/stdout.

**Comment by bmk** [comment]
We have not yet implemented support for Windows in our socket nif (the plan is for it to be added in OTP-25).
But when we do, we will also add UDS support.

**Comment by bmk** [comment]
Socket on Windows is now supported (as of 26.0), although still "preliminary"
(I think we need 26 to be iron out "all" the issues).
As for UDS, I only just heard that its a thing on Windows. We need to investigate,
but it does look like a nice feature to add.

**Comment by bmk** [comment]
I see that we are using AF_LOCAL rather than AF_UNIX in our code,
which may be an issue.

**Comment by bmk** [comment]
As it turns out, no we did not. We had some if-def'ing going on...

**Comment by bmk** [comment]
https://devblogs.microsoft.com/commandline/windowswsl-interop-with-af_unix/

**Comment by bmk** [comment]
This will be released in 26.1
