### ISSUE TITLE
It's not possible to use certificates with RSASSA-PSS public key or signature for tls server

### ISSUE THREAD

**Issue by sigsergv** [erlang/otp#5029]
One can specify RSA PSS key and certificate in ssl options but attempts to use the cause crash.

**How to reproduce**

Generate key and certificate:

~~~
openssl genpkey -algorithm rsa-pss -pkeyopt rsa_keygen_bits:2048 -pkeyopt rsa_keygen_pubexp:65537 -pkeyopt rsa_pss_keygen_saltlen:100 -out key.pem
openssl req -new -x509 -batch -days 1000 -key key.pem -subj '/C=AQ/O=Penguin Co./CN=Demo Cert' -out cert.pem
~~~

Execute testing script:
~~~
main(_) ->
    ssl:start(),
    Opts = [{certfile, "cert.pem"}, {keyfile, "key.pem"},{reuseaddr, true}],
    {ok, ListenSocket} = ssl:listen(19998, Opts),
    {ok, Socket} = ssl:transport_accept(ListenSocket, 100000),
    {ok, TLSSocket} = ssl:handshake(Socket, Opts, 10000),
    ssl:send(Socket, "BLBLBLBL\n"),
    1
~~~

Try to open URL https://localhost:19998:

~~~
telnet-ssl -z ssl localhost 19998
~~~

**Expected behavior**
TLS connection should be established and text string `BLBLBLBL` transfered to client.

**Actual behaviour**
~~~
=NOTICE REPORT==== 7-Jul-2021::17:50:48.482268 ===
TLS server: In state hello at tls_handshake.erl:248 generated SERVER ALERT: Fatal - Handshake Failure
 - malformed_handshake_data
escript: exception error: no match of right hand side value {error,
                                                    {tls_alert,
                                                     {handshake_failure,
                                                      "TLS server: In state hello at tls_handshake.erl:248 generated SERVER ALERT: Fatal - Handshake Failure\n malformed_handshake_data"}}}
~~~

**Affected versions**
OTP 24

**Additional context**
 RSA PSS public key and signature algorithms are not recognized by functions public_key:pkix_sign_types and ssl_certificate:public_key_type:

~~~
Erlang/OTP 24 [erts-10.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Eshell V10.5  (abort with ^G)
1> public_key:pkix_sign_types({1,2,840,113549,1,1,10}).
** exception error: no function clause matching public_key:pkix_sign_types({1,2,840,113549,1,1,10}) (public_key.erl, line 729)
2> ssl_certificate:public_key_type({1,2,840,113549,1,1,10}).
** exception error: no function clause matching ssl_certificate:public_key_type({1,2,840,113549,1,1,10}) (ssl_certificate.erl, line 214)
3> 
~~~

**Comment by IngelaAndin** [comment]
It looks like your example is trying to negotiate TLS-1.2 and it is true that we have not implemented the handling of RSASSA-PSS  PSS algorithms for TLS-1.2 yet. Currently, only RSASSA-PSS RSAE algorithms are implemented for TLS-1.2. It should work if TLS-1.3 is negotiated.  The requirement of TLS-1.2 also handling such certs is mandated by the TLS-1.3 standard and hence in our backlog.

**Comment by sigsergv** [comment]
Thank you, my private key was created with unsupported options (sha1 as md), correct command is (added sha256 digest and changed saltlen):

~~~
openssl genpkey -algorithm rsa-pss -pkeyopt rsa_keygen_bits:2048 -pkeyopt rsa_keygen_pubexp:65537 -pkeyopt rsa_pss_keygen_md:sha256 -pkeyopt rsa_pss_keygen_saltlen:20 -out key.pem
~~~

Also I've added additional options to server code to enforce tls 1.3: `{versions, ['tlsv1.2', 'tlsv1.3']}`

With that key testing client is working fine:

~~~
openssl s_client -tls1_3 -connect localhost:19998
~~~

So I think bug is invalid.

**Comment by IngelaAndin** [comment]
Well, I suppose you might regard it as a missing feature of TLS-1.2 connections when TLS-1.3  is enabled, then it should be possible to use RSASSA-PSS for certificate verification in  TLS-1.2 negotiated connections too. Must of course be supported by both sides.
