### ISSUE TITLE
win32reg:value/2 fails to get default value ('default' or "")

### ISSUE THREAD

**Issue by reganheath** [erlang/otp#5037]
The function win32reg:value/2 cannot be used to get the default value of a registry key.  
- Passing 'default' results in `Bad value on output port 'registry__drv__ wr'`
- Passing "" results in `error:{case_clause,{value,{default,"test"}}} at [{win32reg,value,2,[{file,"win32reg.erl"},{line,175}]},`

The expected outcome is `{ok, Value}` when a value exists.

This affects OTP 24.0

I have a pull request #5038 which should fix this issue, as well as #4702 and I also noticed a weakness in change_key/2 when passed a relative path of .. and at the "top" of the tree.

**Comment by sverker** [comment]
Fixed in OTP 24.1.
