### ISSUE TITLE
Erlang Server Crashed

### ISSUE THREAD

**Issue by gulzarahamed** [erlang/otp#5045]
**Describe the bug**
RabbitMQ is not working after Installed Erlang OTP 23.2(11.1.4) and RabbitMQ Server 3.8.11 in Windows 10 Machine

**To Reproduce**
User has administrator privileges
In administrator Mode install Erlang OTP 23.2(11.1.4) and RabbitMQ Server 3.8.11
Open Command Prompt in Admin Mode and navigate to C:\Program Files\RabbitMQ Server\rabbitmq_server-3.8.11\sbin
Run "rabbitmq-plugins enable rabbitmq_management" command

**Expected behavior**
RabbitMQ Management Console should be enabled

**Affected versions**
Erlang OTP 23.2(11.1.4)

Exception Message:-

22:41:30.800 [error] GenServer :net_kernel terminating
** (stop) {:could_not_start_server, :inet_gethost_native}
    (kernel 7.2) inet_gethost_native.erl:549: :inet_gethost_native.ensure_started/0
    (kernel 7.2) inet_gethost_native.erl:488: :inet_gethost_native.getit/2
    (kernel 7.2) inet.erl:1295: :inet.gethostbyname_tm_native/4
    (kernel 7.2) inet.erl:1246: :inet.getaddrs_tm/3
    (kernel 7.2) inet.erl:658: :inet.getaddr_tm/3
    (kernel 7.2) inet.erl:653: :inet.getaddr/3
    (kernel 7.2) inet_tcp_dist.erl:59: :inet_tcp_dist.gen_select/2
    (kernel 7.2) net_kernel.erl:1532: :net_kernel.select_mod/2
Last message: {:auto_connect, :rabbit@md2se77c, {1, #Reference<0.2819954093.4104257546.155285>}}

22:41:30.800 [error] Process #PID<0.103.0> on node :"rabbitmqcli-302-rabbit@md2se77c" raised an exception
** (ErlangError) Erlang error: :eacces
    erlang.erl:2272: :erlang.open_port({:spawn, 'inet_gethost 4 '}, [{:packet, 4}, :eof, :binary])
    (kernel 7.2) inet_gethost_native.erl:184: :inet_gethost_native.server_init/2

22:41:30.800 [error] GenServer :inet_gethost_native_sup terminating
** (stop) :eacces
    erlang.erl:2272: :erlang.open_port({:spawn, 'inet_gethost 4 '}, [{:packet, 4}, :eof, :binary])
    (kernel 7.2) inet_gethost_native.erl:184: :inet_gethost_native.server_init/2
Last message: {:EXIT, #PID<0.103.0>, {:eacces, [{:erlang, :open_port, [{:spawn, 'inet_gethost 4 '}, [{:packet, 4}, :eof, :binary]], [file: 'erlang.erl', line: 2272]}, {:inet_gethost_native, :server_init, 2, [file: 'inet_gethost_native.erl', line: 184]}]}}
"escript: exception error: undefined function 'Elixir.Inspect.BitString':inspect/2\n  in function  'Elixir.Inspect.Algebra':container_each/6 (lib/inspect/algebra.ex, line 402)\n  in call from 'Elixir.Inspect.Algebra':container_doc/6 (lib/inspect/algebra.ex, line 380)\n  in call from 'Elixir.Inspect.Algebra':container_each/6 (lib/inspect/algebra.ex, line 402)\n  in call from 'Elixir.Inspect.Algebra':container_doc/6 (lib/inspect/algebra.ex, line 380)\n  in call from 'Elixir.Inspect.Algebra':container_each/6 (lib/inspect/algebra.ex, line 402)\n  in call from 'Elixir.Inspect.Algebra':container_doc/6 (lib/inspect/algebra.ex, line 380)\n  in call from 'Elixir.Inspect.Algebra':container_each/6 (lib/inspect/algebra.ex, line 402)\n"

O/S Info:-

Windows 10 Enterprise
Version 1909
OS build 18363.1621

Note: A week before it was working , I could not conclude what was happened in past two days, I have tried re-install the erlang and rabbitmq and stuck on it.
[crash.log](https://github.com/erlang/otp/files/6797331/crash.log)
[port listening info.txt](https://github.com/erlang/otp/files/6797338/port.listening.info.txt)
[rabbit@md2se77c.log](https://github.com/erlang/otp/files/6797344/rabbit%40md2se77c.log)

**Comment by garazdawi** [comment]
Hello,

For some reason, the `inet_gethost` program returns EACCES (permission denied) when executed. So you will have to check your system and see why that might be. The program should be located in `%ERLANG_INSTALL%/erts-X.Y.Z/bin/`.

The Erlang bug tracker is not really the right place to look for help on issues such as these. I would suggest either posting a message to the erlang-questions mailing list or the rabbitmq mailing list to see if anyone else has come across a similar problem or has some suggestions.

Lukas

**Comment by Freakbrain** [comment]
why don't you fix it?

**Comment by Santhanakumar01** [comment]
I have also the same issues. When starting the elixir app then this error
