### ISSUE TITLE
public_key:pkix_sign generates incorrect signature for RSASSA-PSS algorithm

### ISSUE THREAD

**Issue by sigsergv** [erlang/otp#5054]
When you sign a certificate with RSASSA-PSS private key using function public_key:pkix_sign/2 it generates incorrect signature. Resulting certificate fails path validation.

**To Reproduce**

I've attached simple test to demonstrate issue: [test.zip](https://github.com/erlang/otp/files/6819964/test.zip)

Just execute script `test3` and it returns: `Certificate verification result: {error,{bad_cert,invalid_signature}}`

Script load certificate `cert.pem` (self-signed) and private key `key.pem` (RSASSA-PSS), both created in openssl:

~~~
openssl genpkey -algorithm rsa-pss -pkeyopt rsa_keygen_bits:2048 -pkeyopt rsa_keygen_pubexp:65537 -pkeyopt rsa_pss_keygen_md:sha256 -pkeyopt rsa_pss_keygen_saltlen:20 -out key.pem
openssl req -new -x509 -batch -days 1000 -key key.pem -subj '/C=AQ/O=Penguin Co./CN=Demo Cert' -out cert.pem
~~~

Then it signs hardcoded tbs certificate, writes it to `signed-cert.pem` and executes path validation function `public_key:pkix_path_validation/3`.

**Expected behavior**

Signed certificate must pass path validation.

**Affected versions**
OTP24

**Possible fix**

~~~~
diff --git a/lib/public_key/src/pubkey_cert.erl b/lib/public_key/src/pubkey_cert.erl
index 66d37ebf96..5310785328 100644
--- a/lib/public_key/src/pubkey_cert.erl
+++ b/lib/public_key/src/pubkey_cert.erl
@@ -537,10 +537,10 @@ gen_test_certs(
 
 
 x509_pkix_sign_types(#'SignatureAlgorithm'{algorithm = ?'id-RSASSA-PSS',
-                                           parameters = #'RSASSA-PSS-params'{hashAlgorithm = #'HashAlgorithm'{algorithm = Alg}}}) ->
+                                           parameters = #'RSASSA-PSS-params'{saltLength = SaltLen, hashAlgorithm = #'HashAlgorithm'{algorithm = Alg}}}) ->
     Hash = public_key:pkix_hash_type(Alg),
     {Hash, rsa_pss_pss, [{rsa_padding, rsa_pkcs1_pss_padding},
-                         {rsa_pss_saltlen, -1},
+                         {rsa_pss_saltlen, SaltLen},
                          {rsa_mgf1_md, Hash}]};
 x509_pkix_sign_types(#'SignatureAlgorithm'{algorithm = Alg}) ->
     {Hash, Sign} = public_key:pkix_sign_types(Alg),
~~~~

After that patch signed ceritficate passes path validation in erlang and in openssl.

**Comment by IngelaAndin** [comment]
Looks reasonable, would you consider creating a PR for it?
