### ISSUE TITLE
Yecc generates code which has unused functions

### ISSUE THREAD

**Issue by skynet1** [erlang/otp#5067]
**Describe the bug**
Yecc generates code which contains unused functions which the compiler complains about.

**To Reproduce**
Run yecc on the attached file 
[jsparsey.zip](https://github.com/erlang/otp/files/6863429/jsparsey.zip).

**Expected behavior**
Yecc should not generate code that has unused functions.

**Affected versions**
25.0-rc0.

**Additional context**
The OS is manjaro Linux, and the OTP version is the latest version that was compiled from this repo.

**Comment by uabboli** [comment]
Thank you for the bug report. Merged commit 33e7948d29c6b67f10939fd0b66e1f1079f3ebe1 into erlang:maint.
