### ISSUE TITLE
temp_alloc: Cannot reallocate 34359738368 bytes of memory (of type "estack")

### ISSUE THREAD

**Issue by gzj0518** [erlang/otp#5072]
Describe the bug
The combination of RabbitMQ 3.8.16 and Erlang/OTP 24.0 running on CentOS 7.9 results in the node crashing. 
The temp_alloc allocator seems to have a huge size in the crash dump despite the node using only a few hundred megabytes of memory.

Fri Jul 16 22:27:40 2021
Slogan: temp_alloc: Cannot reallocate 34359738368 bytes of memory (of type "estack")
System version: Erlang/OTP 24 [erts-12.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]
Compiled: Fri Jun 18 10:43:52 2021
Taints: asn1rt_nif,crypto
Memory allocated: 122MB
Memory maximum: 
Atoms: 46715
Processes: 928
ETS tables: 192
Timers: 194
Funs: 6133
Calling Thread: scheduler:1

I can share the erl_crash.dump file privately
[229.tar.gz](https://github.com/erlang/otp/files/6883260/229.tar.gz)
[228.tar.gz](https://github.com/erlang/otp/files/6883264/228.tar.gz)

Affected versions
OTP 24.0 downloaded from erlang.org.

Additional context
RabbitMQ sets the folllowing allocator flags at startup:
+MBas ageffcbf +MHas ageffcbf +MBlmbcs 512 +MHlmbcs 512 +MMmcs 30

**Comment by RaimoNiskanen** [comment]
Platform and processor type might be useful here since this could be a byte order or sign problem.

**Comment by lhoguin** [comment]
This might be related to https://github.com/erlang/otp/issues/4981 which has a fix released in OTP-24.0.2.

**Comment by gzj0518** [comment]
> 
> 
> Platform and processor type might be useful here since this could be a byte order or sign problem.

 Intel Xeon  processor  

Linux  3.10.0-1160.25.1.el7.x86_64   x86_64 GNU/Linux

**Comment by garazdawi** [comment]
Have you tested with OTP-24.0.2 or later?

**Comment by rickard-green** [comment]
Closing this. Please reopen if this occurs with an OTP version larger or equal to OTP 24.0.2

**Comment by gzj0518** [comment]
> 
> 
> Have you tested with OTP-24.0.2 or later?



> 
> 
> Have you tested with OTP-24.0.2 or later?

No test with OTP-24.0.2 or later

**Comment by gzj0518** [comment]
> 
> 
ok，thanks

**Comment by gzj0518** [comment]
> 
> 
> Closing this, since this most likely is due to the bug fixed in OTP 24.0.2. Please reopen this issue if this occurs with an OTP version larger than or equal to OTP 24.0.2

OK,thanks
