### ISSUE TITLE
etop limited terminal width cause column value truncation

### ISSUE THREAD

**Issue by menih** [erlang/otp#5080]
etop line length always calculated base on 80 chars, even of terminal is configured with much wider. As a result large numbers gets truncated (******). Is there a workaround for this?

**Comment by lhoguin** [comment]
Not a workaround per se but https://github.com/zhongwencool/observer_cli is a much better alternative these days.

**Comment by menih** [comment]
Can it be added to otp?

**Comment by menih** [comment]
Need to modify the following https://github.com/erlang/otp/blob/master/lib/observer/src/etop_txt.erl#L104.

Main reason for using etop is .... it is already incorporated in OTP so any system will just have it. It is quite useful.

**Comment by garazdawi** [comment]
There is no workaround and it is not something that we are planning to fix. However, a PR fixing the issue would be most welcome.
