### ISSUE TITLE
Strange rendering in crashdump viewer

### ISSUE THREAD

**Issue by michalmuskala** [erlang/otp#5107]
**Describe the bug**
In the "Internal Tables" section of the crashdump viewer (but possibly in other sections as well), it looks like the test is re-rendered on top of the old text at each selection change. Please see the video attached.

https://user-images.githubusercontent.com/477062/128856204-61a3f95d-981b-4e4f-9f1c-f69156d8b524.mov

**To Reproduce**
* `$ erl -s erlang halt foobar`
* `$ erl -eval 'crashdump_viewer:start("erl_crash.dump").'`
* Navigate to the "Internal Tables" pane and click around

**Expected behavior**
Normal text rendering

**Affected versions**
Checked on OTP 24.0.3

**Comment by dgud** [comment]
I can't see it on windows nor linux (gtk), so appears to be a wxWidgets bug on macOS. 
What wxwidgets version do you use?

**Comment by dgud** [comment]
Closing this, re-open if still is an issue with newer wxWidgets.
