### ISSUE TITLE
I add maya file manually i cant see it in library. I show the direction. 

### ISSUE THREAD

**Issue by NuryAnim** [erlang/otp#5124]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Affected versions**
The OTP versions that are affected by this bug.

**Additional context**
Add any other context about the problem here. If you wish to attach Erlang code you can either write it directly in the post using [code tags](https://guides.github.com/features/mastering-markdown/), create a [gist](https://gist.github.com), or attach it as a zip file to this post.

**Comment by sverker** [comment]
No comprende.
