### ISSUE TITLE
fts_rand_float_decimals test fail in some rare case

### ISSUE THREAD

**Issue by DianaOlympos** [erlang/otp#5128]
[Link to the test code](https://github.com/erlang/otp/blob/master/erts/emulator/test/num_bif_SUITE.erl#L283)
Reproduction at the end

This was found as part of #4719 

Here is what i understand of the problem here.

We are basically testing `printf` from the libc. The problem is that we try to compute the maximum difference when limiting the number of decimals from first principles... but this is heavily influenced by _what type of rounding does `printf` use_.

Sadly, i went diving into the C spec and the spec says

> The low-order digit shall be rounded in an implementation-defined manner. 

What that means is that we are incapable of predicting the maximum difference in a way that is highly useful, cause we are forced to expect it to round up or down by a whole unit.

So i think this test should be deleted and would be happy to offer a PR for this.

Additional support for this deletion:
- Some of this test is already not run on windows
- Some of this test is already not run for more than 10 decimals

At this point, there is so much edge cases we cannot protect on for a test that basically test `printf` that it seems we should just delete it.

```
F0 = -0.48224313707914995 <<191,222,221,18,81,158,108,219>>

L1 = -0.4822431370792

F1 = -0.4822431370792 <<191,222,221,18,81,158,112,97>>

Diff = 5.007105841059456e-14, MaxDiff = 5.005551115123126e-14


*** CT Error Notification 2021-08-11 17:29:43.936 ***
num_bif_SUITE:'-fts_rand_float_decimals/1-lc$^0/1-0-' failed on line 309
Reason: {badmatch,error}

Full error description and stacktrace




=== Ended at 2021-08-11 17:29:43
=== Location: [{num_bif_SUITE,'-fts_rand_float_decimals/1-lc$^0/1-0-',309},
              {num_bif_SUITE,fts_rand_float_decimals,319},
              {num_bif_SUITE,t_float_to_string,203},
              {test_server,ts_tc,1783},
              {test_server,run_test_case_eval1,1292},
              {test_server,run_test_case_eval,1224}]
=== === Reason: no match of right hand side value error
  in function  num_bif_SUITE:'-fts_rand_float_decimals/1-lc$^0/1-0-'/1 (num_bif_SUITE.erl, line 309)
  in call from num_bif_SUITE:fts_rand_float_decimals/1 (num_bif_SUITE.erl, line 319)
  in call from num_bif_SUITE:t_float_to_string/1 (num_bif_SUITE.erl, line 203)
  in call from test_server:ts_tc/3 (test_server.erl, line 1783)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1292)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 1224)

```

**Comment by kjellwinblad** [comment]
Fixed by merged PR https://github.com/erlang/otp/pull/5133
