### ISSUE TITLE
string:lexemes failes if the binary string's first character is bigger than dec 127

### ISSUE THREAD

**Issue by Bencepapa** [erlang/otp#5137]
**Describe the bug**
string:lexemes failes if the binary string starts with a character with bigger ascii code than 127 like á, Á, ö, Ö and the SeparatorList is not an empty list

**To Reproduce**
The following ones fail:
string:lexemes(<<"Ádám">>, [[$\r,$\n]]).
string:lexemes(<<"Á">>, [[$\r,$\n]]).
string:lexemes(<<"ö">>, [[$\r,$\n]]).
string:lexemes(<<"128">>, [[$\r,$\n]]).

error message:
`** exception error: bad argument: <<128>>
     in function  string:bin_search_inv_1/3 (string.erl, line 1671)
     in call from string:lexemes_m/3 (string.erl, line 1323)
`2
The following ones pass:
string:lexemes(<<"bÁdám">>, [[$\r,$\n]]).
string:lexemes(<<"bÁ">>, [[$\r,$\n]]).
string:lexemes(<<"bö">>, [[$\r,$\n]]).
string:lexemes(<<"127">>, [[$\r,$\n]]).

**Expected behavior**
string:lexemes should accept and process binary strings with starting accent characters

**Affected versions**
erlang          23.2.3 

**Additional context**
Problem occurred while parsed a txt file with hungarian characters. Using utf8 encoded binaries or list strings works as expected

**Comment by dgud** [comment]
This is from the top of the man page of the string module.

> A string in this module is represented by unicode:chardata(), that is, a list of codepoints, 
> binaries with UTF-8-encoded codepoints (UTF-8 binaries), or a mix of the two.
> 

Each function is typed with unicode:chardata() as input/output,
thus non-utf8 binary is not valid input and badarg seems a reasonable response.

Though any case of crash can happen if you supply bad input to the functions and it is not double checked
in all cases that the binary data is valid utf-8 for performance reasons.
