### ISSUE TITLE
SSL certificate expired for packages.erlang-solutions.com

### ISSUE THREAD

**Issue by Amet13** [erlang/otp#5142]
Sorry if it's incorrect repo for issues like that.

**Describe the bug**
SSL certificate expired for packages.erlang-solutions.com

```
# apt update
...                                                                     
Err:10 https://packages.erlang-solutions.com/ubuntu bionic Release                                                                                   
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 143.204.42.85 443]
```

**To Reproduce**
https://packages.erlang-solutions.com/downloads/
![Screenshot 2021-08-21 at 23 12 39](https://user-images.githubusercontent.com/5184847/130333756-379a8b56-340b-4259-b766-3c70027dce1f.png)

**Comment by starbelly** [comment]
Hi @Amet13. packages.erlang-solutions.com is not related to erlang/otp or ericsson. ESL is working to resolve the issue as FYI.

**Comment by IngelaAndin** [comment]
@Amet13  thank you for wanting to report an Erlang/OTP issue (what we don't know we can not fix)  but as @starbelly  pointed out this is an ESL issue that they are working on. So I will close this now.
