### ISSUE TITLE
Incorrect GitHub release name?

### ISSUE THREAD

**Issue by thbar** [erlang/otp#5169]
The GH release at https://github.com/erlang/otp/releases/tag/OTP-24.0.5 (matching tag `OTP-24.0.5`) is described as `OTP 20.0.5`.

All the assets seem to refer to `24.0.5`.

Is that a typo?

**Comment by garazdawi** [comment]
Maybe it is time for me to automate this so that we cannot make typos...

Thanks for reporting! Fixed!

**Comment by thbar** [comment]
> Maybe it is time for me to automate this so that we cannot make typos...

I didn't dare suggesting it yet, but I would agree ^_^

> Thanks for reporting! Fixed!

Thanks for the quick fix!
