### ISSUE TITLE
Typo in httpc.xml

### ISSUE THREAD

**Issue by benbro** [erlang/otp#5177]
Missing letter in [httpc.xml.](https://github.com/erlang/otp/blob/master/lib/inets/doc/src/httpc.xml#L353) Should be connecting instead of connectin:
```<p>This is the <c>SSL/TLS</c> connectin configuration option.</p>```

**Comment by IngelaAndin** [comment]
Thank you for pointing this out. For next time I recommend directly creating a PR that fixes the typo.  As I just did #5182
