### ISSUE TITLE
Wrong type in ssl:str_to_suite documentation

### ISSUE THREAD

**Issue by essen** [erlang/otp#5178]
https://erlang.org/doc/man/ssl.html#str_to_suite-1

```
str_to_suite(CipherSuiteName) -> erl_cipher_suite()

CipherSuiteName =
    string() |
    {error, {not_recognized, CipherSuiteName :: string()}}
```

But the error is what is returned as a return value when the cipher is not recognized, it isn't something accepted as argument.

**Comment by IngelaAndin** [comment]
Thank you for pointing this out,  it was sort of a typo in the spec that slipped through!
