### ISSUE TITLE
Emakefile with erl -make do not compiles yrl file

### ISSUE THREAD

**Issue by 221V** [erlang/otp#5180]
trying to compile https://github.com/erlydtl/erlydtl/tree/0.14.0

Emakefile
```
{"deps/erlydtl/src/*", [{i, "deps/erlydtl/include"}, {outdir, "deps/ebin"}]}.
{"apps/myapp/src/*", [debug_info, {outdir, "apps/ebin"}]}.
```
with
```
ERL_LIBS="apps:deps" erl -make
```
i got next error when try to run my app
```
{"init terminating in do_boot",{undef,[{erlydtl_parser,parse,[[
...
Crash dump is being written to: erl_crash.dump...done
```
because **erlydtl_parser.yrl** was not compiled...

question: there are any parameters for compiling yrl files or Emakefile can not do that?

erlang 23.3, ubuntu 20.04

thank you

**Comment by 221V** [comment]
oh, Emakefile can not find subdirs, so needs
```
{["deps/erlydtl/src/*", "deps/erlydtl/src/filter_lib/*", "deps/erlydtl/src/i18n/*"],
  [{i, "deps/erlydtl/include"}, {outdir, "deps/ebin"}]}.
```
instead of
```
{"deps/erlydtl/src/*", [{i, "deps/erlydtl/include"}, {outdir, "deps/ebin"}]}.
```

**Comment by bjorng** [comment]
The `make` module does not support compiling `.yrl` files. We have no intention of adding such support. We recommend using an external build tool such as [rebar3](https://rebar3.org).
