### ISSUE TITLE
Wrong exception text for `maps:get/2` if map doesn't contain such key

### ISSUE THREAD

**Issue by vshev4enko** [erlang/otp#5196]
**Describe the bug**
It says that argument 2 is not a map although it is a map.

**To Reproduce**
`maps:get(some_key, #{}).`

**Expected behavior**
Do not print that second argument not a map.

**Affected versions**
OTP 24.

**Additional context**
```
5> maps:get(key, #{}).
** exception error: bad key: key
     in function  maps:get/2
        called as maps:get(key,#{})
        *** argument 2: not a map
```

**Comment by bjorng** [comment]
Thanks for the bug report.
