### ISSUE TITLE
don't "Warning: a term is constructed, but never used" in some cases

### ISSUE THREAD

**Issue by DominicGame** [erlang/otp#5203]
in the project, we use this macro
`-define(IF(B, T, F), case B of true -> T; _ -> F end)`

then
```
run(E) ->
    EE = ?IF(E, 1, 0),
    erlang:error(test),
    EE + 1.
```
in this cases, I will get a warning

```
run(_E) ->
    EE = ?IF(true, 1, 0),
    erlang:error(test),
    EE + 1.
```
in this cases, I will not get a warning
I check ".S" file, the compiler has skip "EE"
```{function, run, 1, 2}.
  {label,1}.
    {line,[{location,"test.erl",8}]}.
    {func_info,{atom,test},{atom,run},1}.
  {label,2}.
    {move,{atom,test},{x,0}}.
    {line,[{location,"test.erl",10}]}.
    {call_ext_only,1,{extfunc,erlang,error,1}}.
```

so, should compiler make a warning in this cases?

code:
```
-module(test).

-compile(nowarn_export_all).
-compile(export_all).

-define(IF(B, T, F), case B of true -> T; _ -> F end).

run(_E) ->
    EE = ?IF(true, 1, 0),
    erlang:error(test),
    EE + 1.
```

**Comment by bjorng** [comment]
The compiler intentionally does not warn if the case expression is a literal, because it is likely to be code for debugging such as:

```
-defined(DEBUG, false).
   .
   .
   .
case ?DEBUG of
    true -> . . . ;
    false -> . . .
end
```

**Comment by michalmuskala** [comment]
Since there's the `generated` annotation, what if the code inlined from macros was always annotated with `generated`, and then the compiler only skips warning in case of the generated marker (as it already is the case today).

**Comment by bjorng** [comment]
I don't think we can assume that it is appropriate to suppress all warnings from code generated by macros.

**Comment by DominicGame** [comment]
> 
> 
> I don't think we can assume that it is appropriate to suppress all warnings from code generated by macros.

Oh, I got the point!
I have a better code in this cases!
In the project, I generate macros(test.hrl) from config file(xlsx, csv, etc.)
In some case I will use a "literal" variable('EE')
```
-module(test).

-compile(nowarn_export_all).
-compile(export_all).

%% test.hrl
-define(A, 1).% generate from config
-define(B, 1).% generate from config

-record(protobuf, {
    a = erlang:exit({require, a}),
    b = erlang:exit({require, b}),
    c = erlang:exit({require, c})
}).

run(E) ->
    EE = ?A + ?B,% this is a literal, 
    _P = #protobuf{a = EE, b = E},% I add 'c' in the proto and forget the code
    % send(P),
    EE + E.
```
then
If I use a "literal" variable, compiler will not make any warning
if write it in this way 'EE = ?A + ?B + E', I will get a warning

>
>
>The compiler intentionally does not warn if the case expression is a literal
just like this cases, compiler ignore the "literal" variable

of course, I want a warning
but I don't know if it's a good idea
thanks for you reply!
