### ISSUE TITLE
Performance degradation when spawning concurrent instances of ERTS

### ISSUE THREAD

**Issue by plux** [erlang/otp#5204]
**Describe the bug**
We've ran into an interesting issue where we've observed that it seems
like starting multiple concurrent instances of ERTS on a Linux system
with many cores (72 cores in this example) will slow down the average
run time of each instance. The bulk of the time seems to be spent
making syscalls.

Obviously this is not a common or recommend way of running Erlang
code, but it is a use case where we would like to see improved
performance.

**To Reproduce**
This simple shell script can be used to observe the issue:
```
#!/bin/bash
echo "Using flags: $EMULATOR_FLAGS"
echo "sequential version"
time ( for x in {1..72}; do erl ${EMULATOR_FLAGS} -noshell -eval 'halt()'; done ; wait )
echo "parallel version"
time ( for x in {1..72}; do erl ${EMULATOR_FLAGS} -noshell -eval 'halt()' & done ; wait )
```

Running the script:
```
$ ./erl-testcase.sh

sequential version (observe sys time)

real 0m7.498s
user 0m12.393s
sys  0m7.635s

parallel version (only a 4x speedup with 72 processes. notice the high sys time)

real 0m1.612s
user 0m21.878s
sys  1m26.754s
```

One idea we had was to actually force ERTS to only using a single core
to reduce the concurrency. This seems to make some difference, but not
much.

```
$ EMULATOR_FLAGS="+S1" ./erl-testcase.sh

sequential version (observe sys time)

real 0m6.558s
user 0m6.198s
sys  0m2.020s

parallel version (only a 4x speedup with 72 processes. notice the high sys time)

real 0m1.341s
user 0m11.764s
sys  1m17.610s
```

We observed that it seem like ERTS will make lots of sys calls to read
`/sys/devices/system/`.
When we dug into the source code of OTP we found that `read_topology()`
in `erl_misc_utils.c` issues these calls to determine the CPU topology.

We tried experimenting with bypassing the detected topology using `+sct`
flag to setup a custom defined CPU topology, but it seems like
`read_topology()` is always called during init even when `+sct` flag is
supplied.

To verify the suspicion we added an environment variable to disable
the call to read_topology().

```
diff --git a/erts/lib_src/common/erl_misc_utils.c b/erts/lib_src/common/erl_misc_utils.c
index f50d709..0fb5258 100644
--- a/erts/lib_src/common/erl_misc_utils.c
+++ b/erts/lib_src/common/erl_misc_utils.c
@@ -271,6 +271,8 @@ erts_cpu_info_update(erts_cpu_info_t *cpuinfo)
     int available = 0;
     erts_cpu_topology_t *old_topology;
     int old_topology_size;
+    char *env_val;
+    int skip_read_topology = 0;
 #if defined(ERTS_HAVE_MISC_UTIL_AFFINITY_MASK__)
     cpu_set_t cpuset;
 #endif
@@ -420,7 +422,13 @@ erts_cpu_info_update(erts_cpu_info_t *cpuinfo)
     old_topology_size = cpuinfo->topology_size;
     cpuinfo->topology = NULL;

-    read_topology(cpuinfo);
+    if (env_val = getenv("ERL_SKIP_READ_TOPOLOGY")) {
+        skip_read_topology = atoi(env_val);
+    }
+
+    if (!skip_read_topology) {
+        read_topology(cpuinfo);
+    }

     if (cpuinfo->topology_size != old_topology_size
        || (old_topology_size != 0
```

When setting the environment variable we can see an improvement in sys time:

```
$ ERL_SKIP_READ_TOPOLOGY=1 ./erl-testcase.sh

sequential version (observe sys time)

real 0m7.086s
user 0m12.982s
sys 0m6.657s

parallel version (a 12x speedup with 72 processes)

real 0m0.598s
user 0m22.745s
sys 0m12.201s
```

And even more improvement is seen when limiting ERTS to a single scheduler:

```
$ ERL_SKIP_READ_TOPOLOGY=1 EMULATOR_FLAGS="+S1" ./erl-testcase.sh

sequential version (observe sys time)

real 0m6.163s
user 0m6.352s
sys 0m1.490s

parallel version (a 21x speedup with 72 processes)

real 0m0.289s
user 0m12.391s
sys  0m3.267s
```

**Expected behavior**
There should be a way to improve performance of spawning concurrent ERTS instances on systems with many cores.

**Affected versions**
Atleast OTP-22+

**Questions** 
* Is it possible to avoid the overhead of read_topology() or in other
ways improve performance when spawning concurrent instances of ERTS
without changing the OTP source code?
* If it is not possible - could a PR with such a patch be considered? 
* Is using an environment variable a decent approach or would you suggest another method?
* Could a possible solution be to skip calling `read_topology()` if the
  `+sct` flag is set?

**Comment by rickard-green** [comment]
>  * Is it possible to avoid the overhead of read_topology() or in other ways improve performance when spawning concurrent instances of ERTS without changing the OTP source code?

No I don't think so

> * If it is not possible - could a PR with such a patch be considered?

Yes

> * Is using an environment variable a decent approach or would you suggest another method?

We avoid new environment variables to control things in the VM and prefer command line arguments

> * Could a possible solution be to skip calling read_topology() if the +sct flag is set?

Yes

**Comment by plux** [comment]
Thanks for the reply, I will start working on a patch which uses the flags.

Another thing I discovered is that `read_topology()` is called twice during init, but I can't quite figure out if this is intentional or not.
Do you have any insight regarding that?

**Comment by rickard-green** [comment]
> Another thing I discovered is that read_topology() is called twice during init, but I can't quite figure out if this is intentional or not.
Do you have any insight regarding that?

One comes from [`ethr_aux.c`](https://github.com/erlang/otp/blob/a83541527625fae5d7f849718a052cf6f2833809/erts/lib_src/common/ethr_aux.c#L199) which is part of the ethread library which is supposed to work independently of the runtime system, and one comes from [`erl_cpu_topology.c`](https://github.com/erlang/otp/blob/a83541527625fae5d7f849718a052cf6f2833809/erts/emulator/beam/erl_cpu_topology.c#L1667). Both of these calls are made very early in the initialization sequence. They stem from [`erts_pre_early_init_cpu_topology()`](https://github.com/erlang/otp/blob/a83541527625fae5d7f849718a052cf6f2833809/erts/emulator/beam/erl_init.c#L849) and [`erts_sys_pre_init()`](https://github.com/erlang/otp/blob/a83541527625fae5d7f849718a052cf6f2833809/erts/emulator/beam/erl_init.c#L864) in [`early_init()`](https://github.com/erlang/otp/blob/a83541527625fae5d7f849718a052cf6f2833809/erts/emulator/beam/erl_init.c#L805) which are made before parsing arguments.

I'm not sure but I don't think the ethread library actually needs the cpu topology. I think it only uses the amount of logical processors, but I'm not sure.

I guess it would be possible to not read cpu topology in `erts_cpu_info_create()` and extend `erts_cpu_info_update()` so you can choose if you want cpu topology and or not, and then later read cpu topology using `erts_cpu_info_update()` if you need it after the command line arguments have been parsed.
