### ISSUE TITLE
Broken stable sort of applications when building a release

### ISSUE THREAD

**Issue by tsloughter** [erlang/otp#5211]
**Describe the bug**

The sort order of applications when building a release is not completely stable (as in, some applications end up being put before applications that are listed after them even though there is no dependency that would force this).

**To Reproduce**

```
git clone https://github.com/tsloughter/otel_getting_started/
cd otel_getting_started
git checkout broken-order
rebar3 release
```

Then looking at `_build/default/rel/otel_getting_started/releases/0.1.0/start.script` you'll see that `opentelemetry` and `opentelemetry_api` are started directly after `stdlib`. But `opentelemetry_exporter` has `inets` and `grpcbox` listed before those 2 apps, https://github.com/open-telemetry/opentelemetry-erlang/blob/main/apps/opentelemetry_exporter/src/opentelemetry_exporter.app.src#L8-L11

**Expected behavior**

My understanding of the expected stable sort used by systools when building a release is that `inets` and `grpcbox` should come before `opentelemetry_api` and `opentelemetry` because they are listed before it in an apps list of applications and there is no direct dependency that would make reordering required:

https://github.com/open-telemetry/opentelemetry-erlang/blob/main/apps/opentelemetry_api/src/opentelemetry_api.app.src

https://github.com/open-telemetry/opentelemetry-erlang/blob/main/apps/opentelemetry/src/opentelemetry.app.src

**Affected versions**

Likely all recent versions, but 23 and 24 were tested.

**Additional context**

There was a period when relx used its own stable sort because of a bug in the systools sort, but this was years ago and has been removed for a long time.

**Comment by garazdawi** [comment]
From what I can tell, it works the way it is supposed to. The sorting does not take the order of deps in the `.app` file into consideration, it looks at the `.rel` file.

What is the problem that happens because of the sorting?

**Comment by tsloughter** [comment]
Oh, damn, I see:

> The applications are sorted according to the dependencies between the applications. Where there are no dependencies, the order in the .rel file is kept.

So that is the only stable sort part of the equation. If no dependency in the `.app` files would change the order they are found in the `.rel` file then it must keep the same order as in the `.rel`, but it is our (relx) responsibility to make the order in the `.rel` file be correct.

Thanks, was just me being confused about where systools got the order from.
