### ISSUE TITLE
Possible memory leak in DTLS implementation

### ISSUE THREAD

**Issue by michael-michalski** [erlang/otp#5224]
**Describe the bug**
We are experiencing undesired behavior with our long dtls connections over time: Latency spikes, disconnects, especially once heavier load is introduced.

**To Reproduce**
I created the following repository which can be run it sets up a dtls listener with a ssl connection in a unit test.
https://github.com/michael-michalski/dtls_leak_test
If you run it with various lengths you can see that the heap of ssl_gen_statem process grows at a fast pace.

**Expected behavior**
Heap size of the gen_statem process should be more stable.

**Affected versions**
Tested on OTP 24, but not sure exactly which versions reproduce.

**Comment by michael-michalski** [comment]
I will continue with investigating the issue, let me know if I can assist in any way.

**Comment by michael-michalski** [comment]
# Specs
Operating System: Linux
CPU Information: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
Number of Available Cores: 8
Available memory: 31.34 GB
Elixir 1.12.2
Erlang 24.0.5

## 50 seconds

Name           ips        average  deviation         median         99th %
send        5.16 K      193.76 μs    ±33.18%      178.19 μs      364.80 μs

total_heap_size: 83818,
heap_size: 28690,
stack_size: 19,
reductions: 193295134,

## 100 seconds

Name           ips        average  deviation         median         99th %
send        4.71 K      212.38 μs    ±34.50%      194.39 μs      409.49 μs

total_heap_size: 107742,
heap_size: 46422,
stack_size: 19,
reductions: 385291858,

## 200 seconds

Name           ips        average  deviation         median         99th %
send        4.40 K      227.10 μs    ±41.09%      209.85 μs      435.72 μs

total_heap_size: 373310,
heap_size: 121536,
stack_size: 19,
reductions: 702017154,

**Comment by dgud** [comment]
Would be great if you write the examples in erlang when you do an error report on erlang :-(

**Comment by michael-michalski** [comment]
The error report is on otp. Is it a deal breaker for you that the example is in elixir?
Unfortunately my organization is shifting towards using a different dtls implementation, so I will no longer be able to assist as much going forwards.

**Comment by dgud** [comment]
I don't have the tooling, i.e. elixir installed, neither is I fluent in elixir, 
so it takes an effort for me to re-write the example in erlang and I might do it wrong.
Which makes me less eager to help, which might give you less support.
The less effort it takes to replicate an issue/bug the easier it is to fix it.

I found the bug and a fix will be available soon I hope.
Anyway good catch and thanks for the bug report and making the trouble of writing the example, 
an example in elixir it better than no example.

**Comment by IngelaAndin** [comment]
OTP 24.1.2 has been released
