### ISSUE TITLE
Dialyzer: File path omitted in 'unknown type'

### ISSUE THREAD

**Issue by jtrees** [erlang/otp#5234]
**Describe the bug**
When getting the `unknown_type` warning, the file path (and line) is omitted. This makes debugging very hard.

For example:

```
[{:warn_unknown, {[], 0}, {:unknown_type, {DoesNotExist, :t, 0}}}]
```

This [also affects upstream Elixir projects](https://github.com/jeremyjh/dialyxir/issues/102), such as [dialyxir](https://github.com/jeremyjh/dialyxir).

**To Reproduce**
1. Create a multi-file project
2. Write a typespec using a type that doesn't exist

**Expected behavior**
The dialyzer error should include the filename and line of the encountered reference to the missing type.

**Affected versions**
`Erlang/OTP 22 [erts-10.7.2.3]`

**Additional context**
Previously reported here:
- https://github.com/jeremyjh/dialyxir/issues/102
- https://github.com/erlang-labs/dialyzer/issues/2

**Comment by paulo-ferraz-oliveira** [comment]
Are you able to reproduce this in OTP 24? I reported that bug a while bug and think it's since been fixed.

**Comment by paulo-ferraz-oliveira** [comment]
Here you go: https://github.com/erlang/otp/issues/4416

**Comment by paulo-ferraz-oliveira** [comment]
(that also implied changes to `rebar3`, though I think it was kept backward compatible)

**Comment by paulo-ferraz-oliveira** [comment]
https://github.com/erlang/rebar3/pull/2351/files adapts to the old output (the one you're experiencing).

https://github.com/erlang/rebar3/pull/2481/files adapts to OTP 24.

**Comment by jtrees** [comment]
Oh sweet, I'll check it out.
