### ISSUE TITLE
dialyzer with recursion type

### ISSUE THREAD

**Issue by DominicGame** [erlang/otp#5246]
I think I'd better post the code first:
```
-module(test).

-compile(nowarn_export_all).
-compile(export_all).

-spec run(gb_trees:tree()) -> any().
run({_, T}) ->
    run1(T).

run1({_,_,_,_}) ->
    ok;
run1(nil) ->
    ok.
```
run dialyzer on wls and Windows with otp 23 get same result:
```
test.erl:6: Invalid type specification for function test:run/1. The success typing is
          ({_, 'nil' | {_, _, _, _}}) -> 'ok'
 ```
and this is `gb_trees:tree()` code copy from gb_trees.erl:
```
-export_type([tree/0, tree/2, iter/0, iter/2]).

-type gb_tree_node(K, V) :: 'nil'
                          | {K, V, gb_tree_node(K, V), gb_tree_node(K, V)}.
-opaque tree(Key, Value) :: {non_neg_integer(), gb_tree_node(Key, Value)}.
-type tree() :: tree(_, _).
```

I am confused about that 'type' match perfectly in `test:run1`, but I still get a warning
and this code will look more strange
```
run1({_,_,S,B}) ->
    run1(S),
    run1(B);
run1(nil) ->
    ok.
```
dialyzer result:
```
test.erl:6: Invalid type specification for function test:run/1. The success typing is
          ({_,
           'nil' |
           {_, _,
            'nil' | {_, _, 'nil' | {_, _, _, _}, 'nil' | {_, _, _, _}},
            'nil' | {_, _, 'nil' | {_, _, _, _}, 'nil' | {_, _, _, _}}}}) ->
             'ok'
```
dialyzer try to recursion `test:run1`??

by the way, I search some issue like   #5240 and #5223, but I am not sure if it's the same problem(gb_tree has an opaque too)

**Comment by jhogberg** [comment]
Thanks for your report, but this is not a bug.

You're not supposed to deconstruct opaque types: the whole point of them is that users are not allowed to rely on their structure, and that any attempt to do so is an error.

Opaque types don't match anything but themselves, so even though `{_, 'nil' | {_, _, _, _}}` happens to follow the structure of  `gb_trees:tree()` internally, we need to raise an error as if it did not.

**Comment by KennethL** [comment]
Isn't it a bug (or a weakness) that Dialyzer is not mentioning that an
opaque type is misused in this case?
I think so.

**Comment by jhogberg** [comment]
Sort of, it's a generic invalid specification warning that gives no information beyond "it's broken:" we get the same warning if the spec is `-spec run(some_atom) -> any().` This is something we need to improve in general.

If we extend the example with an actual use (whether in this module or elsewhere), we get an opacity warning as expected:

```erlang
%% t.erl:16:9: The call t:run
%%          (gb_trees:tree(_, _)) contains an opaque term as 1st argument when a structured term of type 
%%           {_, 'nil' | {_, _, _, _}} is expected
foo() ->
    run(gb_trees:empty()).
```

**Comment by DominicGame** [comment]
> You're not supposed to deconstruct opaque types: the whole point of them is that users are not allowed to rely on their structure, and that any attempt to do so is an error.

You are right!
But Dialyzer output make me confused => "I can use these struct, but may be write in a wrong way?"
So, If I can get a warning like "opaque type 'gb_trees:tree(_,_)' should not be deconstruct!"  will be better?

Thanks for your reply!
