### ISSUE TITLE
wxMenuItem.setItemLabel is undefined or private

### ISSUE THREAD

**Issue by rengel-de** [erlang/otp#5250]
When called from Elixir, the following code 

`:wxMenuItem.setItemLabel(menu_item, "abc")`

with a perfectly valid `menu_item` produces this error:

```
iex(5)> recompile
Compiling 4 files (.ex)
warning: :wxMenuItem.setItemLabel/2 is undefined or private. Did you mean one of:

      * getLabel/1

  lib/desktop/component/menu_item.ex:63: MenuItem.make_menu_item/1
```
Workaround: The label can be set, though, if I use the `text` field of the `options`:

```
 defp make_menu_item(action) do
      options = [
        id: action[:id],                        # A non-stock-item-id
        text: "<#{action[:name]}>",  # This is the workaround.
        help: action[:help],
        kind: action[:kind]
        ]
      menu_item = :wxMenuItem.new(options)
      # This produces the error:
      :wxMenuItem.setItemLabel(menu_item, "#{action[:name]}")
      menu_item
  end
```

**Comment by dgud** [comment]
It is only available in OTP-24, since the docs are generated the since tags is not available in wx (yet or ever).

**Comment by dgud** [comment]
wx had large re-write in OTP-24 so the interface have changed between OTP-23 and OTP-24,
but it should be easier to use from elixir now.

I have added these functions, which should be improved and  documented maybe..

```
6> wxe_util:get_const(wxPENSTYLE_SOLID).
100
7> wxe_util:get_name(wxPenStyle, 100).
wxPENSTYLE_SOLID
```
