### ISSUE TITLE
nanosecond in datetime

### ISSUE THREAD

**Issue by q1208c** [erlang/otp#5261]
I am a new guy in Erlang.
Recently, I write a little project use Erlang with MySQL.
Each database table has a "last_update" with "default CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)".
When I select the record from database, the "last_update" column return like "{{2021,9,20},{23,2,34.42323}}".
But, I could not found function to convert it to system_time like "1633321037419851419". 
And, I also could not found function to convert system_time to datetime like above(with nanosecond).
Is there any plain to support datetime with nanosecond?
Currently, I write a function deal with nanosecond and datetime, I don't think is a good function.

Sorry for my poor English.

**Comment by rickard-green** [comment]
No we have no plans on supporting such a datetime representation.

What erlang binding to mysql are you using that delivers this datetime representation with nanoseconds?

**Comment by q1208c** [comment]
> No we have no plans on supporting such a datetime representation.
> 
> What erlang binding to mysql are you using that delivers this datetime representation with nanoseconds?

I use mysql-otp(https://github.com/mysql-otp/mysql-otp) / mysql-otp-poolboy(https://github.com/mysql-otp/mysql-otp-poolboy).
And, I also test the PostgreSQL with egpsql+poolboy.
Both database can return datetime with nanosecond(maybe microsecond), so, I just write my own function deal with it.
I notice that calendar have rfc3339 support, it can have nanosecond, but, only from system_time to rfc3339, not reverse.

Thanks for your explain.

**Comment by zuiderkwast** [comment]
Hello. I'm the author of mysql-otp.

I chose that representation because there was no suitable representation for datetime with nanoseconds in OTP at the time. Feel free to open an issue at mysql-otp if you think we can do something about it.

**Comment by zuiderkwast** [comment]
Btw, MySQL datetime columns don't have nanoseconds by default. When they don't, the value is returned in the calendar format properly.

**Comment by q1208c** [comment]
> Hello. I'm the author of mysql-otp.
> 
> I chose that representation because there was no suitable representation for datetime with nanoseconds in OTP at the time. Feel free to open an issue at mysql-otp if you think we can do something about it.

Thank you for your reply.
The mysql-otp return is good enough for me.
