### ISSUE TITLE
erl -profile_boot true    vm  crash

### ISSUE THREAD

**Issue by xiake-1024** [erlang/otp#5264]
**Describe the bug**
erl -profile_boot true  vm crash

**To Reproduce**
C:\Users\Administrator>erl -profile_boot true
{"init terminating in do_boot",{function_clause,[{init,collect_mfa,[{math,fmod,2
},undefined,0,0],[{file,"init.erl"},{line,1544}]},{init,collect_mfas,2,[{file,"i
nit.erl"},{line,1535}]},{init,do_boot,3,[{file,"init.erl"},{line,892}]}]}}
init terminating in do_boot ({function_clause,[{init,collect_mfa,[{_},undefined,
0,0],[{_},{_}]},{init,collect_mfas,2,[{_},{_}]},{init,do_boot,3,[{_},{_}]}]})

Crash dump is being written to: erl_crash.dump...done

**Affected versions**
OTP 24

**Additional context**
My suggest is in  init.erl
collect_mfas([MFA|MFAs],Info) ->
    case erlang:trace_info(MFA,call_time) of
        {call_time, []} ->
            collect_mfas(MFAs,Info);
        {call_time, undefined} ->
            collect_mfas(MFAs,Info);
        {call_time, false} ->
            collect_mfas(MFAs,Info);
        {call_time, Data} ->
            case collect_mfa(MFA,Data,0,0) of
                {{0,_},_} ->
                    %% ignore mfas with zero time
                    collect_mfas(MFAs,Info);
                MfaData ->
                    collect_mfas(MFAs,[MfaData|Info])
            end
    end.

**Comment by garazdawi** [comment]
Fixed in #5546
