### ISSUE TITLE
gen_udp:connect/3 changes local port number

### ISSUE THREAD

**Issue by benbro** [erlang/otp#5279]
**Describe the bug**
When opening a udp socket with port=0 and calling gen_udp:connect/3 the local port changes:

**To Reproduce**
```erlang
{ok, S} = gen_udp:open(0).
{ok, Port1} = inet:port(S).
gen_udp:connect(S, {127,0,0,1}, 10000).
{ok, Port2} = inet:port(S).
Port1 =/= Port2.
```
**Expected behavior**
The local port should not change.

**Affected versions**
OTP 24.1.2

**Additional context**
Maybe related to PR #5120

**Comment by benbro** [comment]
I can't reproduce it with otp 24.1.2 running on ubuntu 20.04.
Still trying.
```erlang
{ok,S1}=gen_udp:open(10000, [{ip, {127,0,0,1}}]).
{ok,S2}=gen_udp:open(20000, [{ip, {127,0,0,1}}]).
gen_udp:send(S1,{127,0,0,1},20000,<<"test 1">>).
flush().
gen_udp:connect(S2, {127,0,0,1}, 10000).
gen_udp:send(S1,{127,0,0,1},20000,<<"test 2">>).
flush().
```

**Comment by RaimoNiskanen** [comment]
I am for documenting `gen_udp:connect/3`!

**Comment by benbro** [comment]
@RaimoNiskanen I understand not wanting to workaround a Linux kernel bug.
I need the source port to be constant because I advertise it to the client as part of DTLS handshake. Instead of using port 0 for open I could choose a random port in the ephemeral port range and retry on failure but it can get inefficient when large number of ports are already used. Is there other option?

**Comment by RaimoNiskanen** [comment]
Then I guess we will have another look at this...

**Comment by RaimoNiskanen** [comment]
@benbro: I have created a fix that it would be very nice if you could evaluate, in PR #5343

**Comment by benbro** [comment]
Thank you for the PR.
Does the socket backend considered stable enough to be used in production?
I've verified that the local port doesn't change after the first call to gen_udp:connect/3 with both backends:
```erlang
{ok, S} = gen_udp:open(0).
{ok, Port1} = inet:port(S).
gen_udp:connect(S, {127,0,0,1}, 10000).
{ok, Port2} = inet:port(S).
Port1 =:= Port2.
```
```erlang
{ok, S} = gen_udp:open(0, [{inet_backend, socket}]).
{ok, Port1} = inet:port(S).
gen_udp:connect(S, {127,0,0,1}, 10000).
{ok, Port2} = inet:port(S).
Port1 =:= Port2.
```

**Comment by RaimoNiskanen** [comment]
The `socket` backend for `gen_udp` is the newest one (the other one is the backend for `gen_tcp`).

I do not know how much field testing people have done.  We run them in our daily builds and some test cases
simply does not work because the test case e.g assumes that a socket is a port, so we may have missed failing test cases that indicate "real" problems.

Sorry that I do not have a clearer answer for you...
