### ISSUE TITLE
Exporting the re:mp/0 type

### ISSUE THREAD

**Issue by galdor** [erlang/otp#5280]
Would you be ok with exporting the `re:mp/0` type ? In the current situation, code that stores compiled regular expressions cannot be properly annotated because the type is not exported. It forces users to copy the type definition, which is definitely not a good thing.

Bonus point for `re:nl_spec/0` and `re:compile_option/0`, this is the exact same issue.

**Comment by legoscia** [comment]
`re:mp/0` and `re:compile_option/0` are exported as of this change: https://github.com/erlang/otp/pull/7999/files#diff-c55ce6991e26b9b8516eee89aa2b4dffec490406c4b87f6057fefa322a32f15a
