### ISSUE TITLE
FTP passive mode always times out

### ISSUE THREAD

**Issue by D4no0** [erlang/otp#5282]
**Describe the bug**
Let's suppose we start a ftp connection:
```
{:ok, pid} = :ftp.start_service(host: 'test.host.com', verbose: true)
\n220
:ftp.user(pid, 'test', 'test')
"Sending: USER test"
"Receiving: 331 Password required for test"
"Sending: PASS test"
"Receiving: 230 Logged on"
:ftp.ls(pid)                                                                 
"Sending: PASV"
"Receiving: 227 Entering Passive Mode (202,60,200,181,17,149)"

{:error, :timeout}
```

All commands that require data channel always time out.
After digging for some time and using fileZilla to connect to the ftp server I got the following error in fileZilla:

> Server sent passive reply with unroutable address. Using server address instead.

After searching for this error I found this article: https://superuser.com/questions/1195462/server-sent-passive-reply-with-unroutable-address-in-filezilla/1195591#1195591

**Expected behavior**
The server address should be used, or an option to do so should be added.

**Affected versions**
OTP-24.1.2

**Comment by D4no0** [comment]
Also I can confirm that software like `curl` works without any problems.

**Comment by D4no0** [comment]
The passive connection ip gets set [here](https://github.com/erlang/otp/blob/master/lib/ftp/src/ftp.erl#L1678). I can confirm that passing the control channel IP works as expected !!!

I can make a PR, however we should decide on what solution to implement.
I was thinking about using the same mechanism FileZilla client uses and implementing:

- Check if the returned IP is not part of private network IPs and if yes use the IP from **control channel**, show a warning to the user in the process.
- Check if the returned IP is different from the original IP and show warning to the user(it is not likely that the ftp server uses channels located on another server), no actions.

**Comment by kimmerin** [comment]
You can check FEAT if EPSV is supported by the server or simply try EPSV first before falling back to PASV. The EPSV-response doesn't include an IP-address if it's the same as the one being used for the control channel.
