### ISSUE TITLE
The ssl_session_cache sometimes crashes

### ISSUE THREAD

**Issue by mmzeeman** [erlang/otp#5287]
**Describe the bug**

During zotonic web development I sometimes see this crash in my logs.

```
1:51:47.643 [error] gb_trees:470 gen_server <0.700.0> terminated with reason: no function clause matching gb_trees:take_smallest1(nil) line 470
21:51:47.643 [error] gb_trees:470 CRASH REPORT Process <0.700.0> with 0 neighbours crashed with reason: no function clause matching gb_trees:take_smallest1(nil) line 470
21:51:47.644 [error] gb_trees:470 Supervisor ssl_server_session_cache_sup had child undefined started with ssl_server_session_cache:start_link(#Port<0.18>, #{lifetime => 300,max => 20000,session_cb => ssl_server_session_cache_db,session_cb_init_args => []}) at <0.700.0> exit with reason no function clause matching gb_trees:take_smallest1(nil) line 470 in context child_terminated
```

To me it looks like there might be a problem with bookkeeping of the session as it looks like `ssl_server_session_cache` is trying to evict entries from the cache, which is empty, but the `ssl_server_session_cache` things the max is reached, or there are at least some elements in the cache. See: https://github.com/erlang/otp/blob/85530f5fb3b1f737a43206c7d14c5790ca694fb5/lib/ssl/src/ssl_server_session_cache.erl#L163

**To Reproduce**
I don't really have a short steps to reproduce.

**Expected behavior**
No crashing. This could be very noisy on a busy server.

**Affected versions**
A saw it in 23.1, but did not file a report. At the moment I'm running: 24.0.4

**Comment by IngelaAndin** [comment]
Greate :)  Then I will close this. Welcome to reopen if should turn out to be otherwise.
