### ISSUE TITLE
install erlang for aarch64 ( EC2 AWS)

### ISSUE THREAD

**Issue by NguyenXuanNam** [erlang/otp#5299]
**Describe the bug**
wxWidgets was not compiled with --enable-webview or wxWebView developer package is not installed, wxWebView will NOT be available

        wxWidgets must be installed on your system.

        Please check that wx-config is in path, the directory
        where wxWidgets libraries are installed (returned by
        'wx-config --libs' or 'wx-config --static --libs' command)
        is in LD_LIBRARY_PATH or equivalent variable and
        wxWidgets version is 3.0.2 or above.

**Comment by sidkshatriya** [comment]
You need to install some libraries on your system. You have not specified the exact operating system/distribution you are using. If you are using Ubuntu then something like this might help:

```bash
sudo apt install libwxgtk-webview3.0-gtk3-dev
```

The above command might work on a Debian system as Ubuntu is derived from Debian.
