### ISSUE TITLE
Potential process leak in net_kernel with TLS distribution

### ISSUE THREAD

**Issue by aartamonau** [erlang/otp#5332]
**Describe the bug**
I've been looking at `inet_tls_dist` and noticed the following behavior.

A recent patch changed `inet_tls_dist` to do the TLS handshake in subprocesses: https://github.com/erlang/otp/commit/14bc45e39443eeb10adad352c318f6d3807b3745. If the subprocess receives an error from the call to `inet_tcp:accept()`, it [exits](https://github.com/erlang/otp/blob/OTP-24.1.3/lib/ssl/src/inet_tls_dist.erl#L276-L277). This in turn [terminates the acceptor](https://github.com/erlang/otp/blob/OTP-24.1.3/lib/ssl/src/inet_tls_dist.erl#L251-L254). But it is possible that one of the other subprocesses has just sent an `{accept, ...}` message to `net_kernel` [here](https://github.com/erlang/otp/blob/OTP-24.1.3/lib/ssl/src/inet_tls_dist.erl#L291-L294). This process will get killed as well. When handling the `{accept,...}` message, `net_kernel` will spawn a new process via `inet_tls_dist:accept_connection()` and tell `AcceptPid` to [pass the socket to the new process](https://github.com/erlang/otp/blob/OTP-24.1.3/lib/kernel/src/net_kernel.erl#L776-L781). But by this point `AcceptPid` is either dead or about to die, and so it will never pass the socket and unblock the `accept_connection()` [process](https://github.com/erlang/otp/blob/OTP-24.1.3/lib/ssl/src/inet_tls_dist.erl#L456). As far as I can tell, there's no code that would clean these processes up once `net_kernel` [receives the `EXIT` message from the acceptor](https://github.com/erlang/otp/blob/OTP-24.1.3/lib/kernel/src/net_kernel.erl#L1038-L1050).

**To Reproduce**
Found via code inspection, I have not attempted reproducing it.

**Expected behavior**
There should be no leak.

**Affected versions**
OTP-24.1.3

**Comment by u3s** [comment]
I think you are right. I will work on improving the code.

**Comment by u3s** [comment]
I think you're right. Improvement is needed.
