### ISSUE TITLE
inet_tcp_dist / inet_tls_dist ignores custom EPMD name resolution mechanism

### ISSUE THREAD

**Issue by zzydxm** [erlang/otp#5334]
**Describe the bug**
When using custom EPMD module with address_please/3 defined, ip resolving of a dist connection should always go through this function. However right now in inet_tcp_dist:select/1 and inet_tls_dist:select/1, it can end up calling inet:gethostbyname_tm, which is not desired.

**To Reproduce**
Terminal 1:
erl -sname "a@a" -epmd_module my_epmd

Terminal 2:
erl -sname "b@a" -epmd_module my_epmd
net_kernel:connect_node('a@a').
This will return false

However, if we do this, it will success
Terminal 1:
erl -sname "a@localhost" -epmd_module my_epmd

Terminal 2:
erl -sname "b@localhost" -epmd_module my_epmd
net_kernel:connect_node('a@localhost').
true

[my_epmd.zip](https://github.com/erlang/otp/files/7437488/my_epmd.zip)

**Expected behavior**
inet_tcp_dist:select/1 and inet_tls_dist:select/1 should respect EpmdModule:address_please/3 if it is defined

net_kernel:connect_node('a@a') should success

**Affected versions**

**Comment by garazdawi** [comment]
I did a quick attempt at a fix in #5337, can you take a look and see if it solves the problem for you?

**Comment by zzydxm** [comment]
Thanks for the fix!

I think the inet_tcp_dist/inet_tls_dist:select part looks good to me, but there is an additional one (see previous comment): inet_tls_dist:do_setup_connect uses Address (it actually is the string hostname), instead of IP in ssl:connect

Should that done in a separate commit or you work like to put them in one place?

**Comment by garazdawi** [comment]
I fixed the problem in tls dist and added a testcase for it. So it should work now.

**Comment by zzydxm** [comment]
Yeah I verified it works now. Thanks a lot!
