### ISSUE TITLE
`erlang:fun_info/1` returns invalid module name

### ISSUE THREAD

**Issue by moogle19** [erlang/otp#5350]
**Describe the bug**
`erlang:fun_info/1` returns empty list as `module` instead of atom, when module with a function which returns an anonymous function is deleted & purged.

**To Reproduce**
Define a module with a function which returns an anonymous function, e.g.
```erlang
% File: v.erl
-module(v).
-export([function/0]).

function() ->
  fun () -> 
    1 
  end.
```

Start Erlang shell:
```
1> c("v.erl").
{ok,v}
2> Fn = v:function().
#Fun<v.0.69809155>
3> code:delete(v).
true
4> code:purge(v).
false
5> erlang:fun_info(Fn).
[{pid,<0.79.0>},
 {module,[]},
 {new_index,0},
 {new_uniq,<<133,38,128,127,204,81,172,58,50,202,83,21,52,
             153,191,4>>},
 {index,0},
 {uniq,69809155},
 {name,[]},
 {arity,0},
 {env,[]},
 {type,local}]
```

**Expected behavior**
The documentation says that the module returned by `fun_info/1` must be an atom.

**Affected versions**
master

**Comment by jhogberg** [comment]
Thanks for your report, I've fixed it in https://github.com/erlang/otp/pull/5467
