### ISSUE TITLE
No way to silence certificate path validation warning

### ISSUE THREAD

**Issue by ericmj** [erlang/otp#5352]
**Describe the bug**
When making a request without certificate path validation there is no way to silence the produced warning, even when explicitly opting out of verification with `[{verify, verify_none}]`.

**To Reproduce**
```erlang
1> application:ensure_all_started(ssl).
{ok,[crypto,asn1,public_key,ssl]}
2> ssl:connect("google.com", 443, [{verify, verify_none}]).
=WARNING REPORT==== 6-Nov-2021::21:21:05.453579 ===
Description: "Authenticity is not established by certificate path validation"
     Reason: "Option {verify, verify_peer} and cacertfile/cacerts is missing"

{ok,{sslsocket,{gen_tcp,#Port<0.5>,tls_connection,undefined},
               [<0.117.0>,<0.116.0>]}}
```

**Expected behavior**
If I explicitly opt out of verification then I should not get a warning.

**Affected versions**
Since the warning was introduced.

**Comment by IngelaAndin** [comment]
I agree, have been thinking this is a reasonable change. Just have not got around to it yet!
