### ISSUE TITLE
OTP 23 and 24 SSL app violates spec, does not support {3,0} for record layer version

### ISSUE THREAD

**Issue by csrl** [erlang/otp#5380]
**Describe the bug**

From: https://datatracker.ietf.org/doc/html/rfc5246#appendix-E states
> TLS servers compliant with this specification MUST accept any value {03,XX} as the record layer version number for ClientHello

However, starting with OTP 23, the ssl app rejects record layer version of `{3,0}` in violation of the specification.

**To Reproduce**
Use a client that sends `{3,0}` record layer version, even when the client specifies `{3,1}` (or newer) in the `ClientHello.legacy_version` field.

**Expected behavior**
Allow accepting connections from clients that send `{3,0}` (or indeed, any `{3,_}`) as record layer version while using `{3,1}, {3,2}, {3,3}` in ClientHello.legacy_version (when not a tls 1.3 client - a client that does not send supported_versions extension)

![image](https://user-images.githubusercontent.com/48568/141534305-b66f30aa-f18b-4f27-a4f8-1fdfc017e6f8.png)

**Affected versions**
23+

**Additional context**
`ALL_AVAILABLE_VERSIONS` as defined at:
https://github.com/erlang/otp/blob/99943ae054dcb13432c2a4e193b8d240efb7247a/lib/ssl/src/ssl_internal.hrl#L73-L77

The use of ALL_AVAILABLE_VERSIONS is used in two places that are not compatible.

https://github.com/erlang/otp/blob/99943ae054dcb13432c2a4e193b8d240efb7247a/lib/ssl/src/ssl.erl#L1307

and

https://github.com/erlang/otp/blob/99943ae054dcb13432c2a4e193b8d240efb7247a/lib/ssl/src/tls_gen_connection.erl#L535-L549

Specifically using it in the tls_gen_connection.erl for allowed record versions break both backwards and forwards compatibility. Rather it should allow all `{3,_}` to be provided in the record layer version.  Note that does not require supporting sslv3 as the negotiated version.

Additionally the tls 1.2 RFC allows such behavior:
> TLS clients that wish to negotiate with older servers MAY send any value {03,XX} as the record layer version number.  Typical values would be {03,00}, the lowest version number supported by the client, and the value of ClientHello.client_version.

We have production clients that handshake with tlsv1.2 but connect with sslv3 record layer version.  As such their connections are rejected under OTP 23+

We have confirmed that adding {3,0} to the allowed record versions allows the client to handshake with tlsv1.2 while using sslv3 record layer version. Also we have confirmed as expected that sslv3 is still rejected as a negotiated protocol version.

**Comment by IngelaAndin** [comment]
Well, we are following the latest TLS-1.3 RFC. 
"legacy_record_version:  MUST be set to 0x0303 for all records
      generated by a TLS 1.3 implementation other than an initial
      ClientHello (i.e., one not generated after a HelloRetryRequest),
      where it MAY also be 0x0301 for compatibility purposes."    
We could consider making max version dependent so that if TLS-1.2 is the highest version configured we could allow 3.0 record version in the client hello.

**Comment by csrl** [comment]
Thank you for your response.

My understanding of the text you quoted is that a TLS 1.3 client and TLS 1.3 server must implement such constraints on records they generate, but not constrain what a previous tls implementation sends.

A TLS 1.0 - 1.2 client does not have such a constraint on the initial ClientHello handshake record.  To continue quoting the text you shared from section 5.1 (emphasis mine):

> This field is deprecated and MUST be ignored for all purposes. Previous versions of TLS *would use other values* in this field under some circumstances.

I read that text as: A TLS 1.3 server MUST still accept versions {3,0} to {3,3} for the ClientHello record (per tls v1.2 spec) from *non* tls v1.3 clients [^1]. However a tls 1.3 server or client MUST not generate such a record itself (and the other side must reject in such a case).

So, the idea to allow `{3,0}` record protocol version based on whether tls 1.3 is not configured in the server does provide some relief for our case, however I think that is an artificial constraint not dictated by the spec.

Finally I find no additional security risk to allow and ignore any `{3,_}` version in the initial ClientHello handshake record as long as all other constraints specified are respected.

[^1]: As defined as clients that send `ClientHello.legacy_version = 0x303` or less without a tls v1.3 ClientHello `supported_versions` extension per section 4.1.2 legacy_version explanation.

**Comment by IngelaAndin** [comment]
I do not agree.  For instance, it says:
"Note that earlier versions of TLS did not clearly specify the record
   layer version number value in all cases
   (TLSPlaintext.legacy_record_version).  Servers will receive various
   TLS 1.x versions in this field, but its value MUST always be ignored."  

Also 
" If the "supported_versions" extension is absent and the
   server only supports versions greater than
   ClientHello.legacy_version, the server MUST abort the handshake with
   a "protocol_version" alert."   

This will be the case for a real SSL-3.0 hello as it does not support extensions. 

What kind of client do you have that sends TLS-1.2 hellos with an SSL-3.0 record protocol?  SSL-3.0 has been considered broken for many years. If your client is configured to not support the SSL-3.0 version there should not be any reason for it to send such hellos. 

Could you check how OpenSSL handles this?  If it allows it could be an argument for ignoring it even though I do not think the latest RFC mandates it. 

And yes we intentionally dropped all support for SSL-3.0 in OTP-23,  release note: 

"Drop support for SSL-3.0. Support for this legacy TLS version has not been enabled by default since OTP 19. Now all code to support it has been removed, that is SSL-3.0 protocol version can not be used and is considered invalid."

**Comment by csrl** [comment]
> "Note that earlier versions of TLS did not clearly specify the record layer version number value in all cases (TLSPlaintext.legacy_record_version). Servers will receive various TLS 1.x versions in this field, but its value MUST always be ignored."

I guess you are indicating the text `TLS 1.x versions`.  I agree that everyone is generally expecting to not see `{3,0}` anywhere for version fields these days. Conceptually I 100% agree with that.  However, TLS 1.2 specification clearly states (see relevant quote in original post) that it must tolerate clients sending `{3,0}` and clearly states *any* `{3,_}` (both historical and future) versions should be accepted in the record layer version.

TLS 1.3 specification says to completely ignore that legacy record layer version value.  The TLS 1.3 specification is supposed to be tolerant of non TLS 1.3 clients.  And `{3,0}` is a valid record layer version for TLS 1.2 client's to send.  So between TLS 1.2 allowing all 3.x values and TLS 1.3 saying to ignore it, I can not find any violation in supporting `{3,0}`.  It is certainly understandable that there would be ambiguous guidance/text in TLS 1.3 specification only referring to TLS 1.x, simply because SSL 3.0 is no longer even thought about.  But that doesn't mean compatibility with valid implementations should be ignored.

> If the "supported_versions" extension is absent and the server only supports versions greater than ClientHello.legacy_version, the server MUST abort the handshake with a "protocol_version" alert."
> 
> This will be the case for a real SSL-3.0 hello as it does not support extensions.

I absolutely agree, but nowhere is that statement being violated by this request.   The `ClientHello.legacy_version` is being set to `{3,3}` which certainly is supported.  You are conflating the record version and the negotiated handshake version.

> What kind of client do you have that sends TLS-1.2 hellos with an SSL-3.0 record protocol? SSL-3.0 has been considered broken for many years. If your client is configured to not support the SSL-3.0 version there should not be any reason for it to send such hellos.

I agree, and nowhere do I say I want SSL 3 to be a negotiated protocol.  The client uses that for the record version for compatibility with old servers, per tls 1.2 specification guidance.

That said, the client is an embedded device that we have no control over and our customer is using hardware vendor provided SDK, and so to have this addressed at the client side is unrealistic for some time.  So, while we want to offer TLS 1.3 to our customers it is not acceptable to break compatibility with existing devices that are handshaking with supported TLS 1.2.

> Could you check how OpenSSL handles this? If it allows it could be an argument for ignoring it even though I do not think the latest RFC mandates it.


openssl without ssl3 support, and with tls1, tls1_1, tls1_2, tls1_3 support.
```
$ openssl version
OpenSSL 1.1.1l  24 Aug 2021

$ openssl ciphers -ssl3
ciphers: Option unknown option -ssl3
ciphers: Use -help for summary.

$ openssl ciphers -tls1_3
TLS_AES_256_GCM_SHA384:<snip>
```

Run a server:

`openssl s_server -status_verbose -HTTP -cert basic/server/cert.pem -key basic/server/key.pem -msg` 

And here is a simple erlang shell script to send the handshake in question so you can verify openssl server behavior as well:

```erlang
ClientHello = <<22,3,0,0,211,1,0,0,207,3,3,90,84,99,129,207,19,185,164,
  61,79,223,84,76,246,10,150,173,251,185,156,150,32,23,21,
  37,159,129,192,153,178,216,40,0,0,56,192,44,192,48,0,
  159,204,169,204,168,204,170,192,43,192,47,0,158,192,36,
  192,40,0,107,192,35,192,39,0,103,192,10,192,20,0,57,192,
  9,192,19,0,51,0,157,0,156,0,61,0,60,0,53,0,47,0,255,1,0,
  0,110,0,0,0,18,0,16,0,0,13,108,111,99,97,108,104,111,
  115,116,46,99,111,109,0,11,0,4,3,0,1,2,0,10,0,12,0,10,0,
  29,0,23,0,30,0,25,0,24,0,35,0,0,0,22,0,0,0,23,0,0,0,13,
  0,48,0,46,4,3,5,3,6,3,8,7,8,8,8,9,8,10,8,11,8,4,8,5,8,6,
  4,1,5,1,6,1,3,3,2,3,3,1,2,1,3,2,2,2,4,2,5,2,6,2>>.
SayHello = fun() -> {ok,S} = gen_tcp:connect("127.0.0.1",4433,[inet,{active,false}]), gen_tcp:send(S,ClientHello), gen_tcp:close(S) end.
SayHello().
```

Wireshark capture of ClientHello and ServerHello:

![ClientHello](https://user-images.githubusercontent.com/48568/142384464-e982acb3-6379-44d8-a7d1-001d886c9d49.png)

![ServerHello](https://user-images.githubusercontent.com/48568/142384499-821d14f8-0935-422a-af25-0d5303472565.png)


> And yes we intentionally dropped all support for SSL-3.0 in OTP-23, release note:

Absolutely, we are quite aware, and we consider that a very good thing.  However, this is not about negotiating use of SSL v3.0.  It is a TLS v1.2 client that implemented (per tls 1.2 specification) compatibility mechanism for connecting to old servers (using record layer version `{3,0}` in the initial connection. 

Anyway, we are talking about a single byte 0x00 (which is the 3rd byte) that is sent by the client `<<22,3,0>>`.  This byte should be 100% ignored and has no affect on the protocol negotiated as you have stated.  This isn't about supporting ssl3 its about supporting a compliant tls 1.2 client.

Thank you for your patience and consideration with this request.  I'm being verbose to provide as much detail as I can, with what I hope brings clarification of the issue.

**Comment by IngelaAndin** [comment]
Well, I guess it is somewhat a question of interpretation and I agree that legacy interop can be important.  I am starting to feel inclined to agree that the purposed change could be ok, I will take it up with my team and get back to you.

**Comment by csrl** [comment]
Thank you!

**Comment by IngelaAndin** [comment]
We now have a ticket to solve this that hopefully will make it to our next sprint.
