### ISSUE TITLE
Failing app upgrade in release_hander_1 because of process shutdown

### ISSUE THREAD

**Issue by zsoci** [erlang/otp#5387]
**Describe the bug**
In https://github.com/erlang/otp/issues/3696 there were two places where release handler failed due to a process shutdown. The issue is fixed in https://github.com/erlang/otp/pull/2666

We encountered another place where the same improvement is needed. During release upgrade:
```
release_handler: {'EXIT',{{shutdown,{socket_error,closed,'The socket has been closed.'}},{gen_server,call,[<0.27413.4942>,which_children,infinity]}}}
error during a which_children call to cowboy_tls (<0.27413.4942>). [State: running] Exiting ... 
```

This points to : https://github.com/erlang/otp/blob/master/lib/sasl/src/release_handler_1.erl#L643 where in case the Result is not a list an error is reported and the release upgrade fails.

**Expected behavior**
Release upgrade does not fail when a process shuts down during an upgrade as that process shall not be treated furthermore.

**Affected versions**
All

**Comment by sverker** [comment]
Fix merged to maint for OTP 24.2.
