### ISSUE TITLE
Bind empd port to only ipv4 address with ipv6 disabled

### ISSUE THREAD

**Issue by polaris-alioth** [erlang/otp#5394]
**Is your feature request related to a problem? Please describe.**

To bind epmd port to specific ip, we need export ERL_EPMD_ADDRESS.
If we **compile erlang in ipv6 system.** It will bind port to ipv6 address.
However, if we **disabled ipv6**, epmd will start failed.
 
**Describe the solution you'd like**
We can compile one binary which can run on both ipv4 and ipv6 system.

**Describe alternatives you've considered**
Add a new environment to control socket binding. 
`
SET_ADDR6(address, in6addr_loopback, sport);
`
like this:
```
    if (g->inet6_flag == 1) {
    SET_ADDR6(address, in6addr_loopback, sport);
    salen = sizeof(struct sockaddr_in6);
    connect_sock = socket(AF_INET6, SOCK_STREAM, 0);
    if (connect_sock>=0) {
    if (connect(connect_sock, (struct sockaddr*)&address, salen) == 0)
	return connect_sock;
    close(connect_sock);
    }
```

**Additional context**

**Comment by weiss** [comment]
I guess this is addressed by commit e8c9e121c1b286ecddd572190c2a1fe72adc97bb, so this issue can be closed?
