### ISSUE TITLE
[Question] - About AWS EC2 performance 

### ISSUE THREAD

**Issue by mobilemindtec** [erlang/otp#5416]
Hello,

I don't know if this would be the right place, but I've done a lot of research on my problem and still can't solve it.

I have a web application running with OTP 21 (Chicagoboss) using docker swarm. When I run this application on my local machine, its processing consumption is very low. However, when I run the same docker on an EC2 t3a.xlarge server the consumption is very high, exceeding 100% CPU usage at all times.

I tried to add some parameters in vm.args

``` 
+sbwt none
+sbwtdcpu none
+sbwtdio none
+sfwi 0
+scl false
-smp
``` 

This had little effect. This application is 90% idle, and occasionally processes something that arrives using a crontab library.

The process that consumes processing is beam.smp.

Do you have an explanation for this behavior? 

Thanks!

**Comment by max-au** [comment]
Shameless plug for https://erlangforums.com/ - I think it's more appropriate to ask the question there...

**Comment by mobilemindtec** [comment]
Ok, thanks!

**Comment by vans163** [comment]
EC2 instances are multi tenant, beam does not run well on them. Try using the dedicated/singleuser EC2 instances.
