### ISSUE TITLE
Dialyzer error messages render binary literals/patterns/types differently to the original source

### ISSUE THREAD

**Issue by TD5** [erlang/otp#5429]
**Describe the bug**
Dialyzer error messages print snippets of binary literals/patterns/types in a normalized way, rather than the format in which it was given in the source code. This can lead to confusion as to whether the error message really does refer to the code snippet in question, since the error message snippet's formatting doesn't match the source.

**To Reproduce**

When Dialyzer analyzes this code:
```
-spec foo() -> ok.
foo() ->
    case foo of
      <<"bar">> -> ok;
      _ -> ok
    end.
```

it gives this error:
```
The pattern <<6447474:24>> can never match the type 'foo'
```

Notice how the binary appears as `<<"bar">>` in the source, but appears as `<<6447474:24>>` in the snippet in the error message. I think these both correspond to the same binary, so in some sense this is "technically correct", but potentially quite confusing since they don't _look_ the same.

**Expected behavior**
I'd expect the error message to use the same format as the source code, i.e. the error would be something like this:

```
The pattern <<"bar">> can never match the type 'foo'
```

**Affected versions**
HEAD of erlang/OTP right now, but I think this has been around for a fair while.

**Additional context**
Arguably this is as much a feature request as it is a bug, in that the current output is not strictly "wrong". However, in my experience, Dialyzer users see a different rendering of the binary, and wonder whether they're looking at the correct source code or not. Happy to relabel this as a feature request or otherwise as people deem appropriate.

In terms of implementing a fix, as I understand it, the issue stems from [pretty printing the core Erlang](https://github.com/erlang/otp/blob/master/lib/dialyzer/src/dialyzer.erl#L724), where knowledge of the way in which the binary pattern was expressed in the source code has been lost. `pattern_match` errors are detected in [`dialyzer_dataflow.erl`](https://github.com/erlang/otp/blob/master/lib/dialyzer/src/dialyzer_dataflow.erl#L1360), so we'd need accurate source location information or an annotation with a high-fidelity representation of the original source here. With recent changes to improve location information in terms, perhaps this is more feasible now than it was in the past?

**Comment by bjorng** [comment]
In the linked pull request, I have fixed what I consider a bug in the compiler. This bug fix will make the generated message slightly less confusing:
```
The pattern <<98,97,114>> can never match the type 'foo'
```
I don't see any easy way to improve pretty printing beyond that. For this particular we could add an heuristic in the pretty printing that would see if all characters in a binary looks like printable character and convert back to the string representation. More involved would be for the compiler to add annotations to the Core Erlang code that would help Dialyzer to pretty print it more accurately. I don't expect that we will have time to do that for OTP 25 (but we hope to do some other improvements to Dialyzer in OTP 25).

**Comment by TD5** [comment]
Thanks for that quick turnaround, @bjorng! The `<<98,97,114>>` does indeed seem less confusing, so that's solid improvement 👍
