### ISSUE TITLE
Inconsistent error messages when errors are optimized away by the compiler

### ISSUE THREAD

**Issue by josevalim** [erlang/otp#5440]
**Describe the bug**

Take this code:

```erlang
-module(foo).
-compile(export_all).

example1() ->
  try
     atom_to_binary(11111)
  catch
     error:Error:Stacktrace ->
        erlang:display({Error, Stacktrace})
  end.

example2(Binary) ->
  try
     atom_to_binary(Binary)
  catch
     error:Error:Stacktrace ->
        erlang:display({Error, Stacktrace})
  end.
```

The functions above will raise different error messages in the shell. I assume this happens because the actual function call is eliminated by the compiler in `example1`:

```erlang
1> foo:example1().
{badarg,[{foo,example1,0,[{file,"foo.erl"},{line,6}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,689}]},{shell,exprs,7,[{file,"shell.erl"},{line,686}]},{shell,eval_exprs,7,[{file,"shell.erl"},{line,642}]},{shell,eval_loop,3,[{file,"shell.erl"},{line,627}]}]}
true
2> foo:example2(1111).
{badarg,[{erlang,atom_to_binary,[1111],[{error_info,#{module=>erl_erts_errors}}]},{foo,example2,1,[{file,"foo.erl"},{line,14}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,689}]},{shell,exprs,7,[{file,"shell.erl"},{line,686}]},{shell,eval_exprs,7,[{file,"shell.erl"},{line,642}]},{shell,eval_loop,3,[{file,"shell.erl"},{line,627}]}]}
```

**Expected behavior**

I thought I would open up the issue for discussion as it would be nice if both messages were the same for consistency. Perhaps the simplest way is to not remove the problematic call, even if the error is found at compile time? Another idea is to inline the relevant `error_info` in the call site too.

However, I can also see that the consistency between the messages may not really be a strong requirement, so feel free to close this. :)

**Affected versions**

Since the fantastic EEP 54 was added. :)

**Comment by bjorng** [comment]
> Perhaps the simplest way is to not remove the problematic call, even if the error is found at compile time?

Yes, I think that is harmless.

I think this change to the compiler is safe enough that I can do it in `maint` for OTP 24.2.

**Comment by bjorng** [comment]
I've created a pull request.
