### ISSUE TITLE
M1 Max Performance Issues

### ISSUE THREAD

**Issue by jwaldrip** [erlang/otp#5465]
**Describe the bug**
While most other applications seem to be excelling on my 64GB M1 Max, the BEAM seems to be running about 10 times slower. It also seems to only be using the first 2 cores.

**To Reproduce**
Install and run a BEAM application on an M1 Max.

**Expected behavior**
I expect it to perform fast.

**Affected versions**
24.x

**Comment by garazdawi** [comment]
As we don't have access to any M1 Max (that I know) we need more information to go on in order to help. Could you post:

1. The build log
2. How do you measure the slowdown?
3. What HW/OS do you run the comparison on that runs 10 times faster?

**Comment by jwaldrip** [comment]
@garazdawi there is a pretty good thread talking about it on the elixir forum, it just hasn't been posted here yet. https://elixirforum.com/t/erlang-and-elixir-on-apple-silicon-m1-chip/35699/40 see the note about only seeing two active cores while compiling.
