### ISSUE TITLE
Documentation about filters in generators is not in sync with actual behavior

### ISSUE THREAD

**Issue by ilya-klyuchnikov** [erlang/otp#5470]
**Describe the bug**
Documentation - https://www.erlang.org/doc/reference_manual/expressions.html#list-comprehensions - states that "A filter is an expression, which evaluates to true or false."
However, - it is possible to have filters returning other values (eg integers).

**To Reproduce**
```erlang
2> L = [true, false, 1, 2, 3].
[true,false,1,2,3]
3> [X || X <- L, X].
[true]
```

Obviously, the filter `X` in the comprehension evaluates to integers without any runtime errors (or compile errors).

**Expected behavior**
Documentation matching actual runtime behavior

**Comment by michalmuskala** [comment]
It's kind of more complicated because the behaviour differs depending if the expression is a guard-safe expression or not:

```erl
1> Id = fun(X) -> X end.
#Fun<erl_eval.44.40011524>
2> L = [true, false, 1, 2, 3].
[true,false,1,2,3]
3> [X || X <- L, X].
[true]
4> [X || X <- L, Id(X)].
** exception error: bad filter 1
```
