### ISSUE TITLE
git clone failed on windows

### ISSUE THREAD

**Issue by polaris-alioth** [erlang/otp#5474]
**Describe the bug**
git clone otp project failed on windows with the following error.
```
error: unable to create file lib/stdlib/test/shell_docs_SUITE_data/unknown_erlang_*_2_func.txt: Invalid argument
error: unable to create file lib/stdlib/test/shell_docs_SUITE_data/unknown_erlang_<_2_func.txt: Invalid argument
error: unable to create file lib/stdlib/test/shell_docs_SUITE_data/unknown_erlang_=<_2_func.txt: Invalid argument
error: unable to create file lib/stdlib/test/shell_docs_SUITE_data/unknown_erlang_>=_2_func.txt: Invalid argument
error: unable to create file lib/stdlib/test/shell_docs_SUITE_data/unknown_erlang_>_2_func.txt: Invalid argument
Updating files: 100% (11865/11865), done.
fatal: Could not reset index file to revision 'HEAD'
```
Because the file name contains special character which is illegal on windows. 
#5226

**To Reproduce**
git  clone https://github.com/erlang/otp.git

**Comment by garazdawi** [comment]
Thanks for the report! I don't have access to a windows machine, so can you test and see if the fix in pr #5480 works? You should be able to do:

```
git clone -b lukas/stdlib/fix-shelldocs-test-windows-clone https://github.com/garazdawi/otp
```

**Comment by polaris-alioth** [comment]
It works, I checkout successfully on windows
```
$ git clone -b lukas/stdlib/fix-shelldocs-test-windows-clone https://github.com/garazdawi/otp
Cloning into 'otp'...
remote: Enumerating objects: 424678, done.
remote: Total 424678 (delta 0), reused 0 (delta 0), pack-reused 424678
Receiving objects: 100% (424678/424678), 389.98 MiB | 533.00 KiB/s, done.
Resolving deltas: 100% (339787/339787), done.
Checking out files: 100% (11910/11910), done.
```

**Comment by polaris-alioth** [comment]
It works, I checkout successfully on windows

$ git clone -b lukas/stdlib/fix-shelldocs-test-windows-clone https://github.com/garazdawi/otp
Cloning into 'otp'...
remote: Enumerating objects: 424678, done.
remote: Total 424678 (delta 0), reused 0 (delta 0), pack-reused 424678
Receiving objects: 100% (424678/424678), 389.98 MiB | 533.00 KiB/s, done.
Resolving deltas: 100% (339787/339787), done.
Checking out files: 100% (11910/11910), done.

**Comment by garazdawi** [comment]
Fix merged, thanks for reporting and testing.
