### ISSUE TITLE
Bitstring Spec in Documentation doesn't reflect compiler behaviour

### ISSUE THREAD

**Issue by artman41** [erlang/otp#5476]
**Describe the bug**
The docs describe a spec for bitstring which doesn't seem to be followed by the compiler.

[Docs](https://www.erlang.org/doc/reference_manual/typespec.html#types-and-their-syntax):
![image](https://user-images.githubusercontent.com/5568965/144418448-9e3bc885-62ca-493a-bf17-8510bcf80321.png)

Compiler:
![image](https://user-images.githubusercontent.com/5568965/144418412-9f227ab2-2f38-4e9f-88be-be4cd50880c6.png)

**To Reproduce**
Write code using the specs `<<_:M1, _:M2>>` or `<<_:M*N>>` or `<<_:_*N>>`

**Expected behavior**
The given spec can be compiled

**Affected versions**
22.3, 24.1, possibly others

**Comment by kostis** [comment]
You are reading the docs wrongly.  Read them again. 
In particular, `*` is a _literal_, not regular expression syntax.

You cannot write `<<_:M1, _:M2>>` (if there is a `,`, there needs to be a `_:_*N` afterwards).
Similarly, you cannot write `<<_:M*N>>`; you need to write `<<_:_*N>>`.
