### ISSUE TITLE
"remsh" does not appear to work on Windows

### ISSUE THREAD

**Issue by lukebakken** [erlang/otp#5501]
**Describe the bug**

When attempting to connect to another node on a Windows system, `remsh` does not work.

**To Reproduce**

* Terminal 1 -

```
erl -sname node1
```

* Terminal 2

```
erl -sname node2 -remsh node1
```

Output:

```
C:\Users\bakkenl> erl -sname node2 -remsh node1
Eshell V12.1.5  (abort with ^G)
(node2@bakkenl-z01)1>
```

Expected is to see `node1@bakkenl-z01` in the shell prompt. This is the `epmd` info at the time the above two nodes are running:

```
C:\Users\bakkenl> C:\tools\erl-24.1.7\erts-12.1.5\bin\epmd.exe -names
epmd: up and running on port 4369 with data:
name node2 at port 64487
name node1 at port 64484
```

Arguments to each node are correct:

```
(node1@bakkenl-z01)1> init:get_arguments().
[{root,["C:\\tools\\erl-24.1.7"]},
 {progname,["erl"]},
 {home,["C:\\Users\\bakkenl"]},
 {sname,["node1"]}]
(node1@bakkenl-z01)2> erlang:get_cookie().
'JSKGQLYGTEMZAEVMEHJB'
```

```
(node2@bakkenl-z01)2> init:get_arguments().
[{root,["C:\\tools\\erl-24.1.7"]},
 {progname,["erl"]},
 {home,["C:\\Users\\bakkenl"]},
 {sname,["node2"]},
 {remsh,["node1"]}]
(node2@bakkenl-z01)4> erlang:get_cookie().
'JSKGQLYGTEMZAEVMEHJB'
```

**Expected behavior**

On WSL (Ubuntu) and Arch Linux, the output is as follows (copied from a `tmux` session):

```
lbakken@shostakovich ~                                                                      │lbakken@shostakovich ~
$ erl -sname node2 -remsh node1                                                             │$ erl -sname node1
Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] │Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
                                                                                            │
Eshell V12.1.5  (abort with ^G)                                                             │Eshell V12.1.5  (abort with ^G)
(node1@shostakovich)1>                                                                      │(node1@shostakovich)1>
```

**Affected versions**

`24.1.7` (I have not yet tested other versions)

**Additional context**

Windows 10 version - `21H1`

**Comment by garazdawi** [comment]
This is the same issue as #4220, but manifested in a different way.

The `-remsh` command only works if using "newshell", which on windows means that you have to run `werl.exe`.

**Comment by lukebakken** [comment]
@garazdawi thank you, that is indeed it.

> The -remsh command only works if using "newshell"

Is this documented and I missed it? If not, I'll open a PR to document it.

**Comment by garazdawi** [comment]
No, I don’t think it is documented. So a pr to the erl documentation would be great!

**Comment by lukebakken** [comment]
@garazdawi I took a stab at a "Note" for Windows. Let me know what you think.
