### ISSUE TITLE
Provide better stacktraces for errors in erl_eval

### ISSUE THREAD

**Issue by josevalim** [erlang/otp#5526]
Today, if there is an error on the expression being evaluated, there is very little information about where said exception happened and I would like to improve this.

**Describe the solution you'd like**

A simple way we could achieve this is to wrap each external call in a try/catch and reraise any exception with the additional stacktrace empty. However, I have some concerns with this approach:

  1. `erl_eval` currently does not have the file, which makes it impossible to assemble any kind of stacktrace.

  2. Wrapping all external function applications in try/catch may make code that does not care about the stacktrace slower.

  3. `erl_eval` still raises its own exceptions (case clauses errors, match errors, etc) that are outside of the external function handler.

We could add the `File` as an argument to `erl_eval`, and maybe additional flags to control how the stacktrace would look like, but it may be simpler to allow users to control this behaviour instead. This could be done with two relatively small changes:

  1. Allow the `ExternalFunction` to be a function of arity 4, in the shape of `Fun(Ann, Mod, Fun, Args)`. This way, as a user of `erl_eval`, I can pass my own `ExternalFunction` and add the relevant try/catch. `Ann` is the `erl_anno:anno()` of the node from where I can access additional information such as line in case I need to build a stacktrace.

  2. Change `erl_eval` to dispatch all of its internal errors (case clause error, match error, etc) through the external handler too (which, per the item above, will also include `Ann`). In other words, instead of `erlang:error(error, Reason, ?STACKTRACE)`, we would do something similar to: `do_apply(Ann, erlang, error, [error, Reason, ?STACKTRACE], Ef, RBn, ...)`.

With those two changes, I should be able to add my stacktrace with a simple function external function as this:

```erlang
File = "this/file/comes/from/somewhere",

ExternalFunction = fun(Ann, Mod, Fun, Args) ->
  try
    apply(Mod, Fun, Args)
  catch
    Kind:Reason ->
      Entry = {Mod, Fun, length(Args), [{file, File}, {line, erl_anno:line(Ann)}]},
      erlang:raise(Kind, Reason, [Entry | ?STACKTRACE])
  end
end.
```

The stacktrace may need some munging but that's precisely the point, I will have the flexibility to do so. :D

**Additional context**

I will be glad to implement this. I am looking for an initial thumbs up if this direction is acceptable. Thank you! 🎄

**Comment by bjorng** [comment]
Seems reasonable. Looking forward to a pull request.

**Comment by josevalim** [comment]
Closing in favor of the PR.
