### ISSUE TITLE
`file` module doesn't export some types

### ISSUE THREAD

**Issue by jolonf** [erlang/otp#5530]
**Describe the bug**
I'm writing a piece of software that uses `code:get_doc/1` to get the function signatures from Erlang modules. I'm starting with the `file` module and there are some type definitions which are not included in the `get_doc` results. These are: `posix_file_advise`, `delete_option`, `send_file_option`, and `file_info_option`. This basically makes it impossible to fully describe the functions. 

Interestingly these types are in the docs, however they are explicitly placed there using the `<type>` tag, and all the other types do not appear in `<type>` tags. E.g.:

https://github.com/erlang/otp/blob/fbb4f69861fedbee1e0cf19dab325782820068c2/lib/kernel/doc/src/file.xml#L191

It seems that the above types have been overlooked in being added to `export_type`:

https://github.com/erlang/otp/blob/fbb4f69861fedbee1e0cf19dab325782820068c2/lib/kernel/src/file.erl#L71-L72

Related to #5422 which I believe is also a case of not exporting all types.

**Affected versions**
OTP/24

**Comment by jolonf** [comment]
I've written an Elixir script which processes the docs from all of the kernel modules and finds any types not exported but referenced by exported functions in the module.

The script is available here: https://github.com/jolonf/find_private_types

I've also uploaded the current output from the script which contains all of the types not exported for each module: https://github.com/jolonf/find_private_types/blob/main/private_types.txt

For convenience I've also pasted the output here (note that I haven't manually verified all of these):

```
Module: application
[:application_spec]

Module: code
[:add_path_ret, :loaded_filename]

Module: disk_log
[:notify_ret, :block_error_rsn, :chunk_ret, :bchunk_ret, :close_error_rsn,
 :inc_wrap_error_rsn, :dlog_info, :lclose_error_rsn, :log_error_rsn, :open_ret,
 :dlog_options, :reopen_error_rsn, :sync_error_rsn, :trunc_error_rsn,
 :unblock_error_rsn]

Module: erpc
[:caught_call_exception]

Module: error_logger
[:open_error]

Module: file
[:posix_file_advise, :delete_option, :sendfile_option]

Module: global
[:method, :retries, :trans_fun]

Module: global_group
[:info_item]

Module: logger
[:config_handler]

Module: net_adm
[:verbosity]

Module: seq_trace
[:component, :value, :tracer]

Module: wrap_log_reader
[:chunk_ret, :open_ret]
```

**Comment by garazdawi** [comment]
Hello!

In the Erlang version of the EEP-48 doc chunks, the information about those types is placed in the module metadata. When the renderer of the docs sees this:

```erlang
[{ul,[{class,<<"types">>}],
  [{li,[{name,<<"posix_file_advise">>}],[]}]}
```

It should lookup the named type in the `types` field of the module metadata. This is done [here](https://github.com/erlang/otp/blob/master/lib/stdlib/src/shell_docs.erl#L937-L943) in the shell docs implementation for Erlang and described in the [EEP-48: Implementation in Erlang/OTP](https://www.erlang.org/doc/apps/erl_docgen/doc_storage.html#erlang-documentation-extra-metadata) chapter in the Erl_Docgen User's Guide.

**Comment by garazdawi** [comment]
The reason why they are not exported is that we only export the types that are needed by the user. However, types are still good for documentation purposes so even if they are not exported they may be documented.

Of course, what "needed by the user" means is different to everyone so we are not as consistent as we could be with what is exported and what is not.

**Comment by jolonf** [comment]
Great, thanks! I had missed the metadata at the top.

I will close this issue.
