### ISSUE TITLE
erl_drv_mutex_create crash in debug mode when name is NULL

### ISSUE THREAD

**Issue by silviucpp** [erlang/otp#5539]
**Describe the bug**

Calling `erl_drv_mutex_create(NULL) when VM is compiled in DEBUG mode it's causing a segmentation fault`

**To Reproduce**
just call `erl_drv_mutex_create(NULL)` in debug mode.

**Expected behavior**
Should work in the same way as in release mode.

**Affected versions**
OTP 24+ (also last master)

**Additional context**

In debug mode seems the VM is using `ERTS_ENABLE_LOCK_CHECK` which cause the following call to be executed (which is not in release mode):

```
#ifdef ERTS_DYN_LOCK_CHECK
erts_dlc_create_lock(&dmtx->dlc, name);
#endif
```

And here seems it's using variable `name` instead `dmtx->name` which in case `name` is `NULL` it's value is equal with `no_name` which basically is equal with string "unknown".

**Comment by rickard-green** [comment]
The string is mandatory. Passing NULL has never been supported.

**Comment by silviucpp** [comment]
@rickard-green this is not that clear from the code. 2 lines above you have:

```
if (name) {
	    dmtx->name = ((char *) dmtx) + sizeof(ErlDrvMutex);
	    sys_strcpy(dmtx->name, name);
        } else {
	    dmtx->name = no_name;
	}
```

**Comment by rickard-green** [comment]
Yes that is true. The documentation has however always stated that it should be passed a string. I suppose it would be harmless to support NULL, though. I'll change the state of this issue to an enhancement and set it in help wanted. That is, we are not going to change it, but a PR changing it is welcome.

**Comment by sverker** [comment]
I think I would prefer keeping the lock name mandatory and if anything remove the `if (name)` stuff.

The dynamic lock checker uses the lock name to determine and check locking order. By accepting NULL as "noname" you practically disable the dynamic lock checker.

**Comment by rickard-green** [comment]
@sverker ok, then I take what I said above back :-) Perhaps we should also verify that name is non-NULL and let erl_drv_mutex_create() fail if it is NULL. Probably not in a patch though, but for OTP 25. I'll leave it in the help-wanted state for those changes.
