### ISSUE TITLE
Issue with make install on Intel Edison board - Yocto 3.10.17-poky

### ISSUE THREAD

**Issue by leondavi** [erlang/otp#5545]
**Describe the bug**
I get the following errors when running make install (make command finishes without any error): 
```
/mnt/microSD/Downloads/otp_src_24.2/erts/autoconf/install-sh: hdlt_ssl_client_cert.pem does not exist.
Makefile:99: recipe for target 'release_spec' failed
make[5]: *** [release_spec] Error 1
make[5]: Leaving directory '/mnt/microSD/Downloads/otp_src_24.2/lib/inets/examples/httpd_load_test'
/mnt/microSD/Downloads/otp_src_24.2/make/otp_release_targets.mk:232: recipe for target 'release' failed
make[4]: *** [release] Error 2
make[4]: Leaving directory '/mnt/microSD/Downloads/otp_src_24.2/lib/inets/examples/httpd_load_test'
/mnt/microSD/Downloads/otp_src_24.2/make/otp_subdir.mk:29: recipe for target 'release' failed
make[3]: *** [release] Error 2
make[3]: Leaving directory '/mnt/microSD/Downloads/otp_src_24.2/lib/inets/examples'
/mnt/microSD/Downloads/otp_src_24.2/make/otp_subdir.mk:29: recipe for target 'release' failed
make[2]: *** [release] Error 2
make[2]: Leaving directory '/mnt/microSD/Downloads/otp_src_24.2/lib/inets'
/mnt/microSD/Downloads/otp_src_24.2/make/otp_subdir.mk:29: recipe for target 'release' failed
make[1]: *** [release] Error 2
make[1]: Leaving directory '/mnt/microSD/Downloads/otp_src_24.2/lib'
Makefile:1127: recipe for target 'install.libs' failed
make: *** [install.libs] Error 2
```

**To Reproduce**
Build from source Erlang OTP on Yocto 

**Expected behavior**
make install should finish successfully. 

**Affected versions**
24.2 - latest

**Additional context**
OS release: 3.10.17-poky-edison
Intel Edison board 
OpenSSL 1.0.1j 15 Oct 2014
gcc (GCC) 4.8.2
g++ (GCC) 4.8.2
ncurses-devel 6.1

**Comment by garazdawi** [comment]
Hello!

Could can you attach the output from the entire build, that is what is printed from `./configure && make && make install`.

**Comment by leondavi** [comment]
[make_run.txt](https://github.com/erlang/otp/files/7768404/make_run.txt)
[make_install_run.txt](https://github.com/erlang/otp/files/7768405/make_install_run.txt)
[configure_run.txt](https://github.com/erlang/otp/files/7768406/configure_run.txt)

**Comment by garazdawi** [comment]
The file that it fails to install is a soft link to another file located in `lib/inets/test/`. Could it be that your system has some special handling of soft-links, or that the file is missing for any other reason?

**Comment by leondavi** [comment]
[run_make_release_tests.txt](https://github.com/erlang/otp/files/7769452/run_make_release_tests.txt)

**Comment by leondavi** [comment]
There is an option to skip these tests part when running make install? 
I can run erl from compile bin without any issue.

**Comment by garazdawi** [comment]
> Is there an option to skip these tests part when running make install?

The files in question are not test files, but example files that are installed together with Erlang to help development. They are also included in our tests because we need to make sure the examples work. So, no they cannot be skipped.

One thing you could do is to disable building of the `inets` application completely if you do not need it. You do this by passing `--without-inets` to configure. 

Besides that there is not much I can help with without having access to the same environment as you. You will need to dig into what is special about the environment. Maybe the people that maintain [meta-erlang](https://github.com/meta-erlang/meta-erlang) know something?

**Comment by garazdawi** [comment]
Closing this. Feel free to re-open if you have any other problems.

**Comment by joaohf** [comment]
Hello @leondavi

I just saw this right now. Did you tried meta-erlang (https://github.com/meta-erlang/meta-erlang) before ? if you are still having problems, could you open an issue in meta-erlang github repo ? I can help.

Thanks
