### ISSUE TITLE
RFC 5424 logger formatter

### ISSUE THREAD

**Issue by hauleth** [erlang/otp#5562]
**Is your feature request related to a problem? Please describe.**

Syslog is one of the most popular centralised logging formats out there. It is standardised by the [RFC 5424 "Syslog protocol"](https://datatracker.ietf.org/doc/html/rfc5424) and used by many OSes as a default system logging facility.

**Describe the solution you'd like**

There should be `logger_rfc5424_formatter` that would log messages accordingly to the mentioned above RFC.

**Describe alternatives you've considered**

This one would be easily implemented as an external library, however due to the fact that syslog is so popular format that is supported on almost any platform I think it would be useful for the end-users to have such feature available OotB.

**Additional context**

Related to #5561

**Comment by garazdawi** [comment]
As you say, an RFC 5424 logger would work great as an external library and I think that is the best approach to take. If the implementation becomes popular we may consider including it later.
