### ISSUE TITLE
Add is_local_pid/1 as a guard function

### ISSUE THREAD

**Issue by okeuday** [erlang/otp#5568]
**Is your feature request related to a problem? Please describe.**
This idea may have already been mentioned in the past, I am not sure.  However, it would be beneficial for Erlang in two separate ways:

* A guard expression could use `is_local_pid(Pid)` instead of `node() =:= node(Pid)` (or `is_local_pid(Pid) =:= false` instead of `node() /= node(Pid)`) as a more efficient check.  Most usage in Erlang of the `node/0` function has likely been for this check (my opinion, I haven't done a source code search to support that view).
* The `is_local_pid/1` guard function would provide a way to avoid using the `node/0` function in guard expressions.  Guard expressions could avoid side-effects (i.e., be referentially transparent) if the `node/0` function wasn't allowed in guard expressions.  As has been mentioned in the past, the `node/0` function as a guard function is problematic because it is a read of global state that is allowed to change, even though command-line arguments may prevent it from changing during the VM's execution.  I understand the `node/0` function may not change to not be a guard function in the future due to legacy source code, but the `is_local_pid/1` guard function could provide an alternative to avoid `node/0` use.

**Describe the solution you'd like**
The addition of the `erlang` module `is_local_pid/1` guard function.

**Describe alternatives you've considered**
It would be the best alternative to `node() =:= node(Pid)` in guard expressions.

**Comment by michalmuskala** [comment]
Wouldn't `is_local_pid` be not referentially transparent either? Depending where it is executed - locally or remote, it would produce different result.

**Comment by okeuday** [comment]
@michalmuskala `is_local_pid` would only use the Pid data to determine if it is local.  So, it is a read of Pid memory in the local VM to determine whether it exists in the data there.  The operation is referentially transparent because the VM is ensuring all Pids are unique.  The C source code would be a simplified version of `erlang:is_process_alive/1`:
https://github.com/erlang/otp/blob/f8e41f8553239fb02598ef6c019cdb8a174d4eea/erts/emulator/beam/erl_bif_info.c#L3683-L3722

**Comment by ranjanified** [comment]
sure I'm confused about the `referential transparency` thing... and you guys definitely can help me understand it better...

What if I interpret it this way that the function application of `is_local_pid`, given a `Pid`, is dependent upon some state of the instance of the VM, and the result can vary depending upon that state... which makes this function application `referentially opaque`.

Am I on the right track or something is missing on my part??

**Comment by okeuday** [comment]
@ranjanified wikipedia describes it well: ["An expression is called referentially transparent if it can be replaced with its corresponding value (and vice-versa) without changing the program's behavior."](https://en.wikipedia.org/wiki/Referential_transparency)

**Comment by ranjanified** [comment]
Thanks @okeuday ... I think I mixed it up with `idempotency`. Thanks for the link.

**Comment by rickard-green** [comment]
We do not want to introduce yet another guard BIF unless it is really important. We do not see this as important. In order to be consistent we would in this case also have to introduce `is_local_reference()` and `is_local_port()` (instead introducing an `is_local()` that accepts pids, ports and references could however be an alternative to that).

The implementation can not be made much more efficient than it already is. The VM internal `is_internal_pid()` macro is not equivalent to `is_pid(Pid), node() == node(Pid)`. In order to behave as `is_pid(Pid), node() == node(Pid)` it would have to do the same thing as `is_pid(Pid), node() == node(Pid)` internally. That is, you would only reduce the amount of guard bif calls.

**Comment by okeuday** [comment]
@rickard-green Your response is slightly disturbing because you say "We do not see this as important.".  The `erlang:node/0` guard function has been a long-term defect in the Erlang programming language.  I understand the Erlang/OTP team likely has many other priorities that are focused on avoiding any changes to existing functions (to avoid breaking existing source code), but it should be important to consider future improvements to Erlang/OTP (even if they require changing existing functions).

The Erlang Language Specification describes why `erlang:node/0` should not be a guard function: ["The guard tests and their constituent guard expressions (syntactic category GuardExpr) have been chosen so that they are independent of the state (i.e., their result depends exclusively on their arguments), have no side effect and (with a few exceptions) take O(1) time (with respect to the size of their arguments)."](https://github.com/erlang/spec/blob/0d70db4d904c45678cb46de8f0f0f93eb35c66f3/src/es-notation.tex#L862-L867).  I understand "side effect" may not be clearly defined by many people when the term is used, but I do have a list of the types of side effects as it [relates to a separate programming language (i.e., ATS v2 would view the `erlang:node/0` side effect as `!ref`)](https://github.com/CloudI/CloudI/blob/develop/src/api/ats/v2/cloudi.sats#L98-L111).

To earnestly follow the `is_local_pid/1` direction of avoiding the use of `erlang:node/0` in guard expressions would be slightly worse than what you have described because we would want 6 new guard functions instead of 3, to ensure a type check is always used.  That would mean adding:

    is_local_pid/1,  is_local_port/1,  is_local_reference/1  for is_*(Term), node() =:= node(Term)
    is_remote_pid/1, is_remote_port/1, is_remote_reference/1 for is_*(Term), node() /= node(Term)

I would want to avoid considering `is_local/1` and `is_remote/1` due to its type ambiguity (types help us avoid errors).

Joe Armstrong's thesis stressed the importance of naturally avoiding side-effects with the Erlang programming language in his analysis of ["clean" and "dirty" modules in the AXD301 source code](https://erlang.org/download/armstrong_thesis_2003.pdf#page=183).  His description of side-effects in Erlang includes what he considered dangerous: ["The dangerous side-effects are those which change the concurrency structure of the applications, thus modules which call the link, unlink, spawn or spawn_link, primitives must be carefully checked.  Even more dangerous is code that might evaluate halt or processes-- I would assume that such code is very carefully checked."](https://erlang.org/download/armstrong_thesis_2003.pdf#page=186).  The side-effects of `erlang:node/0` are the same as `erlang:processes/0` because they both are reads of global state that is allowed to change.  The potential for `erlang:node/0` to change its value will only increase with the addition of the ["Dynamic node name improvements" pull request](https://github.com/erlang/otp/pull/5623) source code.

The other aspect of this direction (of avoiding `erlang:node/0`) to consider is that if `erlang:node/0` is not allowed in guard expressions, it should be simpler to have compiler optimizations (mainly in JIT) of all guard expressions everywhere because you would always know guard expressions are referentially transparent (it would be peephole optimizations to combine operations based on constant arguments in the function call path).

So, I would hope the Erlang/OTP team would reconsider this approach to avoiding `erlang:node/0` in guard expressions.
