### ISSUE TITLE
ERL-1224: Erlang OTP64 EXE Missing Properties is closed without actually being resolved

### ISSUE THREAD

**Issue by inikulshin** [erlang/otp#5582]
#4232

I wrote some comments in this bug few days ago, but it seems like no one reads comments in closed bugs. :)

**Comment by dgud** [comment]
Not many of us works in holidays, and it nice to want things and we can't comment or prioritize every wish.
Make a PR if you want things.

Not anywhere in the original request was the installers mentioned :-/

**Comment by inikulshin** [comment]
@dgud , I read that bug again, and I'm still sure it is about **Windows installer**.

**OTP64 Windows EXE binary** is a very strange description for `erl.exe`, but fits `otp_win64*.exe` much better.

Also, it mention **Chocolatey**, which is a manager for **installers**.

**Comment by KennethL** [comment]
@inikulshin, can you please explain the use case in more details so I(we)
understand how Chocolately is using the file metadata.
I would also like to understand how and when Chocolately is used in this
case.

**Comment by inikulshin** [comment]
@KennethL I'm not familiar with Chocolatey, so I asked the community help.

http://disq.us/p/2lv0he9

**Comment by OnorioCatenacciAAMP** [comment]
As far as I know (I used to maintain the Chocolatey Package for Erlang and probably will be again when I get a few spare cycles) Chocolatey doesn't care about file metadata.  If it does care about metadata that's news to me. FWIW.

**Comment by inikulshin** [comment]
@OnorioCatenacciAAMP so, do you think the [original bug](https://github.com/erlang/otp/issues/4232) creator meant for?
`erl.exe` or `otp_win64*.exe`?

What is the "dynamic discovery of the binary version"?

**Comment by OnorioCatenacciAAMP** [comment]
I have no idea.  Sounds like they want to be able to grab the version of the binary from the binary.  But I don't know of anything in Chocolatey that uses that.  Maybe some notion of being able to programmatically build the CNG package?

**Comment by lukebakken** [comment]
@inikulshin - see the NSIS documentation and open a PR to modify this file:

https://github.com/erlang/otp/blob/master/erts/etc/win32/nsis/erlang20.nsi

https://nsis.sourceforge.io/Examples/VersionInfo.nsi

**Comment by KennethL** [comment]
We close this issue since we don't have a clear use case for when this meta data is needed. Welcome back with a PR together with a convincing use case.

**Comment by inikulshin** [comment]
@KennethL 

Are you agree #4232 is talking about `otp_win64*.exe` and not about `erl.exe` and was closed **by mistake**?
If you are agree (and from your last comment I think you are), please **reopen** it.

After the #4232 is reopened, @lukebakken 's comment should be copied to it, and the #4232 should remain opened until the fixing PR is pulled.

**Comment by OnorioCatenacciAAMP** [comment]
You can reopen the issue if you wish but as far as I can tell that metadata is not needed by Chocolatey NuGet.

**Comment by inikulshin** [comment]
@KennethL 

Are you agree #4232 is talking about `otp_win64*.exe` and not about `erl.exe` and was closed **by mistake**?
If you are agree (and from your last comment I think you are), please **reopen** it.

After the #4232 is reopened, @lukebakken 's comment should be copied to it, and the #4232 should remain opened until the fixing PR is pulled.


VERSIONINFO is not mandatory for executables, and this info proves nothing (e.g. if it is not malicious software). But it is good practice to fill it.
The issue has a very minor priority, but it exists and should be fixed someday.

We (Varonis) deploy Erlang and we need to manage a text file with internal version (e.g. 12.1.5) next to OTP to support upgrades.
