### ISSUE TITLE
erlang:display/1 errored output for large maps

### ISSUE THREAD

**Issue by pehuen-rodriguez** [erlang/otp#5585]
**Describe the bug**
When given a map of size > 32, `erlang:display/1` will print out the map incorrectly formatted and including some garbage. `erlang:display/1` implementation for [large maps](https://www.erlang.org/doc/efficiency_guide/maps.html#how-large-maps-are-implemented) seems to be missing or incorrect.

**To Reproduce**
`35>` shows a **working** example of 32 positions. `36>` is how to reproduce it: a Map with size 33
```
35> erlang:display(maps:from_list([{K, v} || K <- lists:seq(1, 32)])).
#{1=>v,2=>v,3=>v,4=>v,5=>v,6=>v,7=>v,8=>v,9=>v,10=>v,11=>v,12=>v,13=>v,14=>v,15=>v,16=>v,17=>v,18=>v,19=>v,20=>v,21=>v,22=>v,23=>v,24=>v,25=>v,26=>v,27=>v,28=>v,29=>v,30=>v,31=>v,32=>v}
true
36> erlang:display(maps:from_list([{K, v} || K <- lists:seq(1, 33)])).
#<fffb>{<1201>{[16|v],[18|v],[5|v]},<4400>{[19|v],[27|v]},<80>{<4080>{[10|v],[24|v]}},<14>{[4|v],[21|v]},<240>{[22|v],[17|v]},<2a>{[3|v],[8|v],[1|v]},<8512>{[7|v],[2|v],[14|v],[15|v],[20|v]},[13|v],[6|v],<1400>{[28|v],[25|v]},<212>{[32|v],[9|v],[11|v]},[31|v],[26|v],<2040>{[30|v],<8020>{[29|v],[23|v]}},<8200>{[12|v],[33|v]}}
true
```

**Expected behavior**
Output should be a correctly shaped map.

**Affected versions**
OTP 23~24. Elder versions: not sure

**Comment by garazdawi** [comment]
That output is the internal representation of large maps, so it is correct. I believe it was done this way for large maps because when debugging the implementation of large maps it was very useful to know the internal details of the data structure.

I'm unsure how easy it is to fix the printing logic to print a normal map for large maps as the entire implementation for `erlang:display` has to be in C.

**Comment by pehuen-rodriguez** [comment]
Thank you @garazdawi for the clarification! So it's not a bug but an inconsistency and a counter-intuitive result, you'd say?

Assuming the large maps implementation is stable, I do agree we should consider modifying that printing logic. As it is in C, I couldn't propose a patch myself.

**Comment by garazdawi** [comment]
> So it's not a bug but an inconsistency and a counter-intuitive result, you'd say?

yes, something like that.

> Assuming the large maps implementation is stable, I do agree we should consider modifying that printing logic. As it is in C, I couldn't propose a patch myself.

I don't think fixing this will be high priority for us. So if someone else wants to try to do it the code is located here: https://github.com/erlang/otp/blob/master/erts/emulator/beam/erl_printf_term.c#L723-L769

**Comment by josevalim** [comment]
I took a stab at documenting this behaviour here: https://github.com/erlang/otp/pull/5633
