### ISSUE TITLE
filename:basedir(user_log,...) documentation and implementation disagree

### ISSUE THREAD

**Issue by leoliu** [erlang/otp#5605]
**Describe the bug**
As suggested in the title

**To Reproduce**
```
> filename:basedir(user_log, "my_application", #{os=>darwin}).
"[HOME]/Library/Logs/my_application"
```

But The example on the reference manual says:
"[HOME]/Library/Caches/my_application"

**Expected behavior**
They should agree.

**Affected versions**
24.2

**Comment by garazdawi** [comment]
Fixed in #5616
