### ISSUE TITLE
lists:uniq

### ISSUE THREAD

**Issue by meox** [erlang/otp#5606]
Seems that an important function is missing in the `lists` module: `unique`
The `uniq` function should takes a list and returns the unique elements from that list preserving the order.

Possible implementation:

```erlang
uniq([]) ->
  [];
uniq(List) when is_list(List) ->
  uniq(List, []).

uniq([], Acc) ->
  lists:reverse(Acc);
uniq([H | Tail], Acc) ->
  case lists:member(H, Acc) of
    true ->
      uniq(Tail, Acc);
    false ->
      uniq(Tail, [H | Acc])
  end.
```

**Comment by vkatsuba** [comment]
Or this can looks like

```erlang
uniq([]) ->
    [];
uniq([H|T]) ->
    [H | [X || X <- uniq(T), H /= X]].
```
:upside_down_face:

**Comment by meox** [comment]
Is just me or could be helpful to have it in the stdlib?

**Comment by dgud** [comment]
Whats wrong with lists:usort() ?

**Comment by vkatsuba** [comment]
> Whats wrong with lists:usort() ?

Wrong point in changing order of items:
```erlang
1> lists:usort([1,5,1,2]).
[1,2,5]
```
But `uniq/1` should works like:
```erlang
1> lists:usort([1,5,1,2]).
[1,5,2]

**Comment by vkatsuba** [comment]
> Is just me or could be helpful to have it in the stdlib?

This will helpful to all for case if by some reason Erlang Core Team will reject this proposal :upside_down_face:.

**Comment by lisztspace** [comment]
Ignoring order, the following implementation should have lower complexity than the proposed solutions.

```uniq(L) ->
    Put = fun(E, M) -> maps:put(E, true, M) end,
    maps:keys(lists:foldl(Put, #{}, L)).
```
An _order preserving_ implementation using a map to record elements seen could be as follows (consuming stack, but avoiding the call to `lists:reverse/1` in the end).

```
uniq(L) ->
    uniq(L, #{}).

uniq([], _) ->
    [];
uniq([X|Xs], M) ->
    Put = fun(E, M) -> maps:put(E, true, M) end,
    case maps:is_key(X, M) of
	true ->
	    uniq(Xs, M);
	false ->
	    [X| uniq(Xs, Put(X, M))]
    end.
```
Variations on the above possible, e.g., using `lists:foldl/3` or `lists:foldr/3`, but it should be noted that _order preserving_ is not really a unique term in this context.  We need to specify which of the multiples of an element is to be _kept_.  For input `[1,2,2,1]` both `[1,2]` and `[2,1]` preserve order, but the difference is if we keep (in this example) the first or the last instance of a multiple element.

**Comment by paulo-ferraz-oliveira** [comment]
As an example, internally we do have `:unique`, which takes options.

If the options list is `[]`, it calls `lists:usort(List)`. 😄 
If the options list contains `stable` (only possible option, at the moment), it keeps the original order.

From a quick search in most of our codebase I see `stable` being used less than 1% of the time.

**Comment by meox** [comment]
should be better if we use tail recursion?

**Comment by RaimoNiskanen** [comment]
That builds more garbage.

In benchmarks tail recursive often beats body recursive but in a real program it puts more stress on the garbage collector, so it is not obvious which is better.  I prefer body recursive when possible since I believe it degrades less under load.
