### ISSUE TITLE
Add GC/hibernation configurations for supervisors, or even set it to be default option

### ISSUE THREAD

**Issue by zzydxm** [erlang/otp#5608]
**Is your feature request related to a problem? Please describe.**
Supervisors are often mostly idle after being started. Every garbage generated during the start process of the supervisor will stay the whole lifetime of the supervisor.

Especially, supervisor has a progress report of start_child, which calls customized log filters and handlers if it was defined, and that could cause large memory footprint.

After tls_dyn_connection_sup was introduced. Every TLS connection starts a separate supervisor, this caused an issue on us while we have 50k+ connections. Each tls_dyn_connection_sup supervisor holds a 300KB heap, and the summation is 15GB, which makes our service OOM-looping.

**To Reproduce**
erl
logger:set_primary_config(level, info).
logger:add_primary_filter(test, {fun(_, _) -> lists:seq(1, 1000000), ignore end, ok}).
application:ensure_all_started(os_mon).
process_info(whereis(os_mon_sup),[total_heap_size]).

return:
[{total_heap_size,4712239}]

**Expected behavior**
After some time total_heap_size should shrink to negligible.

**Affected versions**
This supervisor behavior existed for a quite long time, but the newly added tls_dyn_connection_sup might easily cause memory issue because of this behavior
https://github.com/erlang/otp/commit/3f8d48a6fa0dd5ccdf6c0d401efca52228af5ca8

**Describe the solution you'd like**

While we can do something on our logging to solve this issue. I think it might be good to add support in supervisor itself to support hibernation with a new API start_link/4, and ideally change most non-dynamic supervisors to hibernate by default.

**Comment by max-au** [comment]
I would be interested in suppressing supervisor progress reports altogether, especially for processes that are expected to be spawned with high intensity (e.g. accepting TLS connections). There is not much value in having those logged anyway.

**Comment by IngelaAndin** [comment]
Note that some supervisor shutdown logs are avoided by adjustment b0f82ee6e721a7bab80cd9b034061459c4b36dc7
that has not been released yet, but will be included in the next OTP-24 patch.  I also agree that supervisor progress reports for the dynamic supervisor processes are not what you want. I think that supervisor progress reports in common ought to be debug-level logging, but this would be changing legacy behavior so it would take some consideration when and if to change it.

**Comment by garazdawi** [comment]
> While we can do something on our logging to solve this issue. I think it might be good to add support in supervisor itself to support hibernation with a new API start_link/4, and ideally change most non-dynamic supervisors to hibernate by default.

We agree that this is a good idea. I've added it to our backlog, but if anyone else wants to help implement this they are most welcome.

**Comment by michalmuskala** [comment]
I think this is a symptom of a larger issue, where processes are frequently forced to periodically hibernate to avoid "holding on" to large heaps.

Perhaps, it would make sense to periodically force GC on each process that was active in that time, but did not trigger a GC? For example, once every minute. I believe, this could automatically solve a large amount of those "manual" interventions without significantly increasing the CPU overhead.
A similar approach is [already used by Go](https://github.com/golang/go/blob/895b7c85addfffe19b66d8ca71c31799d6e55990/src/runtime/proc.go#L4481-L4486), that forces a (global) GC every 2 minutes, even if normally the program wouldn't allocate enough to warrant a collection within that time.

**Comment by garazdawi** [comment]
> Perhaps, it would make sense to periodically force GC on each process that was active in that time, but did not trigger a GC? For example, once every minute. I believe, this could automatically solve a large amount of those "manual" interventions without significantly increasing the CPU overhead.

We have been discussing something similar to this for a very long time and so far our conclusion has been that it cannot be done without "significantly increasing the CPU overhead". It all depends on what you define as a significant increase.

I know of systems that have implemented a similar mechanism themselves, i.e. a process that does `process_info` of all processes in the system and then triggers a GC using some logic of how and when. That seems to work for them, but I don't think that it can be applied as a general solution for everyone.

**Comment by garazdawi** [comment]
> Was the solution to run the GC periodically for all processes, or only for the subset of processes that were scheduled in the particular window, but did not trigger a GC in it?

I can't recall the exact algorithm we were considering, but it did have some sort of limit on what processes were considered.

**Comment by zzydxm** [comment]
> > While we can do something on our logging to solve this issue. I think it might be good to add support in supervisor itself to support hibernation with a new API start_link/4, and ideally change most non-dynamic supervisors to hibernate by default.
> 
> We agree that this is a good idea. I've added it to our backlog, but if anyone else wants to help implement this they are most welcome.

I can add the start_link/4 API and use it in tls_dyn_connection_sup:start_link, it would be a quite simple change. @IngelaAndin do you think this works or you would prefer not to change start_link options? If it works, which hibernation timeout do you think to be appropriate? Would it make sense to do {hibernate_after, 0}? Thanks!

**Comment by potatosalad** [comment]
@zzydxm My opinion: I think since [`supervisor:start_link/2,3` simply calls `gen_server:start_link/3,4`](https://github.com/erlang/otp/blob/340aefb5cdd7aa73a3b9daa1781037334d8c7341/lib/stdlib/src/supervisor.erl#L172-L183), it should probably leave the defaults the same as in `gen_server` (as in: `[]` by default).  I don't think there is a good way to determine whether a supervisor will be dynamic or not _before_ the call to [`Module:init/1`](https://www.erlang.org/doc/man/supervisor.html#Module:init-1), right?

While we're considering the addition of `supervisor:start_link/4`, would it also make sense to add something like `supervisor:enter_loop/*` to mirror the functionality provided by [`gen_server:enter_loop/3,4,5`](https://www.erlang.org/doc/man/gen_server.html#enter_loop-3) and [`gen_statem:enter_loop/4,5,6`](https://www.erlang.org/doc/man/gen_statem.html#enter_loop-4)?

**Comment by zzydxm** [comment]
> @zzydxm My opinion: I think since [`supervisor:start_link/2,3` simply calls `gen_server:start_link/3,4`](https://github.com/erlang/otp/blob/340aefb5cdd7aa73a3b9daa1781037334d8c7341/lib/stdlib/src/supervisor.erl#L172-L183), it should probably leave the defaults the same as in `gen_server` (as in: `[]` by default). I don't think there is a good way to determine whether a supervisor will be dynamic or not _before_ the call to [`Module:init/1`](https://www.erlang.org/doc/man/supervisor.html#Module:init-1), right?

Oh I mean to modify some of the OTP supervisors to use the start_link/4 API with hibernation option, instead of using the start_link/2,3 with default [] option.

> While we're considering the addition of `supervisor:start_link/4`, would it also make sense to add something like `supervisor:enter_loop/*` to mirror the functionality provided by [`gen_server:enter_loop/3,4,5`](https://www.erlang.org/doc/man/gen_server.html#enter_loop-3) and [`gen_statem:enter_loop/4,5,6`](https://www.erlang.org/doc/man/gen_statem.html#enter_loop-4)?

I think it is surely doable, but maybe in a separate stream. What would be the use case of supervisor:enter_loop?

**Comment by josevalim** [comment]
Unless `hibernate_after` is set to 0, which means it runs all the time, won't any other value be prone to "race conditions" in that if the supervisor reports are frequent enough, we won't ever hibernate? If the issue are the reports, then I would say an option to enable/disable the `sasl_reports` is the way to go (and in the future it can default to `false` for `simple_one_for_one`, if desired).

On the other hand, `tls_dyn_connection_sup` is a `one_for_all` supervisor, which means that if it uses 300kb of heap, this data was most likely generated during its initialization? So hibernate/gc once after initalization would most likely yield the benefits necessary here. Is calling `erlang:garbage_collect(self())` something we would be comfortable doing by default for a supervisor? Or should that also require an option?

**Comment by garazdawi** [comment]
> Unless hibernate_after is set to 0, which means it runs all the time, won't any other value be prone to "race conditions" in that if the supervisor reports are frequent enough, we won't ever hibernate?

In a very active supervisor that would indeed be a problem.

>  If the issue are the reports, then I would say an option to enable/disable the sasl_reports is the way to go (and in the future it can default to false for simple_one_for_one, if desired).

You could also add a primary log filter that drop any log messages from that type of supervisor. No need to add an option to disable it.

> On the other hand, tls_dyn_connection_sup is a one_for_all supervisor, which means that if it uses 300kb of heap, this data was most likely generated during its initialization? So hibernate/gc once after initalization would most likely yield the benefits necessary here. Is calling erlang:garbage_collect(self()) after init something we would be comfortable doing by default for a supervisor? Or should that also require an option?

I don't see any reason why we couldn't do that, especially if we can do it at a point where we know that we have very little live data.

**Comment by josevalim** [comment]
> You could also add a primary log filter that drop any log messages from that type of supervisor. No need to add an option to disable it.

My understanding is that there are two possible issues here:

1. the logger work is consuming additional memory
2. the additional reports are verbose

Telling users to setup a filter is a good solution for 2), but I was thinking that we want to the reports altogether because of 1)?

So my thinking is that `ssl` itself would disable the reports altogether for `tls_dyn_connection_sup`, as there is no need to send those reports in the first place? My understanding is that the reports were never there and having them available now is a side-effect of the solution chosen.

The automatic garbage collection would be a secondary alternative to reap the benefits of reduced memory usage for everyone, even if they don't disable the reports.

>  Before adding such a change though I would like to know that this is actually the problem and that this solves it.

Ack! @zzydxm, is this something you could/want to verify?

**Comment by garazdawi** [comment]
> Telling users to setup a filter is a good solution for 2), but I was thinking that we want to the reports altogether because of 1)?

Adding a primary filter should remove a lot (if not all) of the resource overhead of the logging message as the formatted would never be called and it is the most likely culprit to use a lot of memory. As to whether this log message is needed or not for `ssl` I have no idea.

**Comment by josevalim** [comment]
> Before adding such a change though I would like to know that this is actually the problem and that this solves it.

FWIW, here is the simplest experiment I could run. [Livebook](https://github.com/livebook-dev/livebook) is a Phoenix/Elixir app. It has 24 deps (not counting Elixir and OTP apps), not all of them may have supervisors though. I booted it up four times, computed `erlang:memory()`'s, and shut it down. I also applied a patch that immediately garbage collects after the supervisor init.

Before the patch, the memory total were: 40550544, 40151544, 40342664, 40058248.

After the patch, the memory totals were: 39869888, 39760384, 39852984, 39779072.

On average that's a 400Kb saved after boot.

If someone else wants to give it a try:

```diff
diff --git a/lib/stdlib/src/supervisor.erl b/lib/stdlib/src/supervisor.erl
index 6638110ec1..776c140b23 100644
--- a/lib/stdlib/src/supervisor.erl
+++ b/lib/stdlib/src/supervisor.erl
@@ -330,10 +330,14 @@ init({SupName, Mod, Args}) ->
     case Mod:init(Args) of
        {ok, {SupFlags, StartSpec}} ->
            case init_state(SupName, SupFlags, Mod, Args) of
-               {ok, State} when ?is_simple(State) ->
-                   init_dynamic(State, StartSpec);
-               {ok, State} ->
-                   init_children(State, StartSpec);
+        {ok, State} when ?is_simple(State) ->
+            Res = init_dynamic(State, StartSpec),
+            erlang:garbage_collect(self()),
+            Res;
+        {ok, State} ->
+            Res = init_children(State, StartSpec),
+            erlang:garbage_collect(self()),
+            Res;
                Error ->
                    {stop, {supervisor_data, Error}}
            end;
```

**Comment by zzydxm** [comment]
> Ack! @zzydxm, is this something you could/want to verify?

Yes, your patch solves the problem we met.

**Comment by garazdawi** [comment]
> @garazdawi shall I submit a PR?

Yes, please do.

**Comment by josevalim** [comment]
PR sent for the GC problem:  #5632.

**Comment by IngelaAndin** [comment]
> 

I do not think that hibernate after zero makes sense as first the dynamic supervisor is started and then its two children are added. So there should be enough time for the supervisor to start its children before hibernating it.

**Comment by IngelaAndin** [comment]
> And @IngelaAndin, please let me know if you think there should be an option to disable the reports altogether.

@josevalim Well If you want to get rid of all reports I think that is already possible by disabling "SASL-loggs" but maybe it would be nice to be able to just get rid of the progress reports and not the error reports. Correct me if I am wrong @garazdawi

**Comment by garazdawi** [comment]
> Well If you want to get rid of all reports I think that is already possible by disabling "SASL-loggs" but maybe it would be nice to be able to just get rid of the progress reports and not the error reports. Correct me if I am wrong @garazdawi

It is definitely possible to use logger to filter away any progress reports that you are not interested in. I think what José is wondering about is whether the `tsl_dyn_connection_sup` should have progress reports disabled by default?

**Comment by garazdawi** [comment]
> @zzydxm
> 
> > I can add the start_link/4 API and use it in tls_dyn_connection_sup:start_link, it would be a quite simple change. @IngelaAndin >do you think this works or you would prefer not to change start_link options? If it works, which hibernation timeout do you think >to be appropriate? Would it make sense to do {hibernate_after, 0}? Thanks!
> 
> I do not think that hibernate after zero makes sense as first the dynamic supervisor is started and then its two children are added. So there should be enough time for the supervisor to start its children before hibernating it.

I did not know that the `tld_dyn_connection_sup` works like this. Isn't it a bit odd that the solution proposed in #5632 fixes the problem in `tls_dyn_connection_sup` according to @zzydxm?

**Comment by josevalim** [comment]
`tls_dyn_connection_sup` is `one_for_all`, so it should be starting both children on `init`. So `{hibernate_after, 0}` should work too but I feel like doing it by default (or at least GC-ing)  is less surprising and provide benefits in other scenarios.

**Comment by garazdawi** [comment]
Are you sure? [this init function](https://github.com/erlang/otp/blob/master/lib/ssl/src/tls_dyn_connection_sup.erl#L53-L61) does not seem to start any children at all, instead all are added afterward using start_child. Or are we talking about different things?

**Comment by IngelaAndin** [comment]
Yes, the children are started afterward just after starting the supervisor. So my thought was that if we hibernate the supervisor just after we start it we would wake it up again when adding the children!

**Comment by josevalim** [comment]
Oops, my bad. @garazdawi so consider me equally puzzled on why my patch addresses the issue. :)

**Comment by lhoguin** [comment]
Would there be any obvious drawbacks in making all supervisor and top-level application processes hibernate after 60s of complete inactivity by default?

**Comment by garazdawi** [comment]
> Would there be any obvious drawbacks in making all supervisor and top-level application processes hibernate after 60s of complete inactivity by default?

The first one that comes to mind for me is that a timer would have to be created (and canceled) for each of these processes every time they are scheduled out/in. It would depend on how active supervisors are in your system to know if that is a problem or not, though I would suspect that most would consider it a worthwhile tradeoff.

**Comment by michalmuskala** [comment]
The top level application process is a group leader for all processes in the application. This means it will be "woken" up whenever any process inside of the application does `io:format` or uses stdin/stdout some other way. Initial hibernation might make sense to compact the initial state, but I'm not sure about the periodic hibernation.

**Comment by max-au** [comment]
> a timer would have to be created

Given the amount of these short-lived TLS connections (in many cases a connection-per-request is created), it might get expensive. I would rather prefer to suppress progress report logging for TLS altogether. To be honest, I can't recall a single case when logging every TLS connection accepted made sense by default (for debugging, yes, but that can be done at DEBUG log level).

I was going to suggest removing SASL progress logging from `simple_one_for_one` supervisors (as it is expected to spawn many children in a rapid succession). But it won't solve the TLS problem, as the child is also the supervisor (`one_for_all`), and now two progress reports are generated each time a TLS connection is accepted.
Suppressing all SASL progress reports sounds like an interesting option (we can then manually add logging in the children being started). But error reports (crashes) are very important, and I think they should stay on by default.

Except that I would not consider TLS connection termination to be an error. Right now, when a TLS connection terminates before completing the handshake, it generates a log message (and we have elaborate code to suppress specifically that type of an error from TLS).

**Comment by zzydxm** [comment]
> I did not know that the `tld_dyn_connection_sup` works like this. Isn't it a bit odd that the solution proposed in #5632 fixes the problem in `tls_dyn_connection_sup` according to @zzydxm?

Sorry, my fault. I didn't really run it in our prod but rather just read the code. The tls_dyn_connection_sup does start child after init(), so doing GC after init() would not solve the problem, sorry for the mistake.

Sounds like having a proper hibernation time or remove SASL progress logging would better solve the problem.

**Comment by gonzalobf** [comment]
If anyone got here looking how to disable the `tld_dyn_connection_sup` progress message, I have disabled it with the filter below. I couldn't find a better way than pattern matching the log event data:
```erlang
filter_tls_dyn_connection_sup(
    #{
        level := info,
        meta := #{domain := [otp, sasl]},
        msg := {report, #{report := [{supervisor, {_Pid, tls_dyn_connection_sup}}, _]}}
    },
    _
) ->
    stop;
filter_tls_dyn_connection_sup(LogEvent, _) ->
    LogEvent.
    
main() ->
    logger:add_primary_filter(filter_tls_dyn_connection_sup, {fun filter_tls_dyn_connection_sup/2,[]}).
```

**Comment by IngelaAndin** [comment]
I added a backlog item for OTP-27 to not progress report dynamically started supervisors.  And #6895  already part of OTP-26 significantly reduces memory consumption of static supervisors by default.

**Comment by hkrutzer** [comment]
>I added a backlog item for OTP-27 to not progress report dynamically started supervisors.

Was this added to OTP-27? I can't find it in the release notes.
