### ISSUE TITLE
Issue with LTO build of ei

### ISSUE THREAD

**Issue by saleyn** [erlang/otp#5609]
**Describe the bug**
`ei_*` functions are reported as undefined by the linker when linking with `libei.a`.

This issue appears in some builds of the 24.2 release (presently reproduced in Arch Linux and macOS), where `libei.a` is getting built with LTO optimization that results in undefined `ei_*` symbols when linking with that library.

An illustration of this error can be found [here](https://github.com/saleyn/erlexec/issues/155).

Notably, when the OTP 24.2 is compiled locally from sources, this doesn't happen, but when the pre-built package is installed from the distribution of Arch/macOS, and the project containing a port program that depends on `libei.a` is built, undefined symbols are reported.

I believe it boils down to `libei.a` getting compiled with LTO, which is not something that happened in the releases prior to 24.2.

```bash
$ nm /usr/lib/erlang/lib/erl_interface-5.1/lib/libei.a | grep -B2 -A10 ei_connect
nm: ei_connect.o: plugin needed to handle lto object

ei_connect.o:
0000000000000001 C __gnu_lto_slim

ei_resolve.o:
0000000000000001 C __gnu_lto_slim

eirecv.o:
0000000000000001 C __gnu_lto_slim

send.o:
0000000000000001 C __gnu_lto_slim
```
Whereas a locally compiled 24.2 has a different output:
```bash
$ nm /opt/sw/erlang/24.2/lib/erlang/lib/erl_interface-5.1/lib/libei.a | grep ei_connect
ei_connect.o:
0000000000003050 T ei_connect
                 U ei_connect_ctx_t__
0000000000000a40 t ei_connect_helper
0000000000003110 T ei_connect_host_port
0000000000003080 T ei_connect_host_port_tmo
0000000000002e00 T ei_connect_init
0000000000000018 b ei_connect_initialized
0000000000002a50 T ei_connect_init_ussi
0000000000002ef0 T ei_connect_tmo
0000000000002a30 T ei_connect_xinit
0000000000002480 T ei_connect_xinit_ussi
                 U ei_connect_t__
0000000000000910 T ei_connect_ctx_t__
0000000000001360 T ei_connect_t__
```

**Comment by garazdawi** [comment]
Hello! What versions have you tested? I see in the linked issue that you have tried 24.1 and that worked? From what git tells me, we have done zero changes in erl_interface between 24.1 and 24.2, so it seems odd that this is something that we have caused.

Do you know what `CFLAGS` and `LDFLAGS` are being passed to configure?

**Comment by saleyn** [comment]
In the Arch package repository used to build the erlang distribution package we can find:
- [Package content](https://archlinux.org/packages/community/x86_64/erlang/)
- [Package source](https://github.com/archlinux/svntogit-community/blob/packages/erlang/trunk/PKGBUILD)

The last link shows that Erlang was configured with:
```
./configure \
    --enable-builtin-zlib \
    --enable-smp-support \
    --prefix=/usr \
    --with-odbc \
    --with-wx-config=/usr/bin/wx-config-gtk3
```
but I don't see any special assignments to LDFLAGS and CXXFLAGS there aside from:
```
sed -i 's/^LDFLAGS = /LDFLAGS += /g' otp/lib/megaco/src/flex/Makefile.in
sed -i 's/^LDFLAGS =  /LDFLAGS += /g' otp/lib/odbc/c_src/Makefile.in
```
I cannot reproduce this when building locally in my environment from sources, and would think that it's a build issue that needs to be addressed by the maintainer of the Arch package.  However, the user of my erlexec library reported the same issue with a macOS distribution, which makes me think that it could be something related to the version of the gcc compiler/linker which triggers the LTO issue.

**Comment by garazdawi** [comment]
I did some digging and found [this](https://gitlab.archlinux.org/archlinux/rfcs/-/merge_requests/4/diffs#15a936dc6460871af375cc13bd909812867c1c25_0_52) announcement and line 52 in that looks very much as what is happening to the nm output. So I tried to do

```
strip -R .gnu.lto_* -R .gnu.debuglto_* -N __gnu_lto_v1 "/build/lib/erl_interface/obj/x86_64-pc-linux-gnu/libei.a" -o libei.a
```

and then I get an archive that looks just like the `libei.a` distributed by arch linux. I don't think that this is really a problem, as the strip should only remove some unneeded lto information. Can you try to build `erlexec` with a `libei.a` that is stripped using the strip above and see if you get the same problem?

**Comment by saleyn** [comment]
It doesn't look like `strip` is affecting the size of `libei.a` in case of my locally built version 24.2:
```
$ du -b lib/erl_interface/obj/x86_64-pc-linux-gnu/libei.a
814802  lib/erl_interface/obj/x86_64-pc-linux-gnu/libei.a
$ strip -R .gnu.lto_* -R .gnu.debuglto_* -N __gnu_lto_v1 "lib/erl_interface/obj/x86_64-pc-linux-gnu/libei.a" -o libei.a
$ echo $?
0
$ du -b libei.a
814802  libei.a
```

**Comment by garazdawi** [comment]
I forgot to add that you probably need to have the lto flags to configure as well. From what I could understand they are:

```
./configure CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto" LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now" AR=gcc-ar RANLIB=gcc-ranlib
```

**Comment by saleyn** [comment]
When building with these flags, and running `strip` I am able to reproduce this problem with libei.a.

**Comment by garazdawi** [comment]
Can you reproduce the problem if you do not strip? Either way this to me is a problem in arch Linux and not with our build system.

**Comment by saleyn** [comment]
If I don't strip, the problem is not reproducible, but it is, when the `libei.a` is stripped using with the command you provided.

**Comment by saleyn** [comment]
> Either way this to me is a problem in arch Linux and not with our build system.

Since it appears to be an issue in both Arch and macOS repositories, maybe the configure needs to strip `-flto`, and introduce an explicit switch to enable LTO in `erl_interface`, so that the package maintainers don't need to make changes to the way the package has been build?

**Comment by saleyn** [comment]
> Do you know what configure flags were passed to the macOS build? Would be interesting to see how it manifests there and if the same `strip` is needed.

This bug on macOS was reported by @Skoda091, who used `macOS Monterey 12.1`.  I don't have a mac environment to test, and the 24.2 macOS build github action workflows [pass successfully](https://github.com/saleyn/erlexec/runs/4844210503?check_suite_focus=true).

**Comment by saleyn** [comment]
FWIW, added a [bug report](https://bugs.archlinux.org/task/73409) to Arch's makepkg.

**Comment by garazdawi** [comment]
> Also adding CXXFLAGS="-ffat-lto-objects" to configure the erlang package does solve this problem when libei.a is later stripped.

Aha, that makes sense. I didn't know about that option.

**Comment by saleyn** [comment]
The maintainer of erlang Arch Linux package made [this change](https://github.com/archlinux/svntogit-community/blob/packages/erlang/trunk/PKGBUILD#L41), so all should be good with `libei.a` going forward.
