### ISSUE TITLE
erlang:fun_info() return value change at master branch

### ISSUE THREAD

**Issue by shino** [erlang/otp#5617]
**Describe the bug**
erlang:fun_info() for `fun F/A` style differs between master branch 2022-01-18  (commit: 110e69061dccfe5ad687930316b8bd326ef334f9) and 24.2.

**To Reproduce**
- Save the below code as a.erl

```
-module(a).

-export([start/0]).

start() ->
    F = fun foo/0,
    io:format("foo() type: ~p~n", [erlang:fun_info(F, type)]),
    io:format("foo() name: ~p~n", [erlang:fun_info(F, name)]),
    ok.

foo() ->
    ok.
```
- Execute it with master branch OTP 
```
% erlc a.erl && erl -noshell -s a -s init stop
foo() type: {type,local}
foo() name: {name,foo}
```

- Execute it with 24.2
```
% erlc a.erl && erl -noshell -s a -s init stop
foo() type: {type,local}
foo() name: {name,'-fun.foo/0-'}
```
- name differs

**Expected behavior**
I'm not sure which is correct, or both are correct, or this is not-officially-specified-details of Erlang/OTP.

**Affected versions**
git master branch.

**Additional context**
I first noticed this when eunit test case failed when executed with master OTP,
by badmatch at https://github.com/erlang/otp/blob/master/lib/eunit/src/eunit_lib.erl#L391 .
So I'm not sure about "Expected behavior" of fun_info, either fun_info or eunit should be fixed?

This PR may be related? https://github.com/erlang/otp/pull/5542

**Comment by jhogberg** [comment]
Thanks for your report!

This is undocumented so both are correct. `eunit` shouldn't have done this, so I've made a [PR](https://github.com/erlang/otp/pull/5619) that removes the affected functionality. Do you think you can try it out to see if it causes more problems than it solves?

**Comment by shino** [comment]
Thanks a lot for quick reply and fix!
All test cases on my side have passed with your PR branch. Yay!!

**Comment by jhogberg** [comment]
I've merged the fix now, thanks again for your report! :)
