### ISSUE TITLE
Segfault while compiling 24.2 release for linux/amd64

### ISSUE THREAD

**Issue by AndrewDryga** [erlang/otp#5625]
**Describe the bug**
While trying to update our container to Erlang 24.2 we got into a situation where it will never build due to a segfault:
```
#10 1072.2 === Leaving application tftp
#10 1072.2 make[2]: Leaving directory '/usr/src/otp_src_24.2/lib/tftp'
#10 1072.2 make[1]: Leaving directory '/usr/src/otp_src_24.2/lib'
#10 1072.2 make[1]: Entering directory '/usr/src/otp_src_24.2/erts'
#10 1072.3 make[2]: Entering directory '/usr/src/otp_src_24.2/erts/start_scripts'
#10 1072.4  GEN	/usr/src/otp_src_24.2/erts/start_scripts/start_clean.rel
#10 1072.4  GEN	/usr/src/otp_src_24.2/erts/start_scripts/start_sasl.rel
#10 1072.5  GEN	/usr/src/otp_src_24.2/erts/start_scripts/start_all_example.rel
#10 1072.5  GEN	/usr/src/otp_src_24.2/erts/start_scripts/no_dot_erlang.rel
#10 1072.5  GEN	/usr/src/otp_src_24.2/erts/start_scripts/start_clean.script
#10 1072.8 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
#10 1072.8 make[2]: *** [Makefile:84: /usr/src/otp_src_24.2/erts/start_scripts/start_clean.script] Segmentation fault
#10 1072.8 make[2]: Leaving directory '/usr/src/otp_src_24.2/erts/start_scripts'
#10 1072.8 make[1]: *** [Makefile:67: local_setup] Error 2
#10 1072.8 make[1]: Leaving directory '/usr/src/otp_src_24.2/erts'
#10 1072.8 make: *** [Makefile:1070: local_setup] Error 2
------
Dockerfile:26
```

The host used to compile the Erlang is running M1 chip. The compilation would only crash for `linux/amd64` target and it was not happening for Erlang 23.3.4.10 (everything else was the same).

**To Reproduce**
Dockerfile can be found here: https://github.com/Nebo15/alpine-erlang/blob/master/Dockerfile
```
docker buildx use --create
docker buildx build --platform=linux/386,linux/amd64,linux/arm64 --tag "nebo15/alpine-erlang:24.2" ./
```

Any hints if this is an Erlang thing or maybe we should dig into `qemu` issues in Alpine 3.15 and M1 Mac? (For the official Docker container Alpine 3.15 works just fine.)

**Comment by garazdawi** [comment]
When https://github.com/esl/packages was being built, I have a vague recollection of being asked about a similar problem which in the end turned out to be something about docker and qemu. It is a bit odd that it managed to build all `.beam` files but segfaults when the boot scripts are built, but from what I recall that was the same place as the other fault was.

Maybe you can have a look at esl/packages and see if there are any hints about what to do about it there.

**Comment by AndrewDryga** [comment]
@rnewson hi 👋, I'm sorry for poking you out of random but I checked your Dockerfiles and they don't give any tricks to work around segfaults, maybe you can shine some light on this issue?

**Comment by rnewson** [comment]
Hi, Sorry I don't recall having to work around segfaults (or encountering any). The esl/packages scripts for erlang use docker buildx and cross compilation (that is, they always build on the host architecture, for performance reasons). So perhaps avoiding emulation helps avoid some causes of segfaults during compilation?

**Comment by rnewson** [comment]
glancing at your dockerfile and it seems you might be attempted cross compilation too. A mistake there could explain things. In yours you set `--build` and in mine I set `--host`. I think the definitions of those terms, for GCC cross compile, are a little unintuitive;

```
the build platform on which the compilation is performed, and the host platform on which the resulting executable is expected to run
```

I found that the cross compilation toolkit did the right thing if I told it only the target system (with `--host`). You control the build architecture with how you invoke docker.

**Comment by AndrewDryga** [comment]
Thank you @rnewson, I'll give it a try ❤️.

**Comment by garazdawi** [comment]
> Should we close this issue though? I looks like an issue with docker `buildx` and `qemu`..

Yes, I think so. There is not much that we can do to help this. If you do find a solution though, please make a note here so that anyone else that comes across this will now what to do.

**Comment by garazdawi** [comment]
https://erlangforums.com/t/otp-25-0-rc3-release-candidate-3-is-released/1317/24 turns out that the problem is a bug/feature of qemu. Not much that we can do about it without compromising the security of all JIT nodes, so if you want this to work, the fix should be in qemu.
