### ISSUE TITLE
Improve `base64` performance

### ISSUE THREAD

**Issue by dlesl** [erlang/otp#5639]
**Is your feature request related to a problem? Please describe.**
The `base64` module does not perform very well which can be a bit of a bottleneck given the widespread use of base64 encoding. 

**Describe the solution you'd like**
A C implementation would much faster, especially for large inputs . Given the ubiquitous nature of base64 encoding, my opinion is it would make sense to implement this as a BIF in OTP. This could be a significant performance win for many applications.

**Describe alternatives you've considered**
Alternatively, users could use one of the NIF implementations available. This has some disadvantages, the biggest being that a lot of libraries use base64 and in many cases it would not be reasonable or desirable for libraries to pull in a NIF as a dependency.

**Additional context**
A quick [benchmark](https://github.com/dlesl/b64_nif/blob/cbd602c9d7af64fcad1dfca1d136c43866f08602/bench.erl), and the [results](https://github.com/dlesl/b64_nif/blob/cbd602c9d7af64fcad1dfca1d136c43866f08602/README.md#benchmarks). For a large input, a NIF was >200x faster for both encoding and decoding.

**Comment by nickva** [comment]
Another common `base64` encoding format is `base64` with a url and filename safe alphabet [RFC 3548](https://datatracker.ietf.org/doc/html/rfc3548#section-4).

Apache CouchDB uses NIF for it as https://github.com/apache/couchdb-b64url. It would be great to have a BIF for it as well.

**Comment by michalmuskala** [comment]
I wonder how the Erlang implementation and the NIFs compare to the [elixir implementation](https://hexdocs.pm/elixir/Base.html#decode64/2) which is pretty well optimised. Perhaps there's no reason going all the way to the NIF, if an efficient pure Erlang implementation can be provided (especially with the new JIT).

**Comment by garazdawi** [comment]
I do not think that we are interested in including a native base64 implementation in Erlang/OTP, but we are always interested in making the current Erlang implementation faster :)

We have spent quite some time optimizing the current implementation, but that was before the JIT, and also optimizations the compiler does have improved, so what is fast may have changed.

**Comment by dlesl** [comment]
@michalmuskala Thanks for the tip about the Elixir implementation. Unfortunately it seems to perform almost identically to the erlang implementation:

<details>
<summary>bench.erl</summary>
<p>

```erlang
-module(bench).

-mode(compile).

-define(F(F), {??F, F}).

main([]) ->
  Data100B = crypto:strong_rand_bytes(100),
  Data1MB = crypto:strong_rand_bytes(1024 * 1024),
  io:format("== Testing with 100 B ==~n"),
  test_encode(Data100B, 1_000_000),
  test_decode(Data100B, 1_000_000),
  io:format("~n== Testing with 1 MB ==~n"),
  test_encode(Data1MB, 1000),
  test_decode(Data1MB, 1000).

test_encode(Data, Iterations) ->
  Encoded = base64:encode(Data),
  [test(Fun, Data, Encoded, Iterations)
   || Fun <- [?F(fun base64:encode/1), ?F(fun 'Elixir.Base':encode64/1), ?F(fun b64fast:encode64/1), ?F(fun b64_nif:encode/1)]].

test_decode(Data, Iterations) ->
  Encoded = base64:encode(Data),
  [test(Fun, Encoded, Data, Iterations)
   || Fun <- [?F(fun base64:decode/1), ?F(fun(A) -> {ok, Res} = 'Elixir.Base':decode64(A), Res end), ?F(fun b64fast:decode64/1), ?F(fun b64_nif:decode/1)]].

test({Name, F}, Input, Expected, Iterations) ->
  %% Check that the fun works
  Expected = F(Input),
  {Time, ok} = timer:tc(fun() -> run_test(F, Input, Iterations) end),
  Millis = Time div 1000,
  io:format("~s: ~B iterations in ~B ms: ~B it/sec~n", [Name, Iterations, Millis, Iterations * 1000 div Millis]).

run_test(_Fun, _Input, 0) ->
  ok;
run_test(Fun, Input, Iterations) ->
  Fun(Input),
  run_test(Fun, Input, Iterations - 1).
```

</p>
</details>

<details>
<summary>Results</summary>
<p>

```
== Testing with 100 B ==
fun base64 : encode / 1: 1000000 iterations in 2332 ms: 428816 it/sec
fun 'Elixir.Base' : encode64 / 1: 1000000 iterations in 2223 ms: 449842 it/sec
fun b64fast : encode64 / 1: 1000000 iterations in 758 ms: 1319261 it/sec
fun b64_nif : encode / 1: 1000000 iterations in 240 ms: 4166666 it/sec
fun base64 : decode / 1: 1000000 iterations in 2441 ms: 409668 it/sec
fun ( A ) -> { ok , Res } = 'Elixir.Base' : decode64 ( A ) , Res end: 1000000 iterations in 2359 ms: 423908 it/sec
fun b64fast : decode64 / 1: 1000000 iterations in 770 ms: 1298701 it/sec
fun b64_nif : decode / 1: 1000000 iterations in 277 ms: 3610108 it/sec

== Testing with 1 MB ==
fun base64 : encode / 1: 1000 iterations in 23447 ms: 42 it/sec
fun 'Elixir.Base' : encode64 / 1: 1000 iterations in 24244 ms: 41 it/sec
fun b64fast : encode64 / 1: 1000 iterations in 585 ms: 1709 it/sec
fun b64_nif : encode / 1: 1000 iterations in 83 ms: 12048 it/sec
fun base64 : decode / 1: 1000 iterations in 23857 ms: 41 it/sec
fun ( A ) -> { ok , Res } = 'Elixir.Base' : decode64 ( A ) , Res end: 1000 iterations in 29180 ms: 34 it/sec
fun b64fast : decode64 / 1: 1000 iterations in 514 ms: 1945 it/sec
fun b64_nif : decode / 1: 1000 iterations in 103 ms: 9708 it/sec
```

</p>
</details>

@garazdawi I understand that it's desirable to keep it in erlang, but I'm not sure how much speedup we'd reasonably be able to achieve here. I really think that in this case a native implementation might be worth it, like with the zlib module for example.

**Comment by seriyps** [comment]
@dlesl I wonder how benchmark results would differ between OTP-24 and OTP-23, to see how is it affected by JIT

**Comment by dlesl** [comment]
I ran all of the above on OTP-24. It seems the JIT does make a big difference, since OTP-23 is ~2x slower:
<details>
<summary>Benchmarks</summary>
<p>

OTP-23
```
erlang:system_info(version): "11.2.2.9"
== Testing with 100 B ==
fun base64:encode/1: 1000000 iterations in 5705 ms: 175284 it/sec
fun b64fast:encode64/1: 1000000 iterations in 782 ms: 1278772 it/sec
fun b64_nif:encode/1: 1000000 iterations in 299 ms: 3344481 it/sec
fun base64:decode/1: 1000000 iterations in 4594 ms: 217675 it/sec
fun b64fast:decode64/1: 1000000 iterations in 723 ms: 1383125 it/sec
fun b64_nif:decode/1: 1000000 iterations in 289 ms: 3460207 it/sec

== Testing with 1 MB ==
fun base64:encode/1: 1000 iterations in 57624 ms: 17 it/sec
fun b64fast:encode64/1: 1000 iterations in 678 ms: 1474 it/sec
fun b64_nif:encode/1: 1000 iterations in 77 ms: 12987 it/sec
fun base64:decode/1: 1000 iterations in 46839 ms: 21 it/sec
fun b64fast:decode64/1: 1000 iterations in 669 ms: 1494 it/sec
fun b64_nif:decode/1: 1000 iterations in 717 ms: 1394 it/sec
```

OTP-24 on same machine
```
erlang:system_info(version): "12.1.5"
== Testing with 100 B ==
fun base64:encode/1: 1000000 iterations in 2272 ms: 440140 it/sec
fun b64fast:encode64/1: 1000000 iterations in 746 ms: 1340482 it/sec
fun b64_nif:encode/1: 1000000 iterations in 230 ms: 4347826 it/sec
fun base64:decode/1: 1000000 iterations in 2440 ms: 409836 it/sec
fun b64fast:decode64/1: 1000000 iterations in 761 ms: 1314060 it/sec
fun b64_nif:decode/1: 1000000 iterations in 269 ms: 3717472 it/sec

== Testing with 1 MB ==
fun base64:encode/1: 1000 iterations in 24007 ms: 41 it/sec
fun b64fast:encode64/1: 1000 iterations in 575 ms: 1739 it/sec
fun b64_nif:encode/1: 1000 iterations in 81 ms: 12345 it/sec
fun base64:decode/1: 1000 iterations in 23798 ms: 42 it/sec
fun b64fast:decode64/1: 1000 iterations in 522 ms: 1915 it/sec
fun b64_nif:decode/1: 1000 iterations in 98 ms: 10204 it/sec
```

</p>
</details>

**Comment by max-au** [comment]
I agree with @nickva - adding `urlsafe` option would be really nice. To a degree that I might take a stab at it.

**Comment by dlesl** [comment]
I did a bit of investigation into how other runtimes handle this. I like the idea of something like python's `binascii` module -- it could be useful in other places, like base 16 encoding in `io_lib` for example.

| Platform           | Implementation                                                                                               | Time to encode 1 MB (ms) |
|--------------------|--------------------------------------------------------------------------------------------------------------|--------------------------|
| Erlang (24)        | [Erlang](https://github.com/erlang/otp/blob/master/lib/stdlib/src/base64.erl)                                | 30.1                     |
| Ruby (3.0)         | [C](https://github.com/ruby/ruby/blob/e5319dc9856298f38aa9cdc6ed55e39ad0e8e070/pack.c)                       | 2.5                      |
| Python (3.9)       | [C](https://github.com/python/cpython/blob/main/Modules/binascii.c)                                          | 2.3                      |
| JS (Node v16.13.0) | [Probably C?](https://github.com/nodejs/node/blob/e46c680bf2b211bbd52cf959ca17ee98c7f657f5/src/base64-inl.h) | 1.89                     |
| DotNet (5)         | [C#](https://github.com/microsoft/referencesource/blob/master/mscorlib/system/convert.cs)                    | 1.6                      |
| JVM (OpenJDK 11)   | [Java](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/Base64.java)         | 1.5                      |

<details>
<summary>Details</summary>

```sh
$ nix-shell -p erlangR24 --run erl
Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]

Eshell V12.1.5  (abort with ^G)
1> F = fun() -> Bytes = crypto:strong_rand_bytes(1024 * 1024), {Time, _} = timer:tc(base64, encode, [Bytes]), Time / 1000.0 end.
#Fun<erl_eval.45.65746770>
2> F().
30.096
3> F().
66.559
4> F().
31.572
5> F().
32.321
6> F().
32.357
7> F().
33.453
```

```sh
$ nix-shell -p ruby_3_0 --run irb
irb(main):001:0> require 'securerandom'
=> true
irb(main):002:0> require 'base64'
=> true
irb(main):003:0> require 'benchmark'
=> true
irb(main):004:0> bytes = SecureRandom.random_bytes(1024 * 1024); nil
=> nil
irb(main):005:0> puts Benchmark.measure { Base64.encode64 bytes }
  0.002474   0.000049   0.002523 (  0.002504)
=> nil
irb(main):006:0> puts Benchmark.measure { Base64.encode64 bytes }
  0.010612   0.002067   0.012679 (  0.012674)
=> nil
irb(main):007:0> puts Benchmark.measure { Base64.encode64 bytes }
  0.011648   0.001065   0.012713 (  0.012713)
=> nil
irb(main):008:0> puts Benchmark.measure { Base64.encode64 bytes }
  0.008653   0.003987   0.012640 (  0.012639)
=> nil
irb(main):009:0> puts Benchmark.measure { Base64.encode64 bytes }
  0.011584   0.000050   0.011634 (  0.011627)
=> nil
```

```sh
$ nix-shell -p python39 --run 'python -mtimeit -s "import os; import base64; data = os.urandom(1024 * 1024)" "base64.b64encode(data)"' 
100 loops, best of 5: 2.32 msec per loop
```

```sh
$ nix-shell -p nodejs_latest 'clojure.override { jdk = openjdk17;}' --run "$(cat <<EOF
clj -Sdeps '{:deps {org.clojure/clojurescript {:mvn/version "1.10.597"}}}' -M -m cljs.main -re node
EOF
)"
ClojureScript 1.10.597
cljs.user=> (def crypto (js/require "crypto"))
#'cljs.user/crypto
cljs.user=> (defn random-bytes [size] (.randomBytes crypto size))
#'cljs.user/random-bytes
cljs.user=> (dotimes [_ 100] (let [b (random-bytes (* 1024 1024))] (time (.toString b "base64"))))
<snip>
"Elapsed time: 1.889449 msecs"
"Elapsed time: 1.823829 msecs"
"Elapsed time: 2.417049 msecs"
"Elapsed time: 2.055916 msecs"
"Elapsed time: 1.875932 msecs"
nil
```

```sh
➜  ~ nix-shell -p dotnet-sdk_5 rlwrap --run 'cd $(mktemp -d); dotnet new tool-manifest; dotnet tool install --local Clojure.Main; rlwrap --always-readline dotnet Clojure.Main'
The template "Dotnet local tool manifest file" was created successfully.
You can invoke the tool from this directory using the following commands: 'dotnet tool run Clojure.Main' or 'dotnet Clojure.Main'.
Tool 'clojure.main' (version '1.10.0') was successfully installed. Entry is added to the manifest file /run/user/1000/tmp.eVuOsnusJO/.config/dotnet-tools.json.
Clojure 1.10.0
user=> (defn random-bytes [size] (let [b (byte-array size)] (.GetBytes (System.Security.Cryptography.RandomNumberGenerator/Create) b) b))
#'user/random-bytes
user=> (dotimes [_ 100] (let [b (random-bytes (* 1024 1024))] (time (System.Convert/ToBase64String b))))
<snip>
"Elapsed time: 1.6929 msecs"
"Elapsed time: 1.6797 msecs"
"Elapsed time: 1.6115 msecs"
"Elapsed time: 1.646 msecs"
"Elapsed time: 3.6063 msecs"
nil

```

```sh
$ nix-shell -p 'clojure.override { jdk = openjdk17;}' --run clj                                                                                                             
Clojure 1.10.3
user=> (defn random-bytes [size] (let [b (byte-array size)] (.nextBytes (java.security.SecureRandom.) b) b))
#'user/random-bytes
user=> (dotimes [_ 100] (let [b (random-bytes (* 1024 1024))] (time (.encode (java.util.Base64/getEncoder) b))))
<snip>
"Elapsed time: 1.516793 msecs"
"Elapsed time: 1.611691 msecs"
"Elapsed time: 8.211678 msecs"
"Elapsed time: 1.517201 msecs"
"Elapsed time: 1.493902 msecs"
nil
```

</details>

**Comment by seriyps** [comment]
@bjorng would it make sense to re-open/re-create this ticket as an opportunity for JIT optimizations instead of it being a ticket about rewriting `base64` as BIF?

**Comment by seriyps** [comment]
I tried to run `base64:encode/1` and `base64:decode/1` under `perf` on OTP-24.1. Seems most of the time is spent in [`erts_bs_append`](https://github.com/erlang/otp/blob/340aefb5cdd7aa73a3b9daa1781037334d8c7341/erts/emulator/beam/erl_bits.c#L1395) and [`erts_new_bs_put_integer`](https://github.com/erlang/otp/blob/340aefb5cdd7aa73a3b9daa1781037334d8c7341/erts/emulator/beam/erl_bits.c#L799), so, inside the instructions, not in code dispatcher

<details>

```erlang

-module(benchmark).

-mode(compile).
-export([main/1]).

main([]) ->
  Data100B = crypto:strong_rand_bytes(100),
  Data1MB = crypto:strong_rand_bytes(1024 * 1024),
  io:format("== Testing with 100 B ==~n"),
  test_encode(Data100B, 1_000_000),
  test_decode(Data100B, 1_000_000),
  io:format("~n== Testing with 1 MB ==~n"),
  test_encode(Data1MB, 1000),
  test_decode(Data1MB, 1000).

test_encode(Data, Iterations) ->
  Encoded = base64:encode(Data),
  [test(Fun, Data, Encoded, Iterations)
   || Fun <- [fun base64:encode/1]].

test_decode(Data, Iterations) ->
  Encoded = base64:encode(Data),
  [test(Fun, Encoded, Data, Iterations)
   || Fun <- [fun base64:decode/1]].

test(Fun, Input, _Expected, Iterations) ->
  %% Check that the fun works
  %% Expected = Fun(Input),
  erlang:garbage_collect(),
  {Time, ok} = timer:tc(fun() -> run_test(Fun, Input, Iterations) end),
  Millis = Time div 1000,
  io:format("~p: ~B iterations in ~B ms: ~B it/sec~n", [Fun, Iterations, Millis, Iterations * 1000 div Millis]).

run_test(_Fun, _Input, 0) ->
  ok;
run_test(Fun, Input, Iterations) ->
  Fun(Input),
  run_test(Fun, Input, Iterations -  #1).
```
`ERL_FLAGS="+JPperf true +S 1" perf record --call-graph lbr escript benchmark.erl`
</details>

![image](https://user-images.githubusercontent.com/422014/151834895-f3e67a2d-dbc9-47d7-a948-065a8f12b9c1.png)

![out](https://user-images.githubusercontent.com/422014/151835210-feb75128-6254-452e-98ff-ed18b9a19180.svg)

**Comment by bjorng** [comment]
> would it make sense to re-open/re-create this ticket as an opportunity for JIT optimizations instead of it being a ticket about rewriting base64 as BIF?

Yes, it does.

> I tried to run base64:encode/1 and base64:decode/1 under perf on OTP-24.1.

That seems to confirm that the optimizations we were thinking of would improve performance of `base64`.
