### ISSUE TITLE
do mnesia:write operation inside caller process ??

### ISSUE THREAD

**Issue by Rustixir** [erlang/otp#5641]
hi. 

(in disc_copies / ram_copies mode) 

do mnesia:write operation inside caller process ?? 
or send request to parent ets process  ??

and also

ets itself default access_mode is **protected**
if mnesia default create ets table with protected !!
how mnesia:write caller can access to table ??

**Comment by dgud** [comment]
We will not answer questions here, this is for reporting bugs and feature requests.
Use [erlangforums.com](https://www.erlangforums.com) for questions.

**Comment by vans163** [comment]
> hi.
> 
> (in disc_copies / ram_copies mode)
> 
> do mnesia:write operation inside caller process ?? or send request to parent ets process ??
> 
> and also
> 
> ets itself default access_mode is **protected** if mnesia default create ets table with protected !! how mnesia:write caller can access to table ??

Not encouraging using ticket tracker as a QnA but it sends a msg to the mnesia process for the write. The mnesia process then write to ets and log but not to disk, it decides when to write to disk based on the log threshold
