### ISSUE TITLE
filelib:find_source/1 fails for some OTP modules

### ISSUE THREAD

**Issue by tsloughter** [erlang/otp#5655]
**Describe the bug**

`filelib:find_source` will fail to find the source file of modules even in OTP because it does not search all the places source modules are in OTP applications like `public_key` which has modules in `asn1/`

**To Reproduce**

```
> filelib:find_source("<path to erlang install>/lib/public_key-1.11/ebin/PKCS-FRAME.beam").`
{error,not_found}
```

**Expected behavior**

Expected result is to return the source path:

```
{ok,"<path to erlang>/lib/public_key-1.11/asn1/PKCS-FRAME.erl"}
```

**Affected versions**

`filelib:find_source` was introduced in OTP-20.

**Additional context**

I ended up running into this due to warnings given by `systools` `exref` option when building releases with `relx` that include the `public_key` application. See https://github.com/erlang/rebar3/discussions/2531 -- there are issues open about as well this I believe.

This problem partly arises because they include src in the release and relx copies only certain dirs where src files should be https://github.com/erlware/relx/blob/main/src/rlx_assemble.erl#L219-L231

Because of these warnings I looked into a way to get all source dirs for an application (aside from doing a `filelib:wildcard("**/*.erl")` -- well something similar, it would need to be more complicated to ignore stuff like `test/*.erl` and `examples/*.erl`). 

So a side issue is it'd be nice if either all OTP applications generated source to `src` instead of a dir like `asn1` or to have a way to get the dirs where source is from for the modules in an Application consistently.

**Comment by garazdawi** [comment]
> So a side issue is it'd be nice if either all OTP applications generated source to src instead of a dir like asn1 or to have a way to get the dirs where source is from for the modules in an Application consistently.

I think it makes sense to move the source files in public_key and then add a test that makes sure that `filelib:find_source/2` can find all source files in an Erlang/OTP release.

Can you use the [Kernel source search rules](https://www.erlang.org/doc/man/kernel_app.html#source_search_rules) to work around the issue for older releases?

**Comment by tsloughter** [comment]
Oh, I forgot about those, does that make it possible to say you want all `.erl` files for all `.beam` files in `ebin/` only? I think it does if I remember correctly, since it is for matching. That'd make it so I could say to look at any directory, `**`, which includes stuff like `test/` and `examples/`, and not have issues since those dirs won't have beams that are also found in the `ebin` of the application.

**Comment by garazdawi** [comment]
In #5669 I've fixed `filelib:find_source/1` to always find a source file for all `.beam` files in Erlang/OTP using the default search path. The change involved some changes that I did not want to release in a patch release, so the fix will be part of Erlang/OTP 25.

**Comment by tsloughter** [comment]
Great :+1:
