### ISSUE TITLE
Incorrect documentation about overloading of function specs

### ISSUE THREAD

**Issue by ilya-klyuchnikov** [erlang/otp#5663]
**Describe the bug**
[A clear and concise description of what the bug is.](https://www.erlang.org/doc/reference_manual/typespec.html#specifications-for-functions

"A current restriction, which currently results in a warning (not an error) by the compiler, is that the domains of the argument types cannot overlap. For example, the following specification results in a warning:"

`erlc` doesn't  perform these checks.

**Expected behavior**
Either completely remove the phrase about restrictions - since the compiler doesn't impose any restrictions there, or provide clearer guidance/recommendations when to use and when NOT to use overloaded specs.

**Comment by bjorng** [comment]
Dialyzer will give a warning, so I changed the text to indicate that.
