### ISSUE TITLE
`seq_trace:set_token/2` and `erlang:seq_trace/2` type missmatch

### ISSUE THREAD

**Issue by kren1** [erlang/otp#5667]
**Describe the bug**
`seq_trace:set_token/2` and `erlang:seq_trace/2` have missmatching types in the second argument.

**To Reproduce**
Run dialyzer on 

```
seq_trace:set_token(label, {new_proc, 123})
```

Dialyzer complains with:
```
The call seq_trace:set_token ('label', {'new_proc', _}) will never return since it differs in the 2nd argument from the success typing arguments: (atom(), boolean() | [] | integer() | {integer(), integer()})
```

**Expected behavior**
The code seems to work, so I expect no dialyzer warning

**Affected versions**
Tested on Erlang/OTP 25 , but probably earlier too

**Additional context**

[seq_trace:set_token/2](https://github.com/erlang/otp/blob/master/lib/kernel/src/seq_trace.erl#L46)
uses the this type as second argument:
```
-type value()      :: (Label :: term())
                    | {Previous :: non_neg_integer(),
                       Current :: non_neg_integer()}
                    | (Bool :: boolean()).
  ```
but if you look at the code, it just calls [erlang:seq_trace/2](https://github.com/erlang/otp/blob/master/lib/kernel/src/seq_trace.erl#L70) with the same arguments:

which has the [following type](https://github.com/erlang/otp/blob/master/erts/preloaded/src/erlang.erl#L1892):
erlang:seq_trace/2
```
      P2 :: boolean() | {integer(), integer()} | integer() | [].
 ```
and dialyzer infers the type of seq_trace:set_token/2 to the more specific one, which makes sense.

**Comment by jhogberg** [comment]
Thanks for your report, this has been fixed in the upcoming `OTP-24.3` release. :)
