### ISSUE TITLE
How to access Client certificate in resumed sessions using TLS1.3 session resumption?

### ISSUE THREAD

**Issue by Elimira** [erlang/otp#5671]
I've implemented a TLS1.3 stateless server which receives resumed sessions using session resumption feature

My problem space is, in part of our server side logic, we need to retrieve client certificate per each TLS connection request (regardless of whether it's a full-handshake request or resumed session with ticket information in its extension); So, resumed sessions break our logic since  we are not able to fetch the client certificate (for instance, in our implementation [`peercert/1](https://www.erlang.org/doc/man/ssl.html#peercert-1)` returns `{:error,no_peercert}`)

So, as solution, I aim to store information related to  the first full handshake connection (such as client certificate) in an external cache (Like an standalone Redis server), but with this solution, I've two critical question:

1. How can I access master secret or similar information (which server uses to decrypt the “ticket”, extracts the session information in resuming a session) to use those information as key for store/restoring data related  to resumed sessions? I mean, how can I access the ticket information at the time of handling first full hand shake connection request (which, under the hood,  the server is using them to send  back to the client via the Session Ticket message)?

2. Since, “Session resumption”  in TLS1.3 allows customers to use work performed for one handshake to bypass the need for authentication, am I doing some anti patterns by storing some information in server side and add extra overhead?

**Comment by Elimira** [comment]
Thanks for your reply; Do you think if I can retrieve keylog and other secret information from a TLS 1.3 connection [by setting keep_secrets  to be true], then can I use it as an unique identifier that associates the resumed session with the original session?

**Comment by IngelaAndin** [comment]
No, I do not think so. Firstly keylogging is a debugging feature I think you would not want in production. Secondly, I do not think this would work as you expect as TLS-1.3 session tickets are quite different from TLS-1.2 sessions where a lot of secret information was reused.

**Comment by IngelaAndin** [comment]
@Elimira The PR #5957 might interest you. It is far from done but probably something you would want. We have not had time to add post _auth yet and even if we do it also needs to be supported and perhaps enabled by the client, so an alternative might be interesting.
