### ISSUE TITLE
ssh_file returns legacy Ed25519 format

### ISSUE THREAD

**Issue by hauleth** [erlang/otp#5681]
**Describe the bug**

`public_key` documentation states that the legacy key format will not be returned by the functions in this module. As `ssh_file:decode/2` and `ssh_file:encode/2` are meant to be replacements of `public_key:ssh_*/2` functions I would assume that the same rule will apply there. 

**To Reproduce**

Have valid `id_ed25519` key in your `user_dir` and then use:

```erlang
ssh_file:user_key('ssh-ed25519', []).
```

This will return:

```erlang
{ok,{ed_pri,ed25519, …}}
```

**Expected behavior**

I would expect to get the record:

```erlang
{ok,{#'ECPrivateKey', …}}
```

**Affected versions**

I have tested only OTP 24, but I assume that previous versions are affected as well.

**Comment by HansN** [comment]
This is related to a change in the public key typing that shall be fixed, and to that OTP/SSH does not yet use the `#'ECPrivateKey'{}` record for the experimental implementation of the  `openssh-key-v1` in combination with Edwards curves.

We  will fix the typing and the documentation.

**Comment by HansN** [comment]
Related to #5680 
(Internal note: OTP-17912)

**Comment by HansN** [comment]
Fixed in master to be released as OTP 25.
