### ISSUE TITLE
Attributes mixed with functions

### ISSUE THREAD

**Issue by elbrujohalcon** [erlang/otp#5689]
### Is your feature request related to a problem? Please describe.
I would like to implement AdRoll/rebar3_format#244 using attributes to surround code blocks that the formatter should ignore. To do that, I would like to be able to write code as…

```erlang
-module my_mod.

-export [my_fun/0].

my_fun() ->
    my_fun(something, something).

-format_block ignore.
my_fun(something, something) -> [
  this
  , function
    , should
      , not be:formatted()
        ].
-format_bock.
```

But the compiler now tells me that…

```erlang
my_mod.erl:#:#: attribute format_block after function definitions
```

### Describe the solution you'd like
I would like to have a compiler option available to disable that check.

### Describe alternatives you've considered
A brutal alternative would be to remove that check entirely, but I don't really know if there are scenarios where it's really needed.
Another one would be to allow _some_ (i.e. a list of) attributes to be interleaved, but that list should either be configurable or otherwise properly maintained.
Another alternative is to preserve the check but only for OTP attributes… user attributes can be interleaved at will. That would be my favorite choice, but again… I'm not really aware of the consequences.

**Comment by ilya-klyuchnikov** [comment]
there are tools (like code linters and analysers) that would also benefit from an ability to specify how particular functions should be handled, - similar to how dialyzer relies on `-dialyzer(...)` attributes. 

It it possible to do this via putting custom attributes in the beginning of a file and mention the function `foo/1` explicitly, like this:

```erlang
-my_tool({ignore, {foo, 1}}).

-spec ...
bar1(..) ->

bar2(..) ->

foo1(Arg) -> 
...
```

But it is very sub-optimal for the ergonomics and usability points of view - since for developers it is important to keep the locality of "annotations" - keep annotations close to the code they affect.

**Comment by paulo-ferraz-oliveira** [comment]
Code editors would potentially also benefit from the possibility to expand/collapse code, as eg.:

```erlang
-module(example).
-export([a/0, b/0, c/0]).

-region Public API.
a() -> a_int().
b() -> b_int().
c() -> c_int().
-endregion.

-region Internal functions.
a_int() -> a().
b_int() -> b().
c_int() -> c().
-endregion.
```

would look like this when collapsed (the `+` is just "visual").

```erlang
-module(example).
-export([a/0, b/0, c/0]).

+Public API

+Internal functions
```

This is actually something I've missed from my C# days. It could also probably be achieved with comments, though, but it would be trickier to validate, I imagine.

Hm... I think I might have mentioned this in `rebar3_format` somewhere, already. 😄

**Comment by elbrujohalcon** [comment]
Any chance we can re-surface this idea, OTP Team? As a maintainer for Elvis, Hank, and rebar3_format (among others) I found myself linking to this ticket time and time again, lately. I still wonder how bad it could be to allow custom attributes to be placed after the first function declaration.

**Comment by duncanatt** [comment]
Is there an update regarding these custom attributes that can be used to annotate functions? Is this something you plan to support in future releases?
