### ISSUE TITLE
Application names may conflict with command line flags with multiple args

### ISSUE THREAD

**Issue by josevalim** [erlang/otp#5699]
**Describe the bug**

If you create an application that has the same name as a command line flag that accepts multiple arguments, then certain invocations of `erl` may cause the application failing to load:

```
$ erl -pa "/Foo/Bar" "/Bar/Baz"
Erlang/OTP 24 [erts-12.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Eshell V12.1  (abort with ^G)
1> application:load({application,pa,[]}).
=ERROR REPORT==== 9-Feb-2022::08:42:20.434214 ===
application_controller: syntax error before: '/': /Foo/Bar

{error,{bad_environment_value,"/Foo/Bar"}}
```

If it helps, here is the stacktrace of the failure:

```erlang
{current_stacktrace,[{application_controller,handle_make_term_error,3,[{file,"src/application_controller.erl"},{line,1659}]},{application_controller,conv,1,[{file,"src/application_controller.erl"},{line,1642}]},{application_controller,'-get_cmd_env/1-fun-0-',2,[{file,"src/application_controller.erl"},{line,1637}]},{lists,foldl,3,[{file,"lists.erl"},{line,1267}]},{application_controller,load,2,[{file,"src/application_controller.erl"},{line,1303}]},{application_controller,handle_call,3,[{file,"src/application_controller.erl"},{line,639}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,721}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,750}]}]}
```

This means two things:

1. A developer must avoid picking an application name that conflicts with any of the multi-args flags. The conflicting flags today are: `boot_var compile config configfd env pa pz path run s setcookie`

2. Adding new flags to `erl` may break existing applications in case there is already an application with the name of such flag

**Expected behavior**

At the moment, I can't think of anything actionable to be done. It may be the Erlang/OTP team is familiar with this bug, but I thought I would report it as it may impact how decisions about new flags are made in the future. Feel free to close it. :)

**Affected versions**

Verified to happen at least from Erlang/OTP 21.

**Comment by max-au** [comment]
Any problem can be solved with an extra layer... something like `erl -app_env pa key value` (where `-app_env` is a new command line switch, followed by app name, key name and value).

**Comment by josevalim** [comment]
I will go ahead and close this one. This bug is pretty much a PSA and Elixir does not allow you to generate applications with any of the names above. If rebar3 has a command for generating new applications, they likely want to do the same.
