### ISSUE TITLE
compact not works without decimals option

### ISSUE THREAD

**Issue by 221V** [erlang/otp#5714]
**Describe the bug**
```
float_to_binary(Float, Options) -> binary()  OTP R16B

Types
Float = float()
Options = [Option]
Option =
    {decimals, Decimals :: 0..253} |
    {scientific, Decimals :: 0..249} |
    compact
```
![docs screenshot](https://i.imgur.com/BAvzGJg.png)
[Docs](https://www.erlang.org/doc/man/erlang.html#float_to_binary-2)

but compact not works  

**To Reproduce**
```
> A1 = 2.5 + 4.
6.5
> A1.                   
6.5

> float_to_binary(A1).                         
<<"6.50000000000000000000e+00">>

> float_to_binary(A1, [compact]).
<<"6.50000000000000000000e+00">>

> float_to_binary(A1, [{decimals, 16}, compact]).
<<"6.5">>
```

**Expected behavior**
```
> A1 = 2.5 + 4.
6.5

> float_to_binary(A1, [compact]).
<<"6.5">>
```
please improve doc info about float_to_binary/2 --  
because we read symbol "|" in types description as OR, not as AND --  
so now doc for float_to_binary/2 looks like Options [compact] can be used as well .. (((
again wasted time with [compact] ((

**Affected versions**
OTP versions 23.3

**Comment by garazdawi** [comment]
Hello!

> please improve doc info about float_to_binary/2 -- because we read symbol "|" in types description as OR, not as AND --

It is not possible to describe a relationship between two options in the type language of Erlang, so what we have to do is to include both variants and describe in the documentation the relationship.

The documentation for float_to_binary/2 says that the options work as for float_to_list/2, and in float_to_list/2 `compact` is described like this:

> If option compact is specified, the trailing zeros at the end of the list are truncated. This option is only meaningful together with option decimals.

If you have any suggestion about how to make the documentation clearer, a PR is most welcome.

**Comment by 221V** [comment]
Hello @garazdawi !

can we add description

> If option compact is specified, the trailing zeros at the end of the list are truncated. This option is only meaningful together with option decimals.

for float_to_binary/2 too ?
not only for float_to_list/2, please

thank you!

**Comment by garazdawi** [comment]
> Hello @garazdawi !
> 
> can we add description
> 
> > If option compact is specified, the trailing zeros at the end of the list are truncated. This option is only meaningful together with option decimals.
> 
> for float_to_binary/2 too ? not only for float_to_list/2, please
> 
> thank you!

We tend to avoid adding duplicate documentation as inevitable there is a large chance that an update is done only to one of the texts. But if you have any suggestions to make it more obvious that the user of the float_to_binary API should also read the float_to_list documentation a PR would be very welcome.
