### ISSUE TITLE
Is it possible to provide a user generated tls session ticket key

### ISSUE THREAD

**Issue by yonashaile** [erlang/otp#5715]
I am working on a multi-node TLS 1.3 stateless server, where each server would be able to handle session tickets generated from any of the servers.

With multiple servers, it is possible that 0-RTT might end up in a server different from the one that handled fulll handshake (or generated the session ticket). However, it might not be decrypted/validated since each server is using a randomly generated keys used for generating/verifying session tickets.

1. Is there a way to use a user generated tls session ticket key, that could be re-used across servers?
For example, apache's mode_ssl sslsessionticketkeyfile (https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslsessionticketkeyfile)
and envoy TlsSessionTicketKeys (https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#extensions-transport-sockets-tls-v3-tlssessionticketkeys)

2. If not, is there a workaround or recommended way of implemented multi-node TLS 1.3 stateless servers?

**Comment by IngelaAndin** [comment]
Your links above seem to be handling RFC RFC 5077, which is the TLS ticket extension used before TLS-1.3. I think we would need to make some similar option for the stateless server for that to work. PR is welcome!

**Comment by u3s** [comment]
Could this PR be a solution for you issue https://github.com/erlang/otp/pull/5982 ?

https://www.erlang.org/doc/man/ssl.html#type-stateless_tickets_seed

It is available since ssl-11.0 (OTP-26).

**Comment by u3s** [comment]
I've read you description again and I think that seed solution is the answer.
Therefore, I will close the issue.

Feel free to re-open it, if I missed something.
