### ISSUE TITLE
process_info(Pid, dictionary) causes idle process to tick their reduction count

### ISSUE THREAD

**Issue by jesperes** [erlang/otp#5716]
**Describe the bug**
Fetching the process dictionary using `process_info(Pid, dictionary)` causes the observed process (`Pid`) to increment its reduction count.

**To Reproduce**
```
2> Pid = spawn(fun() -> receive stop -> ok end end).
<0.92.0>
3> process_info(Pid, reductions).
{reductions,4007}
4> process_info(Pid, dictionary).
{dictionary,[]}
5> process_info(Pid, reductions).
{reductions,4008}
6> 
```

**Expected behavior**
I would have expected the reduction count to say the same.

**Affected versions**
I have verified the bug to be present in:
22.3.4.23
23.3.4.9
24.2.1

**Additional context**
Related to https://github.com/erlang/otp/issues/4304.

**Comment by jhogberg** [comment]
Thanks for your report, but this is not a bug. The target process does actual work when you ask for its process dictionary, so its reductions are bumped to match.

The issue you linked mentions this in the first comment.

**Comment by jesperes** [comment]
Ok, thanks.

**Comment by jesperes** [comment]
Would it make sense to add a feature request for a more well-defined way to detect stalled processes? I am guessing that this is not a very far-fetched use-case and that other people would have had similar issues.
