### ISSUE TITLE
why there are two different erl 19.3.6.5 ?

### ISSUE THREAD

**Issue by 221V** [erlang/otp#5720]
**Describe the bug**
i need erl 19.3.6.5, so looking around --

and found two different links  -- 
1. page https://github.com/erlang/otp/releases/tag/OTP-19.3.6.5  
    link https://github.com/erlang/otp/archive/refs/tags/OTP-19.3.6.5.zip  ("Source code (zip)" - bottom)  
2. page https://www.erlang.org/patches/otp-19.3.6.5  
    link https://api.github.com/repos/erlang/otp/tarball/refs/tags/OTP-19.3.6.5  (red button "Download source" - right top)

**To Reproduce**

diff output --  
https://gist.github.com/221V/17046ff1cd942d4a1dee207764ff8b9d

**so what this means? why there are diff?**
thank you!

**Comment by garazdawi** [comment]
The difference seem to the in the files that are symbolic links in our repository, for example: https://github.com/erlang/otp/blob/master/lib/inets/examples/httpd_load_test/hdlt_ssl_client_cert.pem

Seems like the tool you are using to extract the zip archive does not handle symbolic links as it should.
