### ISSUE TITLE
Failed to build with Gitpod.

### ISSUE THREAD

**Issue by zeek0x** [erlang/otp#5732]
**Describe the bug**

If I access gitpod from the gitpod link (https://gitpod.io/#https://github.com/erlang/otp) in otp/HOWTO/DEVELOPMENT.md, the build will start and fail.

**To Reproduce**

Open https://gitpod.io/#https://github.com/erlang/otp

**Expected behavior**

Successfully build an Erlang/OTP environment within Gitpod.

**Affected versions**

master branch version. (or PR based on master:  https://gitpod.io/#https://github.com/erlang/otp/pulls/xxx )

**Additional context**

I have tried to fix this problem. 

The first problem is running apt-get as `gitpod` user (≠ root).

https://github.com/erlang/otp/blob/9f87c568cd3cdb621cf4cae69ccce880be4ea1b6/.github/dockerfiles/Dockerfile.ubuntu-base#L14

```console
#5 1.238 E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
#5 1.238 E: Unable to lock directory /var/lib/apt/lists/
#5 ERROR: process "/bin/sh -c apt-get update && apt-get -y upgrade &&
...
```

I actually run it locally...

```console
$ docker run --rm gitpod/workspace-full whoami
gitpod
```

So I added `USER root` before `DEBIAN_FRONTEND=noninteractive`  (L10 of the following code). 

https://github.com/erlang/otp/blob/9f87c568cd3cdb621cf4cae69ccce880be4ea1b6/.github/dockerfiles/Dockerfile.ubuntu-base#L9-L14

Then I found a problem with the `apache2` installation. 

```console
Configuration file '/etc/apache2/apache2.conf'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** apache2.conf (Y/I/N/O/D/Z) [default=N] ?
```

Even though `DEBIAN_FRONTEND=noninteractive` is set, the installer still ask how to install.

I tried to connect the yes command to the apt-get pipeline, but ran into another problem.

```console
Setting up apache2 (2.4.41-4ubuntu3.9) ...

Configuration file '/etc/apache2/apache2.conf'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** apache2.conf (Y/I/N/O/D/Z) [default=N] ? Installing new version of config file /etc/apache2/apache2.conf ...

Configuration file '/etc/apache2/envvars'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** envvars (Y/I/N/O/D/Z) [default=N] ? Installing new version of config file /etc/apache2/envvars ...
ERROR: Module mpm_prefork is enabled - cannot proceed due to conflicts. It needs to be disabled first!
```

Finally, by disabling `mpm_prefork` (`$ a2dismod php7.4 mpm_prefork`), `apt-get install apahce2` succeeds.

However, it relies on `gitpod/workspace-full`, which is not suitable for a general Dockerfile used with Erlang/OTP.

Are there any plans to create a Dockerfile for gitpod?

**Appendix**

I don't know the exact cause, but I think the problem is caused by the problem that `gitpod/workspace-full` already has `apahce2`.

```console
docker run --rm gitpod/workspace-full apt list apache2

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Listing...
apache2/focal-updates,focal-security 2.4.41-4ubuntu3.9 amd64
```

**Comment by garazdawi** [comment]
Hello! Nice to see someone exploring the gitpod setup that I made! :)

I made some changes in #5821 that should fix the issues by not installing apache if it already exists and the `USER root` fix that you proposed.

> Are there any plans to create a Dockerfile for gitpod?

I was really hoping to avoid having multiple docker files to maintain, so if possible I would like to continue as is. It really is too bad that gitpod does not allow you to give any arguments to the development image like devcontainers do.

**Comment by maennchen** [comment]
@garazdawi I was also trying the setup (using VSCode devcontainer) and I found two problems:

```console
$ ./otp_build configure
...
config.status: creating config.mk
config.status: creating c_src/Makefile
./configure: line 5245: pkg-config: command not found
./configure: line 5246: pkg-config: command not found
```

That one is easily solved by adding `pkg-config` via apt.

If I do that, I however get this error and I don't know how to solve that one:

```console
$ ./otp_build all -t
...
 GEN    x86_64-pc-linux-gnu/erl_db_insert_list.ycf.h
/workspaces/otp/erts/lib_src/yielding_c_fun/bin/x86_64-pc-linux-gnu/yielding_c_fun: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /workspaces/otp/erts/lib_src/yielding_c_fun/bin/x86_64-pc-linux-gnu/yielding_c_fun)
make[2]: *** [x86_64-pc-linux-gnu/Makefile:699: x86_64-pc-linux-gnu/erl_db_insert_list.ycf.h] Error 1
make[2]: Leaving directory '/workspaces/otp/erts/emulator'
make[1]: *** [/workspaces/otp/make/run_make.mk:42: generate] Error 2
make[1]: Leaving directory '/workspaces/otp/erts/emulator'
make: *** [Makefile:550: depend] Error 2
```

Should I open a new issue for both or open a PR for 1 and an issue for 2?

**Comment by garazdawi** [comment]
> Should I open a new issue for both or open a PR for 1 and an issue for 2?

Yes, please do.
