### ISSUE TITLE
Incorrect column number for "exported from 'case'" warning

### ISSUE THREAD

**Issue by mheiber** [erlang/otp#5749]
**Describe the bug**

The column number in the warning for variable exported from
case is incorret

**To Reproduce**

Save sample.erl with these contents, then `erlc sample.erl`:

```erl
-module(sample).
-export([main/1]).

main(_) ->
X = case ok of
      X -> X
end,
X.
```

The error message incorrectly reports the column number as `5`:

```
sample.erl:5:1: Warning: variable 'X' exported from 'case' (line 5, column 5)
%    5| X = case ok of
%     | ^
```

**Expected behavior**

Error message reports that the variable 'X' is in column 1

**Affected versions**

This is what I see when I start `erl`:

```
Erlang/OTP 25 [DEVELOPMENT] [erts-12.2] [source-a3d7f60267] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns] [dtrace]
```

**Comment by bjorng** [comment]
As far as I can see the warning is correct.

`X` is in column 1, as indicated by:

```
sample.erl:5:1:
```

The keyword `case` starts at column 5, as indicated by:

```
(line 5, column 5)
```

**Comment by mheiber** [comment]
Thanks, I was reading the error message wrong, I see the column number points to the `case`. Sorry about that
