### ISSUE TITLE
Dialyzer sometimes reports incorrect location for "unknown type" errrors in OTP 24.x-25.x

### ISSUE THREAD

**Issue by jesperes** [erlang/otp#5764]
**Describe the bug**
OTP 24.x introduced locations for "unknown type" errors, see https://github.com/erlang/otp/issues/4416. However, these are in some circumstances incorrect.

**To Reproduce**
Detailes steps to reproduce, including module source code and scripts to reproduce can be found in this gist: https://gist.github.com/jesperes/4265139e0e8f597ea5d9fd368b6bf8af. The errors are:
```erlang
  foo:bar/0 (epgsql.erl:3:25)
  foo:bar/0 (epgsql_cmd_connect.erl:3:25)
```

**Expected behavior**
I would have expected this:
```erlang
  foo:bar/0 (epgsql.erl:3:25)
```
The second error is wrong, because (1) it refers to a location where `foo:bar()` is **not** used, and (2) the filename and location are incorrect; there is not even any code at `src/epgsql_cmd_connect.erl:3:25`. The `3:25` is likely taken from the other error.

**Affected versions**
All OTP versions 24.x and later are affected, including the OTP 25.x rcs.

**Comment by bjorng** [comment]
Thanks for the bug report. The linked pull request solves the problem.
