### ISSUE TITLE
Document how to use unicode:characters_to_binary correctly

### ISSUE THREAD

**Issue by mheiber** [erlang/otp#5777]
**Is your feature request related to a problem? Please describe.**

I often see code like this, which is subtly incorrect:

```
function_expecting_binary(unicode_to_binary(Unicode))
```

I understand if the author intended to ignore error cases, but there's a possible success case that is also unhandled, `{incomplete, binary(), RestData}`:

```erl
-spec characters_to_binary(Data) -> Result when
      Data :: latin1_chardata() | chardata() | external_chardata(),
      Result :: binary()
              | {error, binary(), RestData}
              | {incomplete, binary(), binary()},
      RestData :: latin1_chardata() | chardata() | external_chardata().
```

I recommend documenting what `incomplete` means and what the developer using this API is supposed to do. I assume something like this, but I don't know what to put in the `???` part: a loop to keep reading until there are no more `incomplete`s?

```
Binary = case characters_to_binary(Unicode) of
   B when is_binary(B) -> B,
   {incomplete, B1, B2} -> ?????
end,
function_expecting_binary(Binary)
```

**Describe alternatives you've considered**

I considered making a wrapper function that handles the `incomplete` case, but I don't know how to write it.

**I'd be happy to PR to the docs once I know what the recommendation is, thanks for your help**

**Comment by dgud** [comment]
Incomplete is documented if you follow the documentation, it says see [characters_to_list-2](https://www.erlang.org/doc/man/unicode.html#characters_to_list-2) and incomplete is described at the bottom of that function 
it even have an example of how to handle incomplete.

Send a PR if you still believe it needs improvements.
