### ISSUE TITLE
TLS handshake issue in OTP 24.3

### ISSUE THREAD

**Issue by acco** [erlang/otp#5783]
**Describe the bug**
When attempting to connect to a remote server, I receive the following error:

```
[error] pid=<0.737.0> [error] GenStateMachine #PID<0.737.0> terminating
** (KeyError) key :certificate_authorities not found in: %{signature_algs: {:signature_algorithms, [:ecdsa_secp256r1_sha256, :ecdsa_secp384r1_sha384, :ecdsa_secp521r1_sha512, :eddsa_ed25519, :eddsa_ed448, :rsa_pss_pss_sha256, :rsa_pss_pss_sha384, :rsa_pss_pss_sha512, :rsa_pss_rsae_sha256, :rsa_pss_rsae_sha384, :rsa_pss_rsae_sha512, :rsa_pkcs1_sha256, :rsa_pkcs1_sha384, :rsa_pkcs1_sha512, {:sha224, :ecdsa}, {:sha224, :rsa}]}}
    :erlang.map_get(:certificate_authorities, %{signature_algs: {:signature_algorithms, [:ecdsa_secp256r1_sha256, :ecdsa_secp384r1_sha384, :ecdsa_secp521r1_sha512, :eddsa_ed25519, :eddsa_ed448, :rsa_pss_pss_sha256, :rsa_pss_pss_sha384, :rsa_pss_pss_sha512, :rsa_pss_rsae_sha256, :rsa_pss_rsae_sha384, :rsa_pss_rsae_sha512, :rsa_pkcs1_sha256, :rsa_pkcs1_sha384, :rsa_pkcs1_sha512, {:sha224, :ecdsa}, {:sha224, :rsa}]}})
    (ssl 10.7) tls_handshake_1_3.erl:1442: :tls_handshake_1_3.process_certificate_request/2
    (ssl 10.7) tls_handshake_1_3.erl:1094: :tls_handshake_1_3.do_wait_cert_cr/2
    (ssl 10.7) tls_connection_1_3.erl:410: :tls_connection_1_3.wait_cert_cr/3
    (stdlib 3.17.1) gen_statem.erl:1203: :gen_statem.loop_state_callback/11
    (ssl 10.7) tls_connection.erl:155: :tls_connection.init/1
    (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

Full stack trace:
https://gist.github.com/acco/74f768da80b96775b14cf31889ecee8e

**To Reproduce**
Unfortunately it involves connecting to a private database, so I can't share reproducible steps. Trying to see if I can spin up a test db for the purposes of this ticket. This issue does not occur for every database I try to connect to, just a small subset of them.

If there's something I can run to determine details about remote server (TLS version etc) let me know.

**Expected behavior**
TLS connection established.

**Affected versions**
For me, this issue occurs in 24.3 but not 24.2.2.

**Additional context**
None.

**Comment by IngelaAndin** [comment]
I think this is a case of a missing default value. I think PR #5784 should solve the problem. I will work on creating a new test as this apparently slipped through.

**Comment by IngelaAndin** [comment]
@acco It would be nice if you could confirm that my PR solves your issue before we make a patch. Our planned test framework additions that I referred to in the comments to my code in the PR will take some time and will probably not be prioritized before the OTP-25 release.

**Comment by indrekj** [comment]
I think we stumbled upon the same issue. We're using `elixir:13` image which is [built from](https://github.com/erlef/docker-elixir/blob/2e8a37c9f725f49dff4ae17e0ca893aaedddc00b/1.13/alpine/Dockerfile#L1) `erlang:24-alpine`. That image however was [updated](https://github.com/erlang/docker-erlang-otp/commit/672916f1a4f82a5102092b116a3075641de3fff2) a few days ago from 24.2.2 to 24.3. So all our new builds started using the new erlang version and thus stopped running.

**Comment by IngelaAndin** [comment]
OTP-24.3.1 is now available
