### ISSUE TITLE
IPv6 multicast options are broken

### ISSUE THREAD

**Issue by binaryseed** [erlang/otp#5789]
Using `gen_udp` multicast options with an IPv6 address fail with a `badarg` error. Beyond the argument parsing, the `inet_driver` code doesn't have support for handling IPv6 addresses when doing multicast operations (see https://github.com/erlang/otp/pull/5726#discussion_r814790826). The underlying multicast functionality does work however, once the kernel gets the correct socket options.

For example, opening a socket with a multicast interface and an IPv4 address:
```erlang
gen_udp:open(5000, [inet, binary, {multicast_if, {10, 11, 12, 1}}]).
```

This fails with an IPv6 address:
```erlang
gen_udp:open(5000, [inet6, binary, {multicast_if, {65152, 0, 0, 0, 0, 0, 0, 1}}]).
```

There is a workaround, which involves giving the kernel `raw` socket options, for example, joining a multicast group with this:

```erlang
Mad = <<65298:16, 0:16, 0:16, 0:16, 0:16, 0:16, 0:16, 1:16>>,
Ifindex = <<10:32/native>>,
Ip6 = 41,
Ip6am = 12,
Raw = {raw, Ip6, Ip6am, <<Mad/binary, Ifindex/binary>>},
gen_udp:open(5000, [inet6, binary, Raw]).
```

The issue has been around for a while, and was described here: https://stackoverflow.com/questions/38376640/cant-add-multicast-group . The workaround is complicated because it involves passing OS-specific socket flags:

* Linux: `IPV6_ADD_MEMBERSHIP 20` https://github.com/torvalds/linux/blob/master/include/uapi/linux/in6.h#L172
* Mac: `IPV6_JOIN_GROUP 12` https://github.com/apple/darwin-xnu/blob/main/bsd/netinet6/in6.h#L568

**Comment by bmk** [comment]
If you are looking for an IPv6 version of multicast_if, it is currently not supported.
Even though the documentation claims it is.
Also, the IPv6 version of multicast_if takes an interface index (integer), not an (IPv6) address.
Also, the add/drop membership option has the same problem. It is documented to
work with IPv6, but does not.

**Comment by bmk** [comment]
A solution for this problem has now been merged (into maint and master)

**Comment by njouanin** [comment]
Hi,
I'm running Erlang/OTP 25.2 and it seems that `badarg` error still appears with IPv6. 
Here's my test:

```
$ erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:fwrite(Version), halt().' -noshell
25.2
$ erl
Erlang/OTP 25 [erts-13.1.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]

Eshell V13.1.3  (abort with ^G)
1> gen_udp:open(5000, [inet, binary, {multicast_if, {10, 11, 12, 1}}]).
{ok,#Port<0.5>}
2> gen_udp:open(5000, [inet6, binary, {multicast_if, {65152, 0, 0, 0, 0, 0, 0, 1}}]).
** exception exit: badarg
     in function  inet6_udp:open/2 (inet6_udp.erl, line 55)
```

Can you confirm this issue is closed and released ?
