### ISSUE TITLE
observer_backend:get_port_list/0 fails (partially) on macOS

### ISSUE THREAD

**Issue by leoliu** [erlang/otp#5798]
**Describe the bug**
On macOS `observer_backend:get_port_list/0` returns empty list of `options` for `tcp_inet` ports.

**To Reproduce**
Check it with observer or just inspect the value from `observer_backend:get_port_list()`.

**Expected behavior**
Should return the options as on other platforms

**Affected versions**
Bug reproduced with OTP 23.3, 24.3 on macOS 11

**Additional context**
The `inet:getopts` call in `observer_backend:inet_port_extra/2` fails with `{error,einval}`. Remove `bind_to_device` and `netns` and it succeeds.

**Comment by leoliu** [comment]
I just tested this on Windows 10 using OTP 25.rc1 and removing `bind_to_device` and `netns` also makes it work.

**Comment by bmk** [comment]
I have a simple fix that simply the (socket) options one-by-one.
That way, if one fails (for whatever reason) it can be "ignored"
(actually, the failure is included as a "value" as information).
Basically, it presents the values in a similar way as the 'socket' sockets.
Hopefully this will make it into 25.0-rc3.

**Comment by IngelaAndin** [comment]
Solution merged for OTP-25.0-rc3
