### ISSUE TITLE
code:modified_modules/0 false positives for modules loaded from escript

### ISSUE THREAD

**Issue by leoliu** [erlang/otp#5801]
**Describe the bug**
code:modified_modules() returns unmodified modules loading from escript

**To Reproduce**
Use rebar3 escript to start a shell session like `rebar3 shell` and then run `code:modified_modules().` At the time of testing it returned 82 modules that were packed in the escript.

**Expected behavior**
Should not return modules that aren't modified.

**Affected versions**
All versions since the function was introduced for example OTP 24.3

**Additional context**
See `code:beam_file_md5/1` which fails when a module is loaded from an escript because it tries to read the module from disk.

**Comment by bjorng** [comment]
I have fixed the bug in the linked pull request. Please verify that it solves your problem.

**Comment by leoliu** [comment]
My tests seem to suggest it returns `[]` even when there are modules modified. Also the function seems to get noticeably slower.

**Comment by leoliu** [comment]
Thanks. It fixes the bug for me though the function is getting noticeably slower.

**Comment by bjorng** [comment]
I have force-pushed a new version that only calls `code:get_object_code/1` if direct access to the file system fails. It is faster?

**Comment by leoliu** [comment]
Much faster. Thanks for the quick fix.
