### ISSUE TITLE
Add support for caching load paths

### ISSUE THREAD

**Issue by josevalim** [erlang/otp#5811]
**Is your feature request related to a problem? Please describe.**

Currently, code loading has two options: embedded or interactive. During a release, embedded mode restricts the code path to a single application and loads all modules upfront. This avoids code loading after the application boots but uses more memory, as you may load unused modules. On the other hand, interactive mode loads the modules as necessary.

For applications with many dependencies, we have started to noticed that interactive mode is actually slower to boot than embedded mode. That's because the cost of traversing the filesystem to find a module becomes too expensive. This can be particularly true on embedded devices. Therefore, this puts us in an awkward position here we have to choose a faster boot with more memory usage (embedded) or a slower boot with less memory usage (interactive). The slow loading in interactive mode can be noticed when running tests too, where there is an increased time until the first test runs.

**Describe the solution you'd like**

I would like to propose the ability of caching load paths. First, we will change all `code:all_*/1` functions to receive an optional second argument, called `cache`. For example:

    code:add_path("some_dep/ebin", cache)

If the cache option is given, we will perform a `file:list_dir/1` operation whenever we first attempt to lookup the cached directory and then store all files in a map to speed up future lookups. This is particularly useful in interactive mode, as we will no longer need to traverse the filesystem multiple times. In embedded mode, it has no effect.

I also propose additional changes:

  * [ ] Add `-pac` and `-pzc` to `erl`
  * [ ] Make it so all paths for Erlang/OTP apps are cached by default (can this be a breaking change? How does it play with ERL_LIBS?)
  * [ ] Add an option or a mechanism to cache all paths in a release

I will be glad to work on this, but I thought I would submit an initial description of the problem and the possible solution before I jump into it.

**Comment by KennethL** [comment]
We had more or less exactly the functionality you are suggested and removed it in OTP 19.0 (kernel-5.0).
The release note was like this:
```
The code path cache feature turned out not to be very useful in practice and has been removed. If an attempt is made to enable the code path cache, there will be a warning report informing the user that the feature has been removed.
```
In the documentation for OTP 18.0 is should be described how it worked.

**Comment by KennethL** [comment]
In OTP 18 we had this option to the `erl` command. 

`-code_path_cache`

Enables the code path cache of the code server.

That said I am positive to optimizing the speed of code loading during startup, if it is the traversing of directories which is the bottleneck. 
We have to remind ourselves of why we thought the code path cache was not very useful and what the problems was.

**Comment by KennethL** [comment]
There was also a `code:rehash()` function for updating the cache if new files have been added which could possibly impact what modules to be loaded.

**Comment by josevalim** [comment]
Thank you @KennethL, that's why I thought we had this functionality and I could not find it! :D

I think there is one important difference between the two approaches in that this proposal has the cache per directory. If I understand it correctly, the issue with `code:rehash/0` is that once you enabled it, no new .beam files from any directory would be loaded (unless you rehashed again). So there was no way for tools like Mix or Rebar to call `code:rehash/0` upfront without changing how the user code behaved or without affecting how loading modules from "." (or from any path added via `code:add_*/1`) worked.

By configuring the cache per load path, as in this proposal, Mix and Rebar can use it for all dependencies or even for Erlang/OTP itself, but keeping all other paths intact. The cost of computing the cache is also much cheaper compared to rehash. rehash always had to traverse all directories and this proposal keeps it per directory, so removing or adding a directory does not require full rehashes (and we can make the call to `file:list_dir/1` itself lazy by happening on the first directory lookup instead of upfront). This still means the operation is linear based on the amount of paths, but at least we replace several file system lookups, which is the expensive operation.

If we were to add something like `-code_path_cache`, then I would call it something like `-cache_erl_libs`, so it impacts only `ERL_LIBS`/OTP, and nothing more.

I hope this offers some ideas on how the approaches can differ and hopefully be more useful.

**Comment by tsloughter** [comment]
Haven't read all this yet and Fred will probably have a more detailed answer :), but thought I'd quickly add that rebar3 changes the code path a lot. I see caching used to be an option and we never used it... but if such functionality would improve performance around that we should have and would use it.

The issue with continually changing the path has been discussed before with the solution planned being major updates to the compiler so that code paths could be arguments instead of a global.

**Comment by josevalim** [comment]
To add a bit more of evidence on how this could be useful: a couple weeks ago I created a Mix project with 150 dependencies. However, starting the project with all 150 dependencies felt slow. Once I debugged it, most of the time was actually spent traversing the code paths to find the .app file to load it. I solved this by directly loading the .app files since I knew where it was for each dependency. With this small change, this particular step went from 920ms to 120ms.

The point is that, to load the .app for those 150 dependencies, we had to do 11325 file system lookups (`Enum.sum(1..150)`).  The fix made it so we performed only 150 lookups. But this change doesn't address the loading of the modules that happens once we start those applications, which is something this proposal would help us improve. :)

@tsloughter my idea is that the cache would be per directory, so you should be fine. You can either enable the cache as you add and remove directories or enable the cache during the last mangling of the code path. The important property is to know that nothing will be written to the `ebin` directory after it is cached.

**Comment by fhunleth** [comment]
I just want to add that this would greatly benefit Nerves devices. The differences that José found are magnified on the 32-bit ARM devices. 

I did a similar project on a Raspberry Pi Zero with 94 dependencies and saw the large number of file system lookups. To test removing the lookups, I make hard links to every BEAM file to the first directory in the search path. Here are the results:

Interactive mode start time: 48s
Embedded mode start time: 33.2s 
Interactive mode w/ hard links to all BEAMs in the first directory in the path: 32.9s

Having every BEAM file in one directory got rid of the excess path lookups, but each access took longer (presumably since there were a lot of files in that one directory). I would expect to get an even better load time with the caching described here.

I'm very interested in this and will watch here if there's anything to try. Thanks José for bringing this up and everyone for any help on it.

**Comment by KennethL** [comment]
@josevalim we in the OTP team encourage you to dig deeper into this and describe in more details how this could work in a compatible way. I think our previous solution gave a good speedup but suffered of a need to invalidate the cache quite often for various reasons. Having the cache per directory might be a better approach where the code path still is used and there is no need to have caching on every directory in the path.

**Comment by josevalim** [comment]
PR sent #6729. I will close this so we can continue the discussion there.

**Comment by josevalim** [comment]
Folks, just an update that the code path cache has been a resounding success for Elixir. Some folks are reporting compilation times decreased from 57% (from 62s to 27s) and even 70% (from 163s to 51s). The more cores on the machine, the better it seems, which means the code server was indeed a bottleneck for larger parts of our compilation. More reports here: https://elixirforum.com/t/elixir-v1-15-0-released/56584
