### ISSUE TITLE
file:copy(File,File) results in an empty file

### ISSUE THREAD

**Issue by hansph** [erlang/otp#5815]
if calling file:copy() with the same source and destination file name, it will silently overwrite the file. I would expect either a badarg or it would simply do nothing in this case, but it should never overwrite the source with 0 bytes.

**To Reproduce**
Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]

```
Eshell V12.2.1  (abort with ^G)
1> file:copy("p.txt","p2.txt").
{ok,6475}
2> file:copy("p2.txt","p2.txt").
{ok,0}
```
After the second command, the file p2.txt has 0 bytes.

**Expected behavior**
Either a badarg exception or doing nothing and return {ok,0}

**Comment by hansph** [comment]
I'm not yet 100% convinced :)
Linux stat should give you inode and device, and on filesystems which do not support this (FAT ?), probably the filename is sufficient.

**Comment by jhogberg** [comment]
> Linux stat should give you inode and device

The examples I listed are situations where `stat(2)` is of no help at all, the files will look different but they're not. :(

> probably the filename is sufficient.

I fear that rejecting "obviously" bad arguments will make people rely on it, breaking their applications in horrible and subtle ways once their users get creative with NFS.

**Comment by hansph** [comment]
i suppose locking the source file in order to avoid overwriting it is also not reliable, right? So i agree, if we can't guarantee the behaviour we should it.
