### ISSUE TITLE
erl_call stop app failed when upgrade otp version

### ISSUE THREAD

**Issue by bighunter513** [erlang/otp#5819]
**Describe the bug**
I have some erlang apps node compiled with otp 24.3.
when I upgrade otp to 24.3.2, and use erl -remsh attach them or erl_call to stop them,
2 of them will failed with Error:
{undef,[{erpc,execute_call,
              [#Ref<0.672512857.1505492994.24018>,shell,start,[]],
              []}]}
,but others ok
I don't have any clue.

**Comment by garazdawi** [comment]
The erpc module was added in Erlang/OTP 23, so you seem to be using erl_call to call a node that is older than that.

Can you verify that all the nodes are actually using 24.3.2?

**Comment by bighunter513** [comment]
> 

the problem is when I rollback to otp 24.3, I can attach the node, and find erpc:execute_call， also stop ok.

**Comment by garazdawi** [comment]
That makes no sense. None of the changes in between those versions should be affecting that behaviour. Can you create a small example for me to run?

**Comment by bighunter513** [comment]
I did a make clean ; and restart all apps ,and do upgrade otp (accutally, it not first come from otp 24)
when I use an newer erl_call to call any func like below: 

 erl_call -v -name mycache_carry_2_2@10.2.60.102 -c vgame_dev_2 -r -a 'erlang time'
erl_call: node = mycache_carry_2_2@10.2.60.102
Cookie = vgame_dev_2
flags =  verbosep
module: name =  , size = 0
apply = erlang time
erl_call: we are now connected to node "mycache_carry_2_2@10.2.60.102"
erl_call: module = erlang, function = time, args = []

{badrpc, {'EXIT', {undef, [{erpc, is_arg_error, [undef, erlang, time, []], []}, {rpc, execute_call, 3, [{file, "rpc.erl"}, {line, 263}]}, {rpc, '-handle_call/3-fun-0-', 5, [{file, "rpc.erl"}, {line, 136}]}]}}}

It looks the rpc module is called, not erpc .

**Comment by garazdawi** [comment]
> I did a make clean

Is this referring to doing a `make clean` in the Erlang/OTP repo? Could you try to do a `git clean -Xfdq` instead? Doing `make clean` is not a reliable way to clean all build artifacts from the Erlang/OTP repository.

> It looks the rpc module is called, not erpc .

As I said, [erpc](https://www.erlang.org/doc/man/erpc.html) was added in Erlang/OTP 23. So if all your nodes are Erlang/OTP 24 nodes it should be there.

**Comment by bighunter513** [comment]
> > I did a make clean
> 
> Is this referring to doing a `make clean` in the Erlang/OTP repo? Could you try to do a `git clean -Xfdq` instead? Doing `make clean` is not a reliable way to clean all build artifacts from the Erlang/OTP repository.
> 
> > It looks the rpc module is called, not erpc .
> 
> As I said, [erpc](https://www.erlang.org/doc/man/erpc.html) was added in Erlang/OTP 23. So if all your nodes are Erlang/OTP 24 nodes it should be there.

I know erpc was added in otp 23.  Actuall I encounter this problem for a long time, not just 24.3.
I try delete all beam files and use rebar3 compile again on any otp after 23, 
 it still can't stop when I upgrade to a newer version.

**Comment by bighunter513** [comment]
I add "erpc:call(node(), erlang, time, []) " when start the app,
And then the problem fixed, the node can attach and stop now.

I think some times erpc is not started by default .

**Comment by garazdawi** [comment]
> And then the problem fixed, the node can attach and stop now.

Great that you have fixed the problem!
