### ISSUE TITLE
devcontainer: version `GLIBC_2.34' not found

### ISSUE THREAD

**Issue by maennchen** [erlang/otp#5887]
**Describe the bug**

When using the devcontainer in VSCode and running `./otp_build all -t`, the following error occures:

```
/workspaces/otp/erts/lib_src/yielding_c_fun/bin/x86_64-pc-linux-gnu/yielding_c_fun: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /workspaces/otp/erts/lib_src/yielding_c_fun/bin/x86_64-pc-linux-gnu/yielding_c_fun)
make[2]: *** [x86_64-pc-linux-gnu/Makefile:699: x86_64-pc-linux-gnu/erl_db_insert_list.ycf.h] Error 1
make[2]: Leaving directory '/workspaces/otp/erts/emulator'
make[1]: *** [/workspaces/otp/make/run_make.mk:42: generate] Error 2
make[1]: Leaving directory '/workspaces/otp/erts/emulator'
make: *** [Makefile:550: depend] Error 2
```

**To Reproduce**

* Open Terminal inside devcontainer in VSCode
* Run `./otp_build all -t`

**Expected behavior**

Successful build.

**Affected versions**

`master`

**Additional context**

There's an earlier error for that I directly opened a PR: #5886

Follow up for https://github.com/erlang/otp/issues/5732#issuecomment-1097549304

**Comment by garazdawi** [comment]
And I thought docker was all about being able to reproduce issues in different environments... but I cannot reproduce your fault.

As described in the intro of the [Development Howto](https://github.com/erlang/otp/blob/master/HOWTO/DEVELOPMENT.md) the build system is not always as robust as one would like. Can you run git clean and try from scratch and see if that helps?

**Comment by maennchen** [comment]
@garazdawi I think I know what the problem is: `.devcontainer/devcontainer.json` overrides the `BASE` from `gitpod/workspace-full` to `mcr.microsoft.com/vscode/devcontainers/base:focal`.

The microsoft image does not contain `pkg-config` and apparently also uses a different version of glibc.

**Comment by garazdawi** [comment]
Using the MS image is intentional as otherwise things do not work as they should. I can't recall exactly what goes wrong if you don't use that image, but something breaks.

> The microsoft image does not contain pkg-config and apparently also uses a different version of glibc.

Do you get the same problem if you do not install `pkg-config`? It is only needed to detect some optional wx functionality and Erlang will build just fine without it.

> Cloning the repo anew does not solve the issue.

Please make triple sure that no artifacts are left behind and you are compiling what you think you are compiling. The problem you are seeing is just as if Erlang was built using the host machine first and then you try again within docker without cleaning up properly.

**Comment by maennchen** [comment]
@garazdawi 

Hm, I must have an incompatible VSCode extension that runs something it should not.

**Errors:**

* fresh git clone
* `git checkout devcontainer_pkg_config`
* `code .`
* accept popup to open in devcontainer
* in terminal: `./otp_build all -t`

**Does not error:**

* fresh git clone
* `git checkout devcontainer_pkg_config`
* `devcontainer open .` - open vscode directly in container, never on host
* in terminal: `./otp_build all -t`

That seems to be a problem with my setup then. Sorry for that.
