### ISSUE TITLE
Support vheap size limit for off-heap binaries

### ISSUE THREAD

**Issue by max-au** [erlang/otp#5889]
**Is your feature request related to a problem? Please describe.**
It's possible that a single process consumes all memory on the host, even when `process_flag(max_heap_size, #{size => 1000, kill => true})` is set for that process.

It happens when the process creates huge off-heap binaries that are accounted separately (vheap_size), and there is no way to be notified about a process that grows vheap beyond reasonable size (e.g. there is no `system_monitor(large_vheap)`

**Describe the solution you'd like**
Either account vheap_size as a part of a heap_size (breaks existing behaviour though), or implement `process_flag(max_vheap_size)` and `system_monitor(large_vheap)`.

**Describe alternatives you've considered**
Hope to find some, but so far unsuccessful.

**Comment by sverker** [comment]
@max-au What do you think about #6345?

**Comment by max-au** [comment]
Looks great! I am still torn between having that as a separate limit (so I can have 1M heap and 1G binaries). But your solution is indeed much smaller incremental change, and well controlled. I think I like it.
