### ISSUE TITLE
SSL transport socket setopts

### ISSUE THREAD

**Issue by mcodev31** [erlang/otp#5898]
**Describe the bug**
In order for ssl to allow receive on a socket when there is data available, the transport socket close is ignored (depending on active opt)
In addition to some odd behaviour where you can e.g. receive on a socket but not send, this can cause trouble if there is a setopt on the transport socket.
One such setopt is packet_size. This opt is specified as emulated, but it still seems to reach the transport socket. This can cause problems for e.g. publicly facing web servers relying on packet_size to prevent certain attacks.

**To Reproduce**

Simply close one end and call `ssl:setopts(Sock,[{packet_size,X}])` on the (non active) socket on the other end.
Attached code in additional context section. Call `test_setopts:run(ssl).` and `test_setopts:run(gen_tcp).`
With ssl you should see something like this:
```
call inet:setopts(#Port<0.8>,[{packet_size,1000}]) ({ssl_gen_statem,set_socket_opts,6}) ...
packet_size: setopts failed witn {error,{options,{socket_options,[{packet_size,1000}],einval}}}
returned from inet:setopts/2 -> {error,einval} ...
send result {error,closed}
recv result {ok,"h2"}
```

**Expected behavior**
I would essentially expect ssl to behave like gen_tcp. Assuming that's not possible, the packet_size setopt should not reach inet:setopts on the transport socket.

**Affected versions**
Present in 24 and 23 (not sure how far back)

**Additional context**
Example code:
```
-module(test_setopts).

-export([run/1]).


%% ssl/gen_tcp
run(Mod) ->
    ssl:start(),
    if Mod =:= ssl ->
	   Opts = [{active,once},{packet,raw},{certfile,"server1.crt"},{keyfile,"server1.key"},{reuseaddr,true}],
	   Port = 19999;
       true ->
	   Opts = [{active,once},{packet,raw},{reuseaddr,true}],
	   Port = 19998
    end,
    {ok,LSock} = Mod:listen(Port,Opts),
    S = spawn_link(fun() -> acceptor(Mod,LSock) end),
    C = spawn_link(fun() -> client(Mod,Port) end),
    dbg:stop_clear(),
    dbg:tracer(),
    dbg:p(all,[call, timestamp]),
    dbg:tp(inet, setopts, 2, cx),
    C!connect,
    {ok,S,C}.

acceptor(Mod,LSock) ->
    {ok,Sock} = if Mod =:= gen_tcp ->
		       gen_tcp:accept(LSock);
		   Mod =:= ssl ->
		       {ok,TSock} = ssl:transport_accept(LSock),
		       ssl:handshake(TSock)
		end,
    receive
	{Type,Sock,Data} when Type =:= ssl, Mod =:= ssl; Type =:= tcp, Mod =:= gen_tcp ->
	    io:format("received ~0p\n",[Data]),
	    receive after 1000 -> ok end,
	    setopts(Mod,Sock,[{packet_size,1000}],"packet_size"),
	    Send = Mod:send(Sock,<<"hello">>),
	    Recv = Mod:recv(Sock,0),
	    io:format("send result ~0p\n",[Send]),
	    io:format("recv result ~0p\n",[Recv]),
	    Mod:close(Sock),
	    Mod:close(LSock)
    end.

client(Mod,Port) ->
    receive connect -> ok end,
    {ok,Sock} = Mod:connect("localhost",Port,[{packet,raw}]),
    ok = Mod:send(Sock,<<"h1">>),
    receive after 100 -> ok end,
    ok = Mod:send(Sock,<<"h2">>),
    receive after 100 -> ok end,
    ok = Mod:send(Sock,<<"h3">>),
    Mod:close(Sock).

setopts(Mod0,Sock,Opts,Str) ->
    Mod1 = if Mod0 =:= gen_tcp -> inet;
	      true -> Mod0
	   end,
    case Mod1:setopts(Sock,Opts) of
	{error,_} = R ->
	    io:format("~s: setopts failed witn ~0p\n",[Str,R]);
	ok = R ->
	    io:format("~s: setopts ok\n",[Str])
    end,
    R.
```

**Comment by IngelaAndin** [comment]
The option is indeed emulated. It seems however the option is missing in the setopts and getopts code, but will work if set initially in connect or listen.  I am working on a PR to fix it.
