### ISSUE TITLE
i found atom count can not more than 33554432

### ISSUE THREAD

**Issue by xiaodoudou12** [erlang/otp#5903]
**Describe the bug**
we use otp 24.1.6.
our server will crash when  running a month later with core.
![11111](https://user-images.githubusercontent.com/39048971/163801179-7d7ef732-8e6d-41fb-8fdc-5460abf85041.png)

dmesg -T will show
```traps: 1_scheduler[1214814] general protection ip:566b97 sp:7fe661eaad00 error:0 in beam.smp[44c000+2c0000]```

in some reason the atom always increase in our server , so we run with -t 104857600.
i look up the source code

erts/emulator/beam/atom.c:348

```
/*

 * erts_atom_put() may fail. If it fails THE_NON_VALUE is returned!
 */
Eterm
erts_atom_put(const byte *name, Sint len, ErtsAtomEncoding enc, int trunc)
{
    int aix = erts_atom_put_index(name, len, enc, trunc);
    if (aix >= 0)
	return make_atom(aix);
    else
	return THE_NON_VALUE;
}
```

`#define make_atom(x)  ((Eterm)(((x) << _TAG_IMMED2_SIZE) + _TAG_IMMED2_ATOM))`

Eterm is unsigned long
_TAG_IMMED2_SIZE is 6
but x is int.
((unsigned long)(((x) << 6) + _TAG_IMMED2_ATOM))
so if x is more than 1<<25 (=33554432), make_atom will overflow.
i think if the atom count more than 33554432, erts_atom_put_index will return aix greater than 33554432.

i test it in c code

```
#include <stdio.h>
int main(){
        int x = (1<<25);
        int x1 = (x<<6)+10;
        unsigned long y = (unsigned long)(x1);
        printf("x=%d\n", x);
        printf("x1=%d\n", x1);
        printf("y=%lu\n", y);
        return 0;
}
```
output
x=33554432
x1=-2147483638
y=18446744071562067978
y is so big, it overflow.

i also test in erlang
```
test_atom_count(StartIndex, Count) ->
  case Count > 0 of
    ?TRUE ->
      TestList = lists:concat(["testatom_", StartIndex]),
      TestAtom = list_to_atom(TestList),
      TestList_2 = atom_to_list(TestAtom), 
      case TestList_2 of
        ?TRUE -> true;
        _ -> false
      end,
      test_atom_count(StartIndex+1, Count-1);
    ?FALSE ->
      ok  
  end.
```
test_atom_count will simulate add atom.
test_atom_count(10000000, 10000000). will add 10000000 atom.
test_atom_count(10000000, 10000000).
test_atom_count(20000000, 10000000).
test_atom_count(30000000, 10000000).
test_atom_count(40000000, 10000000).
run this function  4 times.our server will crash with core.

**Comment by mikpe** [comment]
Thanks for the bug report. I believe `erts_atom_put()` should declare `aix` as `Sint` not `int`.

_However_, the real problem is that your system is allocating new atoms like crazy, and the Erlang VM isn't designed for that. The real long-term fix is to identify why your system is creating new atoms at this rate and prevent it doing so.

**Comment by xiaodoudou12** [comment]
> Thanks for the bug report. I believe `erts_atom_put()` should declare `aix` as `Sint` not `int`.
> 
> _However_, the real problem is that your system is allocating new atoms like crazy, and the Erlang VM isn't designed for that. The real long-term fix is to identify why your system is creating new atoms at this rate and prevent it doing so.

thank you very much.
our system will restart every 3 to 4 weeks,last we run it on ecs,now we move it in k8s and reduce the pod count.
we will fix our system allocating new atoms like crazy in future.

**Comment by garazdawi** [comment]
I'm reopening this issue so that we fix the problem in `erts_atom_put`.
