### ISSUE TITLE
erlang inet:getifaddrs() hags on pure IPv6-only windows machine

### ISSUE THREAD

**Issue by peculiar-pooja** [erlang/otp#5904]
**Describe the bug**
Erlang command inet:getifaddrs() hags on pure IPv6-only windows setup. This is causing failure in starting rabbitMQ service.
For more details refer rabbitMQ thread: https://groups.google.com/g/rabbitmq-users/c/FJgf_Pp1O4c?pli=1 

**To Reproduce**
Run below command to reproduce issue locally:

C:\temp\erl-24.0.6\bin>erl -kernel inetrc "\"C:/erl_inetrc\"" -proto_dist inet6_tcp
Eshell V12.0.4  (abort with ^G)
1> init:get_arguments().
[{root,["C:\\temp\\erl-24.0.6"]},
 {progname,["erl"]},
 {home,["C:\\Users\\Administrator"]},
 {kernel,["inetrc","\"C:/erl_inetrc\""]},
 {proto_dist,["inet6_tcp"]}]
2> inet:getifaddrs().
[cmd prompt is hang at this stage]

**Expected behavior**
Command should list ip interfaces without hanging.

**Affected versions**
I validated with version erl-24.0.6 but previous version are also must be affected.

**Additional context**
Created pull request with fix for this issue as: https://github.com/erlang/otp/pull/5891

**Comment by bmk** [comment]
Solution merged.
