### ISSUE TITLE
Documentation bug: anchor tags incorrect

### ISSUE THREAD

**Issue by nathanl** [erlang/otp#5916]
**Describe the bug**
https://www.erlang.org/doc/man/erlang.html#process_flag_message_queue_data links to a specific flag. But the link icon labeled "Link to this place!" doesn't - clicking it takes you to the more general https://www.erlang.org/doc/man/erlang.html#process_flag-2. So there's no way to link to specific flags without manually constructing the URL.

![Screen Shot 2022-04-20 at 10 33 03 AM](https://user-images.githubusercontent.com/338814/164254752-932772ee-03cc-4c65-9306-4d76e3bbfa97.png)

**To Reproduce**
Click the link beside one of the flag.

**Expected behavior**
I expect it to change the URL to point to that flag's anchor tag.

**Affected versions**
This is a documentation issue. It's present in the current version online.

**Comment by garazdawi** [comment]
Hello! Thanks for the bug report. This is indeed a bug. I'll check and see what we can do about it.

**Comment by garazdawi** [comment]
Since we are migrating to ExDoc, this will no longer be an issue in Erlang/OTP 27, so closing this issue.
