### ISSUE TITLE
dialyzer should consider the use for an improper list

### ISSUE THREAD

**Issue by dotsimon** [erlang/otp#5937]
**Describe the bug**
Dialyzer produces an improper list warning even when that list is constructed for a function call that specs an improper list .e.g. `iodata()`

Consider `erlang:port_control/3`
```erlang
-spec port_control(Port, Operation, Data) -> iodata() | binary() when
      Port :: port() | atom(),
      Operation :: integer(),
      Data :: iodata().
```

And this code snippet:
```erlang
cmd(P, flush) ->
    port_control(P, ?FLUSH, [0 | <<1:32/native>>]);
```

Causes this dialyzer output:
`x.erl:10: Cons will produce an improper list since its 2nd argument is <<_:32>>`

**To Reproduce**
Put the example above into a module and dialyze

**Expected behaviour**
If the success typing for a constructed list is an improper list - and especially `iodata()` - then no warning should be emitted.

**Affected versions**
All?

**Comment by jhogberg** [comment]
Thanks for your report!

This warning is not for the use of, but rather the _construction_ of improper lists, which the original authors considered awful. We're leaning towards disabling these warnings by default in a future version, but for now you can pass `-Wno_improper_lists` to suppress it.

**Comment by dgud** [comment]
Or suppress it:
`-dialyzer({no_improper_lists, [stack/2, length_b/3]}).`

**Comment by dotsimon** [comment]
Ok, the warning being about _construction_ of an improper list makes a subtle difference.
So then maybe this should be a feature request rather than PR because I still think that given dialyzer tracks types especially within a module, that it could be smarter about this. 
I personally don't know that disabling all improper list warning would be a good idea. I would assume most lists are used as lists (eg. could be used as an argument to `lists:*` or in a comprehension) and therefore improper lists should be viewed with some suspicion.
Or is this now an "old fashioned" view - I notice the OTP team made a design decision that `gen` tags could be an improper list!

@dgud Yes! That is what I have been using to make these go away.

**Comment by jhogberg** [comment]
> I personally don't know that disabling all improper list warning would be a good idea. I would assume most lists are used as lists (eg. could be used as an argument to lists:* or in a comprehension) and therefore improper lists should be viewed with some suspicion.

`no_improper_lists` only affects the construction warnings, so you'll still get a type warning for passing `[foo | bar]` to a list function, for example.

>  Or is this now an "old fashioned" view - I notice the OTP team made a design decision that gen tags could be an improper list!

That's just the opinion of the original authors, at least as it were back then. Many of us at OTP disagree with the warning because it throws the baby out with the bathwater, there's nothing wrong with using a single cons cell as a more compact alternative to 2-tuples in internal code like `gen`.

**Comment by dotsimon** [comment]
Thanks for the additional context.
