### ISSUE TITLE
 Allow in memory tar files to be created in memory

### ISSUE THREAD

**Issue by PabloG6** [erlang/otp#5938]
**Is your feature request related to a problem? Please describe.**

I'm creating a library that binds docker commands to erlang/elixir code. I'm basically at a point where i need to build an image but docker requires a compressed tar file of the package your trying to build. I believe that `:erl_tar.create` is inefficient because it creates an actual file. I'd like to create this file in memory and send it to the docker api for building the image.
**Describe the solution you'd like**
I believe my solution would be two fold:

- First, expand the `open/2` definition in the `:erl_tar` package to use pid and file descriptors as well. 
- Expand the spec of create/2 to accept file_descriptors or pids for reading,
- Expand the options of create/2 to use the :ram flag.

**Describe alternatives you've considered**
I've considered developing a package manually that does this in elixir. I've not abandoned that idea but i do believe it would be more beneficial to the erlang and elixir community to request this feature here.

**Additional context**

**Comment by bjorng** [comment]
With your suggested extension of the API, it is not clear how you can open a tar file in memory and use `erl_tar:add/3,4` to add files to it. How would you retrieve the binary when you were done? I can see that `erl_tar:create/1,2` could work with `ram` option by returning the binary directly.

`erl_tar` started out with a limited but simple and elegant API. More functionality was needed, so the API was extended and it lost its simplicity. It seems to me that we have reached a pain point where we would need to design a new cleaner API before adding any more functionality (keeping the old for backward compatibility, of course).

It is very unlikely that we will be able to prioritise that task in Erlang/OTP 26.

Therefore, I will ask you whether you still need this functionality from Erlang/OTP? I saw [your thread](https://elixirforum.com/t/is-there-a-way-to-create-a-tar-file-in-memory-in-elixir/47470) in the Elixir forum and it was marked as solved. If you don't need the functionality, I intend to close this issue.
