### ISSUE TITLE
Confusing documentation around EUnit tests and `assertMatch` macro

### ISSUE THREAD

**Issue by distortedsignal** [erlang/otp#5949]
**Describe the bug**
The clearest documentation of the bug is probably in [this StackOverflow Question/Answer](https://stackoverflow.com/q/72063449/617122), but I'll try to reproduce it here:

I have some code that looks like this:

```erl
-module(ca_data).
-export([delete_ca_data/1]).

% ...

delete_ca_data(N) when N < 1 -> ?NEGATIVE_ID_ERROR;
delete_ca_data(N) -> util_db_generic(ca_data, N, fun(_) -> ok end).

% ...
```

... and some tests that look like this:

```erl
wrap_meck(MockMod, MockArgs, F) ->
    meck:new(MockMod, MockArgs),
    try
        F()
    catch Ex ->
        throw(Ex)
    after
        meck:unload(MockMod)
    end.

delete_ca_data_test() ->
    F = fun() ->
        meck:expect(util_db_generic, delete_object, fun (_, _, _) -> ok end),

        ?assertEqual(?NEGATIVE_ID_ERROR, ca_data:delete_ca_data(-1)),

        ?assertEqual([], meck:history(util_db_generic)),

        meck:expect(util_db_generic, delete_object, fun(_, _, _) -> ok end),
        ?assertEqual(ok, ca_data:delete_ca_data(1)),

        ?assertMatch(
            [{_, {util_db_generic, delete_object, [ca_data, 1, fun(_) -> ok end]}, ok}],
            meck:history(util_db_generic)
        ),

        ?assertMatch(
            [{self(), {util_db_generic, delete_object, [ca_data, 1, fun(_) -> ok end]}, ok}], % Uh-oh
            meck:history(util_db_generic)
        )
    end,
    wrap_meck(util_db_generic, [], F).
```

I recieve a compile error on the line marked `Uh-oh` because of the `self()` function. [However, the `assertMatch` documentation states that it](https://www.erlang.org/doc/apps/eunit/chapter.html#Assert_macros)...

> Evaluates Expr and matches the result against GuardedPattern, if testing is enabled. ... GuardedPattern can be anything that you can write on the left hand side of the -> symbol in a case-clause, except that it cannot contain comma-separated guard tests.

...[and the `self()` function's documentation states that it is](https://www.erlang.org/doc/man/erlang.html#self-0)...

> Allowed in guard tests

These seem like contradictory remarks to my experience (that the `self()` function is allowed in guard clauses, but it causes a compilation issue in _this particular guard test_). I would like to understand what the documentation is trying to say, and perhaps get a change in to communicate _why_ this guard does not allow the `self()` function.

**To Reproduce**
```sh
> cd $src/scratch/
> mkdir -p erlang_repro/assert_match_fail
> cd erlang_repro/assert_match_fail
> rebar3 new lib
===> Writing mylib/src/mylib.erl
===> Writing mylib/src/mylib.app.src
===> Writing mylib/rebar.config
===> Writing mylib/.gitignore
===> Writing mylib/LICENSE
===> Writing mylib/README.md
> cd mylib
> ls
LICENSE      README.md    rebar.config src
> mkdir test
> echo '-module(ca_data).
-export([delete_ca_data/1]).

% ...

-define(NEGATIVE_ID_ERROR, error).

delete_ca_data(N) when N < 1 -> ?NEGATIVE_ID_ERROR;
delete_ca_data(N) -> util_db_generic:delete_object(ca_data, N, fun(_) -> ok end).

% ...
' > src/ca_data.erl
> echo '-module(util_db_generic).

-export([delete_object/3]).

delete_object(_, _, _) -> ok.
' > src/util_db_generic.erl
> echo '-module(ca_data_tests).

-include_lib("eunit/include/eunit.hrl").

wrap_meck(MockMod, MockArgs, F) ->
    meck:new(MockMod, MockArgs),
    try
        F()
    catch Ex ->
        throw(Ex)
    after
        meck:unload(MockMod)
    end.

-define(NEGATIVE_ID_ERROR, error).

delete_ca_data_test() ->
    F = fun() ->
        meck:expect(util_db_generic, delete_object, fun (_, _, _) -> ok end),

        ?assertEqual(?NEGATIVE_ID_ERROR, ca_data:delete_ca_data(-1)),

        ?assertMatch([], meck:history(util_db_generic)),

        meck:expect(util_db_generic, delete_object, fun(_, _, _) -> ok end),
        ?assertEqual(ok, ca_data:delete_ca_data(1)),

        ?assertMatch(
            [{self(), {util_db_generic, delete_object, [ca_data, 1, _]}, ok}], % Uh-oh
            meck:history(util_db_generic)
        )
    end,
    wrap_meck(util_db_generic, [], F).
' > test/ca_data_tests.erl
> echo '{erl_opts, [debug_info]}.
{deps, []}.
{profiles, [
    {test, [{erl_opts, []},
            {relx, [{dev_mode, true}]},
            {deps, [meck]}]}
]}.
' > rebar.config
> rebar3 compile
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling mylib
> rebar3 eunit
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling mylib
===> Compiling test/ca_data_tests.erl failed
test/ca_data_tests.erl:29:15: illegal pattern

>
```

**Expected behavior**
I expect this code to compile with the `self()` function in the guard, since the docs say `self()` can be used in guards.

**Affected versions**
```sh
> rebar3 version
rebar 3.18.0 on Erlang/OTP 24 Erts 12.3.1
```
**Additional context**
I'm on a Mac? I've seen this in compilers going back to erlang 20-something, and those compilers were running in docker containers. Not sure if this is helpful. Let me know if you need more info from me to repro this.

**Comment by distortedsignal** [comment]
More interesting notes: if I bind the return from `self()` to a variable, I can use it in the `assertMatch` macro, but I cannot use the function. So this works:

```erl
        Self = self(),
        ?assertMatch(
            [{Self, {util_db_generic, delete_object, [ca_data, 1, fun(_) -> ok end]}, ok}], % Former Uh-oh, but we're ok now!
            meck:history(util_db_generic)
        )
```

but this doesn't work:

```erl
        ?assertMatch(
            [{self(), {util_db_generic, delete_object, [ca_data, 1, fun(_) -> ok end]}, ok}], % Uh-oh
            meck:history(util_db_generic)
        )
```

**Comment by eproxus** [comment]
Note that a `GuardPattern` refers to a pattern match plus optional guard test of the form `Pattern when Guards`. The documentation is correct in that `self()` is only allowed in guards (i.e. any expressions after the `when` keyword), not in the pattern itself (because function calls are not allowed there).

The `?asserMatch` macro allows the first argument to be a `GuardPattern` as would be allowed in this expression:

```erl
case Expr of
    GuardPattern ->
        ResultExpr
    % or expanded:
    Pattern when Guards ->
        ResultExpr
end
```

That is, `self()` (and any other functions allowed in guards) can only occur in the `Guards` above. On top of that, commas are not allowed between the guards because that would be interpreted as delimiters between the macro arguments instead.

In my opinion the documentation is correct. But perhaps it could be improved in some way.

**Comment by IngelaAndin** [comment]
Feel free to make PR if you think the documentation could be improved to make things easier to understand.
