### ISSUE TITLE
ssl: Configurable seed for TLS 1.3 stateless session tickets encryption

### ISSUE THREAD

**Issue by ahovgaard** [erlang/otp#5962]
**Is your feature request related to a problem? Please describe.**

The TLS 1.3 stateless session tickets in OTP are not truly stateless in the sense that the listener's session tickets tracker process has state (the IV and shard seed) needed to encrypt/decrypt the session tickets. This seed is generated on calling `ssl:listen/2`, with option `{session_tickets, stateless}`, when starting the session tickets tracker (`tls_server_session_ticket`) for the listener.

`tls_server_session_ticket.erl`:
```erlang
inital_state([stateless, Lifetime, _, MaxEarlyDataSize, undefined]) ->
    #state{nonce = 0,
           stateless = #{seed => {crypto:strong_rand_bytes(16), 
                                  crypto:strong_rand_bytes(32)},
                         window => undefined},
           lifetime = Lifetime,
           max_early_data_size = MaxEarlyDataSize
          };
```

This prevents using stateless session resumption across multiple server instances.

**Describe the solution you'd like**

The server session ticket encryption seed could be made configurable, e.g., by providing the seed shard and IV in the `ssl:listen/2` options:
```erlang
IV = crypto:strong_rand_bytes(16),
Shard = crypto:strong_rand_bytes(32),
ssl:listen(Port, [{session_tickets, stateless}, {stateless_session_tickets_seed, {IV, Shard}}, ...]).
```

**Describe alternatives you've considered**

It was considered making the seed configurable for the `ssl` application, however this would mean that all `ssl` listeners within an application would have the same seed, which may not be what you would want.

**Additional context**

Suggestions for alternative solutions to achieving the same goal would be appreciated.

I will begin working on a draft PR implementing the solution described above.

**Comment by ahovgaard** [comment]
This feature request was previously mentioned as part of the broader feature request #5870. The scope of this request is narrowed to be only about configuring the tickets encryption seed.

**Comment by ahovgaard** [comment]
I am wondering how this proposed `stateless_tickets_seed` option could be improved to make it less coupled with internal implementation details of `ssl`. With the initial idea described above, the user would need to read the documentation and know that the IV and shard need to be random 16 and 32 byte binaries, respectively. Furthermore, this makes it more difficult to change the implementation of ticket encryption later on.

Perhaps it could be simplified to just require that the user provides a randomly generated binary (or `iodata()`) seed
```erlang
Seed = crypto:strong_rand_bytes(32),
ssl:listen(Port, [{session_tickets, stateless}, {stateless_tickets_seed, Seed}, ...]),
```
which could then be hashed into the shard and IV in `tls_server_session_ticket` as needed:
```erlang
<<Shard:32/binary, IV:16/binary, _/binary>> = crypto:hash(sha512, Seed).
```

Suggestions and other ideas are very welcome.

**Comment by IngelaAndin** [comment]
We have been very busy with the OTP-25 deadline. We will start taking a look at this hopefully next week.
