### ISSUE TITLE
ssl:cipher_suites(all, Version, openssl) is very slow and unstable

### ISSUE THREAD

**Issue by zhongwencool** [erlang/otp#5971]
**Describe the bug**
ssl:cipher_suites(all, Version, openssl) is very slow and unstable.

**To Reproduce**
Steps to reproduce the behavior.
```erlang
Erlang/OTP 24 [erts-12.3.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Eshell V12.3.1  (abort with ^G)
1> rp(fun() -> lists:sort(lists:map(
fun(_) -> erlang:garbage_collect(), 
element(1, timer:tc(fun() -> [ssl:cipher_suites(all, V, openssl) || V <- ['tlsv1.3','tlsv1.2','tlsv1.1',tlsv1]] end)) end, 
lists:seq(1,100))) end()).
[352,361,364,366,366,367,368,368,370,370,370,372,372,372,
 373,373,374,374,375,376,377,378,379,379,379,379,380,380,387,
 389,389,391,392,394,402,402,404,404,406,407,411,417,417,419,
 419,420,423,424,425,427,428,429,433,437,438,438,447,448,450,
 458,461,461,463,476,481,483,491,495,503,508,510,511,518,537,
 539,543,552,565,569,588,592,602,603,608,619,625,632,633,635,
 651,672,705,815,861,883,954,975,1173,1179,1228]
```
I also run `fprof `:
```erlang
Seq = lists:seq(1, 100),
fprof:start(),
fprof:trace([start, {procs, self()}]),
 [begin
         [ssl:cipher_suites(all, V, openssl) || V <- ['tlsv1.3','tlsv1.2','tlsv1.1',tlsv1]]
  end || _ <- Seq],
 fprof:profile(),
 fprof:analyse([totals, {dest, "/tmp/cipher_suites.prof"}]),
```
[cipher_suites.prof.zip](https://github.com/erlang/otp/files/8644590/cipher_suites.prof.zip)
<img width="889" alt="image" src="https://user-images.githubusercontent.com/3116225/167242190-d6f1a438-7f11-4c5f-8483-d4c490ef68c9.png">

**Expected behavior**
Hopefully, this function will be faster and more stable( <100 microseconds).

**Affected versions**
The OTP versions that are affected by this bug.

**Additional context**

Add any other context about the problem here. If you wish to attach Erlang code you can either write it directly in the post using [code tags](https://guides.github.com/features/mastering-markdown/), create a [gist](https://gist.github.com), or attach it as a zip file to this post.

**Comment by IngelaAndin** [comment]
Firstly why do you think it is important that this utility function should be fast? And what do you mean by unstable? The there existed a bug in some erlang version? That it does not execute in constant time? 
This function is mainly to make it easier to compare available cipher suites with what OpenSSL calls them. And historically their naming conventions are not very straightforward.

**Comment by zhongwencool** [comment]
I have a function call `ssl:cipher_suites/3` 1000 times to generate a big schema json.  I find it very slow. so I fprof to find why. 
Of course, I could have cached the result myself, and I had done this cache optimization,
but one thing I don't quite understand is why the same input/l output function can consume time ranging from 300 to 1200 microseconds. **4 times** the difference.
In my opinion, at least the consumption time should be fixed, right?

**Comment by jhogberg** [comment]
> but one thing I don't quite understand is why the same input/l output function can consume time ranging from 300 to 1200 microseconds. 4 times the difference.

It makes a lot more sense when you remove the sorting:

```
Erlang/OTP 25 [RELEASE CANDIDATE 3] [erts-12.3.2] [source-612dc7f5ec] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Eshell V12.3.2  (abort with ^G)
1> BenchFun = fun() -> lists:map(
1> fun(_) -> erlang:garbage_collect(), 
1> element(1, timer:tc(fun() -> [ssl:cipher_suites(all, V, openssl) || V <- ['tlsv1.3','tlsv1.2','tlsv1.1',tlsv1]] end)) end, 
1> lists:seq(1,100)) end.
#Fun<erl_eval.43.110466490>
2> 
2> %% Dry run to ensure all modules are loaded.
2> [ssl:cipher_suites(all, V, openssl) || V <- ['tlsv1.3','tlsv1.2','tlsv1.1',tlsv1]], ok.
ok
3> 
3> timer:sleep(1000), rp(BenchFun()).
[2156,1817,1629,1599,1851,1795,1935,1718,1613,1622,1735,
 1442,1470,1447,1496,1690,1420,1163,1024,1100,943,776,787,
 782,746,781,702,621,628,614,636,625,666,614,873,552,525,526,
 533,511,520,467,446,510,497,506,455,440,439,442,458,396,398,
 399,393,401,395,401,430,397,393,412,362,369,390,370,445,365,
 371,369,374,361,368,376,364,374,373,370,383,372,372,373,370,
 382,378,373,376,376,382,377,386,361,353,353,359,366,360,367,
 362,365]
ok
```

Notice how it's slower in the beginning and gradually getting faster? Most modern processors run in a low performance mode to save power until there's a lot of work to do, and it takes a short while (tens of milliseconds) for them to gradually switch to high-performance mode.

If we change the system configuration to run in high-performance mode all the time, we get the predictable performance you were after:

```
4> timer:sleep(1000), rp(BenchFun()).
[322,294,268,262,303,296,269,267,263,267,306,266,262,277,
 280,306,273,308,277,293,270,280,351,271,262,269,382,271,270,
 270,269,272,279,270,266,268,274,273,275,272,266,269,268,299,
 301,306,275,264,298,271,277,272,277,275,279,278,275,273,302,
 273,276,277,272,270,275,271,275,269,270,270,275,339,270,279,
 276,279,278,279,281,275,275,275,271,277,278,273,279,299,280,
 279,274,281,269,268,268,280,270,276,272,279]
ok
6> timer:sleep(1000), rp(BenchFun()).
[319,292,265,261,291,296,266,264,260,265,293,298,265,265,
 277,303,271,306,274,292,268,268,276,280,265,271,276,270,270,
 271,269,270,279,269,265,263,272,280,276,271,265,268,268,296,
 297,342,299,271,270,318,278,272,278,274,279,278,274,273,300,
 274,277,272,277,272,275,271,276,267,271,305,276,268,270,278,
 272,287,277,278,280,274,275,275,271,278,276,272,279,278,282,
 279,273,280,268,344,268,280,304,275,306,279]
```

**Comment by zhongwencool** [comment]
Okay, I understand, thanks for the detailed answer! 👍
