### ISSUE TITLE
Running smoke tests fails

### ISSUE THREAD

**Issue by VlkrS** [erlang/otp#5973]
**Describe the bug**
running smoke tests as described in the build instructions fails when compiling `ei_decode_encode_SUITE` with:

```
1>
Common Test: Running make in test directories...
1> Recompile: ei_decode_encode_SUITE
1> ei_decode_encode_SUITE.erl:25: can't find include file "ei_decode_encode_SUITE_data/ei_decode_encode_test_cases.hrl"

```

**To Reproduce**
```
cd otp_src_21.3.8.24
export ERL_TOP=`pwd`
make release_tests
cd release/tests/test_server
$ERL_TOP/bin/erl -s ts install -s ts smoke_test batch -s init stop
```

**Expected behavior**
No build failure when running tests

**Affected versions**
Only tried with erlang 21.3.8.24 built on OpenBSD -current

**Additional context**
Couldn't find a file named `ei_decode_encode_test_cases.hrl` anywhere in the files extracted from 
https://github.com/erlang/otp/releases/download/OTP-21.3.8.24/otp_src_21.3.8.24.tar.gz

**Comment by garazdawi** [comment]
Running the commands you've listed (adding a `./configure && make`) I don't get any failures on my machine, but it is a Linux and not BSD. Can you post everything that is printed to the console when running the tests?

There should be a section looking like this:
```text
erlc -W init_tc.erl
erl -noinput -pa ../all_SUITE_data -s init_tc run ei_accept_test -s erlang halt
erl -noinput -pa ../all_SUITE_data -s init_tc run ei_connect_test -s erlang halt 
erl -noinput -pa ../all_SUITE_data -s init_tc run ei_decode_test -s erlang halt
erl -noinput -pa ../all_SUITE_data -s init_tc run ei_decode_encode_test -s erlang halt
erl -noinput -pa ../all_SUITE_data -s init_tc run ei_encode_test -s erlang halt
erl -noinput -pa ../all_SUITE_data -s init_tc run ei_format_test -s erlang halt
erl -noinput -pa ../all_SUITE_data -s init_tc run ei_print_test -s erlang halt
erl -noinput -pa ../all_SUITE_data -s init_tc run ei_tmo_test -s erlang halt
erl -noinput -pa ../all_SUITE_data -s init_tc run erl_connect_test -s erlang halt
erl -noinput -pa ../all_SUITE_data -s init_tc run eterm_test -s erlang halt
erl -noinput -pa ../all_SUITE_data -s init_tc run ext_test -s erlang halt
erl -noinput -pa ../all_SUITE_data -s init_tc run format_test -s erlang halt
erl -noinput -pa ../all_SUITE_data -s init_tc run erl_global_test -s erlang halt 
erl -noinput -pa ../all_SUITE_data -s init_tc run match_test -s erlang halt
```
which is when the file that is missing is generated.

**Comment by VlkrS** [comment]
That was a problem between keyboard and chair, but I needed your question to figure that out.
The OpenBSD port renames the binaries to erl21 and erlc21, but at test time, erlc failed to find a binary named erl21.

Sorry to bother you about that - tests build and mostly run fine now!
