### ISSUE TITLE
OTP-25.0 miscompiles record creation with unused defaults

### ISSUE THREAD

**Issue by mikpe** [erlang/otp#6000]
**Describe the bug**
We have some code which uses `_ = error(...)` in record constructions to catch failures to explicitly initialize all fields. This worked fine with OTP-25.0-rc3 and previous releases. However, with OTP-25.0 the compiler doesn't realize that all fields _are_ initialized and instead considers the record constructions to always fail. This initially showed up as a compile error with OTP-25.0 (we don't allow warnings), but  the generated code is also wrong: it throws an error when it should not.

**To Reproduce**
```
> cat foo.erl
-module(foo).
-export([foo/2]).
-record(rec, {field}).

foo(X, Y) ->
  Z = X - Y,
  nop(#rec{field = 42, _ = error(uninitialized_field)}),
  Z.

nop(_) -> ok.
> /tmp/otp25/bin/erl
Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Eshell V13.0  (abort with ^G)
1> c(foo).
foo.erl:6:9: Warning: the result of evaluating operator '-'/2 is ignored (suppress the warning by assigning the expression to the _ variable)
%    6|   Z = X - Y,
%     |         ^

{ok,foo}
2> foo:foo(5, 2).
** exception error: uninitialized_field
     in function  foo:foo/2 (foo.erl, line 7)
3>
```

**Expected behavior**
```
> /tmp/otp25rc3/bin/erl
Erlang/OTP 25 [RELEASE CANDIDATE 3] [erts-13.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Eshell V13.0  (abort with ^G)
1> c(foo).
{ok,foo}
2> foo:foo(5, 3).
2
3>
```

**Affected versions**
OTP-25.0

**Additional context**
The unexpected warning from OTP-25.0 caused one of our modules to fail to compile, while OTP-25.0-rc3 was ok (as are OTP-24 and OTP-23). A `git bisect` identified the starting point of that failure as:

`# first bad commit: [ffb60e3537d65e7c34c8e50f86572be8dc42acc4] Fix multi-init record initialization edge case`

**Comment by bjorng** [comment]
My intention with the commit was to make code such as the following possible to compile:

```
#rec{field=value,_=V=something},
V.
```

In OTP 24 and earlier, attempting to compile such code would crash the compiler.

My "solution" didn't consider your use case.

I will revert the commit in OTP 25.1 or in a patch, and I will probably change `erl_lint` to properly reject the example above (instead of letting the compiler crash later).

**Comment by essen** [comment]
What does this end up returning? `something`? I'm confused at what the `_` means as well.

```
#rec{field=value,_=V=something},
V.
```

**Comment by mikpe** [comment]
> What does this end up returning? `something`? I'm confused at what the `_` means as well.
> 
> ```
> #rec{field=value,_=V=something},
> V.
> ```

In record construction, `_ = Default` means that fields that haven't been explicitly assigned are assigned `Default`. Given `-record(foo,{x,y,z})`, `#foo{x=42,_=Bar}` is expanded to `#foo{x=42,y=Bar,z=Bar}`. This is most commonly used to create record patterns with wildcards for uninteresting fields in match specs, but it also works in expressions.

Björn's example ought to return `something`.

**Comment by bjorng** [comment]
> Björn's example ought to return `something`.

Yes, it does in OTP 25.0. In OTP 24 and earlier the compiler crashes.

**Comment by crownedgrouse** [comment]
Not a good idea to do this after rc3 in an untested final release...

**Comment by bjorng** [comment]
> Not a good idea to do this after rc3 in an untested final release...

Yes, I agree.

**Comment by bjorng** [comment]
The pull request linked to this issue fixes the problem. It will be released in the next emergency patch.

**Comment by bjorng** [comment]
The fix is merged to maint and master, and placed in the queue for the next emergency patch.
