### ISSUE TITLE
Error install 24.1 on MacOS BigSur

### ISSUE THREAD

**Issue by spencerdcarlson** [erlang/otp#6005]
**Describe the bug**
OTP 24.1 build failing on MacOS

Here is my error log:
>gen/wxe_wrapper_5.cpp:2165:29: error: taking the address of a temporary object of type 'wxBitmap' [-Waddress-of-temporary]
  const wxBitmap * Result = &This->GetBitmap();
                            ^~~~~~~~~~~~~~~~~~

**To Reproduce**
```
sw_vers
ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165
```

```
asdf install erlang 24.1
```

**Affected versions**
24.1

**Additional context**
I believe that https://github.com/erlang/otp/commit/c2eb69239622046093c25e986dd606ea339c59a9# needs to be applied to old tags. If I hot patch I can run 
```
./configure && \
  make && \
  make 
```

**Comment by michaelklishin** [comment]
Are there any reasons to use 24.1 over 24.3 where this is no longer an issue?

**Comment by dgud** [comment]
Yes, this was patched in latest 24 patch, i.e. 24.3.4.
If you want the fix anywhere else you will have pickup wx from that release.

**Comment by SyedMuhamadYasir** [comment]
how do i pick up the WX from that release ?

please advise
