### ISSUE TITLE
:inets.start(:ftpc, ...) stopped working in Erlang 25

### ISSUE THREAD

**Issue by AndrewDryga** [erlang/otp#6011]
We were using the ftpc in our tests which stopped working after we upgraded to Erlang 25 (specifically v1.13.4-otp-25 from https://repo.hex.pm/builds/elixir/builds.txt):
```
     ** (UndefinedFunctionError) function :ftpc.start_service/1 is undefined (module :ftpc is not available)
     stacktrace:
       :ftpc.start_service([host: 'localhost', port: 21212, verbose: false, mode: :passive])
```

While `:ftp` module exists and is available: 
```
iex(1)> :ftp.stop()
{:error, {:not_started, :ftp}}
```

I've checked the changelog and can't find any notes about changes to `:inets`, `:ftp` or `:ftpc`. Is this some sort of compilation issue with Hex-provided Erlang releases or there is a breaking change missing from the changelog?

**Comment by garazdawi** [comment]
Since Erlang/OTP 21 all ftp functionality has been moved into a [separate application](https://www.erlang.org/patches/otp-21.0#ftp-1.0). In Erlang/OTP 24.0 the support for accessing that application through inets [was dropped](https://www.erlang.org/patches/otp-24.0#OTP-16722).

**Comment by IngelaAndin** [comment]
Also, there has never existed a module called ftpc (inets used to map it to ftp). And in OTP-24 we also deprecated ftp:start_service and ftp:stop_service functions that accidentally were preserved in the ftp-application. 

ftp:start_service/1 (use ftp:open/2 instead)
ftp:stop_service/1 (use ftp:close/1 instead)

**Comment by IngelaAndin** [comment]
Release note from inets:

Inets 7.4

Drop all support for ftp and tftp in inets code.

Own Id: OTP-16722

ftp:start_service/1 and ftp:stop_service/1  are scheduled for removal in OTP-26 and are now only wrappers for ftp:open and ftp:close. These functions only made sense for inets application as it was sort of an umbrella application (now it is more of a HTTP application).  
https://www.erlang.org/doc/general_info/scheduled_for_removal.html

**Comment by AndrewDryga** [comment]
Thank you! Indeed the container jumped over 24 too, I did not notice that.

@IngelaAndin we were not using `:ftpc` directly, instead, we accessed it through inets like so:
```
{:ok, ftp_client_pid} =
      :inets.start(:ftpc, host: 'localhost', port: 21212, verbose: false, mode: mode)
```
