### ISSUE TITLE
TLS 1.3 stateless session resumption with anti_replay ignores ticket lifetime

### ISSUE THREAD

**Issue by sindrip** [erlang/otp#6014]
**Describe the bug**
When using TLS 1.3 session resumption with `anti_replay` enabled, the ticket is only valid for `WindowSize` seconds (see: https://www.erlang.org/doc/man/ssl.html#type-anti_replay).

Note that at the bottom I have a proposed resolution to the problem.

**To Reproduce**
We can use the test setup from #5943 with slight modifications.
 
Generate some test certificates:

```shell
openssl req -x509 -newkey rsa:4096 \
    -keyout rootCA.key -out rootCA.pem \
    -sha256 -days 365 -nodes \
    -subj '/CN=Test root CA'

openssl genrsa -out server.key 2048
openssl req -new -key server.key -out server.csr \
    -subj "/CN=Test server"

openssl x509 -req -in server.csr \
    -CA rootCA.pem -CAkey rootCA.key \
    -CAcreateserial -out server.pem -days 1000 -sha256
```

`server.erl`:

```erlang
-module(server).

-export([run/0,
         run_anti_replay/0,
         start_trace/0,
         stop_trace/0]).

run() ->
    application:ensure_all_started(ssl),
    LOpts = [{cacertfile, "rootCA.pem"},
             {certfile, "server.pem"},
             {keyfile, "server.key"},
             {versions, ['tlsv1.3']},
             {session_tickets, stateless}],
    {ok, LSock} = ssl:listen(8001, LOpts),
    handle(LSock).

run_anti_replay() ->
    application:ensure_all_started(ssl),
    LOpts = [{cacertfile, "rootCA.pem"},
             {certfile, "server.pem"},
             {keyfile, "server.key"},
             {versions, ['tlsv1.3']},
             {session_tickets, stateless},
             {anti_replay, {10, 5, 72985}}], % {10, 5, 72985} is equivalent to the 10k default
    {ok, LSock} = ssl:listen(8001, LOpts),
    handle(LSock).

handle(LSock) ->
    {ok, CSock} = ssl:transport_accept(LSock),
    {ok, Sock} = ssl:handshake(CSock),
    {ok, Opts} = ssl:connection_information(Sock, [session_resumption]),
    io:format('Connected with session resumption ~p~n', [Opts]),
    handle(LSock).

start_trace() ->
    dbg:tracer(),
    dbg:p(all, [c]),
    dbg:tpl({tls_server_session_ticket, stateless_living_ticket, '_'}, [{'_',[],[{return_trace}]}]).

stop_trace() ->
    dbg:stop_clear().
```

Start tracing and run the server:

```
1> c(server).
{ok,server}
2> server:start_trace().
{ok,[{matched,nonode@nohost,1},{saved,1}]}
3> server:run().
```

Connect with OpenSSL `s_client`, waiting 15 seconds before trying to reconnect and resuming the session:

```shell
sleep 3s | openssl s_client -tls1_3 -connect localhost:8001 -sess_out sess1.pem -debug
sleep 15s
sleep 3s | openssl s_client -tls1_3 -connect localhost:8001 -sess_in sess1.pem -debug
```

The server shows that the connection succeeded to use session resumption:

```
Connected with session resumption [{session_resumption,false}]
(<0.120.0>) call tls_server_session_ticket:stateless_living_ticket(1956700463,1956683463,7200,1653382359,undefined)
(<0.120.0>) returned from tls_server_session_ticket:stateless_living_ticket/5 -> true
Connected with session resumption [{session_resumption,true}]

```

If we now start a new server with `anti_replay` enabled with `server:run_anti_replay()`

```
1> c(server).
{ok,server}
2> server:start_trace().
{ok,[{matched,nonode@nohost,1},{saved,1}]}
3> server:run_anti_replay().
```

The server shows that the connection failed to use session resumption:

```
Connected with session resumption [{session_resumption,false}]
(<0.120.0>) call tls_server_session_ticket:stateless_living_ticket(1176305235,1176288235,7200,1653382568,10)
(<0.120.0>) returned from tls_server_session_ticket:stateless_living_ticket/5 -> false
Connected with session resumption [{session_resumption,false}]
```

**Expected behavior**
Enabling `anti_replay` does not change the behavior of normal client flows.

**Affected versions**
Tested on master (`38f6106`) and a fork of `24.1.3`

**Additional context**
This is the current implementation

`tls_server_session_ticket.erl`
```erlang
stateless_living_ticket(0, _, _, _, _) ->
    true;
stateless_living_ticket(ObfAge, TicketAgeAdd, Lifetime, Timestamp, Window) ->
    ReportedAge = ObfAge - TicketAgeAdd,
    RealAge = erlang:system_time(second) - Timestamp,
    (ReportedAge =< Lifetime * 1000)
        andalso (RealAge =< Lifetime)
        andalso (in_window(RealAge, Window)).
```

A proposed solution would be to subtract the ReportedAge in seconds from RealAge and take the absolute value.

```erlang
stateless_living_ticket(ObfAge, TicketAgeAdd, Lifetime, Timestamp, Window) ->
    ...
    DriftTime = abs(RealAge - (ReportedAge / 1000)),
    (ReportedAge =< Lifetime * 1000)
        andalso (RealAge =< Lifetime)
        andalso (in_window(DriftTime, Window)).

```

The above change fixes the simple example that is presented above, but might not be the ideal solution due to client-side clock drift.

**Comment by IngelaAndin** [comment]
Thank you for your report and PR we will start by running your PR in our builds.  And we will discuss your solution within our team and see what we come up with.

**Comment by u3s** [comment]
I don't understand this issue report. After reading `tls_bloom_filter` and how it used in `tls_server_session_ticket` I think dropping tickets older than Window number of seconds (current behavior reported as error) prevents us from receiving false negatives.

For tickets older than Window parameter (used for rotating bloom filters data structures), we might not have access to filter that contained information about using the ticket - treat it as unused, while it was used but filter that stored information about usage was rotated out.

Please explain if I'm missing something ...
I used this as reference for rotating bloom filter https://programming.guide/sliding-bloom-filter.html

**Comment by sindrip** [comment]
After WindowSize seconds since ticket creation, stateless_living_ticket will always return false for that specific ticket. Stateless_usable_ticket then always returns false.

**Comment by u3s** [comment]
But before WindowSize passes - you can use the stateless ticket with anti_replay feature enabled ?

I'm reading `anti_replay` feature as something protecting from re-using same ticket more than once.
If we don't reject tickets older than WindowSize seconds, than every ticket (used or unused) could be replayed for establishing connection after `2*WindowSize` ... this is how I'm reading that code.

**Comment by IngelaAndin** [comment]
>My understanding is that anti_replay is to protect against replays of the ClientHello >itself, which contains the ticket.

I do not agree!  

Section 8
As noted in Section 2.3 and Appendix E.5, TLS does not provide
inherent replay protections for 0-RTT data.  (That is so-called early data).

 Section 8.1  outlines the simplest form of anti-replay defense (which requires statefulness).

Section 8.2 
Outlines another approach of anti-replay defense.

**Comment by IngelaAndin** [comment]
hum ... I think this could be a refactor gone bad!  I will come back to this tomorrow!

**Comment by peterdmv** [comment]
> Isn't it the case that Section 8.2 is what the current implementation is based on? More specifically:

That is correct, current implementation records the PSK binder and I believe this implicitly prevents any re-use of the same stateless ticket as an attacker needs to have access to the _resumption_master_secret_ that is needed to calculate the _PSK_ that is used to derive the _binder_key_ that is used to compute the PSK Binder (= HMAC(binder_key, Transcript-Hash)).

> And RealAge, is the server's calculated age of the ticket since it was generated. If RealAge is greater than the configured Window, stateless_living_ticket returns false even if we assume the ticket has not exceeded its lifetime and has never been used (which doesn't matter at this point as we will not check the bloom filter if this function returns false). This implicitly sets the lifetime of all tickets to WindowSize.

I think the key here is that Freshness Check is a mechanism that is not connected to the ticket lifetime. It is more strict and meant to efficiently determine **if a ClientHello was likely sent reasonably recently**. Freshness Check is also tightly coupled with the implemented storage mechanism, a pair of rotating Bloom Filters. If the window is too large, the bloom filter could fill up and false positivity rate could reach unacceptable levels. All this is summarized in Section 8.3:
```
   8.3 Freshness Checks

   Because the ClientHello indicates the time at which the client sent
   it, it is possible to efficiently determine whether a ClientHello was
   likely sent reasonably recently and only accept 0-RTT for such a
   ClientHello, otherwise falling back to a 1-RTT handshake.  This is
   necessary for the ClientHello storage mechanism described in
   Section 8.2 because otherwise the server needs to store an unlimited
   number of ClientHellos, and is a useful optimization for self-
   contained single-use tickets because it allows efficient rejection of
   ClientHellos which cannot be used for 0-RTT.
```

My current opinion is that the proposed change would enable replay attacks with ClientHello messages that are replayed  _2*WindowTime_ after packet capture but not later then _TicketLifeTime_.

**Comment by sindrip** [comment]
> > Isn't it the case that Section 8.2 is what the current implementation is based on? More specifically:
> 
> That is correct, current implementation records the PSK binder and I believe this implicitly prevents any re-use of the same stateless ticket as an attacker needs to have access to the _resumption_master_secret_ that is needed to calculate the _PSK_ that is used to derive the _binder_key_ that is used to compute the PSK Binder (= HMAC(binder_key, Transcript-Hash)).

Yes, I agree that it prevents an attacker to re-use the ticket. It does not prevent all re-use as you imply, as the client who does have access to the _resumption_master_secret_ is able to re-use it. This is easy to verify by using the same ticket multiple times, for example by running the following script against the server in the initial report.

```sh
sleep 3s | openssl s_client -tls1_3 -connect localhost:8001 -sess_out sess1.pem > /dev/null 2>&1

cp sess1.pem sess1_backup.pem
openssl sess_id -in sess1.pem -text

sleep 1s | openssl s_client -tls1_3 -connect localhost:8001 -sess_in sess1.pem > /dev/null 2>&1
openssl sess_id -in sess1.pem -text

rm sess1.pem && mv sess1_backup.pem sess1.pem

sleep 1s | openssl s_client -tls1_3 -connect localhost:8001 -sess_in sess1.pem > /dev/null 2>&1
openssl sess_id -in sess1.pem -text

```
Which is a re-use by the client with access to the _resumption_master_secret_.
```
1> c(server).
{ok,server}
2> server:start_trace().
{ok,[{matched,nonode@nohost,1},{saved,1}]}
3> server:run_anti_replay().
Connected with session resumption [{session_resumption,false}]
(<0.119.0>) call tls_server_session_ticket:stateless_living_ticket(735383898,735381898,7200,1655475358,10)
(<0.119.0>) returned from tls_server_session_ticket:stateless_living_ticket/5 -> true
Connected with session resumption [{session_resumption,true}]
(<0.119.0>) call tls_server_session_ticket:stateless_living_ticket(735384898,735381898,7200,1655475358,10)
(<0.119.0>) returned from tls_server_session_ticket:stateless_living_ticket/5 -> true
Connected with session resumption [{session_resumption,true}]
```

> > And RealAge, is the server's calculated age of the ticket since it was generated. If RealAge is greater than the configured Window, stateless_living_ticket returns false even if we assume the ticket has not exceeded its lifetime and has never been used (which doesn't matter at this point as we will not check the bloom filter if this function returns false). This implicitly sets the lifetime of all tickets to WindowSize.
> 
> I think the key here is that Freshness Check is a mechanism that is not connected to the ticket lifetime. It is more strict and meant to efficiently determine **if a ClientHello was likely sent reasonably recently**. Freshness Check is also tightly coupled with the implemented storage mechanism, a pair of rotating Bloom Filters. If the window is too large, the bloom filter could fill up and false positivity rate could reach unacceptable levels. All this is summarized in Section 8.3:
> 
> ```
>    8.3 Freshness Checks
> 
>    Because the ClientHello indicates the time at which the client sent
>    it, it is possible to efficiently determine whether a ClientHello was
>    likely sent reasonably recently and only accept 0-RTT for such a
>    ClientHello, otherwise falling back to a 1-RTT handshake.  This is
>    necessary for the ClientHello storage mechanism described in
>    Section 8.2 because otherwise the server needs to store an unlimited
>    number of ClientHellos, and is a useful optimization for self-
>    contained single-use tickets because it allows efficient rejection of
>    ClientHellos which cannot be used for 0-RTT.
> ```

Yes, I have looked at large parts of the implementation and compared it to the RFC and from what I can tell it is perfectly sound. Except for the fact that the `in_window` comparison is nonsensical.

If we inline the `in_window` call we end up with the following implementation:
```erlang
stateless_living_ticket(ObfAge, TicketAgeAdd, Lifetime, Timestamp, Window) ->
    ReportedAge = ObfAge - TicketAgeAdd,
    RealAge = erlang:system_time(second) - Timestamp,
    (ReportedAge =< Lifetime * 1000)
        andalso (RealAge =< Lifetime)
        andalso (RealAge =< Window).
```
I think the problem is quite obvious after we have inlined the function call, but let's consider the implications.

- Window default value is `10`
- Lifetime default value is `7200`
- Given that Lifetime is greater than Window, which with default values is always the case. `RealAge =< Window` implies `RealAge =< Lifetime` and becomes a redundant check.

Now let's simplify the function again by eliminating the unnecessary check and substituting the default value of Window.
```erlang
stateless_living_ticket(ObfAge, TicketAgeAdd, Lifetime, Timestamp, Window) ->
    ReportedAge = ObfAge - TicketAgeAdd,
    RealAge = erlang:system_time(second) - Timestamp,
    (ReportedAge =< Lifetime * 1000)
        andalso (RealAge =< 10).
```
And if you assume that the client is behaving correctly and that `ReportedAge ≈ RealAge` the same argument applies and we can again simplify the function.
```erlang
stateless_living_ticket(ObfAge, TicketAgeAdd, Lifetime, Timestamp, Window) ->
    ReportedAge = ObfAge - TicketAgeAdd,
    RealAge = erlang:system_time(second) - Timestamp,
    RealAge =< 10.
```

- If the function `stateless_living_ticket` returns false, a ticket is not allowed to be used.
- The current implementation always returns false when more than `Window` (10 by default) seconds have passed since the server generated it.
- `Lifetime` is completely ignored in the cases where `Lifetime > Window`.

This simplified implementation is not following Section 8.3's proposed implementation
```
   In order to implement this mechanism, a server needs to store the
   time that the server generated the session ticket, offset by an
   estimate of the round-trip time between client and server.  I.e.,

       adjusted_creation_time = creation_time + estimated_RTT

   This value can be encoded in the ticket, thus avoiding the need to
   keep state for each outstanding ticket.  The server can determine the
   client's view of the age of the ticket by subtracting the ticket's
   "ticket_age_add" value from the "obfuscated_ticket_age" parameter in
   the client's "pre_shared_key" extension.  The server can determine
   the expected_arrival_time of the ClientHello as:

     expected_arrival_time = adjusted_creation_time + clients_ticket_age

   When a new ClientHello is received, the expected_arrival_time is then
   compared against the current server wall clock time and if they
   differ by more than a certain amount, 0-RTT is rejected, though the
   1-RTT handshake can be allowed to complete.
```

Here is an example implementation following the naming scheme of the RFC of the freshness check:

```erlang
stateless_living_ticket(ObfAge, TicketAgeAdd, Lifetime, Timestamp, Window) ->
    EstimatedRTT = 0,
    CreationTime = Timestamp,
    AdjustedCreationTime = CreationTime + EstimatedRTT,
    % ReportedAge = ObfAge - TicketAgeAdd,
    ClientsTicketAge = ((ObfAge - TicketAgeAdd) / 1000), % Convert to seconds
    ExpectedArrivalTime = AdjustedCreationTime + ClientsTicketAge,
    %RealAge = erlang:system_time(second) - Timestamp,
    Difference = abs(ExpectedArrivalTime - erlang:system_time(second))
    Difference =< Window.
```

The obvious optimization is to compare the server and ticket view of the age as we don't have EstimatedRTT data available.

```erlang
stateless_living_ticket(ObfAge, TicketAgeAdd, Lifetime, Timestamp, Window) ->
    ClientsTicketAge = ((ObfAge - TicketAgeAdd) / 1000), % Convert to seconds
    ServerTicketAge = erlang:system_time(second) - Timestamp
    Difference = abs(ServerTicketAge - ClientsTicketAge)
    Difference =< Window.
```

> My current opinion is that the proposed change would enable replay attacks with ClientHello messages that are replayed _2*WindowTime_ after packet capture but not later then _TicketLifeTime_.

In the case that you replay a ClientHello after 2*WindowTime, then `DriftTime >= 2*WindowTime` plus/minus the actual clock drift between the server and client. In my proposed implementation `in_window` then returns false and `stateless_living_ticket` returns false.

**Comment by peterdmv** [comment]
> Yes, I agree that it prevents an attacker to re-use the ticket. It does not prevent all re-use as you imply, as the client who does have access to the resumption_master_secret is able to re-use it. This is easy to verify by using the same ticket multiple times, for example by running the following script against the server in the initial report.

I verified this out of my curiosity. Same session ticket was used multiple times but each ClientHello had a different binder due to the variable parts of the message (_random, session_id, key_share, obfuscated_ticket_age_).

> In the case that you replay a ClientHello after 2*WindowTime, then DriftTime >= 2*WindowTime plus/minus the actual clock drift between the server and client. In my proposed implementation in_window then returns false and stateless_living_ticket returns false.

I think you are right, nice catch! As far as I can recall it, the current implementation has made the following assumptions:

- Clients can lie about the age of the ticket. This was the original reason to put a timestamp into the session ticket and verify it on receipt.
- _Freshness_ was interpreted so that a session ticket (in a ClientHello) was fresh if it was likely sent **back** reasonably recently after the ticket itself was created.

After reading your explanation and the relevant sections of the standard again, I think that the correct interpretation is that a ClientHello is fresh if it was likely **sent** reasonably recently. So it should be allowed to use a ticket after ```2*WindowTime``` as this mechanism protects against replay of ClientHello messages **that were captured** more than ```2*WindowTime``` seconds ago.

Regarding the solution I would prefer using the naming scheme of the RFC and keeping variables even if they are not used for future reference and maintainability e.g. ```EstimatedRTT```.

**Comment by u3s** [comment]
@sindrip - Thanks for patience and detailed explanations!
@peterdmv - also thanks for looking at this one!

I think that in the end I'm agreeing with what is proposed in the issue.

Unfortunately documents seem to be a bit careless when using term
'ticket' instead of 'unique value derived from the ClientHello'.
#### RFC8446 - confusing parts
I've found some parts of RFC8446 which seem to match to our current code
behavior. Am I reading it wrong or is written in a strange fashion?

##### NewSessionTicket (chapter 4)
A server MAY treat a _ticket_ as valid for a shorter period of time than what is
stated in the ticket_lifetime.

##### Client Hello Recording (section 8.2)
Recording all ClientHellos causes state to grow without bound, but a server can
instead record ClientHellos within a given time window and use the
"obfuscated_ticket_age" to ensure that _tickets_ aren’t reused outside that
window.

##### Client Tracking Prevention (C.4)
(not confusing but related)
Clients SHOULD NOT reuse a ticket for multiple connections. Reuse of
a ticket allows passive observers to correlate different connections.
...
Servers SHOULD issue new tickets with every connection.
This ensures that clients are always able to use a new ticket when
creating a new connection.
#### A Survey of TLS 1.3 0-RTT Usage - ETH Zürich
I also found another reference dealing with the topic:

https://ethz.ch/content/dam/ethz/special-interest/infk/inst-infsec/appliedcrypto/education/theses/MihaelLiskij_Thesis.pdf

It covers NSS - Mozilla’s TLS library used in Firefox and other products.
NSS is interesting because it has anti_replay with Bloom filters and stateless
tickets - so could serve as a reference.

In the document, I read ticket-skew as DriftTime variable introduced in PR-6019 (or Difference in code samples
above).

most relevant sections include:
3.2.2 Session Ticket Management
3.2.3 Anti-replay Mechanisms
Contrary to OpenSSL, NSS instead opts for a type of ClientHello recording
anti-replay mechanism which uses two bloom filters to prevent replay
attacks during the ticket-skew window.
...
This is because, during
the ticket-skew window, an adversary can not make the server accept the
same session ticket twice by replaying the packets, since the random nonce
would not have changed; while after the ticket-skew window, the _ticket_ is
no longer valid.

Above confused me again, but I checked NSS source which is aligned with your proposal rather than with how documents might be interpreted ...
https://github.com/nss-dev/nss/blob/be5a5d6a971f6ada66b5440960b4435b7357089f/lib/ssl/tls13replay.c#L200

#### Summary
I will paste also some comments in #6019 .
I'm fine with the issue and conclusion now. @ingela what about you?

**Comment by sindrip** [comment]
> Unfortunately documents seem to be a bit careless when using term 'ticket' instead of 'unique value derived from the ClientHello'.

That's true, but I suppose it's because the implementer is free to choose either.

> #### RFC8446 - confusing parts
> 
> I've found some parts of RFC8446 which seem to match to our current code behavior. Am I reading it wrong or is written in a strange fashion?
> ##### NewSessionTicket (chapter 4)
> 
> A server MAY treat a _ticket_ as valid for a shorter period of time than what is stated in the ticket_lifetime.

Is reasonable, it allows the implementer to reject tickets that come right after server startup for example. It also allows the implementer to use a non-deterministic data-structure like a bloom-filter. I read it as ticket_lifetime is not the only thing to consider when determining if a ticket is valid.

> ##### Client Hello Recording (section 8.2)
> 
> Recording all ClientHellos causes state to grow without bound, but a server can instead record ClientHellos within a given time window and use the "obfuscated_ticket_age" to ensure that _tickets_ aren’t reused outside that window.

This is what is implemented with the rotating bloom filters

> ##### Client Tracking Prevention (C.4)
> 
> (not confusing but related) Clients SHOULD NOT reuse a ticket for multiple connections. Reuse of a ticket allows passive observers to correlate different connections. ... Servers SHOULD issue new tickets with every connection. This ensures that clients are always able to use a new ticket when creating a new connection.

Implies a client can re-use a ticket. But doing so weakens anonymity?

> Above confused me again, but I checked NSS source which is aligned with your proposal rather than with how documents might be interpreted ... https://github.com/nss-dev/nss/blob/be5a5d6a971f6ada66b5440960b4435b7357089f/lib/ssl/tls13replay.c#L200

From reading the comments, it sounds like the same/similar implementation.
