### ISSUE TITLE
Dialyzer: flags missing_return and extra_return go against documentation (they are swapped)

### ISSUE THREAD

**Issue by ilya-klyuchnikov** [erlang/otp#6017]
**Describe the bug**

`-Wextra_return` command line option does what is described for `-Wmissing_return` option in documentation and vice versa.

**To Reproduce**

```erlang
-module(xxx).
-export([foo/1, bar/1]).

-spec foo(integer()) -> integer() | binary().
foo(1) -> 2;
foo(_) -> 4.

-spec bar(any()) -> integer().
bar(1) -> 2;
bar(_) -> ok.
```

```
dialyzer xxx.erl
.. - no warnings
```
----

```
dialyzer -Wmissing_return xxx.erl
xxx.erl:8:2: The success typing for xxx:bar/1 implies that the function might also return 
          'ok' but the specification return is 
          integer()
```

Documentation:

> -Wmissing_return
> Warn about functions whose specification includes types that the function cannot return.

-----

```
dialyzer -Wextra_return xxx.erl
xxx.erl:4:2: The specification for xxx:foo/1 states that the function might also return 
          binary() but the inferred return is 
          2 | 4

```

Documentation:

> -Wextra_return
> Warn about functions that return values that are not part of the specification.

----

The flags are "swapped" in command line

**Expected behavior**
According to documentation - https://www.erlang.org/doc/man/dialyzer.html

**Affected versions**
25.0

**Comment by jhogberg** [comment]
Woops, I'll fix it in https://github.com/erlang/otp/pull/6018. Thanks for your report!

**Comment by ilya-klyuchnikov** [comment]
Closing, - since #6018 has been merged.
