### ISSUE TITLE
Building OTP 25.0 on Ubuntu 22.04 LTS with wxWidgets 3.1.6 causes compilation error

### ISSUE THREAD

**Issue by jj1bdx** [erlang/otp#6022]
**Describe the bug**
Building OTP 25.0 on Ubuntu 22.04 LTS with wxWidgets 3.1.6 wxGTK causes compilation error in `lib/wx/c_src/gen/wxe_wrapper_7.cpp` due to type difference of a class wxBitmap (on wx-3.0) and wxBitmapBundle (on wx-3.1). 

**To Reproduce**

Execution environment:

* Ubuntu 22.04 LTS with uname: `Linux gluonite 5.15.0-33-generic #34-Ubuntu SMP Wed May 18 13:34:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux` (gluonite is my machine name)
* gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
* wxWidgets 3.1.6.0 wxGTK built with the following configure options: `--prefix="/opt/wx-3.1" --enable-compat28 --enable-compat30 --enable-unicode --with-gtk` (GTK version: 3)
* Following GTK packages installed on Ubuntu: libgth-4-dev libgtk-3-dev
* kerl version 2.3.0
* Locally built OpenSSL 1.1.1o under /opt/openssl/1.1.1o

Build shell command using kerl:

```shell
OTP_VERSION=25.0
OPENSSL_LOCAL="/opt/openssl/1.1.1o"
INSTALL_DIR_PREFIX="/home/kenji/otp/"
INSTALL_NAME=${OTP_VERSION}-wxgtk-buildtest
#
env \
    CC=/usr/bin/cc \
    CXX=/usr/bin/c++ \
    CFLAGS="-O3 -fstack-protector-strong" LDFLAGS="-fstack-protector-strong" \
    MAKEFLAGS="-j12" \
    KERL_BUILD_DOCS="yes" \
    KERL_BUILD_PLT="yes" \
    KERL_CONFIGURE_OPTIONS="--disable-debug --disable-silent-rules --enable-m64-build --disable-dynamic-ssl-lib --disable-hipe --disable-vm-probes --enable-kernel-poll --enable-dirty-schedulers --enable-sharing-preserving --enable-lock-counter --enable-esock --without-javac --without-odbc --enable-threads --enable-smp-support --with-wx --with-ssl=${OPENSSL_LOCAL} --with-wx-config=/opt/wx-3.1/bin/wx-config" \
    sh -c "(kerl build git https://github.com/jj1bdx/otp/ OTP-${OTP_VERSION} ${INSTALL_NAME} && kerl install ${INSTALL_NAME} ${INSTALL_DIR_PREFIX}${INSTALL_NAME})"
```

**Expected behavior**

Completing compilation and installation.

**Affected versions**

OTP 25.0

**Additional context**

Relevant part of the compilation log for building by kerl:

```
mkdir -p x86_64-pc-linux-gnu
/usr/bin/c++ -c -Werror=return-type  -Wall -fPIC -m64 -O3 -fstack-protector-strong -Wno-deprecated-declarations -fomit-frame-pointer -fno-strict-aliasing  -D_GNU_SOURCE -D_THREAD_SAFE -D_REENTRANT -DHAVE_GLIB=1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/opt/wx-3.1/lib/wx/include/gtk3-unicode-3.1 -I/opt/wx-3.1/include/wx-3.1 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread  -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DSIZEOF_VOID_P=8 -DHAVE_GL_GL_H=1 -DHAVE_GL_GLU_H=1 -DHAVE_GL_SUPPORT=1 -DHAVE_GLINTPTR=1 -DHAVE_GLINTPTRARB=1 -DHAVE_GLCHAR=1 -DHAVE_GLCHARARB=1 -DHAVE_GLHALFARB=1 -DHAVE_GLINT64EXT=1 -I/home/kenji/.kerl/builds/25.0-wxgtk-buildtest/otp_src_git/erts/emulator/beam -I/home/kenji/.kerl/builds/25.0-wxgtk-buildtest/otp_src_git/erts/include -I/home/kenji/.kerl/builds/25.0-wxgtk-buildtest/otp_src_git/erts/include/x86_64-pc-linux-gnu -I/home/kenji/.kerl/builds/25.0-wxgtk-buildtest/otp_src_git/erts/include/internal -I/home/kenji/.kerl/builds/25.0-wxgtk-buildtest/otp_src_git/erts/include/internal/x86_64-pc-linux-gnu -I/home/kenji/.kerl/builds/25.0-wxgtk-buildtest/otp_src_git/erts/emulator/sys/unix -I/home/kenji/.kerl/builds/25.0-wxgtk-buildtest/otp_src_git/erts/emulator/sys/common  wxe_helpers.cpp -o x86_64-pc-linux-gnu/wxe_helpers.o
gen/wxe_wrapper_7.cpp: In function 'void wxToolBar_AddTool_4(WxeApp*, wxeMemEnv*, wxeCommand&)':
gen/wxe_wrapper_7.cpp:2342:65: error: call of overloaded 'AddTool(int&, wxString&, wxBitmap&, wxString&, wxItemKind&)' is ambiguous
 2342 |   wxToolBarToolBase * Result = (wxToolBarToolBase*)This->AddTool(toolId,label,*bitmap,shortHelp,kind);
      |                                                    ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/wx-3.1/include/wx-3.1/wx/toolbar.h:67,
                 from /opt/wx-3.1/include/wx-3.1/wx/wx.h:87,
                 from gen/wxe_wrapper_7.cpp:23:
/opt/wx-3.1/include/wx-3.1/wx/tbarbase.h:311:24: note: candidate: 'wxToolBarToolBase* wxToolBarBase::AddTool(int, const wxString&, const wxBitmapBundle&, const wxString&, wxItemKind)'
  311 |     wxToolBarToolBase *AddTool(int toolid,
      |                        ^~~~~~~
In file included from /opt/wx-3.1/include/wx-3.1/wx/wx.h:14,
                 from gen/wxe_wrapper_7.cpp:23:
/opt/wx-3.1/include/wx-3.1/wx/tbarbase.h:527:24: note: candidate: 'wxToolBarToolBase* wxToolBarBase::AddTool(int, const wxBitmap&, const wxBitmap&, bool, wxCoord, wxCoord, wxObject*, const wxString&, const wxString&)'
  527 |     wxToolBarToolBase *AddTool(int toolid,
      |                        ^~~~~~~
/opt/wx-3.1/include/wx-3.1/wx/defs.h:648:43: note: in definition of macro 'wxDEPRECATED'
  648 | #define wxDEPRECATED(x) wxDEPRECATED_DECL x
      |                                           ^
/opt/wx-3.1/include/wx-3.1/wx/tbarbase.h:526:5: note: in expansion of macro 'wxDEPRECATED_INLINE'
  526 |     wxDEPRECATED_INLINE(
      |     ^~~~~~~~~~~~~~~~~~~
gmake[3]: *** [Makefile:168: x86_64-pc-linux-gnu/wxe_wrapper_7.o] Error 1
gmake[3]: *** Waiting for unfinished jobs....
gmake[3]: Leaving directory '/home/kenji/.kerl/builds/25.0-wxgtk-buildtest/otp_src_git/lib/wx/c_src'
gmake[2]: *** [/home/kenji/.kerl/builds/25.0-wxgtk-buildtest/otp_src_git/make/otp_subdir.mk:29: opt] Error 2
gmake[2]: Leaving directory '/home/kenji/.kerl/builds/25.0-wxgtk-buildtest/otp_src_git/lib/wx'
gmake[1]: *** [/home/kenji/.kerl/builds/25.0-wxgtk-buildtest/otp_src_git/make/otp_subdir.mk:29: opt] Error 2
gmake[1]: Leaving directory '/home/kenji/.kerl/builds/25.0-wxgtk-buildtest/otp_src_git/lib'
gmake: *** [Makefile:511: libs] Error 2
```

The difference of AddTool() in wx/tbarbase.h between wxWidgets 3.0.5 and 3.1.6 is shown in the following wxWidgets source code portions:

* https://github.com/wxWidgets/wxWidgets/blob/v3.0.5/include/wx/tbarbase.h#L304L313
* https://github.com/wxWidgets/wxWidgets/blob/v3.1.6/include/wx/tbarbase.h#L310L318

Showing the closeup part of the difference:

https://github.com/wxWidgets/wxWidgets/blob/v3.0.5/include/wx/tbarbase.h#L307

and

https://github.com/wxWidgets/wxWidgets/blob/v3.1.6/include/wx/tbarbase.h#L313

The related part of wx module code is here:

https://github.com/erlang/otp/blob/OTP-25.0/lib/wx/c_src/gen/wxe_wrapper_7.cpp#L2308L2346

And the line caused the error is here:

https://github.com/erlang/otp/blob/OTP-25.0/lib/wx/c_src/gen/wxe_wrapper_7.cpp#L2342

The problem is that

https://github.com/erlang/otp/blob/OTP-25.0/lib/wx/c_src/gen/wxe_wrapper_7.cpp#L2323

is for wxWidgets 3.0.5 (using `wxBitmap`) and does not match the declaration of wxWidgets 3.1.6 using `wxBitmapBundle` instead.

I don't know how to fix this bug, so I raise an issue here.
Attached file is a full build log.

[otp_build_git_wx3.1.log](https://github.com/erlang/otp/files/8776116/otp_build_git_wx3.1.log)

**Comment by jj1bdx** [comment]
In https://docs.wxwidgets.org/3.1.6/classwx_bitmap_bundle.html, I've found a following note:

> Also note that the existing code using [wxBitmap](https://docs.wxwidgets.org/3.1.6/classwx_bitmap.html) is compatible with the functions taking [wxBitmapBundle](https://docs.wxwidgets.org/3.1.6/classwx_bitmap_bundle.html) in wxWidgets 3.1.6 and later because bitmaps are implicitly convertible to the objects of this class, so just passing [wxBitmap](https://docs.wxwidgets.org/3.1.6/classwx_bitmap.html) to the functions taking [wxBitmapBundle](https://docs.wxwidgets.org/3.1.6/classwx_bitmap_bundle.html) continues to work and if high resolution versions of bitmap are not (yet) available for the other toolbar tools, single bitmaps can continue to be used instead.

I think this explains why wx module works OK on macOS with Homebrew wxwidgets of 3.1.6.

**Comment by jj1bdx** [comment]
A workaround: https://github.com/erlang/otp/pull/6023

**Comment by dgud** [comment]
Closing this since it build if wxWidgets is compiled without **-enable-compat28** which I don't think will be included/supported 
in the upcoming 3.2 release.

**Comment by Bodhert** [comment]
I am having a similar problem, I am using Sonoma 14.1.1 (m1), erlang 25.3.2.7,  I have not been able to compile erlang passing the `--enable-wx` `--with-wx-config` option
 
 `wx-config --version-full` -> `3.2.4.0`

if managed to compile `erlang 26.1.2` but not the `25.3.2.7`

when I try to compiles it throws the next:
`clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [../priv/aarch64-apple-darwin23.1.0/erl_gl.so] Error 1`

**Comment by dgud** [comment]
See comments in #7748
