### ISSUE TITLE
Cannot compile module without name

### ISSUE THREAD

**Issue by vkatsuba** [erlang/otp#6026]
**Describe the bug**
Not sure that this is a bug but still... Some time ago I was see some twitter post https://twitter.com/elbrujohalcon/status/1522277932139487234?s=12&t=bJtinvtZ_MPlSerfFdOzig where described interesting behavior where user is try to create the module without name and call functions. I was try to reproduce and looks like the module cannot be call.

**To Reproduce**
* Create module `.erl`
* Add structure like:
```erlang
-module('').

-export([''/0]).

''() -> 0.
```
* Try compile module:
```erlang
1> c(''). %% Or c(".erl").
..beam: Module name '' does not match file name '.'
error
```

**Expected behavior**
In the twitter post was show other strange behavior but maybe this is related to specific OS. So, in one hand it is a nonsense to create module without name but in other hand the `''` atom is valid. I suppose it should be possible to create module without name and call as empty atom.

**Affected versions**
The OTP 24.

**Additional context**
The fun point that if add space to module and restore it - all will be working as expected:
* Create module ` .erl`
* Add structure like:
```erlang
-module(' ').

-export([' '/0]).

''() -> 0.
```
* Try compile module:
```erlang
1> c(' '). %% Or c(" .erl").
{ok,' '}
2> ' ':''().
0
```

**Comment by josevalim** [comment]
I wonder if instead of making it work, it should instead raise that the module name cannot be an empty atom? Perhaps the same for functions too.

**Comment by robertoaloi** [comment]
Note: the check is not executed if, for example, you use basic validation:

```
1> c('').
..beam: Module name '' does not match file name '.'
error
2> c('', [basic_validation]).
** Warning: No object file created - nothing loaded **
ok
```

**Comment by bjorng** [comment]
The linked pull request eliminates the bug by forbidding empty module names.
