### ISSUE TITLE
Incorrect specs for `erl_syntax:string_value/1`?

### ISSUE THREAD

**Issue by robertoaloi** [erlang/otp#6042]
The `erl_syntax:string_value/1` function has the following signature:

    -spec string_value(syntaxTree()) -> string().

Given a string _node_, it returns the corresponding _string_. The problem arises if the function is invoked with a tree which does not represent a string. For example:

    > erl_syntax:string_value(erl_syntax:comment(["This is a comment"])).
    {comment,none,["This is a comment"]}

In this case, the function extracts and returns the _data_ from the node, which can be any arbitrary _term()_.

One could protect against this last case by checking the returned value, but then a Dialyzer error similar to the following would probably appear:

> [...] can never match since previous clauses completely covered the type string()

~One may also ensure the `erl_syntax:string_value/1` is only called with a node representing a string, but there seems not to be an API for that (or I failed finding it). `erl_syntax:is_string/2` checks the type but *also* checks the actual value.~

An alternative is to use the `erl_syntax:type/1` to ensure the input node represents a string.

**Comment by bjorng** [comment]
It seems to me that the spec captures the intended use of the function. That is, you should only call it after having called `erl_syntax:type/1` to ensure that the node is indeed a string.

**Comment by robertoaloi** [comment]
Agreed, that should be enough. Thanks for looking into this!
