### ISSUE TITLE
scheduler bind type flag not working on aarch64 machine

### ISSUE THREAD

**Issue by EricLin89** [erlang/otp#6043]
I'm using RabbitMQ 3.8.21 and erlang 23.3. The -stbt flag is the default value (db),
When running on a aarch64 machine, the command:
`erlang:system_info(scheduler_bind_type).`
returns
`unbound`
and
`erlang:system_info(scheduler_bindings).`
shows that all the sheduler threads are unbound.
and
`erlang:system_info(scheduler_online).`
also gives an unexpected wrong number.
Changing -stbt explicitly to tnnps also gives the same result.

While those results are correct on x86 machine.

Is this issue due to erlang can't recognise some types of CPU?
How can I confirm it and how to solve this problem?

**Comment by rickard-green** [comment]
Are you running inside a VM? If so, which?

**Comment by rickard-green** [comment]
What do you expect `erlang:system_info(scheduler_online)` to return and what does it return?

**Comment by EricLin89** [comment]
@rickard-green 
The OS is Linux. I'm running it inside the RabbitMQ erlang VM using `erl -sname xxx -rmesh xxx` command.
The RabbitMQ process is running in a cgroup which has 24 CPUs assigned to it. so `erlang:system_info(scheduler_online)` should return 24, but instead it returns 10.
I also checked `erlang:system_info(scheduler_online)` and it also returns 10.

The cpuset of the cgroup is cpu 10-33.
The machine has total of 96 cpus, 0-47 is on numa node0, and 48-95 is on node1.

I checked another machine running the same version and the same setting with only the cpuset different as 0-33, and  `erlang:system_info(scheduler_online)`  returns 34 correctly, which is strange. But scheduler_bind_type is still unbound.

**Comment by EricLin89** [comment]
Sorry, my bad. Seems the way I'm using to connect to the erlang VM is not correct.
I tried using `rabbitmqct eval` command to check the system_info and now it's right.

But it's still confusing, why I got the right result which the same way on x86 machine.

**Comment by rickard-green** [comment]
> Sorry, my bad. Seems the way I'm using to connect to the erlang VM is not correct. I tried using `rabbitmqct eval` command to check the system_info and now it's right.
> 

I built OTP 23.3 on our aarch64 linux machine and confirmed that binding works on our machine as well.

> But it's still confusing, why I got the right result which the same way on x86 machine.

Seems like you executed the `system_info()` call in another node than the one you expected, and then you get the results from that node. I do not know anything about these rabbitmq APIs, so I cannot give you any information about that. This you'll have to ask someone supporting rabbitmq about.
