### ISSUE TITLE
mod_alias failed to handle re_write config

### ISSUE THREAD

**Issue by xning** [erlang/otp#6074]
**Describe the bug**
mod_alias module of inets http server failed to hadnle re_write config.

**To Reproduce**
Start a http server to view erlang help doc as follows, then try open http://localhost:8080/doc/index.html

```erlang
inets:start().
inets:start(httpd, [{server_name, "localhost"},
                             {port, 8080}, {server_root, Tmpdir},
                             {document_root, "/usr/share/doc/erlang-24.3.4"},
                             {error_log, "error.log"},
                             {security_log, "secure.log"},
                             {transfer_log, "access.log"},
                             {re_write, {"^/(^[^/]+)/([+]+)/doc/(.*)$", "/\\1/\\2\\3"}},
                             {bind_address, "localhost"}]).
```

**Expected behavior**

http server return 505

**Affected versions**
erlang-24.3.4

**Additional context**

erlang-24.3.4-2.fc36.x86_64

I test the regular expression in re module, it works.

**Comment by u3s** [comment]
- can you give some examples showing user URIs and rewriting result?
- why do you expect server returning HTTP 505 ?
