### ISSUE TITLE
how does escript  not  close the window when I double click the escript file in windows?

### ISSUE THREAD

**Issue by iclodq** [erlang/otp#6077]
Erlang:OTP 19 
OS:windows 11
I have set double click escript to execute, it's done but close the result window which I want to check the output through.

I have tried to like this:
```	
case  os:type() of 
		{win32,_} ->
			% ct:sleep({seconds,5}),
			os:cmd("timeout 50"),
			os:cmd("cmd /k");
		_ ->
			ok
end.
```
It does not work.

**Comment by rickard-green** [comment]
I don't think this relates to Erlang at all. You have somehow configured Windows to start Erlang in a command window which terminates when Erlang terminates. If you want the window to remain after Erlang has terminated, you have to configure that outside of Erlang. A workaround could be to not terminate the `escript`, though. For example by inserting a `receive after infinity -> ok end` expression as last expression in the `escript`. Executing `os:cmd()` from within the `escript` will not help other than as a side effect it may delay the termination of the `escript`.

**Comment by iclodq** [comment]
> I don't think this relates to Erlang at all. You have somehow configured Windows to start Erlang in a command window which terminates when Erlang terminates. If you want the window to remain after Erlang has terminated, you have to configure that outside of Erlang. A workaround could be to not terminate the `escript`, though. For example by inserting a `receive after infinity -> ok end` expression as last expression in the `escript`. Executing `os:cmd()` from within the `escript` will not help other than as a side effect it may delay the termination of the `escript`.

In windows
I think  escript may be like   .py behavior,   double click to execute , the result window ouput "Press any key to quit program", there is no other statement to control, it's controlled by  "py.exe" (python 3.6) .    

Or like .bat , insert a statement "PAUSE".
Or like  "normal  C langue cmd app" insert a statement "getchar()". 

`receive after infinity -> ok`  can't quit through press any keys?  Can input any things to escript?

Now   I use the  `timer:sleep(10000)` .
