### ISSUE TITLE
Dialyzer unable to find remote type nonempty_binary()

### ISSUE THREAD

**Issue by g-andrade** [erlang/otp#6083]
**Describe the bug**
I've got an OTP app (rebar3) containing a conditional type spec of `nonempty_binary()` that precedes OTP 24 (it has been `ifdef`ed to avoid conflict with the latter). This type spec is exported with `export_type` (not conditioned by `ifdef`) and referenced in another module within the same app. Compilation succeeds but `rebar3 dialyzer` outputs a warning:

```
===> Analyzing 2 files with _build/default/rebar3_24.3.4_plt...

src/foobar_b.erl
Line 5 Column 13: Unknown type foobar:nonempty_binary/0
  ```

**To Reproduce**
Have an app with `foobar.erl`:
```erlang
-module(foobar).

-if(?OTP_RELEASE < 24).
-type nonempty_binary() :: <<_:8,_:_*8>>.
-endif.

-export_type([nonempty_binary/0]).
```

And `foobar_b.erl`:
```erlang
-module(foobar_b).

-export([do_it/1]).

-spec do_it(foobar:nonempty_binary()) -> binary().
do_it(<<_, Foo/bytes>>) ->
    Foo.
```

And tell Dialyzer to look for unknown types on `rebar.config`:
```
{dialyzer, [
    {warnings, [
        unknown
    ]}
]}.
```

**Expected behavior**
I expected Dialyzer to not complain about `foobar:nonempty_binary()` being an unknown type, since it's being exported from `foobar` (even though the built-in definition is being used on OTP 24).

On OTP 23.3.4.7 there's no warning.

**Affected versions**
OTP 24.3.4 (rebar 3.17.0)

**Additional context**
Example app to reproduce the behaviour: [foobar.zip](https://github.com/erlang/otp/files/8898545/foobar.zip)

**Comment by bjorng** [comment]
I find it confusing that there is an export for a type that not is defined in the module itself. We don't consider it a bug that you are not allowed to do that.

After some thinking and discussion we've come up with alternate suggestion for solution. See #6132.

However, if we implement it, it will be no earlier than OTP 26, so it will not solve your immediate problem. A workaround I can think of is to export the type with another name (not clashing with a built-in type).
