### ISSUE TITLE
kernel_config fails to sync nodes due to crypto nifs not being loaded (TLS)

### ISSUE THREAD

**Issue by vngthb** [erlang/otp#6085]
**Describe the bug**
Given an **embedded** Erlang node is configured to use **TLS** and wait for node syncing through the **sync_nodes_optional**/**sync_nodes_mandatory** and **sync_nodes_timeout** parameters, when starting up the node an error is thrown:
```
=ERROR REPORT==== 14-Jun-2022::17:56:28.705000 ===
Error in process <0.380.0> on node test2@myhost with exit value:
{undef,[{crypto,supports,[],[]},
        {tls_record,sufficient_crypto_support,1,
                    [{file,"tls_record.erl"},{line,378}]},
        {ssl,validate_versions,2,[{file,"ssl.erl"},{line,2478}]},
        {ssl,handle_option,4,[{file,"ssl.erl"},{line,1928}]},
        {ssl,process_options,3,[{file,"ssl.erl"},{line,1648}]},
        {ssl,handle_options,3,[{file,"ssl.erl"},{line,1602}]},
        {ssl,connect,4,[{file,"ssl.erl"},{line,604}]},
        {inet_tls_dist,do_setup_connect,10,
                       [{file,"c:/Program Files/erl-23.2/lib/ssl-10.2/src/inet_tls_dist.erl"},
                        {line,540}]}]}
```

This leads to the kernel_config to wait for the full duration configured through the sync_nodes_timeout and proceeds without syncing the specified nodes configured through either sync_nodes_mandatory or  sync_nodes_optional despite the other nodes being up.

**To Reproduce**
Common steps:
1. Create a boot script with the necessary applications so that the node would use TLS for distribution, e.g.:
```
{release, {"Test", "0"}, {erts, "11.1.4"},
      [{kernel, "7.2"},
      {stdlib, "3.14"},
      {sasl, "4.0.1"},
      {asn1, "5.0.14"},
      {crypto, "4.8.1"},
      {public_key, "1.9.2"},
      {ssl, "10.2"}]}.
```

Node A:
1. Start node with the following arguments: 
`erl -sname test1 -mode embedded -boot path_to_boot_script -proto_dist inet_tls`

Node B:
1. Create a node config file with the following parameters:
```
[{kernel, 
	[{sync_nodes_optional, ['test1@myhost']},
	 {sync_nodes_timeout, 10000}]}].
```
2. Start node with the following arguments:
`erl -sname test2 -mode embedded -boot path_to_boot_script -config path_to_config  -proto_dist inet_tls`

**Expected behavior**
Node B has to sync with node A without any errors being thrown and without the sync_node_timeout being breached.

**Affected versions**
All.

**Additional context**
The root of this issue seems to be that the crypto application nifs are not loaded by the time when the kernel_config supervisor attempts to establish a connection with the other nodes, which leads to the undefined function error. The crypto nifs most likely are expected to be loaded during the [kernel_safe_sup supervisor](https://github.com/erlang/otp/blob/master/lib/kernel/src/kernel.erl#L189) initialization which, according to [this](https://github.com/erlang/otp/blob/master/lib/kernel/src/kernel.erl#L173) list, is done after the kerner_config supervisor is started, thus leading to the above issue.

**Comment by IngelaAndin** [comment]
Well, I think the problem is that "Erlang applications" do not really exist until after the kernel application is started. Due to this the ssl application supervisor tree is sort of mirrored under the kernel supervisor tree for it to work in the early stage when the distribution is started, which normally works well. Now I am not familiar with the embedded mode implementation but it seems that does not load any code not belonging to the kernel application until after the distribution has started and is expected to work. The problem then is that the code of all the other applications, needed now, needs to be thought of as belonging to kernel, or maybe embedded loading ought to work differently.
