### ISSUE TITLE
[DNS] Handling of the LOC resource record type

### ISSUE THREAD

**Issue by bortzmeyer** [erlang/otp#6098]
The current DNS code in `lib/kernel/src/inet_dns.hrl` does not handle the `LOC` resource record type ([RFC 1876](https://www.rfc-editor.org/info/rfc1876)). True, it is not used a lot but I have one or two projects that may use it. 

Therefore, I would be happy if  `LOC` and its encoding/decoding would be added to `lib/kernel/src/inet_dns.hrl` .

**Comment by bortzmeyer** [comment]
Note there is Erlang code to deal with LOC types in [this library](https://github.com/dnsimple/dns_erlang).

**Comment by RaimoNiskanen** [comment]
I am working on it...

**Comment by RaimoNiskanen** [comment]
I have implemented a suggestion in PR #6982.

I selected a different data content format than in the `dns_erlang` library because `inet_dns` does not expose any records for RR data content.

Comments are welcome, preferably over there...

**Comment by RaimoNiskanen** [comment]
Fixed in PR #6982.  Thank you for reporting this issue.
