### ISSUE TITLE
inets: httpd->mod_esi broken since OTP Rel. 23.0

### ISSUE THREAD

**Issue by guberathome** [erlang/otp#6122]
According to documentation, mod_esi allows to implement a callback with 2 parameters (even if it's discouraged for good reasons).

**To Reproduce**
* compile the following code
* `greeter:start().`
* open `http://localhost:8080/esi/greeter:f2` in web browser
* browser responds with "Object not found. The requested URL ... is not found on the server." (see attached)
* using URL ".../esi/greeter/f2" instead of ".../esi/greeter:f2" does not change things
* note that `http://localhost:8080/esi/greeter:f3` works fine for all OTP versions

**Expected behavior**
Either call ESI (and show output of greeter:f2/2) or update documentation, if only 3-parameter-callback can be used.

**Affected versions**
* all from OTP Rel. 23.0 (verified with Rel. 23.3.4.15, Rel. OTP24.3.4.2).
* works fine with OTP Rel. 22.3
* tested under Windows, FreeBsd, Linux 

**Additional context**
```
-module(greeter).
-export([f2/2, f3/3, start/0, stop/0]).

-define(serverPort, 8080  ).
-define(esiRoot   , "/esi").                  % Upload-URL: http://localhost:8080/esi/greeter:f2

-define(serverRoot  , "..").
-define(documentRoot, ?serverRoot ++ "/web-content/").	
-define(httpContent, 	"Content-Type: text/html\r\n\r\n<head><meta charset='utf-8'></head> <body><h2>Welcome...</h2><p>... to Erlang Server Interface!</p> </body>" ).
	
f2( _env, _input ) -> 
	?httpContent.

f3(SessId, _Env, _Input) ->
    mod_esi:deliver( SessId, ?httpContent ).
	
start() ->
	ok = inets:start(),
	inets:start( httpd, [ 
		{modules, [mod_esi, mod_auth, mod_dir, mod_get, mod_log] },
		{port, ?serverPort}, {server_name, "httpd_Greeter"},  
		{server_root, ?serverRoot},  {document_root, ?documentRoot},  
		{mime_type, "application/octet-stream"},    % specify :mime_types to correctly display images!
		{bind_address, "localhost"}, 
		{error_log,    "errors.log"},
		{transfer_log, "transfer.log"},
		{erl_script_alias, {?esiRoot, [greeter]}}
		] ).
	
stop() ->
	inets:stop().
```

**error message:**
![image](https://user-images.githubusercontent.com/84842184/177027159-e9c42e9d-2fc9-4de2-a9f2-22382de9f589.png)

**Comment by guberathome** [comment]
![image](https://user-images.githubusercontent.com/84842184/177027123-667ab2bc-11b6-401c-833b-8c73a44e4571.png)

**Comment by IngelaAndin** [comment]
This I think is a bug in the documentation, that is we dropped the support for this callback function in OTP-23. 

Also, 22.3.1 will not support it:

OTP-16556    Application(s): inets

               Remove use of http_uri and mod_esi eval API.

               This is a backport from OTP 23 that improves the check
               of URIs to ensure that invalid URIs does not cause
               vulnerabilities. This will render the deprecated
               mod_esi eval API unusable as it used URI that does not
               conform to valid URI syntax.
