### ISSUE TITLE
Certificate is expired for Erlang version 24.1.7

### ISSUE THREAD

**Issue by Revanborg** [erlang/otp#6125]
**Describe the bug**
Certificate is expired for Erlang OTP version 24.1.7

**To Reproduce**
Right click on the Erlang OTP exe and go to properties. In Properties go to Digital Signatures tab and check the certificate validity. It is showing expiry date as 29th June 2022.

**Expected behavior**
Certificate should be valid and it should not be expired.

**Affected versions**
24.1.7

**Additional context**
Add any other context about the problem here. If you wish to attach Erlang code you can either write it directly in the post using [code tags](https://guides.github.com/features/mastering-markdown/), create a [gist](https://gist.github.com), or attach it as a zip file to this post.

**Comment by Revanborg** [comment]
Hi Lukas,

I am getting below error and when I googled more around the error. I came to know it might be related to certificate.
That’s why I raised issue related to certificate. Kindly help us with this issue.

Error:
[1AAC:0768][2022-06-30T18:25:49]e000: Error 0x800b010a: Failed authenticode verification of payload: C:\ProgramData\Package Cache\.unverified\payB1DCAD7D637C2D584813DAB3C5946A8A
[1AAC:0768][2022-06-30T18:25:33]e000: Error 0x800b010a: Failed to verify signature of payload: payB1DCAD7D637C2D584813DAB3C5946A8A

Thanks in advance!

Thanks & Regards,
Revansiddh Borgaonkar

**Comment by garazdawi** [comment]
I don't think that error has anything to do with the date of the certificate, but rather that your Windows install lacks the proper root certificate to authenticate the installer. There are a couple of suggestions of what you might want to try in this thread: https://social.msdn.microsoft.com/Forums/en-US/a8f0ce40-1567-4e35-9c95-3c86ee7ecc35/failed-authenticode-verification-during-visual-studio-2015-enterprise-install?forum=vssetup

**Comment by Revanborg** [comment]
Thanks a lot for your quick reply.

I will go through the details from the link you shared and will update you.


Thanks & Regards,
Revansiddh Borgaonkar

**Comment by garazdawi** [comment]
I'm closing this issue as there does not seem to be anything wrong with anything that we do. If you figure out what the problem was, please do let us know so that others that encounter the same problem can get help.

**Comment by Revanborg** [comment]
Thanks a lot Lukas for your quick support and fix.

Thanks & Regards,
Revansiddh Borgaonkar
