### ISSUE TITLE
Problem installing Erlang on Lubuntu 20.04

### ISSUE THREAD

**Issue by tigadad** [erlang/otp#6147]
**Describe the bug**
Trying to sudo apt-get install erlang gives the following error. I have been trying for two weeks. This error occurs on many (all) files. I get the same error trying to install Elixir but I think it is the Erlang install part that fails.

Get:34 http://binaries.erlang-solutions.com/debian impish/contrib amd64 erlang-os-mon amd64 1:24.1.7-1 [113 kB]
Err:34 http://binaries.erlang-solutions.com/debian impish/contrib amd64 erlang-os-mon amd64 1:24.1.7-1
  File has unexpected size (113194 != 113234). Mirror sync in progress? [IP: 13.33.21.69 80]
  Hashes of expected file:
   - SHA256:06d5e9ded4c6d3e35f5079b5e810d5df51a00e4730a8209d35e65facd876f17d
   - SHA1:84c98b33d177ebe2a6b07541585994b2a24891ad [weak]
   - MD5Sum:58bb40b1969cdc0c927e0e35a5982c6a [weak]
   - Filesize:113234 [weak]

**To Reproduce**
As described

**Expected behavior**
Install Erlang

**Affected versions**
The OTP versions that are affected by this bug; I assume 25

**Additional context**
Add any other context about the problem here. If you wish to attach Erlang code you can either write it directly in the post using [code tags](https://guides.github.com/features/mastering-markdown/), create a [gist](https://gist.github.com), or attach it as a zip file to this post.

**Comment by rickard-green** [comment]
We do not deliver those packages. You have to contact erlang-solutions.com about issues with their packages.
