### ISSUE TITLE
maps module doc has broken link to the efficiency guide

### ISSUE THREAD

**Issue by mikpe** [erlang/otp#6155]
**Describe the bug**
The `maps` module documentation, https://www.erlang.org/doc/man/maps.html, contains in its Description a link labelled "how to use maps efficiently" which is _supposed_ to link to the `maps` part of the Efficiency Guide, https://www.erlang.org/doc/efficiency_guide/maps.html. Instead the link points back to itself, i.e. https://www.erlang.org/doc/man/maps.html .

**To Reproduce**
Point your web browser (I'm using Firefox) to https://www.erlang.org/doc/man/maps.html and click on the "how to use maps efficiently" link the the Description. Notice how it takes you back to the same page.

**Expected behavior**
I expected the link to take me to the `maps` part of the Efficiency Guide.

**Affected versions**
OTP-25.

**Additional context**
Other links to the Efficiency Guide seem to work, e.g. the one from the `timer` module does. I can't see anything obviously wrong with the source code (lib/stdlib/doc/src/maps.xml). Perhaps it's a document processing problem?

**Comment by frazze-jobb** [comment]
Thanks for the report! I merged a PR that fixes this issue at https://github.com/erlang/erlang-org/pull/90
