### ISSUE TITLE
Using 'inline_list_funcs' with lists:xxx

### ISSUE THREAD

**Issue by DominicGame** [erlang/otp#6158]
**Describe the bug**
lists:all(fun erlang:is_integer/1, Values) compile with inline_list_funcs 

**To Reproduce**
Warning: this clause cannot match because a previous clause always matches

**Expected behavior**
no warning

**Affected versions**
with 24.3.4 on WLS

**Additional context**
see more in:
https://erlangforums.com/t/using-inline-list-funcs-with-lists-xxx/1654

**Comment by RaimoNiskanen** [comment]
I suspect something strange happens in an compiler internal pass.
This will have to wait until our compiler people are back from their vacation.

**Comment by Maria-12648430** [comment]
> **Affected versions**
> with 24.3.4 on WLS

For the record, same for 25.0.3 on Ubuntu.

I'll try with 23.3 later to see if that happened before the advent of JIT, too.

**Comment by bjorng** [comment]
The linked pull request resolves the issue. It will be included in OTP 25.1.
