### ISSUE TITLE
Can't communicate between erlang node and jinterface node

### ISSUE THREAD

**Issue by YuriMzz** [erlang/otp#6166]
**Describe the bug**
net_kernel:connect_node(server@localhost).
=INFO REPORT==== 23-Jul-2022::15:02:31.224196 ===
{net_kernel,{connect,normal,server@localhost}}
=INFO REPORT==== 23-Jul-2022::15:02:31.228144 ===
{net_kernel,{'EXIT',<0.101.0>,{recv_status_failed,{error,closed}}}}
=INFO REPORT==== 23-Jul-2022::15:02:31.228415 ===
{net_kernel,{net_kernel,1362,nodedown,server@localhost}}
false

even if the server node is clearly up:
epmd: up and running on port 4369 with data:
name client at port 36357
name server at port 36157

**To Reproduce**
on erlang:
net_kernel:connect_node(server@localhost).
erl -sname client@localhost -setcookie abcde

java code:
String nodeId = "server@localhost";
String cookie = "abcde";
String mBox = "hello";
OtpNode otpNode = new OtpNode(nodeId, cookie);
OtpMbox otpMbox = otpNode.createMbox(mBox);

**Expected behavior**
net_kernel:connect_node(server@localhost).
true.

**Affected versions**
Erlang/OTP 25 [erts-13.0.2] 
Eshell V13.0.2 
clojang.erlang-jinterface1.10-1 (i tried also with org.erlang.otp.jinterface1.6.1)

**Additional context**
OS: EndeavourOS Linux x86_64 
Kernel: 5.18.12-arch1-1 
Package: community/erlang  25.0.2-1     
openjdk version "18.0.2" 2022-07-19
OpenJDK Runtime Environment (build 18.0.2+9)
OpenJDK 64-Bit Server VM (build 18.0.2+9, mixed mode)

**Comment by josevalim** [comment]
I may be wrong here but if you are using jinterface 1.6.1, it is likely no longer compatible with OTP 25. It is several years old and the wire protocol has likely evolved since then.

**Comment by YuriMzz** [comment]
@josevalim thanks for the hint. I tried with clojang.erlang-jinterface1.10-1 which is the last version i can find a maven dependecy for. I figured out that it work with erlang24 but not with erlang25. Did you know where i can find the maven dependency for the last jinterface?

**Comment by josevalim** [comment]
According to clojang's github repo, the last release was 0.6.0, which was four years ago. So I am afraid you may not be able to make it work via clojang itself.

However, [Erlang should ship with a .jar file inside its distribution](https://www.erlang.org/doc/apps/jinterface/jinterface_users_guide.html#compiling-and-loading-your-code), which you can use. I don't know if this .jar file is published to maven's repository.

**Comment by YuriMzz** [comment]
Thank you very much! I compiled with the last version of jinterface and now work with erlang25.

**Comment by prasanna25t** [comment]
> Thank you very much! I compiled with the last version of jinterface and now work with erlang25.

Hey can you share the link from where you downloaded the latest version of jinterface

**Comment by KennethL** [comment]
jinterface is a component in Erlang/OTP so if you have built and installed Erlang/OTP you normally have jinterface in the same file tree. 
You can for example do like this:
```
Linuxprompt$ erl
Erlang/OTP 24 [erts-12.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Eshell V12.1  (abort with ^G)
1> code:lib_dir(jinterface).
"/usr/local/lib/erlang/lib/jinterface-1.12.1"
```
and you find the OtpErlang.jar in the `priv` directory underneat.

**Comment by prasanna25t** [comment]
i tried it doesn't show up anything , even i checked in path /usr/lib64/erlang/lib it do not have any jinterface-1.12.1

# erl
Erlang/OTP 25 [erts-13.0.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [jit:ns]

Eshell V13.0.2  (abort with ^G)
1> code:lib_dir(jinterface).
{error,bad_name}

**Comment by josevalim** [comment]
@prasanna25t some distributions are known to break Erlang into multiple packages, so you may need to install erlang-jinterface or similar. The exact command will depend on OS and package manager.

**Comment by vans163** [comment]
We ended up using https://github.com/fredlund/JavaErlang on OTP22 days (maybe OTP25 broke that too, have not tested)

**Comment by KennethL** [comment]
JavaErlang is a layer on top of jinterface so you still need jinterface as well. Jinterface is part of OTP and there is always a version of jinterface that works with the Erlang nodes in the same major release. We try to keep compatibility with 2 older major releases when it comes to the Erlang distribution protocol so if you are running OTP 25.x then jinterface as delivered from OTP 23.x, OTP 24.x and OTP 25.x should work together with that.

If you are fetching jinterface from another source you have to check yourself if it is a good version for you.
