### ISSUE TITLE
Internal compiler error: {undefined_label, 0} in beam_clean:function_replace/3

### ISSUE THREAD

**Issue by RobinMorisset** [erlang/otp#6169]
Running erlc on the following code:
```
-module(undefined_label).

-compile([export_all]).

f([] = V1, V2, V3)  -> 
        {V1 - V3, (V1 = V2) - V3}.
```
results in a crash:

> *** Internal compiler error ***
> exception exit: {undefined_label,0}
>   in function  beam_clean:function_replace/3 (beam_clean.erl, line 134)
>   in call from beam_clean:clean_labels/1 (beam_clean.erl, line 105)
>   in call from beam_clean:module/2 (beam_clean.erl, line 35)
>   in call from compile:'-select_passes/2-anonymous-0-'/3 (compile.erl, line 678)
>   in call from compile:fold_comp/4 (compile.erl, line 405)
>   in call from compile:internal_comp/5 (compile.erl, line 389)
>   in call from compile:'-internal_fun/2-anonymous-0-'/2 (compile.erl, line 227)
>   in call from compile:'-do_compile/2-anonymous-0-'/1 (compile.erl, line 217)

**Comment by bjorng** [comment]
I have fixed the problem in the linked pull request. I will be included in OTP 25.1. (The bug does not seem to exist in OTP 24.)
