### ISSUE TITLE
erlc internal consistency error for is_eq_exact

### ISSUE THREAD

**Issue by RobinMorisset** [erlang/otp#6183]
On the following code:
```
-module(is_eq_exact).
-compile([export_all]).

f(V)  when ((V / V) < (V orelse true)); V; V ->
	((V = (a /= V)) orelse 0).
```
erlc (either built from master as of today including the recent fixes to #6163, #6164, and #6169, or a slightly older version from a few weeks ago) crashes with the following error message:

> is_eq_exact:1: function f/1+12:
>   Internal consistency check failed - please report this bug.
>   Instruction: {test,is_eq_exact,{f,9},[{x,1},{atom,true}]}
>   Error:       {type_conflict,{t_atom,[true]},{t_atom,[a]}}:

**Comment by bjorng** [comment]
I have fixed the problem in the linked pull request.
