### ISSUE TITLE
Support for Pre-NIST Keccak256

### ISSUE THREAD

**Issue by heri16** [erlang/otp#6200]
This issue is for Support for Pre-NIST Keccak256.

Keccak256 was recently merged to OpenSSL master:
https://github.com/openssl/openssl/issues/13033#issuecomment-925456698

https://www.openssl.org/docs/manmaster/man7/EVP_MD-KECCAK.html

W3C seems to be ratifying the standard:
https://github.com/w3c-ccg/ethereum-eip712-signature-2021-spec

Changes required here?
https://github.com/erlang/otp/blob/62ff88c44c5ac81ecaab7be7baca53ae7935e146/lib/crypto/c_src/digest.c#L95

**Comment by HansN** [comment]
Thanks for the information!

However, as I understand it, SHA3 will not be re-defined in OpenSSL but "new" algorithms called KECCAK-* will be added. Am I wrong?

We have currently no plans to add Keccak to Erlang/OTP.  However , anyone that want it can submit a PR.  For example, recently we got a PR ( #6203 ) for SHAKE.

**Comment by marcellanz** [comment]
I'm curious why this issue has been closed? @HansN

**Comment by somoza** [comment]
I was working on it but new keccak support on OpenSSL is on dev and will be released on 3.2 version.

https://github.com/openssl/openssl/issues/19304

So far we only gonna get ` Digest type not supported in this cryptolib`.

**Comment by somoza** [comment]
At least someone wants to program the sha3-256 algorithm with 0x1 instead 0x6 delimiter ^-^
