### ISSUE TITLE
dialyzer shows warning when using 'tlsv1.3' in ssl:cipher_suites

### ISSUE THREAD

**Issue by nikigen68** [erlang/otp#6210]
**Describe the bug**
Dialyzer throws warning when compiling code with "ssl:cipher_suites('default','tlsv1.3')." while within erlang shell function execution works fine.

Dialyzer warning:

The call ssl:cipher_suites
         ('default',
          'tlsv1.3') will never return since it differs in the 2nd argument from the success typing arguments: 
         ('all' | 'anonymous' | 'default',
          'dtlsv1' | 'dtlsv1.2' | 'sslv3' | 'tlsv1' | 'tlsv1.1' |
          'tlsv1.2' |
          integer() |
          {integer(), integer()})

$ dialyzer --version
Dialyzer version v4.1.1

Erlang shell printout:

> ssl:cipher_suites(default,'tlsv1.3').
[#{cipher => aes_256_gcm,key_exchange => any,mac => aead,
   prf => sha384},
 #{cipher => aes_128_gcm,key_exchange => any,mac => aead,
   prf => sha256},
 #{cipher => chacha20_poly1305,key_exchange => any,mac => aead,
   prf => sha256},
 #{cipher => aes_128_ccm,key_exchange => any,mac => aead,
   prf => sha256},
 #{cipher => aes_256_gcm,key_exchange => ecdhe_ecdsa,
   mac => aead,prf => sha384},
 #{cipher => aes_256_gcm,key_exchange => ecdhe_rsa,mac => aead,
   prf => sha384},
 #{cipher => aes_256_cbc,key_exchange => ecdhe_ecdsa,
   mac => sha384,prf => sha384},
 #{cipher => aes_256_cbc,key_exchange => ecdhe_rsa,
   mac => sha384,prf => sha384},
 #{cipher => aes_256_gcm,key_exchange => ecdh_ecdsa,
   mac => aead,prf => sha384},
 #{cipher => aes_256_gcm,key_exchange => ecdh_rsa,mac => aead,
   prf => sha384},
 #{cipher => aes_256_cbc,key_exchange => ecdh_ecdsa,
   mac => sha384,prf => sha384},
 #{cipher => aes_256_cbc,key_exchange => ecdh_rsa,
   mac => sha384,prf => sha384},
 #{cipher => aes_256_gcm,key_exchange => dhe_rsa,mac => aead,
   prf => sha384},
 #{cipher => aes_256_gcm,key_exchange => dhe_dss,mac => aead,
   prf => sha384},
 #{cipher => aes_256_cbc,key_exchange => dhe_rsa,mac => sha256,
   prf => default_prf},
 #{cipher => aes_256_cbc,key_exchange => dhe_dss,mac => sha256,
   prf => default_prf},
 #{cipher => aes_128_gcm,key_exchange => ecdhe_ecdsa,
   mac => aead,prf => sha256},
 #{cipher => aes_128_gcm,key_exchange => ecdhe_rsa,mac => aead,
   prf => sha256},
 #{cipher => aes_128_cbc,key_exchange => ecdhe_ecdsa,
   mac => sha256,prf => sha256},
 #{cipher => aes_128_cbc,key_exchange => ecdhe_rsa,
   mac => sha256,prf => sha256},
 #{cipher => aes_128_gcm,key_exchange => ecdh_ecdsa,
   mac => aead,prf => sha256},
 #{cipher => aes_128_gcm,key_exchange => ecdh_rsa,mac => aead,
   prf => sha256},
 #{cipher => aes_128_cbc,key_exchange => ecdh_ecdsa,
   mac => sha256,prf => sha256},
 #{cipher => aes_128_cbc,key_exchange => ecdh_rsa,
   mac => sha256,prf => sha256},
 #{cipher => aes_128_gcm,key_exchange => dhe_rsa,mac => aead,
   prf => sha256},
 #{cipher => aes_128_gcm,key_exchange => dhe_dss,mac => aead,...},
 #{cipher => aes_128_cbc,key_exchange => dhe_rsa,...},
 #{cipher => aes_128_cbc,...},
 #{...}|...]

When tlsv1.2 is used instead of tlsv1.3 then there are no warnings.

**To Reproduce**
Run dialyzer with:
make dialyzer

**Expected behavior**
Dialyzer throws no warnings.

**Affected versions**
Erlang 10.7, OTP 22.3, ssl-9.6, crypto-4.6.5, inets-7.1.2​
I'm using two environments with this OpenSSL versions and in both the problematic ssl:cipher_suites function works fine:
OpenSSL 1.0.1f​
OpenSSL 1.1.1l 

**Additional context**
-

**Comment by IngelaAndin** [comment]
I suspect you have an inconsistent environment. I can not reproduce this. When building OTP 22.3 the make dialyzer target does not exist. On OTP-23.0  it passes and I am pretty sure it will for all later releases as we (for quite some time) have a trigger that checks that code that should be committed does not have dialyzer warnings. Older versions of OTP 22 however had not yet enabled  'tlsv1.3' in its implementation although it was present in the spec. Which I suspect could cause that dialyzer error.

**Comment by nikigen68** [comment]
Ok, then I will postpone TLSv1.3 usage till OTP is upgraded to OTP23 or higher. Thanks!
