### ISSUE TITLE
:global regression in OTP 25

### ISSUE THREAD

**Issue by MikaAK** [erlang/otp#6211]
**Describe the bug**
As of OTP 25, messages for global are now sent using `:erpc` (from what I understand)
This causes a high number of processes to be spun up and when doing fast and high numbers of `:global.set_lock` causes out of process errors cluster wide in some cases (this could also be just the overage of processes, I know set_lock uses :gen_server.multi_call which I believe just uses spawn?)

**To Reproduce**
This is a hard one to reproduce locally, I've attempted in a non prod environment (running 60 nodes is a tad expensive) and been unable to reproduce yet. My attempt has been to lock 500k keys and then use a few nodes to try and unlock all of those keys using an async_stream. I'm going to keep trying to reproduce it and will update this issue if I can manage to reproduce in a local environment

**Expected behavior**
In OTP 24 this example doesn't break, our theory is because the global server is building a message queue but it doesn't topple over like OTP 25 does 

For example in a 60 node cluster locking we're locking about 500 ids per second which creates (500 messages * 60 nodes)  = ~30k process per second spawned across the cluster (30k processes per node per minute)

**Affected versions**
OTP-25+

**Additional context**
We have a cluster of just over 60 nodes and have experienced a lot of issues with the new `prevent_overlapping_partitions`, we set the `net_setuptime` quite high but this didn't help and our cluster was very unhealthy. 
We swapped our locking to redis to avoid all the traffic which helped with the out of process errors from locking but that still didn't help our cluster health fully and were getting lots of global disconnect messages.
We also tried disabling `prevent_overlapping_partitions` by setting it to `false` however the cluster was still un-healthy, downgrading to OTP-24 made it healthy again. 

Let me know if you want a separate issue for `prevent_overlapping_partitions`

### Post Mortem from Outage
https://theblitzapp.notion.site/Cluster-Health-Issue-02829d3cd5304baa94c4a7c4540fbc20

Will update this post with additional info as I can

**Comment by rickard-green** [comment]
> As of OTP 25, messages for global are now sent using :erpc (from what I understand)

No, `global` does not use `erpc` in any released OTP 25 version. In the upcoming maintenance patch (to become OTP 25.1), `global_group` which is a helper to `global`, will use `erpc` as a replacement for its previous use of `rpc`, but that does not cause anymore processes to be spawned. `rpc` also spawn processes, but in a more inefficient manner than `erpc`.

> This causes a high number of processes to be spun up and when doing fast and high numbers of :global.set_lock causes out of process errors cluster wide in some cases (this could also be just the overage of processes, I know set_lock uses :gen_server.multi_call which I believe just uses spawn?)

The `gen_server:multi_call/3` call made as a result of calling `global:set_lock()` does not cause any new processes to be spawned. It will send messages to other global name servers which will respond by sending messages back. `gen_server:multi_call/4` with an integer timeout will spawn a process (and always has done so), but it is not used by `global:set_lock()`.

That is, there seems to be something else causing these issues.

> Let me know if you want a separate issue for `prevent_overlapping_partitions`

Yes, please.

**Comment by MikaAK** [comment]
> rpc also spawn processes, but in a more inefficient manner than erpc.
That makes sense, correct me if I'm wrong but `rpc` went through `rex` server in the past right? Would this of acted as some sort of rate limiter due to single process limits?

> `global:set_lock()` does not cause any new processes to be spawned
That is interesting to hear, I do wonder what caused out of process errors then, ultimately redis locking did remove the out of process issues so it does appear connected to that in some way, but I'm unclear on how given this new info

Let us know if there's any tests you'd like us to run, we can try to schedule some ops at a low usage hour and run a quick test if required

**Comment by rickard-green** [comment]
Looking closer at this I noted that under *Post Mortem from Outage*, you've linked the same link as in #6214. The spawns made in `gns_volatile_send()`, which is only used when `prevent_overlapping_partitions` is enabled, explains the increased amount of spawned processes. That is, I interpret this issue to be covered by the #6214 issue, so I'm closing this issue. Please reopen this issue if you disagree.

**Comment by AndrewDryga** [comment]
@MikaAK we have a similar locking mechanism in our system and even though it's not as heavily used as yours I thought you might reuse some of our experience with it.

We split the problem into two problems: globally unique process and holding list of locks. 

A lock management process is started on every node, one of them would become a leader, and others will hibernate and monitor the leader to re-start the election when the leader is down. To have a globally distributed process `:global` is used with `:global.random_notify_name/3`. 

This lock manager is a GenServer accepting `{:lock, resource_id}` calls, it monitors the caller process and provides some other helper utilities (basically similar to what `:global.set_lock/2` does except we extended it with some additional utilities). This helps to reduce the chances to make `:global` a bottleneck in our system because it's only used for name registration which typically is only needed during cluster rollouts.

The lock manager processes can be scaled by marking more partitions of it on every node, having one leader per partition, and using `resource_id` (or anything else that fits your business logic) as a partition key.

**Comment by MikaAK** [comment]
@rickard-green  gotcha, will stick to that issue, thanks for the insight!

@AndrewDryga  Really cool solution to the problem.  I think Redis really has us covered for locking now since it's super quick   and an easy tool for us to reach for, that being said i think it's awesome to have a native elixir solution as well
