### ISSUE TITLE
beam.smp starts using 1.6G memory？

### ISSUE THREAD

**Issue by clcc2019** [erlang/otp#6217]
<img width="672" alt="image" src="https://user-images.githubusercontent.com/46099295/184276372-37ec0da3-ba3f-40f1-b644-eab52f32c977.png">

**Comment by garazdawi** [comment]
Did you pass any flags to `erl`? What OS are you using? What CPU?

When I start `erl` RES is about 40MB.

**Comment by clcc2019** [comment]
> Did you pass any flags to `erl`? What OS are you using? What CPU?
> 
> When I start `erl` RES is about 40MB.
os: openeulerArchitecture: amd64

**Comment by clcc2019** [comment]
We use kubernetes to run rabbitmq

**Comment by clcc2019** [comment]
<img width="543" alt="image" src="https://user-images.githubusercontent.com/46099295/184303020-92129231-7c20-43ca-9eb9-9bd419f56898.png">

**Comment by clcc2019** [comment]
/opt/bitnami/erlang/lib/erlang/erts-11.2.2.14/bin/beam.smp -W w -K true -A 256 -MBas ageffcbf -MHas ageffcbf -MBlmbcs 512 -MHlmbcs 512 -MMmcs 30 -P 1048576 -t 5000000 -stbt db -zdbbl 128000 -B i -- -root /opt/bitnami/erlang/lib/erlang -progname erl -- -home /opt/bitnami/rabbitmq/.rabbitmq -- -pa  -noshell -noinput -s rabbit boot -boot start_sasl -lager crash_log false -lager handlers []

**Comment by garazdawi** [comment]
Since you are running RabbitMQ, I suggest you ask them why it is using more memory than you expect: https://groups.google.com/g/rabbitmq-users

Or ask on [ErlangForums](https://erlangforums.com/) and see if someone there can help you.
