### ISSUE TITLE
the default args(dump_log_write_threshold) of mnesia  is not same between code and doc

### ISSUE THREAD

**Issue by WHYZN** [erlang/otp#6218]
**Describe the bug**
![image](https://user-images.githubusercontent.com/39898928/184280553-61cad576-a127-477d-b48b-d2bd902991da.png)
![image](https://user-images.githubusercontent.com/39898928/184280922-d5f9384d-ab2b-416b-878c-9422476fa234.png)

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Affected versions**
The OTP versions that are affected by this bug.

**Additional context**
Add any other context about the problem here. If you wish to attach Erlang code you can either write it directly in the post using [code tags](https://guides.github.com/features/mastering-markdown/), create a [gist](https://gist.github.com), or attach it as a zip file to this post.

**Comment by dgud** [comment]
Fixed by #6039
