### ISSUE TITLE
Compiler or VM returning faulty result on multiple guards and integer_to_binary calls with bignums

### ISSUE THREAD

**Issue by josevalim** [erlang/otp#6239]
**Describe the bug**

Take this program:

```erlang
-module(foo).
-export([bar/2]).

bar(A, B) when is_integer(B); is_binary(B) ->
  <<(case A of
      X when is_binary(X) -> X;
      _ -> atom_to_binary(A)
    end)/binary,
    "_",
    (case B of
      Y when is_binary(Y) -> Y;
      _ -> integer_to_binary(B)
    end)/binary>>.
```

It raises the following error when called with an atom and a big num:

```erlang
1> foo:bar(foo, 2749963626218098647).
** exception error: construction of binary failed
     in function  foo:bar/2 (foo.erl, line 5)
        *** segment 3 of type 'binary': expected a binary but got: 2749963626218098647
```

Notice it works fine with a smaller number, which makes me think it is a runtime error. However, the error only happens if there are multiple guards, so maybe a compiler error?

**Affected versions**

It happens on master (as of 23b7b7e29ed003f7a9419432e78111e015822874) and Erlang/OTP 25.

I have verified it doesn't happen on OTP 23.3 and I was told it doesn't happen on OTP 24 either.

**Additional context**

[Issue originally reported here](https://github.com/elixir-lang/elixir/issues/12095).

**Comment by bjorng** [comment]
The bug is in the new type-based optimizations in the JIT (introduced in OTP 25). The linked pull request fixes the bug.
