### ISSUE TITLE
OTP-24.3.4.3 `{unexpected_msg,{internal,{encrypted_extensions,#{}}}}`

### ISSUE THREAD

**Issue by wojtekmach** [erlang/otp#6241]
**Describe the bug**

On OTP-24.3.4.3 I noticed the error below. OTP-24.3.4.2, or other versions, didn't have such behaviour.

**To Reproduce**

```
$ erl
1> ssl:start(), ssl:connect('elixir-lang.org', 443, []).
=WARNING REPORT==== 25-Aug-2022::11:28:04.717049 ===
Description: "Authenticity is not established by certificate path validation"
     Reason: "Option {verify, verify_peer} and cacertfile/cacerts is missing"

=NOTICE REPORT==== 25-Aug-2022::11:28:04.811253 ===
TLS client: In state hello_middlebox_assert at ssl_gen_statem.erl:736 generated CLIENT ALERT: Fatal - Unexpected Message
 - {unexpected_msg,{internal,{encrypted_extensions,#{}}}}
{error,{tls_alert,{unexpected_message,"TLS client: In state hello_middlebox_assert at ssl_gen_statem.erl:736 generated CLIENT ALERT: Fatal - Unexpected Message\n {unexpected_msg,{internal,{encrypted_extensions,#{}}}}"}}}
```

**Expected behavior**
No error.

**Affected versions**
24.3.4.3

**Comment by IngelaAndin** [comment]
If you disable the middle_box_comaptibility mode it will work.

`ssl:connect('elixir-lang.org', 443, [{middlebox_comp_mode, false}]).`

The thing that changed is that we better handle unexpected messages in TLS-1.3 and assert the change_cipher_spec messages that should be sent in middle_box_compatibility mode. 

So either the server is not sending an expected middle_box_compatibility hange_cipher_spec message or we are missing to disable the compatibility switch when the server does not agree to run in middle_box_compatibility-mode.  I will investigate which it could be.

**Comment by IngelaAndin** [comment]
Humm  ...  middle_box_compability mode works if you run only TLS-1.3 so there seems to be a bug in handling of middle_box_comability mode if both TLS-1.2 and TLS-1.3 are supported. 

 `ssl:connect('elixir-lang.org', 443, [{versions, ['tlsv1.3']}])`

**Comment by IngelaAndin** [comment]
Seems that there was a misunderstanding when the middlebox_comp_mode was introduced.  It is only partly a negotiation driven by the client.  I think my PR will correct this!

**Comment by gerhard** [comment]
Thank you for the fix @IngelaAndin! Did you have a chance to test it @wojtekmach?

We are looking forward to upgrading and removing this temporary TODO as soon as the new version is out: https://github.com/thechangelog/changelog.com/commit/0db2e6f1db6f7d0ab3a092393374be2f3f6cdcfd

Thank you again!

**Comment by wojtekmach** [comment]
Yup I just confirmed the fix works. Thanks!
