### ISSUE TITLE
httpc module is unspecced

### ISSUE THREAD

**Issue by ilya-klyuchnikov** [erlang/otp#6245]
**Describe the bug**
I would expect all public functions from OTP have specs - which would make them better for tools like dialyzer and eqwalizer (https://github.com/whatsapp/eqwalizer). The httpc module doesn't have any proper specs.

https://www.erlang.org/doc/man/httpc.html has "pseudo-specs" of no use for practical tooling.

**Comment by garazdawi** [comment]
It has long been on our todo list to make all public functions have specs and use them for documentation, but it has not been prioritized to be done yet. Contributions are welcome!

**Comment by TD5** [comment]
@ilya-klyuchnikov you could probably get a decent amount of milage from running Dialyzer's Typer, then running eqwalizer on the result to tweak the specs, when validating them manually.

**Comment by ilya-klyuchnikov** [comment]
> @ilya-klyuchnikov you could probably get a decent amount of milage from running Dialyzer's Typer, then running eqwalizer on the result to tweak the specs, then validating them manually against the docs.

I don't think typer is needed here - it's mostly about porting https://www.erlang.org/doc/man/httpc.html into proper specs and types.

**Comment by kikofernandez** [comment]
closed by [PR-6449](https://github.com/erlang/otp/pull/6449)
