### ISSUE TITLE
OTP 22.3.4.20: Seg fault in beam/erl_gc.h move_boxed

### ISSUE THREAD

**Issue by scbafk** [erlang/otp#6246]
**Describe the bug**
A segmentation fault occurs while running an elixir phoenix app. It appears to happen randomly. 

**To Reproduce**
I do not know how to reproduce this aside from letting it run for 24 hours. Generally at least one seg fault will occur.

**Expected behavior**
No seg fault.

**Affected versions**
22.3.4.20

**Additional context**
I have a core file and am happy to share it if needed. Here is the backtrace from the main thread:
```
#0  0x0000556ecec4119a in move_boxed (orig=0x7fa003c50888, hpp=0x7fa00a1bf548, hdr=5803546652255022912, ptr=<optimized out>)
    at beam/erl_gc.h:91
#1  sweep (src_size=0, src=0x0, ohsz=<optimized out>, oh=<optimized out>, type=ErtsSweepHeaps, n_htop=<optimized out>, n_hp=0x7fa003c50890)
    at beam/erl_gc.c:2256
#2  sweep_heaps (old_heap=<optimized out>, old_heap_size=<optimized out>, n_htop=<optimized out>, n_hp=<optimized out>) at beam/erl_gc.c:2318
#3  full_sweep_heaps (p=p@entry=0x7fa00d483238, live_hf_end=live_hf_end@entry=0xfffffffffffffff8, n_heap=n_heap@entry=0x7fa003c4f318, 
    n_htop=<optimized out>, n_htop@entry=0x7fa003c4f318, objv=objv@entry=0x7fa00db00200, nobj=nobj@entry=4, hibernate=0, 
    oh_size=<optimized out>, oh=<optimized out>) at beam/erl_gc.c:1991
#4  0x0000556ecec44464 in major_collection (recl=<synthetic pointer>, ygen_usage=<optimized out>, nobj=4, objv=0x7fa00db00200, 
    need=<optimized out>, live_hf_end=0xfffffffffffffff8, p=0x7fa00d483238) at beam/erl_gc.c:1855
#5  garbage_collect (p=0x7fa00d483238, live_hf_end=0xfffffffffffffff8, need=5, objv=0x7fa00db00200, nobj=4, fcalls=3927, max_young_gen_usage=0)
    at beam/erl_gc.c:781
#6  0x0000556ecec45bab in erts_garbage_collect_nobump (p=0x7fa00d483238, need=5, objv=0x7fa00db00200, nobj=4, fcalls=3927) at beam/erl_gc.c:898
#7  0x0000556eceae99df in process_main (x_reg_array=0x7fa00db00200, f_reg_array=0x142295bba1445bd)
    at x86_64-unknown-linux-gnu/opt/smp/beam_hot.h:5481
#8  0x0000556eceaecc4c in sched_thread_func (vesdp=0x7fa00cac2f80) at beam/erl_process.c:8512
#9  0x0000556eced2b563 in thr_wrapper (vtwd=0x7ffda9932c70) at pthread/ethread.c:118
#10 0x00007fa04e491160 in ?? () from /lib/ld-musl-x86_64.so.1
```

beam args:
`/OTP/subdir/bin/x86_64-unknown-linux-gnu/beam.smp -P 2000000 -- -root /OTP/subdir -progname /OTP/subdir/bin/cerl -- -home`

full start command
`/app/releases/0.1.0/../../erts-11.2.2.15/bin/cerl -elixir ansi_enabled true -noshell -s elixir start_cli -debug -mode embedded -setcookie <redacted> -name <redacted> -config /app/tmp/app-0.1.0-20220825215403-66ed.runtime -boot /app/releases/0.1.0/start -boot_var RELEASE_LIB /app/lib -args_file /app/releases/0.1.0/vm.args -extra --no-halt`

system information:
```
OTP release: 22
ERTS version: 10.7.2.12
Compile date: Tue Aug 23 22:12:22 2022
Arch: x86_64-unknown-linux-gnu
Endianness: Little
Word size: 64-bit
HiPE support: no
SMP support: yes
Thread support: yes
Kernel poll: Supported and used
Debug compiled: no
Lock checking: no
Lock counting: no
Node name: <redacted>
Number of schedulers: 4
Number of async-threads: 1
```

I apologize for including elixir code here but I figure the more context the better. This issue started happening after I moved ssl termination from the app to a proxy.

```
 # in config/releases.exs
 # configuration without seg fault
  http: [port: 80],
  url: [ host: System.fetch_env!("HOSTNAME"), port: 443],
  https: [		
    port: 443,		
    cipher_suite: :compatible,
    ...	
    transport_options: [socket_opts: [:inet6]] 
  ],

  # configuration with seg fault
  http: [port: 4000],
  url: [ host: System.fetch_env!("HOSTNAME"), port: 443],
  # https config removed
```

I do not know how to gather the NIFs used by my application, I will need some guidance there. I don't know how useful posting the elixir app's dependencies will be for ya'll so I will hold off on that.

**Comment by garazdawi** [comment]
Hello!

Erlang/OTP 22 is no longer supported so I suggest that you upgrade to a supported release (23, 24 or 25).

That being said, if you have nifs in your system then they are the most likely culprit to this issue. We just merged a PR with details on how to debug nifs: https://github.com/erlang/otp/pull/6121. Have a look at that and see if you can reproduce the issue in a debug build.

**Comment by scbafk** [comment]
Wonderful, the docs are very helpful. I will see what I can find. Thank you!

**Comment by garazdawi** [comment]
Closing this, if you think you have found a bug in the VM while debugging, feel free to re-open this issue or create a new one.

**Comment by scbafk** [comment]
Ok will do. I'm still debugging. I'll keep posting updates here as things happen.
