### ISSUE TITLE
"disksup" should allow check intervals smaller than 1 minute

### ISSUE THREAD

**Issue by lukebakken** [erlang/otp#6283]
**Is your feature request related to a problem? Please describe.**

Team RabbitMQ would love to use the built-in disk monitor that ships with Erlang/OTP - `disksup`. Unfortunately, the smallest `disk_space_check_interval` allowed is 1 minute. RabbitMQ users can be very good a filling disks so we have written our own disk monitor that allows more frequent checks. I'm certain other data services would benefit from shorter check intervals as well.

**Describe the solution you'd like**

We would like to be able to specify `disk_space_check_interval` values in milliseconds. Currently, the default minimum value allowed in RabbitMQ is 100ms.

**Describe alternatives you've considered**

RabbitMQ has its own disk monitor to work around this, but we'd love to use `disksup`!

**Additional context**

Related issue - https://github.com/erlang/otp/issues/6156

Maintaining our own disk monitor has been a source of headaches -
* https://github.com/rabbitmq/rabbitmq-server/pull/5241
* https://github.com/rabbitmq/rabbitmq-server/pull/5726

**Comment by michaelklishin** [comment]
I agree that many would probably choose to use a value in the 10-30s range. That's not too often and provides a "refresh rate" similar to many external monitoring setups.

**Comment by rickard-green** [comment]
A pull request for this is welcome. You can expand the type of the `disk_space_check_interval` parameter to `number()`, so that intervals smaller than a minute can be expressed by a `float()`.

**Comment by lukebakken** [comment]
Great! I'll get right on it. I'm assuming there is value in a hard lower bound to the interval so I'll include that.

**Comment by rickard-green** [comment]
Fixed by #6385
