### ISSUE TITLE
problem installing RabbitMQ/erlang

### ISSUE THREAD

**Issue by YongMinXuan** [erlang/otp#6325]
Hi everyone!
got a question
I am trying to install RabbitMQ on a virtual machine. Running the installer works fine on local environment, but when the file is transferred to the VM and executed, an error pops up like so:
Error! Can't initialise plug--ins directory. Please try again later.
I did some digging around and it seems to be a permission issue, according to others online (https://www.bleepingcomputer.com/forums/t/607935/error-cant-initialize-plug-in-directoryplease-try-again-later/), granting 'Full Control' over the Temp folder and over the installer should resolve the issue. However, it does not work.
I have tried many methods and all do not seem to work, and I am still encountering the issue. Would appreciate if anyone has managed to overcome this and can share some insights.
Summary:
- Versions tried: 3.9.14, 3.10.7
- Do NOT have administrator rights
- Can run Administrator mode in PowerShell (this was used to try and execute the installer)
- Granting 'Full Control' does not work.
- Using the ZIP folder of installations to transfer to directory does not work as well
does anyone have any idea?

**Comment by garazdawi** [comment]
Hello!

Since you are running RabbitMQ, I suggest you ask them why it is not working: https://groups.google.com/g/rabbitmq-users

Or ask on [ErlangForums](https://erlangforums.com/) and see if someone there can help you.

**Comment by YongMinXuan** [comment]
Hello, I asked that qns there and was asked to post here instead.
