### ISSUE TITLE
systools:make_script error reporting is misleading

### ISSUE THREAD

**Issue by max-au** [erlang/otp#6368]
**Describe the bug**
When an application contains duplicate dependencies, systools:make_script fails with "Undefined applications: [dep]". 

**To Reproduce**
Example of myapp.app:
```
{application, myapp, [
    {vsn, "1.0.0"},
    {applications, [kernel, stdlib,
        dep, dep]},
]}.
```
Note that "dep" dependency is mentioned twice. This is not an error anywhere, until I try to build a release with myrel.rel file:

```
{release,{"myrel","1.0.0"},
         {erts,"13.0.2"},
         [{myapp,"1.0.0"},
          {kernel,"8.4.1"},
          {stdlib,"4.0.1"},
          {dep, "1.0.0"}]}.
```

Both `dep` and `myapp` are in the myrel.rel file, but since `dep` is mentioned twice in myapp.app, `systools_make:check_applications/1` throws "Undefined applications: [dep]". 

**Expected behavior**
I would expect to see an error like "myapp has duplicate dependency on dep".

**Affected versions**
All of them.

**Comment by frazze-jobb** [comment]
Thanks for the bug report, I fixed it in #6389
