### ISSUE TITLE
TLS connection error: {unexpected_msg,{internal,{change_cipher_spec,<<1>>}}}

### ISSUE THREAD

**Issue by timofey-barmin** [erlang/otp#6374]
**Describe the bug**
TLS connection from erlang 24.1.6 to erlang 24.3.4.5  gets established and immediately gets closed with the following error in log: `{unexpected_msg,{internal,{change_cipher_spec,<<1>>}}}`

 24.3.4.5 -> 24.1.6, 24.1.6 -> 24.1.6, 24.3.4.5 -> 24.3.4.5 connections seem to work fine.

**To Reproduce**
24.3.4.5 node (server):
```
5> {ok, LS} = ssl:listen(21176, [{keyfile, "./pkey.pem"}, {certfile, "./chain.pem"}, {versions, ['tlsv1.3']}]), Accept = fun (LSS) -> {ok, HS} = ssl:transport_accept(LSS, 60000), ssl:handshake(HS, 30000) end, {ok, S} = Accept(LS).
=NOTICE REPORT==== 17-Oct-2022::19:24:39.974949 ===
TLS server: In state wait_finished at ssl_gen_statem.erl:736 generated SERVER ALERT: Fatal - Unexpected Message
 - {unexpected_msg,{internal,{change_cipher_spec,<<1>>}}}
** exception error: no match of right hand side value {error,
                                                       {tls_alert,
                                                        {unexpected_message,
                                                         "TLS server: In state wait_finished at ssl_gen_statem.erl:736 generated SERVER ALERT: Fatal - Unexpected Message\n {unexpected_msg,{internal,{change_cipher_spec,<<1>>}}}"}}}
```

24.1.6 node (client):
```
7> ssl:connect({127,0,0,1}, 21176, []).
=WARNING REPORT==== 17-Oct-2022::19:04:55.480291 ===
Description: "Authenticity is not established by certificate path validation"
     Reason: "Option {verify, verify_peer} and cacertfile/cacerts is missing"

{ok,{sslsocket,{gen_tcp,#Port<0.9>,tls_connection,undefined},
               [<0.135.0>,<0.134.0>]}}
8> =NOTICE REPORT==== 17-Oct-2022::19:04:55.484117 ===
TLS client: In state connection at tls_record_1_3.erl:340 generated CLIENT ALERT: Fatal - Bad Record MAC
 - decryption_failed
```

**Expected behavior**
Connections are not expected to be closed.

**Affected versions**
24.3.4.5

**Additional context**
Please see the traffic recording for more context: 
[unexpected_msg_tcpdump.zip](https://github.com/erlang/otp/files/9805823/unexpected_msg_tcpdump.zip)

Will appreciate any help, thanks!

**Comment by IngelaAndin** [comment]
You are reporting a bug that has already been fixed so you need to upgrade to a version that not has the bug, and if you choose to run the version where the bug exists it could be possible to work around it by specifying to run only TLS-1.2 or only TLS-1.3 but you can not make the bug go away without taking the patch.

**Comment by timofey-barmin** [comment]
@IngelaAndin 
Thanks for the quick reply!
It doesn't seem to be fixed in the latest 24 (24.3.4.6). Or do you mean it is fixed in erlang 25 and you don't plan to fix it in erlang 24 at all?

If so could you please point me to the patch that fixes this issue so I can backport it to erlang 24 locally?

We can't upgrade to erlang 25 right now so we had to rollback to 24.3.4.4 which doesn't seem to be affected by this bug.

**Comment by IngelaAndin** [comment]
The bug is fixed in OTP-24.3.4.5. It is actually a client bug and your client is running  OTP-24.1.6.
See  #6241  #6249

**Comment by timofey-barmin** [comment]
Thanks a lot Ingela!
Unfortunately it is a bit hard to upgrade the client side erlang in our case (because in order to perform the upgrade we need to establish a TLS connection first, which is broken), so I am looking into how we can work around this problem on the server side. 
Basically we need erl 24.3.4.4 to be able to establish a TLS connection to erl 24.3.4.6 or later. We can't change anything on the client side (because we don't control it). Unfortunately setting TLS version to 1.2 on the server side is not option for us as well. 
What we can do is we can patch the server side erlang, so the connection will work the following way: erl 24.3.4.4 -> erl 24.3.4.6 with a patch.
After looking at the [patch](https://github.com/erlang/otp/commit/cafbd7cb5eb5908912a59a4833fee5fc990ab3f7) that broke the compatibility between those versions I think I come up with something that makes it work for me. Would you mind taking a quick look at this small patch? Do you think it is safe to do something like that, or is there a chance that I will break something else?

```
diff --git a/lib/ssl/src/tls_connection_1_3.erl b/lib/ssl/src/tls_connection_1_3.erl
index 51b964a27e..8511591858 100644
--- a/lib/ssl/src/tls_connection_1_3.erl
+++ b/lib/ssl/src/tls_connection_1_3.erl
@@ -370,6 +370,9 @@ wait_cert(enter, _, State0) ->
 wait_cert(internal = Type, #change_cipher_spec{} = Msg,
           #state{session = #session{session_id = Id}} = State) when Id =/= ?EMPTY_ID ->
     handle_change_cipher_spec(Type, Msg, ?FUNCTION_NAME, State);
+wait_cert(internal = Type, #change_cipher_spec{} = Msg,
+          #state{ssl_options = #{middlebox_comp_mode := true}} = State) ->
+    handle_change_cipher_spec(Type, Msg, ?FUNCTION_NAME, State);
 wait_cert(internal,
           #certificate_1_3{} = Certificate, State0) ->
     case tls_handshake_1_3:do_wait_cert(Certificate, State0) of
@@ -405,6 +408,9 @@ wait_cv(Type, Msg, State) ->
 wait_finished(enter, _, State0) ->
     State = handle_middlebox(State0),
     {next_state, ?FUNCTION_NAME, State,[]};
+wait_finished(internal = Type, #change_cipher_spec{} = Msg,
+              #state{ssl_options = #{middlebox_comp_mode := true}} = State) ->
+    handle_change_cipher_spec(Type, Msg, ?FUNCTION_NAME, State);
 wait_finished(internal = Type, #change_cipher_spec{} = Msg,
               #state{session = #session{session_id = Id}} = State) when Id =/= ?EMPTY_ID ->
     handle_change_cipher_spec(Type, Msg, ?FUNCTION_NAME, State);
```

Thanks a lot!

**Comment by anuthan** [comment]
@IngelaAndin Could you help us out by answering Timofey's question above? Any help is appreciated. Thanks in advance.
