### ISSUE TITLE
Make it possible to choose a node in proc_lib:start_link/5

### ISSUE THREAD

**Issue by mat-hek** [erlang/otp#6375]
**Is your feature request related to a problem? Please describe.**
Hello,

I'd like to `start_link` a gen_server on a particular node. To my knowledge, there's no clean way to do that now.

Here's my use case:
> I have a ‘job manager’ process that receives jobs to execute and spawns workers on demand. If a worker dies, the manager cancels the entire work related to the given job and notifies the process that requested the job, so it’s a very basic ‘supervision’. Workers handling the same job can talk to each other via message passing. If the current node is busy, the manager can spawn a worker on another node - here I need the remote start_link. The nodes are well connected in a local cluster, so there’s no need to worry about netsplits and so on (at least for now).
> I imagine that having a separate supervision tree on each node would require a significant refactor and introduce a lot more complexity to the system.

And the related thread on Erlang forum https://erlangforums.com/t/how-to-start-link-a-gen-server-on-an-arbitrary-node/1948

**Describe the solution you'd like**
I think this could be solved by adding a `{node, Node}` option to the `proc_lib:start_spawn_option` type. If such option is passed to `start_link`, proc_lib could pass the node to `proc_lib:spawn_link`.

**Describe alternatives you've considered**
I considered using monitors, but AFAIK they don't provide some guarantees that links give me, in particular:
-  `DOWN` messages get enqueued in process message queue and it can take time till they're processed. `EXIT` signals can stop a process immediately.
- Monitors don't have anything like the `kill` signal that can't be trapped
- In my case, I would need two-way monitoring, that would be more complex than just using `start_link`

Regards,
Mateusz

**Comment by rickard-green** [comment]
We do not want to introduce such functionality. `gen_server`s are intended to be supervised locally, so the "correct" way of doing it would be to implement an application that is started on the remote node which then starts and supervise `gen_server`s on the remote node.

That being said, if you want to do it the way you described, you can start the `gen_server` remotely by following [`max-au`'s advise in the forum thread](https://erlangforums.com/t/how-to-start-link-a-gen-server-on-an-arbitrary-node/1948/8) using [`proc_lib:spawn_link()`](https://www.erlang.org/doc/man/proc_lib.html#spawn_link-4) and [`gen_server:enter_loop()`](https://www.erlang.org/doc/man/gen_server.html#enter_loop-3) with minor effort.
