### ISSUE TITLE
zip failing to open valid zip file

### ISSUE THREAD

**Issue by trashhalo** [erlang/otp#6379]
**Describe the bug**
Word documents are zip files with a different extension. Newer word documents are failing to open using zip. They open using the elixir library zstream, and the linux command line unzip. This causes me to believe they are valid zip files but something is wrong in erlang.

**To Reproduce**
Steps to reproduce the behavior.
[demo_newer_word.docx](https://github.com/erlang/otp/files/9809774/demo_newer_word.docx)
1. download this docx file2. 
2. in iex run `:zip.unzip("demo_newer_word.docx")`3. 

```elixir
iex(1)> :zip.unzip("samples/demo_newer_word.docx")
{:error,
 {:EXIT,
  {{:badmatch, "samples/demo_newer_word.docx"},
   [
     {:zip, :binary_io, 2, [file: 'zip.erl', line: 1817]},
     {:zip, :get_end_of_central_dir, 3, [file: 'zip.erl', line: 1351]},
     {:zip, :get_central_dir, 3, [file: 'zip.erl', line: 1293]},
     {:zip, :do_unzip, 2, [file: 'zip.erl', line: 385]},
     {:zip, :unzip, 2, [file: 'zip.erl', line: 375]},
     {:elixir, :"-eval_external_handler/1-fun-2-", 4,
      [file: 'src/elixir.erl', line: 298]},
     {:erl_eval, :do_apply, 7, [file: 'erl_eval.erl', line: 748]},
     {:elixir, :eval_forms, 3, [file: 'src/elixir.erl', line: 288]}
   ]}}}
```
**Expected behavior**
it opens

**Affected versions**
Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

**Comment by jdamanalo** [comment]
Elixir strings are different from Erlang strings.

`:zip.unzip('demo_newer_word.docx')`

**Comment by trashhalo** [comment]
```
iex(1)> :zip.unzip('samples/demo_newer_word.docx')
{:ok,
 ['[Content_Types].xml', '_rels/.rels', 'word/_rels/document.xml.rels',
  'word/document.xml', 'word/footnotes.xml', 'word/endnotes.xml',
  'word/header1.xml', 'word/footer1.xml', 'word/theme/theme1.xml',
  'word/settings.xml', 'docProps/core.xml', 'word/fontTable.xml',
  'word/webSettings.xml', 'word/styles.xml', 'docProps/app.xml']}
iex(2)> :zip.unzip('samples/demo.docx')
{:ok,
 ['_rels/.rels', 'docProps/core.xml', 'docProps/app.xml', 'word/document.xml',
  'word/styles.xml', 'word/fontTable.xml', 'word/theme/theme1.xml',
  'word/header1.xml', 'word/footer1.xml', 'word/settings.xml',
  'word/_rels/document.xml.rels', '[Content_Types].xml']}
iex(3)>
```
confirming that both doc files open with :zip. going to close this out and address the bug on the library side. thank you. Im new here!
