### ISSUE TITLE
erts/emulator/sys/win32/sys.c:create_child_process support for paths with spaces in spawn mode

### ISSUE THREAD

**Issue by inikulshin** [erlang/otp#6387]
I think there is a bug in `erts/emulator/sys/win32/sys.c:create_child_process` in `spawn` mode:

* It was initially found for `inet_gethost` in **24.3.*** (https://github.com/elixir-lang/elixir/issues/11785)
* Since **25.0** `inet_gethost` is spawn as `spawn_executable`, but the bug can be reproduced with any other `command parameters` in `spawn` mode, that will be expanded to `<directory with spaces>\command parameters`

**Describe the bug**
If `static int application_type` is ran with `originalName = "inet_gethost"` (w/o quotes), the output path (`wfullpath`) may contain spaces, but `requote` output will be `FALSE`, as it set by **input** and not by **output**,

After that the following code will produce `newcmdline` with unquoted `execPath`:

    if (requote) {
        wcscat(newcmdline, L"\"");
    }
    wcscat(newcmdline, execPath);
    if (requote) {
        wcscat(newcmdline, L"\"");
    }

And finally, `CreateProcessW` with both non-NULL `execPath` and `newcmdline` will cause to process to run, but the `newcmdline` will be split to `argv`: `argv[0] = "C:\Program"` and `argv[1] = "Files+Programming\Erlang\erts-12.3.1\bin\inet_gethost.exe"`

**Expected behavior**
`argv` of spawned process should match the command

**Affected versions**
**24.3**, **25.***

**Additional context**
It's introduced in https://github.com/erlang/otp/commit/f0a273c5a5ebfc97cfe1e88341c803b85d2295e4

@RaimoNiskanen FYI

It worth to check also paths with `%`, `&` and `^`: they are allowed in Windows paths, and must be escaped with double quotes because they have special meaning in command line.

**Comment by sverker** [comment]
@inikulshin I did a proposed fix in #6396.

**Comment by sverker** [comment]
Fixed by #6396.
