### ISSUE TITLE
:net_kernel.start invoked from Node.start does not work just after restarting macOS

### ISSUE THREAD

**Issue by zacky1972** [erlang/otp#6399]
**Describe the bug**

When using `Node.start(:host, :shortnames)` in Elixir just after restarting macOS, then get the following error:

```elixir
07:25:06.212 [notice] Protocol 'inet_tcp': register/listen error: econnrefused

{:error,
 {{:shutdown, {:failed_to_start_child, :net_kernel, {:EXIT, :nodistribution}}},
  {:child, :undefined, :net_sup_dynamic,
   {:erl_distribution, :start_link,
    [
      %{
        clean_halt: false,
        name: :host,
        name_domain: :shortnames,
        net_tickintensity: 4,
        net_ticktime: 60,
        supervisor: :net_sup_dynamic
      }
    ]}, :permanent, false, 1000, :supervisor, [:erl_distribution]}}}
```

I heard `Node.start/3` calls `:net_kernel.start/2` (the comment: https://github.com/elixir-lang/elixir/issues/12219#issuecomment-1295734313 )

So, I ask the OTP team to fix this issue. 

**To Reproduce**

1. Reboot macOS.
2. Enter `iex` by the terminal
3. Run `Node.start(:host, :shortnames)`

**Expected behavior**

`Node.start(:host, :shortnames)` returns `{:ok, #PID<...>}`.

**Affected versions**
The OTP versions that are affected by this bug.

```
Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.1 (compiled with Erlang/OTP 25)
```

**Additional context**
Add any other context about the problem here. If you wish to attach Erlang code you can either write it directly in the post using [code tags](https://guides.github.com/features/mastering-markdown/), create a [gist](https://gist.github.com), or attach it as a zip file to this post.

I posted the issue https://github.com/elixir-lang/elixir/issues/12219#issuecomment-1295734313 
And got the comment https://github.com/elixir-lang/elixir/issues/12219#issuecomment-1295734313
So I posted this issue.

**Comment by josevalim** [comment]
This is expected. For the Erlang distribution to work, you need `epmd` running. When you do `iex --sname` (or `erl -sname`), `epmd` is automatically started for you. However, if you kill `epmd`, you can reproduce the same failure without restarting the machine:

```
$ killall epmd
$ iex
Erlang/OTP 25 [RELEASE CANDIDATE 2] [erts-13.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.15.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Node.start(:host, :shortnames)

09:09:32.101 [notice] Protocol 'inet_tcp': register/listen error: econnrefused
```

Perhaps the error message could be clearer, either by changing the exit code to `noepmd` or by also logging a clearer reason, but the behaviour is expected. :)

PS: Node `Node.start(:host, :shortnames)` is equivalent to `net_kernel:start([host, shortnames])`.

**Comment by zacky1972** [comment]
I see.

How do I start `epmd`?

**Comment by zacky1972** [comment]
Oh, I understood.

Simply, run `epmd` on the shell
