### ISSUE TITLE
Using OpenSSL 3.0 without any deprecated functions

### ISSUE THREAD

**Issue by lukebakken** [erlang/otp#6406]
I'm investigating the use of OpenSSL 3.0's FIPS module with RabbitMQ. I have compiled OpenSSL using the `enable-fips` and `no-deprecated` configuration options and, as expected, Erlang does not compile due to the use of deprecated functions in OpenSSL.

Is anyone working on updating Erlang to not use deprecated OpenSSL functions if version 3.0 is being used? I'm checking because I don't want to duplicate work.

Thanks and I apologize if a github issue is not the correct forum for a question like this.

cc @IngelaAndin

**Comment by IngelaAndin** [comment]
We did do a lot of work in that area, the missing parts, as far as I know, are FIPS and ENGINE. Which is currently not the highest priority so if you would like to help with that you are welcome.

**Comment by lukebakken** [comment]
https://github.com/erlang/otp/issues/4577

**Comment by IngelaAndin** [comment]
Yes, that work is related.

**Comment by lukebakken** [comment]
https://github.com/erlang/otp/issues/4577#issuecomment-945396214

@HansN, I'm sure you already know this, but it seems like the only code that continues to use deprecated OpenSSL functions are the following:

https://github.com/erlang/otp/blob/master/lib/crypto/c_src/ec.c#L344
https://github.com/erlang/otp/blob/master/lib/crypto/c_src/ec.c#L401-L464

Once that is updated to use the OpenSSL 3.0 API, then enabling the 3.0 FIPS module should ["just work"](https://www.openssl.org/docs/man3.0/man7/fips_module.html) (after re-enabling `--enable-fips` and related code in Erlang, of course).

Is there a timeline for addressing this last bit of code and re-enabling FIPS support? OTP 27 perhaps? Thanks!

**Comment by sverker** [comment]
@michaelklishin I've started to look at OpenSSL 3 and FIPS.
I built OpenSSL-3.0.9 with `enable-fips` and `no-deprecated` but I could not even get it to load. The call `OSSL_PROVIDER_load(NULL, "fips")` in `lib/crypto/c_src/crypto.c` fails.
As FIPS is not really high prio for us, I now reverting back to build OpenSSL-3.0.9 with only `no-deprecated` and try getting that to work to start with.
If you can investigate how OpenSSL 3 with FIPS is suppose to be built and used, that would be helpful.

**Comment by lukebakken** [comment]
Hi @sverker, please see my comment [here](https://github.com/erlang/otp/issues/6406#issuecomment-1514026837). There is a minimal set of code in `ec.c` that continues to use deprecated OpenSSL functions.

> The call OSSL_PROVIDER_load(NULL, "fips") in lib/crypto/c_src/crypto.c fails

The FIPS provider in your OpenSSL installation must be enabled. Here are my notes from earlier this year. Note that I last tried this in January and it may not currently work. I'll find time today to give it another try.

* I have [this branch](https://github.com/lukebakken/otp/tree/lukebakken/give-fips-a-try) where I have re-enabled the ability to specify the Erlang configuration `--enable-fips` when OpenSSL 3.0 is used.
* I built OpenSSL 3 and Erlang using the following configurations. This configures OpenSSL 3 to provide the FIPS module and configures both applications to use the custom-compiled OpenSSL in `$HOME/opt/openssl/3.1.1` rather than the system-installed one:
    ```
    # openssl configuration
    ./config enable-fips --shared \
        --prefix="$HOME/opt/openssl/3.1.1" \
        -Wl,-rpath="$HOME/opt/openssl/3.1.1/lib64"

    # erlang configuration
    ./configure --prefix="$HOME/opt/erlang" \
        --enable-silent-rules=no \
        --without-docs \
        --without-wx \
        --without-debugger \
        --without-observer \
        --without-cdv \
        --without-et \
        --without-odbc \
        --without-wx \
        --with-microstate-accounting=extra \
        --enable-smp-support \
        --enable-threads \
        --enable-kernel-poll \
        --disable-hipe \
        --with-ssl="$HOME/opt/openssl/3.1.1" \
        --with-ssl-rpath="$HOME/opt/openssl/3.1.1/lib64" \
        --enable-fips
    ```
* Then, configure OpenSSL 3 to actually enable the FIPS provider. To do so, the `$HOME/opt/openssl/3.1.1/ssl/openssl.cnf` file is edited. Note that you must provide the absolute path to the `fipsmodule.cnf` file:
    ```
    # For FIPS
    # Optionally include a file that is generated by the OpenSSL fipsinstall
    # application. This file contains configuration data required by the OpenSSL
    # fips provider. It contains a named section e.g. [fips_sect] which is
    # referenced from the [provider_sect] below.
    # Refer to the OpenSSL security policy for more information.
    .include /home/lbakken/opt/openssl/3.1.1/ssl/fipsmodule.cnf
    ```
* That configuration enables FIPS for *all* applications that use the OpenSSL 3 libraries in `$HOME/opt/openssl/3.1.1/lib64`. See this setting documented here - https://www.openssl.org/docs/man3.0/man7/fips_module.html
* Then, when Erlang is started, FIPS can be enabled:
    ```
    lbakken@shostakovich ~/opt/erlang
    $ ./bin/erl
    Erlang/OTP 26 [DEVELOPMENT] [erts-13.1.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

    Eshell V13.1.3 (press Ctrl+G to abort, type help(). for help)
    (search)`cr': crypto:info_fips().
    not_enabled
    (search)`crypto': crypto:enable_fips_mode(true).
    true
    3> crypto:info_fips().
    enabled
    ```
    This may not seem like much but it's encouraging.
* I can also run the `crypto` app test suite using FIPS. I see failures, with some due to algorithms being used that FIPS does not support, which means that the FIPS provider _is_ being used.

**Comment by sverker** [comment]
Thanks, @lukebakken for info about FIPS. I current have crypto_SUITE going clean on OpenSSL 3.0.9 with `no-deprecated`. That seems promising for FIPS. To be continued on monday.

**Comment by lukebakken** [comment]
@sverker I'm happy to assist in any way. Thanks!

**Comment by sverker** [comment]
PR #7392 is my progress running FIPS with OpenSSL 3.0.
I can load and run crypto, but I get 7 failing test cases in crypto_SUITE.

**Comment by lukebakken** [comment]
@sverker would you mind sharing how you're building OpenSSL, Erlang, and running tests? I get the "can't load library" error when I try to execute `crypto:start().`. No rush!

**Comment by sverker** [comment]
This is what I did.

Built and installed OpenSSL 3.0.9 with FIPS:
```
$ ./config enable-fips no-deprecated --prefix=/home/sverker/openssl-3.0.9-fips.no-deprecated
$ make
$ make test
$ make install
```
Built OTP #7392:
```
$ git clean -xfdq
$ export ERL_TOP=`pwd`
$ ./otp_build setup --with-ssl=/home/sverker/openssl-3.0.9-fips.no-deprecated --enable-fips
$ export PATH=$ERL_TOP/bin:$PATH
$ make -C lib/crypto
```
`otp_build setup` is the same as `configure && make` but with several disabled applications by default for faster build.
I don't install OTP, instead run $ERL_TOP/bin/erl directly in source tree.

At this point crypto fails to load the same as you (`"load, Library load-call unsuccessful (225)"`)

Then I edited `/home/sverker/openssl-3.0.9-fips.no-deprecated/ssl/openssl.cnf` according to [fips_module](https://www.openssl.org/docs/man3.0/man7/fips_module.html) and ended up with this diff:
```
< # .include fipsmodule.cnf
---
> .include /home/sverker/openssl-3.0.9-fips.no-deprecated/ssl/fipsmodule.cnf
61c61
< # fips = fips_sect
---
> fips = fips_sect
```
and that made crypto load successfully.

**Comment by sverker** [comment]
And I ran tests with
```
$ cd $ERL_TOP
$ make -C lib/crypto/test/ release_tests
$ make -C lib/common_test/test_server release_tests
$ cd  release/x86_64-pc-linux-gnu/test_server
$ erl
1> ts:install().
2> ts:run(crypto,crypto_SUITE,[batch]).
```
Test results in `$ERL_TOP/release/x86_64-pc-linux-gnu/test_server/index.html`.
