### ISSUE TITLE
code:soft_purge/1 incorrectly removes old code

### ISSUE THREAD

**Issue by SzBencej** [erlang/otp#6416]
**Describe the bug**
We noticed during live upgrade that we got a few badfun crashes. We investigated and came to the conclusion that probably the code:soft_purge/1 function removes the old code, even if there is an anomym fun is referenced.

**To Reproduce**

Given the following module:
```
-module(upgrade_test).

%% API
-export([sleep_map_good/0, sleep_map_bad/0]).

-spec sleep_map_good() -> list().
sleep_map_good() ->
  lists:map(fun(N) -> timer:sleep(500), N end, lists:seq(1, 300)).

-spec sleep_map_bad() -> list().
sleep_map_bad() ->
  lists:map(fun(_N) -> timer:sleep(500) end, lists:seq(1, 300)).
```

Load the module into a shell, spawn the sleep_map_good function, then change something in the module and reload the module. After that the code:soft_purge/1 does not purges the upgrade_test module, as expected.
```
Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Eshell V13.1.2  (abort with ^G)
1>
1>
1> c(upgrade_test).              
{ok,upgrade_test}
2> spawn_link(upgrade_test, sleep_map_good, []).
<0.92.0>
%% Here change something in the upgrade_test module
3> c(upgrade_test).                            
{ok,upgrade_test}
4> code:soft_purge(upgrade_test).              
false
5> code:soft_purge(upgrade_test).
false
6> code:soft_purge(upgrade_test).
false
```

But when the sleep_map_bad function is called the behaviour changes, even if only one hot code loading was made.
```
Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Eshell V13.1.2  (abort with ^G)
1> c(upgrade_test).              
{ok,upgrade_test}
2> spawn_link(upgrade_test, sleep_map_bad, []).
<0.92.0>
%% Here change something in the upgrade_test module
3> c(upgrade_test).                            
{ok,upgrade_test}
4> code:soft_purge(upgrade_test).              
true
5> =ERROR REPORT==== 2-Nov-2022::12:07:36.859520 ===
Error in process <0.92.0> with exit value:
{{badfun,#Fun<upgrade_test.1.39746713>},
 [{lists,map_1,2,[{file,"lists.erl"},{line,1320}]},
  {lists,map_1,2,[{file,"lists.erl"},{line,1320}]},
  {lists,map_1,2,[{file,"lists.erl"},{line,1320}]},
  {lists,map,2,[{file,"lists.erl"},{line,1315}]}]}

** exception error: bad function #Fun<upgrade_test.1.39746713>
     in function  lists:map_1/2 (lists.erl, line 1320)
     in call from lists:map_1/2 (lists.erl, line 1320)
     in call from lists:map_1/2 (lists.erl, line 1320)
     in call from lists:map/2 (lists.erl, line 1315)
5>
```

**Expected behavior**
When the sleep_map_bad function call is going during a soft purge, then don't purge the old version of upgrade_test module.
The same behaviour is expected from both of the functions.

**Affected versions**
I checked with 23.2.3 and 25.1.2

**Comment by rickard-green** [comment]
This is not a bug. This is how it is expected to work. References to `fun`s does *not* prevent purging of code. See *note* in the documentation of [`code:soft_purge/1`](https://www.erlang.org/doc/man/code.html#soft_purge-1) which refers to the more detailed explanation in the *note* in the [`erlang:check_process_code/3`](https://www.erlang.org/doc/man/erlang.html#check_process_code-3) documentation.

**Comment by SzBencej** [comment]
Thank you for your answer. I have read the documentation of erlang:check_process_code/3.
This still does not explain the inconsistency of the behaviour I described above.

When the fun in the sleep_map_good function returns with N the old module is never purged.
But when the fun returns with the result of timer:sleep/1 in sleep_map_bad function it is always purged.

**Comment by rickard-green** [comment]
The `fun` in `sleep_map_bad` makes a tail-call to `timer:sleep()`, i.e. it will not leave any references to the module on the stack. The `fun` in `sleep_map_good` does not make a tail-call and needs to build stack when calling `timer:sleep()` leaving a reference to the module on the stack.

**Comment by SzBencej** [comment]
Thank you for the explanation.
Can you direct me to the documentation or source code where it is described what are the direct references to a module?
In the note of the erlang:check_process_code/3 there is an example but what about the other direct references.

**Comment by rickard-green** [comment]
Direct references to a module are more or less just another way of saying pointers that point directly into the module code from the process. There can currently more or less only be these types of direct pointers into the code of a module from a process:
* The process is executing code in the module. In this case the process will have an instruction pointer pointing at an instruction in the module code.
* The process is executing a NIF in the module. Conceptually the same thing as previous point, but looks a bit differently internally.
* The process has executed code in the module which has called a function, via a body-call, external to the module and this external call has not yet returned. In this case, the stack will contain a pointer into the module code pointing to where to continue execution upon return from the called function.

Apart from this a saved stack trace may also point into the code, but it will be cleared, so it won't prevent a purge.

The actual code in the runtime system checking the process prior to a purge can be found in [`erts/emulator/beam/beam_bif_load.c:check_process_code()`](https://github.com/erlang/otp/blob/OTP-25.1.2/erts/emulator/beam/beam_bif_load.c#L1133-L1202).
