### ISSUE TITLE
Failed to write to erl_child_setup: 38

### ISSUE THREAD

**Issue by wydxyreh** [erlang/otp#6422]
**Describe the bug**

I'm new in erl.
I try to run RabbitMQ on Gramine, which make RabbitMQ run in a standalone environment and keep it safe.
But I failed with this error:

```
[root@iZbp182e5onp1lne1n5obzZ python]# gramine-direct ./python scripts/test.py
Failed to write to erl_child_setup: 38

Crash dump is being written to: erl_crash.dump...done
```

I've read the debug report of Gramine and didn't find any problem.
I tried to search the bug in RabbitMQ, but didn't find ant problem, too.
When I search this problem in erl, I find that `erl_child_setup:38` in `otp_src_25.0/erts/emulator/sys/unix/sys_drivers.c`:
```
if (errno == ERRNO_BLOCK || errno == EINTR) {
    return;
} else if (errno == EMFILE) {
    forker_sigchld(proto->u.start.port_id, errno);
    if (forker_deq(port_num, proto) == 0)
        driver_select(port_num, forker_fd, ERL_DRV_WRITE, 0);
    return;
} else {
    erts_exit(ERTS_DUMP_EXIT, "Failed to write to erl_child_setup: %d\n", errno);
}
```
I tried to locate `EINTR  and `EMFILE`, and find `EINTR  and `EMFILE` in `mingw64/x86_64-w64-mingw32/include/errno.h`, which were defined as specific numbers.
```
#define EINTR 4
#define EMFILE 24
```
I tried to locate `ERRNO_BLOCK` as well, and find it in `otp_src_25.0/erts/emulator/beam/sys.h`. After all I speculate that the number 38 in `erl_child_setup: 38` has a certain connection with `mingw64/x86_64-w64-mingw32/include/errno.h`.

But I can run RabbitMQ directly in terminal without any error.
I don't know how to deal with this problem.
Can you help me?

OS：AlibabaCloud（similar to CentOS）
arch: x86
rabbitmq-server: v3.10.7
Erlang/OTP 25

**To Reproduce**
Steps to reproduce the behavior.

It is hard to reproduce this problem.
First, it is hard for the developers to get AlibabaCloud.
Second, to reproduce, the developers need install `Gramine` and `RabbitMQ`, and try to run `RabbitMQ` in `Gramine`. 

**Expected behavior**

Run RabbitMQ successfully.

**Affected versions**
The OTP versions that are affected by this bug.

Erlang/OTP 25

**Additional context**
Add any other context about the problem here. If you wish to attach Erlang code you can either write it directly in the post using [code tags](https://guides.github.com/features/mastering-markdown/), create a [gist](https://gist.github.com), or attach it as a zip file to this post.

Here is the link of `erl_crash.dump`:
<https://1drv.ms/u/s!AmusSNbHLgPQhYIlthN_Kyk-O2ff1g?e=AzAd1f>

**Comment by rickard-green** [comment]
When googling "errno 38 Gramine" the results seem to indicate that it is an "Function not implemented" error. The error is the result of a call to `sendmsg()` on a unix domain socket. It seems that that operation is not supported on Gramine, but I have no experience with Gramine what so ever.

**Comment by wydxyreh** [comment]
> When googling "errno 38 Gramine" the results seem to indicate that it is an "Function not implemented" error. The error is the result of a call to `sendmsg()` on a unix domain socket. It seems that that operation is not supported on Gramine, but I have no experience with Gramine what so ever.

Thanks for you reply! I'm wondering where this problem is happening. And it seems that there are some problems when I using `Gramine` instead of `RBMQ`/`ERL`. I will consult `Gramine` on this question. Thanks again!
If I get this problem resolved, I will soon close the error.

**Comment by wydxyreh** [comment]
Now I konw `RabbitMQ v3.11.0` and `Gramine v1.3.1` do not match, beacuse RabbitMQ tries to use some data on unix socket, which is not supported in Gramine. But Gramine team will build all the blocks in the future. Information updated at 2022/11/23.
Thanks for your reply. I will close this soon.
