### ISSUE TITLE
Build otp-OTP-19.3.6.9 was fail on Apple silicon(chip)

### ISSUE THREAD

**Issue by RbBtSn0w** [erlang/otp#6453]
**Describe the bug**

I installed all dependency lib by homebrew

when I use './configure && make && sudo make install' 

have fail error log

`
❯ ./configure && make && sudo make install
./configure: line 2572: LM_PRECIOUS_VARS: command not found
Ignoring the --cache-file argument since it can cause the system to be erroneously configured
Disabling caching
checking build system type... arm-apple-darwin21.6.0
checking host system type... arm-apple-darwin21.6.0
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking for ld... ld
checking for env... /usr/bin/env
checking for GNU make... yes (make)
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln -s works... yes
checking for ranlib... ranlib
checking ERTS version... 8.3.5.4
checking OTP release... 19
checking OTP version... 19.3.6.9
configure: error: 

  You are natively building Erlang/OTP for a later version of MacOSX
  than current version (12.6). You either need to
  cross-build Erlang/OTP, or set the environment variable
  MACOSX_DEPLOYMENT_TARGET to 12.6 (or a lower version).

`

**To Reproduce**
Steps to reproduce the behavior.

1. download from version from  https://github.com/erlang/otp/releases/tag/OTP-19.3.6.9
2. open the finder, use the command line: ./configure && make && sudo make install

I was using kerl to try it, but it failed again.

**Expected behavior**

The build should be a success.

**Affected versions**
The OTP versions that are affected by this bug.
* 19.3.6.9
* 19.3.6.13

**Additional context**
Add any other context about the problem here. If you wish to attach Erlang code you can either write it directly in the post using [code tags](https://guides.github.com/features/mastering-markdown/), create a [gist](https://gist.github.com), or attach it as a zip file to this post.

**Comment by rickard-green** [comment]
OTP 19 is ancient, has been out of support for a number of years now,  and is known not to build on Apple Silicon. This is not anything we will fix. Use a supported OTP version. Currently OTP 23, 24, and 25 are supported.
