### ISSUE TITLE
Undocumented scoping rules in list comprehensions

### ISSUE THREAD

**Issue by RobinMorisset** [erlang/otp#6454]
I don't know whether this is a bug, or (more likely imho) something missing in the documentation or something that I missed.
On master, the following code:
```erlang
f() ->
  [Y || _ <- (Y = 42)].
```
is rejected with
```
test.erl:7:4: variable 'Y' is unbound
%    7|   [Y || _ <- (Y = 42)].
%     |    ^
```

whereas `[Y || Y <- 42]` naturally is fine.

I first thought that this means that variables bound in an expression in a generator are only bound for the rest of that comprehension's generators. But the following: `[Y || _ <- (Y = 42), Y <- Y]` is also rejected, showing that it is even more restrictive.

My current guess is that they are bound only for the duration of that expression itself. So I have 3 questions:
- Is my guess correct?
- If so, is it intended?
- If so, did I miss it in the documentation? (I checked https://www.erlang.org/doc/reference_manual/expressions.html#list-comprehensions and only found the following snippet: "The variables in the generator patterns shadow previously bound variables, including variables bound in a previous generator pattern.")

**Comment by bjorng** [comment]
> * Is my guess correct?

Yes.

> * If so, is it intended?

It seems to be:

https://github.com/erlang/otp/blob/0113d9cc5a11a14bafdded89b0ba9d700bacd20d/lib/stdlib/src/erl_lint.erl#L3687-L3690

> * If so, did I miss it in the documentation?

You probably did not miss anything. It's not documented as far as I know.

In my opinion, I don't see any usefulness of exporting the variables out of the generator expression, and it seems to be a backward incompatibility if we would do so, so I think we should keep the behavior and update the documentation.

What do you think?

**Comment by RobinMorisset** [comment]
I agree with you, this looks more like a missing piece of documentation than a bug.
I'll try to send a PR updating the documentation in the coming days, I just wanted to make sure I correctly understood the situation before doing so.
