### ISSUE TITLE
the `filelib:safe_relative_path` may return wrong result in macos

### ISSUE THREAD

**Issue by lafirest** [erlang/otp#6460]
**Describe the bug**
I use macOS Big Sur (Version 11.4) with OTP 24.1.5, and I found that `filelib:safe_relative_path` will return a wrong result if the `Cwd` is one of `/etc` `/tmp` `/var` `/home` 

e.g.
` filelib:safe_relative_path("foo/../foo", "/etc").`
will return
`foo/private/etc/foo`
but the correct result should be `foo`

` filelib:safe_relative_path("foo/../foo", "/home").`
will return
`unsafe`
but the correct result should be `foo`

**To Reproduce**
e.g.
` filelib:safe_relative_path("foo/../foo", "/etc").`

**Expected behavior**
return correct result

**Affected versions**
The version I used is 24.1.5,  but I think other versions also have this issue.

**Additional context**
Add any other context about the problem here. If you wish to attach Erlang code you can either write it directly in the post using [code tags](https://guides.github.com/features/mastering-markdown/), create a [gist](https://gist.github.com), or attach it as a zip file to this post.

**Comment by lafirest** [comment]
In Linux the `/bin` is wrong too,
e.g.
 `filelib:safe_relative_path("foo/../foo", "/bin").`
 will return: `"foo/usr/bin/foo"`

**Comment by juhlig** [comment]
On investigation, this happens when the second argument is a link (eg, `/bin` is a link to `/usr/bin` in Linux; but it could be any link anywhere) and the path given in the first argument descends and then climbs up to the (relative) top level.

```shell
$ mkdir foo
$ ln -s foo bar
```
_(We now have a real directory `foo` and a link to it, `bar`, in the current working directory)_
```erlang
1> % using a link as cwd and climbing back to the top level -> wrong
1>  filelib:safe_relative_path("a/b/../../c/d", "bar".
"a/foo/c/d"

2> % using a real dir as cwd and climbing back to the top level -> correct
2> filelib:safe_relative_path("a/b/../../c/d", "foo").
"c/d"

3> % using a link as cwd and not climbing to the top level -> correct
3> filelib:safe_relative_path("a/b/../c/d", "bar").
"a/c/d"

4> % using a real dir as cwd and not climbing to the top level -> correct
4> filelib:safe_relative_path("a/b/../c/d", "foo").
"a/c/d"
```

**Comment by juhlig** [comment]
Another issue with `safe_relative_path` is that the link loop detection may be wrong:
```shell
$ mkdir -p foo/foo/bar
$ ln -sr foo/foo/bar foo/bar
$ ln -s foo/bar bar
```
Resulting in an (admittedly weird) structure like this:
```text
/
|
+-- foo/
|   |
|   +-- foo/
|   |   |
|   |   +-- bar/
|   |         ^
|   +-- bar* -'
|         ^
+-- bar* -'
```
That is, we have two things on the top level:
* a directory named `foo`, containing two things:
  * another directory named `foo`, containing one thing:
    * a directory named `bar`
  * a link to `foo/bar` named `bar`
* a link to `foo/bar` named `bar`

This is obviously _not_ a loop. The `bar` on the top level links to the `bar` under the outer `foo`, and this `bar` in turn links to the directory `bar` under the inner `foo`, which is where the chain ends. However...
```erlang
1> filelib:safe_relative_path("bar", ".").
unsafe
```

**Comment by juhlig** [comment]
The linked PR should hopefully fix this issue. Tricky...
