### ISSUE TITLE
inet_dist_listen_min causes port conflict

### ISSUE THREAD

**Issue by zseronc** [erlang/otp#6461]
**Describe the bug**
win10 otp25
2 werl start with same args "-kernel inet_dist_listen_min 40001 -kernel inet_dist_listen_max 40001", then they both listen on 40001 port

**To Reproduce**
werl -kernel inet_dist_listen_min 40001 -kernel inet_dist_listen_max 40001 -name tom@127.0.0.1
werl -kernel inet_dist_listen_min 40001 -kernel inet_dist_listen_max 40001 -name joe@127.0.0.1

C:\Users\Administrator>epmd -names
epmd: up and running on port 4369 with data:
name tom at port 40001
name joe at port 40001

**Expected behavior**
i want dynamic port effects

**Affected versions**
win10 since otp25.0

**Comment by rickard-green** [comment]
Fixed in [OTP 25.2](https://www.erlang.org/patches/otp-25.2)
