### ISSUE TITLE
erlc allows to have side effects in "guards"

### ISSUE THREAD

**Issue by ilya-klyuchnikov** [erlang/otp#6466]
**Describe the bug**
https://www.erlang.org/doc/reference_manual/expressions.html#guard-expressions states that guards are designed to be free of side effects.
https://www.erlang.org/doc/reference_manual/expressions.html#maps-in-patterns - keys in maps are guard expressions

It's possible to create a guard expression with side effects.

**To Reproduce**
```erlang
-module(map_guards).
-compile([export_all, nowarn_export_all]).

dirty_loop() ->
  io:format("side_effect~n", []),
  dirty_loop().

-record(bar, {
  foo = dirty_loop()
}).

map_pattern(#{#bar{} := _}) ->
  ok1;
map_pattern(#{}) ->
  ok1.

main() ->
  map_pattern(#{#bar{foo = 1} => 1}).
```

```
$ erlc map_guards.erl
$ erl -noshell -s map_guards main
side_effect
side_effect
side_effect
side_effect
side_effect
side_effect
side_effect
side_effect
side_effect
side_effect
....
```

**Expected behavior**
erlc should not allow to construct guards with side effects

**Affected versions**
OTP 25.1.1

**Comment by bjorng** [comment]
Note that calling **any** function from within a guard is illegal, so this example should fail to compile even if the call to `io:format/2` were to be removed.

**Comment by mikpe** [comment]
> **Affected versions** OTP 25.1.1

Note that OTP-23 and OTP-24 are also affected by this bug.

**Comment by bjorng** [comment]
Yes, I will prepare patches for OTP 23 and OTP 24.
