### ISSUE TITLE
prevent_overlapping_partitions in larger clusters

### ISSUE THREAD

**Issue by MikaAK** [erlang/otp#6470]
#6214

I'm reopening This because it's continuing to happen. We tripled net_setuptime and doubled the busy buffer (though we noticed `:erlang.system_info(:dist_buf_busy_limit)` returns `1048576` by default, not sure how when the default is so low). Our cluster is getting taken out and we're getting loads of disconnect messages.
:global.sync is also hanging so seems like we need to revert back to otp 24. How can we successfully upgrade our 60+ node cluster? 

The nodes are clustered together but the global registered processes we have aren't propagated and can't be accessed 

To be clear this only happens after about a week of being upgraded, we do get overlap disconnects though quite often

We've also tried to set `-prevent_overlapping_partitions false` to all nodes and we're still getting `requested disconnect from node to prevent overlapping partition` messages

**Comment by starbelly** [comment]
> We've also tried to set `-prevent_overlapping_partitions false` to all nodes and we're still getting `requested disconnect from node to prevent overlapping partition` messages

I'm not sure if this is a typo or not, but AFAIK this argument has to be supplied as a kernel argument `-kernel prevent_overlapping_partitions false`. Hope this helps.

**Comment by rickard-green** [comment]
@MikaAK If you disable, `prevent_overlapping_partition` on all nodes, it will behave regarding this as it did in OTP 24. It seems, that you failed at disabling this. As @starbelly pointed out `-prevent_overlapping_partitions false` is not correct. If you've passed that as argument it will just silently be ignored and `prevent_overlapping_partitions` will still be enabled.

**Comment by MikaAK** [comment]
We upgraded to 25.1 hoping it would solve some of the issues with OOM

Unfortunately during this rollout we ran into OOM errors, our theory is because we're trying to deploy so many nodes at once, the traffic in global just explodes when trying to deploy 10-15 nodes of a 60 node cluster, despite higher distribution_busy_buffer settings and net_setuptime.

We also found a way to figure out if prevent_overlapping_partitions flag actually made it into the VM using

```elixir
Node.list() 
  |> Enum.map(fn n ->
    {n, elem(:erpc.call(n, fn -> :application.get_env(:kernel, :prevent_overlapping_partitions) end), 1)} 
  end) 
  |> Enum.filter(fn {_, a} -> a ===  true end)
```
Here's an image of our increase in memory around deploys
![image](https://user-images.githubusercontent.com/4650931/204753436-70620e49-74f2-4a37-a4cb-86fc13a749f7.png)
