### ISSUE TITLE
Documentation on escape sequences is incomplete

### ISSUE THREAD

**Issue by sirikid** [erlang/otp#6477]
Subj states that only letters can be used in caret notation:

https://github.com/erlang/otp/blob/1e47092987aa0f93adea8ece839d9bfb5f8662e2/system/doc/reference_manual/data_types.xml#L474-L478

But `scan_escape/2` does not check for this:

https://github.com/erlang/otp/blob/ab0ea053e2053eb77c37480cdf82994ac972ebde/lib/stdlib/src/erl_scan.erl#L960-L969

In fact Erlang parses both reasonable sequences (`\^@`, `\^?`) and confusing ones (`\^ `, `\^[`) without complaints. (Compare expression `[$\^[]` to Emacs Lisp equivalent `[?\^\[]`.)

I think documentation should be updated and/or additional checks added.

**Comment by bjorng** [comment]
While Erlang is able to parse `$\^?`, it interprets as 31, not as 127 as Emacs and other tools do. That is a bug in my opinion.

I think that is `$\^[` (without backslash preceding the opening bracket) is fine. I don't want to explain in the documentation that you can write `$\^@` but that you would need a backslash between the caret and left bracket in `$^[`.

My suggestion, which will have be approved by the OTP Technical Board, is to only allow the following characters following `$\^`: `@`, `A`-`Z`, `a`-`z`, `?`, `[`, `\`, `]`, `^`, and `_`. The value of `$\^?` will be 127 (not 31).
