### ISSUE TITLE
Source bundle's md5 and sha256 are not correct

### ISSUE THREAD

**Issue by dantran** [erlang/otp#6486]
**Describe the bug**
Provided md5 and sha2 values for download source distribution not matched

**To Reproduce**
download the src bundle and compare its checksum values

**Expected behavior**
local generated checksum value must match with the provided value

**Affected versions**
25.2.1

**Additional context**
  * The provided sha256 value for src bundle  5442dea694e7555d479d80bc81f1428020639c258f8e40b2052732d1cc95cca5
  * Found locally as 865c836345de4730bb2519389efcf2ff03b5cad5e693559afe4460a62c8499d7

**Comment by rickard-green** [comment]
Both md5 and sha256 for `otp_src_25.1.2.tar.gz` at https://github.com/erlang/otp/releases/tag/OTP-25.1.2 compare the same for me. Where have you downloaded from?

**Comment by dantran** [comment]
My bad, it was downloading the .zip file which does not have posted sum value
