### ISSUE TITLE
`-enable-feature maybe_expr` is ignored when recompiling from shell via c/1

### ISSUE THREAD

**Issue by ilya-klyuchnikov** [erlang/otp#6514]
**Describe the bug**
Modules using maybe_expr cannot be recompiled from shell.

**To Reproduce**

```erlang
-module(m).

-export([m/1]).

m(X) -> maybe X end.
```

```
erlc -enable-feature maybe_expr m.erl
```

```
erl -enable-feature maybe_expr
Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns] [dtrace]

Eshell V13.1.1  (abort with ^G)
1> m:m(1).
1
2> c(m).
m.erl:5:15: syntax error before: X
%    5| m(X) -> maybe X end.
%     |               ^

m.erl:3:2: function m/1 undefined
%    3| -export([m/1]).
%     |  ^

error

```

**Expected behavior**
I expect that `erlc` features from shell would be activated if `erl` has been launched with the features.

**Affected versions**
25.1

**Comment by bjorng** [comment]
This is not a bug.

Enabling a feature in the runtime system is not supposed to also enable in the compiler.

**Comment by michalmuskala** [comment]
Shouldn't recompiling the module with the feature enabled, keep it enabled in the compiler, though?

**Comment by bjorng** [comment]
@michalmuskala No, not if the source code is in the current working directory.  If `c/1` finds the source file, it will not look for the BEAM file at all and it will not retrieve the old compiler options. `c/3` can be used to force the BEAM file to be used (pass `fun() -> true end` as the third argument). (The reasons for the differences in behavior between `c/1` and `c/3` is backward compatibility.)
