### ISSUE TITLE
Heisen-variables (2)

### ISSUE THREAD

**Issue by ilya-klyuchnikov** [erlang/otp#6516]
(A continuation of #6141)

**Describe the bug**
Scoping of variables (and whether a variable is already bound or not) is not stable

**To Reproduce**

```erlang
-module(scopes).
-compile([export_all, nowarn_export_all]).

scope1() ->
  {
    (X = 4),
    (X = 3)
  }.

scope2() ->
  {
    X = 4,
    (_ = (X = 3))
  }.
```

```
$ erlc scopes.erl
scopes.erl:7:6: Warning: no clause will ever match
%    7|     (X = 3)
%     |      ^

scopes.erl:7:6: Warning: this clause cannot match because its guard evaluates to 'false'
%    7|     (X = 3)
%     |      ^

```

```
$ erl 
1> scopes:scope1().
** exception error: no match of right hand side value 3
     in function  scopes:scope1/0 (scopes.erl, line 7)
2> scopes:scope2().
{4,3}
```

**Expected behavior**
The same behavior for `scope1` and `scope2`. It seems that `X` is scoped differently under the hood in the 2 functions.

**Affected versions**
25.1

**Comment by bjorng** [comment]
It turns out that this bug is fixed in #6415. We don't plan to fix it in OTP 25.x.
