### ISSUE TITLE
defunct process(erl_child_setup、epmd...) in docker env

### ISSUE THREAD

**Issue by WilliamWei1989** [erlang/otp#6534]
**Describe the bug**

**in docker, there some defunct processes after erlang beam startup.**
![image](https://user-images.githubusercontent.com/10206504/205888002-a0ee5933-3cc8-40fc-b15a-d79923df931f.png)

My erlang server runs ok in "centos 7"(linux kernel 3.10.0) docker env,  today upgrade OS to "Alibaba cloud linux 2"(linux kernel 4.19.0). After server startup, there are some unexpected defunct processes.

**To Reproduce**
**OS**："Alibaba cloud linux 2"(linux kernel 4.19.0)
**Docker Version**：
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:04:24 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:02:38 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.10
  GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Erlang/OTP Version**:
Erlang/OTP 23 [erts-11.2.2.4]

after beam startup, there some defunct processes
![image](https://user-images.githubusercontent.com/10206504/205892575-4aa3d1f7-e89d-43bb-9ba5-491a55118a3d.png)

**Expected behavior**
Expect no defunct processes.
![img_v2_9f3094b8-b8d5-467e-92f4-20fe02eb49fg](https://user-images.githubusercontent.com/10206504/205890648-a0cbf1cd-1c40-459e-812b-345c53bbd628.jpg)

**Affected versions**
The OTP versions that are affected by this bug.
Erlang/OTP 23 [erts-11.2.2.4]

**Additional context**
Add any other context about the problem here. If you wish to attach Erlang code you can either write it directly in the post using [code tags](https://guides.github.com/features/mastering-markdown/), create a [gist](https://gist.github.com), or attach it as a zip file to this post.

**Comment by jhogberg** [comment]
This is a bug in your environment, not Erlang/OTP. Pid 1 (`/sbin/init`) ought to have reaped these defunct processes, but it hasn't.
