### ISSUE TITLE
Support for OpenSSL 3.0 in FIPS mode

### ISSUE THREAD

**Issue by anuthan** [erlang/otp#6566]
The text in the docs page, https://www.erlang.org/doc/man/crypto_app.html, mention "Using OpenSSL 3.0 with Engines or in FIPS mode is not yet supported by the OTP/crypto app."

Hoping to get some sense of if and when, OpenSSL 3.0 with FIPS mode will be officially supported by the OTP/crypto app. 
OpenSSL Version 1.1.1(LTS) will be supported until 2023-09-11 per https://www.openssl.org/policies/releasestrat.html. Switching to using OpenSSL 3.0 and having FIPS mode supported would be really beneficial moving forward.

**Comment by lukebakken** [comment]
This issue is related to #6406

**Comment by sverker** [comment]
Fixed by #7392.
