### ISSUE TITLE
[DNS] Add the DO (DNSSEC OK) flag to dns_rr_opt

### ISSUE THREAD

**Issue by bortzmeyer** [erlang/otp#6605]
In `lib/kernel/src/inet_dns.hrl`, `dns_rr_opt` has almost of the fields mentioned in RFC 6891, section 6.1.3, but the `DO` (DNSSEC OK) flag. It could be useful to know if we received it from the DNS client.

**Comment by bortzmeyer** [comment]
Note that the field `z` contains the `DO` flag in its first bit and therefore is not always zero.

**Comment by RaimoNiskanen** [comment]
Sorry I missed this one entirely, and figured this out the hard way.  This should, like #6606, be solved by #6786.
