### ISSUE TITLE
Defining variable in upper scope from `case`

### ISSUE THREAD

**Issue by liember** [erlang/otp#6640]
Steps to reproduce the behavior.
```
t(K) ->
    case K of
        k ->
            R = a;
        R ->
            2
    end,
    R.
```

Expected behavior
Compile error

Affected versions
25

**Comment by liember** [comment]
```
2> t:t(2).
2
3> t:t(k).
a
```

**Comment by jhogberg** [comment]
It doesn't matter how you define exported variables as long as they're defined in all clauses, and you've bound `R` in both clauses, so this is not a bug. Compare with the following:

```erlang
t(K) ->
    case K of
        {a, R} -> a;
        {b, R} -> b
    end,
    R.

%% 1> t:t({a,1}).
%% 1
%% 2> t:t({b,123}).
%% 123
```

**Comment by okeuday** [comment]
@liember You can use the compiler option `warn_export_vars` to make exported variables a warning and `warnings_as_errors` to make the warning an error.  That would help you avoid having any exported variables.
