### ISSUE TITLE
[jit] Assertion failed at beam/erl_bits.c:523:erts_bs_get_float_2()

### ISSUE THREAD

**Issue by RobinMorisset** [erlang/otp#6645]
**Describe the bug**
Running the following commands:
```bash
erlc -W0 minimized/jit2.erl
cerl -debug -noshell -pa . -s jit2 start -s init stop
```
on the following file:
```erlang
-module(jit2).
-compile([export_all]).

f1(_, _) ->
    ok.

f1(a, _V0, a) ->
    {-9223372036854775808, ok}.

f2() when ok ->
    -2147483648.

f2(true, #{ok := _, #{ok => {}, ok => #{}} := _}, _V0) ->
    (is_float(_V0)).

f3(_, _, <<>>) ->
    f3;
f3(a, {_V0, _V0, {_, _, true}, a}, _) ->
    ok;
f3(_, _, _V0) ->
    <<(f5(ok, _V0)) || <<_V1:0/integer-unit:185, _V2:_V1/float>> <= <<>>, _ <- []>>.

f4(_, _) ->
    ok.

f5(_, _) ->
    ok.

start() ->
    catch f1(0, ok),
    catch f1(ok, ok, ok),
    catch f2(),
    catch f2(2147483647, [], 0),
    f3(0, 0, true),
    f4(0, 0),
    ok.
```
results in a crash of the VM with the following error message:
```
beam/erl_bits.c:523:erts_bs_get_float_2() Assertion failed: (((((void) (((p)->htop <= (p)->stop) ? 1 : (erl_assert_error("(p)->htop <= (p)->stop", __func__, "beam/erl_bits.c", 523), 0))), ((((p)->htop)>((p)->stop - (erts_cp_size() * 3)))?((p)->htop):((p)->stop - (erts_cp_size() * 3)))) - (p)->htop) >= (((sizeof(ieee754_8)/sizeof(Eterm))+1)))
Aborted (core dumped)
```

**Affected versions**
I've tested the following, all with debug builds, and they're both affected:
- master + https://github.com/erlang/otp/pull/6637 + https://github.com/erlang/otp/pull/6642 + https://github.com/erlang/otp/pull/6644
- master

**Additional context**
The bug reproduces reliably on both a linux server and a mac laptop with the testcase provided above.
Minimizing the testcase further tends to make the bug frustratingly non-deterministic.

**Comment by jhogberg** [comment]
Thanks for your report. This was caused by us not updating the current stack pointer before calling `erts_bs_get_float2`, which is normally not required, but is needed for an assertion in debug mode. It's not a problem in release builds.

I've opened a PR (#6646) that updates it when in debug mode.

**Comment by michalmuskala** [comment]
As a followup. Documentation states that the only allowed sizes for reading a float are 16, 32, and 64. Yet here the read succeeds with size 0. Is this an issue with documentation, or with implementation?

**Comment by jhogberg** [comment]
Good catch. I'd say it's a problem with the documentation as zero-width integers are also interpreted as zero, and I can see this behavior as far back as `git blame` can see.
