### ISSUE TITLE
[erlc] Internal consistency check failed: type_conflict on is_eq_exact

### ISSUE THREAD

**Issue by RobinMorisset** [erlang/otp#6653]
**Describe the bug**
erlc crashes on
```erlang
f(X) ->
    Y =
        try
            false = X
        catch
            _ ->
                ok
        end /= ok,
    X = Y,
    false = Y,
    0 = ok.
```
with the error message:
```
is_eq_exact:1: function f/1+20:
  Internal consistency check failed - please report this bug.
  Instruction: {test,is_eq_exact,{f,7},[{x,0},{atom,true}]}
  Error:       {type_conflict,{t_atom,[false]},{t_atom,[true]}}:
```

**Affected versions**
- master
- master + https://github.com/erlang/otp/pull/6651

**Additional context**
I suspect that this might be another symptom of https://github.com/erlang/otp/issues/6599, but the error message is different so I am reporting this in a different issue in case it is a separate bug.

**Comment by jhogberg** [comment]
I can confirm it's another symptom of #6599 :-/
