### ISSUE TITLE
[vm] Null pointer dereference in erts_new_bs_put_string -> sys_memcpy

### ISSUE THREAD

**Issue by RobinMorisset** [erlang/otp#6655]
**Describe the bug**
Running the following commands:
```bash
erlc -W0 minimized/memcpy.erl
cerl -debug -noshell -pa . -s memcpy -s init stop
```
on the following file:
```erlang
-feature(maybe_expr, enable).
-module(memcpy).
-compile([export_all]).

start() ->
    <<
        (maybe
            ok
        end)/bits,
        0/float
    >>.
```
results in a crash with the message:
```
beam/sys.h:1092:sys_memcpy() Assertion failed: dest != ((void *)0) && src != ((void *)0)
Aborted (core dumped)
```

Removing the -debug option to cerl results in a segfault instead.

**Expected behavior**
A type error exception

**Affected versions**
- master
- master + #6651 + #6652

**Additional context**
Passing `-lldb` to `cerl` shows that the caller of `sys_memcpy` is `erts_new_bs_put_string`, but I could not see the rest of the stack trace.
There are lots of variants of this testcase that also cause segfaults but don't trigger the assert even in debug mode. For example:
```erlang
start() ->
    <<
        (case ok of
            _ ->
                0
        end)/bits,
        0
    >>.
```

**Comment by bjorng** [comment]
Thanks for finding this bug. The bug was introduced by my optimizations of binary construction.
