### ISSUE TITLE
unhandled EXIT on MacOS/Darwin when calling cacerts_get/cacerts_load

### ISSUE THREAD

**Issue by kaikuchn** [erlang/otp#6656]
**Describe the bug**
Calling `public_key:cacerts_get()` in a GenServer that traps exits on MacOS I need to handle an EXIT message from a Port, because `cacerts_load` calls [load_darwin()](https://github.com/erlang/otp/blob/0f4345094b9a57c4166c695b7acbb6087df7e444/lib/public_key/src/pubkey_os_cacerts.erl#L133) which opens a Port to get the system root certificates from the MacOS KeyChain.

**To Reproduce**

Start the following GenServer:
```erlang
-module(example).

-behaviour(gen_server).

-export([start_link/0]).
-export([init/1, handle_info/2, handle_call/3, handle_cast/2]).

start_link() ->
    gen_server:start_link({local, ?MODULE}, ?MODULE, [], []).

init([]) ->
    process_flag(trap_exit, true),
    {ok, public_key:cacerts_get()}.

handle_info(Info, State) ->
    erlang:display(Info),
    {noreply, State}.

handle_call(_Request, _From, State) ->
    {reply, ignored, State}.

handle_cast(_Msg, State) ->
    {noreply, State}.
```

**Expected behavior**
My GenServer does not receive an exit message.

I guess this is debatable, and maybe I just don't know enough about Erlang and its philosophy (I've actually encountered this behaviour in Elixir). But it was very surprising to me that some Port somewhere deep in the call stack sends me a message even though I didn't even know he existed :)

**Affected versions**
25.x

**Comment by dgud** [comment]
Merged fix to maint and master

**Comment by kaikuchn** [comment]
Thank you for the quick response & resolution!
