### ISSUE TITLE
ssl_manager excessive heap usage

### ISSUE THREAD

**Issue by mikpe** [erlang/otp#6690]
**Describe the bug**
We noticed today that `ssl_manager` was consuming about 1GB of memory, which is excessive. After some debugging we found that the `session_cache_client` ETS has 654 entries but the `client_session_order` gb_tree has a whopping 687706 entries. My understanding of the code is that these two storages should contain the same number of entries.

The node in question has been running less than 14 days.

**To Reproduce**
unknown

**Expected behavior**
I expected the gb_tree to be several orders of magnitude smaller, and memory usage also.

**Affected versions**
OTP-23.3.4.18.

**Additional context**
This started as a comment to https://github.com/erlang/otp/issues/6549 before I realized our issue was different (that issue is about the ETS table growing, our is about the gb_tree growing).

Debugging is awkward. Retrieving the `ssl_manager`'s state (with `sys:get_state/1`) makes the remote shell very slow, and I don't want to jeopardize the node.

**Comment by IngelaAndin** [comment]
You probably need the patch from OTP-24.1 

```
@@ -143,8 +143,8 @@ handle_call({reuse_session, SessionId}, _From,  #state{store_cb = Cb,
                 true ->
                     {reply, Session, State0};
                 false ->
-                    Order = invalidate_session(Cb, Store0, Order0, SessionId, InId),
-                    {reply, not_reusable, State0#state{session_order = Order}}
+                    {Store, Order} = invalidate_session(Cb, Store0, Order0, SessionId, InId),
+                    {reply, not_reusable, State0#state{db = Store, session_order = Order}}
             end
     end.
 
@@ -220,9 +220,9 @@ session_id(Key) ->
     Bin2 = crypto:crypto_one_time(aes_128_ecb, Key, <<Unique2:128>>, true),
     <<Bin1/binary, Bin2/binary>>.
 
-invalidate_session(Cb, Store, Order, SessionId, InternalId) ->
-    Cb:delete(Store, SessionId),
-    gb_trees:delete(InternalId, Order).
+invalidate_session(Cb, Store0, Order, SessionId, InternalId) ->
+    Store = delete(Cb, Store0, SessionId),
+    {Store, gb_trees:delete(InternalId, Order)}.
 
 init(Cb, Options) ->
     Cb:init(Options).

```

**Comment by mikpe** [comment]
That's `ssl_server_session_cache.erl` while I'm talking about the client-side stuff in `ssl_manager.erl`:
```
(node@host)1> S = sys:get_state(ssl_manager), ok.
ok
(node@host)2> ets:info(element(2, S)).
[{id,#Ref<0.1395869807.3731488771.98742>},
 {decentralized_counters,false},
 {read_concurrency,false},
 {write_concurrency,false},
 {compressed,false},
 {memory,47605},
 {owner,<0.110.0>},
 {heir,none},
 {name,client_ssl_otp_session_cache},
 {size,334},
 {node,'node@host'},
 {named_table,false},
 {type,ordered_set},
 {keypos,1},
 {protection,protected}]
(node@host)3> element(3, S).          
ssl_client_session_cache_db
(node@host)4> element(4, S).
86400
(node@host)5> element(7, S).
1000
(node@host)6> element(9, S).
[]
(node@host)7> gb_trees:size(element(10, S)).
705833
(node@host)8>
```

**Comment by IngelaAndin** [comment]
Oh, my bad I for some reason thought you were talking about the server. And come to think of it probably that bug would crash the server session cache process so you would not get a very large tree... I will look into it!

**Comment by IngelaAndin** [comment]
I do not see any obvious changes to ssl_manager that would fix such a problem in a later release than yours. Do you have an easy way to reproduce it?  We will, of course, look into reproducing it ourselves but we also have a lot of other things to prioritize for the upcoming 26-release candidate so any help in reproducing it will be appreciated.

**Comment by mikpe** [comment]
No easy way to reproduce, it was just found by accident. Also we're just about to upgrade this cluster from OTP-23 to OTP-24, but we'll monitor `ssl_manager` to see if the issue occurs on OTP-24 too.

**Comment by IngelaAndin** [comment]
Ok, thanks, we will keep this open and you or I can report any findings once we manage to find some.

**Comment by mikpe** [comment]
After several weeks on OTP-24.3.4.8 I cannot reproduce this issue. The gb_tree and the ets are in perfect sync, size-wise.

Feel free to close this one.
