### ISSUE TITLE
bitstring-unit:X - discrepancy between documentation and implementation

### ISSUE THREAD

**Issue by ilya-klyuchnikov** [erlang/otp#6706]
**Describe the bug**

According to https://www.erlang.org/doc/reference_manual/expressions.html#bit-syntax-expressions

> Unit= unit:IntegerLiteral
> The allowed range is 1..256. Defaults to 1 for integer, float, and bitstring, and to 8 for binary. No unit specifier must be given for the types utf8, utf16, and utf32.

However, for `bitstring-unit:X` compiler rejects anything but `1`.

**To Reproduce**

```erlang
-module(bitsting_unit).
-compile([export_all, nowarn_export_all]).

make(B) -> <<B:42/bitstring>>.
make_unit(B) -> <<B:42/bitstring-unit:3>>.

match(<<B:42/bitstring>>) -> B.
match_unit(<<B:42/bitstring-unit:3>>) -> B.
```

```
erlc bitstring.erl
bitsting_unit.erl:5:19: conflict in unit specification for bit field: '3' and '1'
%    5| make_unit(B) -> <<B:42/bitstring-unit:3>>.
%     |                   ^

bitsting_unit.erl:8:14: conflict in unit specification for bit field: '3' and '1'
%    8| match_unit(<<B:42/bitstring-unit:3>>) -> B.
%     |              ^

```

**Expected behavior**
No discrepancy between the documentation and the actual behavior.

**Affected versions**
23, 24, 25

**Comment by bjorng** [comment]
The linked pull request fixes this issue, as well as documenting the previously undocumented behavior of units for binary segments.
