### ISSUE TITLE
Ports being initialized through Vanilla Drivers could lead to BEAM failures.

### ISSUE THREAD

**Issue by WLSF** [erlang/otp#6725]
**Describe the bug**
Erlang/OTP still supports [Ports creation by using Vanilla Drivers](https://erlangforums.com/t/ports-communication-through-ipc-safe-to-use-or-likely-to-be-deprecated/2227/2) that are called when you use the first argument as an Atom/String.

This method was deprecated since the early 2000's and got all the documentation removed around 2006, as you can see in the picture below.

<img width="1283" alt="Screen Shot 2023-01-23 at 16 46 00" src="https://user-images.githubusercontent.com/5873073/214134918-534a50e8-4d65-4580-9b91-05168ad043c6.png">

The main problem with this approach is that Vanilla Drivers only do a syscall to open file, doing so can lead to BEAM failures, since it doesn't have any treatment for special files

**To Reproduce**
You can access any file through `open_port/2` by passing a String as first argument.

```
open_port("/dev/urandom", [eof]).
```

**Expected behavior**
Ports usage should only be accepted with tuple arguments like `{spawn, "cat file.txt"}`

Vanilla Drivers shouldn't exist for this case, resulting in a badarg.
```
> open_port("something", [eof]).
badarg error
```

**Affected versions**
It happen on all versions.

This is something I would like to tackle in case you agree that this behavior shouldn't exist any longer. Ideas on that?

**Comment by WLSF** [comment]
I can work on a PR for that, since I've been studying this the past few weeks.

Let me know if thats ok...

**Comment by rickard-green** [comment]
@WLSF I've added a warning in the documentation that this will be removed in OTP 27. This since it has been documented even though it was a long time ago. If you still is interested in making a PR please do. We cannot merge it until OTP 26 has been released (mid/late may) though.

**Comment by WLSF** [comment]
Sure I'll be creating a PR soon.
