### ISSUE TITLE
gb_tree not finding existing key-value pair

### ISSUE THREAD

**Issue by yenrabbyui** [erlang/otp#6764]
**Describe the bug**
On multiple operating systems, I have created a gb_tree from a small, 6 element, orddict. When I then use gb_trees:get/2 to retrieve the value for certain keys on the "right-hand-side" of the tree, I get "exception error: no function clause matching gb_trees:get_1(7,nil) (gb_trees.erl, line 244)." This is not true for any element on the "left-hand-side" of the three. The issue goes away if the tree is built by removing the element with the key of 7.

**To Reproduce**
>GT = gb_trees:from_orddict([{1,-1},{2,-1},{3,-1},{6,-1},{7,-1},{5,-1}]).
{6,
 {6,-1,
  {2,-1,{1,-1,nil,nil},{3,-1,nil,nil}},
  {5,-1,{7,-1,nil,nil},nil}}}
>gb_trees:get(7,GT). %%this causes failure
>gb_trees:get(5,GT).%%this causes failure
>gb_trees:get(3,GT).
-1
>gb_trees:get(2,GT).
-1
>gb_trees:get(1,GT).
-1
**Expected behavior**
When the keys 5 or 7 are used in gb_trees:get/2, the value of the function should be -1.

**Affected versions**
OTP Version: 25 (homebrew distribution)
MacOS: "x86_64-apple-darwin22.1.0", Ventura 13.1 (22C65)
CPU: 3 GHz 6-Core Intel Core i5

OTP Version: 24 (ubuntu apt distribution)
Ubuntu: "x86_64-pc-linux-gnu", Ubuntu 22.04.1 LTS
CPU: Digital Ocean virtual, shared CPU
**Additional context**
None

**Comment by RoadRunnr** [comment]
Your input to `gb_trees:from_orddict/1` is not an orddict.

This is is not ordered: `([{1,-1},{2,-1},{3,-1},{6,-1},{7,-1},{5,-1}])`, it should be `[{1,-1},{2,-1},{3,-1},{5,-1},{6,-1},{7,-1}]`.

The sample works when you use
```GT = gb_trees:from_orddict(orddict:from_list([{1,-1},{2,-1},{3,-1},{6,-1},{7,-1},{5,-1}])).```
instead.
