### ISSUE TITLE
TLS 1.3 Hello Retry Requests Timeout in Some Cases

### ISSUE THREAD

**Issue by andrewcln** [erlang/otp#6807]
**Describe the bug**

When connecting to a number of TLS 1.3 servers on the internet that present a `Hello Retry Request`, the Erlang `ssl:connect` call may cause the TLS FSM to stop processing any more messages. This may be because the incorrect action is taken when processing the retry request when _middlebox compatibility mode_ is true. The result is a timeout or close after a period of time.

**To Reproduce**
```
ssl:start().
ssl:connect({194,176,218,21}, 8443,[
	  {versions, ['tlsv1.3']},
	  {verify, verify_none},
	  {server_name_indication, "cas.librariesni.org.uk"}
]).
```

**Expected behavior**
An `{ok, #sslsocket}` should be returned promptly after the connect.

**Affected versions**
24.3.4.3 and all versions after. Still present in 25.2

**Additional context**
The bug appears to be have been introduced by commit [936a3461](https://github.com/erlang/otp/commit/936a34615c24ca417eb78c20e0f3b8cbe71f5563) in OTP version 24.3.4.3. The bug is not in 24.3.4.2. The following patch to `tls_connection_1_3.erl` does fix the problem:

```
@@ -484,7 +484,7 @@ hello_retry_middlebox_assert(enter, _, State) ->
 hello_retry_middlebox_assert(internal, #change_cipher_spec{}, State) ->
     tls_gen_connection:next_event(start, no_record, State);
 hello_retry_middlebox_assert(internal, #server_hello{}, State) ->
-    tls_gen_connection:next_event(?FUNCTION_NAME, no_record, State, [postpone]);
+    tls_gen_connection:next_event(start, no_record, State, [postpone]);
 hello_retry_middlebox_assert(info, Msg, State) ->
     tls_gen_connection:handle_info(Msg, ?FUNCTION_NAME, State);
 hello_retry_middlebox_assert(Type, Msg, State) ->
```

I'm unconvinced the above is the correct fix, so I'm hoping someone can let me know if it's safe or not.

Thanks

**Comment by IngelaAndin** [comment]
Actually I think it is the server that is not honoring the `middlebox_comp_mode`. The change
you made makes the assertion of the change_cipher_spec for the server after its first handshake message not effective. As a work around you could disable the middlebox_comp_mode.

From  RFC 8446

```
[D.4]  Middlebox Compatibility Mode

   Field measurements  have found
   that a significant number of middleboxes misbehave when a TLS
   client/server pair negotiates TLS 1.3.  Implementations can increase
   the chance of making connections through those middleboxes by making
   the TLS 1.3 handshake look more like a TLS 1.2 handshake:

   -  The client always provides a non-empty session ID in the
      ClientHello, as described in the legacy_session_id section of
      [Section 4.1.2]

   -  If not offering early data, the client sends a dummy
      change_cipher_spec record (see the third paragraph of
      immediately before its second flight.  This may either be before
      its second ClientHello or before its encrypted handshake flight.
      If offering early data, the record is placed immediately after the
      first ClientHello.

   -  The server sends a dummy change_cipher_spec record immediately
      after its first handshake message.  This may either be after a
      ServerHello or a HelloRetryRequest.

   When put together, these changes make the TLS 1.3 handshake resemble
   TLS 1.2 session resumption, which improves the chance of successfully
   connecting through middleboxes.  This "compatibility mode" is
   partially negotiated: the client can opt to provide a session ID or
   not, and the server has to echo it.  Either side can send
   change_cipher_spec at any time during the handshake, as they must be
   ignored by the peer, but if the client sends a non-empty session ID,
   the server MUST send the change_cipher_spec as described in this
   appendix.

```

**Comment by andrewcln** [comment]
Thanks for the response Ingela. I don't own the server and I've noticed this is not an issue with any of the browsers I've tried. So this will be an issue for anyone using Erlang to make outbound connections to servers configured this way.

Can I assume by what you are saying that the Erlang code is just a **much more strict implementation** of the Hello Retry Request than, for example, Chrome browser, or Firefox? I presume there are thousands many more servers worldwide that behave this way on the public internet that only post-24.3.4.2 Erlang versions can't connect to but that every other TLS implementation I've tried can (cURL, Chrome, Firefox).

**Comment by IngelaAndin** [comment]
Do you know if they run middle_box mode or not? If you turn off middle_box mode it will work. But maybe we could make a middle_box_relaxed mode if it is a problem. It is sort of a useless message but in the same time we want follow the spec. Being pragmatic even when it seems to be no problem can turn out to being so later, just saying you never know!

**Comment by andrewcln** [comment]
Thanks Ingela. Yes, I completely agree, and I'm hesitant about the change I suggested.

Regarding if the server is running with middle_box mode, unfortunately I have absolutely no idea. We encountered that website randomly. To give you some context, we use Erlang for testing TLS connections to the general internet with real-time, real user web browsing (think TLS proxy). That gives us a huge and random array of TLS web servers, along with all the unusual server configurations and poor implementations of the various TLS protocols. Occasionally there will be sites that fail, but they often also fail with `openssl s_client` or have some issue flagged up by https://www.ssllabs.com/ssltest/.

That's not the case here though, with this failure looking like its unique to the Erlang TLS 1.3 client implementation, compared with others. In that case, we usually find that a TLS change has been made upstream in a later release that resolves the issue.

I might undo the change I made in our lab, and see if other websites are flagged up. When this particular one was reported, I made the change mentioned quickly to resolve it. Unfortunately, given the presence of just this single failing website, it makes me concerned enough that one of our customers could have a similarly configured server and I'd be keen that our software be able to work with it out-of-the-box.

I'd therefore be keen to see a 'middle_box_relaxed' mode :)

**Comment by IngelaAndin** [comment]
I have had some time to look more into this and I actually see the server sending a change_cipher_spec in middlebox_comp_mode, so I will continue to investigate if it is sent in the correct time or not. As it is a little special, timing issues might interfere with the perception of the correct point in time.

**Comment by andrewcln** [comment]
Thanks for the update @IngelaAndin. FYI the `Server` header from the HTTP request reports the server as `Apereo CAS` (website here: https://www.apereo.org/projects/cas). Not something I've come across before, so not really common on the web but I imagine it's probably more prevalent in enterprise networks.

**Comment by IngelaAndin** [comment]
@andrewcln so it seems like your server waits for the client flight of messages before sending the change_cipher_spec that comes after the hello_retry_request. This change will move the assert to after handling the hello_retry_request and will interop with your server. I will do the semantically same change for earlier OTP versions but due to some refactors we been doing to master the change will require different commits.

**Comment by andrewcln** [comment]
Great, many thanks Ingela. I have been monitoring the web traffic over the last few days and have noticed that all the other destination servers hitting that code (for example, `openssl s_client -connect 40.99.205.98:443 -servername substrate.office.com`) _do_ send the `CHANGE CIPHER SPEC` in the same TCP payload as the the `HELLO RETRY REQUEST`. The server I've seen this problem must have a different TLS server implementation than most.

**Comment by IngelaAndin** [comment]
Yes seems so, our implementation also behaves as OpenSSL that is the implementation that we interop test with. This I think makes more sense. In the same time I do not think that  it changes the semantics of the final outcome making the assertion afterwards, that is it will still make the client timeout for a server not sending the middlebox message after the hello_retry_request message.
