### ISSUE TITLE
Does the --plts Dialyzer option work correctly?

### ISSUE THREAD

**Issue by Olivier-Boudeville** [erlang/otp#6850]
Hi,

(using Erlang/OTP 25 [erts-13.1.3])

Maybe there is a bug in the management of the Dialyzer command-line --plts option (or the doc is maybe unclear), as a call like:

`dialyzer --add_to_plt --output_plt X.plt -r ./src ./test --plts Y.plt` is accepted, whereas `dialyzer --add_to_plt --output_plt X.plt -r ./src ./test --plts Y.plt Z.plt` will fail (for all Z) with:

`{"init terminating in do_boot",{function_clause,[{dialyzer_cl,plt_common,[{options,[],["./src","./test"],plt_add,false,[],byte_code,false,["Y.plt","Z.plt"],[],"X.plt",[warn_behaviour,warn_bin_construction,[...]`

The man page has the following example: `dialyzer files_to_analyze --plts plt_1 ... plt_n`.

Thanks for any feedback,

Olivier.

**Comment by TD5** [comment]
I can reproduce the same. I'll see if I can find the root cause.
