### ISSUE TITLE
Possible typo in OTP-18337 release note

### ISSUE THREAD

**Issue by mikpe** [erlang/otp#6863]
**Describe the bug**
The OTP-26.0-rc1 release notes, https://erlang.org/download/otp_src_26.0-rc1.readme, states under OTP-18337 that `The value for $\? is now 127 (instead of 31 as in earlier releases)`.

I suspect a caret (^) has been lost there, and you meant `$\^?`.

**To Reproduce**
Visit the page

**Expected behavior**
I expected the release note to be correct.

**Affected versions**
OTP-26.0-rc1

**Additional context**
n/a

**Comment by bjorng** [comment]
Thanks! Yes, a caret was lost. Corrected in the ticket. The release note will be correct in the next release candidate.
