### ISSUE TITLE
Let public_key.cacerts_load loads user-trusted certificates on macOS

### ISSUE THREAD

**Issue by pvthuyen** [erlang/otp#6871]
As the moment, `cacerts_load` only load certificates from the OS location, i.e. `/System/Library/Keychains/SystemRootCertificates.keychain`. This lefts out the user-trusted certificates in `/Library/Keychains/System.keychain`

**Describe the solution you'd like**
Load certificates from `/Library/Keychains/System.keychain` in `cacerts_load` too.

**Comment by dgud** [comment]
We don't read the files directly on macOS, see https://github.com/erlang/otp/blob/master/lib/public_key/src/pubkey_os_cacerts.erl#L133
you could do the same and write the results to a temporary file and load for now.

**Comment by dgud** [comment]
I'm closing this for now.

**Comment by randysecrist** [comment]
bump on this -> on the mac the system keychain is where most corps dump their certs

**Comment by dgud** [comment]
See #8844
