### ISSUE TITLE
Mutable variables - let 1 become 0

### ISSUE THREAD

**Issue by michalmuskala** [erlang/otp#6873]
**Describe the bug**
In some specific cases pattern matching doesn't do what it's supposed to - instead it mutates variables.

**To Reproduce**
Given the following snippet:
```erlang
-module(test).

-export([test/0]).

test() ->
    Zero = 0,
    One = 1,

    Result = One = Zero,

    io:format("~p ~p~n", [Zero, One]),
    Result.
```
Compiling the `test` module and running `test:test()` from the shell produces:
```erlang
1> test:test().
0 0
0
```

**Expected behavior**
The code should crash with match error, and variables should remain immutable.

**Affected versions**
Tested with the latest `maint-25` and `maint-24` branches. This correctly fails on current master, even emitting a warning during compilation with `erlc`.

**Additional context**
Originally discovered by @jcpetruzza

**Comment by michalmuskala** [comment]
This also incorrectly succeeds and rebinds a variable with other expressions in the match tail, not just plain variables, e.g.

```
test2() ->
    Zero = 0,

    Result = Zero = self(),
    io:format("~p~n", [Zero]),
    Result.
```

**Comment by bjorng** [comment]
It is also incorrect in OTP 23 and probably in many earlier releases.

It seems that the bug was inadvertently corrected in #6415. My current plan is to backport part of that PR to OTP 23 through 25 in order to fix this bug.

**Comment by hissssst** [comment]
There is the same behavior for arguments in `fun`, but I don't know whether it is a bug or not

**Comment by michalmuskala** [comment]
`fun` arguments allow shadowing, if you mean code similar to the example below, it's working as documented.
```erl
test3() ->
    Zero = 0,
    One = 1,

    F = fun(One) -> io:format("~p~n", [One]) end,
    F(Zero).
```

The compiler also issues a warning about this:
```
test.erl:23:13: Warning: variable 'One' shadowed in 'fun'
%   23|     F = fun(One) -> io:format("~p~n", [One]) end,
%     |             ^
```

**Comment by michalmuskala** [comment]
Thanks for fixing this quickly!
