### ISSUE TITLE
Add gcd to :math module

### ISSUE THREAD

**Issue by somoza** [erlang/otp#6912]
I want to add the gcd function to :math module as a contribution. gcd/2 is acronymous of "greater common divisor".

https://www.w3schools.com/python/ref_math_gcd.asp

Would you like me to add this function, or do you see this as useless?

On Elixir we depend on this module for math stuff so this addition would be an elixir improvement.

**Comment by josevalim** [comment]
FWIW, Elixir already has [Integer.gcd/2](https://hexdocs.pm/elixir/Integer.html#gcd/2). I am not sure if it belongs to the `math` module. I consider the `math` module to be more about floating point operations, but of course it is not my decision to make. :)

**Comment by somoza** [comment]
Jose, after creating this issue I thought that the best way was to create an "overlay" Math module on elixir extending the "basic" :math from Erlang, and adding over more mhhh "high level?" functions like this. Then on the list, I get noticed that you, with the brilliance that characterizes you, already thought on this and added extra functions to Integer module. So I'm closing this issue which has no sense... Thank you!
