### ISSUE TITLE
Unable to eval using -s init stop in OTP 26

### ISSUE THREAD

**Issue by starbelly** [erlang/otp#6916]
**Describe the bug**
Up until erlang otp 26 using -s init stop with an -eval switch would allow one to grab some info about erts, this was useful in that one could use this method such in Makefiles, shell scripts, etc. 

This now fails with a failed to eval error message. There is a work around for this, which is simply to call `init:stop/0` as part of the eval.  This in fact may not be a bug and is intentional, but I didn't see it listed anywhere in release notes. 

**To Reproduce**

```shell
$ erl -noshell -eval "io:format(\"~s\/erts-~s/include/\", [code:root_dir(), erlang:system_info(version)])."
Error! Failed to eval: io:format("~s/erts-~s/include", [code:root_dir(), erlang:system_info(version)]).
```

**Expected behavior**

```shell
$ erl -noshell -s init stop -eval "io:format(\"~s\/erts-~s/include/\", [code:root_dir(), erlang:system_info(version)])."
/path/to/erlang/26.0-rc1/erts-14.0/include/
```

Note that the output will of course differ from platform to platform and depending how exactly you installed erlang/otp. 

Work around : 

```shell
$ erl -noshell -eval "io:format(\"~s\/erts-~s/include/\", [code:root_dir(), erlang:system_info(version)]), init:stop()."
/path/to/erlang/26.0-rc1/erts-14.0/include/
```

**Affected versions**
The OTP versions that are affected by this bug.

OTP-26.0-rc1 

**Additional context**
No additional context.

**Comment by josevalim** [comment]
Keep in mind the original code is fault. `init:stop` is a non-blocking operation to shut down the system, so your previous code had a race condition in that the second `-s` may or may not be executed at all. Try this out:

```
$ erl -noshell -s init stop -eval "receive after 0 -> ok end, erlang:display(oops)."
oops
```

But if you increase the timeout:

```
$ erl -noshell -s init stop -eval "receive after 1000 -> ok end, erlang:display(oops)."
```

So you should move the `-s init stop` to the end. But I would recommend using `-s erlang halt` for quicker shutdowns anyway.

**Comment by josevalim** [comment]
I have debugged the root cause of the error:

```
{error,terminated,[{io,format,["~s/erts-~s/include/",["/Users/jose/OSS/otp","13.1.4"]],[{file,"io.erl"},{line,94},{error_info,#{cause=>{io,terminated},module=>erl_stdlib_errors}}]},{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,744}]},{init,start_it,2,[]},{init,start_em,2,[]},{init,do_boot,3,[]}]}
```

The io device has since them been terminate (due to `init:stop/0`).

**Comment by starbelly** [comment]
Per @josevalim  I'm going to close this. Thanks!

**Comment by starbelly** [comment]
Re-opened this per other reports of this issue and someone on Erlang/OTP team saying this is indeed a bug.

**Comment by frazze-jobb** [comment]
According to [documentation](https://www.erlang.org/doc/man/init.html):

> 
> -eval Expr
> Scans, parses, and evaluates an arbitrary expression Expr during system initialization. If any of these steps fail (syntax error, parse error, or exception during evaluation), Erlang stops with an error message. In the following example Erlang is used as a hexadecimal calculator:
> ```
> % erl -noshell -eval 'R = 16#1F+16#A0, io:format("~.16B~n", [R])' -s erlang halt
> BF
> ```
> If multiple -eval expressions are specified, they are evaluated sequentially in the order specified. **-eval expressions are evaluated sequentially with -s and -run function calls (this also in the order specified)**. As with -s and -run, an evaluation that does not terminate blocks the system initialization process.
>
