### ISSUE TITLE
Binary comprehension and append produces invalid binaries

### ISSUE THREAD

**Issue by nickva** [erlang/otp#6925]
**Describe the bug**

This test snippet on current master or OTP 26.rc1 produces identical B1 and B2 binaries:

```erlang
-module(binfail).

-export([testfun/0]).

testfun() ->
    io:format("OTP: ~p~n", [erlang:system_info(otp_release)]),
    B1 = << <<"x">> || true >>,
    B2 = <<B1/binary, "z">>,
    io:format("  B1: ~p~n", [B1]),
    io:format("  B2: ~p~n", [B2]),
    io:format("  B1 == B2: ~p~n", [B1 == B2]).

```

**To Reproduce**

```
1> binfail:testfun().
OTP: "26"
  B1: <<"xz">>
  B2: <<"xz">>
  B1 == B2: true
ok
```

This seems to be a compiler issue, as compiling the code on OTP 25 and running on OTP 26 works fine.

**Expected behavior**

B1 and B2 binaries should be different as they are on OTP =< 25

```
1> binfail:testfun().
OTP: "25"
  B1: <<"x">>
  B2: <<"xz">>
  B1 == B2: false
ok
```

**Affected versions**

OTP 26.RC1 and master

**Additional context**

Discovered in CouchDB's EUnit collation suite https://github.com/apache/couchdb/blob/ac600d1bb9c9b5335abecc954abf9dd496a2f846/src/couch/test/eunit/couch_ejson_compare_tests.erl#L226-L230

Thanks to @jaydoane for compiling and running CouchDB on Erlang 26.rc1 and noticing the failure.

**Comment by bjorng** [comment]
@frej, Please take a look.

**Comment by nickva** [comment]
Thank you, @bjorng and @frej, for taking a look and a quick fix.
