### ISSUE TITLE
erl_scan:string/1 returns unexpected tokens scanning escaped strings

### ISSUE THREAD

**Issue by williamthome** [erlang/otp#6928]
**Describe the bug**
`erl_scan:string/1` returns tuples of strings and atoms scanning escaped strings.

**To Reproduce**
Copy and paste `erl_scan:string("<<\"foo \"bar\" baz\">>")` in the shell.
This prints:
```console
{ok,[{'<<',1},
     {string,1,"foo "},
     {atom,1,bar},
     {string,1," baz"},
     {'>>',1}],
    1}
```

**Expected behavior**
The expected is a string tuple:
```console
{ok,[{'<<',1},
     {string,1,"foo \"bar\" baz"},
     {'>>',1}],
    1}
```

**Affected versions**
Erlang/OTP 25 (maybe all others)

**Additional context**
Without quotes it returns the expected result:
```console
1> erl_scan:string("<<\"foo bar baz\">>").
{ok,[{'<<',1},{string,1,"foo bar baz"},{'>>',1}],1}
```
Also other values inside quotes produce a strange behavior by including some extra empty lists:
```console
1> erl_scan:string("<<\"foo \"0.0!\"\"bar\"\"=1.0\" baz\">>").
{ok,[{'<<',1},
     {string,1,"foo "},
     {float,1,0.0},
     {'!',1},
     {string,1,[]},
     {atom,1,bar},
     {string,1,[]},
     {'=',1},
     {float,1,1.0},
     {string,1," baz"},
     {'>>',1}],
    1}
```

**Comment by jhogberg** [comment]
This is not a bug, `"<<\"foo \"bar\" baz\">>"` is `<<"foo "bar" baz">>` after escaping.

**Comment by williamthome** [comment]
Oh, my apologies! I was trying to scan a piece o code that is not Erlang.
I'm really sorry for that. I don't know how I missed that.
Thanks anyway, @jhogberg!

**Comment by jhogberg** [comment]
No problem, thanks for taking the time to make a report. :-)
