### ISSUE TITLE
Dialyzer regression in treatment of unused type variables

### ISSUE THREAD

**Issue by cognivore** [erlang/otp#6935]
**Describe the bug**
Before, if there was a type `phantom_t`, used as an output type of some function:

```elixir
@type concrete_type :: {integer(), integer()}
@opaque phantom_t(_t0) :: concrete_type()

@spec mk_float(concrete_type()) :: phantom_t(float())
def mk_float(x), do: x

# ... in another module ...

@spec thisIsABug() :: PhantomTuple.phantom_t(integer())
def thisIsABug(), do: PhantomTuple.mk_float({1, 5})
```

then, `thisIsABug()` would raise a dialyzer error.

Currently, however, it is not the case.

**To Reproduce**
1. Clone [this repository](https://github.com/cognivore/type_nest)
2. Enable Erlang R24 and some version of Elixir compiled with it. If you use `nix`, you can just [checkout branch `r24`](https://github.com/cognivore/type_nest/tree/r24) and write `direnv allow`.
3. Run `./test.sh`. It will make sure that `dialyzer` has produced four errors.
4. Enable Erlang R25 and some version of Elixir compiled with it. If you use `nix`, you can just [checkout branch `main`](https://github.com/cognivore/type_nest/tree/main) and write `direnv allow`.
5. Run `./test.sh`. It will demonstrate that now `dialyzer` has only produced three errors.

**Expected behavior**
On step `5`, `dialyzer` still produces four errors.

**Affected versions**
`Erlang/OTP 25 [erts-13.1.5]`

**Unaffected versions**
`Erlang/OTP 24 [erts-12.0.3]` and older.

**Comment by cognivore** [comment]
@jhogberg thanks for the link! Sorry for not figuring out that it's a known issue. 

But hey, [scream tests](https://www.v-wiki.net/the-scream-test/) are also good :)

I presume that the "type variable has to be used at least twice to not be treated as `term()`" is a new warning about this exactly?

**Comment by jhogberg** [comment]
> @jhogberg thanks for the link! Sorry for not figuring out that it's a known issue.

Don't sweat it, it's a pretty dark corner of `dialyzer`.

> I presume that the "type variable has to be used at least twice to not be treated as `term()`" is a new warning about this exactly?

No, where'd you get that warning from? :sweat_smile:

**Comment by jhogberg** [comment]
That's not a warning `dialyzer` would produce, and the equivalent in Erlang (`-opaque foo(T) :: concrete_type().`) won't even compile because the variable is unused.

**Comment by cognivore** [comment]
Ah, good.
I like Erlang's treatment of this.

**Comment by cognivore** [comment]
🥳
