### ISSUE TITLE
"illegal character" on valid (?) unicode character

### ISSUE THREAD

**Issue by RobinMorisset** [erlang/otp#6952]
**Describe the bug**
On the following code:
```
f() -> "￿".
```
`erlc` fails with the following messages
```
/home/rmorisset/minimized/string.erl:12:9: illegal character
%   12| f() -> "\x{FFFF}".
%     |         ^

/home/rmorisset/minimized/string.erl:12:10: unterminated string starting with ".\n"
%   12| f() -> "\x{FFFF}".
%     |          ^
```

At first I thought that this string is invalid unicode, but checking it with `iconv` as per https://stackoverflow.com/a/115262 reveals no issue with it.

A further search led to https://stackoverflow.com/a/27416004 that states that U+0FFFF is a "non-character". However, it also links to http://www.unicode.org/versions/corrigendum9.html which states:
"The formal wording of the definition of noncharacter in the standard has led some implementers to interpret any presence of a noncharacter code point in a Unicode string as causing that string to be ill-formed, and thereby has led to inappropriate over-rejection of some Unicode strings"

At this point I am rather lost and unsure whether this is a bug in `erlc` or just a unicode string that is not supposed to be accepted by `erlc`. Feel free to close this issue if this is considered working as intended.

**Affected versions**
master

**Comment by jtdowney** [comment]
I'd like to revisit this. The implemented behavior looks narrower than the rationale it was closed on.

What's rejected isn't noncharacters, it's two specific code points. `erl_scan` accepts 64 of the 66 noncharacters in literal strings:

```erlang
-module(noncharok).
-export([f/0]).
f() -> {"\x{FDD0}", "\x{1FFFE}"}.   %% compiles fine
```

Only `U+FFFE` and `U+FFFF` are refused. That falls out of `?UNICODE` in `lib/stdlib/src/erl_scan.erl`:

```erlang
-define(UNICODE(C),
        (is_integer(C) andalso
         (C >= 0 andalso C < 16#D800 orelse
          C > 16#DFFF andalso C < 16#FFFE orelse   %% <- the gap
          C > 16#FFFF andalso C =< 16#10FFFF))).
```

The surrogate exclusion is clearly right. The gap between `C < 16#FFFE` and `C > 16#FFFF` is what rejects these two, and it doesn't line up with any category: `U+FDD0`-`U+FDEF` and `U+nFFFE`/`U+nFFFF` for n >= 1 all pass. Only `U+FFFE` and `U+FFFF`, the plane 0 pair, are refused.

It also isn't limited to literal strings. A noncharacter in a comment stops the module compiling:

```erlang
-module(noncharcomment).
-export([f/0]).
% a noncharacter in a comment: ￾
f() -> ok.
```

```
noncharcomment.erl:3:1: illegal character
```

So the question I'd put back is which of these was intended. If noncharacters are meant to stay out of source, the other 64 are a gap. If not, the exclusion looks like a leftover byte order mark check.

It came up while fuzzing the Gleam compiler, which targets Erlang and JavaScript. `io.println("\u{FFFE}")` compiles and runs on the JavaScript target and fails to compile on the Erlang one.
