### ISSUE TITLE
[erlc] "internal consistency check failed" with some optimizations disabled

### ISSUE THREAD

**Issue by RobinMorisset** [erlang/otp#6962]
**Describe the bug**
Running `erlc` with `+no_copt +no_bool_opt +no_ssa_opt` on the following code:
```erlang
f() ->
    [0 || (X = (true or (X = is_port(node()))))].
```
results in the following error:
```
type_conflict:1: function f/0+10:
  Internal consistency check failed - please report this bug.
  Instruction: {select_val,{x,1},
                           {f,7},
                           {list,[{atom,false},{f,8},{atom,true},{f,9}]}}
  Error:       {type_conflict,{t_atom,[false]},{t_atom,[false]}}:
```

I have not managed to reproduce this bug with default options for `erlc`, but I am reporting it anyway in case it is revealing a more serious problem.

**Expected behavior**
From the name of the options, I expected them to only affect optimizations, and not transformations that are required for correctness.

**Affected versions**
- master
- master + #6619 (checked to make sure that this is not yet another duplicate of #6599)

**Comment by jhogberg** [comment]
Thanks for your report, the type inference in the validator was a bit weaker than it should have been. I've fixed it in https://github.com/erlang/otp/pull/6964
