### ISSUE TITLE
Internal consistency check failed on OTP 25

### ISSUE THREAD

**Issue by xxdavid** [erlang/otp#6969]
**Describe the bug**
The following code

```erlang
-module(reproducer).

-export([exported/0]).

exported() -> hello(<<"string">>, some:remote_function(42)).

hello(A, B) -> mike([{the_same_atom, {A, B}}, {another_atom, B}]).

mike([Head | _Rest]) -> joe(Head).

joe({Name, 42}) -> Name;
joe({the_same_atom, {A, _B}}) -> {41, 42, A}.
```

fails to compile on OTP 25:
```
$ erlc src/reproducer.erl
reproducer:1: function joe/1+14:
  Internal consistency check failed - please report this bug.
  Instruction: {get_tuple_element,{x,1},0,{x,0}}
  Error:       {bad_type,{needed,{t_tuple,1,false,#{}}},{actual,any}}:
```

**To Reproduce**
Try to compile the code above.

**Expected behavior**
I would expect it to compile.

**Affected versions**
It fails to compile on OTP 25.0 and 25.2.3. It does compile on 24.3.4.9 though.

**Comment by jhogberg** [comment]
Thanks for your report! I've fixed it in https://github.com/erlang/otp/pull/6970

**Comment by xxdavid** [comment]
Wow, that was quick! Thank you for fixing it. 🙂 Do you plan to release a new version of OTP 25 anytime soon?

**Comment by jhogberg** [comment]
We're releasing `OTP 25.3` next week, but I'm not sure I'll be able to get it in before then. If I don't it'll be out in the next patch soon after that. :-)

**Comment by xxdavid** [comment]
Okay, thank you for the info. 🙂
