### ISSUE TITLE
debian repos - size mismatches

### ISSUE THREAD

**Issue by rsommer** [erlang/otp#6989]
While mirroring erlang releases from https://packages.erlang-solutions.com we are encountering size mismatch errors at least in stretch and buster repos:

`buster: https://packages.erlang-solutions.com/debian/pool/esl-erlang_25.2.3-1~debian~buster_amd64.deb: size check mismatch 40679732 != 40676556`
`stretch: https://packages.erlang-solutions.com/debian/pool/esl-erlang_25.2.3-1~debian~stretch_amd64.deb: size check mismatch 40343740 != 40345880`

### Example for debian stretch

Excerpt from Packages-file:
```
Filename: pool/esl-erlang_25.2.3-1~debian~stretch_amd64.deb
Size: 40345880
MD5sum: 6f3b174928d4ce718e2290a092e34a72
```
Actual downloaded size: 
```
$ ls -l esl-erlang_25.2.3-1~debian~stretch_amd64.deb 
-rw-rw-r-- 1 nobody nogroup 40343740 Feb 24 10:32 esl-erlang_25.2.3-1~debian~stretch_amd64.deb
```
Actual MD5:
```
$ md5sum esl-erlang_25.2.3-1~debian~stretch_amd64.deb 
0bf3973aa825b45133e7054d735918d6  esl-erlang_25.2.3-1~debian~stretch_amd64.deb
```

### Example for debian buster

Excerpt from Packages-file:
```
Filename: pool/esl-erlang_25.2.3-1~debian~buster_amd64.deb
Size: 40676556
MD5sum: 6b2bebd35eb5e1f9f2b745432546570e
```

Actual downloaded size:
```
$ ls -l esl-erlang_25.2.3-1~debian~buster_amd64.deb
-rw-rw-r-- 1 nobody nogroup 40679732 Feb 24 10:32 esl-erlang_25.2.3-1~debian~buster_amd64.deb
```
Actual MD5:
```
$ md5sum esl-erlang_25.2.3-1~debian~buster_amd64.deb
385d92896ab439765adcac0756a613cf  esl-erlang_25.2.3-1~debian~buster_amd64.deb
```

**Comment by KennethL** [comment]
I think this is an issue to create on this repo: https://github.com/esl/packages/issues/
We at the OTP team are not responsible for the ESL packages.

**Comment by rsommer** [comment]
Sorry for bothering you - https://github.com/erlang/otp/issues/4046 lead me to think this was the right issue tracker. Re-opened at esl's packages project.
