### ISSUE TITLE
WX_GL_CORE_PROFILE not taken into account?

### ISSUE THREAD

**Issue by Olivier-Boudeville** [erlang/otp#7019]
Hi,

(on Erlang 25.3, Arch Linux)

Maybe I am wrong, but creating a GL canvas while requesting the core profile seems, at least in my case, to still return a compatibility profile - at least the GL_ARB_compatibility extension can be detected afterwards, whereas, as I understand it, it should not (core and compatibility are exclusive, and this extension implies 'compatibility', isnt'it?).

I could notice also that in wx_opengl_SUITE.erl the use of the WX_GL_CORE_PROFILE define is commented out, and that Wings3D does not seem to use that profile either.

My setting, if it matters:
 + driver vendor: NVIDIA Corporation
 + driver renderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
 + implementation version: described as '4.6.0 NVIDIA 520.56.06', i.e. 4.6.0
 + supported profile: compatibility
 + shading language version: 4.60 NVIDIA
 + 385 OpenGL extensions supported

Another test could be done with `gl:getIntegerv( ?GL_CONTEXT_PROFILE_MASK ),` but it returns a list of integers (namely `[2,72,0,0,-1576778208,32720,-208425621,21995,2,0,-172421376,21995, 24,0,0,0])` and I do not know which one shall be band'ed  with ?GL_CONTEXT_CORE_PROFILE_BIT / ?GL_CONTEXT_COMPATIBILITY_PROFILE_BIT to check.

Thanks for any hint!

**Comment by dgud** [comment]
I have not that I remember tried to dig into this, but I don't think it is a wx bug, wx just forwards the data down to wxWidgets and OpenGL.

It might depend on how wxWidgets is built, i.e. using EGL or not, or which drivers you have, but I don't know.
I don't know if core and compatibility profiles must be exclusive, I know they are exclusive on Mac.

For how to interpret the values returned by gl:getIntegerv() you will have to read the OpenGL docs.

Since I don't think is a wx bug I will close this, please move any further discussion to the erlang-forums instead.

**Comment by Olivier-Boudeville** [comment]
Hi, thanks for your answers.

https://stackoverflow.com/a/62701962 indicates that core and compatibility profiles must be exclusive, I guess it must be the case. 

Based on your information regarding GL_CONTEXT_PROFILE_MASK, this confirmed that apparently the core profile I requested (and obtained with no error) is actually a compatibility one:

	ProfMask = gl:getIntegerv( ?GL_CONTEXT_PROFILE_MASK ),
  
	case hd( ProfMask ) band ?GL_CONTEXT_CORE_PROFILE_BIT =/= 0 of

		true ->
			trace_utils:debug( "Core profile detected." );

		false ->
			trace_utils:debug( "Core profile not detected." )

	end,

	case hd( ProfMask ) band ?GL_CONTEXT_COMPATIBILITY_PROFILE_BIT =/= 0 of

		true ->
			trace_utils:debug( "Compatibility profile detected." );

		false ->
			trace_utils:debug( "Compatibility profile not detected." )

	end,

led to the following :
```
[debug] Core profile not detected.
[debug] Compatibility profile detected.
```
Anyway this is not a big deal for me (at least for the moment), I just wanted to report it (I do not think I have too specific card/GL driver/wx version/Erlang configuration here) and to ensure that I started with the best context ;-) for my OpenGL endeavours. 

Thanks for your time!

Olivier.
