### ISSUE TITLE
Can't type cjk characters correctly in OTP 26 shell using Microsoft IME

### ISSUE THREAD

**Issue by shionryuu** [erlang/otp#7029]
**Describe the bug**

Can't type CJK correctly using Microsoft IME

**To Reproduce**

- OS: Windows
- Terminal: cmd/powershell

```cmd
Erlang/OTP 26 [erts-14.0] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Eshell V14.0 (press Ctrl+G to abort, type help(). for help)
1> "お疲れ様です。". %% paste from clipboard
[12362,30130,12428,27096,12391,12377,12290]
2> "". %% "お疲れ様です。", type with Microsoft Japanese IME
[]
3> "1717". %% "17时17分", type with Microsoft Pinyin IME, is truncated to "1717"
"1717"
4> "". %% "·", paste from clipboard
[].
5> "·". %% "·", type with Microsoft Pinyin IME
"·"
6> ;2~ %% paste from clipboard, shift+insert
```

**Expected behavior**

Type CJK using Microsoft IME

**Affected versions**

[OTP 26.0-rc1](https://github.com/erlang/otp/releases/tag/OTP-26.0-rc1)

**Comment by frazze-jobb** [comment]
Great, I will close this, I tried on Windows 10 and it seems to work, but I did not have a font in cmd.exe that could display the characters correctly.
