### ISSUE TITLE
tls_alert: handshake failure on post request

### ISSUE THREAD

**Issue by ridzria** [erlang/otp#7030]
I am getting the following error when calling my api. Is it because I'm still running the older version or something to with TLS cipher? Currently nginx server is set to TLSv1.2 for ssl_protocols.

`
Request: POST /api/bill/payment
** (exit) an exception was raised:
    ** (HTTPoison.Error) {:tls_alert, 'handshake failure'}
        (httpoison) lib/httpoison.ex:66: HTTPoison.request!/5
`
Though I tried the following config on my project and it didn't solve this issue. 

`
http_options: [
ssl: [
      ciphers:
        :ssl.cipher_suites(:all, :"tlsv1.2") ++
          [%{key_exchange: :rsa, cipher: :aes_256_cbc, mac: :sha256}],
       log_level: :all
    ],
]
`

Running the following versions
**Erlang: OTP 20
Elixir: 1.6.5**

We are in the midst of converting the project to the latest Elixir and Erlang though. In the meantime we wanted our current

**Comment by IngelaAndin** [comment]
This is too little information to be able to say anything more than it looks like some kind of interop issue.  Also OTP-20 is very old and out of support for quite some while. I suggest that you could try to use OpenSSL test client to try to find out
what algorithms your server would like to get a working connection: 

`s_client -connect localhost -tls1_2 -CAfile cacerts.pem  -debug`

**Comment by IngelaAndin** [comment]
Unless you can provide any more information there is not much we can do to help. I think you should try to upgrade your system as soon as possible.
