### ISSUE TITLE
os:cmd/1 not return

### ISSUE THREAD

**Issue by Iamwaterlemon** [erlang/otp#7037]
**Describe the bug**
when i use os:cmd/1, may be the system No response, and in the function os:get_data/6,
the receive did not return, causing the calling process to be blocked

**To Reproduce**
![image](https://user-images.githubusercontent.com/12644650/226816511-8c500781-73e2-4c10-b1f0-ee3e94418d46.png)
this is process information， try execute function os:get_data/6

**Expected behavior**
os:cmd/1 Add timeout mechanism

**Affected versions**
Erlang/OTP 22

**Comment by bjorng** [comment]
We have no plans to add a timeout mechanism for `os:cmd/1`. You can easily add a timeout yourself by one the following methods:

* Spawn a new Erlang process and execute `os:cmd/1` in that process. When the timeout expires, kill the process.
* Use [open_port({spawn_executable, Executable}, Options)](https://www.erlang.org/doc/man/erlang.html#open_port-2) and use `receive` with a timeout to receive the output from the port.
