### ISSUE TITLE
Printing a long string with ANSI escapes is very slow on Erlang/OTP 26 RC2

### ISSUE THREAD

**Issue by josevalim** [erlang/otp#7040]
**Describe the bug**

Save the contents in this file to "ansi.term": https://gist.githubusercontent.com/josevalim/d041a236af88641d9245ee14b03ae843/raw/cc91f305001f464c4a93c1afc2575ed8a4503439/ansi.term

This command is instant: `erl -noshell -eval '{ok,B} = file:consult("ansi.term"), io:put_chars(B), erlang:halt().'`

If you remove `-noshell`, however, it is very slow (several seconds): `erl -eval '{ok,B} = file:consult("ansi.term"), io:put_chars(B), erlang:halt().'`

Note both commands are fast on Erlang/OTP 25. I believe it is related to ANSI escapes.

**Affected versions**

Verified on Erlang/OTP 26 RC2.

**Comment by frazze-jobb** [comment]
Merged a fix for this.
