### ISSUE TITLE
Support `erlang:is_boolean/1` in match specifications

### ISSUE THREAD

**Issue by christhekeele** [erlang/otp#7045]
# Synopsis

Today, match specifications do not support an equivalent of `erlang:is_boolean/1`. For example:

```erlang
erlang:match_spec_test({true}, [{{'$1'}, [{is_boolean, '$1'}], [{{'$1'}}]}], table).
% {error,[{error,"Function is_boolean/1 does_not_exist."}]}
```

This is surprising behaviour, since most guard-allowed `erlang` functions are available in match specifications, and it is trivial to implement in terms of `or` and `==`, both of which ***are*** available.

This is frustrating when translating existing code into match specs when moving filter/map operations into `ets` for performance reasons.

## Desired Result

Ideally, this would work as such:

```erlang
erlang:match_spec_test({true}, [{{'$1'}, [{is_boolean, '$1'}], [{{'$1'}}]}], table).
% {ok,{true},[],[]}
```

Additionally, `is_boolean/2` would be listed in the match specification documentation grammar guide [here](https://www.erlang.org/doc/apps/erts/match_spec.html#grammar).

## Alternatives

One can always compose the equivalent working match specification:

```erlang
erlang:match_spec_test({true}, [{{'$1'}, [{'or', {'==', '$1', true}, {'==', '$1', false}], [{{'$1'}}]}], table).
% {ok,{true},[],[]}
```

However, this discrepancy furthers the cognitive gap between what is valid Erlang code, and what is valid in match specifications.

**Comment by jhogberg** [comment]
It's funny how some things can go unnoticed for so long. :-)

I've fixed it in https://github.com/erlang/otp/pull/7046, and plan to make it part of OTP 26-rc3.

**Comment by christhekeele** [comment]
@jhogberg That's excellent, thank you so much!

That PR should completely resolve [my hitlist](https://github.com/christhekeele/matcha/blob/latest/lib/matcha/context/erlang.ex#L10-L14) with the exception of `erlang:is_record/2`, which I understand has some more complicated things going on. Much appreciated!
