### ISSUE TITLE
ct_slave on win10

### ISSUE THREAD

**Issue by DominicGame** [erlang/otp#7051]
I can't found out what's wrong with it
```
Erlang/OTP 24 [erts-12.3.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]

Eshell V12.3.2  (abort with ^G)
(m@127.0.0.1)1>  ct_slave:start('127.0.0.1','s',[]).
** exception error: no match of right hand side value {error,econnrefused}
     in function  ct_slave:spawn_remote_node/3 (ct_slave.erl, line 280)
     in call from ct_slave:do_start/3 (ct_slave.erl, line 186)
(m@127.0.0.1)2>  ct_slave:start('s@127.0.0.1').     
{error,boot_timeout,'s@127.0.0.1'
```
I can start `s@127.0.0.1` by using `werl -name s@127.0.0.1` and ping `m@127.0.0.1`
```
(s@127.0.0.1)1> net_adm:ping('m@127.0.0.1').
pong
```
maybe help
```
(m@127.0.0.1)3>  ct_slave:start('s@127.0.0.1',[]).
{error,already_started,'s@127.0.0.1'}
```
using with `sname` get `boot_timeout` too

**Comment by max-au** [comment]
This happens because your local hostname is _not_ '127.0.0.1'. You can check it in the shell, e.g.:
```
(m@127.0.0.1)2> net_adm:localhost().
"win-10.home.max-au.com"
```

So, when you try running `ct_slave:start`, it thinks you're trying to start a new node over SSH - hence the error `econnrefused` (because SSH connection to 127.0.0.1 is indeed refused).

There are two solutions I can suggest:
1. Do not use `ct_slave` (I believe it is being deprecated), use `peer:start` instead:
```
(m@127.0.0.1)3> peer:start(#{name => two}).
{ok,<0.90.0>,'two@win-10.home.max-au.com'}
(m@127.0.0.1)4> nodes().
['two@win-10.home.max-au.com']
```

If you're using it for Common Test, then I'd recommend `?CT_PEER` macro instead (they are documented here: https://www.erlang.org/doc/man/peer.html#example )

2. Use the local host name instead of IP address:
```
(m@127.0.0.1)5> ct_slave:start('win-10.home.max-au.com', 's', []).
{ok,'s@win-10.home.max-au.com'}
```

However, I would advise against unless your OTP version is 24 and below (where `peer` is not supported).

**Comment by DominicGame** [comment]
@max-au thanks for reply
OTP-24 seem havn't `peer` module
I try using the local host name, but havn't success
```
ct_slave:start('DESKTOP-EL3RA3A', 's', []).       
=ERROR REPORT==== 24-Mar-2023::15:25:18.879000 ===
** System running to use fully qualified hostnames **
** Hostname DESKTOP-EL3RA3A is illegal **

=ERROR REPORT==== 24-Mar-2023::15:25:19.896000 ===
** System running to use fully qualified hostnames **
** Hostname DESKTOP-EL3RA3A is illegal **

=ERROR REPORT==== 24-Mar-2023::15:25:20.909000 ===
** System running to use fully qualified hostnames **
** Hostname DESKTOP-EL3RA3A is illegal **

=ERROR REPORT==== 24-Mar-2023::15:25:21.922000 ===
** System running to use fully qualified hostnames **
** Hostname DESKTOP-EL3RA3A is illegal **

{error,boot_timeout,'s@DESKTOP-EL3RA3A'}
```
Yes, I'm playing with `Using Common Test for Large-Scale Testing` and It's a little bit long
s_SUITE.erl
```
-module(s_SUITE).
all() -> [run].
run(_Config) -> ok.
```
s.spec
```
{node, 'S1', 's1@DESKTOP-EL3RA3A'}.
{suites, 'S1', ".", [s_SUITE]}.
```
run `ct_run -spec s.spec`  
```
TEST INFO: 0 test(s), 0 case(s) in 0 suite(s)
```
so, I try `ct_run -ctmaster`, then `ct_master:run("s.spec").`, but still not work
```
The following nodes are inaccessible: ['s1@DESKTOP-EL3RA3A']
```
I check doc and source code, find out [default callback module ct_slave](https://www.erlang.org/doc/apps/common_test/ct_master_chapter.html#automatic-startup-of-test-target-nodes) and there are some print in `ct_master:start_nodes/1`, so I try this spec
```
{node, 'S1', 's1@DESKTOP-EL3RA3A'}.
{init, 'S1', [{node_start, [{ct_slave, start}]}]}.
{suites, 'S1', ".", [s_SUITE]}.
```
but still not work, then I try `ct_slave` and post this issus

BTW, it work with `ct_run -spec s.spec`
```
{suites, all_nodes, ".", [s_SUITE]}.
```
but
```
{suites, master, ".", [s_SUITE]}.
```

**Comment by max-au** [comment]
`peer` has been released as a part of OTP-25.

The problem you're running into is long vs. short node names. The name `DESKTOP-EL3RA3A` is "shortname" (it does not contain the domain name). 
As for `Using Common Test for Large-Scale Testing`, I am yet to find anyone successfully leveraging that feature :)
