### ISSUE TITLE
Erlang OTP64 EXE VersionInfo.FileVersion should match erl.exe's one

### ISSUE THREAD

**Issue by inikulshin** [erlang/otp#7053]
Currently installer's FileVersion equals to OTP version, I think it should be equal to erts version, like all the binaries.

![b2a35feb-700f-4532-8a72-3d9090b7bd01](https://user-images.githubusercontent.com/17042537/227232772-d36066bd-43cc-4308-b04b-3b40cd1be16e.jpg)

**Comment by rickard-green** [comment]
I don't see why it should be like that. The installer is for all of OTP which is changed for each version of OTP. The `erl` executable is changed for each version of ERTS which may be the same in multiple OTP versions. That is, I find this to be exactly as expected.

**Comment by inikulshin** [comment]
@rickard-green historically, Erlang OTP installation left no (or very little?) information about OTP (aka product) version. Neither in installed file names, nor in content, nor in registry. That's why the software, that depends on Erlang (e.g. RabbitMQ) used **ERTS** version (which was always available from `erl.exe -version`) as more reliable to detect if installed Erlang matches the requirements and whether the upgrade is required.

** By the way, recently I was asked by RabbitMQ team to change detecting version from ERTS to OTP version, and I think my code don't work now, because of https://github.com/erlang/otp/pull/5524

And the things are better now (however, not perfect https://github.com/erlang/otp/issues/7054), but not for older versions and also, you change registry keys and value formats a lot...

Maybe my suggestion has its cons, but imho it still can be useful - to know which ERTS version is going to be installed and compare it to the current one.

**Comment by dgud** [comment]
Yes we have changed a lot, but the Windows meta data changes are mostly done by pullrequests and issues from rabbimq people and users.
So if you don't agree comment in those PR's and Issues before we merge them.

**Comment by inikulshin** [comment]
@dgud I don't understand what's the problem to create another PR? I can do it, if you aren't interested.

But to close bug with a reason: we already made some changes, that's enough, is ridiculous :)

**Comment by dgud** [comment]
No, I didn't close it without reason,  I closed it because we think the version handling is as Rickard wrote better now than your suggestion.

My reply was that it seems that you need to have an internal discussion of your PRs and issues before asking us
to change things and then complain that we change things often, when it is on your request.

**Comment by inikulshin** [comment]
@dgud no, my request (https://github.com/erlang/otp/issues/4232) was about VersionInfo, and the "breaking" changes in #5524 aren't related to it.

And the requests was
> For `otp_win*.exe` same VERSIONINFO, like for `erl.exe`, except
`FileDescription` which should be `%ProductName%` installer or `%ProductName% setup`

That means, same `FileVersion`, like I'm proposing now.
However, the initial bug description mentioned
> * File version (should match version of binary, e.g. 22.3.0.0)
> * Product version (should match version of binary, e.g. 22.3.0.0)

that's why both versions are equal now,

I'm not a RabbitMQ developer and I can't have an **internal** discussion with @michaelklishin or @lukebakken.

Anyway, I'm not asking from you to do anything, just to allow this very tiny PR. And the discussion should be about this particular change being right or wrong, not about the process of any previous PRs or bug fixes. Sometimes PRs require fixes, despite all the reviews and tests.

**Comment by dgud** [comment]
Ok, you kept referring to RabbiMQ, so thought you where in that team.

Your suggestion means that if we make a patch in Erlang/OTP without updating ERTS, you will have 
the same fileversion on two different installers which have different content, we don't like that, 
which is why we closed this issue.
