### ISSUE TITLE
Memory Leak in FreeBSD cpu_sup:util

### ISSUE THREAD

**Issue by VlkrS** [erlang/otp#7070]
**Describe the bug**
Each call to cpu_sup:util() in FreeBSD leaks memory.

**To Reproduce**
In the erlang shell:
```
1> cpu_sup:start().
2> lists:foreach(fun(_) -> cpu_sup:util() end, lists:seq(1,100000)).
```
and watch the memory consumption of the ```cpu_sup``` port process go up and remain on this high level, only growing with repeated calls to cpu_sup:util

**Expected behavior**
After the command has completed, the memory consumption of the ```cpu_sup``` process should go back to a lower level.

**Affected versions**
Tested with 25.3, probably every version since the FreeBSD implementation of cpu_sup:util was added.

**Additional context**
In the FreeBSD implementation of util_measure() in ```lib/os_mon/c_src/cpu_sup.c```, ```cpu_times``` is allocated but never freed.

A call to ```free((void*) cpu_times);``` [here](https://github.com/erlang/otp/blob/ae9bdb95ff6659b4f52afb65e9c00af8151bd8b3/lib/os_mon/c_src/cpu_sup.c#LL710) should fix this.

**Comment by rickard-green** [comment]
#7071 merged
