### ISSUE TITLE
gl:getDebugMessageLog/2 not returning *a list* of messages?

### ISSUE THREAD

**Issue by Olivier-Boudeville** [erlang/otp#7074]
Hi,

(Erlang 25.3 on Arch Linux)

Maybe I misunderstood https://www.erlang.org/doc/man/gl.html#getDebugMessageLog-2 (BTW, its description could be updated, as it references C "NULL" value, and "Lengths" that do not exist on the Erlang side), but I expected this function to return, in the last position of the resulting tuple, a list of messages (`[string()]`) whereas it seems to return only a `string()` .

More precisely, whereas an OpenGL debug context was supported and enabled, executing:

```
ByteCount = 5000,
Buffer = <<0:(8*ByteCount)/integer>>

% Up to 10 messages fetched:
Count = 10,

% Before any log insertion:
A = gl:getDebugMessageLog( Count, byte_size( Buffer ) ),
io:format( "A = ~p~n", [ A ] ),

Msg1 = "Hello!",

gl:debugMessageInsert(?GL_DEBUG_SOURCE_APPLICATION, ?GL_DEBUG_TYPE_ERROR,
					  10, ?GL_DEBUG_SEVERITY_HIGH, length(Msg1), Msg1),
check_error(),

Msg2 = "Goodbye...",

gl:debugMessageInsert(?GL_DEBUG_SOURCE_APPLICATION, ?GL_DEBUG_TYPE_ERROR,
					  11, ?GL_DEBUG_SEVERITY_HIGH, length(Msg2), Msg2),
check_error(),


B = gl:getDebugMessageLog( Count, byte_size( Buffer ) ),
io:format( "B = ~p~n", [ B ] ),

C = gl:getDebugMessageLog( Count, byte_size( Buffer ) ),
io:format( "C = ~p~n", [ C ] ).
```

results in:

```
A = {0,[],[],[],[],[]}
B = {2,[33354,33354],[33356,33356],"\n\v",[37190,37190],"Hello!"}
C = {0,[],[],[],[],[]}
```

whereas I would have expected for B: `{2,[33354,33354],[33356,33356],"\n\v",[37190,37190],["Hello!", "Goodbye..."]}`
("\n\v" being [10,11] indeed)

In https://github.com/erlang/otp/blob/ae9bdb95ff6659b4f52afb65e9c00af8151bd8b3/lib/wx/api_gen/glapi.conf#L502 a list was maybe intended, and in https://github.com/erlang/otp/blob/ae9bdb95ff6659b4f52afb65e9c00af8151bd8b3/lib/wx/c_src/gen/gl_nif.cpp#L11567 a single string seems to forged, not a list thereof.

Thanks in advance for any feedback!

**Comment by Olivier-Boudeville** [comment]
BTW:
* I realised that gl:getDebugMessageLog/2 does not expect a user-specified buffer (the requested size, i.e. its second parameter, must be the max size for each of the actual messages to fetch?)  
*  gl:debugMessageInsert/6 could better be gl:debugMessageInsert/5, to avoid specifying length(Msg) _and_ Msg - supposing length/1 is appropriate in all cases / for all encodings

**Comment by dgud** [comment]
Thanks for the bug report, I have removed the length in gl:debugMessageInsert was a bug in the generator.
And fixed getDebugMessageLog.
I can't do anything about the docs, that is just taken from OpenGL man pages.

**Comment by Olivier-Boudeville** [comment]
Many thanks for these updates! 
I suppose that this issue can be closed? (anyway I will test the next Erlang version that will include them, and report any issue I would see) 
Best regards,
Olivier.

**Comment by dgud** [comment]
Patch released

**Comment by Olivier-Boudeville** [comment]
(I tested these message log features in R26 and found them working perfectly as intended)
