### ISSUE TITLE
enif_get_ulong(env, term, *ip) fails to parse uint32_t on Windows Server 2022 (enif_get_uint64 works)

### ISSUE THREAD

**Issue by neelima32** [erlang/otp#7075]
**Describe the bug**
int enif_get_ulong(env, term, unsigned long* ip) behaves differently from
int enif_get_uint64(env, term, ErlNifUInt64* ip) when provided with a term that falls within UINT_MAX.
This is only on Windows 64-bit.
On MacOS/Linux 64-bit, enif_get_ulong(env, term, unsigned long *ip) works as expected for the same parameters.

**To Reproduce**
-spec pwhash(Password, Salt, Ops, Mem, Alg) -> binary()
    when
      Password :: iodata(),
      Salt     :: binary(),
      Ops      :: pwhash_limit(),
      Mem      :: pwhash_limit(),
      Alg      :: pwhash_alg().
pwhash() allows specifying a positive integer for Ops and Mem limits:
-type pwhash_limit() :: interactive | moderate | sensitive | pos_integer().
Run enacl:pwhash() on Windows 64-bit with the following arguments:
3> rp(enacl:pwhash("password",<<1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16>>,3,8388608,argon2id13)).
** exception error: bad argument
     in function  enacl_nif:crypto_pwhash/5
        called as enacl_nif:crypto_pwhash("password",
                                          <<1,2,3,4,5,6,7,8,9,10,11,12,13,14,
                                            15,16>>,
                                          3,8388608,argon2id13)
It works as expected on MacOS 64-bit and Linux 64-bit.

**Expected behavior**
Expected output:
3> rp(enacl:pwhash("password",<<1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16>>,3,8388608,argon2id13)).
<<213,175,188,72,74,14,221,122,55,24,49,186,186,7,122,43,
  221,73,218,245,140,15,249,48,8,141,209,58,111,31,137,168>>
ok

**Affected versions**
erl -eval "{ok, Version} = file:read_file(filename:join([code:root_dir(), 'releases', erlang:system_info(otp_release), 'OTP_VERSION'])), io:fwrite(Version), halt()." -noshell
25.1.2

**Additional context**
This behavior occurs only on Windows Server 2022 (amd64).
On MacOS/Linux, enif_get_ulong() works just fine with the arguments (3, 8388608).
However, I'm able to get this to run on the same Windows Server 2022 (amd64) machine by swapping out
enif_get_ulong() with enif_get_uint64() for Ops|Mem limits in these two places: 
https://github.com/jlouis/enacl/blob/master/c_src/pwhash.c#L27
https://github.com/jlouis/enacl/blob/master/c_src/pwhash.c#L53

My understanding is that enif_get_ulong() should still work even on Windows 64-bit,
so long as the supplied term falls within 4 bytes UINT_MAX.
Both 3 and 8388608 fall within this limit. Why does it fail only on Windows Server 2022?

With the same OTP version, it runs on Linux/MacOS.

I've attached the enacl Windows compilation [warnings.txt](https://github.com/erlang/otp/files/11102884/warnings.txt)

Thanks!

**Comment by mikpe** [comment]
You _do_ know that Microsoft insists on considering `long` to be 32-bit, even on x86-64? This has caused no end of issues porting code between Windows and UNIX-style environments like Linux.

There is no bug here.

**Comment by mikpe** [comment]
> If I continue to use enif_get_ulong(env, arg, &r) but return r & 0xFFFFFFFF, masking the uninitialized upper 4 bytes in size_t r

Note that this isn't a portable solution. It happens to work on little-endian CPUs like x86, but will fail on big-endian ones (older POWER, IBM S/390, Arm64s operating in big-endian mode, there are more but they're uncommon these days). I recommend ensuring that the destination variable (`r` in your case) matches exactly with the operation (`enif_get_ulong()` or similar) used to assign to it; you can always convert afterwards with a cast or assignment to the intended type.

**Comment by mikpe** [comment]
Unfortunately yes you need to use the Erlang VM specific types, so `ErlNifUint64` in this case. You can always convert to `uint64_t` if that's what some other code wants.
