### ISSUE TITLE
Performance issue in OTP 25/26

### ISSUE THREAD

**Issue by nyczol** [erlang/otp#7111]
**Describe the bug**
It looks that OTP 25/26 performance is worse than OTP 24. Please check simple benchmark below:

`
lists:reverse(lists:foldl(
	fun(TN, BAcc) ->
		BenNo = 10000,
		LLen = 1 bsl TN,
		io:format("Testing list ~p~n", [LLen]),
		LN = [{N, LLen-N} || N <- lists:seq(1,LLen)],
		{Min, Total, Max, Res} = lists:foldl(
			fun(N, {AMin, AAvg, AMax, _} = RessAcc) ->
				{CTime, CRes} = timer:tc(fun() -> Ms = maps:from_list(LN), maps:fold(fun(N1, N2, {Acc1, Acc2}) -> {N1+Acc1, N2+Acc2} end, {0,0}, Ms) end),
				NewAMin = case CTime < AMin of true -> CTime; _ -> AMin end,
				NewAMax = case CTime > AMax of true -> CTime; _ -> AMax end,
				{NewAMin, AAvg+CTime, NewAMax, CRes}
			end, {2 bsl 40, 0, 0, 0}, lists:seq(1,BenNo)),
		[{LLen, Min, erlang:round(Total/BenNo), Max, Res}|BAcc]	
	end, [], lists:seq(1, 10))).
` 

**To Reproduce**
Execute above benchmark on OTP 23/24/25/26.
For small map size (below 8) OTP 25/26 is more performant than OTP 24, but for biger maps OTP 24 is faster than 25/26. 

**Expected behavior**
OTP 26 should be more performant than OTP 25.
OTP 25 should be more performant than OTP 24.

**Affected versions**
Erlang/OTP 23 [erts-11.2.2.3] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:16] [hipe]
Erlang/OTP 24 [erts-12.3.2.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]
Erlang/OTP 25 [erts-13.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]
Erlang/OTP 26 [RELEASE CANDIDATE 2] [erts-14.0] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

**Additional context**
AMD EPYC 7742 64-Core Processor but the same issue occures also on INTEL CPU
Red Hat Enterprise Linux Server release 7.9 (Maipo)
Linux scm2.perf.scm 5.4.17-2136.309.4.el7uek.x86_64 #2 SMP Tue Jun 28 17:35:13 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux
$ cat /proc/meminfo
MemTotal:       32583404 kB
MemFree:        26619256 kB

**Comment by nyczol** [comment]
<img width="673" alt="OTP_perf" src="https://user-images.githubusercontent.com/661694/231137366-7d29efcd-ce0c-4b4a-8020-5dfa763bfa0e.png">

**Comment by jhogberg** [comment]
Thanks for your report. Are you running this benchmark by pasting the code into the shell? I can reproduce your results by doing just that, but not when the code is compiled.

**Comment by nyczol** [comment]
Yes, benchmark was executed by pasting the code into the shell.
I will check again with compiled code.

**Comment by nyczol** [comment]
Benchmark for compiled code looks OK.
Thank you for support.
I think we can close it now.

**Comment by jhogberg** [comment]
Yeah, when pasting code into the shell it'll be interpreted by the REPL (`erl_eval` module), which is rather slow compared to compiled code and its performance may vary a bit more from release to release as new language features are added (e.g. `maybe` in OTP 25). As long as the compiled code performs OK, we're happy. :-)
