### ISSUE TITLE
https://github.com/JirkaEli/J.E.pub/issues/1

### ISSUE THREAD

**Issue by JirkaEli** [erlang/otp#7127]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Affected versions**
The OTP versions that are affected by this bug.

**Additional context**
Add any other context about the problem here. If you wish to attach Erlang code you can either write it directly in the post using [code tags](https://guides.github.com/features/mastering-markdown/), create a [gist](https://gist.github.com), or attach it as a zip file to this post.

**Comment by JirkaEli** [comment]
Erlang/OTP 26 [erts-14.0] [source] [64-bit] [smp:16:8] [ds:8:8:10] [async-threads:2] [jit:ns]

Eshell V14.0 (press Ctrl+G to abort, type help(). for help)
1> 0.336+0.107+0.055+0.293+0.209.
0.9999999999999999 % expected value 1.0
2> 1+0.336+0.107+0.055+0.293+0.209.
2.0
3> 0.336+0.107+0.055+0.293+0.209-1.
-1.1102230246251565e-16
4> 0.107+0.055+0.293+0.209+0.336.
1.0
5> 0.107+0.055+0.293+0.209+0.336 =:=0.336+0.107+0.055+0.293+0.209.
false
6> 0.107+0.055+0.293+0.209+0.336 == 0.336+0.107+0.055+0.293+0.209.
false
7> 1+0.107+0.055+0.293+0.209+0.336 == 1+0.336+0.107+0.055+0.293+0.209.
true
8> 1+0.107+0.055+0.293+0.209+0.336 =:= 1+0.336+0.107+0.055+0.293+0.209.
true
9>
% I get the same result in OTP25 [erts-13.2] too, on different machines (DELL desktop, HP laptop).

**Comment by JirkaEli** [comment]
Is the Erlang sum of floats commutative?

**Comment by RaimoNiskanen** [comment]
Erlang uses the floating point library of the underlying platform.

Floating point operations may cause rounding errors, for example when adding values that do not have an exact representation in IEEE 754 binary64, which applies to almost all nice looking decimal values such as 0.1 or 0.107 (but not 0.5, nor 0.25, 0.125, ...)

One can probably expect A + B to produce the same result as B + A in any floating point library, i.e get the same rounding error, or as you say; addition should commute.
But A + B can have a different rounding error than A + C, meaning that (A + B) + C can result in a different value than (A + C) + B.  This is most certainly what you have encountered.

**Comment by JirkaEli** [comment]
Thank you very much for the explanation

Jiří Elicer
