### ISSUE TITLE
Sigsegv on using member in CoreErlang module without any exports

### ISSUE THREAD

**Issue by drathier** [erlang/otp#7151]
**Describe the bug**
A segfault.

**To Reproduce**
Steps to reproduce the behavior.

```
/tmp$ cat test.core
module 'test' [] attributes []
end
/tmp$ erlc test.core
/tmp$ elixir -e ':test.asdf'
zsh: segmentation fault  elixir -e ':test.asdf'
s139/tmp$
```
both erl and elixir segfault like this if there are zero exports from the module, but both work as expected if there's at least one export

**Expected behavior**
A printed error to stderr/stdout on use, or an error when loading/compiling the core file, not a segfault crash.

**Affected versions**
The OTP versions that are affected by this bug.

I think OTP 25.3
```
Erlang/OTP 25 [erts-13.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit] [dtrace]

Elixir 1.14.4 (compiled with Erlang/OTP 25)
```
OS: M2 (arm64) macos 13.2

**Additional context**
Add any other context about the problem here. If you wish to attach Erlang code you can either write it directly in the post using [code tags](https://guides.github.com/features/mastering-markdown/), create a [gist](https://gist.github.com), or attach it as a zip file to this post.

**Comment by jhogberg** [comment]
Thanks for your report, I've fixed it in https://github.com/erlang/otp/pull/7155
