### ISSUE TITLE
ssl system_limit

### ISSUE THREAD

**Issue by lixiaoqian521** [erlang/otp#7164]
** Reason for termination =
** {system_limit,[{erlang,spawn_opt,
                          [proc_lib,init_p,
                           [<0.24548.15>,
                            [ts_client_sup,ts_sup,<0.230.0>],
                            gen,init_it,
                            [gen_statem,<0.24548.15>,self,tls_sender,[],[]]],
                           [monitor]],
                          []},
                  {proc_lib,start,5,[{file,"proc_lib.erl"},{line,314}]},
                  {tls_connection,start_fsm,8,
                                  [{file,"tls_connection.erl"},{line,85}]},
                  {ssl_connection,connect,8,
                                  [{file,"ssl_connection.erl"},{line,91}]},
                  {ssl,connect,4,[{file,"ssl.erl"},{line,452}]},
                  {ts_client,reconnect,5,
                             [{file,"src/tsung/ts_client.erl"},{line,1083}]},
                  {ts_client,handle_next_request,2,
                             [{file,"src/tsung/ts_client.erl"},{line,888}]},
                  {gen_fsm,handle_msg,8,[{file,"gen_fsm.erl"},{line,486}]}]}
                  
                  i use tsung to connect server with ssl,how can i solve this problem
                 this is ulimit -a
```
                  [ec2-user@ip-10-0-11-180 ~]$ ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 124638
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4096
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by michalmuskala** [comment]
Given it's `spawn` that's failing, could it be the limit of Erlang processes? See: https://www.erlang.org/doc/efficiency_guide/advanced.html#system-limits

**Comment by RaimoNiskanen** [comment]
Answered?
