### ISSUE TITLE
gen_udp using {inet_backend, socket} causes crash

### ISSUE THREAD

**Issue by voluntas** [erlang/otp#7165]
**Describe the bug**

I don't know how to reproduce the issue, but a server using gen_udp with the {inet_backend, socket} option enabled occasionally experiences crashes.

Looking at the crash log, it seems to be failing on the pattern match in this section:
https://github.com/erlang/otp/blob/OTP-26.0-rc3/lib/kernel/src/gen_udp_socket.erl#L646-L649

It seems to be expecting ok or {error, closed}, but {error, select_sent} is being received instead.

The conditions for this issue to occur are unknown, but the server experiencing this problem is a low-spec machine with 1 core and 1 GB of memory. It is possible that the low specs are causing the issue.

**To Reproduce**

Currently, I do not know how to reproduce the issue.

**Expected behavior**

I expect that the crash will not occur.

**Affected versions**

OTP 26.0-rc3

**Additional context**

Crash log: 
https://gist.github.com/voluntas/eb2b2f340fab26464be3a149c327d601

The following part of the crash log corresponds to ok = gen_udp:Close(socket):
{app_udp,maybe_socket_close,1, [{file,"/app/src/app_udp.erl"},{line,587}]},

Please let me know if there is any other information needed.

**Comment by bmk** [comment]
Thanks for the report.
We have run into this ourselves.
Should be fixed when 26.0 is released (the fix is not yet merged into the master branch).

**Comment by voluntas** [comment]
I'm sorry, I left out some important information. The environment is Ubuntu 22.04 x86_64.

**Comment by bmk** [comment]
Fix is now merged (to master).

**Comment by sile** [comment]
@bmk Hi,

I had a similiar crash even after updating to Erlang/OTP 26 (`Erlang/OTP 26 [erts-14.0] [source] [64-bit] [smp:four:4] [ds:four:4:10] [async-threads:1] [jit:ns]`).

```
{{{{case_clause,{error,select_sent}},
      [{gen_udp_socket,cleanup_recv,4,
                       [{file,"gen_udp_socket.erl"},{line,646}]},
       {gen_udp_socket,handle_event,4,
                       [{file,"gen_udp_socket.erl"},{line,1356}]},
       {gen_statem,loop_state_callback,11,
                   [{file,"gen_statem.erl"},{line,1379}]},
       {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,241}]}]},
     {gen_statem,call,[<0.1648.0>,close,infinity]}},
    [{gen,do_call,4,[{file,"gen.erl"},{line,246}]},
     {gen_statem,call,3,[{file,"gen_statem.erl"},{line,905}]},
     {gen_udp_socket,call,2,[{file,"gen_udp_socket.erl"},{line,1087}]},
     {gen_udp_socket,close_server,1,[{file,"gen_udp_socket.erl"},{line,111}]},
     {gen_udp_socket,close,1,[{file,"gen_udp_socket.erl"},{line,105}]},
     {my_module,maybe_socket_close,1,
                    [{file,"/my_app/src/my_module.erl"},{line,587}]},
     {gen_server,try_terminate,3,[{file,"gen_server.erl"},{line,1125}]},
     {gen_server,terminate,10,[{file,"gen_server.erl"},{line,1321}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,241}]}]}
```
