### ISSUE TITLE
Incomplete spec on `public_key:verify/5`

### ISSUE THREAD

**Issue by vhf** [erlang/otp#7192]
**Describe the bug**

`public_key:verify/5` accepts a public key like `{ed_pub, ed25519, Pub}` but the spec does not allow it since OTP-24.2

Example code that works with all OTP versions from OTP-24.1 to OTP-26.0-rc1:

```erlang
{Pub, Priv} = crypto:generate_key(eddsa, ed25519).
Challenge = crypto:strong_rand_bytes(1024).
Sig = public_key:sign(Challenge, none, {ed_pri, ed25519, Pub, Priv}, []).
true = public_key:verify(Challenge, none, Sig, {ed_pub, ed25519, Pub}).
```
(code borrowed from <https://blog.differentpla.net/blog/2021/06/10/erlang-ed25519/>)

`public_key:verify/5` does (OTP-25.3.1):

```erlang
verify(DigestOrPlainText, DigestType, Signature, Key, Options) when is_binary(Signature) ->
    case format_verify_key(Key) of
```

and `format_verify_key/1` has this clause:

```erlang
format_verify_key({ed_pub, Curve, Key}) ->
    {eddsa, [Key,Curve]};
```

Here is `verify/5` spec:

```erlang
-spec verify(Msg, DigestType, Signature, Key, Options) ->
                    boolean() when Msg :: binary() | {digest, binary()},
                                   DigestType :: digest_type(),
                                   Signature :: binary(),
                                   Key :: public_key(),
                                   Options :: crypto:pk_sign_verify_opts().
```

Starting from OTP-24.2, `public_key()` does not allow `{ed_pub, Curve, Key}` anymore:

OTP-24.1
```erlang
-type public_key()           ::  rsa_public_key() | rsa_pss_public_key() | dsa_public_key() | ec_public_key() | ed_public_key() .
-type ed_public_key()        :: {#'ECPoint'{}, ed_params()} | {ed_pub, ed25519|ed448, Key::binary()}.
```

OTP-24.2
```erlang
-type public_key()           ::  rsa_public_key() | rsa_pss_public_key() | dsa_public_key() | ec_public_key() | ed_public_key() .
-type ed_public_key()        :: {#'ECPoint'{}, ed_params()}.
```

OTP-25.3
```erlang
-type public_key()           ::  rsa_public_key() | rsa_pss_public_key() | dsa_public_key() | ec_public_key() | ed_public_key() .
-type ed_public_key()        :: {#'ECPoint'{}, ed_params()}.
```

which means that while this works, it won't typecheck:

```erlang
public_key:verify(Challenge, ignored, Sig, {ed_pub, ed25519, Pub}).
```

**To Reproduce**

Run dialyzer on:
```erlang
{Pub, Priv} = crypto:generate_key(eddsa, ed25519).
Challenge = crypto:strong_rand_bytes(1024).
Sig = public_key:sign(Challenge, none, {ed_pri, ed25519, Pub, Priv}, []).
true = public_key:verify(Challenge, none, Sig, {ed_pub, ed25519, Pub}).
```

and get something like:
```
:public_key.verify(
  # …snip…
  {:ed_pub, :ed25519, binary()}
)

will never return since the success typing is:
(
  binary() | {:digest, binary()},
  :md5 | :none | :ripemd160 | :sha | :sha1 | :sha224 | :sha256 | :sha384 | :sha512,
  binary(),
  {integer() | {_, _},
   {:ecParameters, {:ECParameters, _, _, _, _, _, _}}
   | {:namedCurve, atom() | tuple()}
   | {:"Dss-Parms", _, _, _}
   | {:"RSASSA-PSS-params", _, _, _, _}
   | {:ECParameters, _, _, _, _, _, _}}
  | {:RSAPublicKey, _, _}
) :: boolean()
```

**Expected behavior**

Since `public_key:verify/5` works with a public key in this format: `{ed_pub, ed25519, Pub}` I would expect it to typecheck.

**Affected versions**
OTP >=24.2

**Additional context**

I bisected and the issue seems to have been introduced in 59716e72ff68354719fe80e139c8c5fef1902cd0

I'd be happy to contribute a patch but I need some guidance, I doubt it's as simple as going back to:

```diff
--type ed_public_key()        :: {#'ECPoint'{}, ed_params()}.
+-type ed_public_key()        :: {#'ECPoint'{}, ed_params()} | {ed_pub, ed25519|ed448, Key::binary()}.
```

since the part of this type that I think is missing was renamed `type ed_legacy_pubkey()`, maybe the spec change was some sort of soft deprecation and the corresponding part in `format_verify_key` will eventually be removed? `crypto:verify(eddsa, none, Message, Sig, [Pub, ed25519])` basically achieves the same thing

**Comment by IngelaAndin** [comment]
Yes this legacy format was used by some functions previously part of public_key but that where ssh-specific and are now moved there.  The plan is to remove it but that will probably happen in OTP-27 time frame.
