### ISSUE TITLE
Use of inet:gethostbyaddr on iOS device crashed / halt erlang vm / OTP 25.3

### ISSUE THREAD

**Issue by cwmichi** [erlang/otp#7194]
Hello together,

currently I start erlang on my iOS device, this works and erlang starts in iOS. Currently I use Erlang OTP 25.3
But when I use inet:gethostbyaddr("192.121.151.106") to determine the host for an ip address the whole erlang vm get an halt on my iOS device. You can also check the erlang module inet_gethost_native: Line 401
"open_executable(Prog, Opts) ->
    try open_port({spawn_executable, Prog}, Opts)
    catch
        error : badarg when hd(Opts) =:= overlapped_io ->
            open_executable(Prog, tl(Opts));
        error : Reason ->
            erlang:halt(
              "Can not execute "++Prog++" : "++term2string(Reason))
    end."

What can I do with erlang on my iOS device to get the host of an desired IP address?

On my Mac device I get the desired response, e.g. the IP to check erlang.org

inet:gethostbyaddr("192.121.151.106").
{ok,{hostent,"erlang.org",
             ["106.151.121.192.in-addr.arpa",
              "106.151.121.192.in-addr.cslab.ericsson.net"],
             inet,4,
             [{192,121,151,106}]}}

**Comment by obi458** [comment]
Therefore we cannot make connections like gen_tcp:connect("ericsson.net",80,[]), at all!

Any hints?

**Comment by cwmichi** [comment]
I found the solution and works now. On iOS I set in Xcode / swift the kernel parameter inetrc (https://www.erlang.org/docs/25/apps/erts/inet_cfg.html)
to lookup, [dns]
The default value of lookup is native (to make system calls), which causes the erlang vm to halt.

So setting the lookup value to **[dns]** _(dns (use the Erlang DNS client [inet_res(3)](https://www.erlang.org/docs/25/man/inet_res.html) for nameserver queries)_
works to getting the name resolution from the dns and make an gen_tcp:connect("erlang.org", 80,[]).

file: inetrc

{edns,0}.
{alt_nameserver, {8,8,8,8}}.
**{lookup, [dns]}.**

**Comment by RaimoNiskanen** [comment]
Sorry, I, again, mixed up iOS and Mac OS X in my head.

`inet_gethost_native` uses an external port program for calling the resolver, maybe it is not allowed in iOS to execute an external program.  What, exactly, was the halt message?

I don't know much about the iOS port, it is unsupported from our end. Is the inet_gethost binary even built succesfully?

**Comment by obi458** [comment]
Is the inet_gethost binary even built succesfully? Yes it is!
You are right: inet_gethost_native uses an external port program for calling the resolver, this is not allowed on IOS!
inetrc is the solution!
