### ISSUE TITLE
badarg error in dtls_connection.erl started in OTP-25.3.1

### ISSUE THREAD

**Issue by benbro** [erlang/otp#7219]
**Describe the bug**
Since I've upgraded to OTP-25.3.1 from OTP-25.2.2 I started getting badarg error in the logs.
This is the [line](https://github.com/erlang/otp/blob/maint-25/lib/ssl/src/dtls_connection.erl#L586) in the dtls_connection module.
```
exception error: no case clause matching badarg
in function  dtls_connection:connection/3 (ssl/src/dtls_connection.erl, line 586)
```
**To Reproduce**
I don't know. Doesn't happen all the time.

**Expected behavior**
No error.

**Affected versions**
OTP-25.3.1

**Comment by dgud** [comment]
Do you have any other errors in the log from ssl?

**Comment by benbro** [comment]
No, that's the only relevant error. DTLS works most of the time.

**Comment by u3s** [comment]
Thanks. More logs might help.
If that is possible, could you maybe try upgrading with smaller steps - including 25.2.3 and 25.3 ?

**Comment by benbro** [comment]
Yes, I'll try to also upgrade in smaller steps. I didn't get the error again in the logs. It could be a rare case or related to a specific DTLS client.
