### ISSUE TITLE
`erl` does not recognise arrow keys when terminal is in `keyboard_transmit` mode

### ISSUE THREAD

**Issue by rktjmp** [erlang/otp#7227]
**Describe the bug**

`erl` does not recognise "arrow key" key codes when terminal is configured to output in `keyboard_transmit` mode and such it wont cycle through the REPL history or move the cursor.

**To Reproduce**

Tested in `xterm` but the containing term probably wont matter unless it doesn't support `keyboard_transmit` mode. `tmux` etc may interfere with the tests.

```
# or use docker, or your regular shell, the tests are simple
podman run --rm -it hexpm/erlang:25.3-debian-bullseye-20230227-slim

# test working
erl
# type 10<left>
# observe cursor moving
# <ctrl-c><ctrl-c>

# trigger condition
tput smkx # echoti smkx for zsh

# test broken
erl
# type 10<left>
# observe the cursor not moving (also effects right cursor and up/down history seek)

# reset trigger
tput rmkx # undo smkx

# test working
erl
# type 10<left>
# observe cursor moving
# <ctrl-c><ctrl-c>
```

**Expected behavior**

`erl` should have the same history cycling and cursor behaviour when in and out of `keyboard_transmit` mode.

**Affected versions**

- 25.3

**Additional context**

You can see the differing control codes via `cat`,

```sh
tput smkx
cat
#type <up><ctrl-c>
# observe ^[0A^C
tput rmkx
cat
#type <up><ctrl-c>
# observe ^[[A^C
```

Some details on term info

https://www.man7.org/linux/man-pages/man5/terminfo.5.html

(Must search page for rmkx)

```
       keypad_local                rmkx      ke     leave
                                                    'keyboard_transmit'
                                                    mode
       keypad_xmit                 smkx      ks     enter
                                                    'keyboard_transmit'
```

(Also search for "Keypad and Function Keys")

```
The codes sent by the left arrow, right arrow, up arrow, down
       arrow, and home keys can be given as kcub1, kcuf1, kcuu1, kcud1,
       and khome respectively.
```

Also https://vi.stackexchange.com/a/15328/31653 which describes some background information.

I am not sure how common `keyboard_transmit` mode is. For what its worth I could not reproduce the behaviour in pythons or luas REPL so they either recognise the keys or swap the mode.

I was bitten by this when using `atuin`, which includes the `smkx` mode switch (perhaps erroneously?) in its default script.

https://github.com/ellie/atuin/blob/b53ca357cdd6a1b3236cbcadff8626f6bfc37748/atuin/src/shell/atuin.zsh#L34-L39

**Comment by frazze-jobb** [comment]
I don't know why this mode is used but these are the keycodes that I got in my xterm.
In tput smkx mode the following keycodes are outputted for left, right, up and down
with smkx mode:
^[OD^[OC^[OA^[OB (O like in Omega) (Home ^[OH and End ^[OF key are supported but not the arrow keys)
left, right, up, down 
without smkx mode:
^[[D^[[C^[[A^[[B

Modifier keys seem to still work:
with shift
^[[1;2D ...
with alt
^[[1;3D ...
with shift+alt
^[[1;4D ...
with ctrl
^[[1;5D
wth ctrl+shift
^[[1;6D ..

**Comment by frazze-jobb** [comment]
@rktjmp Is a fix 26.0 enough for you?

**Comment by rktjmp** [comment]
Definitely, it's not critical.

**Comment by frazze-jobb** [comment]
Added the keyboard bindings for 26.1 by default
