### ISSUE TITLE
Erlang/OTP 26 stdin fails on file:read/file:read_line

### ISSUE THREAD

**Issue by josevalim** [erlang/otp#7230]
**Describe the bug**

```erl
$ echo "duπa" | erl -noshell -eval "io:setopts(standard_io, [{encoding, latin1}, {binary, true}]), io:format('~p~n', [file:read_line(standard_io)]), erlang:halt()"
{error, collect_line}
```

**Expected behavior**

On Erlang/OTP 25 it worked without problems:

```erl
$ echo "duπa" | erl -noshell -eval "io:setopts(standard_io, [{encoding, latin1}, {binary, true}]), io:format('~p~n', [file:read_line(standard_io)]), erlang:halt()"
{ok,<<100,117,207,128,97,10>>}
```

The goal is to read a bytestream, "duπa" is just an example.

**Affected versions**

Only on Erlang/OTP 26. [This patch fixes stdout](https://github.com/erlang/otp/pull/7211), perhaps similar is needed for stdin?

**Comment by lukaszsamson** [comment]
@frazze-jobb when can we expect a release with fix for that? This one is breaking elixirLS (Elixir Language Server)

**Comment by frazze-jobb** [comment]
Yes, am on parental leave this week, but will look into it next week

**Comment by frazze-jobb** [comment]
Would it be okey to start the shell later?
`echo "duπa" | erl -noinput -eval "io:setopts(standard_io, [{encoding, latin1}, {binary, true}]), shell:start_interactive(noshell), io:format('~p~n', [file:read_line(standard_io)]), erlang:halt()"`

In that case it would be possible to solve this similarly to #7211

**Comment by lukaszsamson** [comment]
@frazze-jobb I can start the shell later but I need something that will work on lower OTP versions. Your example crashes OTP 25
```
echo "duπa" | erl -noinpul -eval "io:setopts(standard_io, [{encoding, latin1}, {binary, true}]), shell:start_interactive(noshell), io:format('~p~n', [file:read_line(standard_io)]), erlang:halt()"
{"init terminating in do_boot",{undef,[{shell,start_interactive,[noshell],[]},{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,744}]},{erl_eval,exprs,6,[{file,"erl_eval.erl"},{line,136}]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({undef,[{shell,start_interactive,[noshell],[]},{erl_eval,do_apply,7,[{_},{_}]},{erl_eval,exprs,6,[{_},{_}]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...done
```

**Comment by lukaszsamson** [comment]
Alternatively, is it possible to read from stdin device without starting a shell?

**Comment by josevalim** [comment]
@frazze-jobb I see! What do you think about a VM flag or app configuration? `-kernel stdin_encoding latin1`? This way you can read the default configuration, it can be set early on, and it should be backwards compatible.

**Comment by ferd** [comment]
For what it's worth, you can access the direct binary stream by setting stdio as a file descriptor when using the erlang:open_port/2 BIFs: 

```
cat ~/Desktop/Audio.wav | head -n1
RIFF�sWAVEJUNK4fmt D��data��s������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������

$ cat ~/Desktop/Audio.wav | head -n1 | erl -noinput -eval 'P = erlang:open_port({fd,0,1}, [binary]), receive {P,{data,X}} -> erlang:port_command(P, ["input was: ", X]) end, halt()'
input was: RIFF�sWAVEJUNK4fmt D��data��s������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
```

This will preserve the exact encoding that was passed in the input. If it was unicode, it remains unicode, if it was binary garbage, it remains binary garbage

**Comment by ferd** [comment]
hm, I think unfortunately windows is pickier about drivers hijacking stdio, even though Erlang is told not to use them. It might fail there, but I haven't had a windows computer in a functional state in a long while to check it.

**Comment by garazdawi** [comment]
Nice idea @ferd !

> @ferd will it work in windows?

I tried it in Windows 10 using cmd.exe and it works there. So I would expect it to work anywhere. This is basically how "oldshell" used to work before the OTP 26 rewrite.

**Comment by lukaszsamson** [comment]
The downside it that as far as I understand it just passes byte blobs with no concept of lines. In order to use it in elixirLS I'd need to implement buffering and reading by lines.

**Comment by garazdawi** [comment]
You can pass `{line, 80}` to open_port to make it send messages based on lines. And the buffer can just be the process mailbox :)

That being said, I think we will add an option as Josè described so that you can set the encoding of standard_io when you start erlang.
