### ISSUE TITLE
`socket:send` doc inconsistent with typespec

### ISSUE THREAD

**Issue by digitalcora** [erlang/otp#7238]
In the current published `socket` documentation, the "nowait" variant of `send` has the following return type:

```
ok |
{ok, RestData} |
{select, SelectInfo} |
{select, {SelectInfo, RestData}} |
{error, Reason}
```

The description then also includes this sentence:

> If some of the data was sent, the function will return [`{ok, {RestData, SelectInfo},`](https://www.erlang.org/doc/man/socket.html#type-select_info) which can only happen for a socket of [type `stream`](https://www.erlang.org/doc/man/socket.html#type-type).

However, this does not correspond to any return type listed in the typespec. If the spec is correct, maybe this was intended to be `{select, {SelectInfo, RestData}}`. But I'm not yet sure how to construct a scenario where the function would return this value, so I haven't verified it.

**Note:** A similar sentence is also included (with the same missing `}`) in the docs for the "nowait" variants of `sendfile`, `sendmsg`, and `sendto`. These also seem to contradict the typespecs of their respective functions.

**Comment by RaimoNiskanen** [comment]
It seems that paragraph in all `nowait` variants of `send*` is a rest int the documentation from before a return value cleanup.
The correct return type in all these cases is `{select, {SelectInfo, RestData}}`, which is in the function's return type.

I will put this on an appropriate ToDo list...

**Comment by digitalcora** [comment]
Thanks! I also just noticed the docs have been updated for the 26.0 release (🎉) and while there was some rewording and the missing `}` typo was corrected, these sections still say the return value is `{ok, {Data, SelectInfo}}`.

**Comment by IngelaAndin** [comment]
OTP-26.0.1 has been released

**Comment by digitalcora** [comment]
It seems like, in correcting this error, another error was made: the updated docs now say the return value is `{select, {RestData, SelectInfo}`. The tuple elements are switched from the actual type `{select, {SelectInfo, RestData}}`, and the closing brace has gone missing again.
