### ISSUE TITLE
Erlang/OTP 26 compiler reorder binary clauses leading to incorrect code

### ISSUE THREAD

**Issue by josevalim** [erlang/otp#7259]
**Describe the bug**

This code:

```erlang
-module(foo).
-compile([export_all]).
-compile([{error_location,line}]).
bar(<<"datediff", Rest/binary>>) -> {ok, "datediff"}; bar(<<"date", Rest/binary>>) -> {ok, "date"}.
```

When run:

```
$ erl -eval 'erlang:display(foo:bar(<<"datediff">>)), halt().'
Erlang/OTP 26 [erts-14.0] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

{ok,"date"}
```

It should have returned "datediff" but the clauses seem to have been reordered. If we keep the column information, then it works (because I assume the column information keeps the correct ordering).

**Affected versions**

Erlang/OTP 26.

**Additional context**

Initially reported here: https://github.com/dashbitco/nimble_parsec/issues/121

**Comment by bjorng** [comment]
Thanks! The linked pull requests resolves the issue.
