### ISSUE TITLE
Erlang/OTP 26 hangs when stdio is set utf-8 encoding without a terminal on Windows

### ISSUE THREAD

**Issue by josevalim** [erlang/otp#7261]
**Describe the bug**

Take this module:

```erlang
-module(foo).
-compile(export_all).

run() ->
  io:put_chars("START\n"),

  open_port(
    {spawn_executable, os:find_executable("erl")},
    [use_stdio, exit_status, binary, hide,
     {args, ["-eval", "io:setopts(standard_io, [{encoding, utf8}]), io:write(hello), erlang:halt()."]}]
  ),

  loop().

loop() ->
  receive
    {_, {data, Data}} ->
      io:put_chars(Data),
      loop();

    {_, {exit_status, _}} ->
      erlang:halt()
  end.
```

If you call `erl -s foo run` on Windows, it will hang because the `open_port` never completes. The `io:write(hello)` operation in the subprocess hangs once we set the encoding to `io:setopts(standard_io, [{encoding, utf8}])`. This only happens on Windows and only if we set the device to `[{encoding, utf8}]`.

**Affected versions**
Erlang/OTP 26.

**Comment by josevalim** [comment]
For completeness, this issue also manifests when invoking rebar3 without an attached terminal on Windows.

**Comment by garazdawi** [comment]
This turned out to be rather difficult to fix, but I think I've found a solution in #7400 . I really would like there to be some way to automatically test the windows console, as it is now we have to hope that I recall to test all variants manually....

maybe I need to write a manual testing script that makes sure that all things work as they should...

**Comment by josevalim** [comment]
Nice!

For IEx, we literally wrote a document with all manual tests to run, because it was really hard to automate. :(

**Comment by garazdawi** [comment]
> For IEx, we literally wrote a document with all manual tests to run, because it was really hard to automate. :(

I was hoping to avoid doing that, but maybe it is time to bite the bullet...
