### ISSUE TITLE
[public_key] Dedicated error on missing cacerts file

### ISSUE THREAD

**Issue by maennchen** [erlang/otp#7295]
**Describe the bug**

When calling `public_key:cacerts_get/0` and the operating system does not have a root ca file, the function crashes instead of returning the error tuple.

**To Reproduce**

```bash
docker run -ti hexpm/erlang:26.0-debian-bullseye-20230227-slim erl -eval 'public_key:cacerts_get()'
```

```
** exception error: no match of right hand side value {error,enoent}
     in function  pubkey_os_cacerts:get/0 (pubkey_os_cacerts.erl, line 38)
```

**Expected behavior**

It should return `{error, enoent}` to the caller.

**Affected versions**

`>= 25.0`

**Additional context**

`httpc:ssl_verify_host_options/1` should also be able to handle the error or return an error itself.

PS: Happy to provide a PR for the issue once the solution has been decided.

**Comment by dgud** [comment]
This is by design and documented, "The function fails if no cacerts could be loaded.", if the OS is not supported or not configured as expected then we should crash and signal that things are not working as expected.

If you are running such as system, you must invoke public_key:cacerts_load(File) initially, 
and/or in the case of httpc set the ssl options manually (and in OTP-26 override the default ssl options).

**Comment by maennchen** [comment]
@dgud Ok. Is crashing with badmatch really what we want or should that have a dedicated error instead?

The current situation does not feel like the behavior is intended.

**Comment by dgud** [comment]
Yeah, it might be cleaner to catch/case the badmatch and exit with the error returned from load.

**Comment by maennchen** [comment]
@dgud I‘ll open a PR 👍

**Comment by maennchen** [comment]
Additionally:

Why does the following code trigger that error?

```erlang
inets:start(),
ssl:start(),
Response = httpc:request(get, {\"https://google.com\", []}, [{ssl,[{verify, verify_none}]}], []),
erlang:display(Response).
```

```
** exception error: no match of right hand side value {error,enoent}
     in function  pubkey_os_cacerts:get/0 (pubkey_os_cacerts.erl, line 38)
     in call from httpc:ssl_verify_host_options/1 (httpc.erl, line 476)
     in call from httpc:http_options_default/0 (httpc.erl, line 1012)
     in call from httpc:http_options/1 (httpc.erl, line 927)
     in call from httpc:handle_request/9 (httpc.erl, line 771)
``

When setting `verify_none` on purpose, there's no reason to attempt to load the certs, no?

**Comment by dgud** [comment]
Hmm, that should override the ssl options, that is bug in httpc.
Please open a new issue and close this one.

**Comment by maennchen** [comment]
Issue replaced by #7302 & #7303
