### ISSUE TITLE
New shell does not understand termcap delay info

### ISSUE THREAD

**Issue by russor** [erlang/otp#7308]
**Describe the bug**
The new shell in OTP/26 does not handle termcap delay info, so when tgetstr("up") returns ```<<"\e[A$<2/>">>```, rather than delaying 2 milliseconds, or ignoring it, the literal ```$<2/>``` is sent to the terminal. 

**To Reproduce**

On FreeBSD 13.1-RELEASE-p3, this is visible with TERM=vt100 erl; nearly any input will leave trails of ```$<2/>``` and or ```$<50/>``` (from tgetstr("cd")). I suspect this will show up similarly on other systems, but termcap/terminfo databases may differ.

**Expected behavior**
Ideally, the termcap delays would be respected; but at least, they should be ignored, if present, and not output. 

**Affected versions**
OTP/26 running the new shell. Running -oldshell does not show this behavior. TERM=xterm does not have delays in its strings, and does not show an issue.

**Additional context**
terminfo(5) describes the delay specifications as follows:

       A delay in milliseconds may appear anywhere in a string capability,
       enclosed in $<..> brackets, as in el=\EK$<5>, and padding characters
       are supplied by tputs(3X) to provide this delay.

       •   The delay must be a number with at most one decimal place of
           precision; it may be followed by suffixes “*” or “/” or both.

       •   A “*” indicates that the padding required is proportional to the
           number of lines affected by the operation, and the amount given is
           the per-affected-unit padding required.  (In the case of insert
           character, the factor is still the number of lines affected.)

           Normally, padding is advisory if the device has the xon capability;
           it is used for cost computation but does not trigger delays.

       •   A “/” suffix indicates that the padding is mandatory and forces a
           delay of the given number of milliseconds even on devices for which
           xon is present to indicate flow control.

**Comment by russor** [comment]
I had some trouble getting this compiling, possibly related to the bootstrap beam file. erlc would not run, because user_drv would fail with bad_lib, Function not found prim_tty:tgoto_nif/1 (or similar).

I ended up taking master plus the updated erl, copying the prim_tty.beam to bootstrap, and then rebuilding with the updated nif.c as well.

After that, the shell works fine with TERM=xterm or TERM=unknown, but TERM=vt100 results in an instant crash:
`
[toast@cylon ~/otp]$ TERM=vt100 ./bin/erl
=ERROR REPORT==== 2-Jun-2023::12:33:33.261969 ===
** State machine user_drv terminating
** When server state  = {undefined,undefined}
** Reason for termination = error:{badmatch,false}
** Callback modules = [user_drv]
** Callback mode = state_functions
** Stacktrace =
**  [{prim_tty,init,2,[{file,"prim_tty.erl"},{line,327}]},
     {prim_tty,init_term,1,[{file,"prim_tty.erl"},{line,238}]},
     {user_drv,init,1,[{file,"user_drv.erl"},{line,154}]},
     {gen_statem,init_it,6,[{file,"gen_statem.erl"},{line,1018}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]

=CRASH REPORT==== 2-Jun-2023::12:33:33.262006 ===
  crasher:
    initial call: user_drv:init/1
    pid: <0.64.0>
    registered_name: []
    exception error: no match of right hand side value false
      in function  prim_tty:init/2 (prim_tty.erl, line 327)
      in call from prim_tty:init_term/1 (prim_tty.erl, line 238)
      in call from user_drv:init/1 (user_drv.erl, line 154)
      in call from gen_statem:init_it/6 (gen_statem.erl, line 1018)
    ancestors: [<0.63.0>,kernel_sup,<0.47.0>]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 434
  neighbours:
`
Looks like line 329, is missing {ok, ...} around (#state{})#state.delete

After adding that in to match the rest of the surroundings, things look good.

Thanks!!!!

**Comment by garazdawi** [comment]
I was a bit eager to start my weekend so apparently missed some things. Will polish things on Monday. Thanks for testing!
