### ISSUE TITLE
erlc halts with `when is_record(Rec, a, 10000000)`

### ISSUE THREAD

**Issue by ilya-klyuchnikov** [erlang/otp#7317]
**Describe the bug**
erlc halts with `when is_record(Rec, a, 10000000)`

**To Reproduce**
```erlang
-module(loop).
-export([test/1]).

test(Rec) when is_record(Rec, a, 10000000) ->
  Rec;
test(_) ->
  false.
```

`erlc loop.erl` halts

**Expected behavior**
It compiles

**Affected versions**
OTP 26, OTP 25

**Comment by bjorng** [comment]
Fixed in two pull requests:

#7319 (maint and master)
#7320 (master only)
