### ISSUE TITLE
[Erlang/OTP 26] [Windows] Old shell does not echo

### ISSUE THREAD

**Issue by foldl** [erlang/otp#7324]
**Describe the bug**

Old shell does not echo.

**To Reproduce**

Start Erlang by `erl.exe -oldshell`, try to input something, but nothing is echo-ed.

Hit enter, then we can confirm that Erlang has read our input, but does not print on the screen.

**Expected behavior**

Old shell just should work like before.

**Comment by foldl** [comment]
Why do I want to try the old shell? Because of issue #7263.

**Comment by garazdawi** [comment]
Fix merged to be released in 26.1. Thanks for the report!
