### ISSUE TITLE
docs: `$OTPROOT` vs. `$OTP_ROOT`

### ISSUE THREAD

**Issue by TD5** [erlang/otp#7332]
**Describe the issue**
The OTP docs refer to the variables `$OTPROOT` and `$OTP_ROOT`, for example, [here](https://www.erlang.org/doc/man/code.html#code-path). The similarity in the names is a bit confusing to me. Are they meant to refer to the same thing, and it's a typo in the docs? Are they two different things, but with misleading names?

**Comment by garazdawi** [comment]
They refer to the same thing, just different authors of the documentation have chosen to call them slightly different things :) There is also `ERL_ROOT` and `RELEASE_ROOT` which I think refer to the same thing. While `ROOT` and `ROOTDIR` have a different meaning...

A PR that tries to unify the usage would be appreciated! :)
