### ISSUE TITLE
Regression in error reporting with 26.0?

### ISSUE THREAD

**Issue by Olivier-Boudeville-EDF** [erlang/otp#7344]
Hi,

While developing a test module of mine, I noticed that with version 26.0 the error reporting was at least in my case a lot less useful than in previous versions.

On the same computer (GNU/Linux, derived from Debian Bullseye) and same codebase, with 25.3 I had:

```
[...]
{"init terminating in do_boot",{{nocatch,{unsupported_random_law_spec,#Fun<random_utils_test.0.14562089>}},[{random_utils,initialise_law,1,[{file,"random_utils.erl"},{line,1187}]},{random_utils_test,run,0,[{file,"random_utils_test.erl"},{line,145}]},{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,744}]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({{nocatch,{unsupported_random_law_spec,}},[{random_utils,initialise_law,1,[{_},{_}]},{random_utils_test,run,0,[{_},{_}]},{erl_eval,do_apply,7,[{_},{_}]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...done
[...]
```

(which is appropriate and useful), whereas now 26.0 returns for the same case:

```
[...]
Error! Failed to eval: random_utils_test:run()

Runtime terminating during boot ({{nocatch,{unsupported_random_law_spec,}},[{random_utils,canonicalise_law_spec,1,[{_},{_}]},{random_utils,initialise_law,1,[{_},{_}]},{random_utils_test,run,0,[{_},{_}]},{erl_eval,do_apply,7,[{_},{_}]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...done
[...]
```

So the fun was not printed out at all (reproducibly), and files and line numbers are lost.

If it matters, it was run with:

```
erl -eval random_utils_test:run() +W w -pz [...] -smp +K true +A 128 +zdbbl 1048576 +P 400000 -setcookie xxx -kernel inet_dist_listen_min 50000 inet_dist_listen_max 55000 -sname random_utils_run-YYY +pc unicode -noinput -extra
```

Thanks in advance,
Best regards,

Olivier.

**Comment by Olivier-Boudeville-EDF** [comment]
(on the other hand we now see a presumably "inlined" function in the stacktrace - canonicalise_law_spec/1 here - which is appreciated)

**Comment by Olivier-Boudeville** [comment]
It may matter that a debug_info_key was set when compiling (worked great for years)

**Comment by jhogberg** [comment]
Thanks for your report! I've removed the bespoke term formatting routine that tried to limit the depth of the slogan in https://github.com/erlang/otp/pull/7350 and replaced it with the emulator's internal term formatting (since `io_lib` is unavailable at this point), feel free to try it out.

**Comment by jhogberg** [comment]
Great, I'll go ahead and merge it then. :)
