### ISSUE TITLE
[erlc] +no_ssa_opt leading to a type_conflict internal consistency failure

### ISSUE THREAD

**Issue by RobinMorisset** [erlang/otp#7360]
**Describe the bug**
Running `erlc +no_ssa_opt` on the following code:
```erlang
f(_V0) ->
    [0 || not (_V0 > (0 bsl erlang:adler32(true = (_V7 = (ok < _V0))))), _V7].
```
results in the following error message:
```
test21380:1: function f/1+20:
  Internal consistency check failed - please report this bug.
  Instruction: {test,is_eq_exact,{f,10},[{y,0},{atom,true}]}
  Error:       {type_conflict,{t_atom,[ok]},none}:
```

**Affected versions**
- master
- master + #7355 + #7357

**Additional context**
This might be a duplicate of #7342, but it only reproduces with `+no_ssa_opt` which made me think it might be a different problem.

**Comment by RobinMorisset** [comment]
Another one, this one needs `+no_copt +no_ssa_opt`:
```erlang
f() ->
    <<_V0/utf32>> = foo,
    [
        0
     || _ <- bar,
        _V4 = (_V2 = _V0) > baz,
        _V4 =
            case _V2 bxor _V2 of
                _ -> ok
            end
    ].
```

**Comment by RobinMorisset** [comment]
A last one (only needing `+no_ssa_opt`), showing that list comprehensions are not necessary for this bug:
```erlang
f(_V3) ->
    case foo =< _V3 of
        _V4 when _V4 andalso {trunc(_V3), _V4 orelse bar} ->
            ok
    end.
```

**Comment by bjorng** [comment]
These examples are duplicates of #7342, despite optimizations being disabled. Unfortunately, simple/partial solutions that might work for those example will mess up other code.

If think it is safe to assume that any failure having the reason `{type_conflict, Something, SomethingElse}` should go into #7342.
