### ISSUE TITLE
`code:ensure_loaded/1` logs error on invalid capitalization

### ISSUE THREAD

**Issue by jonatanklosko** [erlang/otp#7363]
**Describe the bug**

Passing an a module name to `code:ensure_loaded/1` results in an error report being logged. This happens specifically if there exists a module with the given name but different capitalization.

**To Reproduce**

Inside `erl`:

```
1> code:ensure_loaded(iO).
=ERROR REPORT==== 5-Jun-2023::16:37:19.367132 ===
beam/beam_load.c(180): Error loading module iO:
  module name in object code is io


{error,badfile}
```

**Expected behavior**
No error should be logged, just returned.

**Affected versions**

OTP 26.0 (but OTP 25.3.2 as well)

**Comment by jhogberg** [comment]
Thanks for your report!

Error reports on corrupt modules are by design and this is a corrupt module: we asked for `iO.beam` and got something entirely different (`io.beam`), likely due to the file system being case insensitive. I don't think we'll do anything about this.

**Comment by jonatanklosko** [comment]
@jhogberg it happens on macOS, which is case insensitive, good point.

For more context, this error pops up on intellisense both in [Livebook](https://github.com/livebook-dev/livebook) and Elixir shell, when looking for functions in a mistyped module like `Io.` (since we try to load the module). That said, it's only in case of such typos and hence not critical, so feel free to close if there's no reasonable way to make it quiet. Thanks :)

**Comment by jhogberg** [comment]
Have you tried using [logger filters](https://www.erlang.org/doc/apps/kernel/logger_chapter.html#filters) to filter them out?

**Comment by jonatanklosko** [comment]
@jhogberg I added a filter to ignore all logs from `code_server`, thanks for the suggestion!
