### ISSUE TITLE
*NIF tutorial* uses `exit/1` in NIF stubs instead of more appropriate `erlang:nif_error/1`.

### ISSUE THREAD

**Issue by p-kraszewski** [erlang/otp#7371]
**Describe the bug**
[NIF tutorial](https://www.erlang.org/doc/tutorial/nif.html) uses `exit/1` in NIF stubs instead of `erlang:nif_error/1`, which makes `dialyzer` report "*function ... has no local return*" on usage.

**To Reproduce**
1. Create fresh rebar3 app with `rebar3 new app a`
2. Edit `a_app.erl` as follows (using fragments straight from *NIF tutorial*:
```erlang
-module(a_app).

-behaviour(application).

-nifs([foo/1, bar/1]).
-on_load(init/0).

-export([start/2, stop/1]).

start(_StartType, _StartArgs) ->
  foo(1).

stop(_State) ->
  bar(1).

init() ->
  ok = erlang:load_nif("./complex6_nif", 0).

foo(_X) ->
  exit(nif_library_not_loaded).
bar(_Y) ->
  exit(nif_library_not_loaded).
```

3. Run `rebar3 dialyzer`
4. Observe error output:

```
[...]
===> Analyzing 1 files with _build/default/rebar3_25.3_plt...

src/a_app.erl
Line 13 Column 1: Function start/2 has no local return
Line 16 Column 1: Function stop/1 has no local return
===> Warnings written to _build/default/25.3.dialyzer_warnings
```

**Expected behavior**
When all stub instances have `exit/1` replaced with `erlang:nif_error/1`, the error is no more:

```erlang
% ...

foo(_X) ->
   erlang:nif_error(nif_library_not_loaded).
bar(_Y) ->
   erlang:nif_error(nif_library_not_loaded).
```

```
===> Analyzing 1 files with _build/default/rebar3_25.3_plt...

[No further messages]
```

**Affected versions**
Encountered on `Erlang/OTP 25 [erts-13.2]`. No idea on previous occurances. 

**Additional context**

Unintentional triggering of `Function ___ has no local return` can hide/overwhelm legitimate cases where this warning *actually is* an indication of a bug. This happened for me - fixing all warnings caused by `exit/1` unveiled a real bug in my code (what's worse - a corner case that would go unnoticed for months).

**Comment by sverker** [comment]
Fix in #7452
