### ISSUE TITLE
Doom emacs 27  Erlang shell output syntax problem

### ISSUE THREAD

**Issue by erdalturan** [erlang/otp#7393]
**Describe the bug**
When I worked Erlang with shell mode in doom Emacs I had a problem my problem is that I wrote some Erlang code in Erl shell, my code output have some ugly

**To Reproduce**
[Steps to reproduce ]
example: **lists:reverse([1,2,3,4]).**
my output: **$<50>1>**  [4,3,2,1]
**Expected behavior**
[4,3,2,1]
print screen
`https://imgur.com/9qTUHIG`
**Affected versions**
 Erlang versions 26.0.1
System Linux Ubuntu 22

**Comment by erdalturan** [comment]
I don't have any problem for Erlang old version they  working  are very well in my system.

**Comment by garazdawi** [comment]
This seems like the same problem as https://github.com/erlang/otp/issues/7308. Can you try that patch and see if it solves your problem?

**Comment by erdalturan** [comment]
I'm not sure, but maybe this problem because of part of this  https://github.com/erlang/otp/blob/master/lib/tools/emacs/erlang.el#LL5589C18-L5589C18

**Comment by garazdawi** [comment]
Hello! Did you try #7308?

**Comment by erdalturan** [comment]
> Hello! Did you try #7308?

Hello Lucas, today I was try it.
Firstly I removed my latest erlang and I removed in my system cache with auto-clean , then I get your latest branch and I compiled it and then I tested Erlang official shell, but it is output not be fixed. I will attached a print screen.
Notice: In emacs, and doom emacs has a lot of shell program they are working, one of them Erlang-Shell that is a official package output still is ugly 
**my system otuput**: https://imgur.com/a/L9mGxpC

**Comment by garazdawi** [comment]
I was able to reproduce it in normal Emacs for 26.0.1, but in the latest `maint` the bug is fixed by #7352. The [version you tried](https://github.com/erlang/otp/tree/591c578c46b61cb6a013b4f464c8b5451959df43) does not have that fix, so if you try again with the latest maint version it should work.

**Comment by erdalturan** [comment]
Thank you, I compiled again and I see , but I have new problem my problem is
When I keep writing till dot, everything repeats once.  If I keep writing and then switching new line with enter command everything repeat twice.

my latest printscreen: https://imgur.com/a/PXfXKwf

**Comment by garazdawi** [comment]
I noticed the same thing, emacs seems to not handle some characters that it says that it should handle.

If you set `inferior-erlang-shell-type` to `oldshell`, does that work better? i.e. something like this: `(setq  inferior-erlang-shell-type 'oldshell)` in .emacs.

**Comment by erdalturan** [comment]
sure I will try it. 
And I want to share a notice, if I `set -v` in some terminal my  terminal behavior like this **old command repating again**. and I set like this `'set -b` but this way not worked for me.

**Comment by erdalturan** [comment]
I was try it and boom! yeah it was worked :)
My Doom Emacs folder path for Erlang Emacs: `/home/etran/.config/emacs/.local/straight/build-27.1/erlang
how to did I compiled  erlang.el ? compiler command here is `doom run   emacs -batch -q -no-site-file -f batch-byte-compile erlang.el
`

**Comment by erdalturan** [comment]
> I noticed the same thing, emacs seems to not handle some characters that it says that it should handle.
> 
> If you set `inferior-erlang-shell-type` to `oldshell`, does that work better? i.e. something like this: `(setq inferior-erlang-shell-type 'oldshell)` in .emacs.

Hello again, today I did some tests  that you mention it.  I worked only Ubuntu machine with Erlang  latest version `26.0.0` 

`(setq  inferior-erlang-shell-type 'oldshell)` yes this worked wtih `vt100` 
worked:  `             (setq opts (append '("-oldshell" "-env" "TERM" "vt100") opts)))))

Then I worked alternaitvie terminals  like these: `Eshell`, `Vterm`, 
These are didn't affect When I  used them one by one instead of `vt100` They were worked.

`(setq  inferior-erlang-shell-type 'oldshell)`  newshell or oldshell didn't affected
`(setq  inferior-erlang-shell-type 'newshell)`  newshell or oldshell didn't affected
worked:  `             (setq opts (append '("-newshell" "-env" "TERM" "eshell") opts)))))
worked:  `             (setq opts (append '("-oldshell" "-env" "TERM" "eshell") opts)))))
`

**Comment by garazdawi** [comment]
With the new multiline editing support, we do a lot more redrawing of the terminal contents which the Emacs shell does not seem to handle very well. So if you want to work with the Erlang shell inside Emacs, I think the best option is to use `oldshell` so that the Erlang shell and Emacs shell do not step on each other's toes.
