### ISSUE TITLE
zip:create/2,3 does not accept a valid file:file_info record

### ISSUE THREAD

**Issue by sirikid** [erlang/otp#7412]
**Describe the bug**
`zip:create/2,3` does not accept a valid `file:file_info` record.

**To Reproduce**
In erl:
```
Eshell V13.2.2  (abort with ^G)
1> rr(code:lib_dir(kernel, include) ++ "/file.hrl").
[file_descriptor,file_info]
2> zip:create("archive.zip", [{"file.txt", <<>>, #file_info{type=regular, mtime=0}}], [memory]).
{error,{'EXIT',{function_clause,[{zip,dos_date_time_from_datetime,
                                      [0],
                                      []},
                                 {zip,local_file_header_from_info_method_name,5,
                                      [{file,"zip.erl"},{line,1131}]},
                                 {zip,put_z_files,6,[{file,"zip.erl"},{line,874}]},
                                 {zip,do_zip,3,[{file,"zip.erl"},{line,466}]},
                                 {zip,zip,3,[{file,"zip.erl"},{line,455}]},
                                 {erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,748}]},
                                 {shell,exprs,7,[{file,"shell.erl"},{line,691}]},
                                 {shell,eval_exprs,7,[{file,"shell.erl"},{line,647}]}]}}}
```

**Expected behavior**
The file modification time in the archive is set to the Unix epoch. (This won't actually happen because I've omitted the rest of the file_info for brevity.)

**Affected versions**
At least 25.3.2

**Additional context**
I want to create a reproducible archive and while it's doable with the current API it's not that concise. It might be worth adding an option for this.

**Comment by paulo-ferraz-oliveira** [comment]
`file_info`'s `mtime` is specified as https://www.erlang.org/doc/man/calendar.html#type-datetime, which means it can't be `0`, as per your input.

**Comment by jhogberg** [comment]
Thanks for your report, feel free to make a PR that handles this. :)
