### ISSUE TITLE
An error to ssl:send/2 over an active socket isn't followed by an ssl_error message

### ISSUE THREAD

**Issue by dszoboszlay** [erlang/otp#7431]
**Description**
I use an `ssl` client socket in active mode on OTP 24.3. The connection is TLS 1.2, and after a while I reach the `renegotiate_at`  limit of `tls_sender`. However, the server doesn't support renegotiation and closes the TCP connection.

At this point the `ssl:send/2` call that triggered the renegotiation returns `{error, closed}`, however the owner of the socket doesn't receive an `ssl_closed` or `ssl_error` message, so it believes the connection is still alive.

**Expected behaviour**
I would expect the owner of an active socket to receive an `ssl_closed` or `ssl_error` message when the socket is closed. A failure in `send/2` shouldn't be considered an implicit notification of the owner about the socket getting closed. Especially since the `send/2` could happen in any other process too.

But to be honest, I didn't find this scenario described in the documentation, and I could accept the current behaviour to be correct too, but in that case it should be properly documented at least.

**Affected versions**
Tested with OTP 24.3, don't know about later versions.

**How to reproduce**
The above described scenario depends on the server's SSL/TLS implementation and configuration. I can reproduce the problem by using `epgsql` to connect to an Amazon Aurora DB:

```erlang
application:ensure_all_started(epgsql).
Opts = #{host => "yourhost", port => 5542,
         username => "youruser", password => "yourpassword",
         socket_active => true,
         ssl => required,
         ssl_opts => [{renegotiate_at,5},{verify,verify_none}]}.
{ok, PidOfEpgsql} = epgsql:connect(Opts).
epgsql:squery(PidOfEpgsql, "SELECT 1+1;").
```

The `{renegotiate_at, 5}` option ensures the renegotiation happens on the first request, not after several days of operation.

In this example, `epgsql_sock` checks the result of the `ssl:send/2` call and crashes (but there are some more complex scenarios when it doesn't do that and keeps running). Nevertheless, tracing for the messages sent between the processes reveals that no `ssl_error` message is sent:

```erlang
21:26:28:852089 (PidOfEpgsql) << {'$gen_call',{PidOfEShell,#Ref<0.2023633026.1727528961.257471>},
                                              {command,epgsql_cmd_squery,"SELECT 1+1;"}}
21:26:28:852136 (PidOfEpgsql) PidOfTlsSnd ! {'$gen_call',
                                             {PidOfEpgsql,#Ref<0.2023633026.1727528961.257472>},
                                             {application_data,
                                              [<<81,0,0,0,16,83,69,76,69,67,84,32,49,43,49,59,0>>]}}
21:26:28:852152 (PidOfTlsSnd) << {'$gen_call',
                                     {PidOfEpgsql,#Ref<0.2023633026.1727528961.257472>},
                                     {application_data,
                                         [<<81,0,0,0,16,83,69,76,69,67,84,32,49,43,49,59,0>>]}}
21:26:28:852165 (PidOfTlsSnd) PidOfSslStm ! {'$gen_cast',
                                             {internal_renegotiate,
                                              #{beast_mitigation => one_n_minus_one,
                                                cipher_state => ...,
                                                client_verify_data => ...,
                                                compression_state => undefined,
                                                early_data_accepted => false,
                                                mac_secret => ...,
                                                max_fragment_length => undefined,
                                                pending_early_data_size => 16384,
                                                secure_renegotiation => true,
                                                security_parameters => ...,
                                                sequence_number => 5,
                                                server_verify_data => ...,
                                                trial_decryption => false}}}
21:26:28:852193 (PidOfSslStm) << {'$gen_cast',
                                  {internal_renegotiate,
                                   #{beast_mitigation => one_n_minus_one,
                                     cipher_state => ...,
                                     client_verify_data => ...,
                                     compression_state => undefined,early_data_accepted => false,
                                     mac_secret => ...,
                                     max_fragment_length => undefined,
                                     pending_early_data_size => 16384,
                                     secure_renegotiation => true,
                                     security_parameters => ...,,
                                     sequence_number => 5,
                                     server_verify_data => ...,
                                     trial_decryption => false}}}
21:26:28:852511 (PidOfSslStm) << {inet_reply,#Port<0.20>,ok}
21:26:28:902615 (PidOfSslStm) << {tcp,#Port<0.20>,<<...>>}
21:26:28:903565 (PidOfSslStm) << {tcp_closed,#Port<0.20>}
21:26:28:903577 (PidOfSslStm) getting_unlinked #Port<0.20>
21:26:28:905022 (PidOfSslStm) << timeout
21:26:28:905052 (PidOfSslStm) ssl_manager ! {'$gen_cast',{invalidate_session,AuroraHostIp,5552,...}}
21:26:28:905461 (PidOfSslStm) <0.83.0> ! {'$gen_cast',
                                             {'$olp_load',
                                                 <<"=NOTICE REPORT==== 22-Jun-2023::15:17:00.324913 ===\nTLS client: In state hello received SERVER ALERT: Fatal - No Renegotiation\n">>}}
21:26:28:905570 (PidOfSslStm) <0.80.0> ! {'$gen_cast',
                                             {'$olp_load',
                                                 <<"=NOTICE REPORT==== 22-Jun-2023::15:17:00.324913 ===\nTLS client: In state hello received SERVER ALERT: Fatal - No Renegotiation\n\n">>}}
21:26:28:905617 (PidOfSslStm) << timeout
21:26:28:905626 (PidOfSslStm) exit {shutdown,normal}
21:26:28:905674 (PidOfTlsSnd) << {'EXIT',PidOfDynSup,shutdown}
21:26:28:905688 (PidOfTlsSnd) exit shutdown
21:26:28:905714 (PidOfEpgsql) << {'DOWN',#Ref<0.2023633026.1727528961.257472>,process,PidOfTlsSnd,
                                         shutdown}
```

I changed the raw pids to variable names in the trace for readability:
* `PidOfEShell`: the pid of the Erlang shell from which I executed the commands.
* `PidOfEpgsql`: the pid of the `epgsql_sock` process.
* `{sslsocket,{gen_tcp,#Port<0.20>,tls_connection,undefined},[PidOfSslStm,PidOfTlsSnd]}` is the ssl socket.

**Comment by IngelaAndin** [comment]
A lot happened since that version, if you could test it on the latest version OTP-26.0.2 to see if this is still a problem that would be nice.  And if it still is a problem a small test case reproducing the issue will help getting the solution prioritized.

**Comment by IngelaAndin** [comment]
@dszoboszlay I just noticed that you seem to be setting a socket option active that is not an ssl applitcation option but rather an option of epgsql. On the other hand an active socket is default for the ssl application. But you should perhaps check if epgsql sets any of its own values on the ssl socket.  And is the esgsql option somthing that it applies to the ssl socket or there some othe socket involved?

**Comment by IngelaAndin** [comment]
@dszoboszlay  Thank you for providing a way to reproduce.  Your script will no result in:

```
client error: {tls_alert,
                  {no_renegotiation,
                      "TLS client: In state hello received SERVER ALERT: Warning - No Renegotiation\n"}}
```
