### ISSUE TITLE
`/=` against bitstrings in guards behaves differently between x86 and ARM

### ISSUE THREAD

**Issue by the-mikedavis** [erlang/otp#7433]
**Describe the bug**

Checking `/=` against a bitstring appears to behave differently on ARM and x86 processors starting in OTP26 in some scenarios. On x86 the check works as expected but on ARM the check doesn't seem to be run at all.

**To Reproduce**

```erl
%% frame.erl
-module(frame).

-export([translate/1]).

translate({text, <<Reserved/bitstring>>, _Data}) when Reserved /= <<0:3>> ->
    {error, {malformed_reserved, Reserved}};
translate({binary, <<Reserved/bitstring>>, _Data}) when Reserved /= <<0:3>> ->
    {error, {malformed_reserved, Reserved}};
translate({binary, _Reserved, Data}) ->
    {binary, Data};
translate({text, _Reserved, Data}) ->
    {text, Data}.
```

In a shell session:

```erl
> c(frame).
%% ARM:
> frame:translate({text,<<0:3>>,<<"hello">>}).
{error,{malformed_reserved,<<0:3>>}}
> frame:translate({text,<<1:3>>,<<"hello">>}).
{error,{malformed_reserved,<<1:3>>}}
> <<R/bitstring>> = <<0:3>>, R /= <<0:3>>.
false
%% x86:
> frame:translate({text,<<0:3>>,<<"hello">>}).
{text,<<"hello">>}
> frame:translate({text,<<1:3>>,<<"hello">>}).
{error,{malformed_reserved,<<1:3>>}}
> <<R/bitstring>> = <<0:3>>, R /= <<0:3>>.
false
```

**Expected behavior**

The first call to `frame:translate/1` above should return `{text,<<"hello">>}` on ARM as it does on x86.

**Affected versions**

It looks like this bug appeared in OTP26: I can't reproduce this in OTP25. I can also reproduce it on master as of 0e823241cdece4f9af42845a40802606e7796121.

**Comment by mikpe** [comment]
Can you clarify what you mean by "ARM": 64-bit or 32-bit? They're _very_ different animals.

**Comment by the-mikedavis** [comment]
Ah sorry, I mean 64-bit. I am reproducing this on a macbook with apple silicon.
