### ISSUE TITLE
erl argument "-shutdown_time" sometimes have no effect

### ISSUE THREAD

**Issue by toffea** [erlang/otp#7439]
**Describe the bug**
During circumstances described in #7438 the `erl` argument `-shutdown_time` has no effect. 

**To Reproduce**
See #7438 for details, but also set `-shutdown_time` timeout while starting the nodes. 

**Expected behavior**
That `-shutdown_time` should have effect while vm is hanging during `init:stop()` or `erlang:halt()`.

**Affected versions**
Same as #7438 (`25.1.2`, `25.3.2.2` and `26.0.1`).

**Additional context**
Please see details in #7438

**Comment by toffea** [comment]
Howdy OTP-team,

any progress in making `-shutdown_time` have effect when hosts within a "distributed" cluster is disconnected (network wise) from each other? 

Thx
/Toffe

**Comment by rickard-green** [comment]
The `-shutdown_time` parameter sets a limit on how long Erlang applications are allowed to shut down before being brutally taken down. That is, it does not include time for other operations included in `init:stop()` etc. I've changed the wording in the documentation describing the parameter to make it a bit more obvious what it is for in the #8035 PR.
