### ISSUE TITLE
[Windows]: malformed io:format result for <<X>> where X <- [160, 254]

### ISSUE THREAD

**Issue by foldl** [erlang/otp#7442]
**Describe the bug**

`io:format()` within `erl.exe` on Windows gives malformed binary output for `<<X>>` where `X <- [160, 254]`.

**To Reproduce**

For example,

```erlang
1> io:format("~p~n", [<<160>>]).
<<"?>>
ok
```

Where `<<"?>>` is not even a valid term.

**Expected behavior**

Consistent behavior between `erl` and `werl` is preferred.

Bottom line: it should be a valid term.

**Affected versions**

`erl.exe` on Windows: OTP 25.3.2, OTP 25.3.2.2

**Additional context**

In `werl.exe` of these versions it is OK.

I have not tested OTP 25.3.2.1, but I think it is affected too.

**Comment by garazdawi** [comment]
The shell on Windows has gotten a lot of fixes and changes in OTP 26.0. I just tried it and your examples work as expected there, could you try and see if they also work for you?

**Comment by foldl** [comment]
OTP 26.0 is not affected.

**Comment by garazdawi** [comment]
Great!

**Comment by foldl** [comment]
I think OTP-25 is still supported. Maybe this should be fixed in another upcoming patch?

**Comment by garazdawi** [comment]
Since it works in `werl` pre-OTP-26 and in OTP-26 we will not spend any time on fixing it. You are welcome to submit a PR with a fix+testcase and I can put it into a patch for 25.
