### ISSUE TITLE
OTP 24.3.4.13 release is missing MD5 and SHA256 files

### ISSUE THREAD

**Issue by RoadRunnr** [erlang/otp#7463]
**Describe the bug**

OTP releases are usually accompanied by MD5 and SHA256 files to be able to validate the content of the downloaded files. The OTP 24.3.4.13 release is missing those files.

**To Reproduce**

check https://github.com/erlang/otp/releases/tag/OTP-24.3.4.13

**Expected behavior**

MD5 and SHA256 files for the OTP 24.3.4.13 release.
**Affected versions**

OTP 24.3.4.13

**Comment by garazdawi** [comment]
Thanks for the report! Should be fixed now. Was due to some failure in github actions that we have no control over.
