### ISSUE TITLE
[erlc] internal consistency check failed: ambiguous_catch_try_state

### ISSUE THREAD

**Issue by RobinMorisset** [erlang/otp#7477]
**Describe the bug**
Running erlc on the following:
```erlang
f() ->
    try
        erlang:monotonic_time()
    after
        catch (<<>> = size(catch (([_ | _V4] = _V4) = ok)))
    end.
```
results in the following error:
```
test150083:1: function f/0+30:
  Internal consistency check failed - please report this bug.
  Instruction: {gc_bif,size,{f,0},1,[{x,0}],{x,0}}
  Error:       ambiguous_catch_try_state:
```

**Affected versions**
- master + #7474
- maint + #7448
- at least one old version of OTP 25

I've not checked other versions, but this suggests that this is not a new bug

**Additional context**
I suspect that this may be related to #7342, but it has never caused that error message, so I am reporting it in case it is in fact different.

**Comment by bjorng** [comment]
It is in fact different from #7342; it is an unsafe optimization done by `beam_jump`.
