### ISSUE TITLE
erlang:after_send possible scaling issue

### ISSUE THREAD

**Issue by mrchenfenglin** [erlang/otp#7480]
**Describe the bug**
Running 2000 Erlang processes on certain cloud service providers, where the processes are simply looping through erlang:send_after/3 calls, with two loops - one every 1 second, and the other every 125 milliseconds. 

**To Reproduce**
1.  linux command $: erl
2. erlang command 1>: processTest:testProcess(2000).
After following the above two steps, there is a chance that the CPU and load on the Linux system will become high. If it doesn't happen in the first attempt, you can try running it multiple times by exiting the Erlang shell and starting it again. Based on my own experience, out of 10 attempts, there is a high likelihood of encountering a situation with high system load.

**Expected behavior**
I believe high system load should not occur. I contacted the technical support of the cloud service provider, and their response was that it is caused by thread lock contention, leading to high system load.
When high system load occurs, invoking erlang:system_flag(schedulers_online, 1) helps reduce the system load. I believe this could be attributed to lock contention caused by erlang:send_after when multiple schedulers are involved in calling different Erlang processes. Currently, my system requires multiple schedulers_online. I hope the OTP team can address this issue and provide a response. I am extremely grateful for your attention.

**Affected versions**
versions：OTP25 erts-13.1.2，Erlang/OTP 23 erts-11.2.2.18

**Additional context**
code:
`%% @author Administrator
%% @doc @todo Add description to armyMod.

-module(processTest).
-behaviour(gen_server).
-export([init/1, handle_call/3, handle_cast/2, handle_info/2, terminate/2, code_change/3]).

%% ====================================================================
%% API functions
%% ====================================================================
-export([start/0,
testProcess/1]).

testProcess(N) when N < 1->
    ok;
testProcess(N) ->
    start(),
    testProcess(N-1).

%% ====================================================================
%% Behavioural functions
%% ====================================================================

start() ->
    {ok, Pid} = gen_server:start(?MODULE, [], []),
    Pid.

init([]) ->
    %% 125ms 
    erlang:send_after(125, self(), {'loop', 0}),
    erlang:send_after(1000, self(), {'fightLoop'}),
    {ok, []}.

handle_call(_Info, _From, State) ->
    {reply, ok, State}.

handle_cast(_Msg, State) ->
    {noreply, State}.

handle_info({'loop', Last}, State) ->
    erlang:send_after(125, self(), {'loop', Last}),
    {noreply, State};

handle_info({'fightLoop'}, State) ->
    erlang:send_after(1000, self(), {'fightLoop'}),
    {noreply, State}.

%% ====================================================================
terminate(_Reason, _State) ->
    ok.

code_change(_OldVsn, State, _Extra) ->
    {ok, State}.

`

**Comment by jhogberg** [comment]
As this only happens on "certain cloud service providers" it will be very difficult for us to reproduce it.

Please make a `perf` recording of the offending behavior as described in the [manual](https://github.com/erlang/otp/blob/master/erts/emulator/internal_doc/BeamAsm.md#linux-perf-support), and upload the result of `perf report > report.txt` somewhere where we can see it. Making the recording as root would be preferable as said lock contention may very well be in the kernel.

**Comment by mrchenfenglin** [comment]
> As this only happens on "certain cloud service providers" it will be very difficult for us to reproduce it.
> 
> Please make a `perf` recording of the offending behavior as described in the [manual](https://github.com/erlang/otp/blob/master/erts/emulator/internal_doc/BeamAsm.md#linux-perf-support), and upload the result of `perf report > report.txt` somewhere where we can see it. Making the recording as root would be preferable as said lock contention may very well be in the kernel.

I am from China, and I am using Tencent Cloud. I can reproduce the issue directly in my environment. Could you please provide an SSH public key so that I can grant you access and allow you to investigate?

**Comment by jhogberg** [comment]
I cannot. Please provide the requested `perf` report.

**Comment by mrchenfenglin** [comment]
> 我不能。请提供所要求的`perf`报告。

https://ghzslg-cdn.gameone.com/ghzResources/Android/perf.data  我把报告放在这里了 希望你们能去下载分析，万分感谢

这个报告的代码是这样的
`%% @author Administrator
%% @doc @todo Add description to armyMod.

-module(processTest).
-behaviour(gen_server).
-export([init/1, handle_call/3, handle_cast/2, handle_info/2, terminate/2, code_change/3]).

%% ====================================================================
%% API functions
%% ====================================================================
-export([start/1,
testProcess/1]).

-record(state,{i = 0,time = 0}).


testProcess(N) when N < 1->
    ok;
testProcess(N) ->
    start(N),
    testProcess(N-1).


%% ====================================================================
%% Behavioural functions
%% ====================================================================

start(N) ->
    {ok, Pid} = gen_server:start(?MODULE, [N], []),
    Pid.

init([N]) ->
    %% 125ms 
    erlang:send_after(125, self(), {'loop', 0}),
    erlang:send_after(1000, self(), {'fightLoop'}),
    Time = long_unixtime(),
    State = #state{i = N,time = Time},
    {ok, State}.

handle_call(_Info, _From, State) ->
    {reply, ok, State}.

handle_cast(_Msg, State) ->
    {noreply, State}.


handle_info({'loop', Last}, State = #state{i = I,time = Time}) ->
    Last2 = Last + 1,
    Time2 = long_unixtime(),
    LoopTime = 25,
    case I == 1 andalso Last2 rem (1000 div LoopTime) of
        0 ->
            io:format("use time:~w~n",[Time2 - Time]),
            State2 = State#state{time = Time2};
        _ ->
            State2 = State
    end,
    erlang:send_after(LoopTime, self(), {'loop', Last2}),
    {noreply, State2};

handle_info({'fightLoop'}, State) ->
    erlang:send_after(1000, self(), {'fightLoop'}),
    {noreply, State}.


%% ====================================================================
terminate(_Reason, _State) ->
    ok.


code_change(_OldVsn, State, _Extra) ->
    {ok, State}.


long_unixtime() ->
    {M,S,MM} = os:timestamp(),
    M * (1000000 * 1000) + S * 1000 + MM div 1000.
`

**Comment by jhogberg** [comment]
I cannot read that. Please run `perf report > report.txt` and upload `report.txt`.

**Comment by mrchenfenglin** [comment]
> I cannot read that. Please run `perf report > report.txt` and upload `report.txt`.
I'm sorry I didn't follow your request before. This is the latest report：
https://github.com/mrchenfenglin/erlangError/blob/main/report.txt

**Comment by jhogberg** [comment]
Can you make another recording with `perf record --call-graph=fp` ?

**Comment by mrchenfenglin** [comment]
> Thank you. Can you make another recording with `perf record --call-graph=fp` ?

ok, a little later. I have already provided more information.
https://github.com/mrchenfenglin/erlangError/tree/main
thanks

**Comment by mrchenfenglin** [comment]
> Thank you. Can you make another recording with `perf record --call-graph=fp` ?
`perf record --call-graph=fp`  report 
https://github.com/mrchenfenglin/erlangError/tree/main/perf_record_call_graph_fp
thank you very much

**Comment by jhogberg** [comment]
Thank you, this looks relatively normal, from your description I was expecting far more of a difference.

It appears to be spending a lot of time busy-waiting for work. Try playing around with the scheduler busy-wait time option (+sbwt).

**Comment by mrchenfenglin** [comment]
> Thank you, this looks relatively normal, from your description I was expecting far more of a difference.
> 
> It appears to be spending a lot of time busy-waiting for work. Try playing around with the scheduler busy-wait time option (+sbwt).

The system load situation triggering the bug is abnormal:
https://github.com/mrchenfenglin/erlangError/blob/main/perf_record_call_graph_fp/report_high_load.png

If I invoke erlang:system_flag(schedulers_online, 1), the system load decreases. I have also tried increasing the Time parameter of erlang:send_after/3, for example, setting it to 2 seconds, and the system load also decreases.


This is the system load situation where the bug is not triggered:
https://github.com/mrchenfenglin/erlangError/blob/main/perf_record_call_graph_fp/report_low_load.png

Both invocations are using the same code:
https://github.com/mrchenfenglin/erlangError/blob/main/processTest.erl.


Both invocations execute processTest:testProcess(10000).

I am confident that there is an issue. When the system load is high, I sought technical support from the cloud service provider, and they provided me with information stating that the system is spending more time on thread switching or intense thread contention, leading to frequent thread state changes.

Currently, in order to keep the system running smoothly, I have forcibly set erlang:system_flag(schedulers_online, 1). However, this approach quickly reaches the limit of a single core. I need multiple schedulers to work simultaneously in order to operate efficiently.

I need your help, and I am extremely grateful.

**Comment by jhogberg** [comment]
We’re looking at a change of about 10%, which is in no way abnormal for this situation, which you would see in any language due to the nature of it.

You are asking a lot of different things to run at specific points in time, _and you have no useful work being done between those events_. This causes the threads to sleep in between from a lack of work to do, because there’s a limit to how long it makes sense to burn CPU time doing nothing in the hope that work arrives (+sbwt controls this aspect).

That the problem is worse in the cloud is not surprising at all as timing precision falls off a cliff in virtualized environments.

As far as I can tell there is no issue at all here other than with your application. Luckily, this issue is actually not a problem outside of the exact conditions that cause it: _increasing the amount of work being done_ to the point where the threads no longer go to sleep out of a lack of work makes the “problem” go away.

This is what happens when you set the number of online schedulers to 1: it is now so busy that it no longer needs to go sleep in between each timer event.

**Comment by mrchenfenglin** [comment]
> We’re looking at a change of about 10%, which is in no way abnormal for this situation, which you would see in any language due to the nature of it.
> 
> You are asking a lot of different things to run at specific points in time, _and you have no useful work being done between those events_. This causes the threads to sleep in between from a lack of work to do (edit: with associated costs for sleeping and waking up again later: these are the thread state changes they’re talking about), because there’s a limit to how long it makes sense to burn CPU time doing nothing in the hope that work arrives (+sbwt controls this aspect).
> 
> That the problem is worse in the cloud is not surprising at all as timing precision falls off a cliff in virtualized environments.
> 
> As far as I can tell there is no issue at all here other than with your application. Luckily, this issue is actually not a problem outside of the exact conditions that cause it: _increasing the amount of work being done_ to the point where the threads no longer go to sleep out of a lack of work makes the “problem” go away.
> 
> This is what happens when you set the number of online schedulers to 1: it is now so busy that it no longer needs to go sleep in between each timer event.

Indeed, the CPU usage rates do not differ significantly. What I was referring to is the system load, which differs by several orders of magnitude.
Have you noticed this situation?
linux top command  "load average" label

I can see from the two images in my previous response that there shouldn't be such a significant difference under normal circumstances. Moreover, it doesn't resemble the 10% difference you mentioned.

noarml  "load average" -> 0.48
https://github.com/mrchenfenglin/erlangError/blob/main/perf_record_call_graph_fp/report_low_load.png

bug "load average" -> 6.79
https://github.com/mrchenfenglin/erlangError/blob/main/perf_record_call_graph_fp/report_high_load.png

**Comment by jhogberg** [comment]
> What I was referring to is the system load, which differs by several orders of magnitude.

Which is entirely normal for the reasons I described.
