### ISSUE TITLE
call of overloaded 'AddTool' function is ambiguous when installing Erlang OTP 24.x versions 

### ISSUE THREAD

**Issue by SyedMuhamadYasir** [erlang/otp#7514]
**Describe the bug**
`gen/wxe_wrapper_7.cpp: In function 'void wxToolBar_AddTool_4(WxeApp*, wxeMemEnv*, wxeCommand&)':
gen/wxe_wrapper_7.cpp:2342:65: error: call of overloaded 'AddTool(int&, wxString&, wxBitmap&, wxString&, wxItemKind&)' is ambiguous
 2342 |   wxToolBarToolBase * Result = (wxToolBarToolBase*)This->AddTool(toolId,label,*bitmap,shortHelp,kind);
      |                                                    ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

![image](https://github.com/erlang/otp/assets/30082863/8c6764d0-510e-4794-b7fc-37d7881dfcb5)

**To Reproduce**
simply build Erlang OTP 24 or 24.3.4.13 from source OR through Kerl, doesn't matter and its the same error !

**Expected behavior**
A smooth Install 

**Affected versions**
OTP 24.0 and also 24.3.4.13

**Additional context**

**Comment by garazdawi** [comment]
You can set `KERL_CONFIGURE_DISABLE_APPLICATIONS=wx` before running kerl. That will disable wx and should get you up and running.

I don't know much about how wx works, but know that we have had issues in the past where they changed something in an API that made our version no longer compile. What version of wx widgets are you using?

**Comment by SyedMuhamadYasir** [comment]
> You can set `KERL_CONFIGURE_DISABLE_APPLICATIONS=wx` before running kerl. That will disable wx and should get you up and running.
> 
> I don't know much about how wx works, but know that we have had issues in the past where they changed something in an API that made our version no longer compile. What version of wx widgets are you using?

thank you, i might try that - however, i need to know if blockscout will work without wxwidgets.

as for the version for wxWidgets, i am using `wxWidgets-3.2.2.1`

**Comment by SyedMuhamadYasir** [comment]
@garazdawi , so i tried by disabling wx and i got this 👍 
![image](https://github.com/erlang/otp/assets/30082863/2bf7c4a5-116c-472d-a37f-422e1274c4f3)

any advices ?

**Comment by garazdawi** [comment]
You are building Erlang 24.0 which was released May 2021 on an OS that was released April 2022. Try with latest 24 patch release instead and see if that works for you.

From the error message there seems to be something wrong with crypto, which leads me to think you have openssl 3 installed. OpenSSL 3 was first supported in Erlang 25, so if you insist on using Erlang 24 you will need to install an older openssl version.

**Comment by SyedMuhamadYasir** [comment]
> You are building Erlang 24.0 which was released May 2021 on an OS that was released April 2022. Try with latest 24 patch release instead and see if that works for you.
> 
> From the error message there seems to be something wrong with crypto, which leads me to think you have openssl 3 installed. OpenSSL 3 was first supported in Erlang 25, so if you insist on using Erlang 24 you will need to install an older openssl version.

Thank you ! you have been immensely helpful ! 

Yes i have openssl 3 installed, but i will try an older version of openssl ( which one do you recommend ? )

I tried doing so with the latest Erlang 24 patch (24.3.4.13) and there's another error

i cannot disable wx because Blockscout uses wx - i will install an older version of openssl but i don't see any openssl errors in my latest attempt ( please see screenshot below )

![image](https://github.com/erlang/otp/assets/30082863/9dbc5073-e872-46dc-b98a-9c3ea710a939)

**Comment by garazdawi** [comment]
My guess would be that you are using a too new wxwidget version. Try installing an older version and compile with that.

**Comment by dgud** [comment]
This is fixed in OTP-25, so either upgrade OTP or downgrade to an older wxWidgets.
