### ISSUE TITLE
OTP26: gen_statem:start_link is not linked properly with process during init()

### ISSUE THREAD

**Issue by attah** [erlang/otp#7524]
**Describe the bug**
If init() in my gen_statem returns {stop, ...} or even exit()s, the caller of start_link is not notified.
This works on OTP25 but not OTP26(.0.2).

**To Reproduce**
```
-module(init_error_test).
-behaviour(gen_statem).
-export([test/0, callback_mode/0, init/1]).

callback_mode() ->
    state_functions.

init({}) ->
    io:format("Hello from init/1 @~p ~p~n",
              [self(), erlang:process_info(self(), links)]),
    % exit(schmerror),
    {stop, schmerror}.

test() ->
    io:format("test/0 pid is: ~p~n", [self()]),
    process_flag(trap_exit, true),
    {error, schmerror} =
        gen_statem:start_link({local, my_statem}, ?MODULE, {}, []),
    receive
        {'EXIT', _, Err} ->
            io:format("Got EXIT: ~p~n", [Err])
    after 1234 ->
        io:format("No EXIT for you!~n")
    end.
```

**Expected behavior**
'EXIT' is received.

**Affected versions**
OTP26

**Additional context**
OTP25:
```
test/0 pid is: <0.90.0>
Hello from init/1 @<0.130.0> {links,[<0.90.0>]}
Got EXIT: schmerror
=CRASH REPORT==== 2-Aug-2023::12:43:46.511362 ===
  crasher:
    initial call: init_error_test:init/1
    pid: <0.130.0>
    registered_name: []
    exception exit: schmerror
      in function  gen_statem:init_result/8 (gen_statem.erl, line 1041)
    ancestors: [<0.90.0>]
    message_queue_len: 0
    messages: []
    links: [<0.90.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 376
    stack_size: 28
    reductions: 175
  neighbours:

ok

```

OTP26:
```
test/0 pid is: <0.86.0>
Hello from init/1 @<0.93.0> {links,[<0.86.0>]}
=CRASH REPORT==== 2-Aug-2023::12:43:38.687024 ===
  crasher:
    initial call: init_error_test:init/1
    pid: <0.93.0>
    registered_name: []
    exception exit: schmerror
      in function  gen_statem:init_result/8 (gen_statem.erl, line 1005)
    ancestors: [<0.86.0>,<0.85.0>,<0.71.0>,<0.66.0>,<0.70.0>,<0.65.0>,
                  kernel_sup,<0.47.0>]
    message_queue_len: 0
    messages: []
    links: [<0.86.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 376
    stack_size: 28
    reductions: 177
  neighbours:

No EXIT for you!
ok

```

Failing in 'enter' on a state etc, works as expected still.
We don't particularly need/want to faff with trapping and receiving 'EXIT', but that's what you had to do before, so that's what our code does.
And a link is a link.

**Comment by attah** [comment]
Okay, that's nice... but why was {error, ...} just added then, seemingly addressing just he case when you didn't want the caller torn down?

So a good compatibility construct is unlink() and receiving 'DOWN' with a 0 timeout?

**Comment by RaimoNiskanen** [comment]
I guess `-ifdef` is the only solution.  If the server `init/1` returns `{stop|error,_}` then pre-OTP-26.0 the caller got an `'EXIT'` signal, that may arrive after `gen_statem:start_link/3,4` returned, but in OTP-26.0 there is no `'EXIT'` signal.

Sorry about that!
We wanted to make the init error behaviour consistent, so we made the change in a major release...

Note: returning `{stop,normal}` or `ignore` does not generate an `'EXIT'` signal in any release, and calling `exit(Reason)` will make `start_link` return `{error,Reason}` and produce and error report, but no `'EXIT'` signal in any release.

**Comment by attah** [comment]
Well, i do like the new behaviour, but i have to make the code work in both. 

> and calling exit(Reason) will make start_link return {error,Reason} and produce and error report, but no 'EXIT' signal in any release.

No, i don't believe that is correct. (Uncomment the exit in my example).

**Comment by RaimoNiskanen** [comment]
Please have a look at my suggested documentation change for `gen_statem`

**Comment by RaimoNiskanen** [comment]
The documentation improvements have been merged.
Thank you for pointing this out!

**Comment by attah** [comment]
Thanks for the quick and comprehensive fix.
