### ISSUE TITLE
gen_tcp:connect/2 crashes with {inet_backend, socket}

### ISSUE THREAD

**Issue by alexeyshch** [erlang/otp#7530]
**Describe the bug**
`gen_tcp:connect/2` crashes with the following error:
```erlang
1> gen_tcp:connect(#{port => 80, addr => {127, 0, 0, 1}, family => inet}, [{inet_backend, socket}]). 
** exception error: undefined function gen_tcp_socket:connect/3
```
Without `{inet_backend, socket}` it works as expected:
```erlang
1> gen_tcp:connect(#{port => 80, addr => {127, 0, 0, 1}, family => inet}, []). 
{ok,#Port<0.5>}
```

**Affected versions**
OTP 26.0.2

**Comment by RaimoNiskanen** [comment]
The bug seems to have been introduced in OTP-24.3, ticket OTP-17455, b12fd38c46d852c62708e40fb5ed52ba98fa938d

**Comment by bmk** [comment]
Fix for this issue has been merged into maint (and master).
Patches with this fix will (eventually) be released as: 24.3.4.14, 25.3.2.6 and 26.0.3

**Comment by bmk** [comment]
OTP 26.1 has now been released.

**Comment by bmk** [comment]
OTP 24.3.4.14 has now been released.
