### ISSUE TITLE
Allow for an alternative ct_config in Common Test

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlang/otp#7540]
(I searched the Issues and Pull requests for `ct`, `common_test`, `config`, and variants of these, and found no information related to what I'm about to write)

---

**Is your feature request related to a problem? Please describe.**

At the moment, `ct_suite` forces the `ct_config/0` type to be `[{Key :: atom(), Value :: term()}]`, as used by `init/end_per_suite/1`, `init/end_per_group/2`, and `init/end_per_testcase/2`, ...

I feel fetching elements from that list is not as elegant/simple as e.g. pattern matching on an argument map.

**Describe the solution you'd like**

I'd prefer `ct_config/0` to be more loose (I didn't look into the implementation, so don't know if config. elements are used internally - or how "difficult" implementation would be), e.g. a map, or whatever the consumer decides it should be (either via an option - to keep backward compatibility) or by whatever is returned from the first function that would "define" it (e.g. `init_per_suite/1` or `init_per_group/2`).

**Describe alternatives you've considered**

None, as of yet.

**Additional context**

Here's an example that illustrates my proposal (though it doesn't deal with the "initialisation" of the Config. as a list or a map).

```erlang
% as is
-module(ex1_SUITE).

-export([all/0, init_per_suite/1, end_per_suite/1, my_testcase/1]).

all() -> [my_testcase].

init_per_suite(C) -> [{my_option_key1, my_option_value1},
                      {my_option_key2, my_option_value2}
                      | C].

end_per_suite(C) -> C.

my_testcase(C) ->
  my_option_value1 = proplists:get_value(my_option_key1, C),
  my_option_value2 = proplists:get_value(my_option_key2, C).
```

```erlang
% as would be
-module(ex1_SUITE).

-export([all/0, init_per_suite/1, end_per_suite/1, my_testcase/1]).

all() -> [my_testcase].

init_per_suite(C) -> #{my_option_key1 => my_option_value1,
                       my_option_key2 => my_option_value2,
                       config => C}.

end_per_suite(C) -> C.

my_testcase(#{my_option_key := V1, my_option_key2 := V2}) ->
  V1 = my_option_value1,
  V2 = my_option_value2.
```

**Comment by essen** [comment]
I would second using a map if it was to be written today. Not sure a change is necessary though, some people use `?config(...)`, personally I use my own imported `config(...)` function, and those are not too different from a `maps:get`. The only thing missing is the pattern matching but I don't know if it improves things much.

**Comment by paulo-ferraz-oliveira** [comment]
> I don't know if it improves things much.

I don't have hard-data to measure this one, unfortunately, but if I can pattern match to 10 different config. elements/keys (if using a map) instead of calling the same function 10 times, over the same input (or go through some other convoluted solution), I think it's a win for readability, at the very least.

In any case, my proposal is not to break compatibility, but rather allow for alternatives to be used. (not sure why the `Config` element is matched against a list, internally, but there's potentially good reasons for it).

**Comment by u3s** [comment]
We(@IngelaAndin @garazdawi ) discussed it at OTP team and seem to agree with @essen opinion.
It would be great feature if present from day 1 in CT, but probably not worth doing at this stage.

> I'd prefer ct_config/0 to be more loose (I didn't look into the implementation, so don't know if config. elements are used internally - or how "difficult" implementation would be), e.g. a map, 

Unfortunately Config is used in many places inside CT internal code, making it _more loose_ might be quite expensive to introduce and maintain.

At first glance, Config might seem like it's just user state term; intended to be saved and provided by OTP but being treated a bit opaque. But in practice it is not treated as opaque. Original code design was not prepared for a situation in which user can decide what Config could be. Instead CT internal code assumes Config is a list and manifests/leaks that expectation to API.

Sorry to write that, but we are leaning towards closing this issue with a comment.

**Comment by paulo-ferraz-oliveira** [comment]
@u3s, your reply serves not only as a good justification to keep existing behaviour but also document further questions of the same type. I'll go ahead and close this as I'm currently satisfied. Mind you, though, this would be (as per part of my proposal) a completely optional thing, so it wouldn't be good for retrofitting tests, for sure, but would be good (I believe) for newer ones.

Maybe I can fit a parse transform somewhere in my code and ease my frustration 😄

**Comment by u3s** [comment]
> @u3s, your reply serves not only as a good justification to keep existing behavior but also document further questions of the same type. I'll go ahead and close this as I'm currently satisfied. Mind you, though, this would be (as per part of my proposal) a completely optional thing, so it wouldn't be good for retrofitting tests, for sure, but would be good (I believe) for newer ones.

(From OTP perspective) even if optional for end user, we must try to make it as good as possible and maintain it for next OTP releases. 

We considered 2 approaches and didn't like any of them:
1. ConfigMap handled inside CT - too costly to implement, maintain
2. ConfigMap handled by some translation layer, but not inside CT - cheaper to implement and maintain, but having a performance penalty and never recommended for users concerned with performance

When evaluating this proposal, we also considered that:
- CT is already quite complex and loaded with configuration options
- this proposal would provide alternative way of realizing already supported functionality (not a brand new feature like option)

> Maybe I can fit a parse transform somewhere in my code and ease my frustration 😄

This might best solution in this case. Assuming you know how to write it and your don't mind limitations associated with parse transforms.

**Comment by riccardomanfrin** [comment]
Ended up here too.. happy to understand motivations for things... 
I guess I'll have to translate my json decode into tuplelists  ¯\_(ツ)_/¯
