### ISSUE TITLE
OTP26 sends terminal escape sequences over SSH, despite TERM=dumb

### ISSUE THREAD

**Issue by attah** [erlang/otp#7555]
**Describe the bug**
We have slightly augmented the OTP SSH client for convenience of our users.
This is tested against the OTP server/daemon, loaded with a fun to provide trivial replies.

**To Reproduce**
Have a fun replying trivial text data as 'shell' in daemon options.
(I'll look at making a code example, but hopefully it won't be necessary)

**Expected behavior**
Text delivered to client, as sent, +/- newlines.

**Affected versions**
OTP26

**Additional context**
We get <<"\r\n\e[1022D\e[1BourReplyHere ">>, as opposed to <<"\r\nourReplyHere ">>
Looks like it has to do with the introduction of the new shell, but i have not managed to track it down.

**Comment by frazze-jobb** [comment]
Please test my PR and see if it solves this issue.

**Comment by attah** [comment]
Preliminary tests says no. (PEBKAC still possible)
I'm somewhat surprised the proposed fix ended up in the client, as i thought the server was doing things wrong to dumb clients (like when we set that option in the otp client).
@u3s Did you manage to run our tests? (Since you already had access and knowledge)
I'm sorry if i was not clear enough... u3s seemed very on top of things.

**Comment by u3s** [comment]
Issue got hijacked from me before I tried to reproduce :-)
I can have a look tomorrow.

**Comment by u3s** [comment]
I've reproduced the issue. current form of #7627 removes some of unwanted characters but not all.

I will try to write a testcase in OTP repo reproducing that situation.

**Comment by u3s** [comment]
AFAIK, [dd137f](https://github.com/erlang/otp/pull/7627/commits/dd137f3a3712fa663741efeaea41dc3cc7f0bb0d) should fix the issue.
@attah can you confirm?

**Comment by attah** [comment]
Yes, can confirm, that fixes it.
