### ISSUE TITLE
Wrong binary data generated on Mac OS with OTP 26

### ISSUE THREAD

**Issue by ansd** [erlang/otp#7566]
**Describe the bug**
Wrong binary data is generated.

**To Reproduce**
Compile and run the following Erlang program `a.erl`:

```erl
-module(a).
-export([b/1]).

b(Bin) ->
    c(byte_size(Bin)).

c(N) ->
    <<(N rem 128), (N div 128)>>.
```

```
$ erl
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Eshell V14.0.2 (press Ctrl+G to abort, type help(). for help)
1> c(a).
{ok,a}
2> a:b(binary:copy(<<"a">>, 128)).
<<1,1>>
```

**Expected behavior**
```
2> a:b(binary:copy(<<"a">>, 128)).
<<0,1>>
```

**Affected versions**
OTP 26.0.2 on Mac M2.

**Additional context**
Seems unrelated to https://github.com/erlang/otp/issues/7469 as https://github.com/erlang/otp/pull/7471 does not fix this issue. Tested via
```
kerl build git https://github.com/jhogberg/otp.git john/erts/fix-bitstring-match-bug/GH-7469/OTP-18672 otp-7469-fix
```

**Comment by michaelklishin** [comment]
I can reproduce this on an M1 Mac as well.
