### ISSUE TITLE
ei_x_format (_wo_ver) can't handle map term

### ISSUE THREAD

**Issue by fregate** [erlang/otp#7598]
**Describe the bug**
In function https://github.com/erlang/otp/blob/d9fd6615141d2fc555b170fb47e71c8abcf19727/lib/erl_interface/src/misc/ei_format.c#L67
no case to encode map term

**To Reproduce**
```
	ei_x_buff buf;
	ei_x_new(&buf);
	int res = ei_x_format(&buf, "#{a=>1}"); // -1
```

**Expected behavior**
Map as a term in Erlang was introduced many versions ago and there is no support in ei library still.

**Affected versions**
Current and all previous

**Comment by fregate** [comment]
https://github.com/erlang/otp/pull/7602

**Comment by sverker** [comment]
PR #7602 merged.
