### ISSUE TITLE
inets mod_alias uses server_name directive for redirects instead of client-requested hostname

### ISSUE THREAD

**Issue by jchristgit** [erlang/otp#7617]
**Describe the bug**
When building a redirect, `mod_alias` uses the value of the `server_name` directive of the host, which may not match the host fragment originally opened by the user.

**To Reproduce**
Run the tests in `httpd_SUITE`, specifically the `alias` case, which prints the generated `Location` link:
```erl
*** User 2023-09-01 12:00:41.275 ***
RedirectLink = "http://httpd_test:39005/misc/"
```
Alternatively, set up a `httpd` server with `mod_alias` and cause a redirect, whilst having `server_name` be a non-reachable name. (I spotted this while working on tests for #7299)

**Expected behavior**
One of these:
- `server_name` should explicitly document that it is required to be the network-reachable hostname of the server (at the moment: "The name of your server, normally a fully qualified domain name.")
- ~~`mod_alias` redirects should reference the URL opened by the client for protocol, host and port in the redirect~~ (actually I'm not sure there is a reliable way to do this)
- `mod_alias` should build a relative redirect (above, I think it would be `Location: /misc/`) 

**Affected versions**
At least `master`, the code has been in there for a while though

**Additional context**
The redirect building code in question:
https://github.com/erlang/otp/blob/bbb84f33f13568e9308c6f2448d4e06ca6495488/lib/inets/src/http_server/mod_alias.erl#L64-L84

I would be happy to open a PR for this, would just need to know which expected behavior should be the new.

**Comment by IngelaAndin** [comment]
Well, we discussed this and I am afraid we might not have reached a final conclusion. But here is our thinking. Inets code is old an definitely based on RFC-2616 which says that the Location URI should be absolute.  However RFC-7231 (from 2014) that obsoletes RFC-2616 will allow it to be relative, that on the other hand is a not backwards compatible change.  Also changing the documentation to say that server_name has to be fully-qualified domain name may also sort of brake old use cases.  Could you please elaborate on why you discarded your middle option?

**Comment by essen** [comment]
Worth pointing out that the RFCs got updated when HTTP/3 came out (RFCs 9110 to 9114). But things didn't change concerning the Host header. HTTP/1.1 must send it. An HTTP/1.1 client can masquerade as HTTP/1.0 on occasion but should send it as well because modern servers expect it even if the version is HTTP/1.0. Both HTTP/2 and HTTP/3 send either the :authority (in the normal case) or the Host header (when translating an HTTP/1.1 request) and they are equivalent.

**Comment by IngelaAndin** [comment]
Well our thinking is now that we like to simplify things in this area as much as possible, and we like to evaluate the solution number three of using a relative redirect.  We are thinking that in practice this will not be a problem, but we will have to evaluate it further before finally deciding.  But having an implementation of that for master would be a first good step.
