### ISSUE TITLE
[:socket_closed_remotely] :httpc.request

### ISSUE THREAD

**Issue by apoorv-2204** [erlang/otp#7620]
**Describe the bug**
When trying to request an resource on internal ip, socket_closed remotely is returned, since there are not many res on internet that can help .
``` 
   root_url="http://192.168.1.1:52869/gatedesc.xml"
   query =String.to_charlist(root_url)
    :httpc.request(query)
   {:error, :socket_closed_remotely}

```

**To Reproduce**
trying to fetch internal resource , though working for HTTPPoision,

**Expected behavior**
It should return the xml page.

**Affected versions**
currently on 
elixir 1.14.1-otp-25
erlang 25.1.2

**Additional context**
https://github.com/apoorv-2204/elixir_nat/blob/d3ab80528a7684a98ebc9d8ab24bd3bf9b85dea6/lib/natex/nat_upnp_v1.ex#L210

**Comment by apoorv-2204** [comment]
https://erlangforums.com/t/socket-closed-remotely/2845/3

I will rework on this issue

**Comment by IngelaAndin** [comment]
@apoorv-2204 This might already have been solved by patch in OTP-25.3.1 have you checked that?

**Comment by apoorv-2204** [comment]
> @apoorv-2204 This might already have been solved by patch in OTP-25.3.1 have you checked that?
```
turned from httpc_manager:handle_info/2 -> {noreply,
                                                          {state,[],
                                                           httpc_manager__handler_db,
                                                           {cookie_db,
                                                            undefined,
                                                            #Ref<0.3602728524.41025548.170715>},
                                                           httpc_manager__session_db,
                                                           httpc_manager,
                                                           {options,
                                                            {undefined,[]},
                                                            {undefined,[]},
                                                            0,2,5,120000,2,
                                                            disabled,debug,
                                                            inet,default,
                                                            default,[],
                                                            undefined}}}
```

same for OTP-25.3.1 adn otp 26.0.1 and also otp 26.0.2

**Comment by apoorv-2204** [comment]
> @apoorv-2204 This might already have been solved by patch in OTP-25.3.1 have you checked that?

Any reason, or some explanation to understand why is this happening?

**Comment by IngelaAndin** [comment]
@apoorv-2204 the bug, that was fixed,  was a "pipeline/persistent connection"-queue handling bug which had the symptom that  `{error, socket_closed_remotely} ` was returned instead of appropriate HTTP response, which could happen in the OTP version that you reported the bug on. 

Now if there is another error that exist on that release on onwards (as you suggest above) it would very much help if you could provide a small erlang example to reproduce the error.

**Comment by apoorv-2204** [comment]
> @apoorv-2204 the bug, that was fixed, was a "pipeline/persistent connection"-queue handling bug which had the symptom that `{error, socket_closed_remotely} ` was returned instead of appropriate HTTP response, which could happen in the OTP version that you reported the bug on.
> 
> Now if there is another error that exist on that release on onwards (as you suggest above) it would very much help if you could provide a small erlang example to reproduce the error.

:httpc.request(“[http://192.168.1.1:52869/gatedesc.xml”|>String.to_charlist())

Requesting internal Resources , like xml description

**Comment by IngelaAndin** [comment]
@apoorv-2204  I was referring to making a runnable example to reproduce the error not knowing what the httpc:request/1 function call should look like!  For example see #6870

**Comment by apoorv-2204** [comment]
> @apoorv-2204 I was referring to making a runnable example to reproduce the error not knowing what the httpc:request/1 function call should look like! For example see #6870

https://github.com/apoorv-2204/elixir_nat/blob/d3ab80528a7684a98ebc9d8ab24bd3bf9b85dea6/lib/natex/nat_upnp_v1.ex#L210

- Turn on Upnpc on router
- mix deps.get 
- iex -S mix
- import Natex.NatupnpV1
- discover()

**Comment by IngelaAndin** [comment]
Would it be possible to provide it as Erlang and not Elixir? It could speed things up for the handling of this issue.

**Comment by starbelly** [comment]
I couldn't help but notice this issue 😄 I hope my comment helps @apoorv-2204. I think what's needed here is a way to reproduce the issue. The main thing is a simple `httpc:request/1` call, all the other elixir code doesn't matter, nor does the fact that it works in hackney (the implementations are completely different). 

Without access to your router and network (it's always possible there's something funky going on there vs just the webserver), it's very hard to reproduce. I think you're going to need to examine what happens and use an erlang web server to re-create the problem. Using httpc to gather the data needed to reproduce the issue, you could also use curl and have it dump everything to the screen, hopefully that would be enough to help reproduce the scenario. 

That's my two cents, and I hope it helps.

**Comment by IngelaAndin** [comment]
I am closing this for now, if anyone can reproduce feel free to reopen.
