### ISSUE TITLE
Aggressive deprecation period for 'peer'

### ISSUE THREAD

**Issue by eproxus** [erlang/otp#7629]
(This is not a code bug, more like a policy "bug" 🙂) 

**Describe the bug**
When using the `slave` module, the following warning is issued:
> Warning: `slave:start_link/3` is deprecated and will be removed in OTP 27; use the `peer` module instead

**To Reproduce**
Use the `slave` module and compile the code.

**Expected behavior**
A deprecation period of at least 3 supported versions **plus** one more.

**Affected versions**

26.0.2

**Additional context**
When wanting to support the same version span as Erlang/OTP formally supports ("the three latest major versions") it is problematic when a module is replaced by a library that was introduced in version 25 is completely removed in version 27 (or more formally, when it was introduced in version _V_ and will be removed in version _V_ + 2).

That leaves **no** migration window. As soon as OTP 27 is released, one is _forced_ to upgrade the code to be able to support that version. It would be nice with a soft deprecation that spans the three supported versions _plus one_ (version _V_ + 3).

With the current policy, it is not possible to start a migration _ahead_ of OTP 27 (because `peer` doesn't exist in OTP 24).

Please consider using a deprecation window of 3 supported major versions + 1 older major version to help maintainers upgrade without stress.

**Comment by wojtekmach** [comment]
> We can solve any problem by introducing an extra level of indirection.

Just wondering if on your app start you could check OTP version (or whether the module is available) and store in persistent term `{myapp, peer_mod}` with `peer` or `slave`. And one or couple OTP releases later remove the indirection.

**Comment by eproxus** [comment]
@wojtekmach Perhaps for this particular deprecation that would be possible. I cannot find any documentation stating that `peer` is API backwards compatible with `slave` though...

However, I think the policy in general is problematic for cases where you just can't replace one module with a new one promising to implement exactly the same API (which I'm sure `peer` doesn't guarantee, since there are many changes there).

**Comment by bjorng** [comment]
We will not change our general policy, but in this case there is no urgency in removing `slave`. Therefore, we will postpone the removal of `slave` to OTP 29.
