### ISSUE TITLE
`inet_gethost_native:gethostbyname/1` parses hostname as IP address

### ISSUE THREAD

**Issue by robertoaloi** [erlang/otp#7642]
**Describe the bug**
When `native` is used as the lookup method, the `inet_gethost_native` module is used behind the scenes.
If the hostname is numeric (e.g. `"12345"`), the hostname itself is parsed as if it was an IP address.

**To Reproduce**

```
inet_gethost_native:gethostbyname("12345").
{ok,{hostent,"12345",[],inet,4,[{0,0,48,57}]}}
```

**Expected behavior**
The above to return `{error, not_found}` or equivalent.

**Affected versions**
OTP 26.0

**Additional context**
This seems to be because:

```
<<A,B,C,D>> = <<12345:32>>.
<<0,0,48,57>>
```

Is there a way to circumvent this behaviour? I saw references to a `nostring` lookup option in [`inet_cfg`](https://www.erlang.org/doc/apps/erts/inet_cfg.html).

> The lookup method string tries to parse the hostname as an IPv4 or IPv6 string and return the resulting IP address. It is automatically tried first when native is not in the Methods list. To skip it in this case, the pseudo lookup method `nostring` can be inserted anywhere in the Methods list.

But that only applies for non-native resolution. Also (unless I'm doing something wrong), the `nostring` option does not seem to have an effect with different lookup methods:

```
$ cat /tmp/inetrc
{lookup, [file, nostring]}.
$ export ERL_INETRC=/tmp/inetrc
```

And, from the shell:

```
1> inet_db:res_option(lookup).
[file]
2> inet:gethostbyname("12345").
{ok,{hostent,"12345",[],inet,4,[{0,0,48,57}]}}
```

**Comment by bmk** [comment]
Hi,
Our expert is elsewhere at the moment, but from what I can see this is what the port program returns.
The man page also state that this function is obsolete:

      "The gethostbyname*(), gethostbyaddr*(), herror(), and hstrerror() func‐
       tions  are  obsolete.  Applications should use getaddrinfo(3), getname‐
       info(3), and gai_strerror(3) instead."

So I tried net:getaddrinfo("12345"), with the following result:

1> net:getaddrinfo("12345").
{ok,[#{type => stream,
       addr => #{port => 0,addr => {0,0,48,57},family => inet},
       family => inet,protocol => tcp},
     #{type => dgram,
       addr => #{port => 0,addr => {0,0,48,57},family => inet},
       family => inet,protocol => udp},
     #{type => raw,
       addr => #{port => 0,addr => {0,0,48,57},family => inet},
       family => inet,protocol => ip}]}

So I think its safe to say its something strange in the OS (this was on Ubuntu Linux).
But I had the same result on OpenIndiana.

/BMK

**Comment by starbelly** [comment]
It's a feature not a bug 😄 The underlying C functions at work can work with at least 3 (possibly) more types of inputs : 

1. Names (e.g,, `foo.bar`, `foo`, and so on). If it has a-z in it, it's probably a name.
2. Ip addrs (v4 and v6), no lookup is performed, you just get back a hostent structure. 
3. As you have found out, decimal representation of ip addresses. 

```erlang
1> inet_gethost_native:gethostbyname("2130706433").
{ok,{hostent,"2130706433",[],inet,4,[{127,0,0,1}]}}
``` 

Maybe it's worth documenting this?

**Comment by starbelly** [comment]
I forgot to say, this are all valid too : 

```erlang
1> inet_gethost_native:gethostbyname("0x7f000001").
{ok,{hostent,"0x7f000001",[],inet,4,[{127,0,0,1}]}}
2> inet_gethost_native:gethostbyname("127.0x1").
{ok,{hostent,"127.0x1",[],inet,4,[{127,0,0,1}]}}
3> inet_gethost_native:gethostbyname("0xDEADBEEF7f000001").
{ok,{hostent,"0xDEADBEEF7f000001",[],inet,4,[{127,0,0,1}]}}
```

**Comment by robertoaloi** [comment]
I guess it makes sense to consider it a "feature". I noticed this behaviour on a special case where the code wasn't using the "fully qualified" version of the host. So, closing this issue. Documenting some of the above could still be useful reference. Sorry about the noise!

**Comment by starbelly** [comment]
@robertoaloi  It makes for an interesting question, besides documentation. Should there be a function that only accepts one or maybe two types of input that acts like gethostbyname?

**Comment by bmk** [comment]
A small clarification *has* been added to the documentation of the inet:gethostbyname/1,2 functions.
Merged to maint and master. Not sure if it has been released yet.
