### ISSUE TITLE
Support of IP as hostname in erl running flags

### ISSUE THREAD

**Issue by gaoaiyong** [erlang/otp#7644]
**Is your feature request related to a problem? Please describe.**
When starting a erlang beam, we need to indicate flags for hostname.
Currently the flags only support -name and -sname.
But for IP, it does not seems like a short name or a long name due to hostname definition.
Currently we use workaround to set -name for IPs, but it seems incorrect in definition.

**Describe the solution you'd like**
Support erl flags for IP, e.g. -i

**Describe alternatives you've considered**

**Additional context**

**Comment by garazdawi** [comment]
I think using `-name` is a good way to do it. Maybe what is needed is an update in the docs? You can find the docs [here](https://github.com/erlang/otp/blob/master/erts/doc/src/erl_cmd.xml#L494-L526). A PR improving it would be most welcome.
