### ISSUE TITLE
Input is lost with erl -noshell -eval "shell:start_interactive()."

### ISSUE THREAD

**Issue by josevalim** [erlang/otp#7650]
When the shell is started interactively (because it has to be started by Elixir, rebar3, or something else), any previous input is lost (i.e. not read as part of the shell). It can be reproduced with these two scripts (save them to a file, `chmod +x FILE`, and run them):

### Working script

```
#!/usr/bin/expect
spawn erl
send "\"Hello World\".\n"
interact
```

The script above will send "Hello world" to the shell.

### Non-working script

```
#!/usr/bin/expect
spawn erl -noshell -eval "shell:start_interactive()."
send "\"Hello World\".\n"
interact
```

The script above will not send "Hello world" to the shell.

## Expected behavior

Perhaps it makes sense to read any buffered input when starting the shell? I am also fine if this is expected somehow, but I thought I would report.

## Affected versions

Erlang/OTP 26. Note this works fine if I use `-user` but I think starting the shell interactively is a better experience. :)

Thank you.

**Comment by garazdawi** [comment]
You need to use -noinput in such scenarios. The -noshell option is for when you want to start a system without a shell and then use `io:read` or something like that to get the data.

**Comment by garazdawi** [comment]
If you need to read input then you can do `shell:start_interactive(noshell)` after the system was started with `-noinput`.
