### ISSUE TITLE
`abs(-0.0)` returns `-0.0`

### ISSUE THREAD

**Issue by mkuratczyk** [erlang/otp#7654]
**Describe the bug**
```
1> abs(-0.0).
-0.0
```

**Expected behavior**
I'd expect the result to be `0.0`. All other languages I tried return "unsigned zero".

**Affected versions**
all versions (OTP from master, 26.0.2, 25.3)

**Comment by rickard-green** [comment]
Currently 0.0 and -0.0 are considered exactly equal in the language. This will however change as of OTP 27. See [upcoming incompatibilities in OTP 27](https://www.erlang.org/doc/general_info/upcoming_incompatibilities#0.0-and--0.0-will-no-longer-be-exactly-equal) in the documentation.

**Comment by rickard-green** [comment]
Reopening so we don't forget to fix this for OTP 27
