### ISSUE TITLE
Mac OS builds for Erlang/OTP releases

### ISSUE THREAD

**Issue by starbelly** [erlang/otp#7658]
**Is your feature request related to a problem? Please describe.**

Currently Mac OS builds are not provided along with [releases](https://github.com/erlang/otp/releases) on github. This can be particularly problematic when it comes to CI. Specifically, AFAIK most of the community depends on `brew` to install erlang for Mac OS CI workflows and jobs. 

This is sub-optimal as the `brew` method comes with a lot of dependencies, and as such has tendency to break. 

**Describe the solution you'd like**

The OTP has workflows to test building of Erlang/OTP and uploads this artifact, as such I believe it would be possible to at least attach the tarball when the release is created. Github actions such as [setup-beam](https://github.com/erlef/setup-beam) could utilize this artifact to ease usage in CI for the ecosystem, and of course people could just download and unpack as needed. 

**Describe alternatives you've considered**

It might be possible for parts of the community to take this on, but it feels quite natural per the above to keep it here. 

**Additional context**

Examples of recent failed builds in the community : 

[rebar3](https://github.com/erlang/rebar3/actions/runs/5985349038/job/16237347197)
[grisp toolchain](https://github.com/grisp/grisp2-rtems-toolchain/actions/runs/6050754288/job/16420710010)

**Comment by paulo-ferraz-oliveira** [comment]
@starbelly, it's worth mentioning @wojtekmach's work, in https://github.com/erlang/otp/pull/5723, so we're close 😄 

And I feel the pain, both for `rebar3` (updated CI recently to fix `brew`-related stuff: https://github.com/erlang/rebar3/pull/2826) and `setup-beam`, too (specifically https://github.com/erlef/setup-beam/issues/54).

**Comment by paulo-ferraz-oliveira** [comment]
As per what's mentioned in https://github.com/erlang/otp/pull/5723, maybe one solution could be to poll `erlang/otp`, build the image and store it in GitHub, as a first step?

**Comment by starbelly** [comment]
> As per what's mentioned in #5723, maybe one solution could be to poll `erlang/otp`, build the image and store it in GitHub, as a first step?

That's doable, if for some reason this is problematic here, that's definitely a viable alternative solution though. Thanks for calling it out!

**Comment by starbelly** [comment]
It's possible this should be closed as a duplicate. I totally forgot about that PR and the issue.
