### ISSUE TITLE
Fail to install erlang on debian bookworm

### ISSUE THREAD

**Issue by wxmeng04** [erlang/otp#7692]
**Describe the bug**
I cannot install erlang with .deb package download from official website. It depands on libssl1.1 but the defaut version is libssl3 with the distribution of debian bookwork (Debian 12). The same deb package can be installed on Debian 11. The download link is:
https://binaries2.erlang-solutions.com/debian/pool/contrib/e/esl-erlang/esl-erlang_26.0.2-1~debian~bullseye_amd64.deb
```
┌──(root💀debian)-[~]
└─# dpkg -i esl-erlang_26.0.2-1~debian~bullseye_amd64.deb 
Selecting previously unselected package esl-erlang.
(Reading database ... 50659 files and directories currently installed.)
Preparing to unpack esl-erlang_26.0.2-1~debian~bullseye_amd64.deb ...
Unpacking esl-erlang (1:26.0.2-1) ...
dpkg: dependency problems prevent configuration of esl-erlang:
 esl-erlang depends on libssl1.1; however:
  Package libssl1.1 is not installed.

dpkg: error processing package esl-erlang (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 esl-erlang
```

**To Reproduce**
Just install debian bookwork and test.

**Expected behavior**
To install successfully

**Affected versions**
26.0.2-1

**Additional context**

**Comment by garazdawi** [comment]
Hello!

Please report this to https://github.com/esl/packages/issues

Lukas
