### ISSUE TITLE
compiler preprocessor evaluation of functions in -if

### ISSUE THREAD

**Issue by okeuday** [erlang/otp#7706]
**Describe the bug**
The compiler accepts input that should fail, but it doesn't fail.  If this is expected, it would be good to document, but it would be better if the compiler could evaluate the `-if`.  An example is below:

**To Reproduce**
```
$ cat << EOF > test.erl
-module(test).
-export([test/0]).

test() ->
    throw(invisible_to_preprocessor),
    ok.

-if(test() =/= ok).
-error("compiler is unable to get here!").
-endif.
EOF
$ erlc test.erl
$
```

**Expected behavior**
Based on the documentation, the compiler should fail to compile the `test.erl` example.

**Affected versions**
26.1

**Additional context**
Part of the motivation for submitting this bug is the desire to have functionality similar to C++ `static_assert` in an Erlang module.  I had expected `-if` evaluation to be similar to the evaluation of record default values.

The C++ `static_assert` relies on `constexpr` and the Erlang compiler may not currently have a way of marking large expressions constant.  If the Erlang preprocessor could support Erlang function calls in `-if` we could also have an `-assert` directive which would be similar to `-if` use.  Having a way to assert in the preprocessor can help create correct source code, even while humans modify it.  Blocking incorrect source code in the compiler is always desirable.

**Comment by garazdawi** [comment]
This is definitely a documentation bug. Only guard expressions are allowed inside the condition part of `-if`. Would you mind opening a PR expanding the docs? or do you want me to do it?

**Comment by okeuday** [comment]
@garazdawi Ok, it is a documentation bug, but please understand that the compiler doesn't fail on the example input (and any `-if` usage of an Erlang function I tried).  So, it should also be a compiler program validation bug because the compiler should be able to provide an error when `-if` doesn't have a guard expression, with the current Erlang programming language.  I still hope that Erlang is able to get preprocessor assertion functionality in the future.  I won't have time to work on this issue, so feel free to open pull requests for it.

**Comment by mikpe** [comment]
> This is definitely a documentation bug. Only guard expressions are allowed inside the condition part of `-if`. Would you mind opening a PR expanding the docs? or do you want me to do it?

I had a PR recently where knowing this would have helped. I would welcome improved documentation on what may or may not occur in `-if` and `-elif` directives. (FWIW: I would have wanted an equivalent of C's `defined(SYM)`.)

**Comment by michalmuskala** [comment]
`-if` already supports [`defined(SYM)`](https://github.com/erlang/otp/blob/0164d3db05739fc1fad67ac1f5bf3e2aea15cd45/lib/stdlib/src/epp.erl#L1394). It is documented in the EEP https://www.erlang.org/eeps/eep-0044#built-in-functions-in--if-elif, but I don't seem to be able to find it elsewhere
