### ISSUE TITLE
Shell expand/autocomplete is discarding case sensitive suggestions

### ISSUE THREAD

**Issue by josevalim** [erlang/otp#7708]
**Describe the bug**

Compile this module:

```erl
-module(foo).
-compile(export_all).

fabc() -> ok.
fABC() -> ok.
```

Now open up the `erl` shell and type "foo:" followed by tab, you will get this:

```
$ erl
Erlang/OTP 26 [erts-14.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Eshell V14.1 (press Ctrl+G to abort, type help(). for help)
1> foo:
functions
fABC(           module_info(
```

Note it has discarded `fabc(`.

**Expected behavior**

Do not discard suggestions based on case sensitiveness. The `expand_fun` is returning all suggestions, so I assume something after is filtering them. If this is required in some cases, then perhaps the `expand_fun` should filter it, not the shell (as I can replicate this behaviour in Elixir).

**Affected versions**

I have reproduced this on Erlang 26 and 26.1. I did not verify earlier versions.

**Additional context**

The new shell is amazing, thank you.

**Comment by starbelly** [comment]
Replicated; and the issue is [here](https://github.com/erlang/otp/blob/0164d3db05739fc1fad67ac1f5bf3e2aea15cd45/lib/stdlib/src/edlin_expand.erl#L974). Can not open a PR without understanding why this was done to begin with though, as you alluded to, there may be cases where this is ended.
