### ISSUE TITLE
I am unable to install elixir on my HP ProLiant ML30 Gen10 for a week now.   

### ISSUE THREAD

**Issue by 1cbyc** [erlang/otp#7716]
I am unable to install elixir on my HP ProLiant ML30 Gen10 for a week now. 

This url is not functioning: https://github.com/erlang/otp/releases/download/OTP-26.1.1/otp_win64_26.1.1.exe

**Comment by garazdawi** [comment]
What is it that doesn't work? Can't you download the installer?

**Comment by garazdawi** [comment]
Closing this due to lack of information about what the fault is. If you need help, please provide more details. You can also go to either the Erlang or Elixir forum and maybe someone there can assist you.
