### ISSUE TITLE
to_erl clears screen

### ISSUE THREAD

**Issue by garazdawi** [erlang/otp#7737]
**Describe the bug**
When attaching with to_erl the terminal screen is cleared.

**To Reproduce**
Just run to_erl.

**Expected behavior**
The screen should not be cleared.

**Affected versions**
This bug exists since OTP 26

**Additional context**
See https://erlangforums.com/t/ten-year-old-breakage-in-to-erl-run-erl/2934 for a discussion

**Comment by frazze-jobb** [comment]
https://github.com/erlang/otp/pull/8943
