### ISSUE TITLE
shell: \b (aka ctrl+backspace) incorrect behaviour

### ISSUE THREAD

**Issue by garazdawi** [erlang/otp#7749]
**Describe the bug**
When doing Ctrl+Backspace or Ctrl+H on Linux a `$\b` is issued. The `$\b` is interpreted as a `backward_kill_word` when it should be a `backward_kill_char`.

**To Reproduce**
Open a shell on Linux and hit Ctrl+Backspace after typing a word of some sort.

Strangely enough MacOS seems to not be effected by this, haven't tested on Windows.

**Expected behavior**
Ctrl+Backspace and Ctrl+H should work as it always has i.e. the same as it does in bash.

**Affected versions**
This bug was introduced in 26.1. As far as I can tell 26.0 works as it should.

**Additional context**

**Comment by u3s** [comment]
On Windows with OTP-26.1.2. Ctrl+Backspace, Alt+Backspace and Ctrl+H remove a word.

**Comment by NickNeck** [comment]
@garazdawi effects also macOS Monterey.

**Comment by garazdawi** [comment]
Fixed in #7797
