### ISSUE TITLE
`base64:decode*` functions should provide option to reject tampered messages

### ISSUE THREAD

**Issue by hauleth** [erlang/otp#7751]
**Is your feature request related to a problem? Please describe.**

Imagine system where I am receiving some Base64 encoded data and for some reason I do the caching on the data using *encoded data* as a key (for example it is some kind of token).

Unfortunately there is an issue:

```erl
true = base64:decode("QQ==") =:= base64:decode("QR==").
```

This happens because last nibble of encoded data is rejected independently of what is the content of it, while we would expect them to be all zeros.

And there is no way in the VM to reject that message other than writing new implementation of Base64 decode.

This theoretically can lead to some security problems (DoS?) when we use some Base64 encoded security token, as we can cause cache invalidation without tampering with the token data.

**Describe the solution you'd like**

Some way to reject invalid message (where padding data in not all zeros) from `base64:decode*` functions. Either by 2nd argument in form of options list or as a separate function like `base64:decode*_safe` or similar.

**Additional context**

[Article that caught my attention on the problem](https://cendyne.dev/posts/2022-01-23-base64.html)

**Comment by josevalim** [comment]
It is worth mentioning that this is also valid today: `base64:decode(" a G V s b G8 =")`, so if there will be a strict setting, it should probably discard whitespace too. But perhaps the best course of action is a note saying that no one should expect base64 to be bijective (without using the word bijective :P).

Here is what the RFC says:

> When padding is used, there are some non-significant bits that warrant security concerns, as they may be abused to leak information or used to bypass string equality comparisons or to trigger implementation problems.

**Comment by bjorng** [comment]
We have discussed doing this kind validation before and decided not to implement it. We think that depending on Base64 encoding being a bijective function is bad practice.
