### ISSUE TITLE
No shell documentation for dynamic type

### ISSUE THREAD

**Issue by lukaszsamson** [erlang/otp#7752]
**Describe the bug**
No shell documentation for dynamic type introduced in https://github.com/erlang/otp/pull/6993

**To Reproduce**
in erl shell
```
1> ht(erlang, any).

  -type any() :: any().

  All possible Erlang terms. Synonym for term().
ok
2> ht(erlang, dynamic).
{error,type_missing}
```

**Expected behavior**
Documentation returned

**Affected versions**
```
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Eshell V14.0.2 (press Ctrl+G to abort, type help(). for help)
```

**Comment by garazdawi** [comment]
Thanks for the report! I already noticed this a while a ago and fixed it in #7734.
