### ISSUE TITLE
Is it possible to run with thread sanitizers?

### ISSUE THREAD

**Issue by MoBaT** [erlang/otp#7762]
Hey! I have some C code that is wrapped in the nif framework that was built with thread sanitizers. When I try to load it up with “load_nif”, I get an error saying “cannot allocate memeory in static TLS block”. The solutions online say to LD_PRELOAD the tsan library, and when I do that I get a segmentation fault when trying to even use erl. 

LD_PRELOAD=“tsan.so” erl

now my questions is, how can I get thread sanitizer support working with erlang using the LD preload? Is this possible? If not, what are possible workarounds?

Currently on a Ubuntu 22.04 Linux Machine with GCC 11

**Comment by garazdawi** [comment]
Hello!

We have in the past tried to get tsan to work, but failed doing so (don't recall what the problem was). We do not intend to spend any time to make it work or see why it fails.

If you decide to dig into this we would be happy to accept a PR that fixes issues in this area.
