### ISSUE TITLE
Recreating mnesia database with disc_only_copies table with an index from backup crashes mnesia

### ISSUE THREAD

**Issue by fififionek** [erlang/otp#7766]
**Describe the bug**
Recreating mnesia database using `mnesia:restore/2` crashes mnesia application if following conditions are met
* The database is recreated from scratch, ie only new empty schema is present
* Some table in the backup has `disc_only_copies` storage type and the same table has an index on some field.

**To Reproduce**
* Create sourcefile `test.erl` with content:
  ```
  -module(test).
  -export([test_init/0, test_conclude/0]).
  test_init() ->
          mnesia:create_schema([node()]),
          mnesia:start(),
          mnesia:create_table(test, [{disc_only_copies, [node()]}, {index, [val]}]),
          mnesia:backup("backup.bk").
  test_conclude() ->
          mnesia:create_schema([node()]),
          mnesia:start(),
          mnesia:restore("backup.bk", [{recreate_tables, [test]}]).
    ```
* Complie the module: `erlc test.erl`
* Call `erl -noshell -mnesia dir mnesia -s test test_init -s init stop` which will create the backup file `backup.bk` and database directory `mnesia`
* Delete the database: `rm -r mnesia`
* Call `erl -noshell -mnesia dir mnesia -s test test_conclude -s init stop` which will showcase the crash (it will produce mnesia core dump and the OTP will remain hanging)

**Expected behavior**
The `mnesia:restore/2` call should restore the database without any issues

**Affected versions**
The bug is present in OTPs 22.3.4.26, 26.1 and 26.1.1 and I doubt it was fixed for 26.1.2 since that version did not update mnesia.

**Comment by dgud** [comment]
Confirmed.

But if you are starting from scratch you should really use:
> mnesia:install_fallback("backup.bk").
 
Using restore will create a transaction containing all the data in memory, so it is really expensive. 

You can use install_fallback either before starting mnesia or after and mnesia will use
it the next time it starts, though you can't delete the mnesia dir because that will also 
delete the fallback (backup) file.
