### ISSUE TITLE
Unable to build OTP-22.0 on arm64

### ISSUE THREAD

**Issue by juber-nunes** [erlang/otp#7767]
**Describe the bug**
Unable to build OTP-22.0 on arm64

**To Reproduce**
Cloned repo
Went to specific tag - 22.0
and started build process

./otp_build autoconf
./configure

configure: creating ./config.status
config.status: creating emulator/aarch64-unknown-linux-gnu/Makefile
config.status: creating epmd/src/aarch64-unknown-linux-gnu/Makefile
config.status: creating etc/common/aarch64-unknown-linux-gnu/Makefile
config.status: creating include/internal/aarch64-unknown-linux-gnu/ethread.mk
config.status: creating include/internal/aarch64-unknown-linux-gnu/erts_internal.mk
config.status: creating lib_src/aarch64-unknown-linux-gnu/Makefile
config.status: creating ../make/aarch64-unknown-linux-gnu/otp.mk
config.status: creating ../make/make_emakefile
config.status: creating ../lib/os_mon/c_src/aarch64-unknown-linux-gnu/Makefile
config.status: creating ../lib/runtime_tools/c_src/aarch64-unknown-linux-gnu/Makefile
config.status: creating ../lib/tools/c_src/aarch64-unknown-linux-gnu/Makefile
config.status: creating ../make/install_dir_data.sh
config.status: creating aarch64-unknown-linux-gnu/config.h
config.status: aarch64-unknown-linux-gnu/config.h is unchanged
config.status: creating include/internal/aarch64-unknown-linux-gnu/ethread_header_config.h
config.status: include/internal/aarch64-unknown-linux-gnu/ethread_header_config.h is unchanged
config.status: creating include/aarch64-unknown-linux-gnu/erl_int_sizes_config.h
config.status: include/aarch64-unknown-linux-gnu/erl_int_sizes_config.h is unchanged

=== Running configure in /var/snap/amazon-ssm-agent/7629/otp/make ===
./configure --disable-option-checking --cache-file=/dev/null --srcdir="/var/snap/amazon-ssm-agent/7629/otp/make"
configure: error: cannot find required auxiliary files: install-sh config.guess config.sub
ERROR: /var/snap/amazon-ssm-agent/7629/otp/make/configure failed!

**Expected behavior**
To finish build accordingly

**Affected versions**
Only tested with 22.0 which is needed in my case

**Additional context**

**Comment by jhogberg** [comment]
We stopped maintaining OTP 22 two years ago, please try OTP 24 or later.
