### ISSUE TITLE
Issue with the Erlang OTP installation

### ISSUE THREAD

**Issue by dhrbhat1** [erlang/otp#7768]
**Describe the bug**
Team, we are installing Drillbench (SLB) v2022.2.2 using system context , the application requires erlang and rabbitMq as prerequisite. As per the Drillbench installation process
1. Created a System environment variable: RABBITMQ_BASE=C:\ProgramData\RabbitMQ
2. Ran Erlang OTP Version 25.1.2
3. Ran RabbitMQ Version 3.11.2 after a 5-minute wait.
4. Service was not getting excecuted. ![image](https://github.com/erlang/otp/assets/105770370/843c53b6-d9f6-4a39-97a5-5002d4021153)
5.  And we received error while installing drillbench exe

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
We want the required drillbench application gets executed once the dependencies (Erlang & arbbitmq) are installed 

**Affected versions**
The OTP versions that are affected by this bug. v25.1.2

**Additional context**
Add any other context about the problem here. If you wish to attach Erlang code you can either write it directly in the post using [code tags](https://guides.github.com/features/mastering-markdown/), create a [gist](https://gist.github.com), or attach it as a zip file to this post.

**Comment by garazdawi** [comment]
Hello! This is not the correct place to look for help on this issue. Please try contacting the RabbitMQ or Drillbench team.
