### ISSUE TITLE
TLS handshake failure with OTP 26, succeeds with OTP 25

### ISSUE THREAD

**Issue by lukebakken** [erlang/otp#7774]
Repository with code to reproduce this issue:

https://github.com/lukebakken/rabbitmq-users-X9VRDGdn5HU

I know that OTP 26 has "tightened things up" when it comes to TLS, and the following issue may actually be how TLS _should_ work in Erlang, but I thought this deserved a report.

**Describe the bug**

When a SSL listener is configured with `{versions, ['tlsv1.2','tlsv1.3']}`, and a connection attempt is made using a .NET application on Windows Server 2016, a handshake failure occurs using OTP 26. This failure does not occur using OTP 25.

The original reporter also provides a Python script that crafts the same client hello message that causes the issue. The script is located here:

https://github.com/lukebakken/rabbitmq-users-X9VRDGdn5HU/blob/main/py/repro.py

There are some important notes here about which signature algorithms are necessary for OTP 26 to work:

https://github.com/lukebakken/rabbitmq-users-X9VRDGdn5HU/blob/main/py/notes.txt#L5-L10

**To Reproduce**

https://github.com/lukebakken/rabbitmq-users-X9VRDGdn5HU/blob/main/README.md

**Expected behavior**

TLS connection succeeds.

**Affected versions**

Failure tested with OTP 26.1.2, succeeds with OTP 25.3.2.7

**Additional context**

* Note that because the client application is running on Windows and uses .NET, it is using Windows' TLS implementation and not OpenSSL. Running `openssl s_client` works just fine using OTP 26 and `{versions, ['tlsv1.2','tlsv1.3']}`.
* Original report - https://groups.google.com/g/rabbitmq-users/c/X9VRDGdn5HU
* Packet capture when using OTP 26, showing failure - https://github.com/lukebakken/rabbitmq-users-X9VRDGdn5HU/blob/main/failure-otp-26.pcapng
* Packet capture using OTP 25, showing success - https://github.com/lukebakken/rabbitmq-users-X9VRDGdn5HU/blob/main/success-otp-25.pcapng

**Comment by mohag** [comment]
If just TLS 1.2 is enabled, TLS 1.2 works fine. If TLS 1.3 + TLS 1.2 is enabled, a TLS 1.2 ClientHello's signature_algorithms MUST contain "sha256+rsaepss", "sha384+rsaepss"or "sha512+rsaepss", otherwise the handshake fails. (If TLS 1.3 is disabled, this limitation goes away)

**Comment by IngelaAndin** [comment]
Well maybe it is a bug. It looks like the legacy signature schemes  "rsa_pkcs1_sha512,rsa_pkcs1_sha384,rsa_pkcs1_sha256"  are not being handled when negotiating TLS-1.2 when both versions are supported. It can have to do with name conversions as TLS-1.3 signature schemes are somewhat different from TL-1.2 signature algorithms and have different naming schemes but on the wire some algorithms/schemes have the same representation.  I will look into it.

**Comment by lukebakken** [comment]
Thank you @IngelaAndin! Let me know if you need any more information. It's easy for me to reproduce this issue so I can test a fix any time.

**Comment by IngelaAndin** [comment]
@lukebakken  Please try my PR, I believe I found a refactor that went bad!

**Comment by lukebakken** [comment]
@IngelaAndin I tried my PR to your PR...

* https://github.com/IngelaAndin/otp/pull/1
* https://github.com/erlang/otp/pull/7783

...but I still see the same error. I built OTP using your branch and only copied the patched `ssl_cipher.beam` file, overwriting the existing OTP 26.1.2 `ssl_cipher.beam` file.

Would a new packet capture or other set of output be helpful?

**Comment by IngelaAndin** [comment]
Ah, sorry about that trying to do to many things at the time it seems. I must have test it in the wrong place. I think maybe some more adjustment might be needed, but that part was definitely wrong. New try tomorrow,

**Comment by IngelaAndin** [comment]
@lukebakken  I have a new version for you to try, that I believe can solve your problem. It is a different code path than the original suspect code which I am still looking into, but perhaps not cause of your problem.

**Comment by IngelaAndin** [comment]
Think I straightened it out!  commit should have sha  6a8c87a3cf78cf77254ae89825c7595d9aebe037

**Comment by lukebakken** [comment]
OK I will test this out.

**Comment by lukebakken** [comment]
@IngelaAndin great news, that commit fixes the issue in my test environment. Thank you! cc @mohag

**Comment by IngelaAndin** [comment]
Great I need to cuddle some test cases before I can merge, I believe they  need a new configuration. But I had not had time to fix it yet!

**Comment by mohag** [comment]
Thanks!

**Comment by lukebakken** [comment]
Thank you @IngelaAndin
