### ISSUE TITLE
`erl_anno`'s `to_term/1` not working as intended (?)

### ISSUE THREAD

**Issue by kivra-pauoli** [erlang/otp#7778]
## Describe the bug

I'm still unsure it's a bug, but it seems like it is.

`erl_anno`'s `to_term/1` [defined as](https://github.com/erlang/otp/blob/master/lib/stdlib/src/erl_anno.erl#L79)

```erlang
-spec to_term(Anno) -> anno_term() when
      Anno :: anno().

-ifdef(DEBUG).
to_term(Anno) ->
    simplify(Anno).
-else.
to_term(Anno) ->
    Anno.
-endif.
```

is supposed to take an opaque `anno()` and return it (I'm looking at the non-DEBUG bit), unmodified, as a (non-opaque) `term()`.

The `erl_anno` code even mentions Dialyzer in regards to this

```erlang
%% To be used when necessary to avoid Dialyzer warnings.
-export([to_term/1, from_term/1]).
```

I'm getting a Dialyzer analysis issue where it seems the term is still seen as opaque, though.

It's possible I'm missing a detail, but I can't figure it out.

## To Reproduce

I might create specific code for this, if it's potentially deemed as a bug, but just wanna understand if I'm missing something, for the moment.

## Expected behavior

Using `to_term/1` should trick the Dialyzer into not considering that function's return to be opaque.

## Affected versions

26.0.2 at least.

## Additional context
@aronisstav [pointed out](https://erlanger.slack.com/archives/C055DJA49/p1698149796966139) that there might be some 🪄 around this, in Dialyzer, that makes the bug exist, but we didn't conclude on anything yet.

**Comment by elbrujohalcon** [comment]
@kivra-pauoli any chance you can provide a minimal module that triggers dialyzer warnings around this _before_ it's considered a bug? It would be helpful in diagnosing if it's a bug or not ;)

**Comment by kivra-pauoli** [comment]
Yeah, I think I'll need to come up with a minimal example. @jhogberg already gave me some pointers in Erlang Slack, too.

**Comment by kivra-pauoli** [comment]
I believe I "see" my error 😄 There's a function (next to the function I'm calling) that's telling Dialyzer that input is an `anno()`, when it isn't (because it should be a `term()` - wrong spec), and I believe Dialyzer is taking that into account for the "false" report. I'm closing this, for the moment, and will get back to it if I to find the error wasn't on me. Sorry for wasting your time.

**Comment by kivra-pauoli** [comment]
To give a bit more context, it was one of those situations where you have something like:

```erlang
breaks(Location0) ->
    Location = erl_anno:to_term(Location0),
    _ = erl_anno:file(Location),
    {_L, _C} = Location.
```

Even though we're calling `erl_anno:to_term/1`, we're also passing `Location` to a function that expects an opaque, so I guess Dialyzer takes that as "extra information". If I comment out the `:file` line the Dialyzer issue is gone.

So... it might be somewhat misleading in the way it presents the issue, but it's not _wrong_.

**Comment by elbrujohalcon** [comment]
> So... it might be somewhat misleading in the way it presents the issue, but it's not _wrong_.

Yeah… Sounds like Dialyzer to me.
