### ISSUE TITLE
inets:httpd mime_type property does nothing.

### ISSUE THREAD

**Issue by erikareads** [erlang/otp#7827]
**Describe the bug**
The `mime_type` property described in the `httpd` documentation [here](https://www.erlang.org/doc/man/httpd#erlang-http-server-service-start-stop) does not actually do anything. The behavior described:

> When the server is asked to provide a document type that cannot be determined by the MIME Type Settings, the server uses this default type.

Is actually set by the undocumented `default_type` property.

**To Reproduce**
I ran `httpd` on a static directory of files, some of which contained HTML without file extensions.
Setting `{mime_type, "text/html"}` without setting the `default_type` will lead to those files without extensions rendering as plain text, rather than as HTML.

**Expected behavior**
The `mime_type` property to appropriately set the default type of files loaded by `httpd`.
I can confirm that setting `default_type` has the behavior expected from `mime_type`.

Three possible remedies:

1. Update documentation to reflect the correct `default_type` property instead of `mime_type`.
2. Change code using `default_type` to use `mime_type`.
3. Update existing code to have `mime_type`, in addition to `default_type`, set the default type of served files.

**Affected versions**
I found evidence of `mime_type` in the documentation as far back as OTP-17.0, without any functions to support setting the default type with this property. I didn't check further back.

**Additional context**
In `mod_get`, the `send_response/4` function looks up the `mime_type` of a file using its extension: [source](https://github.com/erlang/otp/blob/master/lib/inets/src/http_server/mod_get.erl#L73). It also sets the type to `"text/plain"` if that lookup fails.

To do that it invokes `httpd_util:lookup_mime_default/3`. [That function](https://github.com/erlang/otp/blob/master/lib/inets/src/http_server/httpd_util.erl#L120C13-L120C13) does up to two `ets:lookup`s in order to find the mime_type: one in `mime_types`, set by the `mime_types` property, and one in `default_type` presumably set by the `default_type` property.

The `default_type` and `mime_type` properties are never stored by name (`mime_types` with an `s` is stored explicitly in code), both are stored by default case of [`httpd_conf:store/2`](https://github.com/erlang/otp/blob/master/lib/inets/src/http_server/httpd_conf.erl#L401), which is called by [`httpd_confi:store_traverse/3`](https://github.com/erlang/otp/blob/master/lib/inets/src/http_server/httpd_conf.erl#L602) and to be stored in the `ConfigDB` ets table by [`httpd_conf:store/4`](https://github.com/erlang/otp/blob/master/lib/inets/src/http_server/httpd_conf.erl#L588). Notably, [`httpd_conf:validate_config_params/1`](https://github.com/erlang/otp/blob/master/lib/inets/src/http_server/httpd_conf.erl#L295) has a check for `default_type` but not for `mime_type`.

I'm happy to submit a patch addressing this issue, once I have an idea of which way we want to remedy the issue.

**Comment by IngelaAndin** [comment]
Thanks for the report, we will have a discussion and come back to you.

**Comment by IngelaAndin** [comment]
Hum.. this has been broken for such a long time that it is hard to dig out how this happened. 
We think the safest way to fix it is to implement the mime_type option as it is documented and fallback on the undocumented option if mime_type is not set, and state in the code that it is only for backwards compatibility.

**Comment by IngelaAndin** [comment]
#7843 merged
