### ISSUE TITLE
Identical is_list/1 guard clauses does not generate warning

### ISSUE THREAD

**Issue by eproxus** [erlang/otp#7836]
**Describe the bug**
Two identical function clauses do not generate a warning.

**To Reproduce**
Compile the following module:
```erl
-module(test).
-export([match/1]).
match(Term) when is_list(Term) -> foo;
match(Term) when is_list(Term) -> bar.
```

```console
$ erlc test.erl
$
```

Seems the second clause is silently discarded:
```console
$ erlc +S test.erl
$ cat test.S
...
{function, match, 1, 2}.
  {label,1}.
    {line,[{location,"test.erl",3}]}.
    {func_info,{atom,test},{atom,match},1}.
  {label,2}.
    {test,is_list,{f,1},[{x,0}]}.
    {move,{atom,foo},{x,0}}.
    return.
...
```

**Expected behavior**
```console
$ erlc test.erl
test.erl:4:1: Warning: this clause for match/1 cannot match because a previous clause at line 3 always matches
%    4| match(_Term) when is_list(Term) -> bar.
%     | ^
```

**Affected versions**
26.1.2

**Additional context**
This version works as expected:
```erlang
-module(test).
-export([match/1]).
match([_|_]) -> foo;
match([_|_]) -> bar.
```

```console
$ erlc test.erl
test.erl:4:1: Warning: this clause cannot match because a previous clause at line 3 always matches
%    4| match([_|_]) -> bar.
%     | ^
```

Which generates:
```
{function, match, 1, 2}.
  {label,1}.
    {line,[{location,"test.erl",3}]}.
    {func_info,{atom,test},{atom,match},1}.
  {label,2}.
    {test,is_nonempty_list,{f,1},[{x,0}]}.
    {move,{atom,foo},{x,0}}.
    return.
```

So the test `is_nonempty_list` seems to trigger the warning but not the `is_list` test.

**Comment by josevalim** [comment]
I always took these warnings as "best effort", i.e. they will be emitted if something is found but they do not guarantee to emit whenever there is an overlap (which would be impossible with guards anyway).

**Comment by bjorng** [comment]
Yes, those warnings are best effort. I call them *opportunistic warnings* because they are generated when the compiler happens to notice something fishy while applying an optimization.

The compiler passes that generate opportunistic warnings are generally quite good at detecting and remove clauses that will not be reached based on the patterns alone. They generally don't notice that some clause will not be reached because of repeated guard tests.
