### ISSUE TITLE
Logger log to file format has an issue

### ISSUE THREAD

**Issue by cisiqo** [erlang/otp#7837]
**Describe the bug**

I have an record data, it log to file format has an issue with `logger`.

**To Reproduce**

The record data:
```
{coap_message,con,get,59592,<<"obstoken">>,#{292 => <<5,174,250,106>>,observe => 0,uri_path => [<<"ps">>,<<"coap">>,<<"test">>],uri_query => #{<<"clientid">> => <<"0622ff402c06010122ff">>,<<"token">> => <<"129493754">>}},<<>>}.
```

The coap_message defined:
```
-record(coap_message, {
    type,
    method,
    id,
    token = <<>>,
    options = #{},
    payload = <<>>
}).
```

Use `logger:debug`  print the record data, it will output:
```
debug: {coap_message,con,get,59592,<<"obstoken">>, #{292 => <<5,174,250,106>>, observe => 0, uri_path => [<<"ps">>,<<"coap">>,<<"test">>], uri_query =>, #{<<"clientid">> => <<"0622ff402c06010122ff">>, <<"token">> => <<"129493754">>}}, <<>>}
```

**Expected behavior**

The debug will output:
```
debug: {coap_message,con,get,59592,<<"obstoken">>, #{292 => <<5,174,250,106>>, observe => 0, uri_path => [<<"ps">>,<<"coap">>,<<"test">>], uri_query => #{<<"clientid">> => <<"0622ff402c06010122ff">>, <<"token">> => <<"129493754">>}}, <<>>}
```

The **MAIN DIFFERENCE** is the `uri_query` print `uri_query =>`, actually it should print `uri_query => #{<<"clientid">> => <<"0622ff402c06010122ff">>, <<"token">> => <<"129493754">>}`.

**Affected versions**

macOS m1 Homebrew installed version 26.0.2

**Additional context**

I use shell to reproduce it
```
# erl -kernel logger_level debug

> Config = #{config => #{file => "./info.log"}, level => debug}.

>logger:add_handler(myhandler, logger_std_h, Config).

>rd(coap_message, {type,method,id,token,options,payload}).

>Record = {coap_message,con,get,59592,<<"obstoken">>,#{292 => <<5,174,250,106>>,observe => 0,uri_path => [<<"ps">>,<<"coap">>,<<"test">>],uri_query => #{<<"clientid">> => <<"0622ff402c06010122ff">>,<<"token">> => <<"129493754">>}},<<>>}.

>logger:debug(io_lib:format("~p", [Record])).
```
Exit shell, then `cat ./info.log`, it output the debug data.

**Comment by garazdawi** [comment]
Is it the stray `,` after `=>` that is the issue? Or did I miss some other detail? I'm not sure when I'll have time to dig into this, so a PR with a fix would be much appriated.

**Comment by cisiqo** [comment]
Yes, parsing has added an additional one `,` after `=>`.

**Comment by garazdawi** [comment]
Not a bug, see my comment in #7886.

**Comment by cisiqo** [comment]
Thanks
