### ISSUE TITLE
beam.smp: memfd_create() called without MFD_EXEC or MFD_NOEXEC_SEAL set

### ISSUE THREAD

**Issue by licaon-kter** [erlang/otp#7858]
**To Reproduce**
Use OTP 26.1.2 on Linux kernel 6.4 or later

**Expected behavior**
No syslog warnings

**Additional context**
https://lwn.net/Articles/918106/

**Comment by jhogberg** [comment]
Thanks for your report, I've moved this over to https://github.com/asmjit/asmjit/issues/421 as it's an asmjit issue. :-)

**Comment by garazdawi** [comment]
@licaon-kter I noticed that you asked the in the ASMJIT issue about when this would be fixed in Erlang/OTP.

We usually update the asmjit dependency before each major release, so that means that the fix will be part of Erlang/OTP 27 which is set to be released in about 6 month.

If you need the update before then, you can update it in your own fork by using the [`update_asmjit`](https://github.com/erlang/otp/blob/master/erts/emulator/Makefile.in#L959) make target in `erts/emulator`.

**Comment by licaon-kter** [comment]
```
 ~/otp_src_26.1.2/erts/emulator $ make update_asmjit
Makefile:26: /make/app_targets.mk: No such file or directory
make: *** No rule to make target '/make/app_targets.mk'.  Stop.
```
...what am I missing?

**Comment by frej** [comment]
`Makefile:26: /make/app_targets.mk: No such file or directory` looks like `$ERL_TOP` isn't set. Set it to point to the top of the checked out OTP tree and try again.

**Comment by licaon-kter** [comment]
exported `ERL_TOP` now it says: `make: *** No rule to make target 'update_asmjit'.  Stop.`

**Comment by garazdawi** [comment]
There are plenty of rough edges when this deep inside the makefile system :)

``make -f `$ERL_TOP/erts/autoconf/config.guess`/Makefile update_asmjit``

**Comment by licaon-kter** [comment]
Ok, that moves it along, but to the same error when running `make` in root folder: https://github.com/erlang/otp/issues/7858#issuecomment-1826412074

**Comment by garazdawi** [comment]
Make sure that `ERL_TOP` is set, and if it is then clean the repository and start from scratch again. There are a bunch of tip and tricks in the [Development HOWTO](https://github.com/erlang/otp/blob/master/HOWTO/DEVELOPMENT.md).

**Comment by licaon-kter** [comment]
I'm using an archive of 26.1.2, will retry with a clean git tree too

**Comment by licaon-kter** [comment]
Yeah, it crossed my mind that it might need OTP HEAD or at least newer than my local 26.1.2, will backport them then and report back.

**Comment by licaon-kter** [comment]
Restarted the machine with the backported edits, I didn't see any `beam.smp` notices in dmesg* :tada: 


*althought one like `systemd[539]: memfd_create() called without MFD_EXEC or MFD_NOEXEC_SEAL set` was present and PID 539 was `systemd` doing something :shrug:
