### ISSUE TITLE
record matches do not work in KeyPattern of a map generator in a comprehension

### ISSUE THREAD

**Issue by RoadRunnr** [erlang/otp#7875]
**Describe the bug**

According to the documentation of the map generator the `KeyPattern` can be any pattern. However, using a partial record as pattern doesn't work. However, using the same record pattern in a list generator works as expected.

**To Reproduce**

Sample code:
```
-record(foo, {f1, f2}).

t4() ->
    List = [{#foo{f1 = X, f2 = X*2}, X} || X <- lists:seq(1, 10)],
    FilteredList = [V || {#foo{f1 = M}, V} <- List, M rem 2 =:= 0],
    io:format("List Test~nList: ~0p~nFiltered: ~0p~n", [List, FilteredList]),

    Map = maps:from_list(List),
    FilteredMap = [V || #foo{f1 = N} := V <- Map, N rem 2 =:= 0],
    io:format("~nMap Test~nMap: ~0p~nFiltered: ~0p~n", [Map, FilteredMap]),
    ok.
```

Resulting output:
```
List Test
List: [{{foo,1,2},1},{{foo,2,4},2},{{foo,3,6},3},{{foo,4,8},4},{{foo,5,10},5},{{foo,6,12},6},{{foo,7,14},7},{{foo,8,16},8},{{foo,9,18},9},{{foo,10,20},10}]
Filtered: [2,4,6,8,10]

Map Test
Map: #{{foo,1,2} => 1,{foo,2,4} => 2,{foo,3,6} => 3,{foo,4,8} => 4,{foo,5,10} => 5,{foo,6,12} => 6,{foo,7,14} => 7,{foo,8,16} => 8,{foo,9,18} => 9,{foo,10,20} => 10}
Filtered: []
```

When the `KeyPattern` is modified to `#foo{f1 = N} = _ := V`, it works. However, there is nothing in the documentation that would explain why that is so.

**Expected behavior**

The `Filtered` list should be the same for the list and map example.

**Affected versions**

OTP 26.1.2: Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

**Comment by bjorng** [comment]
Yes, it is a bug. Fixed in the linked pull request.
