### ISSUE TITLE
Documentation: Maps appear as comments in code examples

### ISSUE THREAD

**Issue by JuneKelly** [erlang/otp#7888]
**Describe the bug**
In the [reference manual](https://www.erlang.org/doc/reference_manual), code examples which start with a map literal (like `#{}`) are rendered in grey italics, as if they were comments.

My guess is that `highlight.js` needs to be configured to not treat lines beginning with `#` as comments.

**To Reproduce**
Look at the [Map Expressions](https://www.erlang.org/doc/reference_manual/expressions#map-expressions) section of the reference guide.

Examples that start with map literals seem to be rendered as comments (presumably because of the `#` character)

See screenshot:

![image](https://github.com/erlang/otp/assets/1540054/e29f43e0-52c7-4484-8f1f-d4293765e136)

**Expected behavior**
These examples should render like all other examples

**Affected versions**
The current version of the reference manual.

**Additional context**
I'm using Firefox on MacOS 14.1.1, but the same issue seems to be present in Safari. I presume the issue is not browser-dependant

**Comment by garazdawi** [comment]
We are currently in the process of migrating all our documentation to use [ex_doc](https://github.com/elixir-lang/ex_doc) as the html/epub generator. As part of that migration the code highlighter will be changed from highlight.js to [makeup](https://github.com/elixir-makeup/makeup_erlang) which will solve this issue.
