### ISSUE TITLE
Both ssh_sftp:read_file_info/2,3 and ssh_sftp:read_link_info/2,3 return incorrect record file_info

### ISSUE THREAD

**Issue by shapovalovts** [erlang/otp#7897]
**Describe the bug**
`ssh_sftp:read_file_info/2,3` and `ssh_sftp:read_link_info/2,3` return record `file_info` with `uid` and `gid` string values, while they must be integers. 

**To Reproduce**
Read any file via one of those functions.

**Expected behavior**
`ssh_sftp:read_file_info/2,3` and `ssh_sftp:read_link_info/2,3` return the record in the same format as functions with the same names from `file` module.

**Affected versions**
Reproduced on 24.2 and 26.1.2, but in the past was reproduced on older OTP versions as well.

**Additional context**
The incorrect record can't be used as is, because functions like `ssh_stfp:write_file_info` raise exceptions because incorrect type of `uid` and `gid` in the record.

**Comment by u3s** [comment]
Thanks for report we scheduled work on that. It has to wait for a while due to priorities :-/.
