### ISSUE TITLE
[Rabbitmq] TLS Peer Verification: Should not fail if client certificate does not contain expected value for extended key usage extension

### ISSUE THREAD

**Issue by codegeass1** [erlang/otp#7909]
**TLS Peer Verification: Do not fail if client certificate does not contain expected value for extended key usage extension**

In order to enable TLS Peer Verification, I have added to Rabbitmq config, this config to force rabbitmq to fail if client does not present a valid certificate signed by a trusted authority.

```     
ssl_options.cacertfile = /path/to/ca_certificate.pem
ssl_options.certfile = /path/to/server_certificate.pem
ssl_options.keyfile = /path/to/server_key.pem

ssl_options.verify = verify_peer
ssl_options.depth  = 2
ssl_options.fail_if_no_peer_cert = true
```

On client side, I have added to configuration the usage a certificate when establishing connection to Rabbitmq. This certificate has on its extension 'Extended Key Usage'  set to TLS Web Server Authentication.

I do have this error when client connects to Rabbitmq : 

```
[notice] <0.979.0> TLS server: In state wait_cert at ssl_handshake.erl:2113 generated SERVER ALERT: Fatal - Handshake Failure
**[notice] <0.979.0> - {bad_cert,invalid_ext_key_usage}**
```

From what I understood, I have this error because the client presents a certificate with extension 'Extended Key Usage' set to TLS Web Server Authentication instead of TLS Web Client Authentication.

### Set this restriction as an option

Is it possible to have an option that let us control this validation ? The main verification is that the presented certificate is signed by a trusted authority right ?

### Additional context

(For some reason, my company does not deliver certificates with that value of extension.)

Discussion on Rabbitmq Channel: https://github.com/rabbitmq/rabbitmq-server/discussions/10002

**Comment by IngelaAndin** [comment]
You should be able to handle this error in your verify_fun already! 

https://www.erlang.org/doc/man/ssl#type-custom_verify

**Comment by u3s** [comment]
ping @IngelaAndin

**Comment by madankumar-dev** [comment]
Hi @IngelaAndin I am also facing similar issue and getting invalid certificate response while validating "Extended Key Usage" extension in Erlang version OTP26.2.2 with RSA certificates, as per your last comment, is it fine to handle this extension id at our verify_fun module and return response as valid certificate?  or is it required any changes at OTP(ssl library)?

**Comment by IngelaAndin** [comment]
It is fine for you to catch the   {bad_cert,invalid_ext_key_usage} in you verify_run and report it as valid if that is what you want. If you accept some validation  error it is up to you to decide if that is acceptable or not.  Also note that fairly recently we changed the behavior of this check to only be performed on peer certificates. The client-sever role should not be checked if this extension is used in a CA cert.

**Comment by madankumar-dev** [comment]
@IngelaAndin Thanks for your quick response, in our case we are getting {extension, Extension} in our verify_fun from pubkey_cert.erl,  but we are not  handling this Extension at our verify_fun module and treating this as  bad_cert,  now i did changes at  our verify_fun  module to handle it.
