### ISSUE TITLE
ssl:prf/5 sometimes hangs forever

### ISSUE THREAD

**Issue by leoliu** [erlang/otp#7911]
**Describe the bug**
`ssl:prf/5` may hang forever on some servers.

**To Reproduce**
```Erlang
{ok, Sock} = ssl:connect("www.google.com", 443, [{verify,verify_none}]).
ssl:prf(Sock, master_secret, <<"EXPERIMENTAL-otp">>, [<<>>], 32).
```
Here is another server to try: https://xmpp.earth

**Expected behavior**
Should complete successfully.

**Affected versions**
26.1.2

**Additional context**
When `ssl:prf/5` stuck, `ssl_gen_statem:connection/3` would return `{keep_state_and_data, [postpone]}`.

**Comment by leoliu** [comment]
BTW with the PR applied other functions such as `ssl:peercert/1`, `ssl:connection_information/1` get stuck.

**Comment by leoliu** [comment]
@IngelaAndin Thanks for the work. I tested it with `tlsv1.2` and `tlsv1.3` and both returned promptly without getting stuck. However, I discovered that it produces the same value as `ejabberd` when using `tlsv1.2`, but different value when `tlsv1.3`.

**Comment by leoliu** [comment]
@IngelaAndin Thanks for the work. I tested it with `tlsv1.2` and `tlsv1.3` and both returned promptly without getting stuck. However, I discovered that it produces the same value as `ejabberd` when using `tlsv1.2`, but different value when `tlsv1.3`.

**Comment by IngelaAndin** [comment]
@leoliu  That might be part of the problem I am thinking on while it comes to the API. The original prf function was contributed a long time ago and apart from TLS-1.3 and previous versions handling "prf" calculations differently, the old API will let you create an answer with or without connecting to the session values (or just partially do so).

**Comment by leoliu** [comment]
@IngelaAndin Yes I was trying to see if I can get `ssl` to auth to ejabberd using the `tls-exporter` channel binding. Hope `ssl:prf/5` is the right function. According to RFC 9266 it seems I need to use:

```Erlang
ssl:prf(Sock, master_secret, <<"EXPORTER-Channel-Binding">>, [client_random, server_random], 32)
```

and auth succeeds if I force the connection to be `tlsv1.2` but fails if `tlsv1.3`.

On the ejabberd side it's using `SSL_export_keying_material ` from openssl as per https://github.com/processone/fast_tls/blob/master/c_src/fast_tls.c#L1408

**Comment by IngelaAndin** [comment]
@leoliu Yes I think it is the right function, but I am pondering if there is a valid use case that does not use master_secret and [client_random, server_random] arguments. Also I think a better function name could be exporter. But these would be enhancements. Lets get the functionality correct first. I have done a few adjustments, can you try again. If it still does not work it could help if we could construct some kind white-box test case. I will look at it aging on Monday

**Comment by leoliu** [comment]
@IngelaAndin I just checked to make sure I have used the latest PR 7927. Yes same issue.I have been thinking if there is a way to bypass ejabberd and go straight to openssl (maybe with it's s_server).

**Comment by IngelaAndin** [comment]
@leoliu I just happened to notice I forgot to commit the input adjustment I made. I put it as separate commit for now, and pushed it. Tomorrow I will also try find a simpler way to test.

**Comment by leoliu** [comment]
@IngelaAndin I tested the new patch but I am getting the same issue. I noted that RFC 8446 has `Hash(context_value)` so I tweaked the patch a bit but no luck still.

**Comment by IngelaAndin** [comment]
Thank you for the info, I have been playing around with it trying to get the correct interpretation of the RFCs. Actually going back and forth I find it a bit confusing. Hopefully we can straight it out in the end.

**Comment by IngelaAndin** [comment]
@leoliu So I made a new commit. I think it is becoming clearer but  one thing is not totally clear to me, it seems like client_random and server_random is not used in TLS-1.3 exporter.  For now I made it possible to try both:

```
ssl:prf(Sock, master_secret, <<"EXPORTER-Channel-Binding">>, [client_random,server_random], 32).

ssl:prf(Sock, master_secret, <<"EXPORTER-Channel-Binding">>, [<<>>], 32).

```
  master_secret will use the "exporter master secret"  for TLS-1.3.

**Comment by leoliu** [comment]
@IngelaAndin I have been trying to see if I can get the patch to work. The algorithm in `tls_gen_connection_1_3` is more or less identical to what openssl does. But no matter what I tweaked it didn't work. Eventually I compiled a version of openssl that prints out its `exporter_master_secret` and found that it never agrees with Erlang's.

**Comment by IngelaAndin** [comment]
@leoliu ok interesting. On Monday I will look closer at the exporter master secret generation.

**Comment by IngelaAndin** [comment]
@leoliu  I think I can have found the problem please try new commit

**Comment by leoliu** [comment]
@IngelaAndin The latest patch works with small changes. For tls 1.3 ClientRandom, ServerRandom are not needed. The ?uint16 is also not needed.

**Comment by IngelaAndin** [comment]
@leoliu ok thanks for testing. I will work on a new API function exporter, and also include early_exporter functionality fot TLS-1.3. It could probably be used for prior version to simplify API.  I am not sure if I will totally deprecate prf or only make it legacy.  It would be interesting to know if anyone considers it useful with  arguments  excluding master_secret and [client_random, server_random]  ?!

**Comment by leoliu** [comment]
I like the plan for new API.

Personally I can't think of any practical use of `prf/5` without `master_secret` and the like. But perhaps it was designed that way so that it can be tested better.

**Comment by IngelaAndin** [comment]
@leoliu I have been doing so revisits to the RFC, and I think we now have a API that works for exporters. I think we will leave early exporter for later inclusion as I think we may need other API additions to really support that use case.

**Comment by leoliu** [comment]
@IngelaAndin I like the plan. I just tested the new pr and it works, both the legacy `prf` and the new `exporters`.
