### ISSUE TITLE
Binary Acc gets lost in cow_uri:urldecode/2

### ISSUE THREAD

**Issue by essen** [erlang/otp#7926]
**Describe the bug**
Calling cow_uri:urldecode/1 no longer works under certain cirtumstances. It returns empty binaries instead of url-decoded binaries. The function goes over every byte in the binary so this should not be possible.

**To Reproduce**
I don't seem to be able to extract snippets but I reproduce it 100% by doing the following:

Compile OTP master using `kerl build git https://github.com/erlang/otp master master` and install it `kerl install master ~/erlang/master` (optional?).

```
. ~/erlang/master/activate`
git clone https://github.com/essen/cowboy
cd cowboy
make ct-tracer t=http:path
```

Note: use my fork of Cowboy to reproduce. The main repository doesn't have needed fixes yet.

You will get a failure:

```
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
tracer_SUITE:do_get failed on line 105
Reason: {badmatch,{response,fin,404,
          [{<<"content-leng"......}
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

If you modify `deps/cowlib/src/cow_uri.erl` like this:

```
diff --git a/src/cow_uri.erl b/src/cow_uri.erl
index 4480d6b..6f10bb5 100644
--- a/src/cow_uri.erl
+++ b/src/cow_uri.erl
@@ -92,7 +92,7 @@ urldecode(<< $k, Rest/bits >>, Acc) -> urldecode(Rest, << Acc/bits, $k >>);
 urldecode(<< $l, Rest/bits >>, Acc) -> urldecode(Rest, << Acc/bits, $l >>);
 urldecode(<< $m, Rest/bits >>, Acc) -> urldecode(Rest, << Acc/bits, $m >>);
 urldecode(<< $n, Rest/bits >>, Acc) -> urldecode(Rest, << Acc/bits, $n >>);
-urldecode(<< $o, Rest/bits >>, Acc) -> urldecode(Rest, << Acc/bits, $o >>);
+urldecode(<< $o, Rest/bits >>, Acc) -> ct:pal("~p ~p", [Rest, Acc]), urldecode(Rest, << Acc/bits, $o >>);
 urldecode(<< $p, Rest/bits >>, Acc) -> urldecode(Rest, << Acc/bits, $p >>);
 urldecode(<< $q, Rest/bits >>, Acc) -> urldecode(Rest, << Acc/bits, $q >>);
 urldecode(<< $r, Rest/bits >>, Acc) -> urldecode(Rest, << Acc/bits, $r >>);
```

Then recompile it and run the tests again:

```
make -C deps/cowlib IS_DEP=1 && make ct-tracer t=http:path
```

Then the test will pass with some ct:pal output.

If you change the ct:pal function to `ct:pal("~p ~p", [Rest, something_else])` and run the previous command then the test will fail again.

**Expected behavior**
My code is correct and should not produce this output. :-)

**Affected versions**
Current master, problem exists at least since Monday, but probably earlier.

**Additional context**
Has been seen on Arch Linux as well as Github Actions ubuntu-latest and macos-latest.

**Comment by essen** [comment]
5d7d146e7c1f0602b948eed6d526a14c928d3a3d fails
6e4f65f094547688b74a64807afa216c05cee645 succeeds

**Comment by essen** [comment]
It works in the interpreter, and it also works in many other test suites which do end up calling these functions. I don't know why only tracer_SUITE fails there, but maybe the hint is in the name of the test suite.

**Comment by jhogberg** [comment]
Just to clarify, does it work if you build OTP with `--disable-jit`?

> I don't know why only tracer_SUITE fails there, but maybe the hint is in the name of the test suite.

That would make sense, the writable-binaries optimization is suspended when observed through tracing which might be causing issues here. I'll look into it. :)

**Comment by essen** [comment]
It works with `--disable-jit` yes.
