### ISSUE TITLE
Correct closing of ssl handling DTLS - Erlang OTP 25.3 or higher...

### ISSUE THREAD

**Issue by cwmichi** [erlang/otp#7951]
Hello together,

I have a new issue closing a DTLS socket (using UDP) when the connection is emulated and when I am closing the running process the socket still keeps open, e.g. the listener owner dies

Steps to reproduce:

1> application:ensure_all_started(ssl).
{ok,[crypto,asn1,public_key,ssl]}
2> spawn(fun() -> ssl:listen(0,[inet,{port,63450},{ciphers,[#{cipher => aes_256_gcm,key_exchange => psk,mac => aead,prf => sha384}]},{protocol,dtls},{versions,['dtlsv1.2']},{verify,verify_none},{psk_identity,"psk"}]) end).

and Port 63450 is still open

**Comment by IngelaAndin** [comment]
Thank you for the report. We will fix it but it is not top priority.
