### ISSUE TITLE
broken link to README on 26.2 release news

### ISSUE THREAD

**Issue by Dieken** [erlang/otp#7954]
https://www.erlang.org/news/166

```
For details about bugfixes and potential incompatibilities see the [Erlang 26.2 README](https://erlang.org/download/otp_src_26.2.readme)
```

The link works for versions <= 26.1,  it should be changed to https://erlang.org/download/OTP-26.2.README
 starting from version 26.2.

**Comment by garazdawi** [comment]
I [updated the link](https://github.com/erlang/erlang-org/commit/a395ad551013e570eee5683c45a07f03154acb29), but the readme in the format linked should exist. Will check why it does not.
