### ISSUE TITLE
Dtls listen using inet and inet6 without {ip,ListenIP} override record in ets dtls_listener_sup

### ISSUE THREAD

**Issue by obi458** [erlang/otp#7955]
**Describe the bug**
When listen on same port using once inet and once inet6 without using {ip,ListenIP} will create one record in ets dtls_listener_sup

**To Reproduce**
1> application:ensure_all_started(ssl).
{ok,[crypto,asn1,public_key,ssl]}
2> spawn(fun() -> ssl:listen(0,[inet,{port,63450},{ciphers,[#{cipher => aes_256_gcm,key_exchange => psk,mac => aead,prf => sha384}]},{protocol,dtls},{versions,['dtlsv1.2']},{verify,verify_none},{psk_identity,"psk"}]) end).
3> spawn(fun() -> ssl:listen(0,[inet6,{ipv6_v6only,true},{port,63450},{ciphers,[#{cipher => aes_256_gcm,key_exchange => psk,mac => aead,prf => sha384}]},{protocol,dtls},{versions,['dtlsv1.2']},{verify,verify_none},{psk_identity,"psk"}]) end).

This gives in ets dtls_listener_sup
{{0,0,0,0},63450} {Pid1,Pid2}

**Expected behavior**
Except two records in ets dtls_listener_sup:
{{0,0,0,0},63450} {Pid1,Pid2} %inet
{{0,0,0,0,0,0,0,0},63450} {Pid3,Pid4} %inet6

**Affected versions**
Tested 25.x and 26.1.x

**Comment by IngelaAndin** [comment]
Thank you for reporting it. We will fix it but will not be top priority.
