### ISSUE TITLE
argparse optional nargs is listed in the wrong order in usage 

### ISSUE THREAD

**Issue by dgud** [erlang/otp#7965]
```
ts@localhost 5> Cmd =  #{commands => #{"test" => #{arguments => Args}}}.
#{commands =>
      #{"test" =>
            #{arguments =>
                  [#{name => arg1},
                   #{name => extra,long => "-extra",nargs => list}]}}}
ts@localhost 6> io:format("~s~n", [argparse:help(Cmd, #{command => ["test"]})]).
Usage:
   test [--extra <extra>...] <arg1>
```

Optional **nargs** must come after `<arg1>` since arg1 is not prefixed with `-`.

Should be 
```
Usage:
    test <arg1> [--extra <extra>...]
```

**Comment by max-au** [comment]
From the looks of it, #7934 (and corresponding (#7945) fixes the problem.

**Comment by rlipscombe** [comment]
> Optional nargs must come after <arg1> since arg1 is not prefixed with -.

Clarifying question: this is because `nargs` could be mistaking for positional args?

Yeah, my change probably fixes the usage instructions (I'll trust @max-au on this), but -- maybe -- it's worth a PR to guard against regression in this specific case, and to check the behaviour, if there's not already a test for that as well.

**Comment by dgud** [comment]
in    `prog  --nargs 1 2 3 posarg1 posarg2`  
there is no way of knowing when nargs ends and posarg begins without going backwards, but I guess that brings other problems.

In the current code (according to doc I think) **nargs** parsing ends when encountering a new `-opt_arg`

A regression test case PR would be great, I have not tested or looked at your patch, I just took @max-au word for it.

**Comment by max-au** [comment]
>  nargs parsing ends when encountering a new

It depends on the `nargs` parameter. If it is a positive number, it will consume the specified number of arguments (regardless of whether they are prefixed with `-` or not). But if it is `list` or `nonempty_list`, then yes, it will scan the following arguments until it hits the parameter starting with a prefix.
