### ISSUE TITLE
CT logs: Include time spent in run html page

### ISSUE THREAD

**Issue by essen** [erlang/otp#7972]
**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**
The CT log file `ct_run.***@***.***/index.html`:
![Screenshot from 2023-12-19 11-48-20](https://github.com/erlang/otp/assets/141739/c7d28c7d-51cd-4208-988d-b58d1ff10890)

... should include a column for the total time to run each test suite (the time at the bottom of the suite's html file):
![Screenshot from 2023-12-19 11-48-40](https://github.com/erlang/otp/assets/141739/14042a48-8a9c-495d-93b0-d1e9049b319c)

This will make each line contain the same information that is at the bottom of the suite's html file and help notice which test suites take longer a lot quicker.

**Describe alternatives you've considered**
Going through each test suite file manually and scrolling to the bottom.

**Additional context**
It's just a small thing I noticed was missing when looking at improving test times.

**Comment by u3s** [comment]
Suggestion makes sense.
