### ISSUE TITLE
`dialyzer`'s documentation missing description for option `unknown`

### ISSUE THREAD

**Issue by kivra-pauoli** [erlang/otp#7994]
**Describe the bug**
`dialyzer` documentation doesn't mention `unknown` in its descriptive section.

Where all options from https://www.erlang.org/doc/man/dialyzer.html#type-warn_option are "mirrored" in "Warning options:", `unknown` is missing. Is this oversight? Or does the option not actually exist on the CLI (I didn't check the code)?

**To Reproduce**
Compare "Warning options:", from https://www.erlang.org/doc/man/dialyzer.html, with the type definition in https://www.erlang.org/doc/man/dialyzer.html#type-warn_option

**Expected behavior**
I'd expect the option to be somewhat documented.

**Affected versions**
Current, at least.

**Additional context**
N/A

**Comment by kikofernandez** [comment]
Hi! Thanks for raising this. `unknown` is enabled by default and only disabled when using `no_unknown`.
I have added a simple PR that documents this behavior.
Thanks

**Comment by kivra-pauoli** [comment]
Perfect. Thanks, @kikofernandez.
