### ISSUE TITLE
[windows] [wsl] [`:wx`] Screen tearing when rendering `:wx` frame inside WSL.

### ISSUE THREAD

**Issue by c4lliope** [erlang/otp#8002]
**Describe the bug**

A colleague enabled WSL on their Windows machines and ran one of my apps that uses a wxWebView.
The app came up horribly pixelated because the frame seemed to apply dimensions improperly to the frame;
some of the frame rendered outside the bounds of the window in the horizontal dimension,
and caused the vertical columns to skew badly and make the page unreadable.

![screencap_1](https://cdn.discordapp.com/attachments/1036665986008498176/1190487193580482660/image.png) ![screencap_2](https://cdn.discordapp.com/attachments/1036665986008498176/1190487543142158366/image.png)

This seems to happen also on the `:wx.demo()` inside of WSL, and had been checked both on NVIDIA and AMD graphics cards.

**To Reproduce**

On Windows, run in powershell: `wsl --install`
Inside a WSL shell (easy to access using VS Code): `iex -e ':wx.demo'` (or similar using Erlang)

**Expected behavior**
Proper rendering

**Affected versions**
Erlang 26, possibly others.
Precise `shell.nix` being used is inside codebase:
https://base.bingo/code/press/src/branch/main/shell.nix

**Comment by dgud** [comment]
Since erlang is only a wrapper on wxWidgets, I can't see how we can do anything about that.
Maybe ask questions in the wxWidgets mailing list or forum?

**Comment by c4lliope** [comment]
Re-opened as https://github.com/wxWidgets/wxWidgets/issues/24221
