### ISSUE TITLE
26.2.x source bundle has invalid sub folder name 

### ISSUE THREAD

**Issue by dantran** [erlang/otp#8005]
**Describe the bug**
After expanding the source bundle, found an otp-OTP-26.2.1/erts/test/erlc_SUITE_data/src/''$'\360\237\230\200'

**To Reproduce**

**Expected behavior**
Please correct the invalid folder accordingly

**Affected versions**
26.2.1
**Additional context**

**Comment by jhogberg** [comment]
Thanks for your report, but this is not a bug: that's a unicode emoji placed there on purpose to help test unicode support in `erlc`. Whatever tool you're using to view it just can't display it properly.
