### ISSUE TITLE
beam.smp: error while loading shared libraries: libtinfo.so.5

### ISSUE THREAD

**Issue by asarubbo** [erlang/otp#8047]
Hello,

we are using beam because of elixir. We have a compile enviroment that runs on CentOS-7 and works pretty well when you deploy the elixir app on CentOS-7.

If you try to deploy the elixir app (compiled on CentOS-7) on another enviroment like RockyLinux-9 there are link issues on beam like:

```
/root/app-0.8.9/erts-13.1.5/bin/beam.smp: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```

This obviously happens because on CentOS-7 there is `libtinfo.so.5` while on RockyLinux-9 there is `libtinfo.so.6`

So, to make this environment more portable than now, would it possible make a static link instead of a dynamic (or at least keep the default as dynamic but offer a way to make it static) ?

Thanks

**Comment by garazdawi** [comment]
Hi! You should be able to do that with our current build system. Just call `./configure LIBS=/path/to/libtinfo.a`.

**Comment by asarubbo** [comment]
I just realized that RockyLinux-9 does not provider `libtinfo.a` so I think I won't do it at least on that environment.

Anyway, since this can be a common problem, the `LIBS=...` solution should be mentioned on the install at https://www.erlang.org/doc/installation_guide/install
