### ISSUE TITLE
[Help needed] otp 26.2.2, using existing openssl

### ISSUE THREAD

**Issue by ssm6498** [erlang/otp#8118]
In otp 26.2.2 for the commit "Replace MD5 implementation used" Openssl is added.
Can I use my existing openssl package? how can i do that. earlier also i have referred my existing openssl. but here how can i do that
Help needed.

**Comment by garazdawi** [comment]
Why do you want to use your own OpenSSL for the md5 implementation?

**Comment by garazdawi** [comment]
Closing this as there should not be any need to use your own openssl md5. Feel free to re-open if you need more help.
