### ISSUE TITLE
Convert `tprof` to use trace sessions

### ISSUE THREAD

**Issue by garazdawi** [erlang/otp#8131]
**Is your feature request related to a problem? Please describe.**

With the addition of trace sessions in #8109 it would be great if `tprof` could use that API from the start so that it does not interfere with other tools. 

**Describe the solution you'd like**
There are two ways to implement this.

1. Still have a global tprof server that uses a single trace session.
2. Allow multiple tprof servers that each use separate trace sessions.

I'm not sure the extra complexity warrents allowing multiple tprof server at the same time, but it could be a neat feature.

**Comment by max-au** [comment]
I'm of course for approach (2). It's actually supported right now, you can run multiple `tprof`, there is an option `registered` that you can pass as `false`. However, there is a bit warning that says "don't do it unless you really know what you're doing" :-)
