### ISSUE TITLE
compiler: time to compile gun library with OTP-27.0-rc1 takes ~11x as long

### ISSUE THREAD

**Issue by gonzalobf** [erlang/otp#8132]
**Describe the bug**
Compiling gun library with OTP-27.0-rc1 takes around 110s in my linux x86-x64 computer while using OTP-26.2.2 only takes around 10s. I'm not sure if there is anything special with this library but I think it worth raising it here.

**To Reproduce**
OTP-26.2.2:
```
[gonzalo@zalman gun]$ time ~/bin/rebar3 compile
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling gun

real	0m9.481s
user	0m11.380s
sys	0m0.873s
```

OTP-27.0rc1:
```
[gonzalo@zalman gun]$ time ~/bin/rebar3 compile
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling gun

real	1m51.169s
user	1m50.747s
sys	0m3.768s
```

**Affected versions**
OTP-27.0-rc1

I haven't check yet what is causing the slow compilation but I'll paste here if I find it

Thank you

**Comment by frej** [comment]
Compiling with `+no_ssa_opt_alias +no_ssa_opt_destructive_update` brings it back to ~10s, so this is my fault. I'll investigate further on Monday.

**Comment by gonzalobf** [comment]
Thanks @frej :)
