### ISSUE TITLE
27.0-rc1 refc binaries consume 2 extra words

### ISSUE THREAD

**Issue by okeuday** [erlang/otp#8141]
**Describe the bug**
The extra memory consumption occurs with and without jit.

**To Reproduce**
```
cat << EOF > test_script
#!/usr/bin/env escript
%%!
-mode(compile).
main(_) ->
    RefcBinary = <<1:((64 + 1) * 8)>>,
    io:format("~p~n", [1 + erts_debug:flat_size(RefcBinary)]).
EOF
chmod +x test_script
./test_script
```
The result with `OTP-26.2.2` is 7 and the result with `OTP-27.0-rc1` is 9.

**Expected behavior**
I expected refc binary memory consumption to be the same.  More details could be added at https://www.erlang.org/doc/efficiency_guide/advanced#memory if the memory increase was intentional.

**Affected versions**
`OTP-27.0-rc1`

**Comment by bjorng** [comment]
This is not a bug. The exact implementation of Erlang terms and how much memory they consume is not part of the Erlang language specification. The Efficiency Guide is not a binding promise on how things are implemented. The sizes of Erlang terms are from Erlang/OTP 19. In some future update, we will probably update that table to refer to the current version at the time of writing.

**Comment by okeuday** [comment]
@bjorng If the memory increase in intentional, as implied by your reply, it would be helpful to have an entry in the 27.0 release notes to indicate the memory increase occurs (as a change to Erlang binaries).  That would allow people to understand performance impacts related to the extra memory consumption with the new release.
