### ISSUE TITLE
cover with native coverage with two functions in the same line is order dependent

### ISSUE THREAD

**Issue by josevalim** [erlang/otp#8159]
**Describe the bug**

cover with native coverage on OTP 27 with two functions in the same line returns different results based on the order the functions are called.

**To Reproduce**

Take the following file `foo.erl`:

```erlang
-module(foo).
-export([bar/0, baz/0]).

bar() -> ok. baz() -> not_ok.
```

and now the `erl` session:

```erlang
1> cover:compile_module("foo").
{ok,foo}
2> foo:bar().
ok
3> cover:analyse().
{result,[{{foo,bar,0},{0,1}},{{foo,baz,0},{0,1}}],[]}
```

Notice how it says none of the functions are covered. Erlang/OTP 26 would return `{result,[{{foo,bar,0},{1,0}},{{foo,baz,0},{0,1}}],[]}` instead.

Now check out this new `erl` session:

```erlang
1> cover:compile_module("foo").
{ok,foo}
2> foo:baz().
ok
3> cover:analyse().
{result,[{{foo,bar,0},{1,0}},{{foo,baz,0},{1,0}}],[]}
```

Now it shows *both* as covered, even if `foo:bar()` was never called.

I have tried to isolate this using only the coverage API and I could not reproduce. The coverage API would correctly return:

```
1> foo:bar(), code:get_coverage(line, foo).
[{4,1},{4,0}]
```

Once I started debugging cover, I found this line:

https://github.com/erlang/otp/blob/423f65167a42884c1fc12ac36c46c85fd7c16071/lib/tools/src/cover.erl#L2284

Which explains the error: if you have several functions in the same line, the last one will always win. Perhaps `get_coverage(line, Mod)` should also return the function the coverage pertains to? And then we match that against the `function` and `arity` in `#bump`?

**Expected behavior**

Erlang/OTP 26 returns `{result,[{{foo,bar,0},{1,0}},{{foo,baz,0},{0,1}}],[]}`.

**Affected versions**

27 RC1.

**Additional context**

Thank you for Erlang 27!

**Comment by josevalim** [comment]
> Perhaps get_coverage(line, Mod) should also return the function the coverage pertains to? And then we match that against the function and arity in #bump?

I just realized that the fix is simpler than that. Instead of using `maps:from_list/1`, we can do a `lists:foldl/3 + maps:update_with/4`. :)

**Comment by bjorng** [comment]
Thanks for your bug report. Fixed in the linked pull request.
