### ISSUE TITLE
[documentation] Missing description of rules for record field initializers

### ISSUE THREAD

**Issue by RobinMorisset** [erlang/otp#8166]
**Describe the bug**
The documentation for records (https://www.erlang.org/doc/reference_manual/records) only says that "Each field can be given an optional default value". But some expressions are not allowed in there, for example trying to put any default value that includes a variable fails:
```erlang
-record(my_name, { my_field_name = begin X = 42, X end}).
```
results in
```
test.erl:3:42: variable 'X' in record definition
```

I'd like to add the relevant restrictions to the documentation for tool makers. Is it only variables that are forbidden?

**Comment by bjorng** [comment]
Yes, only variables are forbidden. I will update the reference manual.
