### ISSUE TITLE
Code behaves differently in the presence of erlang:display/1

### ISSUE THREAD

**Issue by josevalim** [erlang/otp#8187]
**Describe the bug**

I believe this is either a compiler or a runtime bug. Take the following code:

```erlang
-module(foo).
-export([rows/1]).

first(Fst, _Snd) -> Fst.

rows(Num) -> create_rows(Num, [[1]]).

create_rows(1, Rows) ->
  Rows;
create_rows(Num, [PrevRow | _] = Rows) ->
  [_PrevRowH | PrevRowT] = PrevRow,
  % erlang:display(PrevRowT),
  [] = first(PrevRowT, PrevRow),
  create_rows(Num - 1, [[1] | Rows]).
```

The assertion `[] = first(PrevRowT, PrevRow)` should never fail, because we always append a list with one element at the top of Rows, which means `PrevRowT` is always an empty list. However, once we invoke, it fails:

```
$ erl
1> c(foo).
{ok,foo}
2> foo:rows(3).
** exception error: no match of right hand side value [[1]]
     in function  foo:create_rows/2 (foo.erl, line 13)
```

Adding `erlang:display/1` "fixes" the issue, which makes me think of a compiler or runtime bug. :)

**Affected versions**

I have verified on OTP 26.0, 26.1, and 27-RC.

**Additional context**

Originally reported here: https://github.com/elixir-lang/elixir/issues/13368

**Comment by wojtekmach** [comment]
FWIW not just `erlang:display`, same behaviour with `self() ! hello`:

```erlang
-module(foo).
-export([rows/1]).

first(Fst, _Snd) -> Fst.

rows(Num) -> create_rows(Num, [[1]]).

create_rows(1, Rows) ->
  Rows;
create_rows(Num, [PrevRow | _] = Rows) ->
  [_PrevRowH | PrevRowT] = PrevRow,
  self() ! hello,
  [] = first(PrevRowT, PrevRow),
  create_rows(Num - 1, [[1] | Rows]).
```
