### ISSUE TITLE
Using emu-style coverage on a JIT-compiled VM

### ISSUE THREAD

**Issue by the-mikedavis** [erlang/otp#8214]
Currently native coverage is used whenever the VM is compiled with the JIT flavor. But the old way of doing coverage (i.e. injecting `counters:add/3`) must be kept around for the emu flavor. It would be useful for us to be able to use the `counters` style of coverage even on a JIT enabled VM. We rely on the `counters` coverage in [rabbitmq/horus](https://github.com/rabbitmq/horus) to get coverage on "standalone functions" even though they are technically a different module than the module in which they are defined. By preserving the `counters:add/3` instructions we count executions of standalone functions towards their original modules. Our use-case is a little bit of a hack but `counters` coverage already needs to stick around for emu and I think it would take a very small change to enable this: we could replace [`cover:has_native_coverage/0`](https://github.com/erlang/otp/blob/ab7b354c37dac92704faac4551939662d7ff5a73/lib/tools/src/cover.erl#L3000-L3001) with a helper

```erl
use_native_coverage() ->
    code:coverage_support() andalso application:get_env(cover, use_native_coverage, true).
```

What do you think (\cc @bjorng)? I could submit a PR if you are interested.

**Comment by bjorng** [comment]
Sounds reasonable. Please submit a pull request.

**Comment by the-mikedavis** [comment]
I looked into adding this like in the snippet above but it isn't as simple as I thought. There wouldn't be a way to configure rebar to compile sources with native coverage turned off without changes to rebar I believe. It also makes it possible to compile and load some modules using native coverage and others using emulator-style coverage, which breaks some of `cover`'s assumptions. So I think this would be a larger change than I thought and I'm not sure it's worth the effort to fix our rather hacky use-case, so I will close this out.

Sorry for the noise!
