### ISSUE TITLE
`simple_one_for_one` supervisor crashes during shutdown if a restarted transient child returns `ignore` from `init`

### ISSUE THREAD

**Issue by zerth** [erlang/otp#8215]
**Describe the bug**
If a restarted transient `simple_one_for_one` child returns `ignore` from `init/1`, its supervisor will continue to track its pid as `undefined`, which later crashes the supervisor during shutdown:
```
=ERROR REPORT==== 1-Mar-2024::11:52:22.792128 ===
** Generic server thingy_sup terminating 
** Last message in was {'EXIT',<0.292.0>,shutdown}
** When Server state == {state,
                            {local,thingy_sup},
                            simple_one_for_one,
                            {[thingy],
                             #{thingy =>
                                   {child,undefined,thingy,
                                       {thingy,start_link,[worker]},
                                       transient,false,5000,worker,
                                       [thingy]}}},
                            {maps,#{undefined => [worker]}},
                            1,5,
                            [-576460680],
                            0,never,thingy,
                            [sup]}
** Reason for termination ==
** {function_clause,[{supervisor,'-terminate_dynamic_children/1-inlined-0-',
                                 [undefined,#{}],
                                 [{file,"supervisor.erl"},{line,1000}]},
                     {maps,fold_1,4,[{file,"maps.erl"},{line,416}]},
                     {supervisor,terminate_dynamic_children,1,
                                 [{file,"supervisor.erl"},{line,999}]},
                     {gen_server,try_terminate,3,
                                 [{file,"gen_server.erl"},{line,1125}]},
                     {gen_server,terminate,10,
                                 [{file,"gen_server.erl"},{line,1321}]},
                     {proc_lib,init_p_do_apply,3,
                               [{file,"proc_lib.erl"},{line,241}]}]}
```

**To Reproduce**
```
-module(thingy).
-compile([nowarn_export_all,export_all]).
-behaviour(supervisor).
-behaviour(gen_server).

-define(SUP, thingy_sup).
-define(SERVER, thingy).

go() ->
    {ok, Sup} = ?MODULE:start_link(),
    {ok, Wrk} = supervisor:start_child(Sup, []),
    exit(Wrk, kill),
    exit(self(), shutdown).

start_link() ->
    persistent_term:put({?MODULE, can_start}, true),
    supervisor:start_link({local, ?SUP}, ?MODULE, [sup]).

start_link(worker) ->
    gen_server:start_link({local, ?SERVER}, ?MODULE, [worker], []).

init([sup]) ->
    SupFlags = #{strategy => simple_one_for_one,
                 intensity => 1,
                 period => 5},
    Child = #{id => ?MODULE,
              start => {?MODULE, start_link, [worker]},
              restart => transient},
    {ok, {SupFlags, [Child]}};
init([worker]) ->
    case persistent_term:erase({?MODULE, can_start}) of
        true ->
            {ok, stateless};
        false ->
            % (imagine some conditions allowing the worker to start no longer hold here)
            ignore
    end.

handle_call(_Request, _From, State) ->
    {reply, {error, not_implemented}, State}.

handle_cast(_Request, State) ->
    {noreply, State}.

handle_info(_Info, State) ->
    {noreply, State}.
```
```
> c(thingy), thingy:go().
```

**Expected behavior**
`supervisor` never crashes.

**Affected versions**
Tested on OTP 26.0.

**Comment by Maria-12648430** [comment]
@zerth non-`temporary` children in a `simple_one_for_one` supervisor mixed with `ignore`, quite the edge case you stumbled upon... I would be interested in the story behind that :sweat_smile:

**Comment by Maria-12648430** [comment]
@IngelaAndin IMO while a quick fix would be to skip `undefined` on shutdown, the correct way to fix this issue would be to drop children which return `ignore` on restart from a `simple_one_for_one` supervisor, in alignment with to this passage in the docs for `start_child/2`:

> For a simple_one_for_one supervisor, when a child process start function returns ignore, the functions returns {ok,undefined} and no child is added to the supervisor.

The child cannot be restarted or deleted manually (as would be possible with other supervisor types), so there is no point in keeping them anyway.

**Comment by zerth** [comment]
> @zerth non-`temporary` children in a `simple_one_for_one` supervisor mixed with `ignore`, quite the edge case you stumbled upon... I would be interested in the story behind that 😅

@Maria-12648430: not much to tell; noticed this while doing stateful property-based testing (via PropEr) of a worker pool component (which has since been updated to no longer allow starting workers to return `ignore`, which in context doesn't really make sense vs crashing/error-ing).

**Comment by Maria-12648430** [comment]
@zerth ok... speaking without any real context, there is a difference between returning `ignore` and erroring if you kept the restart strategy at `transient` (or `permanent` for that matter). The reason for the restart attempt itself is that a child crashed. If it returns `ignore` on restart, it means sth like "I can't (re-)start, but that's ok" and the supervisor will not try again. If it returns an `error` tuple, it means sth like "I can't (re-)start, aaaaargh!" and the supervisor will try again, until it either succeeds in restarting or hits the intensity limit :woman_shrugging:
