### ISSUE TITLE
charlist() Subject in re:split/2

### ISSUE THREAD

**Issue by ansd** [erlang/otp#8237]
**Describe the bug**
`re` Subject does not accept char list.

**To Reproduce**
```
1> re:split("ab🐇","b").
** exception error: bad argument
     in function  re:split/2
        called as re:split([97,98,128007],"b")
        *** argument 1: not an iodata term
```

**Expected behavior**
Subject "ab🐇" gets split by "b".

**Affected versions**
26.2.2

**Additional context**
The function spec says Subject can be `unicode:charlist()`:
```
       split(Subject, RE) -> SplitList
              Types:
                 Subject = iodata() | unicode:charlist()
                 RE = mp() | iodata()
                 SplitList = [iodata() | unicode:charlist()]
```
and:
```
       charlist() =
           maybe_improper_list(char() | unicode_binary() | charlist(),
                               unicode_binary() | [])
```
and
```
       char() = 0..1114111
              An ASCII character or a unicode codepoint presented by an integer.
```

So, either the documentation or the implementation is wrong?

**Comment by garazdawi** [comment]
You need to supply the `unicode` option.

```erlang
1> re:split("ab🐇","b",[unicode]).
[<<"a">>,<<240,159,144,135>>]
```

It is explained in [the docs](https://www.erlang.org/doc/man/re.html#split-3).

>As in [run/3](https://www.erlang.org/doc/man/re.html#run-3), an mp() compiled with option unicode requires Subject to be a Unicode charlist(). If compilation is done implicitly and the unicode compilation option is specified to this function, both the regular expression and Subject are to be specified as valid Unicode charlist()s.

If you think the documentation could be clearer about this a PR improving it would be most welcome.
