### ISSUE TITLE
missing otp_src_25.3.2.10.tar.gz and otp_doc_html_25.3.2.10.tar.gz for 25.3.2.10 release

### ISSUE THREAD

**Issue by chenrui333** [erlang/otp#8272]
👋 missing some artifacts for 25.3.2.10 release, raise this issue for some awareness. Thanks!

**Comment by garazdawi** [comment]
It was not added because [this](https://github.com/erlang/otp/actions/runs/8261148462) github actions run was not successful. I will fix that and upload the proper artifacts.

**Comment by garazdawi** [comment]
fixed
