### ISSUE TITLE
Infinite loop in beam_ssa_destructive_update

### ISSUE THREAD

**Issue by jhogberg** [erlang/otp#8281]
The following code throws the destructive update pass into an infinite loop:

```erlang
-module(t).
-export([f/0]).

-record(rec, {a, b = ext:ernal()}).

f() -> g({#rec{}}).

g({A}) -> g(A);
g(#rec{} = A) -> A#rec{ a = a }.
```

I'm uncertain about the best way to deal with this, could you have a look @frej?

**Comment by frej** [comment]
Looking.
