### ISSUE TITLE
failing to load NIF library from crypto

### ISSUE THREAD

**Issue by MessageMap** [erlang/otp#8290]
**Describe the bug**
I can't make https calls with latest master.

current commit:
$ git log | head -n 4
commit 777936c2c4cc1d0d8ece5b4fa4126f00b2545281
Merge: fe68bf32ce 6602e1312f
Author: Lukas Larsson <lukas@erlang.org>
Date:   Mon Mar 18 20:54:01 2024 +0100

I am running Fedora 39, configure information:
 1000  cd src/otp/
 1001  sudo dnf install openssl-devel
 1002  sudo dnf install gcc gcc-c++ make ncurses-devel perl m4 
 1003  ./configure --with-ssl=/usr
 1005  make
 1006  sudo make install

Config info for crypto:
=== Running configure in /home/ethan/src/otp/lib/crypto ===
./configure --disable-option-checking --cache-file=/dev/null --srcdir="/home/ethan/src/otp/lib/crypto"
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking for mixed mingw-gcc and native VC++ environment... no
checking for mixed cygwin and native MinGW environment... no
checking if we mix cygwin with any native compiler... no
checking if we mix msys with another native compiler... no
checking if we mix WSL with another native compiler... no
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for gcc option to enable large file support... none needed
checking for gcc option for timestamps after 2038... none needed
checking for native win32 threads... no
checking for pthread_create in -lpthread... yes
checking for getconf... getconf
checking for Native POSIX Thread Library... yes
checking for nptl/pthread.h... no
checking for pthread.h... yes
checking for pthread/mit/pthread.h... no
checking if we can add -Wdeclaration-after-statement to DED_WARN_FLAGS (via CFLAGS)... yes
checking if we can add -Werror=return-type to DED_WERRORFLAGS (via CFLAGS)... yes
checking if we can add -Werror=implicit to DED_WERRORFLAGS (via CFLAGS)... yes
checking if we can add -Werror=undef to DED_WERRORFLAGS (via CFLAGS)... yes
checking if we can add -fno-common to DED_CFLAGS (via CFLAGS)... yes
checking if we can add -fno-strict-aliasing to DED_CFLAGS (via CFLAGS)... yes
checking for ld... gcc
checking for static compiler flags... -Werror=undef -Werror=implicit -Werror=return-type  -Wdeclaration-after-statement -Wall -Wstrict-prototypes -Wmissing-prototypes  -D_THREAD_SAFE -D_REENTRANT -DPOSIX_THREADS -D_POSIX_THREAD_SAFE_FUNCTIONS -fno-strict-aliasing -fno-common -g -O2  -D_GNU_SOURCE -DSTATIC_ERLANG_NIF -DSTATIC_ERLANG_DRIVER
checking for basic compiler flags for loadable drivers... -fno-strict-aliasing -fno-common -g -O2 -D_GNU_SOURCE -fPIC
checking for compiler flags for loadable drivers... -Werror=undef -Werror=implicit -Werror=return-type  -Wdeclaration-after-statement -Wall -Wstrict-prototypes -Wmissing-prototypes  -D_THREAD_SAFE -D_REENTRANT -DPOSIX_THREADS -D_POSIX_THREAD_SAFE_FUNCTIONS -fno-strict-aliasing -fno-common -g -O2 -D_GNU_SOURCE -fPIC
checking for linker for loadable drivers... gcc
checking for linker flags for loadable drivers... -shared -Wl,-Bsymbolic
checking for 'runtime library path' linker flag... -Wl,-R
checking for multiarch directory... not found
checking size of void *... 8
checking for static zlib... no
checking how to run the C preprocessor... gcc -E
checking for egrep -e... /usr/bin/grep -E
checking for OpenSSL crypto library with version >= 0.9.8c in standard locations... dynamic crypto library in /usr/lib64
checking for runtime library path to use... /usr/lib64:/usr/local/lib64:/usr/sfw/lib64:/opt/local/lib64:/usr/pkg/lib64:/usr/local/openssl/lib64:/usr/local/opt/openssl/lib64:/opt/homebrew/opt/openssl/lib64:/usr/lib/openssl/lib64:/usr/openssl/lib64:/usr/local/ssl/lib64:/usr/lib/ssl/lib64:/usr/ssl/lib64:/lib64:/usr/local/lib/:/usr/sfw/lib/:/usr/lib/:/opt/local/lib/:/usr/pkg/lib/:/usr/local/openssl/lib/:/usr/local/opt/openssl/lib/:/opt/homebrew/opt/openssl/lib/:/usr/lib/openssl/lib/:/usr/openssl/lib/:/usr/local/ssl/lib/:/usr/lib/ssl/lib/:/usr/ssl/lib/:/lib/:/usr/local/lib:/usr/sfw/lib:/usr/lib:/opt/local/lib:/usr/pkg/lib:/usr/local/openssl/lib:/usr/local/opt/openssl/lib:/opt/homebrew/opt/openssl/lib:/usr/lib/openssl/lib:/usr/openssl/lib:/usr/local/ssl/lib:/usr/lib/ssl/lib:/usr/ssl/lib:/lib
checking for gcc options needed to detect all undeclared functions... none needed
checking whether CRYPTO_memcmp is declared... yes
checking whether CRYPTO_memcmp can be linked... yes
configure: creating ./config.status
config.status: creating c_src/x86_64-pc-linux-gnu/Makefile

**To Reproduce**
```
Erlang/OTP 27 [RELEASE CANDIDATE 1] [erts-14.2.3] [source] [64-bit] [smp:48:48] [ds:48:48:10] [async-threads:1] [jit:ns]

Eshell V14.2.3 (press Ctrl+G to abort, type help(). for help)
1> inets:start(),
   ssl:start(), 
   {ok, {_, _, Response}} = httpc:request(get, {"https://www.google.com/", []}, [], []),
   io:format("Google Response: ~p~n", [Response]).
=ERROR REPORT==== 20-Mar-2024::22:29:53.864677 ===
Unable to load crypto library. Failed with error:
"load_failed, Failed to load NIF library: '/usr/local/lib/erlang/lib/crypto-5.4.1/priv/lib/crypto.so: undefined symbol: EVP_sm4_cbc, version OPENSSL_3.0.0'"
OpenSSL might not be installed on this system.

=WARNING REPORT==== 20-Mar-2024::22:29:53.871528 ===
The on_load function for module crypto returned:
{error,{load_failed,"Failed to load NIF library: '/usr/local/lib/erlang/lib/crypto-5.4.1/priv/lib/crypto.so: undefined symbol: EVP_sm4_cbc, version OPENSSL_3.0.0'"}}

** exception error: no match of right hand side value {error,{failed_connect,[{to_address,{"www.google.com",443}},
                                                                              {inet,[inet],
                                                                                    {eoptions,{undef,[{crypto,supports,[],[]},
                                                                                                      {tls_record,sufficient_support,1,
                                                                                                                  [{file,"tls_record.erl"},{line,723}]},
                                                                                                      {tls_record,supported_protocol_versions,1,
                                                                                                                  [{file,"tls_record.erl"},{line,363}]},
                                                                                                      {tls_record,supported_protocol_versions,0,
                                                                                                                  [{file,"tls_record.erl"},{line,351}]},
                                                                                                      {ssl,default_versions,1,[{file,"ssl.erl"},{line,3513}]},
                                                                                                      {ssl,opt_versions,3,[{file,"ssl.erl"},{line,3502}]},
                                                                                                      {ssl,process_options,3,[{file,"ssl.erl"},{line,3423}]},
                                                                                                      {ssl,handle_options,5,[{file,"ssl.erl"},{line,3457}]}]}}}]}}
2> 
```
**Expected behavior**
I can't connect to anything over https

**Affected versions**
OTP 27 master

**Additional context**
I am not sure if I am missing a install from dnf

but this is the openssl build info:
$ openssl version -a
OpenSSL 3.1.1 30 May 2023 (Library: OpenSSL 3.1.1 30 May 2023)
built on: Thu Aug 31 00:00:00 2023 UTC
platform: linux-x86_64
options:  bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64   -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer  -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wno-complain-wrong-lang -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wa,--noexecstack -Wa,--generate-missing-build-notes=yes -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -specs=/usr/lib/rpm/redhat/redhat-package-notes -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -DPURIFY -DDEVRANDOM="\"/dev/urandom\"" -DREDHAT_FIPS_VERSION="\"3.1.1-c73d659c6982ad92\"" -DSYSTEM_CIPHERS_FILE="/etc/crypto-policies/back-ends/openssl.config"
OPENSSLDIR: "/etc/pki/tls"
ENGINESDIR: "/usr/lib64/engines-3"
MODULESDIR: "/usr/lib64/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_ia32cap=0x7ffef3ffffebffff:0x37ab

let me know if you need other info

**Comment by mikpe** [comment]
I can't reproduce. With Fedora 39 on x86_64, openssl{,-devel}-3.1.1-4.fc39, and OTP-27.0-rc2 `crypto` appears fine:
```
4> {ok, {_, _, Response}} = httpc:request(get, {"https://www.google.com/", []}, [], []).
{ok,{{"HTTP/1.1",200,"OK"},
...
```
One difference is that I don't pass `--with-ssl=/usr` to `./configure`, only my private `--prefix=...`

**Comment by MessageMap** [comment]
Ok thank you for checking, going to do some changes to my setup.

I did run make test and seeing other NIF errors.  will clean my local build thanks!!

**Comment by mikpe** [comment]
> will clean my local build thanks!!

I recommend always cleaning the build (or source, as appropriate) directory in case of unexpected issues. `rm -rf` and `git clean -ffdx` are your friends.

**Comment by MessageMap** [comment]
another PC I have build worked, fine with fedora. something is messed up with EVP_sm4_cbc, on this pc
