### ISSUE TITLE
Correct spec definition of gen_udp:open for track OTP-25.3

### ISSUE THREAD

**Issue by mats9** [erlang/otp#8313]
**Describe the bug**
Spec definition of gen_udp:open got corrected for OTP-26.2 track,, see #8158. Would it be possible to make the same correction on track OTP-25.3 also?

**To Reproduce**

**Expected behavior**

**Affected versions**
OTP-25.3.2.6

**Comment by bmk** [comment]
There is a 25 patch planned for next week. I will see if I can get it into that.

**Comment by IngelaAndin** [comment]
Pach OTP-25.3.2.11 has been released
