### ISSUE TITLE
Port exit status message isn't sent when spawning Cygwin executables

### ISSUE THREAD

**Issue by yastanotheruser** [erlang/otp#8317]
**Describe the bug**

On Windows, ports created with the `exit_status` option don't send the exit status message to connected processes when a Cygwin executable is spawned.

**To Reproduce**

On a Cygwin shell:

```console
$ erl
Erlang/OTP 26 ...
1> Cmd = erlang:open_port({spawn_executable, os:find_executable("cmd.exe")}, [{args, ["/C", "echo Hello world"]}, exit_status, use_stdio, in, binary, hide]).
#Port<0.2>
2> flush().
Shell got {#Port<0.2>,{data,<<"Hello world\r\n">>}}
Shell got {#Port<0.2>,{exit_status,0}}
ok
3> Grep = erlang:open_port({spawn_executable, os:find_executable("grep.exe")}, [{args, ["--version"]}, exit_status, use_stdio, in, binary, hide]).
#Port<0.3>
4> flush().
Shell got {#Port<0.3>,
           {data,<<"grep (GNU grep) 3.11\nPackaged by Cygwin ...">>}}
ok
```

**Expected behavior**

An `exit_status` message should always be sent to the connected process.

**Affected versions**
Erlang/OTP 26 [erts-14.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]
Erlang/OTP 27 [RELEASE CANDIDATE 2] [erts-14.2.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns] (master)

**Additional context**

I noticed this issue because the Elixir Mix CLI kept hanging on my machine when I executed it on a Cygwin terminal, but worked correctly when executed from PowerShell or the command prompt. It seems Mix hangs on Cygwin when attempting to get the output of the Cygwin Git executable, but it doesn't hang when the Windows build of Git is executed.

**Comment by yastanotheruser** [comment]
I've checked the spawn driver Windows implementation, it seems the `GetExitCodeProcess` call returns `STILL_ACTIVE` after getting EOF from the pipe read, which is actually mentioned in the `open_port` docs.

> If the port program closes its stdout without exiting, option exit_status does not work.

**Comment by garazdawi** [comment]
So I guess that means everything if working as expected?

**Comment by yastanotheruser** [comment]
The caveat is documented, but I think there should be a way to get the exit status of the program even after EOF. This is causing Elixir `System.cmd` to hang when this happens.

**Comment by josevalim** [comment]
@yastanotheruser to clarify, what you are saying is:

1. If the program first closes its stdout
2. And then it terminates

We are not getting an exit status notification. Correct?

If that's the case, can you confirm the program has indeed terminated? If you go to the Task Manager (or whatever it is called in Windows), can you confirm there is no "grep.exe" or similar hanging around? Because the root cause can be that the program is still running for some weird reason (or cygwin somehow pretends it is still running?).

**Comment by yastanotheruser** [comment]
@josevalim Exactly, but the program does exit normally. I could also reproduce it without Cygwin using this program, it closes EOF, sleeps 1 second then exits.

hello.c

```c
#include <windows.h>

static char hello[] = "hello world!\n";

int main(void)
{
	DWORD nWritten;
	HANDLE hStdOut = GetStdHandle(STD_OUTPUT_HANDLE);
	WriteFile(hStdOut, hello, sizeof(hello) - 1, &nWritten, NULL);
	CloseHandle(hStdOut);
	Sleep(1000);
	return 0;
}
```

```console
> cl hello.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30153 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

hello.c
Microsoft (R) Incremental Linker Version 14.29.30153.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:hello.exe
hello.obj
```

Erlang

```erlang
Erlang/OTP 26 [erts-14.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Eshell V14.2.2 (press Ctrl+G to abort, type help(). for help)
1> Hello = erlang:open_port({spawn_executable,"hello.exe"}, [use_stdio, exit_status, binary, hide]), timer:sleep(2000), flush().
Shell got {#Port<0.2>,{data,<<"hello world!\n">>}}
ok
2>
```

Elixir

```elixir
Erlang/OTP 26 [erts-14.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.16.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Task.async(fn -> System.cmd("hello.exe", []) end) |> Task.await(5000)
** (exit) exited in: Task.await(%Task{mfa: {:erlang, :apply, 2}, owner: #PID<0.113.0>, pid: #PID<0.114.0>, ref: #Reference<0.0.14467.3109434338.2147287045.84671>}, 5000)
    ** (EXIT) time out
    (elixir 1.16.2) lib/task.ex:874: Task.await_receive/3
    iex:1: (file)
iex(1)>
```

**Comment by garazdawi** [comment]
On Unix we wait until we get SIGCHLD from the spawned process and then deliver the exit_status. We should do something similar on Windows, but don't at the moment. This is not a high priority issue for us to fix, so any help you can give would be much appriciated.
