### ISSUE TITLE
Please revisit new docs serif font use

### ISSUE THREAD

**Issue by essen** [erlang/otp#8320]
**Describe the bug**
The new docs (such as https://www.erlang.org/docs/27/apps/ssl/ssl# for example) use a Serif font.

Serif fonts are fine for books or long form content. But they do not fit tools or technical documentation. If you take a look at what is used around the tech world you will find that serif is very rarely used. There's a reason for that: sans-serif is easier on the eyes if you are not reading a big blob of text sequentially, such as when searching through documentation or reading the manual for a function. GH, SO, Slack, Google apps, RFCs and more, all use sans-serif fonts.

**Expected behavior**
Use sans-serif in the documentation.

**Additional context**
* https://www.adobe.com/creativecloud/design/discover/serif-vs-sans-serif.html
* https://www.vandelaydesign.com/serif-vs-sans-serif-fonts/

**Comment by garazdawi** [comment]
I don't really have an oppinion on this. Maybe @josevalim can shed some light on why serif is used today?

**Comment by josevalim** [comment]
I dug a bit deeper and it seems there is lately a preference in utilizing the native look and feel of the user’s operating system within web applications, especially for long content, leading to a more coherent design and better performance. GitHub does it for its Markdown stuff, ChatGPT does it too. So I pushed a similar change to ExDoc. Please give it a try and let us know how it feels.

**Comment by garazdawi** [comment]
Thanks @josevalim. Closing this for now then. We will use the new ex_doc version for the next release candidate, so if the font is still an issue we can discuss it more then.
