### ISSUE TITLE
configure fails when path contains spaces

### ISSUE THREAD

**Issue by ryutei** [erlang/otp#8323]
**Describe the bug**
configure script fails when path contains spaces

**To Reproduce**
Run configure within a path that contains some spaces. ex) "/path/to/my folder"

I have confirmed this on macOS 14. 

**Expected behavior**
Can build with no problem even if it contains blank spaces.

**Affected versions**
OTP 26.2.3

**Comment by garazdawi** [comment]
Hello! This is not something that we will fix as it is too much work for a relatively small gain. A PR adding a warning that it is not possible would be much appreciated.
