### ISSUE TITLE
Miscompilation on upcoming Erlang/OTP 27

### ISSUE THREAD

**Issue by michallepicki** [erlang/otp#8325]
**Describe the bug**
I found some code that behaves differently when comparing Erlang/OTP 27 and 26

**To Reproduce**
```erlang
-module(testmod).
-export([x/0]).

x() ->
  lists:flatmap(
    fun
      ({_, V}) when V =:= #{} orelse V =:= [] ->
        [];
      ({K, V}) ->
        [K, V]
    end,
    [{<<"interesting">>, true}]
  ).
```
returns `[]`

**Expected behavior**
On Erlang/OTP 26 I get `[<<"interesting">>, true]`

**Affected versions**
Upcoming Erlang/OTP 27 compiled from source (current master)

**Additional context**
I thought it might be related to Elixir and initially reported at https://github.com/elixir-lang/elixir/issues/13461

**Comment by michallepicki** [comment]
I found this happens with more values, not only `true` - also other atoms and integers

**Comment by bjorng** [comment]
Thanks! The linked pull request resolves the issue.
