### ISSUE TITLE
Inconsistent Ordering of Mnesia Table Events Received by Subscribing Process

### ISSUE THREAD

**Issue by enirood-p** [erlang/otp#8333]
**Describe the bug**

When multiple rows of a table are updated within a single transaction, we've observed an inconsistency in the order of table events received by subscribing processes. Specifically, the order of events received by subscribing processes does not consistently match the order in which updates were performed within the transaction.

**To Reproduce**

- Process `p1` subscribes to Mnesia table events for table `t1`
- Another process initiates the following updates within a transaction
```
Update row1 of table t1
Update row2 of table t1
```
- If this transaction is repeated `n` times, there are instances where `p1` receives the table event for the update of `row2` before the table event for the update of `row1`

**Expected behavior**

We expect process `p1` to consistently receive table events in the exact order in which updates were executed within the transaction.

**Affected versions**

OTP 26, and it is likely present in version 25 as well.

**Additional context**

Our use case involves leveraging Mnesia table events for multiple change data capture (CDC) purposes that necessitate strict adherence to the relative ordering of events.

**Comment by dgud** [comment]
Mnesia doesn't guarantee the order of updates of independent rows in the same transactions, and the ordering is not
stored in the transaction data so it can't order them as you want. From Mnesias perspective these updates are "atomic" since
they happen in the same transaction and independent since they are on different rows (i.e. keys).

**Comment by enirood-p** [comment]
@dgud thanks for prompt reply. The documentation currently lacks clarification on this limitation, which would greatly benefit the community if it were incorporated. Also, is the ordering guaranteed when the same row is updated multiple times within a transaction?

**Comment by dgud** [comment]
You only get the last write, there is no need for mnesia to keep track of intermediate writes, they will never make it to the storage.
