### ISSUE TITLE
Rand example issue?

### ISSUE THREAD

**Issue by lhoguin** [erlang/otp#8346]
**Describe the bug**
https://github.com/erlang/otp/blob/master/lib/stdlib/src/rand.erl#L585-L601

I believe the match on 0.0 is going to produce a warning or an error asking to use +0.0 or -0.0.

**Affected versions**
All with the newly added warning/error.

**Comment by juhlig** [comment]
The example is wrong in general (double `end`), but aside from that, yes, you're right.

**Comment by RaimoNiskanen** [comment]
You are quite right.  I will fix this while reworking the `rand` module documentation after the Markdown conversion in OTP 27.

**Comment by RaimoNiskanen** [comment]
You can see the new documentation here:
https://erlang.org/documentation/doc-15.0-rc3/lib/stdlib-6.0/doc/html/rand.html

**Comment by lhoguin** [comment]
Looks good! 🚀
