### ISSUE TITLE
Could `.app.src`'s `vsn` support a file than contains a `v` as a version prefix?

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlang/otp#8359]
It's likely not uncommon that, to keep some sort of consistency, both `.app.src` and `rebar.config`'s `relx` use `{file, "VERSION"}` as input (where `VERSION` is a file that contains an Erlang supported version term).

While experimenting with this today, with file `VERSION` containing string `v0.0.0`, I saw Erlang error out: it seems it doesn't like the initial `v`.

Would it be confusing to allow having the `v` while removing it in-memory just after reading the file? This way that file could support both `v` and non-`v`, used alongside `relx`, CI and other practices where the `v` is e.g. imposed by a group of people.

Or maybe some other syntax for `.app.src` to make it explicit (e.g. `{vsn, {file_strict, "VERSION"}}` - equivalent to the current behavior - v. `{vsn, {file, "VERSION"}}` - a new behaviour)...

**Comment by garazdawi** [comment]
The handling of `.app.src` is done by relx as far as I know, so adding a `file_strict` option or changing how `file` works would be something that has to be done in `relx`. We only read the `.app` file and I think it is better if we are strict in what we read.
