### ISSUE TITLE
list seq

### ISSUE THREAD

**Issue by fiodinggo** [erlang/otp#8368]
**Describe the bug**
i have some problem in otp 26 about this
lists:seq(60,70).
-> result "<=>?@ABCDEF"
lists:seq(50,60).
-> result "23456789:;<"
lists:seq(40,50).
-> result "()*+,-./012"
lists:seq(30,40).
-> result [30,31,32,33,34,35,36,37,38,39,40]
lists:seq(70,80).
-> result "FGHIJKLMNOP"
it is good or bed?
thanx before

**Comment by garazdawi** [comment]
> it is good or bed?

It is good. Integers in a list that might be characters are printed as characters by the shell. If you don't want this you can call `application:set_env(stdlib, shell_strings, false).` in the shell.

**Comment by fiodinggo** [comment]
thanx so much for that
I think this is very helpful.
