### ISSUE TITLE
Erlang 26.2.2 with ECDSA and SHA256withECDSA signature Algorithm certificates not working

### ISSUE THREAD

**Issue by 3XC1T3D** [erlang/otp#8376]
We want to run RabbitMQ 3.13.1 with ECDSA certificates and Erlang 26.2.2. 

Docker Image: 3.12.13 (Erlang: 25.3.2.10) -> working

Docker Image: 3.13.1 (Erlang: 26.2.2)       -> not working

When the client side wants to connect to the rabbitmq server / erlang server we are getting a lot of following Erlang errors:

```
2024-04-10 08:34:38.552513+02:00 [notice] <0.2402.0> TLS server: In state hello at ssl_handshake.erl:1749 generated SERVER ALERT: Fatal - Insufficient Security
2024-04-10 08:34:38.552513+02:00 [notice] <0.2402.0>  - no_suitable_signature_algorithm
```

Do you have some hints, where we could have the issue? Or is it maybe a Erlang 26.2.2 Bug?

Because with erlang 25 everything works like a charme. 

We have testesd our SSL Setup with https://testssl.sh/ and Result of the says, everything is fine with our ECDSA certificates.

Also we have checked if our erlang supports tls 1.2 with the specific cipher.

**Comment by IngelaAndin** [comment]
Are your certificates signed whit ECDSA and SHA (SHA-1)?  Because then you need to customize the supported signature algorithms in  OTP-26 as SHA-1 support was removed from default values.

**Comment by 3XC1T3D** [comment]
Hi @IngelaAndin ,

thank you for your reply. No that we are aware of. We created it with SHA256. Is it the SHA1 fingerprint? :see_no_evil: 

Here is a part of the result from the testssh.sh Script:

```
...
 Testing robust (perfect) forward secrecy, (P)FS -- omitting Null Authentication/Encryption, 3DES, RC4                                                                                                                                                                            
                                                                                                                                                                                                                                                                                  
 PFS is offered (OK)          ECDHE-ECDSA-AES256-GCM-SHA384 ECDHE-ECDSA-AES128-GCM-SHA256                                                                                                                                                                                         
 Elliptic curves offered:     sect163k1 sect163r1 sect163r2 sect193r1 sect193r2 sect233k1 sect233r1 sect239k1 sect283k1 sect283r1 sect409k1 sect409r1 sect571k1 sect571r1 secp160k1 secp160r1 secp160r2 secp192k1 prime192v1 secp224k1 secp224r1 secp256k1 prime256v1 secp384r1   
                              secp521r1 brainpoolP256r1 brainpoolP384r1 brainpoolP512r1                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                  
 Testing server preferences                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                  
 Has server cipher order?     yes (OK)                                                                                                                                                                                                                                            
 Negotiated protocol          TLSv1.2                                                                                                                                                                                                                                             
 Negotiated cipher            ECDHE-ECDSA-AES256-GCM-SHA384, 570 bit ECDH (B-571)                                                                                                                                                                                                 
 Cipher order                                                                                                                                                                                                                                                                     
    TLSv1.2:   ECDHE-ECDSA-AES256-GCM-SHA384 ECDH-ECDSA-AES256-GCM-SHA384 ECDH-RSA-AES256-GCM-SHA384 ECDHE-ECDSA-AES128-GCM-SHA256 ECDH-ECDSA-AES128-GCM-SHA256 ECDH-RSA-AES128-GCM-SHA256                                                                                        
                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                  
 Testing server defaults (Server Hello)                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                  
 TLS extensions (standard)    "renegotiation info/#65281" "EC point formats/#11" "max fragment length/#1"                                                                                                                                                                         
 Session Ticket RFC 5077 hint no -- no lifetime advertised                                                                                                                                                                                                                        
 SSL Session ID support       yes                                                                                                                                                                                                                                                 
 Session Resumption           Tickets no, ID: yes                                                                                                                                                                                                                                 
 TLS clock skew               -1 sec from localtime                                                                                                                                                                                                                               
 Signature Algorithm          ECDSA with SHA256                                                                                                                                                                                                                                   
 Server key size              EC 256 bits                                                                                                                                                                                                                                         
 Server key usage             Digital Signature, Key Encipherment, Key Agreement                                                                                                                                                                                                  
 Server extended key usage    TLS Web Server Authentication                                                                                                                                                                                                                       
 Serial                       C715BC7B0CCD5739 (OK: length 8)                                                                                                                                                                                                                     
 Fingerprints                 SHA1 19EF2096027ABF9CA2E68CE12628F9EACD9B847B                                                                                                                                                                                                       
                              SHA256 6BF4D20BA5C4C92662D35A36186EC162016609BC492D5809F382E437C5EAB8D7                                                                                                                                                                             
 Common Name (CN)             <hostname>                                                                                                                                                                                                                          
....
```

**Comment by IngelaAndin** [comment]
Could you try trace the function ssl_handshake:do_select_hashsign/3 ?

```
dbg:tarcer().
dbg:tp(all, [call]).
dbg:tpl(ssl_handshake, do_select_hashsign, cx).


```

**Comment by 3XC1T3D** [comment]
i dont know if i can configure trace logging for erlang in the rabbitmq docker image - i will check.

**Comment by 3XC1T3D** [comment]
Hi @IngelaAndin ,

we have activated tracing on the rabbitmq Docker Container through following command:

```
docker exec -ti rabbitmq-3.13.1 rabbitmqctl eval 'dbg:tracer(process, {fun(Msg) -> io:format("~p~n", [Msg]) end, []}), dbg:p(all, c), dbg:tpl(ssl_handshake,do_select_hashsign, cx).'
```

**Both Docker Container are running with the exact same parameters and the exact same certificates.
We are creating the certificate with SHA256withECDSA and secp256r1 as curve.**

here is the result of the trace you asked under OTP 26.2.2

```
2024-04-15 15:02:41.420631+02:00 [notice] <0.745.0> TLS server: In state hello at ssl_handshake.erl:1749 generated SERVER ALERT: Fatal - Insufficient Security
2024-04-15 15:02:41.420631+02:00 [notice] <0.745.0>  - no_suitable_signature_algorithm
** dbg got EXIT - terminating: {trace_handler_crashed,
                                {{badarity,
                                  {#Fun<erl_eval.42.105768164>,
                                   [{trace,<0.758.0>,call,
                                     {ssl_handshake,do_select_hashsign,
                                      [[ecdsa_secp256r1_sha256,
                                        ecdsa_secp384r1_sha384,
                                        ecdsa_secp521r1_sha512,eddsa_ed25519,
                                        eddsa_ed448,rsa_pss_rsae_sha256,
                                        rsa_pss_rsae_sha384,
                                        rsa_pss_rsae_sha512,
                                        rsa_pss_pss_sha256,rsa_pss_pss_sha384,
                                        rsa_pss_pss_sha512,rsa_pkcs1_sha256,
                                        rsa_pkcs1_sha384,rsa_pkcs1_sha512,
                                        {sha256,dsa},
                                        {sha224,ecdsa},
                                        {sha224,rsa},
                                        {sha224,dsa},
                                        ecdsa_sha1,rsa_pkcs1_sha1,
                                        {sha,dsa}],
                                       ecdsa,
                                       [{sha512,ecdsa},
                                        {sha512,rsa_pss_pss},
                                        {sha512,rsa_pss_rsae},
                                        {sha512,rsa},
                                        {sha384,ecdsa},
                                        {sha384,rsa_pss_pss},
                                        {sha384,rsa_pss_rsae},
                                        {sha384,rsa},
                                        {sha256,ecdsa},
                                        {sha256,rsa_pss_pss},
                                        {sha256,rsa_pss_rsae},
                                        {sha256,rsa}]]},
                                     {tls_handshake,handle_client_hello,5,
                                      {"tls_handshake.erl",357}}},
                                    []]}},
                                 [{dbg,invoke_handler,3,
                                   [{file,"dbg.erl"},{line,887}]},
                                  {dbg,invoke_handler,3,
                                   [{file,"dbg.erl"},{line,886}]},
                                  {dbg,handle_traces,4,
                                   [{file,"dbg.erl"},{line,876}]},
                                  {dbg,tracer_loop,2,
                                   [{file,"dbg.erl"},{line,838}]}]}}
```

here is the result of the trace you asked under OTP 25.3.2.10:

```
....
** dbg got EXIT - terminating: {trace_handler_crashed,
                                {{badarity,
                                  {#Fun<erl_eval.42.3316493>,
                                   [{trace,<0.865.0>,call,
                                     {ssl_handshake,do_select_hashsign,
                                      [[{sha256,ecdsa},
                                        {sha384,ecdsa},
                                        {sha512,ecdsa},
                                        {sha256,rsa_pss_rsae},
                                        {sha384,rsa_pss_rsae},
                                        {sha512,rsa_pss_rsae},
                                        {sha256,rsa_pss_pss},
                                        {sha384,rsa_pss_pss},
                                        {sha512,rsa_pss_pss},
                                        {sha256,rsa},
                                        {sha384,rsa},
                                        {sha512,rsa},
                                        {sha256,dsa},
                                        {sha224,ecdsa},
                                        {sha224,rsa},
                                        {sha224,dsa},
                                        {sha,ecdsa},
                                        {sha,rsa},
                                        {sha,dsa}],
                                       ecdsa,
                                       [{sha512,ecdsa},
                                        rsa_pss_pss_sha512,
                                        rsa_pss_rsae_sha512,
                                        {sha512,rsa},
                                        {sha384,ecdsa},
                                        rsa_pss_pss_sha384,
                                        rsa_pss_rsae_sha384,
                                        {sha384,rsa},
                                        {sha256,ecdsa},
                                        rsa_pss_pss_sha256,
                                        rsa_pss_rsae_sha256,
                                        {sha256,rsa},
                                        {sha224,ecdsa},
                                        {sha224,rsa},
                                        {sha,ecdsa},
                                        {sha,rsa},
                                        {sha,dsa}]]},
                                     {tls_handshake,handle_client_hello,5}},
                                    []]}},
                                 [{dbg,invoke_handler,3,
                                   [{file,"dbg.erl"},{line,877}]},
                                  {dbg,invoke_handler,3,
                                   [{file,"dbg.erl"},{line,876}]},
                                  {dbg,handle_traces,4,
                                   [{file,"dbg.erl"},{line,866}]},
                                  {dbg,tracer_loop,2,
                                   [{file,"dbg.erl"},{line,828}]}]}}
```

**Comment by IngelaAndin** [comment]
Humm  ... I added a commit one one of my branches that might help. Seems maybe this "naming issue" was noly solved for other algorithms.

**Comment by IngelaAndin** [comment]
@3XC1T3D I think my first thought here was wrong, I too quickly assumed it was a similar bug to a previous one and that I missed something. But I think this is a different problem. So ignore that, I will continue looking into it.

**Comment by 3XC1T3D** [comment]
@IngelaAndin thank you for your support!

**Comment by lukaseckert** [comment]
Hi @IngelaAndin 
thank you for your support in this issue. So far we've spent many hours analyzing the problem and we're still not sure if the cause lies within the Erlang VM, the RabbitMQ server that is based on it, or the Java (21) client. 
When both the (erlang) server and the (java) client are limited to TLS 1.2, the mentioned issue occurs. When both are set to TLS 1.3, the connection is successful. This hints to a problem on the client side. However with the older OTP, the same (TLS 1.2) configuration has no problems, which makes it look like an issue in the newer OTP version.

Looking at the parameters `HashSigns` and `SupportedHashSigns` of the do_select_hashsign function (https://github.com/erlang/otp/blob/b83df13eec5446beab06dd24315d37a5b0633fd2/lib/ssl/src/ssl_handshake.erl#L1709): How are these values determined? Do they come from the client hello message? Or are they determined by the certificate?
In the traces of the older and newer OTP (see above) the values of both parameters change, although the client and the certificate remain the same.

**Comment by IngelaAndin** [comment]
The first argument comes form the client hello signature_algorithms_certs extension,if sent, and otherwise it comes form the value of the  client hello extension signature_algorithm instead.  These include all algorithms that can be supported. Hopefully then which ones can be choose will also depend on the certificate. A server could potentially have more then one certificate and choose the most preferred one that the client also support the algorithms for.

**Comment by IngelaAndin** [comment]
I put a bug label for now, even though we do not yet know if it is an OTP bug or not, it makes tracking easier and I will put the special label not_bug if we conclude it is client problem.

**Comment by IngelaAndin** [comment]
Any progress in fully understanding this? You can use {log level, debug} on the server if you want to find out what exactly the client sends you.

**Comment by lukaseckert** [comment]
Hi @IngelaAndin 
last week we tried to build a minimal Erlang/OTP Https server using only the "naked" Erlang and Java JDK Docker images, so we can make sure it does not depend on any configuration oder modification by our application or the RabbitMQ server.
As a team of Java developers this proved to be harder than expected, so currently we're trying to analyze the problem using the official Erlang sample from https://github.com/erlang/docker-erlang-example
As soon as we know more, we'll post it here :)

**Comment by lukaseckert** [comment]
Hi @IngelaAndin 
finally @3XC1T3D and me have prepared a little setup to reproduce the issue. 

The code is in this fork of the docker-erlang-example repo: https://github.com/lukaseckert/docker-erlang-example

**This is what we changed:**
- removed all other samples beside "dockerwatch"
- added the small "java-ssl-client" app that is built on top the latest Eclipse Java 21 (LTS) image and simply connects to the dockerwatch server with configurable TLS parameters. The code is based on https://github.com/ChristopherSchultz/ssltest
- modified the "create-certs" script to generate an elliptic curve certificate instead of RSA
- parametrized the Dockerfile of the dockerwatch app to easily switch between Erlang 25 (works) or 26 (does not work)
- added a docker-compose.yaml file to start the whole setup (one container for the dockerwatch app, and one for the java client)

**How to test**
1. `cd` to the repository.
2. Generate the EC certificate in the `ssl` directory:
`./create-certs`
3. Build the client app image:
`docker build -t java-ssl-client java-ssl-client/`
4. Build the server app image:
`docker build --build-arg "ERLANG_VERSION=25" -t dockerwatch-server .`
5. In a separate bash in the same directory, run the Erlang server:
`docker run -d --rm --network host -v "$(pwd)/ssl:/etc/ssl/certs" --name "dockerwatch" dockerwatch-server`
6. In the original shelll, execute the client app:
    ```
    docker run --rm -ti --network host java-ssl-client java -cp /usr/src/app/classes net.christopherschultz.ssltest.SSLTest -enabledprotocols TLSv1.2 localhost:8443
    ```
    The client will now try and report all accepted/rejected ciphers:
    ```
    ....
    Rejected  TLSv1.2 TLS_DHE_DSS_WITH_AES_128_CBC_SHA
    Rejected  TLSv1.2 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    Rejected  TLSv1.2 TLS_DH_anon_WITH_AES_256_GCM_SHA384
    Given this client's capabilities ([TLSv1.2]), the server prefers protocol=TLSv1.2, cipher=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    ```
    So there is a successful handshake using **TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384**
7. Now stop the server using `docker stop dockerwatch`.
8. Repeat from step 4, with only one difference: change the `ERLANG_VERSION=25` part to `ERLANG_VERSION=26`.

Notice that now all 93 supported ciphers are rejected by the server.

**Why do we think this might be an issue of Erlang/OTP**
- The same setup works in Erlang 25.
- It might be true that Erlang 26 enforces stricter security constraints, however then one might argue that (with everything in its default configuration) a technology as popular as Java (in its most recent version) should be able to connect via TLS 1.2 by default.
- Other popular server software like Node.js, Apache Tomcat etc. do not cause issues with the EC certificate and Java clients.


Sorry for the long post, but I hope this is everything we need to really analyze the issue :)

**Comment by IngelaAndin** [comment]
@lukaseckert Thank you very much for the work, I promise I will investigate further. However there is a lot to do at the moment for upcoming release and CodeBeam conference in Stockholm so please be patient.

**Comment by IngelaAndin** [comment]
I managed to get a connection with the certs used in your example with other clients. I get the java client to fail but there is still to much things around to tell why. To be continued.

**Comment by IngelaAndin** [comment]
So here is the input form java client and  {sha256,ecdsa}  is not part of the algorithms sent in the  signature_algs_cert 
extension and the reason for the rejection of the connection. The cert is ECDSA-signed with curve secp256r1 and sha256.  Note that ecdsa_secp256r1_sha256 is a TLS-1.3 scheme only and not considered a valid input for the TLS-1.2 negotiation. 

```
<<< TLS 1.2 Handshake, ClientHello
[{client_version,{3,3}},
 {random,
     <<2,152,123,88,211,134,93,30,47,42,24,225,20,226,135,169,40,228,64,96,91,
       73,113,51,64,42,85,72,27,127,17,14>>},
 {session_id,<<>>},
 {cookie,undefined},
 {cipher_suites,["TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"]},
 {compression_methods,[0]},
 {extensions,
     #{signature_algs =>
           {hash_sign_algos,
               [{sha256,ecdsa},
                {sha384,ecdsa},
                {sha512,ecdsa},
                {sha256,rsa_pss_rsae},
                {sha384,rsa_pss_rsae},
                {sha512,rsa_pss_rsae},
                {sha256,rsa_pss_pss},
                {sha384,rsa_pss_pss},
                {sha512,rsa_pss_pss},
                {sha256,rsa},
                {sha384,rsa},
                {sha512,rsa},
                {sha256,dsa},
                {sha224,ecdsa},
                {sha224,rsa},
                {sha224,dsa},
                {sha,ecdsa},
                {sha,rsa},
                {sha,dsa}]},
       signature_algs_cert =>
           {signature_algorithms_cert,
               [ecdsa_secp256r1_sha256,ecdsa_secp384r1_sha384,
                ecdsa_secp521r1_sha512,eddsa_ed25519,eddsa_ed448,
                rsa_pss_rsae_sha256,rsa_pss_rsae_sha384,rsa_pss_rsae_sha512,
                rsa_pss_pss_sha256,rsa_pss_pss_sha384,rsa_pss_pss_sha512,
                rsa_pkcs1_sha256,rsa_pkcs1_sha384,rsa_pkcs1_sha512,
                {sha256,dsa},
                {sha224,ecdsa},
                {sha224,rsa},
                {sha224,dsa},
                ecdsa_sha1,rsa_pkcs1_sha1,
                {sha,dsa}]},
       elliptic_curves =>
           {elliptic_curves,
               [{1,3,101,110},
                {1,2,840,10045,3,1,7},
                {1,3,132,0,34},
                {1,3,132,0,35},
                {1,3,101,111}]},
       srp => undefined,
       client_hello_versions => {client_hello_versions,[{3,3}]},
       sni => undefined,alpn => undefined,
       ec_point_formats => {ec_point_formats,[0]},
       next_protocol_negotiation => undefined,
       renegotiation_info => {renegotiation_info,<<0>>}}}]
writing (7 bytes) TLS 1.2 Record Protocol, alert
0000 - 15 03 03 00 02 02 47                                ......G
=NOTICE REPORT==== 21-May-2024::16:05:09.548035 ===
TLS server: In state hello at ssl_handshake.erl:1740 generated SERVER ALERT: Fatal - Insufficient Security
 - no_suitable_signature_algorithm
```

Have you tried using your certs with openssl s_server and will it then connect with the Java server?  (I might try later but I have some other stuff that takes priority). The shift from TLS-1.2  signature support to TLS-1.3 signature schemes is quite intricate, so it might be interesting to know if other projects have an other interpretation.

**Comment by lukaseckert** [comment]
Hi @IngelaAndin 
I've tried using the certificates from the sample repo using openssl s_server:
`openssl s_server -accept 8443 -www -key dockerwatch-server.key -cert  dockerwatch-server.pem`
Using OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

The (successful) result of the Java client is like the result with Erlang 25:
`Given this client's capabilities ([TLSv1.2]), the server prefers protocol=TLSv1.2, cipher=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384`

**Comment by IngelaAndin** [comment]
@lukaseckert well in that case I think we can consider an interoperability enhancement of  translating some TLS-1.3 schemes to
TLS-1.2 signature pairs as the server is evidently capable of handling those algorithms.

**Comment by IngelaAndin** [comment]
I can scheduled it to be piggy-backed on some other 26-patch.  I can not promise any specific time it will happen as it depends on many other things not to forget summer vacations.

**Comment by IngelaAndin** [comment]
@3XC1T3D, @lukaseckert if you have possibility to verify my PR I would apricate it.

**Comment by lukaseckert** [comment]
Hi @IngelaAndin 
thank you for the fix, I was not able to verify it yet however. This is what I tried:

1. Clone this repo in the "maint" branch where you merged the fix
2. Build a Docker image from it as described in https://github.com/erlang/otp/blob/master/HOWTO/DEVELOPMENT.md#using-docker
3. Use the locally build erlang image as base image where `erlang:26` was used before.

Unfortunately the application does not launch and seems to be stuck after `/dockerwatch`
```
No cookie is set or found. This limits the scripts functionality, installing, upgrading, rpc and getting a list of versions will not work.
Exec: /dockerwatch/erts-15.0/bin/erlexec -noinput +Bd -boot /dockerwatch/releases/1.0.0/start -mode embedded -boot_var SYSTEM_LIB_DIR /dockerwatch/lib -config /dockerwatch/releases/1.0.0/sys.config -args_file /dockerwatch/releases/1.0.0/vm.args -- foreground
Root: /dockerwatch
/dockerwatch
```

I`m pretty sure that this is just a wrongly built Docker image, however I don't know an other way to create an erlang Docker image from the fixed branch 😬

**Comment by NaseerPashaR** [comment]
Hi @IngelaAndin,

In which version of Erlang OTP this fix will be available. Please let me know.

**Comment by IngelaAndin** [comment]
@NaseerPashaR It is scheduled for inclusion in next patches for OTP 26 and OTP 27 ( OTP-26.2.5.1 and  OTP-27.0.1) I can not give you a date.

**Comment by NaseerPashaR** [comment]
OK @IngelaAndin. Thanks for the information. I will follow up the Erlang Releases.

**Comment by IngelaAndin** [comment]
@NaseerPashaR it will be announced on https://erlangforums.com/ when it happens.

**Comment by NaseerPashaR** [comment]
@IngelaAndin As you have mentioned OTP-26.2.5.1 above, I have tested the Patch Package OTP 26.2.5.1 Released. I see still the same issue with ECDSA prime256v1 and secp384r1.

I see the logs as below :
2024-07-02 17:08:39.128000+05:30 [notice] <0.209358.0> TLS server: In state hello at ssl_handshake.erl:1740 generated SERVER ALERT: Fatal - Insufficient Security
2024-07-02 17:08:39.128000+05:30 [notice] <0.209358.0>  - no_suitable_signature_algorithm

Request you let me know that, Is the same version issue fixed or do you have any other specific for this fix.

**Comment by lukaseckert** [comment]
Hi @IngelaAndin 
i can confirm @NaseerPashaR`s report, using the latest RabbitMQ 3.13.4 Docker image which internally uses OTP 26.2.5.1.
https://github.com/docker-library/rabbitmq/blob/f1d6b407fa37ad6fe4de699fba2724143ff66e34/3.13/ubuntu/Dockerfile#L38

Java clients trying to reach RabbitMQ will report SSLHandshakeException: insufficient_security

**Comment by 3XC1T3D** [comment]
Hey @NaseerPashaR @IngelaAndin ,

RabbitMQ uses now OTP 26.2.5.2.

It seems that with the current OTP 26.2.5.2 Release the Issue is fixed.

Best Regards
