### ISSUE TITLE
Allow configuration of `ex_doc` through configure flag

### ISSUE THREAD

**Issue by chiroptical** [erlang/otp#8377]
**Is your feature request related to a problem? Please describe.**

I am working on adding Erlang w/ OTP 27-rc2 to nixpkgs (https://github.com/NixOS/nixpkgs/pull/303750/files). It took me some time, but I was able to find `EX_DOC` (https://github.com/erlang/otp/blob/e6d340156dc4c483293466b2c7a883c08173751e/erts/configure.ac#L475) and set it manually.

**Describe the solution you'd like**

I would like to set `--with-ex_doc=X`. Having this in `./configure --help` would increase discoverability of the setting and make building in nix land much easier.

**Describe alternatives you've considered**

I was able to use `EX_DOC` but it was hard to discover.

**Additional context**

I am happy to implement this configuration flag. I am reaching out to see if this is interesting to the project or not.

**Comment by garazdawi** [comment]
There is a list of important variables here: https://github.com/erlang/otp/blob/master/make/autoconf/otp.m4#L85-L130

I think EX_DOC should be added there. A pr would be welcome.

**Comment by chiroptical** [comment]
> There is a list of important variables here: https://github.com/erlang/otp/blob/master/make/autoconf/otp.m4#L85-L130
> 
> I think EX_DOC should be added there. A pr would be welcome.

Awesome, I'll get this done soon. Thanks for the quick response.
