### ISSUE TITLE
Is it possible to compile erlang programs into standalone executables?

### ISSUE THREAD

**Issue by fenginsc** [erlang/otp#8404]
Is it possible to compile erlang programs into standalone executables?

**Comment by garazdawi** [comment]
It is not something that we provide, but there exist third-party solutions. I suggest you ask on erlangforums and see if anyone there knows where to find them.

**Comment by garazdawi** [comment]
I've been here for 15 years and during that time there has never been an official way to do a standalone binary. There was an experiment called Stand Alone Erlang that was done around the year 2000, but that was never official nor supported.

If this is important to you, I would suggest you take an interest in the third-party projects I mentioned.

**Comment by fenginsc** [comment]
Sorry, I may have mistakenly thought that the HiPE project(https://www.erlang.org/docs/22/man/hipe_app) could compile standalone binary executables, but HiPE seems to be unsupported now.
Thank you very much for correcting the error of my statement.
