### ISSUE TITLE
Erlang 27 fails to build from source on IBM S390x architecture

### ISSUE THREAD

**Issue by sgolovan** [erlang/otp#8410]
During build of Erlang 27.0-rc3 for Debian GNU/Linus it fails to build on IBM S390x architecture (which is by the way the only big-endian architecture left officially supported by Debian). The build log can be found on [Debian buildd status page](https://buildd.debian.org/status/fetch.php?pkg=erlang&arch=s390x&ver=1%3A27.0%7Erc3%2Bdfsg-2&stamp=1713634467&raw=0), but the relevant error message is the following:

```erlang
System process <0.0.0> terminated: {{case_clause,{error,{bad_lib,"Function not found zlib:close_nif/1"}}},[{zlib,on_load,0,[]},{erl_init,start,0,[]}]}
```

The beam is succesfully compiled, but fails to start immediately given this error message. Also, build fails for powerpc, which is big-endian as well, see [the corresponding log](https://buildd.debian.org/status/fetch.php?pkg=erlang&arch=powerpc&ver=1%3A27.0%7Erc3%2Bdfsg-2&stamp=1713635333&raw=0)) with the same symptoms, so may be the problem is concerned with the endiannes.

I have removed all the Debian patches and bisected the FTBFS problem. It loos like the culprit is commit [24b0d99](https://github.com/erlang/otp/commit/24b0d99d6e595d30474e1d51e5a7ae9c9e720f3e). Before this commit Erlang builds fine on S390x, but starting with it and on any commit after it build always fails with the same error message issued by erlc.

If you neen any additional info, logs etc. I'll gladly supply it.

**Comment by sgolovan** [comment]
Hi John!

Looks like it! erlc executes fine and builds the rest of Erlang/OTP libraries.

**Comment by jhogberg** [comment]
Thank you, there must be some raw access to that field somewhere (without using the struct). I'll look into it :-)
