### ISSUE TITLE
JIT in OTP 27-RC2 passes wrong value to NIF in aarch64

### ISSUE THREAD

**Issue by alexandrejbr** [erlang/otp#8433]
**Describe the bug**
We are observing consistently in our code what seems like the wrong value is being picked up to pass to a function. This is seen only with JIT and on aarch64 (both Linux and Darwin) in OTP 27. OTP 26.2.3 works with no problems.

The code has the following structure:
```
f(Atom, {ListOfAtoms, OtherAtom}, Record) ->
    (... Pure functions are called here) 
    YetAnotherAtom = (some value obtained from calling pure functions) 
    [OtherAtom |
     case Atom of
         atomA ->
             [OtherAtom, f2(OtherAtom, YetAnotherAtom)];
         atomB ->
             ['', 0]
     end].
```

f is being called with f(atomA, {[a1], c1}, #record{...}) and we have added an io:format in f2 and we see that OtherAtom is there atomA while YetAnotherAtom has the correct value.

If we rewrite the above code to be like the following the bug disappears, and also disappears if we add an io:format or `put(something,something)` immediately after the line that creates YetAnotherAtom:

```
f(Atom, {ListOfAtoms, OtherAtom}, Record) ->
    (... Pure functions are called here) 
    YetAnotherAtom = (some value obtained from calling pure functions) 
    F2 = f2(OtherAtom, YetAnotherAtom),
    [OtherAtom |
     case Atom of
         atomA ->
             [OtherAtom, F2];
         atomB ->
             ['', 0]
     end].
```

**To Reproduce**
Unfortunately, I didn't manage to isolate the issue so I can't really provide a reproduction. Even just by exporting the function and calling it from the shell doesn't trigger the bug.

**Expected behavior**
The first argument of the f2 function should be taken from OtherAtom and not Atom.

**Affected versions**
OTP 27, we tested with RC2 and RC3 and both behave the same.

**Additional context**
I understand that this is most not enough information for you to investigate the issue, but maybe you can give me ideas on what to get you so you can understand the issue better.

**Comment by jhogberg** [comment]
Thanks for your report! If you can't share minimized code to reproduce the issue, can you try using `git bisect` to find the commit that introduced the error?

**Comment by alexandrejbr** [comment]
@jhogberg I think it's these: a16397dfde9d906e7d40898959f08d9303696d77 and 06d402a75078150963b75518ce271582bbb94897

I didn't do bisect since we have some patches on top and complicates things. I did instead  some reverts of commits that look suspicious and it was when I reverted those 2 that the problem disappeared.

**Comment by jhogberg** [comment]
Thanks, that's a humongous diff though :sweat_smile: 

Can you print out the result of `beam_disasm:file("path/to/module.beam")` to a file, and post the nearest handful instructions around the call to `f2` (as many as you're comfortable sharing)?

**Comment by jhogberg** [comment]
Thanks, does `atomA` correspond to `set_case`?

**Comment by alexandrejbr** [comment]
Yes

**Comment by jhogberg** [comment]
Thanks, can you try out https://github.com/jhogberg/otp/tree/john/jit/fix-invalid-reg-cache/GH-8433 and see if that fixes the issue?

**Comment by alexandrejbr** [comment]
Yes it does! Thank you for looking into this so fast!
