### ISSUE TITLE
Documentation Light Theme should be fully light

### ISSUE THREAD

**Issue by fififionek** [erlang/otp#8447]
**Is your feature request related to a problem? Please describe.**
In the new Documentation styling. The contrast between the almost black sidebar and the white main area makes it hard for me to read anything in the sidebar. I have to consciously mentally switch just to be able to navigate elsewhere and then switch back to read the text.
**Describe the solution you'd like**
There are three themes now, but the Light theme is identical to the default System one. I would like the Light theme use white background even for the sidebar. Or at least have light background with dark text there.

**Comment by garazdawi** [comment]
Hello! The styling is part of the [ex_doc](https://github.com/elixir/ex_doc) project, so please create an issue there and discuss with the maintainers.
