### ISSUE TITLE
Inconsistent Behavior of CPU Quotas and Online Schedulers Across Erlang Versions in Docker Containers Leads to Production Outages

### ISSUE THREAD

**Issue by eric0fw** [erlang/otp#8450]
**Describe the bug**
Inconsistent behavior in handling CPU quotas and the number of online schedulers across different Erlang/OTP versions when running in Docker containers (and k8s) with CPU limitations (`--cpus=2`). Starting from Erlang/OTP 25, the system respects the CPU quota setting (`erlang:system_info(cpu_quota)` returns `1`), unlike in Erlang/OTP 24, where it returns `unknown`. Moreover, in versions 25, 26, and 27, the number of schedulers online is unexpectedly set to `1` instead of `2`, which aligns with the CPU quota. This discrepancy led to a production outage, indicating that the issue poses significant risks in production environments.

**To Reproduce**
1. Run a Docker container with Erlang/OTP 24, 25, 26 and 27 using the commands:
    ```
    docker run --cpus=2 -it --rm erlang:24
    docker run --cpus=2 -it --rm erlang:25
    docker run --cpus=2 -it --rm erlang:26
    docker run --cpus=2 -it --rm erlang:27
    ```
1. Check the CPU quota and the number of online schedulers for each version above:
    ```erlang
    erlang:system_info(cpu_quota).
    erlang:system_info(schedulers).
    erlang:system_info(schedulers_online).
    ```
1. Observe that `cpu_quota` returns `unknown` and `schedulers_online` returns `8` for OTP 24 and `cpu_quota` returns `1` and `schedulers_online` returns `1` for OTP 25, 26 and 27.

**Expected behavior**
The expected behavior is that the number of schedulers online should correspond directly to the number of CPUs available in the quota. Specifically, when `--cpus=2` is specified, there should be 2 schedulers online. This behavior should be consistent across all versions to prevent mismanagement of resources and potential system outages.

**Affected versions**
- Erlang/OTP 25
- Erlang/OTP 26
- Erlang/OTP 27

**Additional context**
This inconsistency in scheduler management and CPU quota has already led to a production outage, highlighting the critical nature of this issue. The behavior of the schedulers not adjusting properly to the CPU quota results in underutilization of available resources and can significantly impact system performance and stability. Immediate attention and modifications are necessary to ensure that the number of online schedulers accurately reflects the available CPU resources and to prevent further production issues.

**Comment by nickva** [comment]
I had noticed two recent 25 and 26 releases fixed a bug related to CPU quotas, wonder if it's the bug you're describing:

https://github.com/erlang/otp/commit/01754dee85a37d597fe820f68fae2991e2e35b63

https://erlangforums.com/t/patch-package-otp-25-3-2-12-released/3579
https://erlangforums.com/t/patch-package-otp-26-2-5-released/3582/2

**Comment by eric0fw** [comment]
I am more than happy to verify. Is there a docker image available for these new patched versions?

**Comment by garazdawi** [comment]
CPU quotas are notoriosly hard to test as they require various OSs in different configurations to test, so when #8259 tried to fix some issues in 25.3.2.11 and 26.2.3, it broken some other things. This was fixed in #8380, released in 25.3.2.12+26.2.4.

Please do test 25.3.2.12 and 26.2.4 and make sure that they work as expected. As I said these things are hard to test, so we have to do it manually, which means errors are bound to slip through.

**Comment by eric0fw** [comment]
So 26.2.4 is broken:
```
❯ docker run --cpus=2 -it --rm erlang:26.2.4
Erlang/OTP 26 [erts-14.2.4] [source] [64-bit] [smp:8:1] [ds:8:1:10] [async-threads:1] [jit]

Eshell V14.2.4 (press Ctrl+G to abort, type help(). for help)
1> erlang:system_info(cpu_quota).
1
2> erlang:system_info(schedulers).
8
3> erlang:system_info(schedulers_online).
1
```

**Comment by garazdawi** [comment]
Sorry, I wrote the wrong version for 26. It was introduced in 26.2.4 and fixed in 26.2.5.

the docket images always lag a bit behind because they are built using a manual process.

**Comment by eric0fw** [comment]
I can confirm that 26.2.5 works.
```
❯ docker run --cpus=2 -it --rm erlang:26.2.5
Erlang/OTP 26 [erts-14.2.5] [source] [64-bit] [smp:8:2] [ds:8:2:10] [async-threads:1] [jit]

Eshell V14.2.5 (press Ctrl+G to abort, type help(). for help)
1> erlang:system_info(cpu_quota).
2
2> erlang:system_info(schedulers).
8
3> erlang:system_info(schedulers_online).
2
```

**Comment by eric0fw** [comment]
I can also confirm 25.3.2.12 works.
```
❯ docker run --cpus=2 -it --rm erlang:25.3.2.12
Erlang/OTP 25 [erts-13.2.2.9] [source] [64-bit] [smp:8:2] [ds:8:2:10] [async-threads:1] [jit]

Eshell V13.2.2.9  (abort with ^G)
1> erlang:system_info(cpu_quota).
2
2> erlang:system_info(schedulers).
8
3> erlang:system_info(schedulers_online).
2
```

**Comment by garazdawi** [comment]
Great!
