### ISSUE TITLE
Use of built-in json module fails to maintain order in JER-encoded ASN.1

### ISSUE THREAD

**Issue by attah** [erlang/otp#8453]
**Describe the bug**
With the switch to the new nice json module as the encoder for ASN.1 JER, the order of elements in the JSON objects is no longer maintained.
https://github.com/erlang/otp/pull/8241

**To Reproduce**
JER-encode some ASN-1 object with several keys.
(Let me know id you need me to whip something up).

**Expected behavior**
Key order, when encoded, follows ASN.1 spec.

**Affected versions**
27

**Additional context**
We could probably argue all day (and part of next week) whether key order is defined or definable in JSON, and whether or not JSON is acceptable for human consumption. But none the less, this is a use-case we have, and a feature that was explicitly added to JER-encoding for this very reason (note how the accumulator is a proplist and not already a map).

Personally i see no other possibility than adding proplist support for the json module, both in encode and decode.

**Comment by bjorng** [comment]
Thanks for reporting this issue. The linked pull request ensures that the order is retained. I hope to include in the Erlang/OTP 27 release.

**Comment by attah** [comment]
Thanks for the speedy fix!
