### ISSUE TITLE
OTP-24.3.4.17 release tarball doesn't seem to contain the same source as OTP-24.3.4.17 GH tag

### ISSUE THREAD

**Issue by nickva** [erlang/otp#8471]
**Describe the bug**
Noticed the https://www.erlang.org/patches/otp-24.3.4.17#crypto-5.0.6.5 feature changes were not in the downloadable tar ball [otp_src_24.3.4.17.tar.gz](https://github.com/erlang/otp/releases/download/OTP-24.3.4.17/otp_src_24.3.4.17.tar.gz)

**To Reproduce**

Inspect https://github.com/erlang/otp/blob/OTP-24.3.4.17/lib/crypto/c_src/pbkdf2_hmac.c#L73 (at the OTP-24.3.4.17 tag, also https://github.com/erlang/otp/commit/e0001cd0fa553513ee8fee998a82a01ac9b7329b commit SHA).

Download and unpack https://github.com/erlang/otp/releases/download/OTP-24.3.4.17/otp_src_24.3.4.17.tar.gz and inspect the same file there.

```
 % sha256sum otp_src_24.3.4.17.tar.gz
2f0661b1f98b01c26e2bde7234ef587f77e5ee0e384f3b1221496782bf9c8b28  otp_src_24.3.4.17.tar.gz
```

Match with the [SHA256.txt](https://github.com/erlang/otp/releases/download/OTP-24.3.4.17/SHA256.txt)
```
% cat SHA256.txt
cb76b9d11d7b6c023ae9ed869d716fc3528699c8a9d40477026a9a65720d8eda  otp_doc_html_24.3.4.17.tar.gz
c4dc1034d82fcfcea2667076e667cf27cbd0d7e27e7da250f53e7fdba310034d  otp_doc_man_24.3.4.17.tar.gz
2f0661b1f98b01c26e2bde7234ef587f77e5ee0e384f3b1221496782bf9c8b28  otp_src_24.3.4.17.tar.gz
```

```
% tar xfz otp_src_24.3.4.17.tar.gz

% tail -n30 ./otp_src_24.3.4.17/lib/crypto/c_src/pbkdf2_hmac.c
        goto bad_arg;
    if (!enif_get_uint64(env, argv[3], &iter))
        goto bad_arg;
    if (!enif_get_uint64(env, argv[4], &keylen))
        goto bad_arg;

    if (iter < 1)
        goto bad_arg;
    if (keylen < 1)
        goto bad_arg;

    if (!enif_alloc_binary(keylen, &out))
        goto err;

    if (!PKCS5_PBKDF2_HMAC((const char *)pass.data, pass.size,
                           salt.data, salt.size, iter,
                           digp->md.p,
                           keylen, out.data)) {
        enif_release_binary(&out);
        goto err;
    }

    return enif_make_binary(env, &out);
 bad_arg:
 err:
    return enif_make_badarg(env);
#else
    return EXCP_NOTSUP(env, "Unsupported CRYPTO_PKCS5_PBKDF2_HMAC");
#endif
}
```

Expected

```
otp (tags/OTP-24.3.4.17) % tail -n30 ./lib/crypto/c_src/pbkdf2_hmac.c
                             const ERL_NIF_TERM argv[])
{
#ifdef HAS_PKCS5_PBKDF2_HMAC
    ErlNifUInt64 iter, keylen;

    if (!enif_get_uint64(env, argv[3], &iter))
        return enif_make_badarg(env);
    if (iter < 1)
        return enif_make_badarg(env);

    if (!enif_get_uint64(env, argv[4], &keylen))
        return enif_make_badarg(env);
    if (keylen < 1)
        return enif_make_badarg(env);

    /* Use a direct call if iterations and keylen are relatively small. keylen
       size of 64 is used as that's the longest currently implemented hash size
       for sha512.
    */
    if (iter <= 100 && keylen <= 64)
        return pbkdf2_hmac(env, argc, argv);

    /* Use a dirty CPU scheduler for a potentially long running call */
    return enif_schedule_nif(env, "pbkdf2_hmac",
                             ERL_NIF_DIRTY_JOB_CPU_BOUND,
                             pbkdf2_hmac, argc, argv);
#else
    return EXCP_NOTSUP(env, "Unsupported CRYPTO_PKCS5_PBKDF2_HMAC");
#endif
}
```

**Expected behavior**

Release tarball content would match the https://github.com/erlang/otp/releases/tag/OTP-24.3.4.17 tag.

**Affected versions**
OTP-24.3.4.17

**Additional context**
N/A

**Comment by davisp** [comment]
Here's confirmation that the differences between the uploaded tarball and the auto-generated tarball have different content beyond the "autoconf"'ed differences.

https://gist.github.com/davisp/eb3e39147f858c3e0e85232cf80c32d7

The crytpo bits that @nickva noticed start one line 2575 in that big diff.

**Comment by davisp** [comment]
For giggles I went and checked the 24.3.4.16 vs 24.3.4.17 uploaded tarballs and while the diff looks much bigger due to all the timestamps changing, the actual code differences are considerably smaller.

https://gist.github.com/davisp/a401bcc093ec60436b7e279be8290176

**Comment by davisp** [comment]
Looks like some but not all of the commits that GitHub claims are in 24.3.4.17 are just missing. Spot checking I'm not seeing a pattern to what's included vs not.

**Comment by dgud** [comment]
We have a long weekend here in Sweden so no one from OTP team will probably be at work to investigate this until Tuesday.
Interesting though.
It is late here so I have not checked but does the content of tag 24.3.4.16 and its src tar ball diff too?

**Comment by nickva** [comment]
@dgud git tag 24.3.4.16 vs 24.3.4.17 tar.gz does differ but not as much as it does from 24.3.4.17 git tag <-> 24.3.4.16 tar.gz.

A quick kdiff3 summary of changes 24.3.4.16 git tag <-> 24.3.4.17 tar.gz

<img width="732" alt="Screenshot 2024-05-09 at 6 27 18 PM" src="https://github.com/erlang/otp/assets/211822/4519ae25-a7d6-4501-899e-8de0d48026e1">

Some were auto-generated or doc chunks. But here is a change that looked like a code change

<img width="463" alt="Screenshot 2024-05-09 at 6 39 29 PM" src="https://github.com/erlang/otp/assets/211822/98dea5ec-34ed-48e2-ac80-93dab6efc886">

**Comment by garazdawi** [comment]
Not all of us are as lucky as @dgud and have today off... :)

The automation on [github actions failed](https://github.com/erlang/otp/actions/runs/8616663221) for that patch so I had to do it *manually*, which is of course where something went wrong. I seem to have uploaded the prebuilt archives for OTP-24.3.4.15 instead of OTP-24.3.4.17.

I have now [fixed the prebuilt archive and updates the shas](https://github.com/erlang/otp/releases/tag/OTP-24.3.4.17). Thank you very much for noticing and reporting this. Can you please verify that the correct archive is now available?

I'll be issuing statements about this on the platforms I have access to.

In light of the issues with xz and the brittle nature of GH actions, it probably is time to write a script that verifies that the prebuilt archives contain what they should contain.

**Comment by rnewson** [comment]
I can confirm the tarball at https://github.com/erlang/otp/releases/download/OTP-24.3.4.17/otp_src_24.3.4.17.tar.gz now matches the source of the OTP-24.3.4.17 tag from https://github.com/erlang/otp.git. The only differences are the expected (and welcome) pre-built `.beam` files.

**Comment by big-r81** [comment]
Hey,

one question to the released windows installer binaries. Are they affected too and need to get rebuild or are they build from git tags directly?

**Comment by garazdawi** [comment]
The Windows installer is not built from github actions (as the executable needs to be signed) so Windows is not affected.

**Comment by garazdawi** [comment]
> I can confirm the tarball at https://github.com/erlang/otp/releases/download/OTP-24.3.4.17/otp_src_24.3.4.17.tar.gz now matches the source of the OTP-24.3.4.17 tag from https://github.com/erlang/otp.git. The only differences are the expected (and welcome) pre-built `.beam` files.

Great, thanks for verifying.

**Comment by nickva** [comment]
Thanks for fixing the issue so quickly, Lukas!

Rebuilding with asdf (i.e. kerl) I now see the expected changes in the release.
