### ISSUE TITLE
Multiple instances of erl_child_setup process in the rabbitmq container

### ISSUE THREAD

**Issue by Vishnu-0809** [erlang/otp#8475]
Hi, I have a rabbitmq container running in which I can see that majority are erlang processes

```
bash-4.4$ ps -eaf
UID         PID   PPID  C STIME TTY          TIME CMD
rabbitmq      1      0  0 15:29 ?        00:00:00 /bin/sh /usr/lib/rabbitmq/bin/rabbitmq-server start
rabbitmq     40      1  1 15:29 ?        00:01:08 /usr/lib64/erlang/erts-13.2.2.1/bin/beam.smp -W w -MBas ageffcbf -MH
rabbitmq    182     40  0 15:29 ?        00:00:00 erl_child_setup 1048576
rabbitmq    256      1  0 15:29 ?        00:00:00 /usr/lib64/erlang/erts-13.2.2.1/bin/epmd -daemon
rabbitmq    338    182  0 15:29 ?        00:00:00 /usr/lib64/erlang/erts-13.2.2.1/bin/inet_gethost 4
rabbitmq    339    338  0 15:29 ?        00:00:00 /usr/lib64/erlang/erts-13.2.2.1/bin/inet_gethost 4
rabbitmq    397    182  0 15:29 ?        00:00:00 /bin/sh -s rabbit_disk_monitor
rabbitmq  46466      0  0 16:29 pts/0    00:00:00 bash
rabbitmq  46491  46466  0 16:29 pts/0    00:00:00 ps -eaf
```

As erlang is a dependency for rabbitmq application I have erlang rpm is installed in the container and most of the processes are result of execution of binaries in /usr/lib64/erlang/erts-13.2.2.1/bin/ directory after the erlang VM starts.
My requirement is when any of the above processes are killed I should have a log message along with the return code of that process. As I dont have any control on how these erlang processes are started as they all are binaries to get their return code I am trying to wrap those binaries in a wrapper script and make it an executable.

eg: epmd binary in this path /usr/lib64/erlang/erts-13.2.2.1/bin/epmd will be copied to /usr/lib64/erlang/erts-13.2.2.1/bin/epmd_original and then invoked in a wrapper script whose name will be same as the actual binary i.e /usr/lib64/erlang/erts-13.2.2.1/bin/epmd. The script will look something like this

```
#!/bin/sh
/usr/lib64/erlang/erts-14.1/bin/epmd_original $1

if [ $? -eq 137 ]; then
    echo "epmd is terminated by signal 137 (SIGKILL)." > /proc/1/fd/1
fi
```

So in this way whenever the actual epmd binary has to be executed by the application it will execute my wrapper binary which will in turn execute the actual one copied to a different path and everything else will remain same.
I was able to do this for epmd, inet_gethost processes but when I do the same for erl_child_setup processes the rabbitmq container is not starting up with log messages saying boot has failed and nothing specific to any erlang processes in the logs.

When I exec into container to check the running processes I see that there are multiple instances of erl_child_setup processes where in the ideal scenario should be only one instance of erl_child_setup process as mentioned in above ps output. This issue is observed only when I warp erl_child_setup with my wrapper script similar to what I have mentioned above and not for other binaries.

```
bash-4.4$ ps -eaf
UID          PID    PPID  C STIME TTY          TIME CMD
rabbitmq       1       0  0 07:45 ?        00:00:00 /bin/sh /usr/lib/rabbitmq/bin/rabbitmq-server start
rabbitmq      25       1  0 07:45 ?        00:00:00 sh /usr/sbin/update_default_password.sh
rabbitmq      42       1  1 07:45 ?        00:00:04 /usr/lib64/erlang/erts-14.1/bin/beam.smp -W w -MBas ageffcbf -MHas ageffcb
rabbitmq      58       1  0 07:45 ?        00:00:00 /bin/sh /usr/lib64/erlang/erts-14.1/bin/erl_child_setup 1048576
rabbitmq      91      58  0 07:45 ?        00:00:00 erl_child_setup_orig 1048576
rabbitmq     186      42  0 07:45 ?        00:00:00 /bin/sh /usr/lib64/erlang/erts-14.1/bin/erl_child_setup 1048576
rabbitmq     187     186  0 07:45 ?        00:00:00 erl_child_setup_orig 1048576
rabbitmq     283       1  0 07:45 ?        00:00:00 /usr/lib64/erlang/erts-14.1/bin/epmd_orig -daemon
rabbitmq     287       1  0 07:45 ?        00:00:00 /bin/sh /usr/lib64/erlang/erts-14.1/bin/erl_child_setup 1048576
rabbitmq     288     287  0 07:45 ?        00:00:00 erl_child_setup_orig 1048576
rabbitmq     328     187  0 07:45 ?        00:00:00 /bin/sh /usr/lib64/erlang/erts-14.1/bin/inet_gethost 4
rabbitmq     329     328  0 07:45 ?        00:00:00 /usr/lib64/erlang/erts-14.1/bin/inet_gethost_orig 4
rabbitmq     330     329  0 07:45 ?        00:00:00 /usr/lib64/erlang/erts-14.1/bin/inet_gethost_orig 4
rabbitmq     333     187  0 07:46 ?        00:00:00 /bin/sh -s rabbit_disk_monitor
rabbitmq     361       1  0 07:46 ?        00:00:00 /bin/sh /usr/lib64/erlang/erts-14.1/bin/erl_child_setup 1048576
rabbitmq     362     361  0 07:46 ?        00:00:00 erl_child_setup_orig 1048576
rabbitmq     426       1  0 07:46 ?        00:00:00 /bin/sh /usr/lib64/erlang/erts-14.1/bin/erl_child_setup 1048576
rabbitmq     427     426  0 07:46 ?        00:00:00 erl_child_setup_orig 1048576
rabbitmq     509       1  0 07:47 ?        00:00:00 /bin/sh /usr/lib64/erlang/erts-14.1/bin/erl_child_setup 1048576
rabbitmq     510     509  0 07:47 ?        00:00:00 erl_child_setup_orig 1048576
rabbitmq     584       1  0 07:48 ?        00:00:00 /bin/sh /usr/lib64/erlang/erts-14.1/bin/erl_child_setup 1048576
rabbitmq     585     584  0 07:48 ?        00:00:00 erl_child_setup_orig 1048576
rabbitmq     649       1  0 07:48 ?        00:00:00 /bin/sh /usr/lib64/erlang/erts-14.1/bin/erl_child_setup 1048576
rabbitmq     650     649  0 07:48 ?        00:00:00 erl_child_setup_orig 1048576
rabbitmq     733       1  0 07:50 ?        00:00:00 /bin/sh /usr/lib64/erlang/erts-14.1/bin/erl_child_setup 1048576
rabbitmq     734     733  0 07:50 ?        00:00:00 erl_child_setup_orig 1048576
rabbitmq     808       1  0 07:50 ?        00:00:00 /bin/sh /usr/lib64/erlang/erts-14.1/bin/erl_child_setup 1048576
rabbitmq     809     808  0 07:50 ?        00:00:00 erl_child_setup_orig 1048576
rabbitmq     873       1  0 07:50 ?        00:00:00 /bin/sh /usr/lib64/erlang/erts-14.1/bin/erl_child_setup 1048576
rabbitmq     874     873  0 07:50 ?        00:00:00 erl_child_setup_orig 1048576
rabbitmq     932       0  0 07:52 pts/0    00:00:00 bash
rabbitmq     938     932  0 07:52 pts/0    00:00:00 ps -eaf
```

We suspect that there are other rabbitmq processes (lets say processA) which are creating another erl_child_setup process and when processA is killed/finished erl_child_setup is not killed and adopted by pid=1 process, but 
1. why it should bring up another erl_child_setup process when there is already one running 
2. If it is expected behavior to bring up multiple erl_child_setup why they are not removed when parent goes down
3. Is there something that I am missing in my approach which is leading to this issue

**Comment by garazdawi** [comment]
`erl_child_setup` is started each time the Erlang VM is started. So there would be on of those for each Erlang VM started. My guess would be that when you wrap it, the termination detection logic within `erl_child_setup` breaks, that thus they leak. So the solution is to not wrap it.
