### ISSUE TITLE
Compile a file with lot of duplicate clauses

### ISSUE THREAD

**Issue by shionryuu** [erlang/otp#8493]
**Describe the bug**

Compile a file with lot of duplicate clauses will take much more time than file with no duplicate code.

**To Reproduce**

The test code can be find in [gist](https://gist.github.com/shionryuu/76c3952849625956eb19266de16b76b3)

```bash
$ cat compile_no_duplicate.erl | wc -l
27825
$ cat compile_duplicate.erl | wc -l
27826
$ time erlc compile_no_duplicate.erl
erlc compile_no_duplicate.erl  2.08s user 0.11s system 113% cpu 1.926 total
$ time erlc compile_duplicate.erl 
....
erlc compile_duplicate.erl  51.47s user 6.95s system 122% cpu 47.844 total
```

**Expected behavior**

Reduce compile time

**Affected versions**

OTP 26 / OTP 27

**Comment by frej** [comment]
A quick `erlc +time compile_no_duplicate.erl` gives `parse_module` as the slowest pass at roughly 0.2s. As the timing report is nearly instantaneous, my guess is that the time is spent in formatting the warnings. `erlc +time '+{nowarn_function, get_id/1}' compile_duplicate.erl` confirms that it is the warning formatting which is the problem.

So the philosophical question is: "Should the compiler be optimized for absolute massive number of warnings?" :)

**Comment by bjorng** [comment]
> So the philosophical question is: "Should the compiler be optimized for an absolute massive number of warnings?" :)

No, we have more important optimizations to do.

Producing the context for each warning is what takes most of time. That is, the lines that start with `%`:

```
compile_duplicate.erl:11:1: Warning: this clause cannot match because a previous clause at line 9 always matches
%   11| get_id({1, 1, 1}) ->
%     | ^
```

There are two ways to avoid the problem. Either suppress the warnings using the `nowarn_nomatch` option. That is best done by inserting the following line into the module:

```
-compile(nowarn_nomatch).
```

Alternatively, keep the warnings but suppress the context:

```
% erlc +brief
compile_duplicate.erl:11:1: Warning: this clause cannot match because a previous clause at line 9 always matches
compile_duplicate.erl:23:1: Warning: this clause cannot match because a previous clause at line 21 always matches
compile_duplicate.erl:35:1: Warning: this clause cannot match because a previous clause at line 33 always matches
   .
   .
   .
compile_duplicate.erl:27791:1: Warning: this clause cannot match because a previous clause at line 27789 always matches
compile_duplicate.erl:27803:1: Warning: this clause cannot match because a previous clause at line 27801 always matches
compile_duplicate.erl:27815:1: Warning: this clause cannot match because a previous clause at line 27813 always matches
```
