### ISSUE TITLE
cookie right but pang!

### ISSUE THREAD

**Issue by xlh1001** [erlang/otp#8495]
**Describe the bug**
set right cookie for two node . then execute ping but fail.

**To Reproduce**
`werl -name a@127.0.0.1 -setcookie aa`
`werl -name b@127.0.0.1 -setcookie bb`
fail:
![图片](https://github.com/erlang/otp/assets/141419455/7647f800-1de4-4493-99aa-162036fc16d4)

succeed：
![图片](https://github.com/erlang/otp/assets/141419455/352f1d4b-09bd-40eb-9b19-bd0ec72a99bd)

**Affected versions**
OTP 25 [erts-13.0.3]

**Comment by jrfondren** [comment]
with OTP 26 and 27, with nodes started the same way, and interleaving the shell interactions to reflect the timeline:

replication (`a` pings after `b`'s change):
```
(a@127.0.0.1)1> erlang:set_cookie('b@127.0.0.1', bb).
true
(b@127.0.0.1)1> erlang:set_cookie('a@127.0.0.1', aa).
true
(a@127.0.0.1)2> net_adm:ping('b@127.0.0.1').
pang
=ERROR REPORT==== 20-May-2024::22:10:32.626666 ===
** Connection attempt from node 'a@127.0.0.1' rejected. Invalid challenge reply. **
(a@127.0.0.1)3> {erlang:get_cookie(), erlang:get_cookie('b@127.0.0.1')}.
{aa,bb}
(b@127.0.0.1)2> {erlang:get_cookie(), erlang:get_cookie('a@127.0.0.1')}.
{bb,aa}
```
non-replication (`a` pings before and after `b`'s change):
```
(a@127.0.0.1)1> erlang:set_cookie('b@127.0.0.1', bb).
true
(a@127.0.0.1)2> net_adm:ping('b@127.0.0.1').
pong
(b@127.0.0.1)1> erlang:set_cookie('a@127.0.0.1', aa).
true
(a@127.0.0.1)3> net_adm:ping('b@127.0.0.1').
pong
(a@127.0.0.1)4> {erlang:get_cookie(), erlang:get_cookie('b@127.0.0.1')}.
{aa,bb}
(b@127.0.0.1)2> {erlang:get_cookie(), erlang:get_cookie('a@127.0.0.1')}.
{bb,aa}
```
there's also no pang if `a` looks at `net_adm:names().` before `b` changes its cookie.

**Comment by josevalim** [comment]
I don't think there is a bug here?

This line says, when node A connects to node B, I will send the cookie bb:

```
erlang:set_cookie('b@127.0.0.1', bb).
```

This line says, when node B receives a connection from A, I will expect the cookie aa:

```
erlang:set_cookie('a@127.0.0.1', aa).
```

Therefore there is a mismatch between the node being set and the one being expected.

**Comment by xlh1001** [comment]
Thank you for solving the problem that has puzzled me for a long time. I used to think that erlang:set_cookie/2 was just a way to modify the mapping between a node and a cookie. If you can, please put these words in the documentation.

**Comment by garazdawi** [comment]
@xlh1001 If you think the documentation could be made clearer, please do take the time to make a PR with a fix so that other also benefi. This is the place where this function is documented: https://github.com/erlang/otp/blob/OTP-27.0/erts/preloaded/src/erlang.erl#L11840-L11851
