### ISSUE TITLE
doc/moduledoc metadata keys

### ISSUE THREAD

**Issue by MarkoMin** [erlang/otp#8517]
`title` key in `-doc` metadata and `titles` key in `-moduledoc` metadata seem to be undocumented, at least according to [this link](https://www.erlang.org/doc/system/documentation#doc-metadata), but they are heavily used inside OTP.

Is there any reason for that?

**Comment by garazdawi** [comment]
It is something that is specific to our documentation and not general. It is documented [here](https://github.com/erlang/otp/blob/master/HOWTO/DOCUMENTATION.md#grouping). The implementation is part of our [ex_doc config](https://github.com/erlang/otp/blob/OTP-27.0/make/ex_doc.exs#L73-L108). Anyone is free to copy that approach is they want to.
