### ISSUE TITLE
FIPS mode not working with opensslv3 erlang 26.2.4

### ISSUE THREAD

**Issue by ssm6498** [erlang/otp#8582]
When i compile erlang with --enable-fips and use openssv3 fips enabled libarary. Its giving me error:

Erlang/OTP 26 [erts-14.2.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Eshell V14.2.4 (press Ctrl+G to abort, type help(). for help)
1> crypto:info().
=ERROR REPORT==== 15-Jun-2024::12:28:32.074434 ===
Unable to load crypto library. Failed with error:
"load, Library load-call unsuccessful (227)."

=WARNING REPORT==== 15-Jun-2024::12:28:32.082885 ===
The on_load function for module crypto returned:
{error,{load,"Library load-call unsuccessful (227)."}}

** exception error: undefined function crypto:info/0

Is FIPS with opensslv3 supported in erlang? if yes please share the release version number

**Comment by ssm6498** [comment]
along with providing --enable-fips option do I need to do any other change?

**Comment by ssm6498** [comment]
Now able to load fips modules by creating soft link.
but now fips is not getting enabled:

Erlang/OTP 26 [erts-14.2.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Eshell V14.2.4 (press Ctrl+G to abort, type help(). for help)
1> crypto:info().
#{otp_crypto_version => "5.4.2",compile_type => normal,
  link_type => dynamic,
  cryptolib_version_compiled => "OpenSSL 3.0.13 30 Jan 2024",
  cryptolib_version_linked =>
      "OpenSSL 3.0.13+SL_CCS-2.1.2+b 30 May 2024",
  fips_provider_available => true}
2> crypto:info_fips().
not_enabled


Can anyone please help how can i enable the fips

**Comment by ssm6498** [comment]
I have set fips as true in crypto.app also, still fips is not getting enabled

**Comment by sverker** [comment]
Is this same problem as #7693 maybe?

**Comment by sverker** [comment]
@ssm6498 Does it work if you first do `application:start(crypto)` before loading or calling the `crypto` module?

**Comment by ssm6498** [comment]
Hi,
its now working for unix platforms with minor chnage in export ariables needed for opensslv3 libarary and proiding correct fips.so.

but now I am facing issue on windows. though I am providing corrects lib and dll its not able to load crypto

in build script 

before calling otp_build
I am creating openssl_libs dir

mkdir openssl_libs
mkdir openssl_libs/lib
mkdir openssl_libs/lib/VC
mkdir openssl_libs/include

cp -fra ${PSPOPENSSL_PATH}/include/openssl openssl_libs/include/
cp -fra ${PSPOPENSSL_PATH}/include/AMD64/openssl openssl_libs/include/

#cp -fra ${1}/lib/AMD64/fipscanister.lib openssl_libs/lib/
cp -fra ${PSPOPENSSL_PATH}/lib/AMD64/vxcrypto3.lib openssl_libs/lib/
cp -fra ${PSPOPENSSL_PATH}/lib/AMD64/vxssl3.lib openssl_libs/lib/ssl.lib
cp -fra ${PSPOPENSSL_PATH}/lib/AMD64/vxfips.dll openssl_libs/lib/
cp -fra ${PSPOPENSSL_PATH}/lib/AMD64/vxfips.dll openssl_libs/
cp -fra ${PSPOPENSSL_PATH}/lib/AMD64/vxcrypto3.lib openssl_libs/
cp -fra openssl_libs/lib/*.lib openssl_libs/
cp -fra openssl_libs/lib/*.lib openssl_libs/lib/VC/
cp -fra openssl_libs/lib/crypto.lib openssl_libs/lib/VC/libcrypto.lib
cp -fra openssl_libs/lib/crypto.lib openssl_libs/lib/VC/libcryptoM.lib
cp -fra openssl_libs/lib/crypto.lib openssl_libs/lib/VC/libcrypto64MD.lib
cp -fra openssl_libs/lib/ssl.lib openssl_libs/lib/VC/libssl.lib
cp -fra openssl_libs/lib/ssl.lib openssl_libs/lib/VC/libsslM.lib
cp -fra openssl_libs/lib/ssl.lib openssl_libs/lib/VC/libssl64MD.lib

and then calling ./otp_build configure --enable-fips --enable-dynamic-ssl-lib --with-ssl=${ERL_TOP}/openssl_libs --without-javac --without-odbc

At a run time keeping libvxcrypto_3.dll and vxfips.dll and correct location 

Am I misisng anything?

**Comment by ssm6498** [comment]
To Note: We have our customised fips.dll version, named something different.
In crypto.c at line#227 its failing.
if ((prov_cnt<MAX_NUM_PROVIDERS) && !(prov[prov_cnt++] = OSSL_PROVIDER_load(NULL, "fips"))) return __LINE__;

What can be solution

**Comment by ssm6498** [comment]
It's not completed. Issue is not yet fixed.

**Comment by sverker** [comment]
It got auto-closed when I merged #8590 which was addressing your initial problem, I think.

I suggest you open a new issue for the "FIPS on Windows" problem if you need help.
However, we don't have any testing done with FIPS on Windows. So, I have neither experience to share nor time to spend on that right now.

**Comment by ssm6498** [comment]
Oh okay. Sure thanks
