### ISSUE TITLE
Non-deterministic representation of map as string

### ISSUE THREAD

**Issue by pguyot** [erlang/otp#8606]
**Describe the bug**
Until OTP-27, the following map:
```erlang
#{a => 1, b => 2}
```
would have the following representation:
```erlang
"#{a => 1,b => 2}"
```

With OTP-27, the representation can non-deterministically also be:
```erlang
"#{b = >2,a => 1}"
```

**To Reproduce**

```shell
mkdir /tmp/test_beam
cd /tmp/test_beam
```

Then run the following command a dozen times:
```shell
erl -pa . -eval 'io:format("~p\n", [#{a=>1,b=>2}]).' -run init stop -noshell
```

**Expected behavior**
Representation should be deterministic or non-determinism should be documented (couldn't find it in OTP27 release notes).

**Affected versions**
OTP-27.0

**Additional context**

This was observed on macOS:

ProductName:		macOS
ProductVersion:		14.5
BuildVersion:		23F79

with OTP-27 from MacPorts on an amd64 machine.

<img width="1400" alt="Screenshot 2024-06-22 at 22 51 22" src="https://github.com/erlang/otp/assets/168407/df3918cd-52c2-4cc6-9e29-20b5872bf7c8">

**Comment by michalmuskala** [comment]
This was changed in OTP 26 and is documented in the release notes: https://erlang.org/download/otp_src_26.0.readme (under OTP-18414).

Maps can be printed sorted using `io:format("~kp", [Value]).`, with the `k` and `K` modifiers documented in [`io:fwrite/3`](https://www.erlang.org/doc/apps/stdlib/io.html#fwrite/3).
