### ISSUE TITLE
Use erlang:port_command(Socket, <<0,0,0,1>>), but only receive <<0,1>> in otp-27 erts-15.0.

### ISSUE THREAD

**Issue by xlh1001** [erlang/otp#8635]
**Describe the bug**
otp-27 erts-15:
Use erlang:port_command(Socket, <<0,0,0,1>>), but only receive <<0,1>>.

otp-25 erts-13.2.2.8 
Use erlang:port_command(Socket, <<0,0,0,1>>),  receive <<0,0,0,1>>.

**To Reproduce**
now erlang version: otp-27 erts-15:
server:
```
1> Op = [binary, {packet, 0}].
[binary,{packet,0}]
2> {ok, Ls} = gen_tcp:listen(6001,Op).
{ok,#Port<0.2>}
3> {ok, S} = gen_tcp:accept(Ls).
{ok,#Port<0.3>}
4> flush().
Shell got {tcp,#Port<0.3>,<<0,1>>}
ok
5> erlang:port_command(S, <<0,0,0,1>>).
true
6> flush().
Shell got {tcp,#Port<0.3>,<<0,0,0,1>>}
ok
```
client:
```
1> {ok, S} = gen_tcp:connect("127.0.0.1",6001,[binary, {packet, 0}]).
{ok,#Port<0.3>}
2> erlang:port_command(S, <<0,0,0,1>>).
true
3> flush
   ().
Shell got {tcp,#Port<0.3>,<<0,1>>}
ok
4> gen_tcp:send(S, <<0,0,0,1>>).
ok
```
how can i got original data in this version and use port_command?

**Comment by jhogberg** [comment]
Thanks for your report! Using `port_command` in this way is not supported, use the documented interfaces for interacting with `gen_tcp` sockets.

**Comment by xlh1001** [comment]
```
erlang:port_command(S, [<<RefLen:16, RefBin/binary>>, <<0,0,0,1>>])
```
this work!

**Comment by jhogberg** [comment]
You are not supposed to do that.

**Comment by xlh1001** [comment]
why ? Sometimes I want to sending data asynchronously.

**Comment by jhogberg** [comment]
Because undocumented things can break at any time without warning, as evidenced by this report.

**Comment by essen** [comment]
You can use the `socket` module which supports asynchronous send.

**Comment by xlh1001** [comment]
> You can use the `socket` module which supports asynchronous send.
Thanks, I'll try
