### ISSUE TITLE
liberts.a missing since OTP 25

### ISSUE THREAD

**Issue by alanj853** [erlang/otp#8653]
**Describe the bug**
This is more a question than a bug. Since OTP 25, liberts.a appears to be missing from standard build. Is there a replacement library that can be used, or does some other option need to be enabled/disabled at configure time in order to produce it?

**To Reproduce**
First compile OTP 25
1. git clone --branch=maint-25 https://github.com/erlang/otp && cd otp
2. mkdir -p /home/user/src/otp-25-install/
3. ./configure --prefix=/home/user/src/otp-25-install/
4. make && make install

Next, Compile OTP 24
1. git checkout maint-24
2. mkdir -p /home/user/src/otp-24-install/
3. ./configure --prefix=/home/user/src/otp-24-install/
4. make && make install

**Expected behavior**
I expected both OTP versions to produce a liberts.a file, but otp-25 does not appear to:
```
user@ubuntu-22:~/src/otp$ find otp-24-install/ -name "liberts.a"
otp-24-install/lib/erlang/erts-12.3.2.17/lib/liberts.a
otp-24-install/lib/erlang/usr/lib/liberts.a
user@ubuntu-22:~/src/otp$ find otp-25-install/ -name "liberts.a"
user@ubuntu-22:~/src/otp$
```

**Affected versions**
OTP 25

**Additional context**
Performed on a Ubuntu 22 machine.

**Comment by jhogberg** [comment]
Thanks for your report! The library was removed because it was empty and no longer needed (69994d56e1c454134cbc83fafe673a605daffbe2), was there anything in particular in this library that you used to rely on?

**Comment by alanj853** [comment]
Thank you for the fast reply, @jhogberg! I am currently cross-compiling an Elixir Application, and one of the dependencies of that project is looking for it. Looking at the commit you references, I don't think the application really needs that code.
