### ISSUE TITLE
Can't compile OTP 26.2.5 on RHEL platform, getting issues with parsetools

### ISSUE THREAD

**Issue by ssm6498** [erlang/otp#8654]
The error logs:

sed -e 's;%VSN%;2.5;' parsetools.app.src > ../ebin/parsetools.app
sed -e 's;%VSN%;2.5;' parsetools.appup.src > ../ebin/parsetools.appup
/bin/sh: ../ebin/parsetools.app: No such file or directory
Makefile:83: recipe for target '../ebin/parsetools.app' failed
make[3]: *** [../ebin/parsetools.app] Error 1
make[3]: *** Waiting for unfinished jobs....
/bin/sh: ../ebin/parsetools.appup: No such file or directory
Makefile:86: recipe for target '../ebin/parsetools.appup' failed
make[3]: *** [../ebin/parsetools.appup] Error 1
Runtime terminating during boot ({load_failed,[supervisor,lists,proc_lib,logger_simple_h,logger_config,logger_backend,logger_server,logger_filters,logger,kernel,heart,gen_server,gen_event,gen,file_io_server,file_server,filename,file,ets,erl_lint,erl_eval,error_logger,erl_parse,code_server,code,application_master,application,application_controller,error_handler]})^M
^M
Crash dump is being written to: erl_crash.dump...Runtime terminating during boot ({load_failed,[supervisor,proc_lib,lists,logger_simple_h,logger_config,logger_backend,logger_server,logger_filters,logger,kernel,heart,gen_server,gen_event,gen,file_io_server,file_server,file,filename,ets,erl_lint,error_logger,erl_parse,code_server,erl_eval,application_controller,code,application_master,error_handler,application]})^M
^M
Crash dump is being written to: erl_crash.dump...Runtime terminating during boot ({load_failed,[supervisor,proc_lib,lists,logger_simple_h,logger_config,logger_backend,logger_server,logger_filters,logger,kernel,heart,gen_event,gen_server,gen,file_server,file_io_server,filename,file,ets,error_logger,erl_parse,erl_lint,code_server,erl_eval,code,application_controller,application_master,application,error_handler]})^M

Can any one please help

**Comment by jhogberg** [comment]
Thanks for your report! Unfortunately most of us are on vacation right now, we'll revisit this once we're back. :-)

**Comment by bjorng** [comment]
Please post the full build log. We can't see what is happening from the part you posted.

**Comment by ssm6498** [comment]
Hi,
As I was on tracking this, i forgot to update. My appologies.
Re downloading the source pacakage worked for me. Issue got fixed.
