### ISSUE TITLE
Release notes missing for 27.0.1

### ISSUE THREAD

**Issue by rodrigues** [erlang/otp#8659]
**Describe the bug**
Just a heads up, in https://www.erlang.org/patches/otp-27.0 we don't have the release notes for the latest patch.

Thank you!

**Expected behavior**
Thinking might be a problem in the release pipeline that needs fixing after 27?

**Affected versions**
27.0.1

**Comment by IngelaAndin** [comment]
We are aware that part of the update of erlang org page is missing. Release notes however are present in the applications documentation. And we believe that the patch is intact but some OTP-27 specific pipeline failures remains to be fixed.
