### ISSUE TITLE
Memory usage of OTP-27 -  OOM SIGKILL  - insufficient swap space

### ISSUE THREAD

**Issue by crownedgrouse** [erlang/otp#8669]
**Describe the bug**
A same code is compiling OK with 26.2 and fails due to OOM kill (exit 137) on 27.0.1 .
This ticket is mainly to inform community of such issue.

**To Reproduce**
Compile a big project with only 980 Mo Swap

**Expected behavior**
Inform users of minimal swap partition to use 27.0 safely. 

**Affected versions**
27.0

**Additional context**
Issue disappear by adding 1 Go swap but is then full up to 1.8 Go (2 swap partitions).

**Comment by josevalim** [comment]
I am afraid this will pretty much depend on the project? As the compiler changes between Erlang/OTP versions, it may change the amount of memory it requires. Even things like making the compiler faster can change the memory profile (it can now do more, in less time, allocating more memory). Other things like concurrency will affect it too (depending on the build tool you are using). I don't think the amount of memory used by the compiler was ever a guarantee of the compiler or the build tool.

**Comment by bjorng** [comment]
> Inform users of minimal swap partition to use 27.0 safely.

I don't see that this is practical. As @josevalim points out, it very much depends on the project. Therefore I will close this issue.

**Comment by frej** [comment]
Although if the compiler suddenly requires twice the amount of memory it could be worthwhile to report it. But for it to be actionable the report would have to be along the lines of "The attached module requires X of memory to compile with OTP-X, while in OTP-(X-1) it only required Y". The same applies to compilation speed.

**Comment by bjorng** [comment]
Yes, as @frej said, we are interested in actionable bug reports of regressions in compilation speed or memory consumption.
