### ISSUE TITLE
CRASH REPORT

### ISSUE THREAD

**Issue by zinzinday** [erlang/otp#8677]
C:\Program Files\Erlang OTP\bin>erl
=ERROR REPORT==== 19-Jul-2024::00:33:18.300000 ===
** State machine user_drv terminating
** When server state  = {undefined,undefined}
** Reason for termination = error:{badmatch,
                                   {error,
                                    {'SetConsoleMode',
                                     'The parameter is incorrect.\r\n'}}}
** Callback modules = [user_drv]
** Callback mode = state_functions
** Stacktrace =
**  [{prim_tty,init,1,[{file,"prim_tty.erl"},{line,255}]},
     {user_drv,init,1,[{file,"user_drv.erl"},{line,170}]},
     {gen_statem,init_it,6,[{file,"gen_statem.erl"},{line,2695}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,329}]}]

=CRASH REPORT==== 19-Jul-2024::00:33:18.300000 ===
  crasher:
    initial call: user_drv:init/1
    pid: <0.65.0>
    registered_name: []
    exception error: no match of right hand side value
                     {error,
                         {'SetConsoleMode','The parameter is incorrect.\r\n'}}
      in function  prim_tty:init/1 (prim_tty.erl, line 255)
      in call from user_drv:init/1 (user_drv.erl, line 170)
      in call from gen_statem:init_it/6 (gen_statem.erl, line 2695)
    ancestors: [<0.64.0>,kernel_sup,<0.47.0>]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 29
    reductions: 494
  neighbours:

=CRASH REPORT==== 19-Jul-2024::00:33:29.225000 ===
  crasher:
    initial call: supervisor_bridge:user_sup/1
    pid: <0.64.0>
    registered_name: []
    exception exit: nouser
      in function  gen_server:init_it/6 (gen_server.erl, line 2038)
    ancestors: [kernel_sup,<0.47.0>]
    message_queue_len: 0
    messages: []
    links: [<0.49.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 29
    reductions: 677
  neighbours:

=SUPERVISOR REPORT==== 19-Jul-2024::00:33:29.225000 ===
    supervisor: {local,kernel_sup}
    errorContext: start_error
    reason: nouser
    offender: [{pid,undefined},
               {id,user},
               {mfargs,{user_sup,start,[]}},
               {restart_type,temporary},
               {significant,false},
               {shutdown,2000},
               {child_type,supervisor}]

=CRASH REPORT==== 19-Jul-2024::00:33:29.225000 ===
  crasher:
    initial call: application_master:init/3
    pid: <0.46.0>
    registered_name: []
    exception exit: {{shutdown,{failed_to_start_child,user,nouser}},
                     {kernel,start,[normal,[]]}}
      in function  application_master:init/3 (application_master.erl, line 143)
    ancestors: [application_controller,<0.10.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.47.0>,normal}]
    links: [<0.45.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 233
    stack_size: 29
    reductions: 63
  neighbours:

=INFO REPORT==== 19-Jul-2024::00:33:29.225000 ===
    application: kernel
    exited: {{shutdown,{failed_to_start_child,user,nouser}},
             {kernel,start,[normal,[]]}}
    type: permanent

Kernel pid terminated (application_controller) ("{application_start_failure,kernel,{{shutdown,{failed_to_start_child,user,nouser}},{kernel,start,[normal,[]]}}}")

Crash dump is being written to: erl_crash.dump...done

**Comment by keyhanjk** [comment]
mention your env, os, ... and full dump file

**Comment by garazdawi** [comment]
This happens when you have a too old version of Windows. You should upgrade your Windows to a version supported by Microsoft.

**Comment by jaksonlin** [comment]
is there a compatibility matrixes? we have lab machines that are old (2008r2 server) and the hardware is not compatible to install the new OS, not sure which version of erlang can use.

**Comment by garazdawi** [comment]
We don’t have any such information, but the crash in this issue was introduced in Erlang/OTP 26. So a version before that could work, unless there is some other incompatibility that we introduced before then.
