### ISSUE TITLE
[Need urgent help] rabbitmq giving channel error

### ISSUE THREAD

**Issue by ssm6498** [erlang/otp#8688]
we are getting below errors in between for a specific user, what can be the reson and what is the solution:

 channel is already closed due to channel error; protocol method: #method<channel.close>(reply-code=403, reply-text=ACCESS_REFUSED - write access to exchange 'amq.topic' in vhost '<some>' refused for user '<user>', backend rabbit_auth_backend_cache returned an error: {failed_connect,                                                                                        ..., class-id=60, method-id=40)

**Comment by jhogberg** [comment]
Thank you for taking the time to make a report, but you have filed this with the wrong people. Please direct this at RabbitMQ instead.

**Comment by ssm6498** [comment]
Sorry my bad,
