### ISSUE TITLE
Regex: unicode property S doesn't match '🥰' emoji and others

### ISSUE THREAD

**Issue by g-andrade** [erlang/otp#8713]
**Describe the bug**

The regular expression `"\\p{S}"`, matching codepoints categorized as symbols, doesn't match the string `"🥰"` - unlike for other emoji.

**To Reproduce**

```erlang
% re:run("🥰", "\\p{S}", [unicode]).
nomatch
```

**Expected behavior**

What happens with other emoji:
```erlang
% re:run("😎", "\\p{S}", [unicode]).
{match,[{0,4}]}
```

[Character properties for 😎](https://util.unicode.org/UnicodeJsps/character.jsp?a=%F0%9F%98%8E&B1=Show), as well [as for 🥰](https://util.unicode.org/UnicodeJsps/character.jsp?a=%F0%9F%A5%B0&B1=Show), both list their general category as 'Other symbol'.

**Affected versions**

OTP 27.0.1 on GNU/Linux

**Comment by g-andrade** [comment]
Further investigation revealed a total of 432 emoji, [out of 1902](https://unicode.org/emoji/charts/full-emoji-list.html), not matched by `\\p{S}`:

```elixir
# "full_emoji_list.txt" |> File.read!() |> String.split("\n", trim: true) |> Enum.count(&(not String.match?(&1, ~r/\p{S}/u)))
432
```

[emojis_not_matching_regex_S.txt](https://github.com/user-attachments/files/16590692/emojis_not_matching_regex_S.txt)

[full_emoji_list.txt](https://github.com/user-attachments/files/16590691/full_emoji_list.txt)

**Comment by g-andrade** [comment]
Further investigation uncovered a total of 432 emojis, out of 1902, not matched by unicode property `S`:

```elixir
# "full_emoji_list.txt" |> File.read!() |> String.split("\n", trim: true) |> Enum.filter(&(:re.run(&1, ~c'\\p{S}',  [:unicode]) === :nomatch)) |> length()
432
```

![Screenshot from 2024-08-12 19-58-50](https://github.com/user-attachments/assets/9d847a3c-114c-4ae7-bb42-fb886b9d260a)

* [full_emoji_list.txt](https://github.com/user-attachments/files/16590778/full_emoji_list.txt), extracted from [unicode.org](https://unicode.org/emoji/charts/full-emoji-list.html).
* [emojis_not_matching_regex_S.txt](https://github.com/user-attachments/files/16590779/emojis_not_matching_regex_S.txt)

At least some of them seem to match the unicode property `C` instead (control characters).

**Comment by g-andrade** [comment]
I suspected pcre, that makes sense. In the process I noticed an up to date [emoji-data.txt](https://github.com/erlang/otp/blob/3bd5814898e90c33470f490ae5aa7b6d7aef565c/lib/stdlib/uc_spec/emoji-data.txt#L4), used for unicode-related code generation, and wondered: is the info on grapheme (cluster) categories, if any, exposed somewhere in the stdlib? - as an alternative to regular expressions.

Essentially, a way to answer the question: according to the unicode standard shipped with a specific version of OTP, is X a symbol? (Or any other unicode category/subcategory)

**Comment by garazdawi** [comment]
You can do it through an undocumented function:

```
1> unicode_util:lookup($🥰).
#{category => {symbol,other},
  canon => [],ccc => 0,compat => []}
```

maybe @dgud knows of an official API that can be used?

**Comment by dgud** [comment]
No API is exposed today, unicode_util was made to support the module `string`s "new" API. 

Some functionality could be exposed in the `unicode` module maybe?

**Comment by garazdawi** [comment]
Closing this as there is not anything we can do about this except change re implementation and that is tracked elsewhere.
