### ISSUE TITLE
`file:read_file/1` missing 1st binary of `/dev/stdin` which comes from Unix pipe

### ISSUE THREAD

**Issue by pojiro** [erlang/otp#8725]
**Describe the bug**

I wrote a escript like following,

```erlang
#!/usr/bin/env escript
main(_) ->
  {ok, Binary} = file:read_file("/dev/stdin"),
  io:format("~s", [binary_to_list(Binary)]).
```

Then use it with Unix pipe like following

```bash
LC_ALL=c ping -c 1 example.com | escript pipe_test_with_file_read.erl
```

Above didn't put anything, but when changed the ping `count` option from 1 to 2, the result was printed without 1st ping.

```bash
LC_ALL=c ping -c 2 example.com | escript pipe_test_with_file_read.erl
64 bytes from 93.184.215.14 (93.184.215.14): icmp_seq=2 ttl=54 time=129 ms

--- example.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 126.080/127.448/128.817/1.368 ms
```

**To Reproduce**

It's the same as the Bug section.

**Expected behavior**

It would be nice to be able to use `/dev/stdin` directly in a Unix pipe.
I'm an Elixir programmer, this issue comes from https://github.com/elixir-lang/elixir/issues/13780

**Affected versions**

I just confirmed this with `27.0.1 `.

**Additional context**

Nothing.

**Comment by garazdawi** [comment]
If you add `-noinput` to you escript it will work. That is:

```
#!/usr/bin/env escript
%%! -noinput
main(_) ->
  {ok, Binary} = file:read_file("/dev/stdin"),
  io:format("~s", [binary_to_list(Binary)]).
```

**Comment by pojiro** [comment]
Thank you!
