### ISSUE TITLE
Windows build call to `erlang:system_info(system_architecture)` returns `"win32"` 

### ISSUE THREAD

**Issue by harrisi** [erlang/otp#8767]
**Describe the bug**
The call to `erlang:system_info/1` with `system_architecture` returns just `"win32"` on Windows.

**To Reproduce**
```erlang
erlang:system_info(system_architecture).
```

**Expected behavior**
Ideally it would return a triple like `x86_64-pc-windows`.

**Affected versions**
At least 27, but I believe any version where Windows builds work will have this problem.

**Additional context**
I haven't tried building locally on Windows yet to see if it's only a problem with the provided pre-built binary.

**Comment by garazdawi** [comment]
There is some work ongoing in #8142 that I think may solve this issue. Our build system for Windows is currently geared towards calling the architecture `win32`, so to change it is a rather big endeavour.

I'll close this as we can track it in #8142.
