### ISSUE TITLE
Escaped chars in SuperCarrier.md

### ISSUE THREAD

**Issue by benbro** [erlang/otp#8770]
```<size in Mb>``` is converted to ```&lt;size in Mb&gt;```
https://www.erlang.org/doc/apps/erts/supercarrier.html
https://github.com/erlang/otp/blob/OTP-27.0.1/erts/emulator/internal_doc/SuperCarrier.md#super-carrier

**Comment by garazdawi** [comment]
Thanks for your report! This was already fixed in #8723.
