### ISSUE TITLE
io:format does not return or hangs VM for certain values

### ISSUE THREAD

**Issue by leonardb** [erlang/otp#8782]
When testing a simple io:format of integer range 1..254 I discovered that the VM does not print any value, or hangs the entire VM for certain values.

Version: 26.2.5.1

To reproduce:

```
[begin io:format("int: ~p ", [X]), io:format("str: ~s~n",[[X]]) end || X <- lists:seq(1,254)].
```

This will print values for integers in the range 1..144

For values 144 through 155 nothing is printed, event the "~n"

For value 156, "nt: 156 str:" is printed (note the missing `i` at the beginning)

On value 157 `int: 157 str:` is printed and the VM hangs.

This behavior is repeated for values 156.. 159

From values 160..254 there are no issues.

**Comment by garazdawi** [comment]
This has nothing to do with Erlang, but with your terminal. When you print certain values the terminal will interpret them as control characters and expect other specific characters to follow. If you want to print those characters you will need to configure the terminal to show them. How you do that I have no idea.

This stackoverflow thread explains it better than I do: https://stackoverflow.com/a/70371287
