### ISSUE TITLE
[HELP NEEDED] enabling FIPS for erlang

### ISSUE THREAD

**Issue by Vishnu-0809** [erlang/otp#8797]
I am trying to bring up the RabbitMQ application in FIPS enabled env which is failing, recent discussion with RabbitMQ team had mentioned that to enabled to FIPS the underlying erlang VM should support FIPS.

For me to enable FIPS for erlang , do I have to compile the erlang source with fips enabled configuration ?

or setting the {crypto, [{fips_mode, true}]} in advanced.config for rabbitmq will enable the same erlang.
and I am using this erlang rpm(26.2.5) - https://github.com/rabbitmq/erlang-rpm
openssl version - 3.0.2

Please clarify on this and thanks in advance.

**Comment by garazdawi** [comment]
Hello! Please read our guide on [FIPS](https://www.erlang.org/doc/apps/crypto/fips.html), it should clarify what you need to do.

**Comment by IngelaAndin** [comment]
You can not disable FIPS for one OTP application and have it for another on the same Erlang node.  But as documentation says you need to both compile for FIPS use and use a runtime switch for FIPS to be used by our crypto application that uses OpenSSL as a backend.

**Comment by swathimocharla** [comment]
hi @IngelaAndin , thanks! Our use case is only to run the application (rabbitmq) on a FIPS enabled environment (rabbitmq is built on top of erlang). For this, do we still need a FIPS enabled erlang OTP?

**Comment by dgud** [comment]
@swathimocharla If you want FIPS you will need to compile erlang with FIPS, if you don't need FIPS you should not need to recompile erlang. 
However, bugs have been fixed in this area so you might need a newer erlang version.
