### ISSUE TITLE
OTP 26 Memory increase

### ISSUE THREAD

**Issue by alanj853** [erlang/otp#8799]
**Describe the bug**
There appears to be a significant memory increase in OTP 26 when compared to OTP 25. In a simple elixir project with 1 file, the memory increase returned from :erlang.memory() is ~7.5 MB more.

**To Reproduce**
1. Install Elixir 1.16.3, erlang 25.3.2 and erlang 26.2.5
2. Run "mix new test_app && cd test_app"
3. First check OTP 25. Run
```
pokyuser@docker:/workdir$ rm -rf _build
pokyuser@docker:/workdir$ asdf local erlang 25.3.2
pokyuser@docker:/workdir$ asdf local elixir 1.16.3-otp-25
pokyuser@docker:/workdir$ MIX_ENV=prod iex -S mix
Erlang/OTP 25 [erts-13.2.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]

Compiling 1 file (.ex)
Generated test_app app
Interactive Elixir (1.16.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>
```
4. Now, check the memory with :erlang.memory()
```
iex(1)> :erlang.memory() |> Enum.map(fn {k,v} -> {k, v/1024/1024} end)
[
  total: 38.005638122558594,
  processes: 5.623779296875,
  processes_used: 5.6236572265625,
  system: 32.381858825683594,
  atom: 0.5626993179321289,
  atom_used: 0.5518970489501953,
  binary: 0.045745849609375,
  code: 12.668996810913086,
  ets: 0.6887054443359375
]
iex(2)>
```
5. Now check with OTP 26
```
pokyuser@docker:/workdir$ rm -rf _build
pokyuser@docker:/workdir$ asdf local erlang 26.2.5
pokyuser@docker:/workdir$ asdf local elixir 1.16.3-otp-26
pokyuser@docker:/workdir$ MIX_ENV=prod iex -S mix
Compiling 1 file (.ex)
Generated test_app app
Erlang/OTP 26 [erts-14.2.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.16.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :erlang.memory() |> Enum.map(fn {k,v} -> {k, v/1024/1024} end)
[
  total: 45.56732177734375,
  processes: 6.725547790527344,
  processes_used: 6.719146728515625,
  system: 38.841773986816406,
  atom: 0.6017694473266602,
  atom_used: 0.5742120742797852,
  binary: 0.5586013793945312,
  code: 13.20484733581543,
  ets: 0.8754806518554688
]
iex(2)>
```

**Expected behavior**
The memory usage should not change this drastically for such a simple application, should it?

**Affected versions**
OTP 26.2.5

**Additional context**
The elixir version remained constant at 1.16.3.

The project is so small and simple that I did not produce a repo for it, but can if required. "mix new test_app" simply produces these files single Elixir files produced are:
mix.exs
```
defmodule TestApp.MixProject do
  use Mix.Project

  def project do
    [
      app: :test_app,
      version: "0.1.0",
      elixir: "~> 1.16",
      start_permanent: Mix.env() == :prod,
      deps: deps()
    ]
  end

  # Run "mix help compile.app" to learn about applications.
  def application do
    [
      extra_applications: [:logger]
    ]
  end

  # Run "mix help deps" to learn about dependencies.
  defp deps do
    [
      # {:dep_from_hexpm, "~> 0.3.0"},
      # {:dep_from_git, git: "https://github.com/elixir-lang/my_dep.git", tag: "0.1.0"}
    ]
  end
end

```
lib/test_app.ex
```
defmodule TestApp do
  @moduledoc """
  Documentation for `TestApp`.
  """

  @doc """
  Hello world.

  ## Examples

      iex> TestApp.hello()
      :world

  """
  def hello do
    :world
  end
end
```

**Comment by garazdawi** [comment]
Something in `system` uses more memory it would seem. Not sure what that could be. If you want to help our investigating, doing a git-bisect and finding which commit causes the memory jump would be of great help.

**Comment by alanj853** [comment]
Using git bisect, I found that this is commit where the erlang VM's memory makes a jump: https://github.com/erlang/otp/pull/6827

**Comment by garazdawi** [comment]
Nice! That commit explains the memory growth nicely. In erts we preallocate a huge array with one element for each potential process (the [`process_limit`](https://www.erlang.org/doc/apps/erts/erlang#system_info_process_limit)). As the limit is rather large, it becomes quite a big array and that PR updates the table use 8 bytes for each process instead of 4, essentially doubling it which is the main part of the difference you are seeing. The good news is that this is just a static memory increase and as a system starts doing actual work, 2 MB is not all that much.

If you want that memory overhead to decrease, you need to set a lower `process_limit`. For example `erl +P 4096`. Or you can run the 32-bit emulator.

Coincidentally you would have seen a similar memory jump when going from 26 to 27 as the default `process_limit` was raised in 27.
