### ISSUE TITLE
dialyzer: `-Woverlapping_contract` command line option is broken

### ISSUE THREAD

**Issue by ilya-klyuchnikov** [erlang/otp#8821]
**Describe the bug**
Dialyzer CLI:

```
dialyzer -h
...
  -Woverlapping_contract ***
     Warn about overloaded functions whose specification include types that
overlap.
...
```

But running dialyzer with this option produces an error:

```
dialyzer  -Woverlapping_contract dial.erl                                       

dialyzer: dialyzer: invalid argument for warnings: overlapping_contract is not one of the choices
```

**To Reproduce**
```
dialyzer  -Woverlapping_contract any_module.erl
```

**Expected behavior**

**Affected versions**
OTP 26, OTP 27

**Additional context**
When putting the option into the config file `dialyzer.config`, it's turned on correctly.

```
{warnings, [overlapping_contract]}.
```

**Comment by TD5** [comment]
Looks like maybe it was missed during the migration to `argparse`?

See: https://github.com/erlang/otp/blob/master/lib/dialyzer/src/dialyzer_cl_parse.erl#L139

**Comment by kikofernandez** [comment]
PR #8986 should have fixed this
