### ISSUE TITLE
The same variable can have "multiple values" in edge cases in fun expressions or: inconsistent shadowing

### ISSUE THREAD

**Issue by ilya-klyuchnikov** [erlang/otp#8828]
**Describe the bug**

```erlang
-module(test_vars).
-export([foo/1]).

foo(Arg) ->
    fun(#{Arg := _}, Arg) -> Arg end.
```

In shell:

```
1> (test_vars:foo(a))(#{a => b}, c).
c
```

The fact that evaluation of the function call succeded means that the first `Arg` was taken from the outer context and the second `Arg` is shadowed, - thus effectively meaning that the same variable has two different values in the same scope.

**Expected behavior**

Either the call crashes or cannot compile.

**Affected versions**
OTP 26, 27

**Comment by Maria-12648430** [comment]
I don't see this as a bug. It is counter-intuitive or surprising, but not wrong.

What you get from the outer function `foo(Arg)` when you call it with argument `(a)` is a function which reads `fun(#{a := _}, Arg) -> Arg end`, where `Arg` now shadows the "outer" `Arg`, and if you call that function with arguments `(#{a := b}, c)`, you get `c` back. Put differently, you don't have the _same_ variable with different values, you have _two_ different variables which happen to have the same _name_, the inner shadowing the outer.

Put differently again, you couldn't define the inner function like this on its own, like `bar(#{Arg := _}, Arg) -> Arg.` Map keys must be fully ground terms in matching, and `Arg` is not. However, when written as an inner function like in your example, `Arg` _is_ a fully ground term, in the context. The other `Arg` is a function parameter for that inner function, which happens to shadow the outer.

**Comment by RaimoNiskanen** [comment]
You _do_ get a warning that the second `Arg` in the `fun` definition shadows the outer `Arg`, while the first `Arg` (map key) doesn't cause such a warning.

Not an error nor a crash, but at least a warning.

**Comment by bjorng** [comment]
I agree with previous comments that this is not a bug. When matching a map, a variable used as a key must be used be bound in the enclosing environment. Therefore, this function cause a compilation error:
```
foo(#{Arg := _}, Arg) -> Arg.
```

Here is the error:

```
t.erl:5:7: variable 'Arg' is unbound
%    5| foo(#{Arg := _}, Arg) -> Arg.
%     |       ^
```

So as @Maria-12648430, there are two unrelated `Arg` vars in your example.
