### ISSUE TITLE
verify_fun/3 receive cert as binary instead of OTPCertificate record

### ISSUE THREAD

**Issue by benbro** [erlang/otp#8832]
**Describe the bug**
public_key.erl calls pubkey_cert:apply_fun/5 in two places.
[Line 1713](https://github.com/erlang/otp/blob/master/lib/public_key/src/public_key.erl#L1713):
```erlang
try pubkey_cert:apply_fun(VerifyFun, Cert#cert.otp, Cert#cert.der, Reason, Userstat0) of
```
[Line 2422](https://github.com/erlang/otp/blob/master/lib/public_key/src/public_key.erl#L2422):
```erlang
try pubkey_cert:apply_fun(VerifyFun, OtpCert, DerCert, Reason, UserState0) of
```
[pubkey_cert:apply_fun/5](https://github.com/erlang/otp/blob/master/lib/public_key/src/pubkey_cert.erl#L383) reverses the order of OtpCert and DerCert and calls the user supplied verify_fun with DerCert instead of OtpCert:
```erlang
apply_fun(Fun, DerCert, OtpCert, Result, UserState) ->
    if is_function(Fun, 4) ->
            Fun(OtpCert, DerCert, Result, UserState);
       is_function(Fun, 3) ->
            Fun(OtpCert, Result, UserState)
    end.
```

**Affected versions**
27.1

**Comment by IngelaAndin** [comment]
Well actual it called forma third place most of the time where the order is correct, but good catch we will fix.
