### ISSUE TITLE
Emulator path is terminated at the first sign of white space in erlc

### ISSUE THREAD

**Issue by starbelly** [erlang/otp#8845]
**Describe the bug**
`erlc` will fail to run if it resides in a path that contains spaces (i.e., `/foo/bar baz/erlc`). This is due to the [push_words](https://github.com/erlang/otp/blob/57dbdfe82c1aa55ecf6e4a6f6f758d98e84abd24/erts/etc/common/erlc.c#L474) function. 

A [fix](https://github.com/erlang/otp/pull/849) was sent up in 2015, yet was reverted in  f77436f337d83a9751dc84d53791500c7f99c92e a few months later, but without indication as to why. 

Per the PR above, it seems this is a problem in multiple programs shipped with OTP. 

**To Reproduce**

Install Erlang/OTP in a location with a parent directory that contains spaces 
such as `/tmp/foo bar/erlang_test` , then try to invoke erlc (i.e., `/tmp/foo bar/erlang_test/bin/erlc`)  , you should get an errno 2 exit. 

**Expected behavior**
erlc and friends can successfully be invoked without issue when residing in a path containing spaces (i.e., the path to the emulator is not lopped off the first sign of space). 

**Affected versions**
All versions of OTP post R13B 

**Additional context**

This bug was noticed and reported by @tsloughter on erlanger slack.

**Comment by garazdawi** [comment]
How odd! We test with a space (and unicode character) in the path for all our GH actions tests. Seems like for some reason that does not catch this problem. Will have to investigate.

**Comment by frazze-jobb** [comment]
Hmm, I ran the erlc_SUITE test suite and I found that it works there, it creats a script file that sets `ERLC_EMULATOR=erl`, when evaluating push_words, everything works fine. But erl might actually have the same path as erlc, but we rely on the OS way of finding the full path later.

If you set `ERLC_EMULATOR=/some path with space/erl`, then we get the same problem as before with push_words.

> ERLC_EMULATOR - The command for starting the emulator. Defaults to erl in the same directory as the erlc program itself, or, if it does not exist, erl in any of the directories specified in environment variable PATH

I think we should try to add this fix again

**Comment by frazze-jobb** [comment]
Thanks for reporting this, a fix has been merged and it will be available in 28

**Comment by dgud** [comment]
This actually makes erlc dialyzer ... NOT work when installed in default dir c:\Program Files\Erlang\.. 
It works when started from WSL (which we do when we test) but starting from Power Shell none of the programs work.

Reverting #8937 fixes it and makes it work. 

IMO  /tmp/foo bar/erlang_test/bin/erlc  shouldn't work without quotes or back quoted space,
it doesn't work in linux nor in windows. 

Testing with 24.2 (old solution) which was wrong according to reporter:

From wsl:
```
16:47:23 :/mnt/e/src/otp:  /mnt/c/Program\ Files/erl-24.2/bin/erlc.exe -d
starting compile server erl_compile_server__famgu
spawning erl for <no source>
16:57:14 :/mnt/e/src/otp:  "/mnt/c/Program Files/erl-24.2/bin"/erlc.exe -d
starting compile server erl_compile_server__famgu
spawning erl for <no source>
```

From powershell
```
PS C:\Program Files> c:\"Program Files"\erl-24.2\bin\erlc.exe -d
spawning erl for <no source>
PS C:\Program Files>
```

**Comment by dgud** [comment]
Ping @frazze-jobb @starbelly

**Comment by frazze-jobb** [comment]
Okey I tried it myself on linux (reverting the commit) building it and got error as reported here:

```
ERLC_EMULATOR="/tmp/hej svej/bin/erl" "/tmp/hej svej/bin/erlc" lib/stdlib/src/edlin_expand.erl
erlc: Error 2 executing '/tmp/hej'.
erlc: Error 2 executing '/tmp/hej'.
```
Escaped space or quotes doesnt make a difference. Omitting ERLC_EMULATOR will also fail

> IMO /tmp/foo bar/erlang_test/bin/erlc shouldn't work without quotes or back quoted space,
> it doesn't work in linux nor in windows.

Having none of them will never work and the commit never did something about that.

Why it works on powershell I dont know and would require investigation.
Or I need some reproduction instructions on linux

**Comment by dgud** [comment]
It fails because on windows it is already quoted so it becomes double quoted.

```
PS C:\Users\daniel> erlc
erlc: Error executing '"\"c:\program files\erlang otp\erts-16.2\bin\erl.exe\""': 5
```

**Comment by frazze-jobb** [comment]
This should now be working again
