### ISSUE TITLE
Working with ERLANG on a windows machine with IPv6 only yields an error message

### ISSUE THREAD

**Issue by c0di11a** [erlang/otp#8848]
**Describe the bug**
Using latest Erlang release 27.1 yields an error. I believe that this may cause a later issue with RabbitMQ.

**To Reproduce**

1. Installed Windows 2019 VM with both IPv4 + IPv6
2. Installed erlang, e.g. version 27.1
3. I ran netsh Ipv4 interface uninstall to remove IPv4
4. I ran erl.exe and I get an error message
```
=ERROR MSG==== 938556505 ===
Failed create 'dummy' socket:
   eafnosupport (10047)
=ERROR MSG==== 938559987 ===
Failed initiating I/O backendErlang/OTP 27 [erts-15.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [jit:ns]

Eshell V15.1 (press Ctrl+G to abort, type help(). for help)
1>
```

I have also tried the next mitigations
1. run `erl.exe -proto_dist inet6_tcp`
2. add variables to .inetrc
```
{inet6, true}.
{tcp, inet6_tcp}
```
3. adding the next variables to .inetrc was not parsed correctly
```
{inet_default_bind_address, {0,0,0,0,0,0,0,0}}.
{inet_default_connect_options, [inet6]}.
```

**Expected behavior**
I expected this to be smooth without errors

**Affected versions**
tested with 26.x and 27.1

**Additional context**
Add any other context about the problem here. If you wish to attach Erlang code you can either write it directly in the post using [code tags](https://guides.github.com/features/mastering-markdown/), create a [gist](https://gist.github.com), or attach it as a zip file to this post.

**Comment by c0di11a** [comment]
Some investigation lead to `esaio_init` which seems to rely on IPv4 interface at `ctrl.dummy = sock_open(AF_INET, SOCK_STREAM, IPPROTO_TCP);`

**Comment by bmk** [comment]
Yes, I discovered same.
I have (just) created a PR for this: https://github.com/erlang/otp/pull/8857
It is currently building.
Since we do *not* have a IPv6-only machine to test on, could you give it a try?

**Comment by c0di11a** [comment]
Sure. I also described how I disabled IPv4 if it helps

**Comment by bmk** [comment]
A patch for this has been release with 27.1.1
A patch for 26 will be released at a later date.
