### ISSUE TITLE
Jinterface: OtpErlangBinary conversion from String includes garbage data

### ISSUE THREAD

**Issue by louiscb** [erlang/otp#8865]
**Describe the bug**

When passing a string into the constructor of `OtpErlangBinary` the string value is prepended with garbage data. E.g:

```
new OtpErlangBinary("asdf");
```

**To Reproduce**

In this test I created here: https://github.com/louiscb/jinterface-binary-bug/blob/main/src/test/java/org/example/MainTest.java

**Expected behavior**

I expect that the string that is provided to the OtpErlangBinary remains the same. However this is the output of running the test when the string `asdf` is provided

When passing a String as a byte array this issue is avoided.

```
org.opentest4j.AssertionFailedError: 
Expected :asdf
Actual   :���t�asdf
```

**Affected versions**

OTP 25

**Comment by jhogberg** [comment]
Thanks for your report! This behaves as documented: when passed an arbitrary Java object, it'll create a binary with its serialized representation.

```java
    /**
     * Create a binary from an arbitrary Java Object. The object must implement
     * java.io.Serializable or java.io.Externalizable.
     *
     * @param o
     *            the object to serialize and create this binary from.
     */
    public OtpErlangBinary(final Object o) {
        super(o);
    }
```
