### ISSUE TITLE
The behavior of re:split/3 trim option is not same as perl split

### ISSUE THREAD

**Issue by shionryuu** [erlang/otp#8868]
**Describe the bug**

[erlang re:split/3](https://www.erlang.org/doc/apps/stdlib/re.html#split/3)

> trim - Specifies that empty parts at the end of the result list are to be disregarded. The same as specifying {parts,0}. This corresponds to the default behavior of the split built-in function in Perl.

```erlang
1> re:split("Chinese,Japanese,Korean,", ",", [trim]).
[<<"Chinese">>,<<"Japanese">>,<<"Korean">>]
2> re:split("", ",", [trim]).
[<<>>]
```

[perl split](https://perldoc.perl.org/functions/split)

> If LIMIT is omitted (or, equivalently, zero), then it is usually treated as if it were instead negative but with the exception that trailing empty fields are stripped (empty leading fields are always preserved); if all fields are empty, then all fields are considered to be trailing (and are thus stripped in this case).

```perl
my @cjk = split(/,/, "Chinese,Japanese,Korean,");
printf("%d\n", scalar @cjk); # len = 3

my @cjk = split(/,/, "");
printf("%d\n", scalar @cjk); # len = 0
```

**Expected behavior**

`re:split("", ",", [trim])` should return `[]`, or update document

**Affected versions**

OTP-27

**Comment by Maria-12648430** [comment]
It is worth noting that `binary:split/3` works as expected for the equivalent case:
```erlang
1> binary:split(<<>>, <<",">>, [trim, global]).
[]
```
