### ISSUE TITLE
Incorrect spec for json:format/3

### ISSUE THREAD

**Issue by isvilen** [erlang/otp#8880]
**Describe the bug**
`json:format/3` has spec `-spec format(Term :: encode_value(), Encoder::formatter(), Options :: map()) -> iodata().`,
but this causes dialyzer errors because first argument `Term` can be any user specific type supported by `Encoder` function.

**Expected behavior**
Spec for `json:format/3`  to be  `-spec format(Term :: dynamic(), Encoder::formatter(), Options :: map()) -> iodata().`.

**Affected versions**
27.1.

**Comment by dgud** [comment]
Fix merged, will be in next patch release.
