### ISSUE TITLE
Dialyzer's `-Wmissing_return` fails to detect incorrect nested types 

### ISSUE THREAD

**Issue by sabiwara** [erlang/otp#8935]
**Describe the bug**

`-Wmissing_return` is performing only a superficial check on container types such as tuples or maps, and is happy as long as:
- one clause exactly matches the spec
- other clauses superficially match the spec

I'm not sure if this is a bug or a known limitation of how `missing_return` is implemented.

**To Reproduce**

#### With tuples:

```erlang
-module(foo).
-export([foo/1]).

-spec foo(binary) -> {ok, integer()}.
foo(<<>>) -> {ok, 0};        % as long as one branch matches
foo(_) -> {ok, unexpected}.  % and other branches have the {ok, _} shape
```

Returning a wrong-sized tuple `{ok, 0, 1}`, or a different leading atom `{error, 1}` gets caught though:

```erlang
foo.erl:4:2: The success typing for foo:foo/1 implies that the function might also return
          {'error', 1} but the specification return is
          {'ok', integer()}
```

#### With maps:

```erlang
-spec foo(binary) -> #{bar := integer()}.
foo(<<>>) -> #{bar => 2};
foo(_) -> #{unknown => <<"doesn't matter">>}.
```

Any map is accepted in the second clause, but other terms are properly caught:

```erlang
foo.erl:4:2: The success typing for foo:foo/1 implies that the function might also return
          'not_a_map' but the specification return is
          #{'bar' := integer()}
```

**Expected behavior**

```erlang
foo.erl:4:2: The success typing for foo:foo/1 implies that the function might also return
          {'ok', 'unexpected'} but the specification return is
          {'ok', integer()}
```

```erlang
foo.erl:4:2: The success typing for foo:foo/1 implies that the function might also return
          #{'unknown' :=<<_:112>>} but the specification return is
          #{'bar' := integer()}
```

**Affected versions**

Still present on 27.1

**Additional context**

Initially reported on the [Elixir Forum](https://elixirforum.com/t/dialxyr-not-catching-error-in-second-function-of-pattern-matching/66696)

**Comment by jhogberg** [comment]
This is a known limitation, `extra_return` and `missing_return` are best-effort and won't catch much. :-/
