### ISSUE TITLE
Defining a fun for a BIF fails in the shell with `undef`

### ISSUE THREAD

**Issue by robertoaloi** [erlang/otp#8963]
**Describe the bug**
Defining a `fun` for a BIF in the shell fails with `undef` error.

**To Reproduce**
```
1> fun list_to_binary/1.
** exception error: undefined function erl_eval:list_to_binary/1
```

**Expected behavior**
The result should be equivalent to:
```
2> fun erlang:list_to_binary/1.
fun erlang:list_to_binary/1
```

**Affected versions**
OTP 27

**Additional context**
The problem most likely resides [here](https://github.com/erlang/otp/blob/fb51687ab57514512f84e22022788e263b72d19f/lib/stdlib/src/erl_eval.erl#L493). We could check whether the input function is a BIF by using `erl_internal:bif/2` and, in the positive case, use `erlang` as the module.
This also affects the Erlang interpreter `int`.

**Comment by bjorng** [comment]
Thanks for reporting this issue. In the linked pull request, I made sure that the `fun Name/Arity` will work for both auto-imported BIFs as well as for local functions defined in the shell.
