### ISSUE TITLE
An option to silence behaviour-related warnings

### ISSUE THREAD

**Issue by elbrujohalcon** [erlang/otp#8985]
**Is your feature request related to a problem? Please describe.**
I want to be able to compile a module like the following one with no warnings:

```erlang
-module(amazing).
-behaviour(gen_server).
```

Currently, if I try to compile it, I get…

```erlang
   ┌─ amazing.erl:
   │
 2 │  -behaviour gen_server.
   │   ╰── Warning: undefined callback function handle_call/3 (behaviour 'gen_server')

   ┌─ amazing.erl:
   │
 2 │  -behaviour gen_server.
   │   ╰── Warning: undefined callback function handle_cast/2 (behaviour 'gen_server')

   ┌─ amazing.erl:
   │
 2 │  -behaviour gen_server.
   │   ╰── Warning: undefined callback function init/1 (behaviour 'gen_server')
```

Which is expected and fine, but in the same way that we have options to disable other warnings (e.g. `nowarn_unused_function`, `nowarn_keywords`, `nowarn_update_literal`, etc.), I would like to have an option to avoid warnings like the ones above.

**Describe the solution you'd like**
I would like the addition of the following compiler options:
* `nowarn_conflicting_behaviours`
* `nowarn_undefined_behaviour_func`
* `nowarn_undefined_behaviour`
* `nowarn_undefined_behaviour_callbacks`
* `nowarn_ill_defined_behaviour_callbacks`
* `nowarn_ill_defined_optional_callbacks`
* `nowarn_behaviour_info`
* `nowarn_redefine_optional_callback`
* `nowarn_undefined_callback`

**Describe alternatives you've considered**
I tried adding `-compile([no_lint]).` to my module, but the warnings were emitted anyway.

**Additional context**
This is the source of the necessity: https://github.com/inaka/elvis_core/pull/367#discussion_r1814971880

**Comment by bjorng** [comment]
I've added the six first of the suggested options in the linked pull request. The last three refers to compiler errors. This will be included in Erlang/OTP 28.
