### ISSUE TITLE
public_key:pem_entry_decode throws an error decoding EDDSA (ed25519 and ed448) keys

### ISSUE THREAD

**Issue by neelima32** [erlang/otp#9009]
**Describe the bug**
`public_key:pem_entry_decode` throws an error while decoding Ed448/Ed25519 public keys.

```
public_key:pem_entry_decode(Entry).
** exception error: no function clause matching public_key:der_decode('EcpkParameters',asn1_NOVALUE) (public_key.erl, line 555)
     in function  public_key:pem_entry_decode/1 (public_key.erl, line 424)
```
when `Entry` contains a valid `SubjectPublicKeyInfo` for an `ed25519`/`ed448` public key.
These entries don't contain `EcpkParameters` Params (asn1_NOVALUE).

**To Reproduce**
`openssl genpkey -out private-key.pem -algorithm ed25519`
`openssl pkey -in private-key.pem -pubout -out public-key.pem`
public-key.pem contains:
```
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAXtuo/Tk+JFHUis9Nfa74SVxVFb7H+u71Fws6Vt/c+0U=
-----END PUBLIC KEY-----
```

```
> [Entry] = public_key:pem_decode(list_to_binary("-----BEGIN PUBLIC KEY-----
   MCowBQYDK2VwAyEAXtuo/Tk+JFHUis9Nfa74SVxVFb7H+u71Fws6Vt/c+0U=
   -----END PUBLIC KEY-----")).
[{'SubjectPublicKeyInfo',<<48,42,48,5,6,3,43,101,112,3,33,
                           0,94,219,168,253,57,62,36,81,
                           212,138,207,77,125,174,...>>,
                         not_encrypted}]
                         
> public_key:pem_entry_decode(Entry).
** exception error: no function clause matching public_key:der_decode('EcpkParameters',asn1_NOVALUE) (public_key.erl, line 555)
     in function  public_key:pem_entry_decode/1 (public_key.erl, line 424)                        
```

Decoding the SPKI DER in Entry:
```
> {_, Der, _} = Entry.
{'SubjectPublicKeyInfo',<<48,42,48,5,6,3,43,101,112,3,33,
                          0,94,219,168,253,57,62,36,81,
                          212,138,207,77,125,174,248,...>>,
                        not_encrypted}
> rp(public_key:der_decode('SubjectPublicKeyInfo', Der)).
{'SubjectPublicKeyInfo',{'AlgorithmIdentifier',{1,3,101,112},
                                               asn1_NOVALUE},
                        <<94,219,168,253,57,62,36,81,212,138,207,77,125,174,248,
                          73,92,85,21,190,199,250,238,245,23,11,58,86,223,220,
                          251,69>>}
```

From https://github.com/erlang/otp/blob/cae99084a410345e4b1739fa758b8b7ae4fc70a8/lib/public_key/src/public_key.erl#L424-L426
EcpkParameters `Params` decoding fails since it is absent for Ed25519 and Ed448.

**Expected behavior**
`public_key:pem_entry_decode` should work for valid Ed25519 and Ed448 PEM entries.

**Affected versions**
The OTP versions that are affected by this bug.
Erlang/OTP 27
public_key version:
```
 {attributes,[{vsn,[47525788427688735812669362219934221828]},
              {app_vsn,"public_key-1.16.3"},
```
crypto version:
```
crypto:version().
"5.5.1"
```

**Additional context**
PEM encoding https://github.com/erlang/otp/blob/cae99084a410345e4b1739fa758b8b7ae4fc70a8/lib/public_key/src/public_key.erl#L489-L503 accounts for EcpkParameters being encoded only for `?'id-ecPublicKey'` (not for `?'id-Ed25519'` or `?'id-Ed448'`) entries. Decoding, however, expects valid EcpkParameters - even for Ed25519 and Ed448 entries.

**Comment by IngelaAndin** [comment]
Yes this looks like a bug. EDDSA does not have parameters they are always treated as named curves. We will fix it for an upcoming release.
