### ISSUE TITLE
setelement/3 causes unexpected mutation in nested tuples

### ISSUE THREAD

**Issue by intarga** [erlang/otp#9014]
**Describe the bug**
As I understand from [the documentation](https://www.erlang.org/doc/system/commoncaveats.html#setelement-3), setelement/3 can mutate tuples in place as an optimisation, but this optimisation should only be applied where it doesn't affect the behaviour of the function. I.e any mutation should never be visible to the user. 

However, when using setelement/3 on a tuple inside another tuple, it always mutates the tuple, changing the behaviour of the program.

**To Reproduce**
```erlang
-type state() :: {state, counter()}.
-type counter() :: {counter, integer()}.

-spec inc_counter(counter()) -> counter().
inc_counter(Counter) ->
    CounterValue = erlang:element(2, Counter),
    erlang:setelement(2, Counter, CounterValue + 1).

-spec wibble(state()) -> counter().
wibble(State) ->
    inc_counter(erlang:element(2, State)),
    inc_counter(erlang:element(2, State)),
    inc_counter(erlang:element(2, State)),
    inc_counter(erlang:element(2, State)),
    inc_counter(erlang:element(2, State)),

    Counter = erlang:element(2, State),
    CounterValue = erlang:element(2, Counter),
    case CounterValue >= 1 of
        true ->
            Counter;
        false ->
            NewCounter = inc_counter(Counter),
            NewState = erlang:setelement(2, State, NewCounter),
            wibble(NewState)
    end.

main() ->
    {counter, 5} = wibble({state, {counter, 0}}).
```

**Expected behavior**
This program should crash. The first 5 calls to `inc_counter` in `wibble` should do nothing, `wibble` should return `{counter, 1}` and main should crash.

Instead, the first 5 calls mutate the `counter` tuple in place, and `wibble` returns `{counter, 5}`

**Affected versions**
I've verified this with: 
- Erlang/OTP 27 from Homebrew on macOS 14.6.1, arm64

Someone else has corroborated it with:
- Erlang 27.1.2, NixOS unstable, x86_64, built from nixpkgs:60d0038

**Comment by frej** [comment]
This is definitely a bug. Running erlc with `+no_ssa_opt_destructive_update` for the affected module will allow you work around the bug until I have a fix available.

**Comment by inoas** [comment]
AFAIU elixir folks are also affected because they also wrap `erlang:element` and `erlang:setelement`:

https://github.com/elixir-lang/elixir/blob/v1.17.3/lib/elixir/lib/kernel.ex#L1886-L1903

**Comment by frej** [comment]
> AFAIU elixir folks are also affected because they also wrap erlang:element

The error only occurs when CSE does not unify all extracts from one tuple and the lifetime of the variables containing the extracted elements are non-overlapping. In that case the alias analysis fails to detect aliasing and then the destructive update pass thinks it is safe to modify the tuple in-place.

**Comment by frej** [comment]
#9024 contains a fix for this problem.
