### ISSUE TITLE
Define `ei` version number in `ei.h`

### ISSUE THREAD

**Issue by siiky** [erlang/otp#9026]
**Is your feature request related to a problem? Please describe.**

Related to [this thread](https://erlangforums.com/t/2740). When I learned of `ei` I tried my hand at implementing a wrapper in my go-to Scheme implementation, and noticed that `ei_get_type()` returns the `ei` version number for a full encoded Erlang term. However, because the version is not defined in `ei.h`, I have to guess that that is the version and not an unknown type.

**Describe the solution you'd like**

It appears to me that [`ERL_VERSION_MAGIC`](https://github.com/erlang/otp/blob/171fb25692e12b8b2988021ff80238bb7da9aa38/lib/erl_interface/src/misc/eiext.h#L27) could be moved to [somewhere around here](https://github.com/erlang/otp/blob/171fb25692e12b8b2988021ff80238bb7da9aa38/lib/erl_interface/include/ei.h#L165).

If this is totally intentional and there's a reason for the version not to be publicly defined (maybe I'm holding it wrong?), I would also like to know -- maybe the docs are lacking in some way in that case.

**Describe alternatives you've considered**

As a temporary workaround, I've defined the version number in the wrapper library. This is not ideal, in case the version changes, although it's also not worrying since the [last change](https://github.com/erlang/otp/blame/171fb25692e12b8b2988021ff80238bb7da9aa38/lib/erl_interface/src/misc/eiext.h#L27) was ~15 years ago ^^

**Comment by jhogberg** [comment]
I suspect that you're using it wrong, the first part of an encoded term is a version that must be decoded with `ei_decode_version` first.

That `ei_get_type` returns the first encountered byte is a bit of an accident, I think it should signal failure (-1) instead when encountering a type it does not recognize.

**Comment by siiky** [comment]
> I suspect that you're using it wrong

I wouldn't be surprised, and as long as I learn how to use it correctly, I don't mind. So my thought process previously was to `ei_get_type()` and then call the corresponding `ei_decode_*()`. I now realize that perhaps one should `ei_decode_version()` before any other `ei_get_type()`/`ei_decode_*()`. Is that the intended usage of the library?

**Comment by jhogberg** [comment]
> You're saying one should instead call `ei_decode_version()` before any other `ei_get_type()`/`ei_decode_*()`. Is that the intended usage of the library?

Yes.

**Comment by fregate** [comment]
Second this request about move protocol version (131) to some public header.

I have IPC between service on OS and Erlang application. I want to check protocol version (is it correct) in binary term to do appropriate error handling. And at this moment I can only use magic number like 131 and wait to announcement about version increment and change it manually in code.

**Comment by siiky** [comment]
@fregate from my understanding, as I commented and @jhogberg confirmed, you're supposed to call `ei_decode_version()` first of all. That function [checks](https://github.com/erlang/otp/blob/171fb25692e12b8b2988021ff80238bb7da9aa38/lib/erl_interface/src/decode/decode_version.c#L33) that the version is the expected (131 [as of now](https://github.com/erlang/otp/blob/171fb25692e12b8b2988021ff80238bb7da9aa38/lib/erl_interface/src/misc/eiext.h#L27)).

Isn't this what you're looking for?

**Comment by fregate** [comment]
Yes. And I received something in version field. At this moment it is 131. How I supposed to know is it right it incorrect magic number in general? 
If this will change sometimes, how I can check is it correct or not?
Or this is lack in documentation. Does decode_version returns -1 if version is not 131?

**Comment by siiky** [comment]
The function I linked to does exactly that...

```c
  if (v != ERL_VERSION_MAGIC)
    return -1;
```

**Comment by fregate** [comment]
Oh. Interesting design) ok. So I wouldn't check, just decode with version nullptr. 
Thanks!
