### ISSUE TITLE
"Internal consistency check failed - please report this bug."

### ISSUE THREAD

**Issue by drathier** [erlang/otp#9030]
**Describe the bug**
This hand-minified .core file:
```erlang
module 'binary.pattern.3'
	[ 'a'/1
	]
attributes
	[
	]

'a'/1 =
	fun (V) ->
		case V of
			<#{
				#<0>(1, 1, 'integer', ['unsigned', 'big'])
			}#> when 'true' -> 0
			<#{
				#<1>(1, 1, 'integer', ['unsigned', 'big'])
			}#> when 'true' -> 0
		end
end
```
when compiled like this:
```
erlc binary.pattern.3.core
```
gives me this output:
```
binary.pattern.3:1: function a/1+6:
  Internal consistency check failed - please report this bug.
  Instruction: {test,bs_start_match3,{f,0},1,[{x,0}],{x,0}}
  Error:       throws_exception:
```

Yes, that `throws_exception:` is the end of the output, there are no further lines. It seems to come from `erlang/27.1.2/lib/erlang/lib/compiler-8.5.2/src/beam_validator.erl`:
```
format_error({{_M,F,A},{I,Off,Desc}}) ->
    io_lib:format(
      "function ~p/~p+~p:~n"
      "  Internal consistency check failed - please report this bug.~n"
      "  Instruction: ~p~n"
      "  Error:       ~p:~n", [F,A,Off,I,Desc]);
```
Perhaps that last line should've read `[[F,A,Off,I,Desc]]`?

**Affected versions**
`Erlang/OTP 27 [erts-15.1.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit] [dtrace]`, I think 27.1.2?

**Question**
Am I doing something obviously wrong or unexpected? (Other than using .core files at all. that is). Would you have expected this file to compile ok? If not, why? :)

**Comment by jhogberg** [comment]
You haven't defined what happens when `V` doesn't match those patterns, so that's not valid code.

The error raised by the validator is also fine, aside from that trailing `:` which should have been omitted as there is no more information. `bs_start_match3` should never have a failure label of `0` as it cannot throw exceptions on failure.

**Comment by drathier** [comment]
Thanks for the quick reply! I minified it too far. My fallthrough branch looked like this, which indeed doesn't match all cases:
```
'true' when 'true' -> 
```
