### ISSUE TITLE
ssl: Also convey alert info in send operations?

### ISSUE THREAD

**Issue by essen** [erlang/otp#9051]
**Describe the bug**
As a followup to https://github.com/erlang/otp/pull/8823 the `send` function is also lacking alert information.

**To Reproduce**

With this module:

```
-module(delayed_tls_alert).

-export([run/1]).

run(Port) ->
    {ok,_} = application:ensure_all_started(ssl),
    Listener = start_server(Port),
    Res = connect_loop(Port),
    ssl:close(Listener),
    Res.

start_server(Port) ->
    case ssl:listen(Port, [{reuseaddr, true},
                           {log_level,none},
                           {verify, verify_peer},
                           {fail_if_no_peer_cert, true},
                           {keyfile, "server.key"},
                           {certfile, "server.crt"},
                           {cacertfile, "cacert.pem"},
                           {versions, ['tlsv1.3']}
                          ]
                   ) of
        {ok, Listener} ->
            spawn_link(fun() -> accept_loop(Listener) end),
            Listener;
        {error, eaddrinuse} ->
            timer:sleep(1_000),
            start_server(Port)
    end.

accept_loop(Listener) ->
    case ssl:transport_accept(Listener) of
        {ok, Socket} ->
            io:format("Server Handshake result:~p~n", [ssl:handshake(Socket)]),
            accept_loop(Listener);
        {error, closed} ->
            ok
    end.

connect_loop(Port) ->
    case ssl:connect("localhost", Port, [{verify,verify_none},{log_level,none}]) of
        {ok, Socket} ->
            io:format("Client successfully connected~n", []),
            send_loop(Socket);
        {error, _} ->
            timer:sleep(1_000),
            connect_loop(Port)
    end.

send_loop(Socket) ->
    SendResult = ssl:send(Socket, "Dead socket"),
    io:format("send result: ~w~n", [SendResult]),
    case SendResult of
        ok ->
            send_loop(Socket);
        {error, _} ->
            ssl:close(Socket),
			c:flush(),
            SendResult
    end.
```

We get:

```
$ erlc delayed_tls_alert.erl 
$ erl                       
Erlang/OTP 27 [erts-15.1.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Eshell V15.1.2 (press Ctrl+G to abort, type help(). for help)
1> delayed_tls_alert:run(4004).
Client successfully connected
send result: ok
...
send result: ok
Server Handshake result:{error,
                            {tls_alert,
                                {certificate_required,
                                    "TLS server: In state wait_cert at tls_handshake_1_3.erl:446 generated SERVER ALERT: Fatal - Certificate required\n certificate_required"}}}
send result: ok
send result: {error,closed}
Shell got {ssl_error,
              {sslsocket,
                  {gen_tcp,#Port<0.6>,tls_connection,undefined},
                  [<0.121.0>,<0.120.0>]},
              {tls_alert,
                  {certificate_required,
                      "TLS client: In state connection received SERVER ALERT: Fatal - Certificate required\n"}}}
{error,closed}
2> 
```

As you can see the TLS socket gets a closed error, but we don't know why, and the alert is in the message sent following that.

**Expected behavior**
The alert should be returned in the send error instead.

**Affected versions**
All?

**Additional context**
https://github.com/ninenines/gun/issues/341

**Comment by dgud** [comment]
I don't know if we want that, then we would slow down the send operation if it have to check everytime that everything is
ok, and also we can't make it async at all, as we have discussed to speed up the send operation.

**Comment by essen** [comment]
I don't think it needs to check every time, just perhaps when it is about to return `{error, closed}` it could figure out if it's because of an alert? So this would only be checked when there is an error.

**Comment by essen** [comment]
Of course if the send eventually becomes completely async this becomes moot.

**Comment by essen** [comment]
If no code change is required perhaps a documentation change is needed. The TLS alert info is documented, but I'm not sure the message itself is, and whether we are expected to handle it.

**Comment by IngelaAndin** [comment]
I do not think we want to do this. In your case you had the socket in active mode so the controlling process, in this case the shell, got the active error message which happens when the server concludes that the client did not send a certificate chain.  In TLS-1.3  client certificate verification happens after the connection is established and application data may already been sent.  It can also possibly happen much later with so called post authentication (although we did not fully implement this yet).  Also sender can be closed when socket is closed where as receiver process will be closed when all data received  has been delivered to user process. I  think it is the controlling process or the receiver that should be notified about the alert.

**Comment by essen** [comment]
Alright, thank you. Should the TLS alert error message [be better described here](https://www.erlang.org/doc/apps/ssl/ssl.html#t:active_msgs/0)? Since it's generally useful to know [the reason](https://www.erlang.org/doc/apps/ssl/ssl.html#t:tls_alert/0), users may want to catch and handle this one differently than generic `ssl_error` messages.

**Comment by IngelaAndin** [comment]
That sound like a good idea, I will put it on the todo list.  Suggestion are of course welcome.

**Comment by essen** [comment]
Not sure about modifying type specs like this (what will Dialyzer think of it?) but something like this?

```
diff --git a/lib/ssl/src/ssl.erl b/lib/ssl/src/ssl.erl
index 7043c040b1..9be8409437 100644
--- a/lib/ssl/src/ssl.erl
+++ b/lib/ssl/src/ssl.erl
@@ -258,11 +258,15 @@ An option that can be supplied to a TLS server.
 The type for the messages that are delivered to the owner of a
 TLS/DTLS socket in active mode.
 
+Applications may want to handle some of the TLS alerts that may be provided
+in the `ssl_error` message, such as certificate authentication failures.
+
 The `ssl_passive` message is sent only when the socket is in `{active, N}` mode
 and the counter has dropped to 0. It indicates that the socket has transitioned
 to passive (`{active, false}`) mode.
 """.
 -type active_msgs()              :: {ssl, sslsocket(), Data::binary() | list()} | {ssl_closed, sslsocket()} |
+                                    {ssl_error, sslsocket(), Alert::error_alert()} |
                                     {ssl_error, sslsocket(), Reason::any()} | {ssl_passive, sslsocket()}. % exported
 
 -doc(#{title => <<"Socket">>}).
```

I'll open a PR if this is roughly appropriate.

**Comment by IngelaAndin** [comment]
I think we should say something along the line of

"The ssl_error reason may convey an TLS protocol alert if such an event occurs after the connection has been established. The most common case case when this will happen is on the client side  when a TLS-1.3 server requests a client certificate and the sent certificate is not accepted by the server, as it will be verified after server sent its last handshake message. "

The Spec I think should be:

 -type active_msgs()              :: {ssl, sslsocket(), Data::binary() | list()} | {ssl_closed, sslsocket()} |
                                                {ssl_error, sslsocket(), Alert::error_alert() |  Reason ::any()} |
                                                 {ssl_passive, sslsocket()}. % exported

**Comment by essen** [comment]
Much better! Will send a PR shortly.

**Comment by essen** [comment]
I have opened https://github.com/erlang/otp/pull/9067 with the PR. I believe all the concerns in this ticket have been resolved so I am closing it. Thank you!
