### ISSUE TITLE
Man pages missing for OTP 27.1.2 at erlang.org/downloads and github releases

### ISSUE THREAD

**Issue by vlad-ngn** [erlang/otp#9107]
**Describe the bug**
Man pages for otp 27 only contains man1:

```
 $ tar -xf otp_doc_man_27.1.2.tar.gz 
 $ ls
man  otp_doc_man_27.1.2.tar.gz
 $ ls man/
man1
 $
 $ du -h otp_doc_man_27.1.2.tar.gz 
48K	otp_doc_man_27.1.2.tar.gz
```
otp 26:

```
 $ tar -xf otp_doc_man_26.2.5.5.tar.gz 
 $ ls 
man  otp_doc_man_26.2.5.5.tar.gz
 $ ls man
man1  man3  man4  man6  man7
$ du -h otp_doc_man_26.2.5.5.tar.gz 
1,7M	otp_doc_man_26.2.5.5.tar.gz
``` 

**To Reproduce**
* Go to https://www.erlang.org/downloads and click arrow right to "View documentation" and then click "Download Man Pages"
* or go to https://github.com/erlang/otp/releases/tag/OTP-27.1.2 and click on otp_doc_man_27.1.2.tar.gz 

**Expected behavior**
Man pages archive contains all man pages.

**Affected versions**
Looks like all 27 versions are affected

**Comment by garazdawi** [comment]
As of Erlang/OTP 27 only man1 is be created for Erlang. The ability to generate man files for modules was lost in the migration to use `ex_doc` as the documentation tool. You are not alone in missing them, there is a dicussion in the [ex_doc](https://github.com/elixir-lang/ex_doc/issues/1962) repo about how to bring them back.

**Comment by zuiderkwast** [comment]
@garazdawi I'm not sure why you closed this issue. When the support is added in ex_doc, I would like to add the `3erl` man pages back. Not in OTP 27.1.2 obviously, but in a future version.

**Comment by zuiderkwast** [comment]
Is there an ope issue for tracking the re-introduction of module man pages? I can see progress here: https://github.com/elixir-lang/ex_doc/pull/1976

Btw, the OTP 26 man pages, the section name on my system was `3erl` (e.g. `argparse(3erl)`) but the header in the man pages say section 3, e.g. `argparse(3)`. Was that difference intentional?

**Comment by garazdawi** [comment]
> Is there an open issue for tracking the re-introduction of module man pages? I can see progress here: https://github.com/elixir-lang/ex_doc/pull/1976

No. I did a quick and dirty 15 min hack just to see how it would look like. I don't plan on doing any more work around this. So the ball is all yours, if you want an issue to track/discuss things, feel free to open one on https://github.com/erlang/otp.

> Btw, in the OTP 26 man pages, the section name on my system was 3erl (e.g. argparse(3erl)) but the header in the man pages say section 3, e.g. argparse(3). Was that difference intentional?

I think that might be something that your OS (debian/ubuntu maybe?) does and not something that we do. If you download the man pages from https://www.erlang.org/patches/otp-26.2.5.6 there are no references to `3erl` that I can find.
