### ISSUE TITLE
Dialyzer gets stuck

### ISSUE THREAD

**Issue by michallepicki** [erlang/otp#9135]
**Describe the bug**
👋🏻 Hi! I have a [repo](https://github.com/michallepicki/elixir-lang-dialyzer-runs) that runs Dialyzer on the Elixir source code, and for fun today I tried to run it using Erlang from the master branch. The PLT file was created, but after that unfortunately the analysis is taking wayyy too long (10+ minutes instead of ~1 minute), to the point that I think it may be stuck.

**To Reproduce**
```
git clone git@github.com:michallepicki/elixir-lang-dialyzer-runs.git
cd elixir-lang-dialyzer-runs
git clone git@github.com:elixir-lang/elixir.git
cd elixir
make compile
cd ../
elixir/bin/elixir dialyzer.exs
```
Then the PLT file is built, but then the Dialyzer analysis starts and never completes

**Expected behavior**
After the successful analysis the Elixir script prints some info about filtered out non-issues / potential issues, you can see sample output when you expand the "Check Elixir" step at https://github.com/michallepicki/elixir-lang-dialyzer-runs/actions/runs/12124851744/job/33803476539

**Affected versions**
I tried the current Erlang master branch, compiled by hexpm/bob for Ubuntu 22.04, I believe it was from the commit https://github.com/erlang/otp/commit/3b405bd4ab356beedfb615ae2b5d91629de9896d

**Additional context**
I thought it may be useful to do this test since there have been some changes to Dialyzer recently, related to the addition of nominal types. ~But the issue could be completely unrelated as well, since I don't know and haven't tried it whether this process would work before that addition 🤔~ edit: I have confirmed that the `dialyzer.exs` script finishes (including building the PLT) under 3 minutes on my machine on Erlang from https://github.com/erlang/otp/commit/b5021ccd64e1d8896b147fbba1abe7121d027af4 but it gets stuck for 10+ minutes on my machine on Erlang from https://github.com/erlang/otp/commit/124687f2eaaf6d951111960284e5904e4fa03ab6

**Comment by jhogberg** [comment]
Thanks for your report! It does take forever, and it turns out that there are far too many legitimate warnings now that opaques work as intended: the inlining done by the Elixir compiler discards type information on opaques, which then results in violations when trying to pass the now non-opaque value around.

We're looking at ways to fix that together with @josevalim, and are also going to optimize the warning passes as some of them are a bit too naive at the moment.

**Comment by josevalim** [comment]
Elixir inlining (via macros and module attributes) has historically struggled with `opaque`, so I believe Elixir should altogether move away from opaques into nominal. According to @jhogberg, passing the `no_opaque` flag will give us exactly that semantic in Erlang/OTP 28, so perhaps our recommendation is to use `no_opaque` when dyalyzing Elixir codebases?

**Comment by michallepicki** [comment]
Three years ago I submitted a different proposal which would have also lowered the amount of issues reported by Dialyzer that come from opaqueness violations, linking it here since I think it's slightly related: https://github.com/erlang/otp/issues/5503

**Comment by michallepicki** [comment]
> perhaps our recommendation is to use no_opaque when dyalyzing Elixir codebases?

Unfortunately it doesn't seem to help here, if I add `:no_opaque` [here](https://github.com/michallepicki/elixir-lang-dialyzer-runs/blob/3a13d67a75f27073a4a80c5773243e64d8accbdf/dialyzer.exs#L55) the analysis still takes a very long time

**Comment by jhogberg** [comment]
> Some time ago I submitted a different issue with a proposal which I think would lower the amount of issues reported by Dialyzer that come from opaqueness violations, linking it here since I think it's slightly related: #5503

That's how they work in OTP 28, it was one of the design goals. :-)

> > perhaps our recommendation is to use no_opaque when dyalyzing Elixir codebases?
> 
> Unfortunately it doesn't seem to help here, if I add `:no_opaque` [here](https://github.com/michallepicki/elixir-lang-dialyzer-runs/blob/3a13d67a75f27073a4a80c5773243e64d8accbdf/dialyzer.exs#L55) the analysis still takes a very long time

`no_opaque` will affect the reported warnings, not how long the analysis takes. We're going to make things faster in this area regardless of whether the warning is on or not.
