### ISSUE TITLE
unable to download erlang on ubuntu 20 

### ISSUE THREAD

**Issue by kishorekumar-anchala** [erlang/otp#9216]
**Describe the bug**
We're unable to download/install erlang on ubuntu , getting below error

```
/runner-images-ci/runner-images-ci/images/ubuntu/templates/../scripts/build/install-erlang.sh
==> azure-arm.build_image: gpg: no valid OpenPGP data found.
```

**To Reproduce**
N/A

**Expected behavior**
it should download and install.

**Affected versions**
Ubuntu 20 

**Additional context**

We're unable to download/install erlang on ubuntu , getting below error

```
/runner-images-ci/runner-images-ci/images/ubuntu/templates/../scripts/build/install-erlang.sh
==> azure-arm.build_image: gpg: no valid OpenPGP data found.
```

**Comment by rickard-green** [comment]
This install script is not provided by us. You need to contact whoever is providing you with that script.
